### ISSUE TITLE
License - Plumbing License - Additional Applicant

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1]
The system is requiring additional applicants to have a capacity = contractor.  

System should allow user to select any capacity type for additional applicant.

**Comment by goggansd** [comment]
This needs to be a discussion between the lead SME(s) and Dan Grendon, as the code currently allows any applicant capacity, but requires ONE applicant to have a capacity of CONTRACT (CONTRACTOR)--UNLESS the COMPLETENESS CHECK review has a result of either COMPLETE or RESUBMIT. Unfortunately, the COMPLETENESS CHECK review currently has RESUBMIT and APPROVED ( not COMPLETE) as valid result codes. Shannon and Juanita want to remove the check for applicant capacity entirely and intend to address it with Ashlye B, but the end result of that discussion needs to be run past Dan Grendon, as he designed this to work a specific way, and may have additional insight as to whether any change would impact the design.

**Comment by goggansd** [comment]
Dan Grendon has fixed this by removing the COMPLETENESS CHECK result check and replacing the check for a capacity of CONTRACT with a check to see that the count of additional applicants is >=1

**Comment by dhenry-KCI** [comment]
Confirmed fixed - ab 2.13.19
