### ISSUE TITLE
License - Distributor Report - DISREP Review Result Codes

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#10]
When resulting the DISREP Review within the Distributor Monthly Report application type (within the License Module), there are too many options available for the review result codes. The review result codes should be limited to the standard: Approved, Denied, Resubmit, and N/A.

Steps to Replicate:
1. Click Reviews Tab
2. Click Check Box next to Renewal Review type.
3. Click Record Results
4. Click the pop up icon on the Result field.

![image](https://user-images.githubusercontent.com/31770504/52363040-dea8ef00-2a0f-11e9-8dc9-6dc67ec5b4ef.png)

**Comment by ABonomo21** [comment]
fixed
