### ISSUE TITLE
Building - Resuse - Pole Building

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#100]
THe system should not generate a DUSWM review for Pole Buildings

AP237170
Logged by M. Coffman

![polebuilding](https://user-images.githubusercontent.com/4129185/53142510-3001c400-3562-11e9-943c-6d82db855051.png)

**Comment by imazlout** [comment]
Duplicate of #36

**Comment by ABonomo21** [comment]
fixed-AW-(this was not a duplicate of #36)
![image](https://user-images.githubusercontent.com/47611580/55736383-30123200-59f1-11e9-888d-d9f162b9dec0.png)
