### ISSUE TITLE
ips-preprod-planning-plat-correction

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1000]
agency is denied on first review, then went to Mylar review milestone.  Skipped resubmittal required and skipped mylar review fees.
![image](https://user-images.githubusercontent.com/4129185/58272308-3b7cab00-7d5c-11e9-90ee-d53eed30d4f5.png)

make exact copy of same AP in test.  Here the same agency is denied and it stage progressed to finalized.
![image](https://user-images.githubusercontent.com/4129185/58272524-bd6cd400-7d5c-11e9-9eba-d7e3850140ef.png)

MW

**Comment by megisys** [comment]
Ready for Retest.. Denied Removed

**Comment by dhenry-KCI** [comment]
ok per PL244562

MW
