### ISSUE TITLE
IPS- Tank- Town Review Options

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1001]
Town review options should not have complete, eplans, or internal 
denied should only be an option for system admin 
![image](https://user-images.githubusercontent.com/47611580/58272788-46840b00-7d5d-11e9-9db1-1a596e17de31.png)

This is in the test environment

**Comment by megisys** [comment]
Filter Denied.  Denied is not done this way

**Comment by megisys** [comment]
Denied will be done via logs, we can finish this out later

**Comment by imazlout** [comment]
Ready for retest

**Comment by ABonomo21** [comment]
confirmed corrected
