### ISSUE TITLE
ips-preprod-planning-unable to add attachments

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1002]
was unable to add attachments in verify and yard mod ap types.  Replicated application in Test and was able to add attachments.

![image](https://user-images.githubusercontent.com/4129185/58278143-4e49ac80-7d69-11e9-80db-0c7819e48556.png)

MW

**Comment by megisys** [comment]
Make Sure Catalog is always ATTACHMENTS. This was attempted against Correspondence

**Comment by dhenry-KCI** [comment]
fixed per VP244547

MW
