### ISSUE TITLE
ips-preprod-planning-FRO-details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1003]
some details didnt come over from V7
-subdivision code
-acres in hansen filled in as sqft in preprod

![image](https://user-images.githubusercontent.com/4129185/58278646-81407000-7d6a-11e9-80f7-e78ce19f3ee1.png)

![image](https://user-images.githubusercontent.com/4129185/58278691-91584f80-7d6a-11e9-8d57-1279b0a6c353.png)

mw

**Comment by JuanitaMiles** [comment]
These Data Issues persist in both TEST and PREPROD. _(See screenshot of TEST environment below)_. Changing labels to 'Data Issue' only.

![image](https://user-images.githubusercontent.com/31770504/58500553-6bf38900-8150-11e9-88bf-9ba0d97c4cf6.png)

**Comment by dhenry-KCI** [comment]
Fixed per AP2195, AM & GH
