### ISSUE TITLE
License - Liquor License - PRELIM Review Resubmit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1006]
When a Completeness Check review has been resulted with Resubmit at least once, the application does not stop in the Preliminary Review Resubmit milestone when you result the PRELIM review with Resubmit. 

If the Completeness Check review is resulted with Approved on the first cycle, the application will move to Preliminary Review Resubmit if the PRELIM review is resulted with Resubmit.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58643731-daaa2100-82cd-11e9-80ac-dc399b873bdc.png)

![image](https://user-images.githubusercontent.com/31770504/58643753-e72e7980-82cd-11e9-888b-60748c150d25.png)

![image](https://user-images.githubusercontent.com/31770504/58643774-f44b6880-82cd-11e9-842e-07790c928aaa.png)

**Comment by megisys** [comment]
This needs to be done based on the log being added after the process state milestone date. See Building

**Comment by calequin** [comment]
fixed in preprod and test

**Comment by JuanitaMiles** [comment]
Fixed
