### ISSUE TITLE
License - Liquor License - PRELIM Review Resubmit Applicant Actions

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1007]
If an application does progress to Preliminary Review Resubmit (due to a 1st cycle COMPLETE approval, then a PRELIM resubmittal: see issue #1006 ), there is no 'Applicant Actions' detail page to complete the resubmittal action.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58644212-d16d8400-82ce-11e9-84cb-bebd7464ca71.png)

![image](https://user-images.githubusercontent.com/31770504/58644230-d9c5bf00-82ce-11e9-8028-08bea66cf70b.png)

**Comment by calequin** [comment]
fixed in preprod and test

**Comment by JuanitaMiles** [comment]
Fixed
