### ISSUE TITLE
License - Liquor License - USE OCCUPY Review Result Codes

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1008]
The review result codes for the USE OCCUPY review are not filtered properly. They should match that of the PLANZONE and HEALTH reviews on this AP Type.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58644453-493bae80-82cf-11e9-8380-41c1a633a869.png)

![image](https://user-images.githubusercontent.com/31770504/58644462-4e006280-82cf-11e9-9afe-494eff66cdd6.png)

**Comment by calequin** [comment]
fixed in preprod and test

**Comment by JuanitaMiles** [comment]
fixed
