### ISSUE TITLE
License - Liquor License - Under Review Result Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1009]
Completing the Under Review reviews with varying results produces different workflow/milestone progression. This issue appears to be impacted by previous reviews being resulted with Resubmit. Two examples of what I'm seeing are below.

I have confirmed this issue occurs in both TEST and PreProd environments.

Example # 1: Approving USE OCCUPY and Resubmitting PLANZONE and HEALTH move the application to Awaiting Resubmittal. Previous COMPLETE and PRELIM reviews were approved at the first cycle.
![image](https://user-images.githubusercontent.com/31770504/58644985-6b81fc00-82d0-11e9-969b-3e24d2ab22ac.png)

Example # 2: Approving PLANZONE and HEALTH and Resubmitting USE OCCUPY skips the Awaiting Resubmittal milestone and goes straight back to Under Review and generates the second cycle the resubmitted review. Previous COMPLETE and PRELIM reviews were resubmitted.
![image](https://user-images.githubusercontent.com/31770504/58645112-b13ec480-82d0-11e9-8247-ef637e78e7cf.png)

![image](https://user-images.githubusercontent.com/31770504/58645123-b865d280-82d0-11e9-9540-3af8d3ea66f5.png)

**Comment by calequin** [comment]
fixed in preprod and test

**Comment by JuanitaMiles** [comment]
Appears fixed in PreProd.
