### ISSUE TITLE
License - Liquor License - Failing Inspections Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1010]
Failing both inspections during the Inspections milestone still allows the application to progress to the Board and Attorney Review milestone.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58645513-81dc8780-82d1-11e9-927a-6a1e23b2e149.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Appears fixed. (LI244275)
