### ISSUE TITLE
License - Liquor License - BOARD Review Resubmit Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1011]
Resulting the BOARD Review with Resubmit in the Board and Attorney Review milestone still allows the application to progress to the Renewal Review milestone.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58645750-f1527700-82d1-11e9-82ae-c259fba8f1f4.png)

**Comment by calequin** [comment]
fixed in test and preprod

**Comment by JuanitaMiles** [comment]
When resulting the BOARD review with RESUBMIT, the application progresses to Awaiting Fee Payment.

![image](https://user-images.githubusercontent.com/31770504/59603721-2c2d1b00-90d8-11e9-87bb-4cd46082b54f.png)

**Comment by calequin** [comment]
fixed in test
