### ISSUE TITLE
License -Liquor License - License and Endorsement Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1012]
On a Class A Liquor License I had two endorsements (Sunday Sales, and Wine Tasting). The fees for this license did not generate properly. The Sunday Sales fee line item generated but with no value. No line item was added for the Wine Tasting or the Class A license. The application went straight from Board and Attorney Review milestone to the Renewal Review milestone.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58646313-227f7700-82d3-11e9-9f79-fc0d939cd65f.png)

![image](https://user-images.githubusercontent.com/31770504/58646323-2612fe00-82d3-11e9-97fd-b472313f522e.png)

![image](https://user-images.githubusercontent.com/31770504/58646333-29a68500-82d3-11e9-9bde-4a15bed01e4e.png)

**Comment by calequin** [comment]
fixed in preprod and test

**Comment by JuanitaMiles** [comment]
Appears fixed. 

![image](https://user-images.githubusercontent.com/31770504/59603984-dad15b80-90d8-11e9-9fb8-b0e544fb26cd.png)
