### ISSUE TITLE
License - Liquor License - Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1013]
After resulting the Board and Attorney Review milestone reviews, the application goes straight to the Renewal Review milestone. However in the Status Logs it looks like the application blows through the Add Fees, Awaiting Fee Payment, Issue License, Active, Pre-Renew, and Renewal Application Fee milestones. I understand some of these milestones are automated and will not stop in the milestone to complete an action, however some seem like you should stop in. Is this correct?

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58646710-fd3f3880-82d3-11e9-8be4-92d115ceca51.png)

**Comment by calequin** [comment]
fixed in test and preprod. It now stops at active until the grace period and expiration dates are met

**Comment by JuanitaMiles** [comment]
When I APPROVE the RENEWAL_CK review during the Renewal Review milestone the application will progress to the Renewal Review Resubmit milestone even though it is not applicable in this situation. Completing the Applicant Actions detail page with 'Yes' will allow the application to progress to the next milestone and will not return to the Renewal Review milestone.

![image](https://user-images.githubusercontent.com/31770504/59605122-128dd280-90dc-11e9-8658-f6e0da405e91.png)

![image](https://user-images.githubusercontent.com/31770504/59605460-d9099700-90dc-11e9-8f5e-92530fd759e4.png)

HOWEVER, when I do ask for a resubmit on the RENEWAL_CK review, complete the Applicant Actions page, the application still does not go back to the Renewal Review milestone for a second cycle RENEWAL_CK review.

![image](https://user-images.githubusercontent.com/31770504/59605604-2980f480-90dd-11e9-98a3-d6e9cfaa7740.png)

![image](https://user-images.githubusercontent.com/31770504/59605646-3f8eb500-90dd-11e9-8348-c53ce0468417.png)

**Comment by kellyjj** [comment]
From reading this issue, the requirement seems to be that the review type RENEWAL_CK   drives the next m/s.   there seems to be a issue with the ms progression.  I am fixing now

**Comment by kellyjj** [comment]
I have fixed the formula driving the next m/s.  it seems to be working and ready for retest.  setting to ready for retest, and removing bug label.

**Comment by JuanitaMiles** [comment]
Milestones appear to be progressing properly.
