### ISSUE TITLE
License - Liquor License - Missing Detail Page in PreProd

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1016]
The Liquor License Application Details page existed in the TEST environment. It currently does not appear within the PreProd environment.

![image](https://user-images.githubusercontent.com/31770504/58647270-27452a80-82d5-11e9-857a-e77a9dca5298.png)

![image](https://user-images.githubusercontent.com/31770504/58647279-30ce9280-82d5-11e9-8cb5-0c6077d1c966.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Confirmed Fixed - JM 

![image](https://user-images.githubusercontent.com/31770504/59050647-d5624e80-8858-11e9-8513-9cb8ebfdcb3e.png)
