### ISSUE TITLE
R4C - Activation Code Email Message

### ISSUE THREAD

**Issue by megisys** [kcigeospatial/Fred_Co_Land-Management#1017]
Need this language changed not using Activation Codes

**Comment by calequin** [comment]
@megisys need more info on this

**Comment by megisys** [comment]
Register for a new account.. It comes up with a Activiation Code Email Message

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/60043463-21512800-968e-11e9-8809-ca286964665b.png)

fixed
