### ISSUE TITLE
Trade License - Electrical - License Category

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#102]
During the migration Electrical License Limited was added to the available License AP types. Talking with Ashlye we would like Eletrical Limited license removed from the available trade license types. The user should select an electrical license then from License Category select the appropriate Electrical License Category (Limited, Restricted, etc.). I will add to github as well.

Screenshot from IPSTEST
 
<img width="629" alt="idsdev" src="https://user-images.githubusercontent.com/4129185/53195140-03da5780-35e3-11e9-9f6e-234219d91f26.PNG">

Screenshot from SNAPSHOT
 
<img width="607" alt="snapshot" src="https://user-images.githubusercontent.com/4129185/53195144-08067500-35e3-11e9-97e8-3a160c13aaee.PNG">

**Comment by megisys** [comment]
This has the migrated data against it and will be rename to Just ELEC as part of GoLive.

Thanks

Dan

**Comment by ABonomo21** [comment]
linked to #383
