### ISSUE TITLE
R4C - Planning - Site Plan - within Municipality

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1020]
R4C allowed me to submit SP244552 which is located within the City of Frederick

**Comment by calequin** [comment]
this has been fixed by @megisys .
tested with same parcel number 02236966

**Comment by dhenry-KCI** [comment]
Fixed.  tried submitting a site plan for parcels in the city of frederick, brusnwick, emmitsburg, and myersville and the system properly prevented me from submitting.

MW
