### ISSUE TITLE
R4C-Trailer Hours of Operation (Excel Issue #59)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1022]
For Trailer permits, when you input the Hours of operation, it changes it once it is saved. I put the Hours of Operation as 8am-7pm. Once the permit was saved it generated as having a date along with the time frame. No date should generate. The Hours of Operation should just be the Time that the Trailer will be in use during each day. -MCoffman

Permit# 245604
![image](https://user-images.githubusercontent.com/47611580/58807149-83fe5900-85e5-11e9-93cc-9419463d9e0b.png)

**Comment by calequin** [comment]
added to list for Dan W. Currently time is coming across as date and time in rhythm. Back office displays it as just time.

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/59614222-4bcf3e00-90ee-11e9-9f2b-35dc24f460ec.png)
![image](https://user-images.githubusercontent.com/47611580/59614236-51c51f00-90ee-11e9-95aa-2b8000976c71.png)

**Comment by calequin** [comment]
removed date and time in backoffice detail page. fixed
