### ISSUE TITLE
R4C- Planning - Site Plan - Resubmission 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1023]
R4C - Resubmission Work Flow - Denied Planning Review - KEV

SP244553 - Denied Planning Review - R4C states 2 Pending tasks - under Instructions "NEEDS ACTION" there is nothing listed? Isn't this confusing for the customer? 

![R4C - Resubmission - Work Flow 2](https://user-images.githubusercontent.com/4129185/58808712-8dd58b80-85e8-11e9-9a45-1743600d2d45.PNG)

![R4C - Resubmission - Work Flow](https://user-images.githubusercontent.com/4129185/58808183-81046800-85e7-11e9-95f1-49a010b8b565.PNG)

**Comment by calequin** [comment]
this will come in as a notification to the customer and the customer will be updating information via projectdox
