### ISSUE TITLE
R4C - Uploading Attachment on Submitted App

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1024]
Error Uploading File

![image](https://user-images.githubusercontent.com/47611580/58809599-3df7c400-85ea-11e9-80c6-360cda9ad586.png)

Received error when dragging a pdf file to a submitted permit. I tried to an attachment to a submitted permit #245603

6/3/19EP

**Comment by megisys** [comment]
This is already logged as a bug.. Not Fixed yet.. But a duplicate ticket
