### ISSUE TITLE
R4C Land Use-Details Page-Temp Construction Structure Info

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1027]
The information required for a temporary construction structure is scattered though out the details page, is there any way we can group them together?-AW
![image](https://user-images.githubusercontent.com/47611580/58812318-954c6300-85ef-11e9-921e-62eb04a51cf4.png)

**Comment by calequin** [comment]
fixed in test.

**Comment by ABonomo21** [comment]
Ready in test; please make formatting consistent throughout-MCoffman

![image](https://user-images.githubusercontent.com/47611580/59105429-e915bf80-8901-11e9-922a-9acc762923f2.png)
