### ISSUE TITLE
R4C - Application located in the City of Frederick

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1028]
Submitted a land use for a property located in the City of Frederick. 

L244555

![image](https://user-images.githubusercontent.com/47611580/58812677-5834a080-85f0-11e9-8fb5-d7df1b36b50f.png)

EP 6/3/19

**Comment by calequin** [comment]
is this rule just for LandUse? similar as the planning rules for taking in outside township applications? @ABonomo21

**Comment by ABonomo21** [comment]
We do not process Land Use or Building permits for the City of Frederick or the Town of Mt. Airy- 
However, Capacity permit under the Building A/P do process applications for the City of Frederick. 

Staff will check the SDAT with every application processed like they do now to confirm the application was submitted to the correct jurisdiction

If the you can establish the rejection of land use permits within the township code for the City of Frederick or the Town of Mt. Airy that would be great. it would be similar to the planning github ticket #1020

**Comment by calequin** [comment]
added logic in test to not allow LANDUSE Applications for township 04 Frederick City and 06 Mt Airy. Need to deploy to preprod for rhythm

**Comment by ABonomo21** [comment]
did not work was able to submit city address in landuse

![image](https://user-images.githubusercontent.com/47611580/60047392-a0972980-9697-11e9-8001-8070fe68b1d9.png)

**Comment by calequin** [comment]
fixed in preprod to not allow city of frederick and mt airy for land use

**Comment by ABonomo21** [comment]
Worked in R4C for 30 North Market Street in City of Frederick and 704 South Main Street in Mount Airy-MCoffman

![image](https://user-images.githubusercontent.com/47611580/60125303-8160d080-9759-11e9-9409-1bb899680268.png)
