### ISSUE TITLE
Building - Garage Addition - Electrical Inspections

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#103]
System should only generate a rough-in Inspection and a Final inspection.
Since its an attached garage it should only generate a rough-in and a final. (If it was an detached it would be a trench, rough-in and final.)

Temp (this would generate a new service panel, or associated with electrical service) and Low Voltage (this will only ever be a manual add) Inspections generate in Hansen 7 and should be disregarded.  

AP237174
Logged by M. Coffman 2/14/2019

![garage](https://user-images.githubusercontent.com/4129185/53250951-8158a300-3689-11e9-8a9e-1e5441b417f4.png)

**Comment by megisys** [comment]
Can someone please review issue #107  THis seems to contradict that ticket

**Comment by imazlout** [comment]
There is no reference that this is a detached or attached garage on this electrical application. I just see that ALTADDACC (alteration, addition, accessory) was added as an electrical detail.
Dan, I see that #107 is referring to a Resuses permit, maybe this was meant to refer to a resuses permit instead of an electrical, since that does indeed have the attached/detached garage data? Need clarification from County.

**Comment by dhenry-KCI** [comment]
@imazlout this is an electrical permit related to a Resuse permit. When work type = Addition or alteration the only inspections that should generate are rough-in and final.

This is documented in airtable.

**Comment by megisys** [comment]
I believe this is ready for Testing...

**Comment by dhenry-KCI** [comment]
Testing Failure-The temp inspection was removed(as it should be) however the underground and the low voltage inspections still generated. As stated above since this is an attached garage it should only have the rough in and the final inspections for the electrical permit.

![image](https://user-images.githubusercontent.com/4129185/53813699-3f065000-3f2c-11e9-88e8-2814b9bacd0b.png)

**Comment by megisys** [comment]
LVOL Inspection pretty much never adds now.. When on a ELEC-UNDGR if I turn off for Addition and Alter, it will be off for ALL ELECPERM

**Comment by ABonomo21** [comment]
Garage #238975, associated electric #238976-The Low Voltage and Temp Service Inspections all generated when they shouldn't-AW
![image](https://user-images.githubusercontent.com/47611580/54755083-8262ee80-4bbb-11e9-9649-cf40c5736407.png)

**Comment by megisys** [comment]
Ready for Retest

**Comment by ABonomo21** [comment]
Not fixed-an electrical permit for a garage should only have the rough in inspection and then the final inspection.-Aw
![image](https://user-images.githubusercontent.com/47611580/55639075-951e1b80-5796-11e9-9a7c-0cb30ee7cf7f.png)

**Comment by ABonomo21** [comment]
According to airtable, Attached Garages (which are considered additions) should only have Rough In and Final Inspections.-Aw
![image](https://user-images.githubusercontent.com/47611580/55735836-1cb29700-59f0-11e9-8992-de6cf4c2c7bd.png)
![image](https://user-images.githubusercontent.com/47611580/55735854-25a36880-59f0-11e9-921b-44e77defc99a.png)

**Comment by megisys** [comment]
Please Retest

**Comment by ABonomo21** [comment]
not fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55815131-d1ff5080-5abd-11e9-8f0e-f7bcbdadaf70.png)

**Comment by megisys** [comment]
Ready for Retest

**Comment by ABonomo21** [comment]
corrected for a garage as an addition
