### ISSUE TITLE
IPS - Planning - Review Names 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1030]
while testing different Site Plan applications I noticed that the Review names had some additional code like text after the normal name - KEV

![Site Plan - Type II - Review Names](https://user-images.githubusercontent.com/4129185/58812754-7d291380-85f0-11e9-8417-95f1d4eaf3b8.JPG)

**Comment by megisys** [comment]
Duplicate.. Known Issue
