### ISSUE TITLE
Land Use-Resubmittal/Applicant Actions

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1031]
after resulting the completeness check as a resubmittal, there is nothing on the R4C side to let the applicant know what the next step is. The only thing that indicates it is the "Current Milestone" at the top and the "Awaiting Applicant Resubmit" but both of them don't give you any other information. The applicant won't know to resubmit under the applicant actions tab. -AW
![image](https://user-images.githubusercontent.com/47611580/58813267-62a36a00-85f1-11e9-969a-bc15d6eb7b79.png)
![image](https://user-images.githubusercontent.com/47611580/58813331-8b2b6400-85f1-11e9-8439-23b740415c60.png)

**Comment by ABonomo21** [comment]
comments populate under the all actions tab under review if you select review detail

![image](https://user-images.githubusercontent.com/47611580/59046090-574d7a00-884f-11e9-9009-34cd7eceedae.png)

![image](https://user-images.githubusercontent.com/47611580/59046124-67655980-884f-11e9-924d-5d866a955e5a.png)

**Comment by ABonomo21** [comment]
Need to clarify better for the applicant where to find the comments. had to go under all - select the review and view comments..

**Comment by ABonomo21** [comment]
It still does not direct the applicant to go to the " all " tab and open the completeness check review details - directions need to be more clear to tell the applicant how to get to the completeness check review 
![image](https://user-images.githubusercontent.com/47611580/59458898-787f0f00-8de9-11e9-989f-2dae50ed4af7.png)

![image](https://user-images.githubusercontent.com/47611580/59458931-86cd2b00-8de9-11e9-8da9-e4218511133b.png)

**Comment by calequin** [comment]
currently working a better solution for this

**Comment by dhenry-KCI** [comment]
Once confirmed we can close issue #883

**Comment by calequin** [comment]
we have added a county comments and status check to the detail page for clarity. ready for retest

**Comment by ABonomo21** [comment]
also need these direction set up for resubmit

**Comment by JuanitaMiles** [comment]
For a Completeness Check Resubmit - Works as expected. R4C provides instruction, with a link that will jump to the Applicant Actions section. The review comments are also shown within the Applicant Actions section. 

![image](https://user-images.githubusercontent.com/31770504/63542023-58f11a80-c4ed-11e9-94e1-6afd57caa436.png)

For an Under Review Resubmit - Does not work as expected. R4C does not provide the instruction with the link to jump to the Applicant Actions page. The review comments are showing within the Applicant Actions section, which is working as expected.

![image](https://user-images.githubusercontent.com/31770504/63542387-44615200-c4ee-11e9-84c5-15065e30d744.png)

**Comment by ABonomo21** [comment]
fixed, comment are showing under the applicant actions. -aw
![image](https://user-images.githubusercontent.com/47611580/63945725-d2cf5980-ca41-11e9-82e0-9a97063454e7.png)
