### ISSUE TITLE
Non-Residential Tanks-Life Safety Review/Inspection

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1033]
Non-Residential Tanks-Permit# 245614
Life Safety Review Fee Generated; However Life Safety Review and Inspection did not Generate.-MCoffman

![image](https://user-images.githubusercontent.com/47611580/58815240-40135000-85f5-11e9-9c2c-76a34ae5d841.png)

![image](https://user-images.githubusercontent.com/47611580/58815116-03dfef80-85f5-11e9-896e-d822945fe723.png)

![image](https://user-images.githubusercontent.com/47611580/58815178-1eb26400-85f5-11e9-935f-e3bfa8727af5.png)

![image](https://user-images.githubusercontent.com/47611580/58825171-d05c8f80-860b-11e9-8658-a5b878b93aad.png)

**Comment by megisys** [comment]
Please test in TEsT and mark as Ready for Deploy

**Comment by ABonomo21** [comment]
Issue Fixed in Test Permit# 245733-MCoffman

![image](https://user-images.githubusercontent.com/47611580/59048321-91207f80-8853-11e9-9bab-2184f553167f.png)

![image](https://user-images.githubusercontent.com/47611580/59048398-b8774c80-8853-11e9-8d2e-f660ac923905.png)
