### ISSUE TITLE
Planning - Final Plat Details - typo

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1035]
![image](https://user-images.githubusercontent.com/4129185/58826661-2979f280-860f-11e9-82cc-f07ab9a590ac.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58980791-19911880-879f-11e9-9dc3-9857c7bce4ea.png)

Fixed - AP # PL244591 - KEV
