### ISSUE TITLE
Temporary Trailer-Health Review Fee did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1037]
same as Issue #548 this was originally fixed on 4/3/19, now the health review fee is not generating for temporary trailers when it should be. -AW

![image](https://user-images.githubusercontent.com/47611580/58827188-61356a00-8610-11e9-966b-4973a89225a2.png)

**Comment by megisys** [comment]
Please Test in Test. Mark as ready to deploy if ok

**Comment by ABonomo21** [comment]
failed. health review fee did not generate-aw
![image](https://user-images.githubusercontent.com/47611580/59046033-308f4380-884f-11e9-96c8-81076df79fec.png)

**Comment by imazlout** [comment]
ready for test

**Comment by ABonomo21** [comment]
populated
