### ISSUE TITLE
Grading- Legal Documents 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1039]
We need to discuss the process for submitting legal documents and guarantees (Bond, Letter of Credit, etc.)  electronically. Currently they have to be originals. 

EP & TM 6/4/19

**Comment by megisys** [comment]
Can not be electorinc must still be originals. No legal change here

**Comment by ABonomo21** [comment]
Ok. Thank you.

6/7/19 EP
