### ISSUE TITLE
r4c - grading - details page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1040]
project specifics should be able to be completed by the applicant. 

![image](https://user-images.githubusercontent.com/4129185/58904461-8f30b200-86d5-11e9-9426-6f2e6dc11e95.png)

![image](https://user-images.githubusercontent.com/4129185/58904485-a079be80-86d5-11e9-87ac-2abeb720252f.png)

tm 6/4/19

**Comment by calequin** [comment]
fixed in test.

**Comment by ABonomo21** [comment]
Grading Details Intake has been corrected.

However- there is nowhere for the applicant to enter this information. 
![image](https://user-images.githubusercontent.com/47611580/59111177-8119a600-890e-11e9-9eab-f83a9fc2e439.png)

6/7/19 EP

**Comment by calequin** [comment]
this was fixed in test. needs to be deployed to preprod for rhythm testing

**Comment by ABonomo21** [comment]
This needs to be corrected in R4C also since this is something that the applicant will complete. We will be verifying at completeness check.

**Comment by calequin** [comment]
fixed in preprod
![image](https://user-images.githubusercontent.com/47603568/59241146-23b27d00-8bcc-11e9-9d8a-60bb0f8535cc.png)

**Comment by ABonomo21** [comment]
THIS IS OK

TM 6/20/19
