### ISSUE TITLE
r4c - grading - swmesd application types

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1041]
can the esd type be completed by the applicant in r4c? 

![image](https://user-images.githubusercontent.com/4129185/58904603-db7bf200-86d5-11e9-98ff-18aada2a145c.png)

![image](https://user-images.githubusercontent.com/4129185/58904690-05cdaf80-86d6-11e9-8c1d-2ea1da3d5225.png)

tm 6/4/19

**Comment by megisys** [comment]
Needs to be Generated for R4C too

**Comment by megisys** [comment]
Generate for R4C
