### ISSUE TITLE
r4c - grading 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1042]
need to have a discussion to be sure that when an application is submitted for mj/swm/pi that if only a pi is submitted but a mj and swm are also to be submitted that we catch it. need to discuss internally to figure this out. 

Is there any way to alert the applicant that an mj/swm is required if they only apply for a pi...

or this could all be done strictly through the review process when vijay/eric look at the cost estimates since that occurs prior to completeness check

tm 6/4/19

**Comment by megisys** [comment]
This is part of the review process due to not knowing the order in which an applicant will apply for the permits.
