### ISSUE TITLE
IPS PreProd - Planning - Review Description 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1044]
![image](https://user-images.githubusercontent.com/47611580/58963513-4e8b7400-877b-11e9-9b47-fa13a63bc1b0.png)
 
Review Descriptions have some sort of code written next to them 
KEV

**Comment by mmbanong** [comment]
Post Go Live issue per Dan

**Comment by mmbanong** [comment]
Post Go Live issue per Dan

**Comment by dhenry-KCI** [comment]
go-live correction- closing
