### ISSUE TITLE
Grading- Migration- Driveway

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1046]
The project # in Hansen 7 is the Planning/Plat # in IPS. 
Permit 192505- in this case it did not relate the record.

![image](https://user-images.githubusercontent.com/47611580/58964028-323c0700-877c-11e9-8098-2dd3fed7e0f7.png)

![image](https://user-images.githubusercontent.com/47611580/58963944-0caefd80-877c-11e9-9d80-332a8499b8a3.png)

6/5/19 EP

**Comment by megisys** [comment]
It is a related record..

**Comment by ABonomo21** [comment]
Closing Ticket. Created in error. 

6/5/19 EP
