### ISSUE TITLE
building - fro - migration - fro protection details

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1047]
the FRo permit details page did not bring over the FIPA (2 or 3 years) this is in hansen 7 but did not get carried over

![image](https://user-images.githubusercontent.com/47611580/58966103-ae841980-877f-11e9-8112-14e9b8d2a6eb.png)

![image](https://user-images.githubusercontent.com/47611580/58966137-b93eae80-877f-11e9-9162-5e0b1f7d7283.png)

tm 6/5/19

**Comment by megisys** [comment]
185875 Example . I can not see these fields in Select * from AGENCYCDR_BUILDING.FROPERMITDET

**Comment by ABonomo21** [comment]
This issue is resolved. 

6/7/19 EP
