### ISSUE TITLE
building - grading - migration - closed/complete

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1048]
the inspections have not been completed and funds have not been returned but IPS shows the application as complete/closed. however, in hansen 7, the application shows open and correct. 

![image](https://user-images.githubusercontent.com/47611580/58968213-aa59fb00-8783-11e9-835b-05ade6547554.png)

![image](https://user-images.githubusercontent.com/47611580/58968241-b5ad2680-8783-11e9-891d-834bfb2c6bf4.png)

tm 6/5/19

**Comment by megisys** [comment]
This is not valid..
