### ISSUE TITLE
Building - Basement Finish - Fire Permit Inspections

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#105]
System generated an incorrect Fire-Flow and Fire - Visul Inspections. System should not generate a Fire Flow (this is a waived inspection in Hansen 7) and Fire Visul should be replaced with Sprinkler Hydrostatic  (Fire- SPKHH,) Fire SPKHH is a missing code type Inspection Type pop-up.

AP 237153
Logged By M. Coffman

![fire inspections](https://user-images.githubusercontent.com/4129185/53252300-8e2ac600-368c-11e9-8afd-60dcdb41a23c.png)

**Comment by megisys** [comment]
@dhenry-KCI , I feel these issues are coming about due to incomplete or half input Fire Detail Pages.. Can we please ensure we are doing a like for like test against Hansen 7.

**Comment by ABonomo21** [comment]
Testing Failure-The Visual Inspection of Hydro Test Inspection still generated. Everything is filled in correctly in the fire details. FIRE-VISUL should be replaced with FIRE_SPKH (Fire Sprinkler Hydrostatic)
![image](https://user-images.githubusercontent.com/47611580/54147152-f5c06f80-4407-11e9-8e35-37960c19d20c.png)

**Comment by megisys** [comment]
Please Retest

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54370077-65736c00-464d-11e9-9223-bb3ab2cbce11.png)
