### ISSUE TITLE
Addresses without Parcels

### ISSUE THREAD

**Issue by megisys** [kcigeospatial/Fred_Co_Land-Management#1051]
Report needed Where Paracel id is set on Detail Page but not actually linked

**Comment by megisys** [comment]
Property.Address Table and the PROPERTY.ADDRLINKPARCEL Table ?

**Comment by mmbanong** [comment]
Report created for Addresses with no parcel

**Comment by mmbanong** [comment]
[AddressesWithNoParcels.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3306347/AddressesWithNoParcels.xlsx)
