### ISSUE TITLE
License - Special Event - Completeness Check (2nd Resubmit)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1052]
When resulting the COMPLETE review with Resubmit a second time, the application does not stop in Awaiting More Information. It blows through the Awaiting More Information milestone and goes straight back to Completeness Check and generates a third review.

![image](https://user-images.githubusercontent.com/31770504/58981305-2104f180-87a0-11e9-9837-7a51c515497c.png)

![image](https://user-images.githubusercontent.com/31770504/58981440-65908d00-87a0-11e9-8da1-05a168a791be.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
The milestones now progress correctly, however the same thing that is happening in issue #1005 is happening here. The Awaiting Applicant Action(s) detail page is pre-populating with 'Yes' on the second Resubmittal request.

**Comment by kellyjj** [comment]
I am assigning this to myself, as I fixed 1005.

**Comment by kellyjj** [comment]
the 2 issues (this one and 1005)  shared the same code.  fixing 1005 has fixed this.  reassigning and removing bug tag

**Comment by JuanitaMiles** [comment]
the applicant actions detail page is still pre-populating with Yes

**Comment by calequin** [comment]
fixed in test. fixed condition formula to also verify applicant action detail page

**Comment by dhenry-KCI** [comment]
prepopulation of "Y" corrected.
