### ISSUE TITLE
License - Special Event - ZONING REV Review Result Codes

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1053]
The ZONING REV review result codes need to be filtered correctly.

![image](https://user-images.githubusercontent.com/31770504/58983033-d2f1ed00-87a3-11e9-9f95-dfd2f93c5893.png)

![image](https://user-images.githubusercontent.com/31770504/58983060-e2713600-87a3-11e9-8f36-1f68bc155181.png)

**Comment by megisys** [comment]
Adjusted

**Comment by JuanitaMiles** [comment]
Appears Fixed
