### ISSUE TITLE
Planning-Plat-Combined-Preliminary Final

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1054]
Comments in Hansen did not fully migrate to IPS' log
![image](https://user-images.githubusercontent.com/4129185/58983419-bd30f780-87a4-11e9-9203-2810003a89a2.png)
![image](https://user-images.githubusercontent.com/4129185/58983465-ddf94d00-87a4-11e9-8e99-9f34adbaf48b.png)

AM/GH

**Comment by dhenry-KCI** [comment]
still missing comments.

![image](https://user-images.githubusercontent.com/4129185/59052380-fe84de00-885c-11e9-92ca-3463db59a891.png)

MW

**Comment by megisys** [comment]
Looked good in Pristine. Get GDS to Run into PreProd

**Comment by dhenry-KCI** [comment]
Fixed!! - GH
![image](https://user-images.githubusercontent.com/4129185/59458217-05c16400-8de8-11e9-8a65-bc5ec60ef9c7.png)
