### ISSUE TITLE
License - Special Event - Under Review Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1055]
When you result a review while in the Under Review milestone with Resubmit, AND the Completeness Check was resubmitted at least once, the application blows through the Awaiting Applicant Resubmit milestone and generates a second cycle review. 

![image](https://user-images.githubusercontent.com/31770504/58983633-47795b80-87a5-11e9-9d84-d0d37fc17995.png)

![image](https://user-images.githubusercontent.com/31770504/58983709-6ed02880-87a5-11e9-9a0c-768dc0c654d5.png)

**Comment by calequin** [comment]
fixed resubmittal formula

**Comment by JuanitaMiles** [comment]
Appears fixed
