### ISSUE TITLE
IPS - Building PreProd - Data Conversion

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1056]
Hansen 7 permit 8193 has passed final inspection however, is not closed because it has an open child permit and a case. 

![image](https://user-images.githubusercontent.com/47611580/58983849-b22a9700-87a5-11e9-8ab1-e28c54dab952.png)

However, when I check status on the IPS 11 permit 8193 it moved to pending certificate which was the correct milestone however, it does not show in the milestone check that there is an open case and it does not show there is an open trade permit 

![image](https://user-images.githubusercontent.com/47611580/58983993-fe75d700-87a5-11e9-8eea-8126fb36dc1c.png)

the case is not shown in the related records tab

![image](https://user-images.githubusercontent.com/47611580/58984042-0f264d00-87a6-11e9-8665-4711ef87966a.png)

and when i go to the case 4050 the permit is not shown as a related record
![image](https://user-images.githubusercontent.com/47611580/58984084-26fdd100-87a6-11e9-93b7-d414094bc735.png)

**Comment by calequin** [comment]
fixed
