### ISSUE TITLE
building - grading - major grading - restown/condo/apt review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1057]
PWDR review populated but should not for a restown, condo, apartment with the not part of overall plan selected. DPZ did not popluate, which is correct. 

![image](https://user-images.githubusercontent.com/47611580/59033077-d1710500-8835-11e9-92aa-e8d31c21c2d8.png)

tiffany martin 6/6/19

**Comment by ABonomo21** [comment]
This is still not corrected. Permit #245675 duplicated issue. 

![image](https://user-images.githubusercontent.com/47611580/59109099-6e04d700-890a-11e9-889f-6712797cea79.png)

6/7/19 EP

**Comment by megisys** [comment]
Added Logic for MJ..

**Comment by ABonomo21** [comment]
Um no still not working.... 

![image](https://user-images.githubusercontent.com/47611580/59871558-da012980-9365-11e9-9aed-ff195877486a.png)

6/20/19 EP

**Comment by goggansd** [comment]
Trying to diagnose this after the latest test in PreProd. Looks like this application did not have the "Not Part of Overall Plan" box checked, as stated in the requirements at the top of this ticket.

![image](https://user-images.githubusercontent.com/28841997/59940479-c5399a00-9428-11e9-80d9-91a6554b6c77.png)

**Comment by ABonomo21** [comment]
Works- PWDR did not populate
Ready for deploy

6/25/19 EP
