### ISSUE TITLE
IPS Pre Prod-Name Search not working

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1058]
When I go to search a name to add as a contact, it does not transfer the name over to search and instead brings up every contact available.-AW
![image](https://user-images.githubusercontent.com/47611580/59033524-e0a48280-8836-11e9-8236-de210c07de88.png)
![image](https://user-images.githubusercontent.com/47611580/59033532-e7cb9080-8836-11e9-8682-19f4485bc7ce.png)

**Comment by megisys** [comment]
This is as expected
