### ISSUE TITLE
Migration _Grading 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1059]
Permit 192505 Driveway- Migration

In Hansen under conditions- PIHOLD was migrated to IPs under Conditions NOT_RRSESUB- it should be under log in IPS

![image](https://user-images.githubusercontent.com/47611580/59034444-0df23000-8839-11e9-9530-dac69e312c8c.png)

![image](https://user-images.githubusercontent.com/47611580/59034280-b81d8800-8838-11e9-969b-96ba75ef66cf.png)

6/6/19 EP

**Comment by megisys** [comment]
These Holds are moved to LOGS

**Comment by ABonomo21** [comment]
It is still populating as a condition. Migration issue. 

6/7/19 EP

**Comment by ABonomo21** [comment]
Corrected 

6/13/19 ep
