### ISSUE TITLE
Building - ResUse - Utility Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#106]
The system should always require a utility permit for new Construction (RESBUILDING). For any addition, alteration or accessory structure the permit tech will manually add the utility permit ( as a child) if required. 

AP 237143
Logged by Coffman

**Comment by megisys** [comment]
@JuanitaMiles What is a Utility Permit ???? (Confused)... 

![image](https://user-images.githubusercontent.com/47392306/53685725-81414e80-3cec-11e9-85f4-288e2e047e6e.png)

**Comment by JuanitaMiles** [comment]
@megisys if you create a plumbing permit, look at the Plumbing type options on the Details page.

**Comment by imazlout** [comment]
Please specify what's the criteria for new construction. Is it if Construction Type = "FULL"?  or If Work type = "ADD"? or something else?

**Comment by ABonomo21** [comment]
For all RESUSE Permits the system should require the user to relate a Child Plumbing Utility Permit. This will be a manual add if required by the tech. Disregard first comment. -MCoffman


Permit# 238581 RESUSE Permit-Minor Permit
![image](https://user-images.githubusercontent.com/47611580/53890520-5c075580-3ff6-11e9-9e28-433a83cf51a8.png)

**Comment by imazlout** [comment]
@ABonomo21 Should or Should not require? The two sentences contradict each other. Please clarify if the Status check should be removed altogether and it will be a manual add going forward?

**Comment by ABonomo21** [comment]
For all ResUse permits, it **should not** require the user to relate a Child Plumbing Utility Permit. This will be a manual add if required by the tech. Plumbing Utility Permit should only be required on New ResBldg.-AW

**Comment by ABonomo21** [comment]
Disregard closure-accidental click- Issue has been reopened-AW

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55178845-94fd9a80-515c-11e9-8933-76a573a59658.png)

**Comment by ABonomo21** [comment]
confirmed fixed for alterations-AW
![image](https://user-images.githubusercontent.com/47611580/55179530-02f69180-515e-11e9-9b23-9f0cbbf7f97d.png)
![image](https://user-images.githubusercontent.com/47611580/55179545-0ee25380-515e-11e9-88ba-5e21c7bb7580.png)

**Comment by ABonomo21** [comment]
confirmed fixed for accessory-AW
![image](https://user-images.githubusercontent.com/47611580/55179939-eb6bd880-515e-11e9-8b04-cf7a159ba5bf.png)

![image](https://user-images.githubusercontent.com/47611580/55179974-f9215e00-515e-11e9-97d0-eb9b598c10c3.png)
