### ISSUE TITLE
Ips Pre Prod-ResSfd-Duplicate Grading permits auto generated.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1060]
Two Grading permits automatically generated for this ResSfd. Only one should generate-AW
![image](https://user-images.githubusercontent.com/47611580/59035734-e6e92d80-883b-11e9-9c58-f95bf23c114e.png)

**Comment by megisys** [comment]
System will check if one already listed as a Child

**Comment by ABonomo21** [comment]
re-checked only generated one - 
![image](https://user-images.githubusercontent.com/47611580/59457866-453b8080-8de7-11e9-9961-871dac25fe8c.png)
