### ISSUE TITLE
Driveway - Priority

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1063]
Driveway should always populate as priority code 3

![image](https://user-images.githubusercontent.com/47611580/59037105-9921f480-883e-11e9-9e4a-78b879c7c78c.png)

6/6/19 EP

**Comment by megisys** [comment]
Please Test in TEST

**Comment by ABonomo21** [comment]
Ready to deploy

6/6/19EP
