### ISSUE TITLE
IPS Pre Prod--Reinspection fee did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1068]
the $48 reinspection fee did not generate after the third failed inspection for electric and plumbing  permits.-AW
electric 245648
![image](https://user-images.githubusercontent.com/47611580/59042988-6df0d280-8849-11e9-8042-13e555d26456.png)
plumbing 245652
![image](https://user-images.githubusercontent.com/47611580/59043483-4bab8480-884a-11e9-865c-070fa6e850e9.png)

**Comment by ABonomo21** [comment]
the reinspection fee also did not generate for a sign permit #245658-aw
![image](https://user-images.githubusercontent.com/47611580/59047178-61707800-8851-11e9-9a95-94a42eb1b53a.png)

**Comment by megisys** [comment]
Needs to be after 2 Inspections

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/59364960-b6a30280-8d05-11e9-8183-318d06e8a98b.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/59457642-d4946400-8de6-11e9-81dd-7e26f54c488e.png)
worked
