### ISSUE TITLE
VOID PROCESS - Add Log

### ISSUE THREAD

**Issue by megisys** [kcigeospatial/Fred_Co_Land-Management#1069]
Need to do LOG process to Waive Fees, Inspections and Reviews and move to complete milestone with a status of Void.

**Comment by megisys** [comment]
Ready for test in TEST -Mark as Ready to deploy when happy

**Comment by ABonomo21** [comment]
not working 

![image](https://user-images.githubusercontent.com/47611580/59449159-9726db00-8dd4-11e9-92a1-80f596629beb.png)

**Comment by mmbanong** [comment]
Will have to work with Dan on this one per Dan

**Comment by megisys** [comment]
See BP_ManageLog_BUF - Started it for you in TEST

**Comment by megisys** [comment]
BP_VOID_AA

**Comment by megisys** [comment]
BP_VOID_LOG_AA

**Comment by mmbanong** [comment]
Added formula BP_VOID_LOG_AA

**Comment by ABonomo21** [comment]
Fixed
