### ISSUE TITLE
Building - Resuse / Basement - Required Inspection

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#107]
The system generated an extra inspection for a BLDG- FOOT inspection (footing inspection).

System should only generate a footing inspection where Work Type = Addition or Where Work Type = Accessory and Where Construction Type DOES NOT EQUAL, Above Ground Pool, In-ground Pool or a Hot tub

**Comment by megisys** [comment]
Please ReTest - Change Made

**Comment by megisys** [comment]
Fixed

**Comment by ABonomo21** [comment]
Basement A/P# 238699 and 238701-NOT Corrected; Footing inspection is still generating-MCoffman
![image](https://user-images.githubusercontent.com/47611580/54128006-74ee7d00-43e1-11e9-8980-3d12572ff26f.png)

![image](https://user-images.githubusercontent.com/47611580/54128453-7b312900-43e2-11e9-8753-8bd3ca4a5042.png)

Inground Pool A/P# 238699-Corrected
![image](https://user-images.githubusercontent.com/47611580/54128894-6f923200-43e3-11e9-891c-bdf6aa8162d6.png)

**Comment by megisys** [comment]
I have made a change. PPlease Retest

Thanks

Dan

**Comment by ABonomo21** [comment]
Permit# 238818 RESUSE Basement-Not Corrected-MCoffman
![image](https://user-images.githubusercontent.com/47611580/54369680-b59dfe80-464c-11e9-931f-ef83149bd209.png)

Permit# 238822 RESUSE Basement-Not Corrected-MCoffman
![image](https://user-images.githubusercontent.com/47611580/54370097-6d331080-464d-11e9-99dd-95e8b4897668.png)

**Comment by imazlout** [comment]
Ready for test. 
Here is complete list of rules I have for when the footing inspection generates. If it's still incorrect, please let me know where the changes should be made in the statements below.

- If work type = ADD => Add Footing Inspection
- If work type = ACCESS AND Acc Structure Det is NOT equal to ‘POOLABOV’, or ‘POOLIN’,  or ‘TUBSPA’ => Add Footing Inspection
- If work type = ALTER AND Type of Alteration is NOT equal to ‘INALT’ or ‘INUNALT’ or 'BSMTFIN' => Add Footing Inspection
- If Minor Permit is not Checked => Add Footing Inspection

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54616476-0be8b400-4a36-11e9-8574-d790834a7036.png)
