### ISSUE TITLE
Ips Pre Prod-Fire Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1071]
#245659-Fire permit does not require a building permit. For these stand alone fire permits, we  Need to add check box (back office only!) on the fire detail page to say "Stand Alone Fire Permit" to be able to move forward with the permit.-AW
![image](https://user-images.githubusercontent.com/47611580/59048561-1146e500-8854-11e9-9a55-f47ac2375964.png)

**Comment by calequin** [comment]
added stand alone permit checkbox to the application. added workflow to the FIRE_ParentBldAp_SCF formula.

**Comment by ABonomo21** [comment]
Fixed in test-MCoffman
![image](https://user-images.githubusercontent.com/47611580/60189915-bd4e7100-97ff-11e9-8fb7-304a84b773e1.png)
