### ISSUE TITLE
IPS-Preprod-APFO details page-exemption fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1073]
move exemption fee to top, and leave space between it and the roads exemption boxes (under trip, previous approval, etc.).  The exemption fee is used to confirm its an exemption and to create the $58 fee.

![image](https://user-images.githubusercontent.com/4129185/59051542-1fe4ca80-885b-11e9-9f20-aa57a7b1c2d9.png)

MW

**Comment by megisys** [comment]
Moved

**Comment by dhenry-KCI** [comment]
still a mess.  shot below from Pre-prod.  Lokks different in test.

![image](https://user-images.githubusercontent.com/4129185/59457413-56d05880-8de6-11e9-93c6-00a9eb016289.png)


MW

**Comment by dhenry-KCI** [comment]
fixed by Dan in house.  R4C and Preprod look good.

MW
