### ISSUE TITLE
R4C- Demolition Detail Page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1074]
Demo detail page is out of order 
Section complete should be below cip and muni check boxes.. 

![image](https://user-images.githubusercontent.com/47611580/59059279-8faf8100-886c-11e9-9bbf-3aeea3b77e48.png)

**Comment by calequin** [comment]
fixed in test

**Comment by ABonomo21** [comment]
Fixed in test-MCoffman
![image](https://user-images.githubusercontent.com/47611580/59204891-a3f6c500-8b6f-11e9-999a-694332fb6789.png)

**Comment by ABonomo21** [comment]
confirmed correct - 

![image](https://user-images.githubusercontent.com/47611580/59441377-7c4d6a00-8dc6-11e9-900c-7471b3aff8a5.png)
