### ISSUE TITLE
ips-preprod-planning-preliminary-extension-fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1075]
$1.00 fee is incorrect.

![image](https://user-images.githubusercontent.com/4129185/59059466-0a789c00-886d-11e9-938a-50918c6f3f05.png)

MW

**Comment by megisys** [comment]
1501

**Comment by dhenry-KCI** [comment]
fixed

![image](https://user-images.githubusercontent.com/4129185/59457234-08bb5500-8de6-11e9-9bc8-ca9f265a8d36.png)

mw
