### ISSUE TITLE
R4C-Non Res Electric Details page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1079]
just like issue #1078 the declared value and the square footage are not required and should be deleted.  and the Occupancy type of non res should drive only the non res details options to show. and the description box/options can be deleted-AW
![image](https://user-images.githubusercontent.com/47611580/59108782-b8398880-8909-11e9-8421-40cd7f8a28d7.png)
![image](https://user-images.githubusercontent.com/47611580/59108824-cdaeb280-8909-11e9-9613-3f4090cd200b.png)
![image](https://user-images.githubusercontent.com/47611580/59108886-f46ce900-8909-11e9-8e01-d46551e122cb.png)

and the grid does not save either
![image](https://user-images.githubusercontent.com/47611580/59109050-51689f00-890a-11e9-8f0e-6f2bfc8ea909.png)
![image](https://user-images.githubusercontent.com/47611580/59109071-5c233400-890a-11e9-81a5-48c0fe9c174b.png)

**Comment by calequin** [comment]
comments on detail page have been added to issue #1078 everything else has been updated.
