### ISSUE TITLE
Planning - Yard Mods - Distance from CL

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#108]
System should not require the user to populate  "Home A from CL" or "Home B from CL" for side or rear yard modifications.

![image](https://user-images.githubusercontent.com/4129185/53265810-23d64d80-36ad-11e9-98dc-db18b5944669.png)

**Comment by goggansd** [comment]
We can correct this using one of two methods:

1) Remove the fields from being required at all, and add a Status Check on a milestone which give you a "red line" if it is not filled in when it should be.
2) Add a Section Complete dropdown and enforce that this is filled in with a "red line" (Status Check) at a particular milestone.

In either case, we will need to know the following:

1) Which option above is preferrable?
2) At which milestone do you want the new rule enforced?
3) How do you distinguish between a side or rear yard modification and other type(s) (i.e. is it a work type, an occupancy code, a detail page field value, etc.)?

**Comment by megisys** [comment]
Other Fields are required , so I removed the above 2 as these are optional.

**Comment by dhenry-KCI** [comment]
Dustin, 
Per your alternatives above.
I would prefer the following;
_2. Add a Section Complete dropdown and enforce that this is filled in with a "red line" (Status Check) at a particular milestone._

In either case, we will need to know the following:

Which option above is preferrable? _2, see above_
At which milestone do you want the new rule enforced? __**Job Description-Work Type under Yard Mod.**__
How do you distinguish between a side or rear yard modification and other type(s) (i.e. is it a work type, an occupancy code, a detail page field value, etc.)? _Work Type_

**Comment by dhenry-KCI** [comment]
You can now add the setback in the box.  the issue has been addressed

**Comment by dhenry-KCI** [comment]
OK got it thanks
T
