### ISSUE TITLE
R4C-Electric app-Homeowners test

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1080]
The section regarding the Homeowners test should be back office only-AW
![image](https://user-images.githubusercontent.com/47611580/59109628-5e39c280-890b-11e9-8f27-426857ea60f9.png)

**Comment by calequin** [comment]
fixed in test.

**Comment by ABonomo21** [comment]
fixed in test, will recheck R4C when it's migrated over-AW
