### ISSUE TITLE
R4C- Fire Permit - Detail Page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1082]
Remove Signed application check box and associated bldg permit details from fire application- they are not options in IPS 

![image](https://user-images.githubusercontent.com/47611580/59110611-7dd1ea80-890d-11e9-9c4c-f392f39932f1.png)

![image](https://user-images.githubusercontent.com/47611580/59110643-8d513380-890d-11e9-92e1-10a3ea9b7211.png)

**Comment by calequin** [comment]
removed show in portal in test.  Fixed in test

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/59293670-ae878c00-8c4d-11e9-9ed7-6d8b8b5056e1.png)
