### ISSUE TITLE
R4C-Cloning permits gives new permit same status (Excel Issue #60)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1083]
Cloning a permit fromR4C will give the new permit the same status as the one that you cloned when it should just clone the info and then start as a new permit. and if you clone off a closed permit, the new permit will already be closed.-AW
#245681 cloned off of #245599. 245681 was done today 6/7, 245599 was done on 6/3. the issue date on 245681 is 6/3 when it should be starting as a new permit. 
![image](https://user-images.githubusercontent.com/47611580/59111259-ab6b6380-890e-11e9-979b-9b3dacb8a606.png)

![image](https://user-images.githubusercontent.com/47611580/59111247-a4445580-890e-11e9-9fa6-533c01208f66.png)

#245679-cloned off of #245678 (which is closed)
![image](https://user-images.githubusercontent.com/47611580/59111401-f38a8600-890e-11e9-837a-16494b50f231.png)

**Comment by calequin** [comment]
I just retested with a sign application #245668 that was in the Inspection milestone  and created #245670 successfully in the correct completeness check milestone. Cant replicate issue

**Comment by ABonomo21** [comment]
I got it to do it again, I cloned a permit off of one i did at around 10am, this new permit #245729 has the correct milestone and status but is has the process and issue date/time of the orignal permit. (245721)-AW
![image](https://user-images.githubusercontent.com/47611580/59295423-aaf60400-8c51-11e9-95b5-f4950a10879c.png)
![image](https://user-images.githubusercontent.com/47611580/59295459-c103c480-8c51-11e9-9fa7-594717c94fd8.png)

**Comment by ABonomo21** [comment]
It did it again, with a permit i did on 6/3/2019 (245599). the new permit that i just did 245730 has the processed/issue date/time of the original permit that i cloned-aw
![image](https://user-images.githubusercontent.com/47611580/59295697-54d59080-8c52-11e9-8bb0-482e61b1d78e.png)
![image](https://user-images.githubusercontent.com/47611580/59295785-82bad500-8c52-11e9-9fb8-2948b53d2810.png)

**Comment by calequin** [comment]
this has been added to the list for Dan W

**Comment by calequin** [comment]
per request. I have turned off the cloning feature on r4c.

**Comment by dhenry-KCI** [comment]
Closing Issue as we have turned cloning off.
