### ISSUE TITLE
R4C-Fire Permit Townhouse Details

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1085]
Is there some type of new Header we can put under the Townhouse Details to break up that section and the Expedited/CIP/Municipality section? Currently it looks like they are all part of the Townhouse Details section and I think it will confuse some customers-AW
![image](https://user-images.githubusercontent.com/47611580/59114154-909bed80-8914-11e9-884d-414cde14fb5e.png)

**Comment by calequin** [comment]
fixed in test.
added additional information label and renamed expedited plan review  = Expedited Plan Review Requested?

**Comment by ABonomo21** [comment]
Fixed but waiting to close until we go over all fire details page info with Ashlye & Christian-AW

**Comment by ABonomo21** [comment]
Closing due to other changes being to a different section. this one is fine-aw
