### ISSUE TITLE
IPS-preprod-Planning-expiration (Batch Manager Task)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1086]
crated this preliminary plan on friday with an expiration date of 6/7.  It appears nothing has happened to make the AP as expired.  For all Planning APs we need the status to somehow show that the application has expired.

![image](https://user-images.githubusercontent.com/4129185/59194613-933a5500-8b57-11e9-9ab6-4f502e25450a.png)

MW

**Comment by megisys** [comment]
We have an abandonment process to handle this. Nightly it will run and do its job. But an application typically will not expire in this method and this quickly.

**Comment by dhenry-KCI** [comment]
changing to will monitor once batch manager and abandonment process is defined.

**Comment by dhenry-KCI** [comment]
Per dan abandonment part of pre-go live. Adding to checklist and closing issue.
