### ISSUE TITLE
BUILDING - GRADING - SWMESD - CONFIG

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1088]
PI Surface course inspection populated after the application closed and finalized. However, this inspection shouldn't populate on this AP type. 

![image](https://user-images.githubusercontent.com/4129185/59196452-b3b8de00-8b5c-11e9-8322-b94b8863a7ed.png)

**Comment by dhenry-KCI** [comment]
the same thing happened with Major Logging permit #245692

**Comment by dhenry-KCI** [comment]
the same thing happened with minor logging permit #245693

**Comment by dhenry-KCI** [comment]
the same thing happened with minor grading permit #245695

**Comment by dhenry-KCI** [comment]
this happened on public improvement as well #245709

**Comment by dhenry-KCI** [comment]
this happened on major grading #245705

**Comment by dhenry-KCI** [comment]
this happened on swm #245708

**Comment by megisys** [comment]
Addressed This

**Comment by ABonomo21** [comment]
I have confirmed this has been corrected.

thank you
6/13/19 EP
