### ISSUE TITLE
building - grading - major grading, towns - under review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1089]
the reviews should not populate on major grading town/apt/condo permits this was working before but currently is not. not part of an overall plan was selected but this did not work as far as reviews. this did skip the inspection requirements (which is correct)

![image](https://user-images.githubusercontent.com/4129185/59198157-0b594880-8b61-11e9-9a30-19b7125c0976.png)

![image](https://user-images.githubusercontent.com/4129185/59200163-9ccab980-8b65-11e9-9eec-5176b8dc94e8.png)

tm 6/10/19

245698

**Comment by megisys** [comment]
Which reviews shouldnt have added please. I need the details of which.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/59351262-fa890e00-8ceb-11e9-94a5-ac293f9ebd65.png)

updated screenshot of reviews for permit #245698 the fees are correct.

**Comment by megisys** [comment]
Please ReTest

**Comment by ABonomo21** [comment]
good job guys!! 

6/20/19 EP Closing
