### ISSUE TITLE
Planning - BOA - Address / Tax Parcel

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#109]
System should not require (redlining)
<img width="571" alt="boa" src="https://user-images.githubusercontent.com/4129185/53266900-153d6580-36b0-11e9-9995-ca77aab9af84.PNG">
 a BOA be associated to a Parcel.

**Comment by megisys** [comment]
Changed this and Associated formulas which are checking Parcel Details for Completeness

**Comment by dhenry-KCI** [comment]
Resolved - A/P # 237453 - 3/4/19 - KEV
