### ISSUE TITLE
building - grading - major grading - mitigation items

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1090]
if you put in a quantity that is too large it will give you an error message. it appears that 5 digits or greater it doesn't accept it.

if quantity too high then you reduce to acceptable quantity then hit approve it removes the existing mitigation items except for the one that you are trying to add. sometimes when adding a mitigation item and you click add it deletes are previous items. the database is holding it but the webpage is not holding it until you go out and back in.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/59201689-f7b1e000-8b68-11e9-98aa-076e1bc53880.png)

**Comment by dhenry-KCI** [comment]
ap 245705

**Comment by megisys** [comment]
Are you going to have such large numbers ?

**Comment by dhenry-KCI** [comment]
@megisys - yes they were using a use case from H7

**Comment by kellyjj** [comment]
I have looked at this.  this is a db issue.  the number of digits is not large enough for a big quantity.

I will make the adjustments to handle a larger number

**Comment by kellyjj** [comment]
this is in test.    will change these settings

![image](https://user-images.githubusercontent.com/27238685/59784952-42c6a400-9289-11e9-8741-43c0877d2f69.png)

**Comment by kellyjj** [comment]
this has been fixed in test.   building permit 245829

there were 2 decimal columns that had to be adjusted for this.  set the total decimals to 32 for both

**Comment by kellyjj** [comment]
removing bug label and assigning to dhenry

**Comment by ABonomo21** [comment]
ok.

6/20/19 EP
