### ISSUE TITLE
building - grading - major grading - inspection fee/actual valuation

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1091]
there are two issues:

first we are not sure where the 7.29 is coming from under actual valuation - this should be the total of the mitigation checklist.

the second issue is the calculation of the fees itself

the inspection fees populated incorrectly. currently the inspection fees are calculated by using the total mitigation/actual valuation * 2.69% - in this case the actual valuation 7.29 however, the mitigation checklist totals to 885896.93 so the calculation should be based on 885896.93 which is 23830.63.

**Comment by ABonomo21** [comment]
1st issue: 
![image](https://user-images.githubusercontent.com/47611580/59202406-63487d00-8b6a-11e9-9bdb-65e977b107da.png)
![image](https://user-images.githubusercontent.com/47611580/59202435-73605c80-8b6a-11e9-90e4-2094a15af1a4.png)

2nd issue:
![image](https://user-images.githubusercontent.com/47611580/59202457-807d4b80-8b6a-11e9-9ef4-b66c7738a8d9.png)

Permit #245705

6/10/19 EP/TM

**Comment by mmbanong** [comment]
I checked and the value set is still set to 0.0269 see screenshot

![image](https://user-images.githubusercontent.com/47392173/59515735-ca797080-8e8d-11e9-95fc-b9bc97c0822c.png)

**Comment by ABonomo21** [comment]
CORRECTED TM 6/20/19
