### ISSUE TITLE
ips-preprod-Planning-Rezone-hearings

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1092]
tried to result hearing prep condition and got this error.

![image](https://user-images.githubusercontent.com/4129185/59202356-49a73580-8b6a-11e9-8dac-22ca4cd77e2d.png)

MW

**Comment by dhenry-KCI** [comment]
continued with above application.  played with resulting CC hearing different ways before approving it. Stuck in hearing milestone.

![image](https://user-images.githubusercontent.com/4129185/59202612-d6ea8a00-8b6a-11e9-9979-4cbfb8c58e31.png)


![image](https://user-images.githubusercontent.com/4129185/59202658-f1246800-8b6a-11e9-9f1a-0ad1d1648818.png)


![image](https://user-images.githubusercontent.com/4129185/59202683-00a3b100-8b6b-11e9-893b-3740f03ad616.png)


MW

**Comment by megisys** [comment]
Duplicate Issue. I have this open already

**Comment by dhenry-KCI** [comment]
fixed in test.

![image](https://user-images.githubusercontent.com/4129185/59705047-865ad880-91cb-11e9-9d17-c813129ba44c.png)


MW
