### ISSUE TITLE
Group Add- ALL

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1093]
Is there a way to have the permit numbers listed when group adding? There is currently a pop up stating it is successful, however it would be beneficial to have the numbers populate on the pop up as well. 

6/10/19

**Comment by dhenry-KCI** [comment]
@megisys @calequin - see Ashlye's comment

**Comment by dhenry-KCI** [comment]
during group add the user can check the related records button which will associate the new record(s) with the original. If the user does not click related records, button return to the search grid and sort by added date for newest records.
