### ISSUE TITLE
grading - public improvement - group add - actual valuation

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1094]
the actual valuation transferred over to the PI and SWM permits even though we did not select that the system pick up valuation when we group added.

![image](https://user-images.githubusercontent.com/4129185/59202891-70b23700-8b6b-11e9-940a-0f1d52fabd3b.png)

swm 245908
pi 245909

tm ep 6/10/19

**Comment by dhenry-KCI** [comment]
the mitigation items also carried over which is not correct. the mitigation items differ from ap to ap

we did not choose to transfer this information from the mj permit.

![image](https://user-images.githubusercontent.com/4129185/59203089-e1f1ea00-8b6b-11e9-9976-322008360e85.png)


245709

**Comment by megisys** [comment]
You copied an application. It is going to do this . This is not wrong..

**Comment by ABonomo21** [comment]
Do the mitigation details have to transfer over when bulk added? 

6/25/19 EP

**Comment by dhenry-KCI** [comment]
SYstem funtioning as designed. Closing issue.
