### ISSUE TITLE
Grading- Mitigation Delete

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1095]
is there a way to delete multiple rows on the mitigation items list instead of deleting one by one?

![image](https://user-images.githubusercontent.com/47611580/59203339-5dec3200-8b6c-11e9-918d-8b605f724bfa.png)

6/10/19 EP

**Comment by dhenry-KCI** [comment]
@megisys @calequin - thoughts here?

**Comment by dhenry-KCI** [comment]
@megisys - is that a no to deleting multiple records?

**Comment by dhenry-KCI** [comment]
The system only allows for individual delete.

**Comment by ABonomo21** [comment]
got it. thanks

6/25/19 ep
