### ISSUE TITLE
building - major grading - under review/pending applicant action

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1096]
drecostest was reviewed as resubmit, then under reviews, i was able to approve all reviews without the resubmit being completed by the applicant. i did not capture this in a screenshot but can always recreate if needed.

![image](https://user-images.githubusercontent.com/4129185/59204163-0cdd3d80-8b6e-11e9-9142-8a14453a9632.png)

245705.

ep/em 6/10/19

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/59204214-2d0cfc80-8b6e-11e9-8058-4f41526e6987.png)

**Comment by megisys** [comment]
The Cost Estimate should never be resubmit. This is the error

**Comment by ABonomo21** [comment]
VIJAY WOULD UPDATE THE COST ESTIMATE AND WOULD NOT SELECT RESUBMIT IF THE ESTIMATE IS INACCURATE OR INCOMPLETE
