### ISSUE TITLE
IPS- All Arrow Button

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1098]
Does the back/ forth arrow button functionable to move from permit to permit within numerical order? 

245705 - wanting to toggle to 245706? 

![image](https://user-images.githubusercontent.com/47611580/59205049-f801a980-8b6f-11e9-884e-ddea2b3932de.png)

6/10/19 EP

**Comment by dhenry-KCI** [comment]
@ABonomo21 the Arrows allow the user to move the next and previous AP# for the AP Type currently being reviewed. The error you received above was because there was no next or previous AP#. @calequin please confirm.

**Comment by calequin** [comment]
that is correct. this only goes in order of the grid filter. For example if I search for all Grading Permits then the next button will be the next item on the grid view. Unless you filter the tab to be ascending or descending.

**Comment by ABonomo21** [comment]
I don't like this... but apparently it is what it is.... 

6/20/19 EP
