### ISSUE TITLE
IPS - PreProd - Planning - Review Name

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1099]
Erroneous cryptic bracketed information following the "Review Name" should be deleted:
![image](https://user-images.githubusercontent.com/4129185/59212930-acf09200-8b81-11e9-9454-f066a945ef56.png)
GH/AM

**Comment by megisys** [comment]
This after Go Live Step

**Comment by dhenry-KCI** [comment]
Duplicate #1044

**Comment by mmbanong** [comment]
This is part of the post go live issues to resolve--per Dan

**Comment by dhenry-KCI** [comment]
Leaving label to address post go live. - closing issue for now.
