### ISSUE TITLE
Planning - BOA - Generated Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#110]
The user should always manually add the following reviews for all BOA applications:
- Board of Education
- Historic Review
- Soil Conservation District
- Monocacy River Board

**Comment by megisys** [comment]
This has been adjusted. Ready for Retest

**Comment by dhenry-KCI** [comment]
![boa reviews](https://user-images.githubusercontent.com/4129185/53756482-39a2fa00-3e87-11e9-83e9-8f495dee325f.PNG)
Planning - BOA - Variance A/P # 237453 - SCD - Soil Conservation District Review still generated

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
![boa review fixed](https://user-images.githubusercontent.com/4129185/53835505-a7205a80-3f5b-11e9-8d37-74fdb84bad51.PNG)
Fixed - KVanaman - 3/5/19
