### ISSUE TITLE
IPS- PreProd- Code Enforcement - Code Violation Duplications 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1102]
Case 9438 - 

Code violations under the inspection triplicated 
![image](https://user-images.githubusercontent.com/47611580/59216372-77e83d80-8b89-11e9-9421-c084491f9723.png)

Hansen 7 Only in once

![image](https://user-images.githubusercontent.com/47611580/59216401-833b6900-8b89-11e9-939f-e4025e99711e.png)

**Comment by megisys** [comment]
This is correct. 2 Violations of the same type against 2 inspections. this is as per Hansen 7.

**Comment by dhenry-KCI** [comment]
Agreed training issue.
