### ISSUE TITLE
IPS - PreProd- Code Enforcement - Inspections

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1103]
When resulting inspections if an inspection passes or is waived it should not generate a follow up inspection 

![image](https://user-images.githubusercontent.com/47611580/59218526-7705da80-8b8e-11e9-9550-5d4db053e170.png)

**Comment by ABonomo21** [comment]
Because the waived inspections keep generating it is getting stuck in the loop of the incorrect milestone- passed inspections should not go back to citations.

**Comment by calequin** [comment]
fixed formula to include waived. Fixed in TEST

**Comment by ABonomo21** [comment]
this is not corrected- the waived and passed inspections still generated again

![image](https://user-images.githubusercontent.com/47611580/59611775-f5f89700-90e9-11e9-9e6b-c371c1f46431.png)

**Comment by calequin** [comment]
added "FOLLP" code to the formula and it progresses correctly. If one fails then goes back to citation if it was the second time around. First time around goes to hearing prep. If passed then they go to admin closure.

**Comment by ABonomo21** [comment]
tried to test and it when through straight to Admin Closure after adding cpro 

![image](https://user-images.githubusercontent.com/47611580/60047080-d556b100-9696-11e9-806f-3b8601135334.png)

**Comment by calequin** [comment]
Type of code enforcement was not selected in the detail page causing the inspection to not populate. this caused the cpro to move forward to admin closure. do we need a section complete field in this detail page and make it required? Also progressed the application with the fees manually added and correct inspections and it followed the milestone progression. Let me know how to proceed

**Comment by ABonomo21** [comment]
passed and waived inspections should not duplicate- only failed or follow up.

**Comment by calequin** [comment]
There is a bit of confusion here. Unlike the other modules inspection being failed will actually advance the case into other milestones for further case workflow. If an inspection passes then it will go straight to admin closure since the violation is being "handled". If it goes back to the cycle then the inspections will auto populate again because a followup needs to happen. We can discuss further if needed.

**Comment by ABonomo21** [comment]
corrected- checked case 10028
![image](https://user-images.githubusercontent.com/47611580/65440066-2ee58d80-ddf6-11e9-9455-ba2c382d73dc.png)
