### ISSUE TITLE
IPS Pre Prod-ResTownhouses-Did not stop for Licensed Homebuilder

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1104]
This Res Townhouse building permit did not stop/hold up the permit for a licensed HomeBuilder to be the primary applicant. However it did automatically charge the HomeBuilder Fee. Building permits for new dwellings must be applied for by licensed homebuilders or the property owner with a landowners affidavit. this also happened with #245722 & #245723-AW
#245721
![image](https://user-images.githubusercontent.com/47611580/59277652-96544480-8c2e-11e9-9a74-7c383f9c7e8d.png)
![image](https://user-images.githubusercontent.com/47611580/59277835-dddad080-8c2e-11e9-9cc2-ec41bf78fd30.png)

**Comment by imazlout** [comment]
ready for test

**Comment by ABonomo21** [comment]
flagged for hb lic req. 
![image](https://user-images.githubusercontent.com/47611580/59452228-41a1fc80-8ddb-11e9-8a3b-fda74c47228c.png)
