### ISSUE TITLE
IPS Pre Prod-Res Townhouse-DUSWM Review did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1105]
The DUSWM Review for Res Townhouses did not generate. this also happened with #245722  & #245723-AW
#245721
![image](https://user-images.githubusercontent.com/47611580/59279217-89852000-8c31-11e9-933d-639fe669ff07.png)

**Comment by megisys** [comment]
It shouldnt.. Should be on the capacity permit

**Comment by ABonomo21** [comment]
DUSWM should not populate as a review agencies- they should have a capacity permit auto generate. Can you confirm this happened? 

Building permit should not issue until capacity permit is issued.

**Comment by ABonomo21** [comment]
Capacity auto generated with review and building permit did not issue until capacity was issued/closed(both happened at the same time. I think that happened because I did not insert capacity fees)-AW
![image](https://user-images.githubusercontent.com/47611580/59607815-07d63c00-90e2-11e9-82ec-cf6de50ebd1e.png)
![image](https://user-images.githubusercontent.com/47611580/59607788-f9882000-90e1-11e9-9818-e67460a83beb.png)
