### ISSUE TITLE
R4C Non-Residential Details 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1106]
Logged By-MCoffman
Permit# 245727

This grid should be moved under construction details
![image](https://user-images.githubusercontent.com/47611580/59276217-e2ea5080-8c2b-11e9-83fb-648561982d23.png)

Please remove the following from Business Use Drop Down
ACCESSORY DWELLING UNIT
AG BLDG EXEMPT PER BLD CODE
AG NONEXEMPT PRODUCT PROCESSING
BINGO
FIRE DEPARTMENT
GAMING
RAFFLE
TIP JAR OFF PREMISE
TIP JAR ON PREMISE
ABOVE GROND TANK
INGROUND TANK
*ALL HOME OCCUPANCY USES*
BAZZAAR
CARNIVAL 
CIRCUS
CORN MAZE
CRAFT FAIRS
CHRISTMAS TREE SALE
FESTIVAL
PUBLIC GATHERING
JUNKYARD
LANDFILL
MUSIC FETIVAL
PARK/RECREATION
POW WOW
PUMPKIN
RODEO
SEASONAL OUTDOOR ACTIVITY
TEMPORARY OUTDOOR EVENT
TENT REVIVALS
TANKS WATER STORAGE
*ALL RESIDENTIAL USES*
ESTABLISHED ZONING USE ONLY

Can we make this a note at the top of this section
![image](https://user-images.githubusercontent.com/47611580/59281308-0ebe0400-8c35-11e9-8072-5a7ca5aacd02.png)

Can we group these together 
![image](https://user-images.githubusercontent.com/47611580/59281188-d4ecfd80-8c34-11e9-98d2-f407a8b33c47.png)

Can we group these drop down boxes under the check box
![image](https://user-images.githubusercontent.com/47611580/59281387-2dbc9600-8c35-11e9-900a-a59ce0bd68a7.png)

Can we move the Type of Storage drop down box up, and then align up all of the check boxes 
![image](https://user-images.githubusercontent.com/47611580/59280517-b5090a00-8c33-11e9-8529-b280e7f24f96.png)

"Y/N" needs to be removed
![image](https://user-images.githubusercontent.com/47611580/59280633-e41f7b80-8c33-11e9-9482-c05725b5150d.png)

Can we line up the drop down boxes and the check boxes in this section; can we make one side drop down boxes and one side check boxes
![image](https://user-images.githubusercontent.com/47611580/59283476-9f4a1380-8c38-11e9-8949-37a886e79d90.png)

Can we group the grids together
![image](https://user-images.githubusercontent.com/47611580/59281553-75432200-8c35-11e9-966f-9300a9941b28.png)

This is a Non-Residential Permit, we need to adjust the wording for Non-Res
![image](https://user-images.githubusercontent.com/47611580/59282109-5ee99600-8c36-11e9-82ab-60d704112294.png)

Can we line up these check boxes
![image](https://user-images.githubusercontent.com/47611580/59282152-7032a280-8c36-11e9-858c-51dab3b39b3b.png)

**Comment by calequin** [comment]
Fixed filter codes
moved grid under construction details
moved acre note up top
cant group checkboxes as this is part of the tab order and the product does not support this type of grouping because of screen rendering
Y/N Removed
Non residential verbiage - Need information on what to add

**Comment by ABonomo21** [comment]
Logged by MCoffman

The Business Uses need to be removed.
Please remove the following from Business Use Drop Down
ACCESSORY DWELLING UNIT
AG BLDG EXEMPT PER BLD CODE
AG NONEXEMPT PRODUCT PROCESSING
BINGO
FIRE DEPARTMENT
GAMING
RAFFLE
TIP JAR OFF PREMISE
TIP JAR ON PREMISE
ABOVE GROND TANK
INGROUND TANK
ALL HOME OCCUPANCY USES
BAZZAAR
CARNIVAL
CIRCUS
CORN MAZE
CRAFT FAIRS
CHRISTMAS TREE SALE
FESTIVAL
PUBLIC GATHERING
JUNKYARD
LANDFILL
MUSIC FETIVAL
PARK/RECREATION
POW WOW
PUMPKIN
RODEO
SEASONAL OUTDOOR ACTIVITY
TEMPORARY OUTDOOR EVENT
TENT REVIVALS
TANKS WATER STORAGE
ALL RESIDENTIAL USES
ESTABLISHED ZONING USE ONLY
![image](https://user-images.githubusercontent.com/47611580/59517230-14178a80-8e91-11e9-975e-401feb3e29be.png)


This section needs to be cleaned up. If we can't group the check boxes on one side and the drop down boxes on one side then we need to try and line them up so that the check box lines up with the corresponding drop down box. I think this section will look confusing to customers. 
![image](https://user-images.githubusercontent.com/47611580/59516764-13cabf80-8e90-11e9-850c-fbd0333c3253.png)

**Comment by calequin** [comment]
Fixed in test
code definition has been added correctly.
added verbiage to checkboxes for customers to understand
![image](https://user-images.githubusercontent.com/47603568/59943904-134e9d80-9429-11e9-937b-ed5074af6ede.png)

**Comment by ABonomo21** [comment]
Permit# 245887-Issue Fixed in test-MCoffman
