### ISSUE TITLE
R4C-ResBldg-Site Location Details Box (Excel Issue #62)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1107]
For ResBldg we would like to add this to the additional details area header.-AW
"Please list all other addresses for related townhouses, condo/apartment units, and live works buildings. "
![image](https://user-images.githubusercontent.com/47611580/59283662-e6380900-8c38-11e9-8f43-ae6be34b07f5.png)

Can this details box be changed per permit type? If so, we would like to add this to trade permits. 
"Please list associated building permit number."

**Comment by megisys** [comment]
No this is not possible. This is not its intended purpose

**Comment by ABonomo21** [comment]
This was per Ashlye-we'll need to check with her on how to proceed. Either way we go, we need a notes box like I described in order for us to be able to make sure all the correct permits get linked together. -AW

**Comment by ABonomo21** [comment]
@calequin can you check with Dan West on this - it is important for us to have this primarily for townhouses and multifamily permit applications.

**Comment by calequin** [comment]
@ABonomo21 adding to the list of enhancement for Dan West. A work around can be adding a box in the detail page for additional information. Let me know if we should proceed with a detail page box

**Comment by calequin** [comment]
added field box to apartment and townhouse detail page in order to capture this information.

**Comment by ABonomo21** [comment]
looks good 
![image](https://user-images.githubusercontent.com/47611580/60047637-2e731480-9698-11e9-8f44-79e6d24129d5.png)
