### ISSUE TITLE
 Case- Zoning - Migration - Missing PDFs

### ISSUE THREAD

**Issue by kvanaman** [kcigeospatial/Fred_Co_Land-Management#1109]
![image](https://user-images.githubusercontent.com/51714100/59287204-34e8a180-8c3f-11e9-8944-714e7281b1f5.png)
![image](https://user-images.githubusercontent.com/51714100/59287216-3b771900-8c3f-11e9-8c0c-fcf2dcd6f6d6.png)

PDFs did not migrate on this Zoning Case and also 1 of the attachements in IPS will not open.
KEV

**Comment by ABonomo21** [comment]
all attachments went over in pristine 
![image](https://user-images.githubusercontent.com/47611580/65437448-cf857e80-ddf1-11e9-9607-ced371b67383.png)
