### ISSUE TITLE
Case - Liquor Violation - Case Detail Pages

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#111]
On the Case Details tab for a Liquor Violation, please hide the following items. They are not used:

- Citation Tracking
- Letters and Agencies
- Motion Tracking Details
- Other Hearing Details
- Report Details

Reported by Ashley Kneessi 2/14/19

**Comment by dhenry-KCI** [comment]
Confirmed Closed by P. Bussard
