### ISSUE TITLE
Ips Pre Prod-ResTownhouse-Major Grading did not auto generate.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1110]
The Major Grading permit did not auto generate on the first townhouse unit.-AW
#245721
![image](https://user-images.githubusercontent.com/47611580/59289168-6bc0b680-8c43-11e9-9ba3-2b7a0f0c9d8a.png)
![image](https://user-images.githubusercontent.com/47611580/59289185-75e2b500-8c43-11e9-8907-96dd72b442ba.png)

**Comment by ABonomo21** [comment]
created a town house "first in unit" and it did not populate a grading permit at all... 

![image](https://user-images.githubusercontent.com/47611580/59460408-03add400-8ded-11e9-9250-fbc059045706.png)

I purposly did not enter any site area because no matter what the disturbed or cut fil is town houses are going to be major because they will always exceed the minor requirement.

**Comment by ABonomo21** [comment]
Partially fixed-The Major Grading auto generated on the Initial Unit in the row (which is correct). however another Major Grading generated on the second unit in the row. The Major Grading should only generate if the "Initial Unit in Row" is checked.-AW
#245794-Initial Unit in Row
![image](https://user-images.githubusercontent.com/47611580/59611891-27716280-90ea-11e9-9e04-9783d6fb2504.png)
![image](https://user-images.githubusercontent.com/47611580/59611661-b16cfb80-90e9-11e9-86ca-a9ef1b0c9cb3.png)

#245800-Second Unit in row
![image](https://user-images.githubusercontent.com/47611580/59612364-f180ae00-90ea-11e9-9d0e-a21b9358a322.png)
![image](https://user-images.githubusercontent.com/47611580/59612378-f6ddf880-90ea-11e9-8c36-bf6d304da15b.png)

**Comment by megisys** [comment]
BP_CreateMinorGrading_AOC Formula Updated..

**Comment by ABonomo21** [comment]
fixed in test-AW
initial unit
![image](https://user-images.githubusercontent.com/47611580/59708805-8c54b780-91d3-11e9-8445-cb4f39dfd1eb.png)
second unit
![image](https://user-images.githubusercontent.com/47611580/59708840-94acf280-91d3-11e9-8571-a5f0e35b7800.png)
