### ISSUE TITLE
R4C-ResBldg details page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1111]
Can we move this note up under the header?-AW
![image](https://user-images.githubusercontent.com/47611580/59289734-cd355500-8c44-11e9-9ede-ea0ce6bddb85.png)

Can we swap the places of these two? That way all the dropdown bars are together.
![image](https://user-images.githubusercontent.com/47611580/59289847-0f5e9680-8c45-11e9-88ac-fa19ff20aef0.png)

**Comment by ABonomo21** [comment]
Septic section can have the "For Residential Use..." note removed since this is for RESBldg-AW
![image](https://user-images.githubusercontent.com/47611580/59291849-be9d6c80-8c49-11e9-8d91-c8a565c46a44.png)

**Comment by calequin** [comment]
removing this from the detail page will also remove it from the non res all together since this detail page is shared.

**Comment by ABonomo21** [comment]
everything is good- okay this the "resuse being on resbldg we will confirm at completeness check that all applicable details are completed
