### ISSUE TITLE
R4C-ADU Details page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1113]
Can we add a note with the "Special Exception Granted?" to make it say "Special Exception Granted? If yes, please reference the Board of Appeals Case Number in the Description Box"  -AW
And can we change the box header to "Accessory Dwelling Unit Details" ? that way it matches the other applications
![image](https://user-images.githubusercontent.com/47611580/59290985-d70c8780-8c47-11e9-843c-aac799660f9c.png)

**Comment by ABonomo21** [comment]
Logged by-MCoffman

After looking at this change, we are wondering if we could add a box under this checkbox for them to put the Planning Application Number, which could then be linked to the Related Records. Then change the note to this:
"If yes, please provide the Planning Application Number associated with your Board of Appeals Case in the box below."

**Comment by calequin** [comment]
fixed verbiage and added planning application number box

**Comment by ABonomo21** [comment]
data box looks good and the lang added however- i can not add any data in the planning application # box  anything i enters clears.

**Comment by calequin** [comment]
fixed. originally had a popup box. disabled the popup box and made it and editable field
![image](https://user-images.githubusercontent.com/47603568/59525082-06670280-8e9b-11e9-8f73-ea9f6d50bc05.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/59606268-b2e4f680-90de-11e9-8d7c-91d5c6043b07.png)
