### ISSUE TITLE
R4C-planning-plat (Excel #69)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1114]
1. too many back office details showing up.
2.  applicant can change details after application is submitted.  This must be blocked.  

![image](https://user-images.githubusercontent.com/4129185/59291092-12a75180-8c48-11e9-943b-510c839040f0.png)

MW

**Comment by megisys** [comment]
Detail Page changes are know.. This is a duplicate for that piece. as for the Required Fields missing. Nothing can be done at this stage. Need to get with Dan West

**Comment by calequin** [comment]
conditions are being worked on by county @ABonomo21 @dhenry-KCI . missing constraints are being researched.

**Comment by calequin** [comment]
Theres a couple of labels added to this issues. Here is the breakdown:
19.9 -  update will add the missing constraints to the page.
Enhancement - detail page editable fix being worked on by @megisys 
County Fix - seems like some of the conditions are displayed which is being worked on by @ABonomo21 and MW
R4C - To keep track of the label fixes

**Comment by mmbanong** [comment]
Ashlye B and Mike are working on condition visibility

**Comment by megisys** [comment]
Product Manager say the product is working as expected and this is not a change they want to introduce. County can update the Portal Description to things such as - County is Reviewing Parcel Details. Or County is doing the lawns. Etc
