### ISSUE TITLE
IPS-Preprod-planning-plat-sha not populating as reviewer

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1115]
SHA was checked off in R4C and shows up in back office but SHA review didnt generate.

![image](https://user-images.githubusercontent.com/4129185/59291517-138cb300-8c49-11e9-93c1-920779ee6618.png)

![image](https://user-images.githubusercontent.com/4129185/59291540-256e5600-8c49-11e9-8fcc-3ff049cbb84f.png)

MW

**Comment by megisys** [comment]
Believe it or not. But the logic was looking at the parcel details. I made it run off the checkbox on the detail page.

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/59444848-94c08300-8dcc-11e9-9b0e-6d8314408502.png)

![image](https://user-images.githubusercontent.com/4129185/59444903-ad309d80-8dcc-11e9-806b-a600b6516f40.png)

Fixed AM 6/13/19

**Comment by megisys** [comment]
This is Fixed
