### ISSUE TITLE
ips-preprod-planning-site-site plan type I-due dates

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1118]
due dates for Type I site plans is 3 weeks for first review, 2 weeks for resubs.  The 2nd submittal was routed for 3 weeks instead of 2.

![image](https://user-images.githubusercontent.com/4129185/59296472-1214b800-8c54-11e9-8623-618a03d069ce.png)

MW

**Comment by dhenry-KCI** [comment]
Retest failed - still generating 3 week review on 2nd submission (should be 2 week review).
-GH
![image](https://user-images.githubusercontent.com/4129185/59441800-1f05e880-8dc7-11e9-9838-fab5dde54bec.png)

**Comment by megisys** [comment]
Addressed this issue for Type 1

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/59456527-84b49d80-8de4-11e9-818b-5f98d2519016.png)

Fixed. AM 06/13/19
