### ISSUE TITLE
ips-preprod-planning-site plan-expiration fields

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1119]
filled in expiration on details page but then have to go into jod descr. to enter again in order to clear conditions.

![image](https://user-images.githubusercontent.com/4129185/59296882-fc53c280-8c54-11e9-8201-0d1fd864778f.png)

![image](https://user-images.githubusercontent.com/4129185/59296912-0a094800-8c55-11e9-8bff-940cb7e8106d.png)

![image](https://user-images.githubusercontent.com/4129185/59296927-15f50a00-8c55-11e9-9a7f-6d804ca332e5.png)

MW

**Comment by megisys** [comment]
Added Logic to copy across

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/59443251-a0f71100-8dc9-11e9-802c-a54c8be43210.png)

![image](https://user-images.githubusercontent.com/4129185/59443579-31cdec80-8dca-11e9-89a0-6eddc278109f.png)


![image](https://user-images.githubusercontent.com/4129185/59443500-182ca500-8dca-11e9-99d5-7609cb640dfa.png)

AM

**Comment by megisys** [comment]
Ready in TEST - Please mark as Ready to Deploy

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/59457293-27b9e700-8de6-11e9-8f35-84276140c8f3.png)


![image](https://user-images.githubusercontent.com/4129185/59457172-eb868680-8de5-11e9-90bf-d434c93faafb.png)

Fixed. Filled in details page and it populated in Job. Descrip. AM 6/13/19
