### ISSUE TITLE
Case - Liquor Violation - Violation Details

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#112]
On the Violation Details tab, in the grid under "Plea", **Deferred Judgement** needs to be added as an option. This is something the new Board offers since this project has begun.

Reported by Ashley Kneessi 2/14/19

**Comment by calequin** [comment]
Added to the Code Definition Management

**Comment by dhenry-KCI** [comment]
Confirmed closed by P. Bussard.
