### ISSUE TITLE
Case - swmsedcase - details page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1120]
the details page in hansen 7 and ips differ. IPS does not include the check box option for sediment control, stormwater management or ag exempt like hansen 7 does.

![image](https://user-images.githubusercontent.com/47611580/59351884-65871480-8ced-11e9-8b4c-83854ae45690.png)

Also, the ag exempt comments should just be comments

![image](https://user-images.githubusercontent.com/47611580/59351933-86e80080-8ced-11e9-9f80-c8dea0dfc9a4.png)

 #244489

tm 6/12/19

**Comment by ABonomo21** [comment]
the requirement needs to be moved prior to creation of the case itself instead of after creation.

**Comment by calequin** [comment]
fixed in test. Added details to start at creation of case. removed and expired citation tracking details
Fixed in TEST

**Comment by calequin** [comment]
fixed in preprod

**Comment by ABonomo21** [comment]
corrected #244498 tm 6/12/19
