### ISSUE TITLE
Building - NonResidential Building Permit - Review Comments

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1121]
The formatting of the DUSWMF review comments came over incorrectly. There is spacing in between each date entry, while in IPS the comments are all continuous. Can the comments be formatted correctly?

![image](https://user-images.githubusercontent.com/31770504/59361011-2cf03680-8cff-11e9-8474-78c0cebc7dce.png)

![image](https://user-images.githubusercontent.com/31770504/59361030-39748f00-8cff-11e9-9778-754afb865174.png)

![image](https://user-images.githubusercontent.com/31770504/59361054-42fdf700-8cff-11e9-8ef4-f5c71068ba91.png)

**Comment by ABonomo21** [comment]
formatting appears to be corrected for this review- will check others in migration testing 

![image](https://user-images.githubusercontent.com/47611580/59611454-5affbd00-90e9-11e9-9a33-2b2d5f768711.png)
