### ISSUE TITLE
R4C-Land Use Details page-Food Service check box is missing.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1122]
the food service check box is missing. as you can see in the screenshots in #1027 it used to be there. we need it back on R4C. Its currently there in Ips Pre Prod-AW
L244566
![image](https://user-images.githubusercontent.com/47611580/59361666-3cbc4a80-8d00-11e9-94f8-c2370bfad06a.png)
![image](https://user-images.githubusercontent.com/47611580/59362373-55793000-8d01-11e9-9b4a-fb93120b565a.png)

**Comment by calequin** [comment]
fixed in preprod
![image](https://user-images.githubusercontent.com/47603568/59363263-7f7b2400-8cfa-11e9-8dba-6a39ad15f63b.png)

**Comment by ABonomo21** [comment]
there - thanks ab
