### ISSUE TITLE
R4C Zoning Certificate Details

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1123]
Permit# 245738-MCoffman

Please remove these from Construction Type
ADDITION
ALTERATION CONVERSION
CARPORT
CELLULAR EQUIPMENT
NEW TENANT CHANGE OF USE 
CORE
DECK OVER 500 SF OR LESS
EXISTING TENANT CHANGE TO SPACE
NEW TENANT FIT OUT
FOUNDATION/SLAB ONLY
GARAGE
MINOR BUILDING PERMIT
NEW TENANT NO CHANGES
OWNER-NAME CHANGE ONLY
ABOVE GROUND POOL
INGROUND POOL
COVERED PORCH OVER 500 SF
COVERED PORCH 500 SF OR LESS
REPAIR
RETAINING WALL
SCREENED PORCH OVER 500 SF
SCREENED PORCH 500 SF OR LESS
SINGLE VISIT
SOLAR ARRAY
VANILLA BOX
WIND TURNINE
![image](https://user-images.githubusercontent.com/47611580/59361404-c91a3d80-8cff-11e9-9a53-b860a082a0ba.png)

For Building Use, please remove all options except AG BUILDING EXEMPT PER BLD CODE
![image](https://user-images.githubusercontent.com/47611580/59361490-f1a23780-8cff-11e9-92f1-81f167f0af41.png)

Can we move this box down
![image](https://user-images.githubusercontent.com/47611580/59361593-1bf3f500-8d00-11e9-90be-a1e90e616cb2.png)

Can we move this note up above the lot size box
![image](https://user-images.githubusercontent.com/47611580/59361839-7b520500-8d00-11e9-9269-f29c8613ff0d.png)

Can we line these boxes up
![image](https://user-images.githubusercontent.com/47611580/59361919-a0467800-8d00-11e9-98fd-d9b2e668493e.png)

Can we group these together a little better
![image](https://user-images.githubusercontent.com/47611580/59362007-c3712780-8d00-11e9-93c5-74cf6042427e.png)

Can we move this up
![image](https://user-images.githubusercontent.com/47611580/59363135-adfcfd00-8d02-11e9-8555-9b72cea315fc.png)

Can we add a similar note under septic information like we have on Residential and Non-Residential Permits
![image](https://user-images.githubusercontent.com/47611580/59362209-0fbc6780-8d01-11e9-9f15-69f39e9657cf.png)

**Comment by calequin** [comment]
removed filter codes from construction type
removed filter codes from building use
moved total impervious area
moved acres label up
lining boxes up - cant group these in r4c unfortunately
removed ft and added it to the same label
added how many new driveway aprons verbiage. since we cant change groupings on r4c
added label under septic

FIXED IN PREPROD

**Comment by ABonomo21** [comment]
non of these are correct in R4C...

**Comment by calequin** [comment]
fixed in test. Need information on what verbiage to add to Septic Information.

**Comment by ABonomo21** [comment]
See language below @calequin 
If installing new installation please also select Conventional or Sandmound
If connecting to existing please do not select a type

**Comment by calequin** [comment]
added verbiage in test

**Comment by ABonomo21** [comment]
need to remove Deck 500 sf or less also

![image](https://user-images.githubusercontent.com/47611580/60046160-a8a19a00-9694-11e9-8a2e-6712b49c73d6.png)


still no drop down for open or closed section driveway 
![image](https://user-images.githubusercontent.com/47611580/60046235-d5ee4800-9694-11e9-9ba4-661f3f458efa.png)

**Comment by calequin** [comment]
fixed in preprod. removed 500 sf or less and added open or closed dropdown
![image](https://user-images.githubusercontent.com/47603568/60102154-244e2600-972b-11e9-9216-e09cd5828ffe.png)

**Comment by ABonomo21** [comment]
Everything is fixed except the drop down for open or closed driveway-AW
![image](https://user-images.githubusercontent.com/47611580/60108378-806a7780-9736-11e9-90a5-b6591612d11e.png)

**Comment by calequin** [comment]
fixed in preprod and regenerated detail.

**Comment by ABonomo21** [comment]
fixed!-AW
![image](https://user-images.githubusercontent.com/47611580/60124328-5b3a3100-9757-11e9-9267-6bba4a12d68d.png)
