### ISSUE TITLE
CASE - FRO - DETAILS PAGE

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1124]
the details page in hansen 7 and ips differ. IPS does not include the check box option the type of code enforcement like hansen 7 does.

![image](https://user-images.githubusercontent.com/47611580/59362678-e18b5780-8d01-11e9-9181-2e956ff5a631.png)

![image](https://user-images.githubusercontent.com/47611580/59362424-69bd2d00-8d01-11e9-876a-9fa5cacb6342.png)

tm 244496 6/12/19

**Comment by ABonomo21** [comment]
similar to item #1120

**Comment by calequin** [comment]
added to start case. expired citation tracking FIXED IN PREPROD

**Comment by ABonomo21** [comment]
corrected tm 6/12/19 #244497
