### ISSUE TITLE
case - swmsed - related records - error message

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1125]
when trying to go to related records tab eric gets the following error message:

![image](https://user-images.githubusercontent.com/47611580/59363657-83f80a80-8d03-11e9-94c7-0a9af68ec33e.png)

**Comment by dhenry-KCI** [comment]
@calequin - can you tell us the question?

**Comment by calequin** [comment]
@dhenry-KCI  my apologies my question must've not saved. Can you get me a bigger screenshot of this issue? The screenshot is blurry and cant tell what the error says.

**Comment by dhenry-KCI** [comment]
Thanks @calequin - let me see what i can dig up

**Comment by dhenry-KCI** [comment]
Assigning to myself - follow-up with Eric D. / Tiffany on error message.

**Comment by ABonomo21** [comment]
this was not an issue that i was able to replicate when I was sitting beside Eric downstairs. Mine worked, his didn't. Would suggest following up with him.

TM 6/25/19

**Comment by dhenry-KCI** [comment]
Per tiffany closing.
