### ISSUE TITLE
Town Review Assignements

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1126]
Town reviews populate on the permit applications and populate department assignment for the specific towns. 
![image](https://user-images.githubusercontent.com/47611580/59363910-01237f80-8d04-11e9-8259-423f73b746b7.png)

We need to configure the "service provider" data so that the individual towns based on department designation can see their review assignments.

**Comment by megisys** [comment]
Need Martin to Set up a Generic account for each Town. Once this is done I will set up a change to assign to the Generic Account.

**Comment by dhenry-KCI** [comment]
CTT - will not move contact record. When we update this we will need to update in PreProd so we can maintain history

**Comment by mmbanong** [comment]
Generic account for each Town have to be setup as portal users
per Dan. Wait until Dan returns

**Comment by calequin** [comment]
List of service providers need to be tested in r4c and logged in.

**Comment by ABonomo21** [comment]
Need to have a larger discussion about town procedure. @dhenry-KCI

**Comment by megisys** [comment]
Not Needed anymore
