### ISSUE TITLE
Case - Fire Case - ADMINREV Result Code Options

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#113]
On a Fire-Case, the NOVREV and ADMINREV result code options popup includes too many options. The options should be limited to the standard for Cases: Approved/Complete, Not Applicable.

![image](https://user-images.githubusercontent.com/31770504/53349969-2ffc1e00-38ec-11e9-96ce-cf0a9bf06105.png)

Reported by Leslie Lenhart 2/13/19

**Comment by ABonomo21** [comment]
corrected
