### ISSUE TITLE
Certificate of Completion  -Demo

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1131]
I had previously said we issue a certificate of completion on Demo permits and we do not. 

Please remove the pending certificate milestone from demo. should just go to final (closed)

![image](https://user-images.githubusercontent.com/47611580/59364583-11882a00-8d05-11e9-9077-40545da46d90.png)

**Comment by megisys** [comment]
Duplicate

**Comment by ABonomo21** [comment]
251215- demo permit - NO COC should be available 

![image](https://user-images.githubusercontent.com/47611580/68032707-a085e680-fc94-11e9-9e36-5402d7e1af1b.png)

![image](https://user-images.githubusercontent.com/47611580/68032729-ac71a880-fc94-11e9-909d-16a00712c568.png)

11/1/19 EP

**Comment by TaraF** [comment]
No COC on DEMOLITION available for on demand now.

Ready for re-test.

**Comment by ABonomo21** [comment]
fixed 251305
