### ISSUE TITLE
case - fro/swmsed - applications added information - migration

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1133]
the following information did not migrate over to Ips from hansen

![image](https://user-images.githubusercontent.com/47611580/59365732-0c2bdf00-8d07-11e9-9c9d-7da4d0ded200.png)

tm case #11198 6/12/19

**Comment by calequin** [comment]
content manager changed and added affected application checkboxes.
![image](https://user-images.githubusercontent.com/47603568/59399025-0dd1c300-8d58-11e9-94e2-f7e4e2d74ad5.png)

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/59399278-1080e800-8d59-11e9-9de2-6344590a5886.png)

**Comment by ABonomo21** [comment]
now populated - ab
