### ISSUE TITLE
IPS -PreProd- Tanks

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1134]
Was able to progress a tank permit to under review without the Priority code being filled in - should redline

![image](https://user-images.githubusercontent.com/47611580/59366699-b35d4600-8d08-11e9-8fe3-0e22cb38f65e.png)

![image](https://user-images.githubusercontent.com/47611580/59366720-bce6ae00-8d08-11e9-9294-3cd5f84ad354.png)

**Comment by megisys** [comment]
Now hold up at Completeness Check

**Comment by ABonomo21** [comment]
corrected
