### ISSUE TITLE
Case - Fire Case - Annual Inspections

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1135]
We need to explore the options behind the Fire Marshal's Annual Inspections. Ideally they would like a new Case to be created and scheduled automatically for each annual inspection. When they run the report for these cases they don't want the old previously failed/passed inspections from the previous year to appear on the current year's report. 

We may need to have a follow-up conversation with the Fire Marshal to solidify the requirements surrounding this and if it is possible.

**Comment by calequin** [comment]
Theres two ways to go about this. If there is a current report then we need to route this over to the reporting team to add the criteria. If they are searching via query then they can filter by date as well. Either way all inspections get logged in the system in order to keep a history.
