### ISSUE TITLE
R4C - Non Res- Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1136]
The occupancy load section on non-res needs to be back office only 
-this is something the reviewer should fill in when applicable for non- res assembly  use 
![image](https://user-images.githubusercontent.com/47611580/59376508-40f76080-8d1e-11e9-96aa-d512156085d4.png)

**Comment by megisys** [comment]
Removed from r4C

**Comment by ABonomo21** [comment]
thank you
