### ISSUE TITLE
Details need for COO and COC's 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1137]
Inserted this Git Hub Ticket for Ashlye, Megan and Abbie to double check 
Please check that the  following a/p types have detail pages for zoning use and building use, a section for code edition to be inserted 

Resuse
Resbldg
NonRes
Trailer
Tank
Sign - should only generate zoning use unless freestanding or monument sign then it should generate a building use detail page

**Comment by ABonomo21** [comment]
Res Use-confirmed-AW
![image](https://user-images.githubusercontent.com/47611580/59512082-f1cc3f80-8e85-11e9-9183-65f56da95429.png)
![image](https://user-images.githubusercontent.com/47611580/59512104-fe509800-8e85-11e9-8619-7ca1ea252c7c.png)

Res Bldg-confirmed
![image](https://user-images.githubusercontent.com/47611580/59512552-f6ddbe80-8e86-11e9-9ba4-51ad1916c8cb.png)
![image](https://user-images.githubusercontent.com/47611580/59512577-01985380-8e87-11e9-8851-c6eda5356284.png)

**Comment by megisys** [comment]
TRAILER TO BE FIXED, TANK AND SIGN.

**Comment by megisys** [comment]
Signs fixed. But the other two never had code edition in Hansen 7 and this is net new. Please let me know how to proceed. as no data to come across.

**Comment by ABonomo21** [comment]
Not needed for tanks and signs we do not issues coc's now we will not start, may consider in the furture.
