### ISSUE TITLE
Sprinkler Rules

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1138]
Need to send dan the rules for spinkler - resbldg, nonres, resuse and trailer

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/59459007-c267f500-8de9-11e9-8569-6269bac1f899.png)

Resbldg - ALWAYS requires a sprinkler suppression permit (regardless of how supression is marked, even though it should be marked new- i will add a note for staff to make sure it says new if the applicant marked it wrong. 

Resuses- For **construction type** of addition with the **type of addition** as, where "existing" system was marked then the sprinkler suppression permit requirement should populate, it should also populate if the applicant marked "new"
For **construction type** of Alteration/conversion with **type of alteration** as, where "existing" system was marked then the sprinkler suppression permit requirement should populate, it should also populate if the applicant marked "new"

**Comment by ABonomo21** [comment]
Non- Residential and Trailer Permits the requirement for sprinkler is based on a number of factors including use and occupancy load which needs to be determined by plan review. Therefore, if there is a requirement for a sprinkler system to be installed the plans review will need to manually add the condition to the permit. I will place this in the SOP instructions at the review milestone for these a/p types

**Comment by kellyjj** [comment]
adding myself to the assigned list.

**Comment by dhenry-KCI** [comment]
redline that a fire permit is required for a res. building permit. She be enforced immediately after issuance of the building permit (status check that sprinkler permit is created if not required log of not required)

**Comment by kellyjj** [comment]
I am currently working on this

**Comment by kellyjj** [comment]
I have attached this status check to the resbldg + resuses ap types, on the final inspection m/s (which is hte next m/s after issuance)

this is ready for retest.

**Comment by ABonomo21** [comment]
Testing  in pre prod an alteration permit, 245653 for a finished basement- marked existing sprinkler and requirement for a fire permit did not show up at the inspections milestone nor at the final inspection milestone. 

![image](https://user-images.githubusercontent.com/47611580/60525550-8f17d800-9cbc-11e9-977c-be9683d29523.png)

![image](https://user-images.githubusercontent.com/47611580/60525507-77405400-9cbc-11e9-8768-2fe2bb21191b.png)

![image](https://user-images.githubusercontent.com/47611580/60525528-81fae900-9cbc-11e9-9afc-0ecb7f26bdf0.png)

**Comment by ABonomo21** [comment]
The permit requirement should populate at the inspection milestone for all required permits- not at the final inspection milestone. JUST AN FYI

**Comment by ABonomo21** [comment]
tested addition # 247922- finished floor area with existing sprinkler and the requirement also did not populate- 

![image](https://user-images.githubusercontent.com/47611580/60526398-511bb380-9cbe-11e9-856e-94270a08c1a5.png)

![image](https://user-images.githubusercontent.com/47611580/60526482-6db7eb80-9cbe-11e9-8f21-c9db44445994.png)

![image](https://user-images.githubusercontent.com/47611580/60526504-78728080-9cbe-11e9-8fec-2b9feab3fc78.png)

**Comment by ABonomo21** [comment]
testing accessory #247924 with sprinkler system marked as new- the requirement did not populate 

![image](https://user-images.githubusercontent.com/47611580/60526845-241bd080-9cbf-11e9-9217-74f108b9a663.png)


![image](https://user-images.githubusercontent.com/47611580/60526872-31d15600-9cbf-11e9-960e-37b8a52ddb30.png)

![image](https://user-images.githubusercontent.com/47611580/60526919-47468000-9cbf-11e9-8118-e8e488647ee3.png)

**Comment by ABonomo21** [comment]
So far in testing the only application that has worked is RESBLDG because all new and replacement RES BLDG apps require a sprinkler permit. 

Why are none of the others working???

**Comment by ABonomo21** [comment]
Unable to Test NONRES because of the drop downs will not open on the details page to select the sprinkler type-

**Comment by ABonomo21** [comment]
Need to set up a meeting to discuss with Dan the Sprinkler Requirement functionality for Condo and Apt Units.

**Comment by megisys** [comment]
Adjusted for RESUSE and Moved to Inspections

**Comment by ABonomo21** [comment]
ResUse-Basement Finish-Sprinkler Permit requirement generated-AW

**Comment by ABonomo21** [comment]
appears to be correct will continue to check thought out training
