### ISSUE TITLE
R4C- Special Events - Intake Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1139]
User needs to provide Event Start Date and Event Name prior to submitting request for review.

Please update R4C details page to include these fields with the initial submittal

**Comment by calequin** [comment]
added new detail page in TEST. need to deploy to preprod
![image](https://user-images.githubusercontent.com/47603568/59517208-a8312400-8e88-11e9-81ff-919c6c1b1d6a.png)

**Comment by JuanitaMiles** [comment]
OK - Appears on R4C. Would like make the Number of Days field a drop down field with options 1 through 7.

**Comment by calequin** [comment]
@JuanitaMiles the number of days field is tied down to a number format, unfortunatly changing this to a set of numbers will cause a good amount of formula rework. This is also part of the completeness check where the county staff will change the number of days to the "approved" days according to the application. If the number of days is greater than 7 the county should be resubmitting.

**Comment by dhenry-KCI** [comment]
agreeing with @calequin - adding as a future enhancement based on go-live use.

**Comment by dhenry-KCI** [comment]
confirmed workflow with liquor board, Closing issue until after go-live
