### ISSUE TITLE
Building - Res Blg / Non-Res - Spawned Capacity Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#114]
The system should spawn capacity permit for a res or non res building. Requirements:
- The spawned capacity permit would be a child of the building permit. 
-The capacity permit should inherit the details of the building permit once spawned.
-The system should prevent the building permit from being issued until the capacity fee are paid.

**Comment by megisys** [comment]
This is added to the User Review Milestone for RESBLDG.. PLease Test

**Comment by dhenry-KCI** [comment]
Confirmed working-AW

![image](https://user-images.githubusercontent.com/4129185/53897277-c83c8600-4003-11e9-90d9-30d03fecaaf0.png)
