### ISSUE TITLE
License - Liquor License - License Class Options

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1142]
For the License Class options on the detail page, remove BA - Arena License, BCC - Conference Center,  & MEC - Microbrewery/Entertainment. Only A, B, C, DBR, and O should remain.

**Comment by calequin** [comment]
fixed in test and preprd

**Comment by JuanitaMiles** [comment]
Appears Fixed.

![image](https://user-images.githubusercontent.com/31770504/59607312-1a9c4100-90e1-11e9-8dec-a293ed071c09.png)
