### ISSUE TITLE
ips-preprod-planning-final plat-multiple fee issues

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1143]
the $58 per page mylar fee should not populate until the paperwork review/mylar review milestone, not at the beginning.  Also, this AP has two pages and should have generated $58 x 2= $116

![image](https://user-images.githubusercontent.com/4129185/59440108-68a10400-8dc4-11e9-9b82-6fc745b97bbc.png)

![image](https://user-images.githubusercontent.com/4129185/59440128-70f93f00-8dc4-11e9-85af-0ddf5c1cdc0e.png)

MW

**Comment by dhenry-KCI** [comment]
also should have generated a $29 per lot fee.

![image](https://user-images.githubusercontent.com/4129185/59440578-35ab4000-8dc5-11e9-9509-7c9e190383c6.png)

MW

**Comment by dhenry-KCI** [comment]
the mylar fees did populate correctly at the end...$116, so that $58 fee at the beginning needs to be removed.

MW

**Comment by megisys** [comment]
Confusion reins
