### ISSUE TITLE
License - Liquor License and Special Event - License Category

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1144]
Remove the Wine Only License Category option.

**Comment by calequin** [comment]
fixed in test and preprd

**Comment by JuanitaMiles** [comment]
Not Fixed for Special Event OR Liquor License in PreProd. Issue is fixed in TEST. Keeping issue open until it is ready in PreProd.

@calequin I am removing Ready for Retest label for now. Please reapply the label when the configuration has been moved over to PreProd.

![image](https://user-images.githubusercontent.com/31770504/59610630-c3e63580-90e7-11e9-9ac0-f47f6c50d9cd.png)

**Comment by megisys** [comment]
PLease Confirm in Preprod = If it is Please Close or redo in TEST and Martin will CTT
