### ISSUE TITLE
ips-preprod-planning-all plats-due dates

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1145]
second review cycle and all afterwards (3, 4, 5 etc) needs to be 2 weeks.  system generated a 3 week second review.  FYI, the first review period of 3 weeks worked correctly.

![image](https://user-images.githubusercontent.com/4129185/59441010-e44f8080-8dc5-11e9-9f23-38719b59cfea.png)

MW

**Comment by megisys** [comment]
Ready for Retest in IPS_TEST - Mark as ready to Deploy when happy

PLN_resubmissionDates_AA

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/59455115-85980000-8de1-11e9-915c-28620f3e6c52.png)


fixed-  mw
