### ISSUE TITLE
ips-preprod-planning-preliminary-due date

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1146]
2nd review and all after should be 2 weeks.

![image](https://user-images.githubusercontent.com/4129185/59447383-2205d680-8dd1-11e9-883b-5660cd3fa4b6.png)

MW

**Comment by megisys** [comment]
Ready in IPS_TEST. Please mark as ready to deploy

**Comment by dhenry-KCI** [comment]
fixed


![image](https://user-images.githubusercontent.com/4129185/59455064-6a2cf500-8de1-11e9-8458-68679fb186f2.png)

MW
