### ISSUE TITLE
ips-preprod-plat review periods

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1148]
reported this on a couple plat types already.  Appears to be a problem on all plat types.  Below is correction plat, showing second submittal being routed for 3 weeks instead of 2.  For all plats, first review is 3 weeks and all reviews after that are 2 weeks, except signature/mylar review which is 1 week

![image](https://user-images.githubusercontent.com/4129185/59452834-9abe6000-8ddc-11e9-9f45-af927ed02a34.png)

MW

**Comment by dhenry-KCI** [comment]
see below- public taking plat

![image](https://user-images.githubusercontent.com/4129185/59453108-2cc66880-8ddd-11e9-9259-45b5dd11dffb.png)


please check all work types under Plat to make sure the second and later reviews ate 2 weeks

MW

**Comment by megisys** [comment]
This was a mistake in TEST
