### ISSUE TITLE
ProjectDox- Planning Workflow - Resubmittal

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#115]
System is in an awaiting applicant revisions milestone, Project Dox not receiving the communication of the condition from IPS. Applicant shouldn't go into R4C during stage

Reviews should not be added with a null result code 

Ensure notifications are in place to prevent citizen from being notified via IPS.

**Comment by megisys** [comment]
This is partially delivered.. Need to adjust Status check and notifications.. Review Null result has been addressed

**Comment by megisys** [comment]
Added New Status Checks and Modified Notifications
