### ISSUE TITLE
License - Liquor License - Conditions on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1150]
What is the purpose of the Conditions Section on Rhythm for Civics? None of these things are required to be filled out on the application. Can they be hidden so they don't show since they don't seem to serve a purpose.

![image](https://user-images.githubusercontent.com/31770504/59454823-ea9f2600-8de0-11e9-8de8-26c59ce1deb6.png)

**Comment by calequin** [comment]
removed show in portal for everything except for notifications. fixed in test and preprd

**Comment by JuanitaMiles** [comment]
fixed
