### ISSUE TITLE
License - Liquor License - Detail Page Update

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1151]
Remove the "X" sections on the Liquor License Application Details page.

![image](https://user-images.githubusercontent.com/31770504/59455123-8892f080-8de1-11e9-81bb-63cc239d5288.png)

**Comment by calequin** [comment]
removed in test and preprod

**Comment by JuanitaMiles** [comment]
fixed
