### ISSUE TITLE
License - Special Event - Application Dates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1152]
Progressed this application all the way to an Active status/milestone. but no dates generated on the License Description.

![image](https://user-images.githubusercontent.com/31770504/59455453-3acab800-8de2-11e9-86ff-52f4fa8c8005.png)

**Comment by calequin** [comment]
fixed in TEST

**Comment by JuanitaMiles** [comment]
Confirmed fixed in TEST. 

![image](https://user-images.githubusercontent.com/31770504/59612512-360c4980-90eb-11e9-92e7-446126bc1404.png)

**Comment by megisys** [comment]
PLease Check is in PreProd. If not please do in TEST and Martin will CTT

**Comment by calequin** [comment]
confirmed fixed in test and preprod. Application was started prior to the new detail page. Expiration date looks at the number of days listed in the intake detail page and calculates the expiration date and time.

**Comment by JuanitaMiles** [comment]
appear fixed
