### ISSUE TITLE
License - Liquor License - Applicant Actions Detail Page

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1153]
Nothing loads on Penny's Applicant Actions detail page to complete a resubmittal action in the back office. This happens anytime she requests a resubmittal on any review, any milestone.

Juanita can see the detail page fine though.

![image](https://user-images.githubusercontent.com/31770504/59456275-fe985700-8de3-11e9-9463-42cf042cb223.png)

**Comment by calequin** [comment]
access control issue.

**Comment by calequin** [comment]
need to add access control for applicant action detail page to the liquor board team

**Comment by JuanitaMiles** [comment]
I have added access to the Liquor_Regular role for the newly created Applicant Actions detail page in PreProd and TEST. -JM

![image](https://user-images.githubusercontent.com/31770504/59609232-065a4300-90e5-11e9-9173-bec0da97954d.png)

**Comment by JuanitaMiles** [comment]
penny confirmed fixed. can now see the detail page
