### ISSUE TITLE
Case - Health Case - Fines Milestone

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1156]
When walking through a Health Case, the application did not stop in Fines milestone after resulting the hearing. It went straight to Awaiting Fine Payment. However, the FINEREV review still populated on the application. 

![image](https://user-images.githubusercontent.com/31770504/59462273-63a67980-8df1-11e9-88de-0a976ec39e45.png)

![image](https://user-images.githubusercontent.com/31770504/59462484-d3b4ff80-8df1-11e9-8854-4903328a1482.png)

**Comment by calequin** [comment]
added review status check to stop the milestone at the fines milestone. I also added "Health Department adds any additional fines/fees during this milestone" verbiage in the standard operating procedure. this is a catch all before accessing fees to the citizen.
Fixed in test and preprod

**Comment by JuanitaMiles** [comment]
Application stops in Fines.
