### ISSUE TITLE
ips-preprod-verification letters-subdivision-due date

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1159]
preprod generated a 4 week review period.  Should be a 2 week review period.

![image](https://user-images.githubusercontent.com/4129185/59610844-37884280-90e8-11e9-8d89-78ca0909659a.png)

MW

**Comment by megisys** [comment]
#1162 , #1163 , #1161

This is the same AP Type and Same Review.. 3 tickets with different dates ? If you have different due dates by WorkType - Please Provide the answers here. Closing Duplicates.


LORDET | LOT OF RECORD DETERMINATION | 3
-- | -- | --
PSRVER | SUBDIVISION POTENTIAL VERIFICATION LETTER | 3
SPVER | SITE PLAN VERIFICATION | 2
ZONVER | ZONING VERIFICATION LETTER | 2
