### ISSUE TITLE
Building - NONRES - Bond Release value for Code selection incorrect

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#116]
Building Permits - NonResidential: Under Applicant Actions there is a selection of “Bond Release”, this selection does not apply to this type of permit.

AP- 238416
Logged by M. Coffman

![image](https://user-images.githubusercontent.com/4104464/53508271-6f12a680-3a87-11e9-8880-83bf054a8c38.png)

**Comment by megisys** [comment]
This page servers all building permits.. Changed Language to make it clear..
![image](https://user-images.githubusercontent.com/47392306/53696387-7b06ad00-3d94-11e9-8a86-858f0ca5b8b5.png)

**Comment by ABonomo21** [comment]
Understood this is generating based on module, not a/p type. No need to change description . I would like to make sure staff understands this process, keeping it marked as training.
Related to item # 247
