### ISSUE TITLE
License - Special Event - Detail Page at Start License

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1160]
Was there a decision made to remove the Detail Page from the Start License back office for the Special Event license? The detail page exists in TEST but not currently in PreProd.

![image](https://user-images.githubusercontent.com/31770504/59611175-d44ae000-90e8-11e9-9764-0ef8d1bfe611.png)

![image](https://user-images.githubusercontent.com/31770504/59611207-e3ca2900-90e8-11e9-80d8-18fa85236289.png)

**Comment by calequin** [comment]
I dont think this has been migrated over to preprod yet

**Comment by JuanitaMiles** [comment]
@calequin OK - Will leave the labels as is for now. Please update to Ready for Retest when it has been migrated.

**Comment by calequin** [comment]
This has been migrated over but has to be tested in Test first.

**Comment by JuanitaMiles** [comment]
Look good.
