### ISSUE TITLE
ips-preprod-verification letter-zoning verification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1162]
Zoning Verify letters should have a 3 week review period, not 4 weeks.

![image](https://user-images.githubusercontent.com/4129185/59611608-98fce100-90e9-11e9-8c32-54e8c6c827e9.png)

MW

**Comment by megisys** [comment]
Duplicate.. As One Ticket for the 4 WorkTypes

**Comment by dhenry-KCI** [comment]
failed.  came up as a 2 week review.  Needs to be 3 weeks
![image](https://user-images.githubusercontent.com/4129185/59691006-5c47ed00-91b0-11e9-988f-0009ba804194.png)
MW
