### ISSUE TITLE
R4C- Plumbing Permit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1164]
The building permit check box on plumbing should read - "is this associated to a building permit?" like the electrical application 
plumbing :
![image](https://user-images.githubusercontent.com/47611580/59612410-08bf9b80-90eb-11e9-8c64-bf7afdfae397.png)

electrical:
![image](https://user-images.githubusercontent.com/47611580/59612642-6eac2300-90eb-11e9-8e53-d72314362d7d.png)

**Comment by ABonomo21** [comment]
In the back office the parent required check box should be auto populated for all plumbing and electrical and removed at completeness check by the techs if a BP is required

electrical:
![image](https://user-images.githubusercontent.com/47611580/59612776-b03cce00-90eb-11e9-8d21-354fe6590496.png)

plumbing: (missing the parent required check box - the building permit required check box should be renamed and a new check box should be added for "is this associated to a building permit?"

![image](https://user-images.githubusercontent.com/47611580/59612846-ce0a3300-90eb-11e9-9647-e1553cd62e64.png)

**Comment by calequin** [comment]
fixed verbiage
inverted check box to allows be true until completeness check
added parent required to plumbing permit checkbox
FIXED IN TEST NEED TO DEPLOY TO PREPROD

**Comment by megisys** [comment]
Check is in PreProd and TEST

**Comment by calequin** [comment]
checked in preprod and test

**Comment by ABonomo21** [comment]
partially fixed in R4C. The verbiage is correct however the note of "*Only fill in grids pertaining to your scope of work" is now at the bottom of the application. It should be up at the top like it was to provide clear instructions for the customers -AW
![image](https://user-images.githubusercontent.com/47611580/59711290-d2f8e080-91d8-11e9-893b-c29115424ad0.png)
![image](https://user-images.githubusercontent.com/47611580/59711455-2bc87900-91d9-11e9-92a9-30afb31af91c.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/59718050-e444eb80-91de-11e9-94c4-f0d40ddadc0f.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/59858601-4ae61880-9349-11e9-8bf2-e7cfefee333a.png)

**Comment by megisys** [comment]
Check this against Electrical - Need Consistent approach and language

**Comment by calequin** [comment]
not sure if this is for another fix. but this was fixed in dev needs to be deployed

**Comment by dhenry-KCI** [comment]
@calequin - can you make this language consistent between the two?

**Comment by calequin** [comment]
isnt this a backoffice checkbox? I followed up via email to Ashlye and Abbie

**Comment by ABonomo21** [comment]
need to discuss, this is not a nice to have set up a meeting with christian @dhenry-KCI

**Comment by ABonomo21** [comment]
r4c look good will have christian confirm back office code for plumbing and we will double check both plumbing and electrical again

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - is this still outstanding?
