### ISSUE TITLE
IPS PreProd- Building Detail Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1165]
Check box for New Septic? Missing on RESBLDG and NONRES- it was removed for RESUSE but this is a universal detail page and should be there 

![image](https://user-images.githubusercontent.com/47611580/59615954-7a024d00-90f1-11e9-9b04-d80d8330dea3.png)

**Comment by calequin** [comment]
Fixed in TEST
![image](https://user-images.githubusercontent.com/47603568/59698465-5c96b700-91b5-11e9-92f1-f08706623076.png)

**Comment by ABonomo21** [comment]
Fixed in Pre Prod for Res Bldg & Non Res-AW
![image](https://user-images.githubusercontent.com/47611580/59711689-9083d380-91d9-11e9-9668-718b5b0b985f.png)
![image](https://user-images.githubusercontent.com/47611580/59711738-a5606700-91d9-11e9-9840-2dbef37f0e88.png)
