### ISSUE TITLE
IPS PreProd- Building Detail Page, Gross Floor Area

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1166]
![image](https://user-images.githubusercontent.com/47611580/59616011-9c946600-90f1-11e9-85d3-a87e0ccf0f9c.png)

because this is a universal detail page Gross Floor Area Altered should have /Proposed next to it for new construction purposes

**Comment by megisys** [comment]
Fixed in preProd

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/59631450-db3c1780-9115-11e9-88b0-e7b4434fa57e.png)
