### ISSUE TITLE
Res Bldg-Condo Parent Structure-Zoning Fee is Incorrect

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1167]
Per the fee schedule the parent structure of a condo building should have the $43 zoning fee, not the $68-AW
![image](https://user-images.githubusercontent.com/47611580/59616286-217f7f80-90f2-11e9-9e10-ef86cec5b4d1.png)

**Comment by mmbanong** [comment]
Checked and the formula is using the Rate Table. The values in the Rate Table are correct
![Capture6](https://user-images.githubusercontent.com/47392173/60207526-1e883b80-9824-11e9-8b26-4335f0d3250d.PNG)
![Capture5](https://user-images.githubusercontent.com/47392173/60207527-1e883b80-9824-11e9-8a2c-a8009c5e1771.PNG)

**Comment by mmbanong** [comment]
![Capture7](https://user-images.githubusercontent.com/47392173/60207656-627b4080-9824-11e9-9622-46c0adbc7858.PNG)

**Comment by mmbanong** [comment]
Maybe the formula needs to be changed to look for the Parent Structure-Zoning Fee instead of just Zoning

**Comment by mmbanong** [comment]
Reassigned to Dan as a bug....wrong Fees

**Comment by megisys** [comment]
Needs to see effective Rate.

**Comment by megisys** [comment]
This is because the worktype for the permit was set to New. If parent structures are New but use a different Value then we will need to cocme up with a plan here.

**Comment by dhenry-KCI** [comment]
@JuanitaMiles  discuss with Ashlye B. and we can determine path forward.

**Comment by ABonomo21** [comment]
we need to have the parent permits generate the correct fee- you can determine if it is a parent structure based on the details page check box- 

please note the fees listed in the original ticket are fy19 fees and we should use fy20 values.

**Comment by mmbanong** [comment]
Ashley I am looking at the Rate table and the Zoning fees for 2018 are 68 and 43
for 2019 the fees are 70 and 44. Are these the correct fees?

![image](https://user-images.githubusercontent.com/47392173/65453279-e25b7b80-de10-11e9-9a9b-8d61dcd36a8c.png)
![image](https://user-images.githubusercontent.com/47392173/65453336-fe5f1d00-de10-11e9-932c-c8450aff5ff8.png)

**Comment by ABonomo21** [comment]
yes 70 and 44 is correct

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/66075409-8d62e800-e529-11e9-8250-86e9c178e485.png)
 see fee schedule reference - nonres fee for principle structure is different

**Comment by ABonomo21** [comment]
fixed 10.16.19
