### ISSUE TITLE
ips-preprod-APFO-exemption-closed with agency status of resub

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1168]
processed this APFO exemption.  Made DUSWM "resub" but went to closed/complete

![image](https://user-images.githubusercontent.com/4129185/59616527-9c489a80-90f2-11e9-983f-2dfa66a80018.png)

MW

**Comment by dhenry-KCI** [comment]
FYI.......tried this in Test as well.  DUSWM did not populate to test their result.  Resulted Dev Rev as resubm and it went to awaiting applicant revisions correctly.

![image](https://user-images.githubusercontent.com/4129185/59616826-301a6680-90f3-11e9-82e5-99647313c5ea.png)

MW

**Comment by mmbanong** [comment]
Checked and it seems to be doing exactly what is in the formula PLN_APFO_FROMUnderREview

![APFO](https://user-images.githubusercontent.com/47392173/60206216-006d0c00-9821-11e9-833c-cb21314d590f.PNG)

**Comment by dhenry-KCI** [comment]
fixed

![image](https://user-images.githubusercontent.com/4129185/62891136-f04ab680-bd12-11e9-9ac4-debf06166fdc.png)

MW
