### ISSUE TITLE
R4C- Edit Details

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1169]
I was able to edit details in a building permit that was in my dashboard after is was already submitted- 

i when in and added the word test in location 

![image](https://user-images.githubusercontent.com/47611580/59616714-02352200-90f3-11e9-8f7b-69c82b0af493.png)

**Comment by calequin** [comment]
currently being handled by @megisys for detail page editing. Marking this as duplicate.

**Comment by megisys** [comment]
Not being handled by Dan Grendon :) This is allowed.. It is still in Completeness Check. Only After it enters review do we close down.

**Comment by ABonomo21** [comment]
once approved they cannot make changes
