### ISSUE TITLE
Building -Fire Permit - Required Electrical Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#117]
The system is preventing the user from moving to final inspection for the fire supression permit, as it is requiring a an associated electrical permit. Electrical Permits should only be requried on Fire Alarm Permits, not Fire Suppression Permits.

AP- 237366
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/53508810-80a87e00-3a88-11e9-8368-44d921d29c09.png)

**Comment by megisys** [comment]
Removed these lines of code - Please CHeck this is right and Retest..

		'Else If (oBldgApp.WorkType.Code = "NEW" AND oBldgApp.OccupancyType.Description.Contains("NONRESIDENTIAL") AND oFireAlaramDetail.FirePermitType.Code.ToUpper.Trim() = "SUPPRSSN" AND ChildElec = False)
		'	StateCheck = True

**Comment by ABonomo21** [comment]
Issue Corrected-MCoffman

Fire Suppression Permit# 238595- was able to close permit out without Electrical Permit being required-Correct
![image](https://user-images.githubusercontent.com/47611580/53897527-53b61700-4004-11e9-888e-8ce50a1ae70c.png)

Fire Alarm Permit# 238600- Required Electrical Permit to be linked as a Child-Correct
![image](https://user-images.githubusercontent.com/47611580/53897832-f8d0ef80-4004-11e9-8f71-e8e587674507.png)
