### ISSUE TITLE
IPS PreProd- Zoning Use Details Data Migation

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1170]
The Zoning Use details page data  did not convert as it was in 7 

![image](https://user-images.githubusercontent.com/47611580/59616916-5b9d5100-90f3-11e9-8f34-5bf2fef10504.png)

![image](https://user-images.githubusercontent.com/47611580/59616929-62c45f00-90f3-11e9-977e-bfbe23b10a1c.png)

![image](https://user-images.githubusercontent.com/47611580/59616944-69eb6d00-90f3-11e9-8836-2e31cd074289.png)

**Comment by megisys** [comment]
Need AP Number

**Comment by goggansd** [comment]
If I look up the AP number provided above in the screenshot in the PreProd environment, I see the same thing on the Zoning Use details:

![image](https://user-images.githubusercontent.com/28841997/59876568-f73bf500-9371-11e9-8d77-0d96b3d3a203.png)

What is the actual issue here?

**Comment by dhenry-KCI** [comment]
@goggansd - the application is displaying the code not the description. Can we update to show the description like it is in H7.

**Comment by dhenry-KCI** [comment]
@calequin - can you update this to pull the description and not the code?

**Comment by calequin** [comment]
added zoning use description as read only for it to display the description of the code
![image](https://user-images.githubusercontent.com/47603568/65165780-0c71ff80-da05-11e9-8d60-cd3afc6f7a9d.png)

**Comment by ABonomo21** [comment]
checked zoning use pop up and they all appear to be there in test cannot check preprod 9.23.19
![image](https://user-images.githubusercontent.com/47611580/65440279-7a983700-ddf6-11e9-8d1c-8c13a999a76d.png)
