### ISSUE TITLE
Grading Permit reviews auto assign

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1171]
Need to confirm with Tiffany Martin that her reviews should auto assign. If they are to auto assign, then they need to assign to a reviewer who works here. DCrable has retired-AW
![image](https://user-images.githubusercontent.com/47611580/59617253-001f9300-90f4-11e9-8b09-cc4e09840c95.png)

**Comment by megisys** [comment]
This is right Tiffany wanted it this way for now..

**Comment by mmbanong** [comment]
Who should these reviews be assigned to?

**Comment by ABonomo21** [comment]
Eric Dodson until Dave's job is filled...it may be a while.

**Comment by mmbanong** [comment]
Changed rewiew assignment to Eric Dodson
![Review Assignment](https://user-images.githubusercontent.com/47392173/60282978-26081d00-98d6-11e9-9d55-1d28c562f515.PNG)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/62052716-0ec59380-b1e4-11e9-9c33-53f03552b5cc.png)
