### ISSUE TITLE
Blanket - Project /Planning - Data Conversation

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1174]
Where did the project/planning details from H7 go in IPS 11??
![image](https://user-images.githubusercontent.com/47611580/59617886-2265e080-90f5-11e9-965d-2ae8b2b15e34.png)

**Comment by megisys** [comment]
They live under Project

![image](https://user-images.githubusercontent.com/47392306/59785771-b1a8fa80-9293-11e9-82ef-8f2ea39ba487.png)

**Comment by ABonomo21** [comment]
i didnt know what i was talking about
