### ISSUE TITLE
ips-preprod-planning-in life mapping-apfo

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1175]
this AP should be under review, not process application

![image](https://user-images.githubusercontent.com/4129185/59618337-01ea5600-90f6-11e9-9686-b666c3b85a63.png)

![image](https://user-images.githubusercontent.com/4129185/59618364-0d3d8180-90f6-11e9-93d3-02ae1cd7a517.png)

MW

**Comment by megisys** [comment]
I wrote processed Applications instead of Process Applications. Fixed and Running now.

**Comment by dhenry-KCI** [comment]
fixed  MW
![image](https://user-images.githubusercontent.com/4129185/59692847-d2018800-91b3-11e9-993c-8b60b72dc697.png)
