### ISSUE TITLE
Res Bldg-ADU- School impact fees did not generate.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1179]
This ADU permit is a standalone accessory dwelling and the school impact fees did not generate like they should. The library impact fees generated correctly-AW
![image](https://user-images.githubusercontent.com/47611580/59625988-a2e20c80-9108-11e9-8bee-058998aad28b.png)
![image](https://user-images.githubusercontent.com/47611580/59626006-af666500-9108-11e9-86f9-b256dc66b813.png)
![image](https://user-images.githubusercontent.com/47611580/59626047-cb6a0680-9108-11e9-9019-a4095012aa71.png)

**Comment by mmbanong** [comment]
Fees not updated due to hard coded values in formula RES_ADU_CVF. 
Referred to Dan

**Comment by dhenry-KCI** [comment]
Training issue. Need to use Sq. footage on building detail page.

**Comment by megisys** [comment]
PLease TEST in TEST

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/60206834-89387780-9822-11e9-92e8-4119789a2a70.png)
