### ISSUE TITLE
Building - Fire Permit - Required Building Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#118]
The system should require a parent building permit for Fire Permits (Suppression or Alarm), before the user can apply- this should be enforced at completion check. IN the 1% of scenarios that don't require a parent building permit the tech would waive the required permit during completeness check.  

AP237366 (able to progress all the way to final inspection)
Logged by A. White

**Comment by ABonomo21** [comment]
Issue Corrected-MCoffman

Fire Suppression System-238595
![image](https://user-images.githubusercontent.com/47611580/53895810-d341e700-4000-11e9-9d20-9d0db9f4790a.png)

Fire Alarm 238600
![image](https://user-images.githubusercontent.com/47611580/53897234-b35ff280-4003-11e9-9e23-56ed603f33c6.png)
