### ISSUE TITLE
PreProd Non-Residential Building Fees/Review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1180]
Building fee did not generate; Permit# 245814-MCoffman

$891.45 fee should have generated for Building
![image](https://user-images.githubusercontent.com/47611580/59626123-0ff5a200-9109-11e9-8400-6bef3633cbf3.png)

Building Review did not generate as well
![image](https://user-images.githubusercontent.com/47611580/59626417-d2454900-9109-11e9-9112-8b0ccd15f908.png)

**Comment by dhenry-KCI** [comment]
@mmbanong, @megisys  the building review fee did not populate which is 0.21 * the sq. footage (which = $891.45 for this example)

**Comment by mmbanong** [comment]
Made changes to formula NONRESBLDG_Fee_BLDGMinimum_AOC

**Comment by ABonomo21** [comment]
Permit# 245887 in Test-Not corrected; Building fee still not generating. Also testing in PreProd Permit#246883-MCoffman
![image](https://user-images.githubusercontent.com/47611580/60105656-b1947900-9731-11e9-806e-dd91e78f7f29.png)

**Comment by ABonomo21** [comment]
Fee's fixed in Pre-Prod and Test; Building review still did not generate in both-MCoffman

Permit# 246887-PreProd
![image](https://user-images.githubusercontent.com/47611580/60120414-b87db480-974e-11e9-8fae-f120b6e2527f.png)

![image](https://user-images.githubusercontent.com/47611580/60120359-a0a63080-974e-11e9-9435-a2e7d88cbf74.png)

Permit# 245894-Test
![image](https://user-images.githubusercontent.com/47611580/60121744-c123ba00-9751-11e9-89a8-262ca54c16ad.png)

![image](https://user-images.githubusercontent.com/47611580/60121754-ca148b80-9751-11e9-88ef-fe960bc3d9b0.png)

**Comment by ABonomo21** [comment]
fees calculated at the wrong rate but calculated. 
reviews were correct
