### ISSUE TITLE
ips-preprod-planning-in life mapping-apfo-14836

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1181]
hansen = application processed.
IPS moved this to complete.
per 4/08/19 email it was noted that under this scenario the application should be in the Under Review milestone in IPS unless its 5+ years old.  This AP is not 5 years old yet

![image](https://user-images.githubusercontent.com/4129185/59626504-0b7db900-910a-11e9-8fe7-ecc530897afc.png)

![image](https://user-images.githubusercontent.com/4129185/59626514-146e8a80-910a-11e9-80ff-13a7580ecdb5.png)

MW

**Comment by megisys** [comment]
Process Application was mapped to Under Review.. Application Processed with a DENIED Review was going to complete

**Comment by dhenry-KCI** [comment]
retest failed. Why would a denied review go to complete?  remember, denied in hansen=resubmit in IPS.

![image](https://user-images.githubusercontent.com/4129185/59694069-07a77080-91b6-11e9-9b0f-3792ea54901a.png)


MW

**Comment by dhenry-KCI** [comment]
spoke with Dan. probably not a common occurrence.  Will report if this is found to be more widespread.

MW
