### ISSUE TITLE
PreProd Non-Residential Grading Permit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1182]
New complete building; Permit# 245819-MCoffman

No Grading Permit Generated
![image](https://user-images.githubusercontent.com/47611580/59627751-fbb3a400-910c-11e9-8bfa-f2f2cd16be71.png)

**Comment by megisys** [comment]
Completed

**Comment by ABonomo21** [comment]
grading permit did not generate - tested permit with the peramiters that would require a grading permit to be generated and it did not work~ 

![image](https://user-images.githubusercontent.com/47611580/60112324-929be400-973d-11e9-9cd0-2a4f21b561c7.png)

![image](https://user-images.githubusercontent.com/47611580/60112355-a3e4f080-973d-11e9-8f66-f572e7fded5e.png)

**Comment by megisys** [comment]
I did > 100 and >5000 and you did exactly the amounts. i Fixed it in TEST

**Comment by ABonomo21** [comment]
grading permit generated in application 245901
