### ISSUE TITLE
IPS Pre Prod- Fire Details 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1184]
Now that we re-configured the detail pages to have staff add them back office - we need to add the specialty inspections details back in to the fire suppression rev/inspection detail page-

![image](https://user-images.githubusercontent.com/47611580/59627918-5ea53b00-910d-11e9-962b-b4b18999f889.png)

![image](https://user-images.githubusercontent.com/47611580/59627860-387f9b00-910d-11e9-8055-2f688b81ec1a.png)

This was cleaned up on the fire detail page update but now staff should have to enter it because it will not be collected data in R4C- see detail page clean up (section circled in highlighter and red only) 
![image](https://user-images.githubusercontent.com/47611580/59628100-cf4c5780-910d-11e9-9ded-dae65c8b327c.png)

**Comment by calequin** [comment]
added the specialty inspections back to the fire suppression rev/insp details. There is currently no workflow associated to it.

**Comment by calequin** [comment]
Fixed in TEST

**Comment by ABonomo21** [comment]
Can we move the Specialty Inspections Required that is in Back Office Only up with the rest of the Back Office information that we will fill in and that drives fees
![image](https://user-images.githubusercontent.com/47611580/60188635-9f800c80-97fd-11e9-9f74-c4a15e3a0dcc.png)
![image](https://user-images.githubusercontent.com/47611580/60188741-cc342400-97fd-11e9-9221-7a9bcc691208.png)

Building Permit# for this project keeps Auto Filling with 1
![image](https://user-images.githubusercontent.com/47611580/60188823-ebcb4c80-97fd-11e9-82fe-a01c822f4b85.png)

Can we add a note above this box that is Back Office Only saying something like "Data Input into Rhythm for Civics" 
![image](https://user-images.githubusercontent.com/47611580/60188884-03a2d080-97fe-11e9-8999-22e3c2e0c293.png)

**Comment by calequin** [comment]
- fixed in test
- Moved the specialty inspections detail page as the second visible detail page. I couldnt merge them together since they are technically two different types.
-building permit # has been removed to show 0
-added group area label to show  "Fire Intake Details (Rhythm for Civics)"

**Comment by ABonomo21** [comment]
@calequin 
Building Permit # is still auto filling as 1
![image](https://user-images.githubusercontent.com/47611580/60206517-bdf7ff00-9821-11e9-96f1-000a08d19dee.png)

The layout of the details page looks good, but is there any way to move the "Specialty Inspections Required (Back Office)" section to be the next one under "Fire Details (Back Office)" since those two sections will be filled out by the Tech and the other Back Office sections are completed by the reviewer. 
![image](https://user-images.githubusercontent.com/47611580/60206576-ebdd4380-9821-11e9-88d5-c5e021859a44.png)

![image](https://user-images.githubusercontent.com/47611580/60206816-8047a600-9822-11e9-95e1-1e50226ea25a.png)

Logged by-MCoffman

**Comment by ABonomo21** [comment]
Fixed in Test-MCoffman
