### ISSUE TITLE
ips-preprod-planning-in life mapping-site plan type I-pre-process

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1185]
hansen= pre-process, which means it should have gone to awaiting payment if fees weren't paid OR  under review if fees were paid. IPS has mapped this in the schedule hearing milestone.  In example below fees werent paid and should have gone to awaiting payment, not schedule hearing.

![image](https://user-images.githubusercontent.com/4129185/59627907-5947f080-910d-11e9-9667-8055b35a3dfb.png)

![image](https://user-images.githubusercontent.com/4129185/59627935-682ea300-910d-11e9-8d4e-bbc6c495c645.png)

AP 18165, 19322, 17111, 9462, 7447 all had the same issue.

MW

**Comment by dhenry-KCI** [comment]
same issue with Type II site plan.  See AP 17111 and 19152
![image](https://user-images.githubusercontent.com/4129185/59630315-0709ce00-9113-11e9-9178-90ba64b572ef.png)
![image](https://user-images.githubusercontent.com/4129185/59630338-125cf980-9113-11e9-8b87-eb57a9878fe7.png)
MW

**Comment by goggansd** [comment]
@megisys , this looks like an issue with the rules for the stage progression utility.

**Comment by megisys** [comment]
This issue has been addressed need to run against another environment

**Comment by dhenry-KCI** [comment]
6/24/19: not fixed--MW

**Comment by dhenry-KCI** [comment]
6/26-went to under review..needs to be awaiting payment-MW

![image](https://user-images.githubusercontent.com/4129185/60204777-9acb5080-981d-11e9-8b2b-75644af8f17b.png)
