### ISSUE TITLE
Use-Gaming-Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1186]
These two options of the IRS letter and By Laws received check boxes should be back office only. That way we can check them off as part of our completeness check.-AW
![image](https://user-images.githubusercontent.com/47611580/59628442-a7112880-910e-11e9-8a7a-3481374bfed0.png)

**Comment by calequin** [comment]
fixed in preprod. switched show in portal = false

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/59629279-16cfe500-9108-11e9-883e-1a16dcf05791.png)

**Comment by ABonomo21** [comment]
fixed-AW
