### ISSUE TITLE
PreProd Resulting Inspections

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1187]
Trying to result the inspections on permit#245819 as passed, keeps coming up with this error message. Doesn't matter what date, if any is put in as scheduled or completed date. I tried to result them as a group or individually and the error still generated -MCoffman

![image](https://user-images.githubusercontent.com/47611580/59629021-ee4be900-910f-11e9-9e01-70f64f4351ef.png)

**Comment by dhenry-KCI** [comment]
Confirmed fixed. Inspections can be resulted as identified above. Requested inspections can't occur in the past or on the weekends.

![Weekend Inspections](https://user-images.githubusercontent.com/4129185/60042820-9885bc80-968c-11e9-9bbf-6df4b061dcf6.PNG)
