### ISSUE TITLE
ips-preprod-planning-in life mapping-site plan Type II-Application Process

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1188]
hansen= application process.

should be "under review" in IPS

IPS has these in the schedule hearing milestone

![image](https://user-images.githubusercontent.com/4129185/59630850-60263180-9114-11e9-8b05-24f3c8248793.png)

![image](https://user-images.githubusercontent.com/4129185/59630868-6b795d00-9114-11e9-8dfa-af4987d53f03.png)

MW

**Comment by dhenry-KCI** [comment]
see also 6545,12708,13518

**Comment by goggansd** [comment]
@megisys , this seems like an issue with the rules for the stage progression utility.

**Comment by dhenry-KCI** [comment]
not fixed   MW

**Comment by dhenry-KCI** [comment]
fixed- mw

![image](https://user-images.githubusercontent.com/4129185/60204903-e7169080-981d-11e9-95c3-1b6aa0321561.png)
