### ISSUE TITLE
ips-preprod-planning-in life mapping-site plan type III-pre-process

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1189]
same issue as type II.  

Hansen= pre-process.
should migrate to pre-processed if fees are unpaid.

below fees were not paid but it went to schedule hearing in IPS

![image](https://user-images.githubusercontent.com/4129185/59631743-9795dd80-9116-11e9-9e63-e2b0be84f4c0.png)

![image](https://user-images.githubusercontent.com/4129185/59631761-a11f4580-9116-11e9-9080-041ae79a9175.png)

see also 15498, 18312

MW

**Comment by goggansd** [comment]
@megisys, this appears to be an issue with the rules for the tool.

**Comment by dhenry-KCI** [comment]
6/24/19- not fixed.  MW

**Comment by dhenry-KCI** [comment]
Corrected. Either awaiting payment or under review. AReed 6/26
