### ISSUE TITLE
License - Special Event - Applicant Document Upload Detail Page

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#119]
The Document Upload detail page for a Special Event license is missing. In order to satisfy the Awaiting Document Upload status check, this detail page needs to be made available.

![special event pic](https://user-images.githubusercontent.com/31770504/53514169-14804700-3a95-11e9-80a2-1e633721f629.png)

**Comment by calequin** [comment]
added to test environment

**Comment by JuanitaMiles** [comment]
Confirmed the License Document Upload detail page has been added.
