### ISSUE TITLE
Building - Capacity Permit - Cannot Progress Past Completeness

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1191]
Lauren is trying to progress an existing Hansen 7 application. We have satisfied all Status Check requirements but the application still will not move forward.

![image](https://user-images.githubusercontent.com/31770504/59689595-eb073a80-91ad-11e9-8bb6-e022ee4f881d.png)

![image](https://user-images.githubusercontent.com/31770504/59689654-096d3600-91ae-11e9-9257-c9a69b1fc3c8.png)

**Comment by megisys** [comment]
As this Application was at Application Added and we mapped to Completeness Check. User will need to manually add complete review if missing
