### ISSUE TITLE
PreProd Mapping-Final Inspection Milestone

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1192]
Permit# 190619 (Non-Residential Tank) -MCoffman

Permit Only has Final Inspection left to be completed, but is still in the "Inspections" Milestone not "Final Inspection"; This issue has been found on multiple permit types

![image](https://user-images.githubusercontent.com/47611580/59690410-63bac680-91af-11e9-96c9-9fba58f2b975.png)

![image](https://user-images.githubusercontent.com/47611580/59690574-9ebcfa00-91af-11e9-8c7d-ab4ed7a486c5.png)

**Comment by ABonomo21** [comment]
This issue also happened on Electrical and Plumbing permits #185437 & #189018-AW

**Comment by megisys** [comment]
Fixed this Issue.

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/59857378-d01bfe00-9346-11e9-94ac-b1aedd6d2f56.png)
![image](https://user-images.githubusercontent.com/47611580/59857402-e033dd80-9346-11e9-84c4-e4f123763c55.png)
![image](https://user-images.githubusercontent.com/47611580/59858248-9d730500-9348-11e9-883f-9bc4a56f71fb.png)
