### ISSUE TITLE
ips-preprod-planning-in life mapping-site plan Type I-Application Process

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1193]
hansen= application process.

should be "under review" in IPS

IPS has these in the schedule hearing milestone

![image](https://user-images.githubusercontent.com/4129185/59690542-9795ec00-91af-11e9-8141-981d39cf1a85.png)
![image](https://user-images.githubusercontent.com/4129185/59690593-a1b7ea80-91af-11e9-983f-0d005a9d34f2.png)

same issue on the following ap #s that we looked at.
#19116
#19097
#18803
#18845
#17807
#17031
#16498
#16294
#8697
#6432

MW

**Comment by goggansd** [comment]
@megisys, stage progression utility issue.

**Comment by dhenry-KCI** [comment]
not fixed.

for best examples see 18803, 18845, 17807, 17031

**Comment by dhenry-KCI** [comment]
19116 correct
18845 correct
