### ISSUE TITLE
Building - Capacity Permit - Floor Drain Fixture Counts

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1194]
Fixture Counts are not generating for any of the numbered Floordrain Fixture codes. The only one that does generate a fixture count is the FLOORDRAI code.

AP 245823

![image](https://user-images.githubusercontent.com/31770504/59691478-0c1d5a80-91b1-11e9-8933-9cc401857d7f.png)

**Comment by JuanitaMiles** [comment]
Update to Issue: This problem appears to be any code that has a number in it.

**Comment by mmbanong** [comment]
Working with Juanita to get missing fixture values updated

**Comment by JuanitaMiles** [comment]
@mmbanong Here are screenshots of the Fixture Descriptions and their value counts. Please identify the Fixture Values that are missing in IPS and update. The Descriptions should match fairly well to identify them.

![image](https://user-images.githubusercontent.com/31770504/59865589-635d2f80-9357-11e9-8e7f-af1e48fe1005.png)

![image](https://user-images.githubusercontent.com/31770504/59865613-73750f00-9357-11e9-8962-896a53e420c1.png)

**Comment by mmbanong** [comment]
Fixture value counts have been updated

**Comment by JuanitaMiles** [comment]
Fixed in PreProd. Will continue to monitor to ensure the values continue to carry over after any database refreshes.
