### ISSUE TITLE
ips-preprod-planning-in life mapping-Combo plat-pre-process

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1195]
hansen= pre-process
should migrate to under review in IPS but is in paperwork review (mylar review.)  Not sure why.  Tested 11 other ap numbers and they were ok.  Something must be different about this one.  Perhaps because there is a case attached to it in hansen?

![image](https://user-images.githubusercontent.com/4129185/59697659-42140c00-91bc-11e9-8e5b-e5c1c5b7ee70.png)

![image](https://user-images.githubusercontent.com/4129185/59697528-f5c8cc00-91bb-11e9-851b-376d3d10eff3.png)

MW

**Comment by goggansd** [comment]
@megisys, looks like an issue in the stage progression utility.

**Comment by dhenry-KCI** [comment]
not fixed-MW

![image](https://user-images.githubusercontent.com/4129185/60038769-2eb4e500-9683-11e9-95ae-a6827d579895.png)
