### ISSUE TITLE
Building - Capacity Permit - Water/Sewer Fees Missing

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1196]
The Water/Sewer fees are not populating when the applicable check boxes are checked on the details page. This appears to be dependent on the Subdivision code selected on the details page. Point of Rocks worked fine while Ballenger Creek did not generate fees.

![image](https://user-images.githubusercontent.com/31770504/59698859-8b655b00-91be-11e9-9709-c5ea116b9686.png)

![image](https://user-images.githubusercontent.com/31770504/59699210-31b16080-91bf-11e9-9015-9d85d4f3465b.png)

**Comment by megisys** [comment]
I dont know what fees should have added. Capacity is a monster of a fee schedule. So for me to troubleshoot i need to know what is missing

**Comment by JuanitaMiles** [comment]
The larger issue: Fees for some subdivisions populate automatically (For example Point of Rocks). However for others (Ballenger Creek) the fees do not populate automatically and we instead get a status check that Water/Sewer fees are required. and need to be added manually. DUSWM feels that all of these should automatically populate fees. Why are they now being asked to manually add fees (most of the time)?

![image](https://user-images.githubusercontent.com/31770504/59874881-551a0e00-936d-11e9-8d81-bec8221a0395.png)

![image](https://user-images.githubusercontent.com/31770504/59874896-6236fd00-936d-11e9-9d6e-35b3f0c71b40.png)

![image](https://user-images.githubusercontent.com/31770504/59874961-901c4180-936d-11e9-85d2-ae7947c1f6a0.png)

![image](https://user-images.githubusercontent.com/31770504/59874979-9f02f400-936d-11e9-849a-46c787638c9b.png)

**Comment by megisys** [comment]
I cant fix this.. I need to know which fees are missing for this sub division code.

**Comment by dhenry-KCI** [comment]
@megisys - why is that the when the user selects certain subdivisions, the system automatically populates the correct fees (Point of Rosks), while others Ballenger creek the system does not populate the correct fee? Why are some subdivisions populating a correct fee, while others are not?

**Comment by dhenry-KCI** [comment]
@pooldaddy @mmbanong - Jeff can you telll us the capacity fee for Ballenger Creeek. See thread for further details.

**Comment by mmbanong** [comment]
Requested capacity fee for Ballenger Creeek form Jeff Wisner

**Comment by JuanitaMiles** [comment]
@megisys Application #246055 : Water/Sewer fees getting the redline to add maually. Subdivision number is 061143. Also, the meter had a quantity of 5 but fees only generated for 1 meter.

**Comment by mmbanong** [comment]
Needs further discussion as per Juanita

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - can refresh my memory here? I think Dan was able to fix some of these fee issues but not all. Is that correct?

**Comment by JuanitaMiles** [comment]
@dhenry-KCI - It sounds like from the most recent conversation you had with DUSWM/Jeff W/Martin, that we determined there are only a few fees for DUSWM. HOWEVER, we still need Jeff W and Martin to work together to fix the fact that the fees are not always adding automatically. Sometimes the sewer fee will add automatically and we'll get a redline to manually add water fees, sometimes both add automatically, and sometimes neither of them add. I believe this is happening depending on the subdivision code chosen.

**Comment by dhenry-KCI** [comment]
@calequin - we should meet on this issue.  Will set up time for Thursday for you, Juanita and I to discuss.

**Comment by megisys** [comment]
Lets meet on this next week please.
