### ISSUE TITLE
ips-preprod-planning-in life mapping-final plat-approve application

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1197]
this one should be expired per rule we established for plats to go to closed if unapproved and are 5 or more years old.
![image](https://user-images.githubusercontent.com/4129185/59699227-3c6bf580-91bf-11e9-9904-2614a1764df5.png)

![image](https://user-images.githubusercontent.com/4129185/59699250-455cc700-91bf-11e9-8447-648b0eecd227.png)

MW

**Comment by dhenry-KCI** [comment]
better screen shot for above


![image](https://user-images.githubusercontent.com/4129185/59699617-e2b7fb00-91bf-11e9-8abc-4f236d4c0d1d.png)

**Comment by goggansd** [comment]
@megisys, when I did a Check Status in IPS 11 for this application, it did not progress because it has the Number of Pages field blank. Could be that the stage progression utility needs to bypass these rules for old data? Or at least in this use case where we are moving them to Closed/Expired?
