### ISSUE TITLE
Mobile - Notifications on Inspection Result

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1198]
Bob mentioned he would like the system to notify the applicant of the result of an inspection, whether pass or fail.

Lets discuss the possibility of this during the Mobile Meeting.

**Comment by dhenry-KCI** [comment]
@calequin to investigate

**Comment by megisys** [comment]
Add to Notification Matrix

**Comment by ABonomo21** [comment]
will confirm with ash and juanita with notification correspondence- will monitor
