### ISSUE TITLE
R4C - Fee Payment - NonResBldg & Planning

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1199]
Lauren could not pay the NonResBldg (AP# 245827) fees online. She got the following message.

![image](https://user-images.githubusercontent.com/31770504/59701471-b7cfa600-91c3-11e9-9037-19b99885ae73.png)

**Comment by megisys** [comment]
Batch Manager was stopped

**Comment by JuanitaMiles** [comment]
Still not able to pay fees on R4C.

**Comment by megisys** [comment]
For All AP Types. or Just NON RES

**Comment by dhenry-KCI** [comment]
@calequin Running log as of June 22nd of successful and unsuccessful R4C payments by AP

Successful Payments (6):
•	**Building:**
o	Fire Permit
•	**Planning:**
o	Board of Appeals
o	FRO
o	Verification Letters
•	**License:**
o	Liquor License
•	**Use:**
o	Home Occupation
-       Gaming 

Unsuccessful Payments (9):
•	**Building:**
o	ResBldg
o	NonResBldg
o	Driveway
o	Demolition
o	FRO Permit
o	Electrical
•	**Planning:**
o	APFO
o	PWConstruc
•	**Trade License:**
o	Plumbing License

**Comment by dhenry-KCI** [comment]
Tested APFO on 8/1 - payment failed - Transaction #200045 AP - A244988
MW AR

**Comment by dhenry-KCI** [comment]
PLANNING - PLAT  PL244943 fees paid correctly. AR

**Comment by dhenry-KCI** [comment]
Will monitor closing for now.
