### ISSUE TITLE
Use - Home Occupation - Home Occupation Details Page Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#12]
(Reported by Ashlye Bonomo - 2/6/19)
There are a couple of updates that need to be made to the Home Occupation Details page:

- [x] Questionaire numbers 2, 5, 7, and 9 need to have the "Y/N" removed as the fields should just be check boxes.
       *  The "Questionaire" section header is misspelled. It should be spelled "Questionnaire".
- [x] If a building permit is required, shouldn't the A/P# reference field be removed and then the building permit number would be referenced on the related records tab.

![image](https://user-images.githubusercontent.com/31770504/52388211-67994800-2a5b-11e9-8605-b07886b0a241.png)

**Comment by ABonomo21** [comment]
This detail page needs to be removed.however, we need to be able to capture the IMPACT OR NO IMPACT on the detail page not view able by the applicants on R4C but inserted at completeness check

![image](https://user-images.githubusercontent.com/47611580/54035460-69077e80-4187-11e9-8edd-1e957580a253.png)

The data is being captured on the home occ intake detail page that was already updated. 

![image](https://user-images.githubusercontent.com/47611580/54034522-0dd48c80-4185-11e9-97ea-c134845a8890.png)


A/P # H235803

**Comment by megisys** [comment]
Addressed
