### ISSUE TITLE
Building - Fire Permit - Fire Alarm Final Inspection needed

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#120]
There should only be a Fire Alarm Final inspection according to the inspection notes in Airtable.

AP: 237368
Logged By: M. Coffman

![image](https://user-images.githubusercontent.com/4104464/53514566-febf5180-3a95-11e9-9666-1b149dd55eee.png)

**Comment by megisys** [comment]
Add Description Column to clear up Inspection Name.. There is a final added

![image](https://user-images.githubusercontent.com/47392306/53697102-b9539a80-3d9b-11e9-8ca5-e9253d85392b.png)

**Comment by dhenry-KCI** [comment]
Testing failed-Permit #238602-A Smoke Control Rough In Inspection generated but this permit is for a fire alarm not a smoke/hood control system.
![image](https://user-images.githubusercontent.com/4129185/53905029-84eb1300-4015-11e9-8674-f7ae8b5c5742.png)

![image](https://user-images.githubusercontent.com/4129185/53905049-8caab780-4015-11e9-94ce-d2e963cf565a.png)

**Comment by dhenry-KCI** [comment]
On a second attempt for a fire alarm permit, no inspections generated at all. Only a Fire Alarm Final inspection should generate for fire alarm permits.-AW
![image](https://user-images.githubusercontent.com/4129185/53905232-fdea6a80-4015-11e9-889a-4bc5f4ddd1de.png)

**Comment by dhenry-KCI** [comment]
Third attempt for a fire alarm permit, same result as before. no inspection generated at all-AW
![image](https://user-images.githubusercontent.com/4129185/53905702-2fb00100-4017-11e9-899f-e94a56b880d2.png)

**Comment by imazlout** [comment]
I'm not sure why the first one had the smoke alarm inspection populate. I looked at the formula and it's set to populate only if the Fire Permit Type = Control. I tried to recreate the issue but I couldn't. 

The retest is as expected. Please try again. No inspections populate on Inspections milestone for Fire Alarm as expected and per the requirements on airtable. The request was to have only Alarm Final populate, which it does once you reach Final Inspection milestone. The application used by the tester is still in Inspections milestone as can be seen by the screenshot provided above (there is a status check to attach an electrical permit). Once that's done, the application will move to Final Inspection where the Alarm Final Inspection will populate.  When in doubt why an application is stuck in a certain milestone, please click the status check button (the checkmark icon) to see why there is a hold up.

**Comment by ABonomo21** [comment]
The Rough In Inspection generated when it should have gone straight to the final (once the other requirements are met) as mentioned above by @imazlout 

![image](https://user-images.githubusercontent.com/47611580/53969739-4f066700-40c7-11e9-813e-e53868f992fe.png)

**Comment by imazlout** [comment]
@ABonomo21  Which environment are you in? I checked permit 238407 and it's a FROPermit. The screenshot you have doesn't include the URL so I can't tell. In the Test environment FIRE-ALMRI has been completely disabled (we removed the formula) and so it never adds, unless manually added by someone. Something isn't adding up. Please confirm the environment you are in.

Below is screenshot for permit 238407 in Test environment:
<img width="812" alt="capture238407" src="https://user-images.githubusercontent.com/47784290/53989072-18464600-40f3-11e9-8b77-2cd3a6c32c0d.PNG">

**Comment by ABonomo21** [comment]
@imazlout It is possible I was in Dev at the time for the this permit. There were a lot of issues with my account being duplicated and it jumping from test to dev and vice versa. I'll retest this type of permit today.-AWhite

**Comment by ABonomo21** [comment]
Confirmed Fixed, only the final inspection generated once the child permits were closed.-AW
![image](https://user-images.githubusercontent.com/47611580/54130917-b2560900-43e7-11e9-8909-04bed457f861.png)
