### ISSUE TITLE
ips-preprod-planning-in life mapping-final plat-approve application-went to awaiting paperwork

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1200]
this is a strange one.
Hansen= application processed
rule= move to under review in IPS
Is showing up in Awaiting Paperwork milestone.

![image](https://user-images.githubusercontent.com/4129185/59699983-830e1f80-91c0-11e9-9570-109aa0e24c7b.png)

**Comment by goggansd** [comment]
@megisys this looks like a stage progression utility issue.

**Comment by dhenry-KCI** [comment]
not fixed 6/24/19

**Comment by dhenry-KCI** [comment]
6/26/19 Should be under review in IPS. Showing Paperwork Review. AReed
