### ISSUE TITLE
ips-preprod-planning-in life mapping-plat-application processed-two different milestones?

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1201]
ap 8846 is under review in IPS with fees due.
![image](https://user-images.githubusercontent.com/4129185/59707143-01be8900-91d0-11e9-88cb-2fd73fe6b7aa.png)

ap 5828 has fees due but went to the awaiting applicant payment milestone

![image](https://user-images.githubusercontent.com/4129185/59707235-36cadb80-91d0-11e9-81de-931a52f9c483.png)

not sure why they are different.  That said I dont have a problem with where they landed in IPS.

MW

**Comment by goggansd** [comment]
@megisys, this may be due to the incomplete SHA review on 8846. I can't view the logic for the stage progression, but presumably it would not move out of Under Review if there are still incomplete reviews.
