### ISSUE TITLE
ips-preprod-planning-in life mapping-plat-application processed-went to awaiting paperwork

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1202]
this AP should have gone to under review.  Instead it is in awaiting paperwork

![image](https://user-images.githubusercontent.com/4129185/59707519-cb353e00-91d0-11e9-913d-0f8c336eea28.png)

MW

**Comment by dhenry-KCI** [comment]
also see ap 18139- MW

**Comment by dhenry-KCI** [comment]
see also 12630

**Comment by dhenry-KCI** [comment]
see also 12968, 19342 MW

**Comment by goggansd** [comment]
This looks like a bug in the stage progression rules, @megisys.

**Comment by dhenry-KCI** [comment]
6/24/19: should have gone to under review, not paperwork review.   MW
![image](https://user-images.githubusercontent.com/4129185/60037875-cbc24e80-9680-11e9-93d2-190218ff25ec.png)
