### ISSUE TITLE
IPS Pre Prod-Mapping Milestones-ResBldg-Pending Certificate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1204]
This Permit #180178 is in the Pre-Finalized stage and should have migrated over to the Pending Certificate milestone. Instead the permit is showing as closed and completed even though there is no final date. This has occurred on multiple permits.-AW
180178
![image](https://user-images.githubusercontent.com/47611580/59707795-5d3d4680-91d1-11e9-92bc-7343badaf9fb.png)
![image](https://user-images.githubusercontent.com/47611580/59707838-7645f780-91d1-11e9-8f97-2ba4d39156dc.png)
![image](https://user-images.githubusercontent.com/47611580/59707867-88c03100-91d1-11e9-84cf-448b140c1ae7.png)

**Comment by megisys** [comment]
The Utility has been fixed but as these have already run. We need to test against another version of the migration

**Comment by megisys** [comment]
Need to run against Pristine

**Comment by calequin** [comment]
fixed
