### ISSUE TITLE
IPS Pre Prod-Mapping Milestones-COO Date incorrect

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1205]
This permit #193323 passed it's final inspection on 5/3/19 and the COO was issued on 5/6/19. however the COO date is showing as 6/12/19 on both the Job Description tab and the log. don't know where 6/12 came from?? -AW
![image](https://user-images.githubusercontent.com/47611580/59708385-ab9f1500-91d2-11e9-9cca-e7f9f9925010.png)
![image](https://user-images.githubusercontent.com/47611580/59708410-b8bc0400-91d2-11e9-810e-2c9645b3c2dd.png)
![image](https://user-images.githubusercontent.com/47611580/59708446-cb363d80-91d2-11e9-8f3e-208cf3b09b96.png)

**Comment by goggansd** [comment]
The last data migration happened the week of 5/6/2019. The modification moving this application to Pre-Issue happened after the migration and was not done by the system (meaning it was manually moved to this milestone and status). @megisys  you indicated that there was a utility which you ran to move these. Given that there is no username associated with the manual move, I'm guessing that this was the utility (as opposed to a user).

**Comment by calequin** [comment]
COO date is now showing 6/21/2019.
![image](https://user-images.githubusercontent.com/47603568/59976678-8a9d4200-958d-11e9-808d-ebc4986ab99a.png)

**Comment by ABonomo21** [comment]
correct in pristine 
![image](https://user-images.githubusercontent.com/47611580/65440367-a2879a80-ddf6-11e9-945f-1f0523585cc1.png)
