### ISSUE TITLE
ips-preprod-planning-in life mapping-plat-application processed-ips fees but no fees in hansen

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1206]
IPS shows fees due but Hansen shows all fees paid.

![image](https://user-images.githubusercontent.com/4129185/59710154-6977d280-91d6-11e9-8ca1-b580d991635f.png)

MW

**Comment by goggansd** [comment]
Two fees were paid on 5/24/2019 in V7. The data migration from a copy of V7 started on 5/6/2019, meaning that these fees were unpaid when the migration occurred. This is not an issue.

![image](https://user-images.githubusercontent.com/28841997/59790062-0f8e1000-929d-11e9-97d5-5f54034187e4.png)

**Comment by dhenry-KCI** [comment]
oops.
