### ISSUE TITLE
R4C-Addendum-Related permit number

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1207]
For the Addendum application on R4C, there is no space to input the associated permit number that they are adding this too. I added it to the description but I think it would be helpful to the customer to have a specific box for this important info.-AW
![image](https://user-images.githubusercontent.com/47611580/59710559-28cc8900-91d7-11e9-9653-b17abd6b1e0f.png)

**Comment by calequin** [comment]
detail page added to addendum to display in portal
![image](https://user-images.githubusercontent.com/47603568/59716591-e0639a00-91db-11e9-82ae-13b17adbc899.png)

**Comment by ABonomo21** [comment]
looks great!-AW
![image](https://user-images.githubusercontent.com/47611580/59853954-effbf380-933f-11e9-86a2-7bc295723c96.png)
