### ISSUE TITLE
License - Special Event - Applicant Actions Detail Pages

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#121]
- Upon resulting a COMPLETE review with Resubmit, the application progress to Awaiting More Information and two 'Awaiting Applicant Action(s)' detail pages generate on the License Details tab.

![image](https://user-images.githubusercontent.com/31770504/53529468-af3f4c80-3aba-11e9-8fe9-df595fbde262.png)

- When clicking on the first Awaiting Applicant Action(s) page two errors are thrown and you are not able to complete the page.

![image](https://user-images.githubusercontent.com/31770504/53529537-e6156280-3aba-11e9-9df5-088ac6da54ae.png)

![image](https://user-images.githubusercontent.com/31770504/53529552-f4fc1500-3aba-11e9-9727-1d75bf7461b0.png)

![image](https://user-images.githubusercontent.com/31770504/53529570-02190400-3abb-11e9-8905-7803868f9f76.png)

- The second Awaiting Applicant Action(s) page works properly and progress the application forward.

**Comment by calequin** [comment]
fixed duplicate detail page and issues

**Comment by JuanitaMiles** [comment]
Confirmed Applicant Action detail page issues are fixed.
