### ISSUE TITLE
Liquor License - R4C - Transfers, Renewals and New Licenses

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1212]
The user needs the ability to select a new license, transfer or renewal. Create a checkbox that will allow the user to select the appropriate application type.

**Comment by megisys** [comment]
Need more information . This is not complete enough

**Comment by calequin** [comment]
added in test
![image](https://user-images.githubusercontent.com/47603568/59871937-4f68fc00-935e-11e9-82bf-902269df2a9c.png)

**Comment by JuanitaMiles** [comment]
Penny confirmed this is OK.
