### ISSUE TITLE
Building - Capacity - Adding Expired APs as Related Records

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1213]
Lauren tried to add an expired permit to an application. Does IPS allow users to add Expired applications to open permit applications for historical purposes?

**Comment by megisys** [comment]
No it doesnt.You would need to reopen it. Then assign and close it back

**Comment by JuanitaMiles** [comment]
tried changing the expiration date, adding it, then changing the date back. works fine.
