### ISSUE TITLE
Building - Capacity - Fixture Type Description Update

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1219]
We need to update the Description of the DRINK2 Fixture value in Hansen 7. It should read "Hi/Lo Drinking Fountain".

![image](https://user-images.githubusercontent.com/31770504/59861590-22f9b380-934f-11e9-982c-0303b5f129a3.png)

**Comment by mmbanong** [comment]
Post Go Live issue per Dan

**Comment by dhenry-KCI** [comment]
Will correct during the data migration.

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/70375797-46e68c80-18d0-11ea-827f-847911932fa4.png)
