### ISSUE TITLE
License - Special Event - Denied COMPLETE Review

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#122]
Upon resulting the first COMPLETE review with 'Denied', the application progressed to the Awaiting More Information milestone. Shouldn't the application progress to a Closed/Complete status when a denial is made?

![image](https://user-images.githubusercontent.com/31770504/53530348-8a98a400-3abd-11e9-839f-ad21254d4246.png)

**Comment by calequin** [comment]
Fixed workflow to send application to a Closed/Complete Milestone and status

**Comment by JuanitaMiles** [comment]
Confirmed fixed.
