### ISSUE TITLE
preprod-planning-in life mapping- PWCONST-pre issue COO to complete- ips shows open status but finalized milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1222]
shouldn't be an open application and finalized.

![image](https://user-images.githubusercontent.com/4129185/59867905-707d1d00-935d-11e9-91e6-b28f32bfe64d.png)

see also 1092, 3370, 5694 etc etc

MW

**Comment by megisys** [comment]
Where should this go

**Comment by dhenry-KCI** [comment]
ok-AR
