### ISSUE TITLE
grading - cost estimate worksheet items

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1228]
[Copy of Cost-Estimate-Worksheet-MS-Excel.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3311573/Copy.of.Cost-Estimate-Worksheet-MS-Excel.xlsx)

tm 6/20/19

**Comment by mmbanong** [comment]
What are we suppose to do? Can I have some directions?
Thanks

**Comment by megisys** [comment]
What values are missing. Dustin to talk to Tiffany

**Comment by dhenry-KCI** [comment]
https://www.frederickcountymd.gov/DocumentCenter/View/15883/APPROVED-UNIT-PRICES---Excel?bidId=

**Comment by dhenry-KCI** [comment]
@mmbanong - i have the correct spreadsheet with the grading unit prices below. We need to make sure all items in this list are added with the associated cost. 

[Unit Prices_07-01-2010.XLSX](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3453578/Unit.Prices_07-01-2010.XLSX)

**Comment by mmbanong** [comment]
grading - cost estimate worksheet items have been updated
![grading](https://user-images.githubusercontent.com/47392173/63105251-6ab34a80-bf4e-11e9-9bf5-2f93c0a317a7.PNG)

**Comment by ABonomo21** [comment]
need to correct description in IPS

**Comment by ABonomo21** [comment]
@dhenry-KCI - not sure who is going to review these and update in IPS.
