### ISSUE TITLE
R4C - GRADING - DETAILS PAGE

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1229]
ESD TYPES ARE ONLY REQUIRED UNDER SWMESD work TYPES OF GRADING PERMITS

![image](https://user-images.githubusercontent.com/47611580/59871899-96f38600-9366-11e9-8ba9-81cb7629cb89.png)

i was entering a major grading permit.

#246853
tm 6/20/19

**Comment by megisys** [comment]
This is not possible. If it isnt filled out right on intake. It is a resubmit or the intake review fills out..

**Comment by dhenry-KCI** [comment]
@calequin - the fields being displayed in the grading mitigation pick list (or similar loggin condition details) are dynamic based on the work type selected on the previous page, if ESD details should only be populated for SWM-ESD wrok types, can we move those fieldsto a similar dynamic section for that work type?

**Comment by calequin** [comment]
as @megisys mentioned this is not possible on a detail page dynamically. If fields are missed they need to resbumit.

**Comment by dhenry-KCI** [comment]
@calequin maybe i am not asking the question correctly. Below are two screenshots from IPS (R4C is also displaying this information dynamically) when creating a grading permit. In the screenshots you can see that the feilds in the detail page ARE DYNAMIC based on the selected work type. So if the user is only to populate SWM-ESD details when that SWM -ESDwork type is selected, can we replciate the process we use for major loggin and major grading? We are obviously dynimcally displaying data. We would remove the SWM-ESD details so it only displays on the appropriate work type
![imagesmitigation](https://user-images.githubusercontent.com/4129185/59966154-31c69e80-94e6-11e9-97a6-611d11c0192b.PNG)
![Loggin Conditions](https://user-images.githubusercontent.com/4129185/59966156-33906200-94e6-11e9-9b07-a8e3c5c7a449.PNG)

**Comment by ABonomo21** [comment]
above is correct. we only want the esd details to be populated on the esd work type. if you have further questions, let me know. 

tm 6/25/19

**Comment by calequin** [comment]
this will be an enhancement on the grading details intake. We would need to create a new detail page and follow up with workflow for it to appear according to the work type. Currently this is tied in the same details intake page.

**Comment by dhenry-KCI** [comment]
Agreed as an enhancement.
