### ISSUE TITLE
Planning - Preplat - Required Plat Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#123]
The system is requiring a Child Plat be associated to the parent Pre-plat during admin closure. the aasociation between a parent pre-plat and child final plat should be required as part of completion check.

Remove association in pre-plat at admin closure. Add association at completeness check for Final Plat only. 

AP - PP237353
![pre-plat](https://user-images.githubusercontent.com/4129185/53575302-45b55180-3b3f-11e9-854d-d6fdc6b0ea5f.png)

**Comment by megisys** [comment]
This has been addressed.

Thanks

**Comment by dhenry-KCI** [comment]
Add association at completeness check for Final Plat only - **Not Achieved**
Under PLAT - FINAL PLAT there needs to be stop in progress at Completeness Check milestone requiring a valid PRE-PLAT (that is not expired) to be added as a Parent -AREED

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
corrected - AReed
