### ISSUE TITLE
License - Liquor License - Next Renewal Date

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1230]
The Next Renewal Date should always be 4/30 of the next year.

![image](https://user-images.githubusercontent.com/31770504/59872111-049fb200-9367-11e9-9519-385032bf3e03.png)

**Comment by calequin** [comment]
@JuanitaMiles on an email from Ashley I received on 12/8 she stated that renewal starts on March 2. I have changed the formula to reflect a March 2 renewal date.

**Comment by dhenry-KCI** [comment]
Confirmed. Closed.
