### ISSUE TITLE
Building - Capacity - Milestone Mapping Issue

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1231]
Based on the conversation had with Dan G. If an application is Expired in Hansen 7 it should be migrated to IPSv11 as a Status of Expired and a Milestone of Complete. The Expired Capacity permits in Hansen 7 are coming over as Expired and in an Pre-Issue Permit milestone.

![image](https://user-images.githubusercontent.com/31770504/59874442-35361a80-936c-11e9-94df-d446a34c08d5.png)

![image](https://user-images.githubusercontent.com/31770504/59874491-4bdc7180-936c-11e9-85fe-f5714cc5679f.png)

**Comment by megisys** [comment]
This has been updated for all permits..

**Comment by JuanitaMiles** [comment]
mapping looks fixed
