### ISSUE TITLE
License - Liquor License - Data Migration Strategy

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1232]
We need to have a conversation on the data migration process for the liquor licenses will look like. 

During our Reports/Testing session on 6/18 we identified some data migration issues. Holding off on creating official issues for these until we have a solid data migration strategy:

- The "L-" on the License Category Codes were not in Hansen. Where did these come from? Are they required? Can they be removed?

- Endorsement Types did not carry over properly.

- For a transfer license, the license was related to itself twice. As a Parent and as a Child.

- Need to confirm Milestone Mapping.

**Comment by dhenry-KCI** [comment]
the L- is a license category code. County fine with keeping these.
Endorsement type added to data migration
transfers would be manual update and the system will not automatically create this realtionship. for historical license number with a T- will be migrated as the child of the new. County accepting deleting extra.
count will have 300+ active licenses
Pre-issuance - completeness check
active = active
cancelled / expired = expired

**Comment by dhenry-KCI** [comment]
Closing data issue. If needed, can provide ticket to GDS team for adjustments post go-live
