### ISSUE TITLE
R4C - Demo AP - No Milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1233]
Created a DEMO Application in R4C. Was able to successfully submit the application. When i look-up the application in IPS the the application "has no milestone"  

AP - 246859

![image](https://user-images.githubusercontent.com/4129185/59878159-9dd5c500-9375-11e9-813a-ce42692a898a.png)

**Comment by calequin** [comment]
fixed. initial milestone checkbox was deleted from the milestones in IPS. added it back and now it follows to completeness check

**Comment by ABonomo21** [comment]
fixed

![image](https://user-images.githubusercontent.com/47611580/60038823-468c6900-9683-11e9-9fb3-70007e38ec03.png)
