### ISSUE TITLE
Temp COO Procress 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1235]
![image](https://user-images.githubusercontent.com/47611580/59925740-c1951b80-9406-11e9-9275-f21a51ba22e0.png)

![image](https://user-images.githubusercontent.com/47611580/59925763-ceb20a80-9406-11e9-9d27-4b4ac0d69381.png)

Instructions for the applicant: (add to the details page)
A Temporary Certificate of Occupancy can be issued for thirty (30) days upon request. A Temporary Certificate of Occupancy request can be made only against Non-Residential Permits.
In order to submit an application for a Temporary Certificate of Occupancy, all final inspections must have been attempted for all permits associated to the non-residential structure.  This includes building, plumbing, electric and fire.  
Once all final inspections have been attempted, the request for temporary occupancy can be submitted, all permits that have a failed final inspection will be subject to a Temporary Certificate of Occupancy inspection. The inspectors may, or may not, have to visit the site again depending on what the final inspections have failed for. In order for the inspectors to grant approval for temporary occupancy the minimum code requirements for building, life safety, electrical, plumbing and site compliance must be met.  
The Temporary Certificate of Occupancy application submission will need to include a copy of the floor plans identifying those areas for which use is being requested.  This includes a plan highlighting or a listing of room numbers as indicated on the approved plan.  If the Temporary Certificate of Occupancy is intended to be used in a manner that is partial to the permitted and full use and occupancy, please provide a description of use for the space (i.e., stocking, training, interviews, storage, orientation, sales, etc.).  Once the Temporary Certificate of Occupancy application is accepted there is a fee, which will need to be paid prior to inspector assignment.  Please allow one week for processing. 
Until such time that a Temporary Certificate of Occupancy has been issued, the use of the structure is NOT permitted. 

Intake Process:- Add to SOP's at the final inspection milestone 
Request form should become available at the inspection milestone.
Once the request is submitted system should generate a Temporary COO Review – need a dashboard item  (will need to add SOP instructions for staff to approve or denied.) If approved staff should manually insert the Temp COO fee and inspections. 
Once the fee is paid the inspections that were inserted can be scheduled and assigned to the appropriate inspector. 
Once inspections completed, Temp COO outcome can be inserted by administrative, approved or denied. (We will monitor this ourselves)
Staff will insert any comments and then manually issue the letter, placard and attach to permit.

**Comment by ABonomo21** [comment]
Christian please make this work- 
See format above. 
A Temporary Certificate of Occupancy can be issued for thirty (30) days upon request. A Temporary Certificate of Occupancy request can be made only against Non-Residential Permits.
In order to submit an application for a Temporary Certificate of Occupancy, all final inspections must have been attempted for all permits associated to the non-residential structure. This includes building, plumbing, electric and fire.
Once all final inspections have been attempted, the request for temporary occupancy can be submitted, all permits that have a failed final inspection will be subject to a Temporary Certificate of Occupancy inspection. The inspectors may, or may not, have to visit the site again depending on what the final inspections have failed for. In order for the inspectors to grant approval for temporary occupancy the minimum code requirements for building, life safety, electrical, plumbing and site compliance must be met.
The Temporary Certificate of Occupancy application submission will need to include a copy of the floor plans identifying those areas for which use is being requested. This includes a plan highlighting or a listing of room numbers as indicated on the approved plan. If the Temporary Certificate of Occupancy is intended to be used in a manner that is partial to the permitted and full use and occupancy, please provide a description of use for the space (i.e., stocking, training, interviews, storage, orientation, sales, etc.). Once the Temporary Certificate of Occupancy application is accepted there is a fee, which will need to be paid prior to inspector assignment. Please allow one week for processing.
Until such time that a Temporary Certificate of Occupancy has been issued, the use of the structure is NOT permitted.

**Comment by ABonomo21** [comment]
need to add a review @megisys

**Comment by ABonomo21** [comment]
appear at final inspection milestone

**Comment by ABonomo21** [comment]
dan fixed review- waiting for directions to be posted

**Comment by calequin** [comment]
added verbiage to detail page to display in portal.
added SOP on final inspection milestone for backoffice

**Comment by ABonomo21** [comment]
good - need to check in R4C
