### ISSUE TITLE
Res Use-Grading and Driveway Permits generating/required.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1236]
A grading permit automatically generated for a Res Use Deck permit I created and it is requiring the grading and driveway permits to be issued before this permit can be issued. The grading permit should only automatically generate on a Res Use permit if the Earth Disturbance/Grading Details are filled in -AW
#246870
![image](https://user-images.githubusercontent.com/47611580/59926493-68c68280-9408-11e9-9b6b-f2c7991314e8.png)
![image](https://user-images.githubusercontent.com/47611580/59926504-6f54fa00-9408-11e9-8425-f28b4e1ae268.png)
![image](https://user-images.githubusercontent.com/47611580/59926535-809e0680-9408-11e9-9d71-4e90f3739010.png)

**Comment by megisys** [comment]
Updated

**Comment by ABonomo21** [comment]
Failed - still generated a grading permit without any details filled in 

![image](https://user-images.githubusercontent.com/47611580/60112794-79dffe00-973e-11e9-9495-749d659e95f3.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/64363812-8656c180-cfdf-11e9-9277-0061431e2d4c.png)
closed 9.5.19 ab 
![image](https://user-images.githubusercontent.com/47611580/64364074-2876a980-cfe0-11e9-9566-bb05937e2223.png)
