### ISSUE TITLE
Addendum-Automatically Jumping Milestones

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1238]
Similar to #1214 but even though I input the fees and reviews before approving the completeness check it still jumped milestones after I paid fees.-AW
Order of steps i took:
-added reviews
-added fees
-approved completeness check
-then it required fees to be paid
-I paid the fees
-then it skipped the open reviews that I added and jumped right to Pending Certificate

#246874
![image](https://user-images.githubusercontent.com/47611580/59931959-1ab77c00-9414-11e9-908f-aa485cb860a2.png)
![image](https://user-images.githubusercontent.com/47611580/59931992-2f940f80-9414-11e9-8da7-ed0a2898cae5.png)
![image](https://user-images.githubusercontent.com/47611580/59932024-45093980-9414-11e9-9bad-91ac71613fa8.png)

**Comment by goggansd** [comment]
Fixed in IPSTest and tested:
![image](https://user-images.githubusercontent.com/28841997/59941219-a63c0780-942a-11e9-8a14-87a3b503c063.png)
Please retest in IPSTest environment.

**Comment by ABonomo21** [comment]
Fixed in test, Addendum went through the correct milestones at the correct pace.-AW
![image](https://user-images.githubusercontent.com/47611580/60121515-38a51980-9751-11e9-9fc6-6aa6947d4fd4.png)

![image](https://user-images.githubusercontent.com/47611580/60121537-49558f80-9751-11e9-9e22-7faa973189dd.png)

**Comment by ABonomo21** [comment]
Accidental Closure. I meant to mark it as Ready to Deploy-AW
