### ISSUE TITLE
Distributor License - Mapping 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1239]
Use the following mapping rule to move Distributor LIcenses from H7 to IPS 11.

-	If in H7 as expired, inactive map in IPS 11 Status = Inactive, Milestone = _Expired_

**Comment by ABonomo21** [comment]
dl 3 is expired in preprod

**Comment by ABonomo21** [comment]
this is the only one that should be expired we only have 5 active
