### ISSUE TITLE
PreProd- Resbldg Pending issuance 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1240]
![image](https://user-images.githubusercontent.com/47611580/60039909-cddadc00-9685-11e9-9538-473091d06bfc.png)

a hold populated for driveway and grading permits to be issued however permit  246879 does not require a driveway permit- they should be separate holds- when there is a seperate permit of each created.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/60040082-2f9b4600-9686-11e9-9609-79dae82d7a66.png)

**Comment by megisys** [comment]
Addressed this

**Comment by ABonomo21** [comment]
language corrected
