### ISSUE TITLE
IPS Test _ addendum error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1242]
![image](https://user-images.githubusercontent.com/47611580/60045179-2ca65280-9692-11e9-9c24-93b789ac67ca.png)

![image](https://user-images.githubusercontent.com/47611580/60045203-3af46e80-9692-11e9-8f07-760a8483657b.png)

**Comment by imazlout** [comment]
Ready for test. Please retest using all new application numbers since non-addendum children that have the -1 will throw an error (duplicate unique key error)

**Comment by ABonomo21** [comment]
Did not receive any errors, permit numbers for addendum generated correctly-AW
![image](https://user-images.githubusercontent.com/47611580/60191184-f091ff80-9801-11e9-932c-02b2d1f3a4ec.png)

**Comment by dhenry-KCI** [comment]
open - need dan to deploy.
