### ISSUE TITLE
Non-Residential Building-Construction Details Grid

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1244]
Permit# 246883; The room Grid does not save on the permit application-MCoffman

![image](https://user-images.githubusercontent.com/47611580/60103597-e6063600-972d-11e9-92ce-9a06066746c0.png)

![image](https://user-images.githubusercontent.com/47611580/60103667-059d5e80-972e-11e9-95df-3b6b8685403e.png)

**Comment by calequin** [comment]
fixed the grid to save.

**Comment by ABonomo21** [comment]
Permit# 245892-Issue fixed in PreProd and R4C-MCoffman
![image](https://user-images.githubusercontent.com/47611580/60124604-fa5f2880-9757-11e9-8e7e-b47fed3a97b4.png)

![image](https://user-images.githubusercontent.com/47611580/60124632-106ce900-9758-11e9-97f0-9d7bd835a4f6.png)
