### ISSUE TITLE
R4C-Gaming-Tip Jar Off Premise-Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1245]
On the Details page for Gaming Tip Jar Off Premise, the "Tip Jar Frequency" and the options "Calendar Year" or "Quarterly" should be all grouped together (Yellow Highlight). The "Liquor License" and "Food License" and their date boxes should all be grouped together too(Green Highlight). Also I think the "Do you have the Following?" is supposed to be the header for the food/liquor license so that should be grouped with them too. -AW
![image](https://user-images.githubusercontent.com/47611580/60105755-ee607000-9731-11e9-861c-62ec1515f545.png)

**Comment by calequin** [comment]
fixed in test. need to deploy in preprod
![image](https://user-images.githubusercontent.com/47603568/60107544-169d9e00-9735-11e9-8fdb-2d5562c5ac75.png)

**Comment by ABonomo21** [comment]
Looks great in Test!-AW
![image](https://user-images.githubusercontent.com/47611580/60109299-1d79e000-9738-11e9-8204-21146f7d3cbc.png)
