### ISSUE TITLE
IPS TEST - Wrong Fee - Solar Array 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1247]
Processed an alteration in test and a fee for an accessory structure populated 

![image](https://user-images.githubusercontent.com/47611580/60119827-612b1480-974d-11e9-975f-d55b89598263.png)

**Comment by megisys** [comment]
This is the New Fee Change Value

**Comment by ABonomo21** [comment]
good job dan
