### ISSUE TITLE
IPS TEST - Sq. Footage

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1248]
Unable to enter sq. footage on a nonres accessory structure

![image](https://user-images.githubusercontent.com/47611580/60120697-72752080-974f-11e9-9f5f-bccbac417b72.png)

**Comment by dhenry-KCI** [comment]
confirmed isues exists in Preprod as well

**Comment by megisys** [comment]
Ready for Retest . Job Estimation was on by mistake

**Comment by ABonomo21** [comment]
corrected
