### ISSUE TITLE
IPS TEST - Occupancy Load Req

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1249]
Occupancy load requirement should not populate until the the under review cycle- not at inital intake-
![image](https://user-images.githubusercontent.com/47611580/60120838-ba944300-974f-11e9-9867-b8971f68ace4.png)

**Comment by megisys** [comment]
This was a recently asked for change. Moved to Under Review. But there is no status check that this information is required in the workflow.

**Comment by ABonomo21** [comment]
moved to under review milestone will add to sop for pdox and at the pending cert review
