### ISSUE TITLE
Planning - Pre-plat - Required Fields at Admin Closure

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#125]
The system require the field "Date Planning Went to FCPC Meeting" during admin closure.

Airtable 108

**Comment by megisys** [comment]
Dustin.. @dhenry-KCI They don't want it to show up or they do want it show up and it isnt ??? Also Airtable issue 108 is something completely different.

**Comment by dhenry-KCI** [comment]
@megisys THe system *SHOULD require the field  "Date PLanning Went to FCPC Meeting" at Admin closure.

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
failed.  "Date PLanning Went to FCPC Meeting" still not required.

![image](https://user-images.githubusercontent.com/4129185/53754407-e1b5c480-3e81-11e9-91f5-2b096913727d.png)

**Comment by dhenry-KCI** [comment]
"Date Planning Went to FCPC Meeting" needs to be a required field at admin closure. In addition to the others that are already populating.

![image](https://user-images.githubusercontent.com/4129185/53760921-35c8a500-3e92-11e9-9b8a-7dcc43edc8ea.png)

**Comment by megisys** [comment]
It is Because FCPC approval required was never selected .. See above you highlight..

**Comment by dhenry-KCI** [comment]
all preliminary plat require FCPC.  The "is FCPC required" field is only used on Combined prelim/finals to generate an additional review fee.  For Prelim the "date project went to FCPC meeting should be a required filed without the check box being checked.
Also, please change "Date Planning" to "Date Project"   MLW

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
"Date Planning Went to FCPC Meeting" is not showing as a required field PP237522
![image](https://user-images.githubusercontent.com/4129185/53897799-e951a680-4004-11e9-995d-4d1dd84860ea.png)
![image](https://user-images.githubusercontent.com/4129185/53897907-1900ae80-4005-11e9-9220-53a44c508b7f.png)

**Comment by megisys** [comment]
Sorry.. It didnt save my change

**Comment by dhenry-KCI** [comment]
good PP 237738
