### ISSUE TITLE
IPS TEST- Unable to bypass the sp requirement 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1250]
Processing an application that is requiring a site plan - attached one that is issued and it will not let me progress
![image](https://user-images.githubusercontent.com/47611580/60121241-9d13a900-9750-11e9-994c-780107711019.png)

![image](https://user-images.githubusercontent.com/47611580/60121268-aef54c00-9750-11e9-9c31-727916427152.png)

**Comment by megisys** [comment]
Site Plan is not attached.. A PWCONTRUC was attached.. Am I confused ????

**Comment by ABonomo21** [comment]
fixed thanks
