### ISSUE TITLE
IPS PreProd Mapping- Driveway 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1251]
Driveway permit that was valid when the mapping was completed is showing closed in IPS 
![image](https://user-images.githubusercontent.com/47611580/60121508-35119280-9751-11e9-942e-d587e8bf9a73.png)

![image](https://user-images.githubusercontent.com/47611580/60121580-65593100-9751-11e9-94c3-06be311c3c89.png)

**Comment by megisys** [comment]
It has been expired for a month. This is valid. For the system to move it to closed .

**Comment by dhenry-KCI** [comment]
Agreed. Application migrated and then expired in IPS. Closing
