### ISSUE TITLE
building - grading - mapping - minor grading

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1254]
when i check status of permit #191480 the application states that that projectdox review cycle is needed - grading is not subject to projectdox

![image](https://user-images.githubusercontent.com/47611580/60177570-38eff400-97e7-11e9-9535-0004e9f5c8b6.png)

tm  6/26/19

**Comment by megisys** [comment]
This is not a data issue. Linked to a bad formula. Closing as a  data issue
