### ISSUE TITLE
building - grading - mapping - minor grading 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1255]
Permit #191480 has a denied review - the milestone should be awaiting application submittal, however, the milestone is under review

![image](https://user-images.githubusercontent.com/47611580/60177731-a6038980-97e7-11e9-8c20-11ce5d50d65e.png)
**

tm 6/26/19

**Comment by ABonomo21** [comment]
checked in pristine and it still went to the under review milestone. 
![image](https://user-images.githubusercontent.com/47611580/65439300-f09b9e80-ddf4-11e9-8c26-2a0d87df64b1.png)

**Comment by dhenry-KCI** [comment]
Closing data issue. If needed, can provide ticket to GDS team for adjustments post go-live
