### ISSUE TITLE
Planning - Pre-plat - Preliminary Plat Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#126]
Spelling issue on preliminary plat details tab. Update spelling to "Preliminary"

![pre-plat](https://user-images.githubusercontent.com/4129185/53575982-b6a93900-3b40-11e9-936e-8d64c775f4fa.png)

**Comment by mmbanong** [comment]
Dustin I went in and checked and the spelling seems OK. Did someone else fix it?

**Comment by megisys** [comment]
I Fixed this..

Dan

**Comment by dhenry-KCI** [comment]
resolved mikw wilkins 3-1-19
