### ISSUE TITLE
Building - Capacity - Permit Issued Notification

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1263]
The approved and issued Capacity notification is sending at the wrong time. The notification should be sent after the Admin Review/Pending Certificate milestone.

**Comment by mmbanong** [comment]
Tested with Juanita and seems to work ok will monitor
![image](https://user-images.githubusercontent.com/47392173/62790143-79a28480-ba98-11e9-9bd4-8a7478384325.png)

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
