### ISSUE TITLE
Data Mapping - PI

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1265]
PI Permit 185351

![image](https://user-images.githubusercontent.com/47611580/60191245-06072980-9802-11e9-9033-d43e6a51360e.png)

Discussion with Dan

6/26/19 EP

**Comment by megisys** [comment]
Its Not Perfect.. But it is in Final Inspection. As an Inspection has the Word Final in its inspections

**Comment by ABonomo21** [comment]
confirmed this went to the final inspection milestone - which should work as it is still an inspection milestone 
![image](https://user-images.githubusercontent.com/47611580/65439864-d7472200-ddf5-11e9-8e25-2f464c189c56.png)
