### ISSUE TITLE
Building - Capacity - Additional Milestones Needed

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1267]
We need to add the milestones outlined in the attached document to the Capacity permit workflow for the Final Fixture Count Inspection Process. See the yellow section and the notes.

[DUSWM_Workflow_Updates_20190626.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3331541/DUSWM_Workflow_Updates_20190626.pdf)

**Comment by kellyjj** [comment]
@JuanitaMiles 

to confirm:   if the capacity permit is nonres  the flow goes from pending certificate straight to final inspection and the flow in the pdf is flow that is followed till completion,

if it is res, then the current flow is followed.

is that right?

**Comment by kellyjj** [comment]
I have added the milestones, and created status checks for each m/s.

waiting for question above to be answered.

**Comment by JuanitaMiles** [comment]
@kellyjj  - That is correct. NonRes capacity permits will flow through the three additional milestones. Res will continue to go from Pending Certificate to Complete.

**Comment by kellyjj** [comment]
I have made the flow changes.  ready for retest.

**Comment by JuanitaMiles** [comment]
The application generated the ADMINREV but passed through the Pending Certificate milestone and went straight into Final Inspection. Instead, it should stop in the Pending Certificate milestone, require the ADMINREV to be resulted, then progress into Final Inspection.

![image](https://user-images.githubusercontent.com/31770504/60592999-d01cf480-9d6f-11e9-8d3d-342bef16d635.png)

![image](https://user-images.githubusercontent.com/31770504/60593227-4d486980-9d70-11e9-815d-3d29c2d39599.png)

**Comment by JuanitaMiles** [comment]
For a NonRes capacity permit, the final fixture count Qty is different from the prelim fixture county qty, therefore the permit should have generated the appropriate fees and stopped at the Awaiting Fixture Payment milestone. Instead it went straight from Inspections to Closed.

![image](https://user-images.githubusercontent.com/31770504/65444639-72dc9080-ddfe-11e9-9945-1dd6b1f491bd.png)

![image](https://user-images.githubusercontent.com/31770504/65444676-8982e780-ddfe-11e9-8d93-a87af1c36f15.png)

**Comment by megisys** [comment]
All runs on Subdivision Codes. It looks like subdivision code was changed mid cycle

**Comment by JuanitaMiles** [comment]
appears fixed during testing with Lauren 11/12
