### ISSUE TITLE
R4C Fire Details Layout

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1268]
We need to try to figure out a better layout for the Fire Details Page on R4C-MCoffman

![image](https://user-images.githubusercontent.com/47611580/60208947-91df7c80-9827-11e9-9df2-8c14e2f425ac.png)

**Comment by dhenry-KCI** [comment]
Will monitor user response during training.

**Comment by ABonomo21** [comment]
meeting with christian 10 am on Wednesday 9.25.19 to discuss lay out

**Comment by JuanitaMiles** [comment]
Christian to update the Fire Intake Details per our 9/25 discussion to add section boxes consistent with the paper application groupings. Christian estimated about a half day's work to do this. Expected to be ready by Monday 9/30. @ABonomo21 @dhenry-KCI

**Comment by calequin** [comment]
FIXED. please review.

**Comment by ABonomo21** [comment]
looks great - will test and re-open new tickets for any issues
