### ISSUE TITLE
Planning - Plat - DUSWM Reviews and Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#127]
DUSWM is a conditional add for all Plat plan. When water designation = W (1, 3,4,5) or Sewer Designation =S (1,3,4,5) then DUSWM fees and reviews should populate. 

DUSWM = $104 for final plats
DUSWM = $75 ADDITION, CORRECTION, FARMLOT, OPENSPACE, PUBLICTAKING, and ROADDEDICATION/ROADALIGNMENT and outlot Plats
DUSWM = $540 Combo Plat

**Comment by megisys** [comment]
@dhenry-KCI . So what is not working.. I reviewed the set up and we have this laid out. I could be missing one combination.. Exxample AP Numbers ??

**Comment by dhenry-KCI** [comment]
@megisys Addition Plat is missing DUSWM Fee 
AP - PL237386

**Comment by megisys** [comment]
Addressed this in previous ticket..

**Comment by dhenry-KCI** [comment]
fees correct on addition and correction - AReed
