### ISSUE TITLE
Pdox-Planning-not all applications coming through to Pdox

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1271]
created three plats- PL244690, PL244695, and PL244691.   The last two came through but the first one didnt.   MW

![image](https://user-images.githubusercontent.com/4129185/60285270-936a7c80-98db-11e9-9219-31c2bb5e79ff.png)

**Comment by dhenry-KCI** [comment]
TESTED COMBO, FINAL, ADDITION, CORRECTION, AND PUBLIC TAKING.  sO FAR ONLY COMBO IS GETTING HELD UP

**Comment by megisys** [comment]
This is because the Work Type Description is too long. These need to be shortened. I added a safe guard to ensure they are truncated

**Comment by dhenry-KCI** [comment]
Confirmed complete.
