### ISSUE TITLE
PDOCS/IPS - Planning - Addition Plat - wrong milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1273]
All reviews approved. IPS should move to awaiting paperwork but is holding in Awaiting Applicant Revisions.  AReed
PL244691
![image](https://user-images.githubusercontent.com/4129185/60289474-81410c00-98e4-11e9-890a-667b49ff9bd1.png)

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
