### ISSUE TITLE
Mobile- Re-Inspection fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1274]
Re inspection fees are generating on plumbing and electrical permits in mobile after the first inspection. which means they are adding in PreProd 

re inspection fees should populate after the second inspection of the same type. 

please look into this - spoke with bob ensor 6.28.19- ab

**Comment by dhenry-KCI** [comment]
per email from Gary on 7/18:
Dan -

Following up on the discussion about reinspection fees.  

We would like to suspend reinspection fees for only those non res electric and plumbing permits where the initial permit fee exceeds $20k.  

Make sense?

Thanks

Gary Hessong

Division of Planning & Permitting
30 North Market Street
Frederick, Maryland 21701
GHessong@FrederickCountyMD.gov
301-600-2028

**Comment by megisys** [comment]
This has been Addressed in Test. Please let me know and mark ready to Deploy

**Comment by ABonomo21** [comment]
closing duplicate
