### ISSUE TITLE
Planning - BOA - Application Status Issue

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1275]
The BOA Application Status progresses to "Closed" upon entering the Admin Closure milestone. The application should remain in an "Open" status until the application reaches the Complete/Finalized milestone.

![image](https://user-images.githubusercontent.com/31770504/60453292-c922a480-9bfe-11e9-81a6-e9fbf56b05a0.png)

![image](https://user-images.githubusercontent.com/31770504/60453308-d2ac0c80-9bfe-11e9-92ae-390f1566c573.png)

**Comment by megisys** [comment]
Addressed in Test

**Comment by JuanitaMiles** [comment]
Appears Fixed
