### ISSUE TITLE
Mobile - Access Updates for Go Live

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1276]
Rick M. is creating a Supervisor Inspector role and applying it to the Admin Access Security Role for now. For Go Live we will need to create an Inspector_Supervisor access role and have the Supervisor Inspector Role applied to it. Rick recommends using the Inspector_Regular role for all normal permissions and the Inspector_Supervisor role will only have the Supervisor Inspector role option.

In the future the Admin Role will be reserved for IT staff. It grants permission to do everything in the system.

We will need to coordinate with Rick and Martin to make these updates closer to Go Live.

**Comment by ABonomo21** [comment]
will monitor for after go live working now @dhenry-KCI
