### ISSUE TITLE
Building - Electrical Permit - Re-Inspection Fee

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1277]
Re-inspection fees should not be populating after the first failed/partial passed inspection. The Re-Inspection fee should populate after the SECOND failed/partial passed inspection.

![image](https://user-images.githubusercontent.com/31770504/60515641-1019a400-9caa-11e9-9af5-0455fa0b2134.png)

![image](https://user-images.githubusercontent.com/31770504/60515720-40614280-9caa-11e9-9eb1-f5a597370261.png)

**Comment by JuanitaMiles** [comment]
This is also an issue for Plumbing Permits

![image](https://user-images.githubusercontent.com/31770504/60516151-270cc600-9cab-11e9-9059-e6479e62e92f.png)

![image](https://user-images.githubusercontent.com/31770504/60516169-33911e80-9cab-11e9-8de6-340decad56c2.png)

**Comment by JuanitaMiles** [comment]
Also an Issue for Signs

![image](https://user-images.githubusercontent.com/31770504/60546439-4cb9bf80-9ceb-11e9-8803-a0cd177a93aa.png)
![image](https://user-images.githubusercontent.com/31770504/60546471-5e02cc00-9ceb-11e9-829e-85c9293b3dad.png)

**Comment by megisys** [comment]
Spoke with Gary we might build in a large project bypass

**Comment by ABonomo21** [comment]
electrical and plumbing permits with fees paid greater than 
20k will not get re inspections fees per ab /gh/ be
all others should get fees as required per fee schedule ab

**Comment by ABonomo21** [comment]
still generating after the first failed inspections - should generate on the third of the same type that had a previous result of failed or partial pass

**Comment by megisys** [comment]
I added for 3rd Round.. But what failed. Example please ?

**Comment by ABonomo21** [comment]
tested permit 246788 and it worked correctly will monitor during training.  has been working on other a/p types that Juanita bob and i have tested
