### ISSUE TITLE
PreProd - Mapping Issue, Non Res

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1278]
Application 1654 in H7 is not a processed applciation nor is it issued 
![image](https://user-images.githubusercontent.com/47611580/60515888-a1891600-9caa-11e9-8584-a0026b04b42f.png)
In IPS 11 it shows as issued and at the inspection milestone. 

![image](https://user-images.githubusercontent.com/47611580/60515964-bb2a5d80-9caa-11e9-9cbf-0740b9473604.png)

**Comment by megisys** [comment]
Moved Building Permits with Application Added with no Address to Complete
