### ISSUE TITLE
Fees Updates- Hard Coded Formulas

### ISSUE THREAD

**Issue by mmbanong** [kcigeospatial/Fred_Co_Land-Management#1279]
Dan is aware of the formula changes and will give an update when all done. Hard coded fee values need to be in the Rate table so the formulas can read from the table instead of the hard coded values in the formulas

 [Hard Coded Formulas.zip](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3350439/Hard.Coded.Formulas.zip)

**Comment by megisys** [comment]
Only 3 to Go. IS the ones with most recent Modification Date.

**Comment by megisys** [comment]
Addressed 2 of 3. 1 Needs to remain due to the complexity.
