### ISSUE TITLE
Planning - Plat - Combination Plat  Affadavit 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#128]
The system must require the user to complete a signed affidavit review. The system should add the Condition Affadavit  at the same time the condition "paperwork" is added. The Affadvit review condition must be met (=Yes) prior to sign-off of the Mylars. 
Airtable 583

**Comment by dhenry-KCI** [comment]
This is a code requirement. We need to have this check in place for PLAT - COMBO. AReed MWilkins

When Total # of Lots on Plat Details is 2 or greater, affidavit will populate as a condition at the same time as the Condition for Paperwork (milestone - Awaiting Paperwork).

**Comment by megisys** [comment]
When you notifiy the applicant - In Awaiting Paperwork - WE tell them what they need to provide.. Sign Affidavit.. Then in Paperwork Review you check you have it...  I added a condition to hole you up

**Comment by dhenry-KCI** [comment]
fixed PL237759
