### ISSUE TITLE
Building - Priority Status Check

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1280]
The Priority Status Check is not populating during Completeness Check for the following Building Permit applications:

- RESBLDG
- Fire Permit
- ResUses
- Signs
- Trailer
- Zoning Certificate
![image](https://user-images.githubusercontent.com/31770504/60519823-51ae4d00-9cb2-11e9-856a-b8944b08c5bf.png)
![image](https://user-images.githubusercontent.com/31770504/60519842-5c68e200-9cb2-11e9-98cc-70c5a65d2f88.png)
![image](https://user-images.githubusercontent.com/31770504/60521253-eb76f980-9cb4-11e9-8f76-a6e458515203.png)
![image](https://user-images.githubusercontent.com/31770504/60521278-f9c51580-9cb4-11e9-9d1e-ff6648a4f07b.png)
![image](https://user-images.githubusercontent.com/31770504/60522230-99cf6e80-9cb6-11e9-954e-2b879f50a548.png)
![image](https://user-images.githubusercontent.com/31770504/60522258-a6ec5d80-9cb6-11e9-9dfa-68c1aa42b80c.png)
![image](https://user-images.githubusercontent.com/31770504/60522890-cdf75f00-9cb7-11e9-81d9-a00d651cc25a.png)
![image](https://user-images.githubusercontent.com/31770504/60522952-e2d3f280-9cb7-11e9-9224-fe3df80389a7.png)
![image](https://user-images.githubusercontent.com/31770504/60524415-832b1680-9cba-11e9-97d2-c84c7adc6a99.png)
![image](https://user-images.githubusercontent.com/31770504/60524463-99d16d80-9cba-11e9-82db-f1109688059e.png)
![image](https://user-images.githubusercontent.com/31770504/60525067-b621da00-9cbb-11e9-99af-b24259c15465.png)
![image](https://user-images.githubusercontent.com/31770504/60525096-c33ec900-9cbb-11e9-82b2-eb1ea305fee3.png)

**Comment by megisys** [comment]
Added Constraint to Completeness Check

**Comment by ABonomo21** [comment]
RESBLDG still is not requiring the priority code 

![image](https://user-images.githubusercontent.com/47611580/61884130-a61ba580-aec9-11e9-9be6-49ff43a97f6c.png)

**Comment by ABonomo21** [comment]
priority code needs to be required on resbldg

![image](https://user-images.githubusercontent.com/47611580/62950553-44f33d80-bdb6-11e9-8833-1bb3f0ee31bb.png)

**Comment by megisys** [comment]
This has been added However Please be aware there was another ticket saying that they didn't like these being enforced at COmpleteness CHeck. AS if you result the completeness check as resubmit you still have to set the Priority Code. PLease Ensure the county is happy with this approach as we seem to be going back and forth between. Having it enforced and having to set the priority for a resubmit

**Comment by ABonomo21** [comment]
resuse-fixed-aw
![image](https://user-images.githubusercontent.com/47611580/64374563-1bfb4c80-cff2-11e9-9bc3-52a51dacc487.png)
resbldg-fixed
![image](https://user-images.githubusercontent.com/47611580/64374744-70063100-cff2-11e9-9fa4-3a694979a64c.png)
fire-fixed
![image](https://user-images.githubusercontent.com/47611580/64374848-a6dc4700-cff2-11e9-8e97-2d081631a6e3.png)
signs-fixed
![image](https://user-images.githubusercontent.com/47611580/64374990-eefb6980-cff2-11e9-9830-c8156d5a3eca.png)
trailer-fixed
![image](https://user-images.githubusercontent.com/47611580/64375151-4dc0e300-cff3-11e9-93dc-fc8724013241.png)
zoning-fixed
![image](https://user-images.githubusercontent.com/47611580/64375242-79dc6400-cff3-11e9-8c88-c3639cd15e5f.png)
