### ISSUE TITLE
PLANNING - R4C/IPS - APFO Application

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1281]
Change "**Select One**" to "**Select One If Not Exempt**" on Roads, Water/Sewer & Schools
Add **"Select One If Exempt"** to Road Exemptions, Water/Sewer Exemptions & School Exemptions

change "**Water & Sewer Exemptions**" to "**Water/Sewer Exemptions**" to replicate the title for Water/Sewer

Remove slash (/) between Public/Water - use a space instead

![image](https://user-images.githubusercontent.com/4129185/60525732-ed44bb00-9cbc-11e9-98cf-b835f86a8c1d.png)

AREED

**Comment by megisys** [comment]
FIXED IN TEST>> Not PreProd. Will migrate when accepted
