### ISSUE TITLE
IPS Test - Non Res Detail Page Grid

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1282]
when attempting to add only an existing room on the grid- i am getting an error that there must be a new room listed as well. 

![image](https://user-images.githubusercontent.com/47611580/60533133-dc03aa80-9ccc-11e9-85a3-f6dcba28453b.png)

there can be just existing rooms without a new being created

**Comment by ABonomo21** [comment]
when i try to add a new room to bypasss the error i get a larger issue of not finding the room in the grid when selected from the list 

![image](https://user-images.githubusercontent.com/47611580/60533219-0ce3df80-9ccd-11e9-83bf-758185431be8.png)

**Comment by megisys** [comment]
Hi , What is the purpose of this data ? When is it needed and what process does it drive ? What are we expecting it to do.

**Comment by ABonomo21** [comment]
there could be an alteration to an existing room which is why the "existing room" would be in the list but there would not be a "new room" required to be listed. there would only be a new room if a new room was being added or a change of use of an existing room was being completed. 

please change the code so that only one or the other would have to be filled in or both could be filled  if needed.

**Comment by ABonomo21** [comment]
worked thanks 246836
