### ISSUE TITLE
PDOX- Non Res Permit 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1285]
Permit 245922 was resulted as a resubmit - revision fee populated and went to awaiting revision fee payment. 
![image](https://user-images.githubusercontent.com/47611580/60537815-53d6d280-9cd7-11e9-9bf9-f4792c9a9959.png)

paid the revision fee - went back under review in IPS however, there was not communication back to PDOX 

![image](https://user-images.githubusercontent.com/47611580/60538032-c8117600-9cd7-11e9-8207-1d2eb0a8082d.png)

![image](https://user-images.githubusercontent.com/47611580/60538049-cfd11a80-9cd7-11e9-8aef-ec5dedbf38cc.png)

tried to add the review in IPS however, it still did not correct it.

**Comment by dhenry-KCI** [comment]
@megisys - i believe this is a batch manager issue, please confirm.

**Comment by dhenry-KCI** [comment]
Closing issue as this has not been an issue with batch manager running.
