### ISSUE TITLE
Extension Requests

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1286]
Permit# 245601 Added Extension Request Details Page into Application Details to replicate what should happen when the permit is 11 months old. The details page did generate in R4C and I was able to submit the information to request an extension. However in PreProd there is no log or review that generates notifying us that the customer applied for an extension or to be able to approve/deny the extension.-MCoffman

![image](https://user-images.githubusercontent.com/47611580/60538175-073fc700-9cd8-11e9-8c4f-20a4db13b737.png)

![image](https://user-images.githubusercontent.com/47611580/60538067-dcee0980-9cd7-11e9-8459-7d29d2222938.png)

**Comment by megisys** [comment]
Add Generic Extension Fees 1- for Build 1 for ECS - On paying the Generic Fee. Look for EXT Review and See result of that review and update the Expiry Date

**Comment by megisys** [comment]
Confirm Budget number for ECS Extension with Emily

**Comment by megisys** [comment]
On First save of Extension Detail Page - The Review did not Add - EXT

**Comment by ABonomo21** [comment]
did not get a review or a log for the extension review to notify staff that and extension request has been submitted , tested on permit 246775
you will see the details mage was manually added and it was completed in r4c 
![image](https://user-images.githubusercontent.com/47611580/65271915-1ae71680-daec-11e9-9899-f9b25367574d.png)
@dhenry-KCI

**Comment by megisys** [comment]
Review will add once compelted

**Comment by ABonomo21** [comment]
permit 246589
added the extension request details page as if it was the 11th month
juanita processed the request in r4c - 
no log was created 
![image](https://user-images.githubusercontent.com/47611580/65530796-9e2ab280-dec6-11e9-9b48-b55f5cda2afa.png)
no condition generated (which it shouldnt, just wanted to make sure i checked every possible way)
![image](https://user-images.githubusercontent.com/47611580/65530833-ac78ce80-dec6-11e9-9c37-58eaee15b2e0.png)
no review generated
![image](https://user-images.githubusercontent.com/47611580/65530885-c74b4300-dec6-11e9-903b-a4985a5cea63.png)

so i will ask a different way .... - how is the back office supposed to know that there was a request for extension received?

**Comment by calequin** [comment]
worked for me
the workflow needs to happen as follows:
1. extreq log gets added by back office staff
2. extension detail page automatically gets added to the application
3. applicant updates extension request detail page
4. EXT review gets added.

The disconnect is on the following: How does an applicant request an EXT prior to the r4c button enhancement coming

**Comment by ABonomo21** [comment]
log needs to be automatically added to an application on anything after issuance and before completed.

**Comment by ABonomo21** [comment]
notification will be sent once log it created

**Comment by ABonomo21** [comment]
will need a follow up meeting with dan christian ash and Juanita.

**Comment by ABonomo21** [comment]
@dhenry-KCI need a meeting for this one

**Comment by ABonomo21** [comment]
this is not a training issue

**Comment by dhenry-KCI** [comment]
Schedule meeting on 10/9

**Comment by ABonomo21** [comment]
Driveway extension process works. confirmed testing 11.4.19

**Comment by ABonomo21** [comment]
will confirm all extension processes work
