### ISSUE TITLE
PDox_ Demo-batch stamp 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1287]
in pdox demo permit is still in batch stamp and in IPS it is in the issued milestone without batch stamp being completed or a condition in IPS

![image](https://user-images.githubusercontent.com/47611580/60539275-440cbd80-9cda-11e9-89c7-68449ed478a0.png)

![image](https://user-images.githubusercontent.com/47611580/60539157-09a32080-9cda-11e9-9e4a-07674a756ad4.png)

**Comment by megisys** [comment]
Demo Permit not a Pdox Type.
