### ISSUE TITLE
PLANNING - PDOCS/IPS - DUE DATE IN IPS

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1288]
PL244719 - Due date did not populate in IPS from PDOCS on 2nd review until review was resulted. AREED

Did not have this issue on PL244718 which is an identical application

![image](https://user-images.githubusercontent.com/4129185/60539552-fba1cf80-9cda-11e9-9282-f50e61959bae.png)

**Comment by dhenry-KCI** [comment]
Pdox  

![image](https://user-images.githubusercontent.com/4129185/60539864-b3cf7800-9cdb-11e9-9e14-db44b396714e.png)

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/60539882-c0ec6700-9cdb-11e9-9035-cab1eab1012b.png)

FRO Review is actually not resulted. ar

**Comment by dhenry-KCI** [comment]
this time a different agency got a due date.  MW


![image](https://user-images.githubusercontent.com/4129185/60596771-abc51600-9d77-11e9-9723-1472ac68b3e6.png)

**Comment by dhenry-KCI** [comment]
Due dates should populate at the assigned reviewer task completion.

**Comment by megisys** [comment]
PLease Retest this. Believe to be fixed with another issue

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
