### ISSUE TITLE
PDox- Prescreen - 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1289]
![image](https://user-images.githubusercontent.com/47611580/60540155-80d9b400-9cdc-11e9-9133-c6dcfc9ea142.png)

why is the description of work up so high?

**Comment by megisys** [comment]
Removing myself.. Purely Avolve Issue

**Comment by dhenry-KCI** [comment]
Robert is aware and looking into this issue.

**Comment by RS-Avolve** [comment]
This was resolved by Alejandro on Wednesday, July 24.  Text field label and content now align, see screenshot below:
[Screenshot - Field Label Alignment Fixed.docx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3447192/Screenshot.-.Field.Label.Alignment.Fixed.docx)

**Comment by ABonomo21** [comment]
lining up. 
![image](https://user-images.githubusercontent.com/47611580/65445883-2e9ebf80-de01-11e9-9131-b1c693798ac2.png)
