### ISSUE TITLE
Planning - Plat - Combo/Final - FCPC

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#129]
During the review of the combo plan the reviewer needs to be able to determine if the plat needs a FCPC. During the under review milestone, if the reviewer determines that an FCPC Application is required the system needs to generate an additional fee of $1154.00 for a total  Panning review Fee of $2,818.00. the system would prevent the plan for proceeding until the fee is paid.

**Comment by megisys** [comment]
This is not a Bug.. If after fees have been generated and paid by the applicant. then you have to go to the Fees tab and manually add fees. The system doesn't automatically add fees when in a milestone.. This funcationality doesn't exist.. Training Issue

**Comment by dhenry-KCI** [comment]
Reviewed with MWilkins - agree to training issue. AREED
