### ISSUE TITLE
PDOX - Upload requirements

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1291]
File size and Minimum Resolution determination 
how many pages can be uploaded at one time 
need to have a conversation with IIT and PDOX

**Comment by dhenry-KCI** [comment]
Per meeting with Avolve on 7/8
No page limit - just size limit
Current default 1 to GB for a single drawing 10gb for batch uploads.

**Comment by dhenry-KCI** [comment]
Closing Issue.
