### ISSUE TITLE
PDOX -Due date 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1292]
IPS states one week from application at 7.10.19 and pdox says 7.9.19

![image](https://user-images.githubusercontent.com/47611580/60595646-643d8a80-9d75-11e9-9359-38f2eee6e9e7.png)

![image](https://user-images.githubusercontent.com/47611580/60595677-76b7c400-9d75-11e9-82d5-bfa063f2509c.png)

however after assigned it changed the due date to 7.10.19 why wouldn't it should the 7.10.19 dated on the initial assignment screen 

![image](https://user-images.githubusercontent.com/47611580/60595790-b7174200-9d75-11e9-871c-9ecdb4abaa31.png)

**Comment by megisys** [comment]
Once it is assigned the Time is REcalculated as this is when the timer starts
