### ISSUE TITLE
Pdox- Stamp Cycle and canned comments 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1293]
At what point in the annotate of the plans cycle will the reviewer insert the canned comments and or standard stamps that are used? 

who is creating those?

**Comment by ABonomo21** [comment]
Where were the check lists that our reviewers use available ? Are we converting them to editable pdfs that can be attached to the plans.

**Comment by dhenry-KCI** [comment]
Will have Resource links provided at the Global Tab in PDox for reviewers as well as prescreen checklist items.

**Comment by dhenry-KCI** [comment]
Closing this issue. We will provide Robert a list of canned comments post training.
