### ISSUE TITLE
IPS/PDox-plat-IPS in awaiting revisions milestone but should be awaiting paperwork

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1295]
resulted all reviews in PDox as approved. IPS should be in the awaiting paperwork milestone (aka mylars).

![image](https://user-images.githubusercontent.com/4129185/60598475-c51b9180-9d7a-11e9-9f33-fd9dae6b0182.png)

MW

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
