### ISSUE TITLE
Tolerance Review- PDOX and IPS 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1296]
![image](https://user-images.githubusercontent.com/47611580/60597352-c6e45580-9d78-11e9-8b02-a7ad8803a70b.png)

do we add fees prior to resulting the review? if not how do we stop the system from auto generating the revision fee - currently the revision fee auto adds should all fees insert be manual? what is best practice. 

should have the applicant actions review prior to the fees being inserted ? 

IPS is back under review and asking me to add another review, is this another tolerance review because i asked for a resubmit. and how do i know the applicant action was taken if no applicant action was sent out by IPS? Pdox is in batch stamp 

![image](https://user-images.githubusercontent.com/47611580/60598170-373fa680-9d7a-11e9-8a56-dc8f285e51bb.png)

added a manual applicant actions and it generated the resubmit submitted - will this be a dashboard item? its should have generated a second tolerance review- 

![image](https://user-images.githubusercontent.com/47611580/60598495-ccdb3600-9d7a-11e9-96a8-8f27fd0dbac5.png)

added another review- stuck in under review and pdox cycle must be complete while pdox is already completed. 

![image](https://user-images.githubusercontent.com/47611580/60598828-6276c580-9d7b-11e9-9522-0ebc48b90e1e.png)

![image](https://user-images.githubusercontent.com/47611580/60598841-6b679700-9d7b-11e9-91e6-25e45ace1b5e.png)

**Comment by dhenry-KCI** [comment]
Closing this issue. Similar to other closed tolerance review items.
