### ISSUE TITLE
PDOX- Resubmit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1298]
Ken selected on application 245934 to resubmit in pdox-
went to awaiting revision fee payment ( i thought the fees were being moved back to calculate and be collected prior to issuance. 
paid the fee- then went to under review
what happen to the applicant action and milestone of awaiting applicant revisions?
![image](https://user-images.githubusercontent.com/47611580/60600564-5e987280-9d7e-11e9-8941-47a8116b2c0f.png)
after resubmit complete in pdox- tolerance review generated in IPS- when are we updating the details page- missing applicant actions?

**Comment by dhenry-KCI** [comment]
@ABonomo21 - Confirm workflow, if comfortable we can close.
