### ISSUE TITLE
IPS/Pdox-planning-site plan- two review items under status check

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1299]
there are two review conditions under status check.  Didnt see this when testing plats. Should this also be in plats or is site  plan wrong?

![image](https://user-images.githubusercontent.com/4129185/60601748-9b656900-9d80-11e9-8ff7-3a756cbd6a79.png)

after resubmittal, only one review condition populated
![image](https://user-images.githubusercontent.com/4129185/60602326-9654e980-9d81-11e9-9e81-1f7681a836d8.png)

![image](https://user-images.githubusercontent.com/4129185/60602370-a7055f80-9d81-11e9-894f-6cf7b69ab35a.png)

**Comment by dhenry-KCI** [comment]
also happening in Preliminary Plat-MW
![image](https://user-images.githubusercontent.com/4129185/60611839-4ed85880-9d95-11e9-8eea-0f5ad14ca733.png)

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
