### ISSUE TITLE
Use - Gaming - Conditional Holds for Raffle and Tip Jars

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#13]
(Reported by Ashlye Bonomo 2/7/19)

For Raffle and Tip Jar permits the permit should hold between the Under Review and Closed milestones. A conditional hold should be in place to accommodate the waiting period for monthly and annual reports to be received. Permits should remain in an active status (issued) or reporting milestone and should not close out without reports being received.

There is currently a condition in IPS for MonthlyTIP that can be utilized for On and Off Premise Tip Jars. However, we will need additional conditions for: 
- Annual Organization (OFF Premise Tip Jar only)
- Annual Raffle

**Comment by calequin** [comment]
@ABonomo21 currently the permit falls in the "Awaiting Last Report" milestone until the "RPTRCVD - Report Received" condition is applied. Once applied to the permit then the permit goes in the completed milestone. Should this be changed?

**Comment by ABonomo21** [comment]
The Annual Organization report should only be for Off Premise Tip Jar Only not On Premise

**Comment by megisys** [comment]
Added Extended Description. As One COndition is enough.. It is purely a hold to say Ready to Close.

![image](https://user-images.githubusercontent.com/47392306/53697378-a098b400-3d9e-11e9-9a0d-f38c15bb9f88.png)

**Comment by ABonomo21** [comment]
All holds work- the permit will not close until they are approved.-AW

![image](https://user-images.githubusercontent.com/47611580/54772431-b51dde80-4bdd-11e9-96ee-96a3ac9cd6b8.png)
![image](https://user-images.githubusercontent.com/47611580/54772528-e9919a80-4bdd-11e9-89b9-e65f56fbd2cf.png)
