### ISSUE TITLE
IPS/Pdox-planning-site plan-wrong milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1300]
all reviews are approved.  IPS should be in schedule hearing milestone, not awaiting resub--MW

![image](https://user-images.githubusercontent.com/4129185/60602961-d36dab80-9d82-11e9-984c-4dc9c29b9b3f.png)

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
