### ISSUE TITLE
IPS/PDOCS - PRE PLAT - DUE DATES 1st review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1301]
PP244739 - FRO is the only agency that populated a due date on the first review.
While testing Site and Plat, we did not have this issue on the first review. Only subsequent reviews.
 AReed

![image](https://user-images.githubusercontent.com/4129185/60611896-6ca5bd80-9d95-11e9-9839-6586614e2b97.png)

**Comment by dhenry-KCI** [comment]
PP244739 Due Dates did not populate once reviews were resulted. In PLAT and SITE the due dates would populate once the reviews were resulted. AReed

![image](https://user-images.githubusercontent.com/4129185/60612390-7e3b9500-9d96-11e9-9381-7bbc6e053fbe.png)

**Comment by dhenry-KCI** [comment]
Due dates not populating on 2nd review. SP244775 AReed
PDox has 7/31 as due date and it is populating in pdox. No due dates populating in IPS

![image](https://user-images.githubusercontent.com/4129185/61400142-9da9e600-a89d-11e9-9c8b-cf67bf542c31.png)
![image](https://user-images.githubusercontent.com/4129185/61400170-af8b8900-a89d-11e9-9872-2ef8477eb3c3.png)

**Comment by megisys** [comment]
This has been addressed and Ready for ReTest

**Comment by dhenry-KCI** [comment]
Occurring in PWCONSTRUC also. Missing Due Date PW244799. AReed
![image](https://user-images.githubusercontent.com/4129185/61475103-140b1e80-a958-11e9-85b8-5af291a958fd.png)

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
