### ISSUE TITLE
IPS/Pdox-planning-preliminary plat-IPS milestone didnt change to awaiting resub

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1302]
resulted all reviews through pdox. IPS stuck in under review instead of awaiting application resubmit.

IPS started with two "reviews completeness" alerts.  Even though all reviews are complete one still remains.

![image](https://user-images.githubusercontent.com/4129185/60612384-7976e100-9d96-11e9-918a-b57eb9cf86cf.png)

![image](https://user-images.githubusercontent.com/4129185/60612487-b8a53200-9d96-11e9-9485-80a1d6c7628b.png)

MW

**Comment by dhenry-KCI** [comment]
this was before resulting reviews.

![image](https://user-images.githubusercontent.com/4129185/60612620-0cb01680-9d97-11e9-9381-759d0df8088f.png)

**Comment by dhenry-KCI** [comment]
went ahead and resubmitted, now we have three result reviews alerts.

![image](https://user-images.githubusercontent.com/4129185/60612765-78927f00-9d97-11e9-869c-d954800b5e98.png)

**Comment by dhenry-KCI** [comment]
resulted 2nd round of reviews and alerts still say pdox reviews must be complete. 

![image](https://user-images.githubusercontent.com/4129185/60612990-f8b8e480-9d97-11e9-8eb1-9e58bd651c47.png)

![image](https://user-images.githubusercontent.com/4129185/60613014-066e6a00-9d98-11e9-9f46-23fd6456fcf3.png)

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
