### ISSUE TITLE
PDox/IPS - PLANNING - Batch Manager - projects not coming through

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1306]
We created all PWCONSTRUCT, PLAT, FRO applications. We then ran Batch Manager. Resources --> ProjectDox Messages only shows a partial listing of the projects that should have transferred to PDox. PDox only has a portion of the projects that the ProjectDox Messages said it sent 

![image](https://user-images.githubusercontent.com/4129185/60732813-05b11180-9f19-11e9-9ba4-e74a2a2fe744.png)

Highlighted projects above, did not transfer to PDOX with batch manager

![image](https://user-images.githubusercontent.com/4129185/60731063-8f121500-9f14-11e9-9d25-a3825b80d8b8.png)  ProjectDox Messages - screen shot above, after running batch manager

![image](https://user-images.githubusercontent.com/4129185/60732971-840db380-9f19-11e9-99c3-8cdddc458ddc.png)
Mike's PDox screen shot - unable to see record #10 - PDox will not show under next or page 2.

![image](https://user-images.githubusercontent.com/4129185/60733048-c8994f00-9f19-11e9-9eea-bf3223b9fdca.png)
Ashley's screen will only show 1-6 and next and page #2 does not work

**Comment by megisys** [comment]
Removed Work Description and we are using Work.Code in the Description

**Comment by JuanitaMiles** [comment]
Marking as will monitor, batch manager appears to be running without error.
