### ISSUE TITLE
Resbldg- Impact Fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1307]
There have been two new impact fee category types created as of July 1, 2019. Which results in needing to add 12 new fees into IPS11 and all dwelling permits need to have the logic added to insert those fees. 

It is the fees on the spreadsheet for Bus Component and Land Component for both City and County permits. 

We will need to get this added to IPS and test!

![image](https://user-images.githubusercontent.com/47611580/60823361-5cb32280-a175-11e9-8581-ae59b1132a9b.png)

**Comment by megisys** [comment]
Dustin to Follow up with Jimi. 10 Hours of Effort believed here. Resource Needed. Needed for Go Live

**Comment by megisys** [comment]
New Set-Up is Complete. Existing School Impact Fees need Budget Number Update.. County Fix from here

**Comment by mmbanong** [comment]
The new school impact fees have been updated in IPS
![BUS Capture](https://user-images.githubusercontent.com/47392173/62072099-e6518f80-b20b-11e9-9852-bd77384c10ea.PNG)
![LND Capture](https://user-images.githubusercontent.com/47392173/62072106-e9e51680-b20b-11e9-92f1-8b2510cf225a.PNG)

**Comment by ABonomo21** [comment]
fees have been looking correct - will monitor during training closing for now
