### ISSUE TITLE
Log Entry - Portal vs public

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1308]
code enforcement should not have ANYTHING avaiable to the public or in the portal- when trying to clear the check boxes in preprod it will not let me remove them .. help

![image](https://user-images.githubusercontent.com/47611580/60835389-f76d2a80-a190-11e9-9d12-223ad8a08191.png)

**Comment by megisys** [comment]
They are not selected.. Also Case Types are not in Portal
