### ISSUE TITLE
R4C - Fees showing to Public. Need to be able to control this (Excel Issue #64)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1309]
Fees are showing as PUBLIC on R4C project look up. We would like them to be visible on the portal only. AReed/ABonomo/MWilkins 

![image](https://user-images.githubusercontent.com/47611580/60836632-1ae5a480-a194-11e9-95fc-0e00abe8ad64.png)

**Comment by calequin** [comment]
removed financial information from public view. Steps taken: Go to instrument detail portlet and remove financials from public view. Please retest

**Comment by ABonomo21** [comment]
Fees are still showing in a public search - Dustin was this something we turned off in the work Mike Ash and I did ? @dhenry-KCI

**Comment by ABonomo21** [comment]
Can someone check to make sure the fees being public was corrected in the back office public vs. private ? @dhenry-KCI

**Comment by dhenry-KCI** [comment]
ok per 199599

MW
