### ISSUE TITLE
Planning - Plat - DUSWM Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#131]
We are using the same parcel ID for two separate planning applications. The parcel detail information for each plan is identical. On AP # PL237366 a DUSWM fee generated. On AP# 237365 and AP#237367 a DUSWM fee did not generate. 

AP#237266 - is a Plat - Farm Lot
AP #237265 /AP #237267 - are addition

**Comment by megisys** [comment]
These AP Numbers are form completely different AP Types. @dhenry-KCI

**Comment by dhenry-KCI** [comment]
not resolved.  DUSWM fee generated on Farm Lot (PL237411)but not addition plat (PL237413)

![image](https://user-images.githubusercontent.com/4129185/53663617-349a3c80-3c34-11e9-9e4c-09bdf3a051a6.png)

![image](https://user-images.githubusercontent.com/4129185/53663580-1d5b4f00-3c34-11e9-8ffd-49f39b4569b7.png)

**Comment by megisys** [comment]
THis has been Addressed - Make sure the parcel details are complete..

**Comment by dhenry-KCI** [comment]
corrected - areed
pl237437
pl237438
