### ISSUE TITLE
PDOX - RESBLDG - Applicant Upload Task - Application Info

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1310]
When completing the Applicant Upload task, we were trying to view the information on the tabs across the top. Upon first glance there appeared to be nothing populating, however the issue is that the box is too small and you have to click on the scroll arrows to view any information.

![image](https://user-images.githubusercontent.com/31770504/60969064-9bb7b400-a2ec-11e9-8321-cc32db71464d.png)

**Comment by ABonomo21** [comment]
The same is happening for the prescreen review 

![image](https://user-images.githubusercontent.com/47611580/60973607-96f7fd80-a2f6-11e9-9cc5-7b3f8b62f712.png)

**Comment by dhenry-KCI** [comment]
appears to be working. Please retest.
