### ISSUE TITLE
PDOX - RESBLDG - Impact Fee Timing

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1311]
@ABonomo21 After Approving all reviews the application progressed to Awaiting Applicant Payment. This is where the Library and School Impact fees are assessed. Ken is asking why we wouldn't do the "Tolerance" review prior to having the applicant pay these fees?

![image](https://user-images.githubusercontent.com/31770504/60970904-f0f5c480-a2f0-11e9-81d8-c005e46d4ee1.png)

**Comment by JuanitaMiles** [comment]
After paying the Impact Fees, the application went to Pending Issuance with a status check of Batch Stamp Plans must be Completed in ProjectDox. We still have not received a Tolerance review to confirm the differences in Square Footage and fees associated.

![image](https://user-images.githubusercontent.com/31770504/60971542-6ca44100-a2f2-11e9-8792-18a311ffab95.png)

**Comment by JuanitaMiles** [comment]
Application progressed all the way to Inspections milestone without a Tolerance review.

![image](https://user-images.githubusercontent.com/31770504/60971819-fce28600-a2f2-11e9-93ee-22f01c6ba44b.png)

**Comment by megisys** [comment]
They said it was 4000 square feet on application and the Review saw less. It only works if we are short paid. I was told refunds dont happen. Not a valid use case..

**Comment by JuanitaMiles** [comment]
Agreed. We will have to test further with the correct tolerance values.

**Comment by dhenry-KCI** [comment]
Closing issue as tolerance reviews have not been an issue once we understood the workflow.
