### ISSUE TITLE
Building - RESBLDG - Fee "Applied By"

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1312]
When the system automatically generates fees, it applies the name of the last person to approve the review. Since the user did not manually add these fees, is there a way to remove their username from this column?

![image](https://user-images.githubusercontent.com/31770504/60971157-85f8bd80-a2f1-11e9-81b3-500c5483b810.png)

**Comment by megisys** [comment]
Can we just hide the column and then the problem goes away ?

**Comment by JuanitaMiles** [comment]
We can confirm with @ABonomo21 , but I would imagine it would be nice to see when a person actually did manually add a fee vs. when it was system generated. Since this would happen in the event of the tolerance review fee updates.

**Comment by megisys** [comment]
Cant have your cake and eat it too :) But as long as people are trained in the reason the name appears it maybe enough

**Comment by JuanitaMiles** [comment]
confirmed with Ashlye this is not an issue. If someone doesn't like to see this field it can be hidden on an individual basis.
