### ISSUE TITLE
PDOX - Batch Stamp Task - Files Not Moving to Approved

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1313]
I have completed the Batch Stamp task, but I did not have the ability to actually apply a stamp. Once completing the task, the Drawings did not move over to the Approved folder.

The Workflow is showing as Completed.

![image](https://user-images.githubusercontent.com/31770504/60972175-b8a3b580-a2f3-11e9-9362-0f947cc9d6d8.png)

![image](https://user-images.githubusercontent.com/31770504/60972213-cd804900-a2f3-11e9-982b-36d5dca0f700.png)

**Comment by RS-Avolve** [comment]
Yep, sorry about that Juanita.  I have given you and Dustin Batch Stamp permissions.  Should be no problem moving forward.
