### ISSUE TITLE
Building - Lookup Applications - AddedBy Field

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1314]
On the Building Lookup Applications window, put a space between Added and By. The field should read "Added By".

![image](https://user-images.githubusercontent.com/31770504/60973459-539d8f00-a2f6-11e9-8c90-0eef7e4afaae.png)

**Comment by mmbanong** [comment]
Dan has not shown me how to make changes to the user interface yet. I will jump on this as soon as I meet with him

**Comment by JuanitaMiles** [comment]
Martin fixed issue. Fixed in TEST. Martin to make update in PREProd as well.

**Comment by mmbanong** [comment]
Completed in Pre prod

**Comment by JuanitaMiles** [comment]
Fixed in both environments.
