### ISSUE TITLE
PDOX - Error 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1315]
Unsuccessful submission from IPS to PDox- for non res alteration work type- no clear reason why it would not have gone through. 

![image](https://user-images.githubusercontent.com/47611580/60974207-afb4e300-a2f7-11e9-8a86-1431d8fc2f6f.png)

**Comment by megisys** [comment]
This could be due to a temp outage to PDox. There is an Action on this screen to reset and the batch manager will process at another time.

**Comment by megisys** [comment]
The 3 Errors still exist. Will need Avolve support here

**Comment by dhenry-KCI** [comment]
Email sent to Robert on 7/23

**Comment by RS-Avolve** [comment]
I have checked my emails for a Project Create Error from Frederick County for this project number, for Frederick County in general, and for specific dates.  I cannot find any emails related to Project Create Errors for Frederick County.  As all emails from the Frederick County ProjectDox site are currently being redirected to me, I should have gotten emails.  Based on this behavior, I am not sure if the projects were ever submitted to the Project Creator Holding table.   I will ask Alejandro if he can check the table and see if the project named: "245940 - NONRESBLDG - Alteration - NRSMSC" is waiting to be submitted to ProjectDox.

**Comment by RS-Avolve** [comment]
Alejandro checked the Project Creator holding table.  The permit referenced in this ticket "245940 - NONRESBLDG - Alteration - NRSMSC" never made it into the holding table.  As such the information was not available to the ProjectDox Project Creator service to create the associated project in ProjectDox.  The App Type code is defined in ProjectDox as "NONRESBLDG" so the Application Type should create in the information is in the holding table.  The "....(500) Internal Server Error" message captured in the first ticket comment points to something happening when this was originally submitted; Alejandro feels the API call may have failed so the information never got into the holding table.

Have subsequent submissions of this application type successfully created projects within ProjectDox ?

**Comment by dhenry-KCI** [comment]
Have not been able to repeat error. Will continue to monitor.
