### ISSUE TITLE
PDOX - Review History

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1316]
is there a way to review the history of the review comments and variable fees/sq/ ft in PDOX.

**Comment by ABonomo21** [comment]
reviewers should be able to view their own reviews.

**Comment by RS-Avolve** [comment]
Reviewer comments within the eForm Comments box are available on the Resubmit Received activity, and on the Department Review eForms as the reviews are underway.  These comments are also available in the ProjectFlow - Department Review Status report.  Reviewer comments made on the changemark viewer are available throughout the review process when accessing the changemark viewer.

The values captured within the fields added to the eForms, such as Observed Square Footage are not "maintained" within ProjectDox reports or are they available through any means once the eForm containing that information is completed (closed).  They are only available for viewing when being added to the eForm.  These values of course are available on the IPS side.

**Comment by dhenry-KCI** [comment]
Confirmed working - closing and will leverage for training.
