### ISSUE TITLE
Project Dox-Reviewer Name Incorrect

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1317]
I assigned this review to myself but it transferred my name over to IPS as AVOLVE when it should be AWHITE.-AW
![image](https://user-images.githubusercontent.com/47611580/60976339-7da58000-a2fb-11e9-87f8-d6755ef70ded.png)

**Comment by dhenry-KCI** [comment]
Correction made for Awhite.

**Comment by ABonomo21** [comment]
closing will monitor during training
