### ISSUE TITLE
PDOX - Batch Manager - Process Error (Different Error from 1315)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1319]
Receiving the following error when trying to send various applications through Project Dox. 

![image](https://user-images.githubusercontent.com/31770504/60976351-826a3400-a2fb-11e9-9733-445692db41dc.png)

**Comment by megisys** [comment]
Addressed this Issue. AP's Need a Name for PDox

**Comment by dhenry-KCI** [comment]
appears corrected. Will continue to monitor.
