### ISSUE TITLE
Planning - Site Plan - Planning Review Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#132]
The system is generating an incorrect planning site planning review fee. The fee should be $2,304 + $92 / Disturbed acre where occupancy type = Non Residential.

**Comment by megisys** [comment]
This is Addressed..

**Comment by dhenry-KCI** [comment]
Type I site plan planning fee is correct. DUSWM is incorrect. Will create a new issue AReed
![image](https://user-images.githubusercontent.com/4129185/53661617-b8e9c100-3c2e-11e9-8cb4-0daf556dc750.png)
