### ISSUE TITLE
PDOX- Batch Stamp 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1320]
We need to clarify the batch stamp process in general 

batch stamp by a reviewer vs. overall approved batch stamp for planning and permitting

**Comment by dhenry-KCI** [comment]
Batch stamp will be in upper left corner. will include two final batch stamps:

a.	Permitting
i.	Frederick County Seal
ii.	Division of Planning and Permitting
iii.	Department of Permits and Inspections
iv.	Date batch stamping process was completed
v.	Gary Hessong signature
b.	Planning
i.	Frederick County Seal
ii.	Division of Planning and Permitting
iii.	Department of Development Review
iv.	Date populated in Approval Date field
v.	Mike Wilkins signature

**Comment by RS-Avolve** [comment]
Is the batch stamp process still unclear?  We had a discussion the other day with Nikki among others and not sure if questions are still outstanding.  I have to create the batch stamps - Dustin provided the specifics for the two stamps - I will try to have these stamps created by end of day tomorrow, Wednesday, July 24.

**Comment by dhenry-KCI** [comment]
@RS-Avolve - the batch stamp process is clear after our meeting. Ticket was created prior to ensure we follow-up with Avolve.

**Comment by ABonomo21** [comment]
dustin have the batch stamps been created? i do not recall seeing them @dhenry-KCI

**Comment by ABonomo21** [comment]
linked to #2192 - closing this one because it is a duplicate
