### ISSUE TITLE
Type of Construction Details Page -PreProd

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1322]
For Non Res building permits the Type of Construction Details Page is missing from Non Res

![image](https://user-images.githubusercontent.com/47611580/60979586-f8bd6500-a300-11e9-8462-5afdbb363815.png)

**Comment by megisys** [comment]
Added Back to Completeness Check

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/61883776-1118ac80-aec9-11e9-8519-68c1af10991a.png)
confirmed generated
