### ISSUE TITLE
PDOX- First in Group 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1323]
Please set the system to default to Individual as opposed to first in group at least for permits
need to check with planning to see if they want this as well

![image](https://user-images.githubusercontent.com/47611580/60980618-d0cf0100-a302-11e9-8f1e-cdc045080d70.png)

**Comment by RS-Avolve** [comment]
All Building (Permit) reviews are now set with an Assignment Type of "Individual", meaning the reviewer will have to be selected from the dropdown list at the "Assign Reviewers" activity.    All Planning reviews with the exception of: "Townrev", "Schools", "FCPC Manager", and "APFO" are set with an "Individual" Assignment Type by default.  These 4 Planning reviews are set with a FirstInGroup Assignment Type by default.

**Comment by dhenry-KCI** [comment]
Confirmed fixed.
