### ISSUE TITLE
License - Liquor License - Application Type Popup Error

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1324]
When clicking on the search popup on the Application Type field on the details page, I get the following error. This is during Start Application in the PreProd environment.

![image](https://user-images.githubusercontent.com/31770504/61057900-2e775200-a3c4-11e9-88aa-1bdd0e0623e9.png)

**Comment by calequin** [comment]
this was fixed in dev. preprod will be refreshed from this environment

**Comment by dhenry-KCI** [comment]
Confirmed closed.
