### ISSUE TITLE
PDOX- Building Resubmit - 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1326]
Resuse and Resbldg permits marked for resubmit in PDox  stuck in awaiting fees

![image](https://user-images.githubusercontent.com/47611580/61131937-5c25cf00-a488-11e9-9c2b-b358b5aac6c3.png)

IPS says it is back under review - fee was already paid 

![image](https://user-images.githubusercontent.com/47611580/61131974-6ea00880-a488-11e9-9b2c-98cfef463f1a.png)

non res 245973 , res use 245968 and resbldg 245970 all stuck in awating fees- 
![image](https://user-images.githubusercontent.com/47611580/61133719-fdfaeb00-a48b-11e9-9a51-e2d91143cb0c.png)

**Comment by JuanitaMiles** [comment]
Was a batch manager issue. Appears to be working correctly. Closing
