### ISSUE TITLE
License - Liquor License - Resubmittal Logs (Xtreme #13716982)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1327]
When completing the Applicant Actions detail page to perform a resubmittal requested on Completeness Check, the application generate three RESREC logs at once.

Testing in TEST environment, because I was getting the error identified in issue #1324 

![image](https://user-images.githubusercontent.com/31770504/61138292-3b17ab00-a495-11e9-829d-5e7d027c50a5.png)

![image](https://user-images.githubusercontent.com/31770504/61138329-4ff43e80-a495-11e9-82e6-755aa5e94a2a.png)

**Comment by calequin** [comment]
Infor xtreme ticket created.

**Comment by dhenry-KCI** [comment]
Confirmed fixed. LI244341
