### ISSUE TITLE
PLANNING - IPS - Work type

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1329]
Change to "Administrative Concept". Administration is incorrect.
![image](https://user-images.githubusercontent.com/4129185/61380950-4d6c5d00-a878-11e9-859a-c330f06f9271.png)
AReed

**Comment by megisys** [comment]
Code Def Fix.

**Comment by JuanitaMiles** [comment]
Confirmed fixed in IPS Test
