### ISSUE TITLE
Planning - Site Plan - Planning Review Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#133]
Where Occupancy type = Residential, the system should generate a flat planning site planning review fee of $2,304 + 10 / lot.

**Comment by megisys** [comment]
This has been addressed.. Thanks

**Comment by dhenry-KCI** [comment]
Planning fee 2304 + 10/lot is correct. Used 10 lots. Planning fee = 2404

![image](https://user-images.githubusercontent.com/4129185/53661053-71af0080-3c2d-11e9-8757-49943450fc43.png)
