### ISSUE TITLE
PLANNING - PDOCS/IPS - Miscellaneous redline showing on 2nd review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1331]
SP244775 
See highlighted Miscellaneous redline on status check in image. We would not be adding reviews here. This seems this should be a check that should be in the background. not showing under status check box. AReed

![image](https://user-images.githubusercontent.com/4129185/61399821-ef9e3c00-a89c-11e9-8fb5-8fbdf38e695c.png)

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
