### ISSUE TITLE
PDOX/IPS - PLANNING - DUE DATE 4TH REVIEW - SITE PLAN TYPE 1 & PRE PLAT

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1332]
The 4th review for a Site Plan Type 1 & PRE PLAT is (1) week. It is populating in IPS and PDOX as 2 weeks.  AReed
SP244775 
![image](https://user-images.githubusercontent.com/4129185/61400888-4442b680-a89f-11e9-97d9-5b5147f0e622.png)
![image](https://user-images.githubusercontent.com/4129185/61400926-56245980-a89f-11e9-9c05-e5cb27c8d5fe.png)

**Comment by megisys** [comment]
Adjustment Made

**Comment by megisys** [comment]
This was completed
