### ISSUE TITLE
PDOX/IPS - PLANNING - SITE PLAN Stuck in Under Review on 4th submission, didn't go to awaiting applicant resubmit on subsequent reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1333]
SP244775 - Milestone is in under review. All reviews are resulted, should be in awaiting applicant resubmit. I continued pushing through PDOX and when I completed the 5th review, IPS automatically populated the 6th review before the applicant resubmitted. See image of Applicant Resubmit Task for the 6th review that has not been completed. 
 AReed

![image](https://user-images.githubusercontent.com/4129185/61401103-b61b0000-a89f-11e9-9460-9c2cfd539891.png)
![image](https://user-images.githubusercontent.com/4129185/61401139-cb902a00-a89f-11e9-8ec9-98d78aa1e623.png)

See 6th review populated before it was completed in PDOX
![image](https://user-images.githubusercontent.com/4129185/61402228-a5b75500-a8a0-11e9-857c-83985fc2f043.png)

**Comment by megisys** [comment]
Dan Added wrong Status Check yesterday. removed.

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
