### ISSUE TITLE
IPS/PDOCS - PLANNING - PWCONSTRUC - Per sheet fees paid after first review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1334]
2nd round of reviews generated without fees being paid. Dan to discuss with Robert and Dustin.
AReed
PW244792
![image](https://user-images.githubusercontent.com/4129185/61479724-694c2d80-a962-11e9-9d76-a36e7eb29f3f.png)

**Comment by megisys** [comment]
We need to ensure that Project Dox projects are not being picked up from ProjectDox if their are associated fees. We need a report for these so we know which ones should be restarted in PDox
