### ISSUE TITLE
IPS/PDOCS - PLANNING - PWCONSTRUC - 3rd round of reviews populated before PDOX submittal

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1335]
3rd round of reviews populated with due dates in IPS before Applicant resubmitted in PDOX. PW244792
areed
![image](https://user-images.githubusercontent.com/4129185/61482238-2f7e2580-a968-11e9-8229-07d20ef60668.png)
![image](https://user-images.githubusercontent.com/4129185/61482264-39078d80-a968-11e9-9dab-de15f5671456.png)

**Comment by megisys** [comment]
This has been addressed

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
