### ISSUE TITLE
IPS/PDOCS - PLANNING - PWCONSTRUC - wrong milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1337]
PW244792 IPS should be in awaiting applicant resubmit. It went to under review and populated 4th review cycle when applicant has not resubmitted to PDOX.
AReed

![image](https://user-images.githubusercontent.com/4129185/61482946-c13a6280-a969-11e9-85fa-4d67f1d3d32f.png)
![image](https://user-images.githubusercontent.com/4129185/61482962-c9929d80-a969-11e9-84ce-af74a4881a4d.png)

**Comment by megisys** [comment]
We Believe this is addressed
