### ISSUE TITLE
IPS - Employee Record Information Update Error

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1338]
There are several employees in the system that have been created without a first and last name. As a result the Employee information cannot be updated. I get an error when trying to save my updates. 

When an employee record already has a first/last name I am able to update the person's email address without issue.

![image](https://user-images.githubusercontent.com/31770504/61545285-20a17c80-aa15-11e9-95c7-537d584bfbff.png)

![image](https://user-images.githubusercontent.com/31770504/61545345-4464c280-aa15-11e9-86ce-69fe7a1adea1.png)

![image](https://user-images.githubusercontent.com/31770504/61545377-58102900-aa15-11e9-83b3-f25d74051164.png)

**Comment by megisys** [comment]
Gerry Kelly Updated this

**Comment by JuanitaMiles** [comment]
i was able to update a formally corrupt record. Marking as will monitor, actual county staff's information will need to be correct upon go live. (not have christian's info)
