### ISSUE TITLE
Planning - Site - Planning Review Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#134]
The system is generating an incorrect DUSWM review fee. The system is displaying the residential DUSWM fee on a Non-res property. The correct fee for a non-res DUSWM fee is $486.

AP#236368
![sitefees](https://user-images.githubusercontent.com/4129185/53583309-51107900-3b4f-11e9-954f-37f9edb10d05.jpg)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/53598437-bb86e080-3b72-11e9-9793-e93cc1759dff.png)

**Comment by megisys** [comment]
There is NO Such Fee @dhenry-KCI

**Comment by dhenry-KCI** [comment]
@megisys the system shoud generate a DUSWM fee for non-residential (not the residential fee being displayed) the amount of the non-residential fee $486. Perhaps its the DUSWM SITE PLAN FEE COMMERCIAL FEE

**Comment by dhenry-KCI** [comment]
@megisys - i will provide an example from H7. Its a non-residential DUSWM fee, commercial was closest based on the list provided.

**Comment by dhenry-KCI** [comment]
@megisys - you emailed yesterday that the commercial fee has been expired since 2013. Below is an example of current AP using the fee that is under review:

![site plans](https://user-images.githubusercontent.com/4129185/53644889-ae670180-3c05-11e9-9f78-fdf378f63e4e.png)

The Commercial Fee - Initial should still be active.

**Comment by megisys** [comment]
THis is Addressed

**Comment by dhenry-KCI** [comment]
correct - areed
