### ISSUE TITLE
Ad Hoc Reporting - Description Output Columns Causing Issues (Xtreme #13703059)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1341]
When creating Ad Hoc reports, using Work Type and Occupancy Type Description as Output columns causes those records that have no value for those fields to be excluded from the report output. The Code must be used in place of the Description to get the correct number of output records.

Dan explained this was due to the relationship between Code and Description tables breaking down when trying to pull the records for the report.

![image](https://user-images.githubusercontent.com/31770504/61640429-4fb12b80-ac6b-11e9-9539-2114688358df.png)
 
![image](https://user-images.githubusercontent.com/31770504/61640595-99017b00-ac6b-11e9-86b7-d31699e1bb46.png)

![image](https://user-images.githubusercontent.com/31770504/61640655-b8000d00-ac6b-11e9-914c-1901d77cf489.png)

![image](https://user-images.githubusercontent.com/31770504/61640747-e1209d80-ac6b-11e9-88cd-3ac65cae54cf.png)

**Comment by calequin** [comment]
Logged xtreme ticket #13703059

**Comment by megisys** [comment]
Data Issue with Nulls
