### ISSUE TITLE
PDOX - PLANNING - Planning Coordinator

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1342]
PDOX assignment for "Additional Reviews Required Task" should be to the Coordinator that is selected on the first review instead of FirstInGroup. This project was assigned to Mike Wilkins but it populated as FirstInGroup.
AReed
![image](https://user-images.githubusercontent.com/4129185/61651748-8cd5e780-ac84-11e9-8578-a8683e7638a8.png)
![image](https://user-images.githubusercontent.com/4129185/61651819-aaa34c80-ac84-11e9-8bfc-a94cddccaf3d.png)

**Comment by RS-Avolve** [comment]
I had left staff members in the Project Coordinator group at the project template level for the sole purpose of facilitating testing.  That is I left multiple people in the group so multiple people had the opportunity to advance this task.  As testing is now well underway, I have changed this to how it will act going forward.  The "Planning Coordinator" group - which controls the "Additional Reviews Required Task" now, by default, has no one in the group at the project template level.  When the workflow advances to the  "Assign Reviewers" activity and staff selects a person to "Make workflow owner" the person is added to the "Planning Coordinator" group.  At that point, and only at that point, does this group actually contain a member, just one person.  That one person will be the person who will be responsible for completing the "Additional Reviews Required Task" when it is enabled after the reviews are all complete and approved.  That one person is the only person who will see this task in his/her task list.  I am not entirely sure what the "Assignment Type" will say - might still say First in Group, but there will only be one person responsible to complete that task.  This is effective as of now - 10:00 am ET, July 23, so all Planning projects created after this time will behave this way.

**Comment by JuanitaMiles** [comment]
Confirm fixed - Per A. Reed
