### ISSUE TITLE
PLANNING - IPS NOTIFICATION - Recordation Details - PLAT EMAIL to applicant

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1343]
AReed
-Change No of Pages to say Page Number. It is already pulling from the correct field in IPS. 
-Remove time recorded. Only include the date.
-Add Project/Phase Name field below the line that starts with "Your" (see green arrow)
-Remove comma after Your
Replace bottom line marked out in red with... 
Thank you,
Department of Development Review & Planning

![image](https://user-images.githubusercontent.com/4129185/61739708-fe806500-ad5a-11e9-9e69-3ec46527b2a7.png)

**Comment by JuanitaMiles** [comment]
Closing - Per A. Reed
