### ISSUE TITLE
R4C - Plumbing Misc Trade License - License Category Options (Xtreme #13702540)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1344]
When trying to create a Plumbing Misc Trade License in R4C, I think I'm getting too many options to choose from for the License Category. Some of the options are liquor board options. 

In the back office the only options I see are Journeyman and Septic System Installer.

![image](https://user-images.githubusercontent.com/31770504/61791451-0b976580-ade8-11e9-96b7-f5ba759fdb4a.png)

![image](https://user-images.githubusercontent.com/31770504/61791492-22d65300-ade8-11e9-902d-843541dfc5bc.png)

**Comment by JuanitaMiles** [comment]
This is also an issue for Electrical Trade License

![image](https://user-images.githubusercontent.com/31770504/61793585-78f9c500-aded-11e9-8be7-b88ceaa16eb0.png)

**Comment by calequin** [comment]
Infor Xtreme ticket has been created. Ticket 13702540

**Comment by megisys** [comment]
Asked Amy for update 8/5/2018

**Comment by megisys** [comment]
8/5/2019

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/63955805-5180c280-ca53-11e9-99bd-fe73baee6b60.png)
![image](https://user-images.githubusercontent.com/47611580/63955841-5e051b00-ca53-11e9-93a5-7bd60c7ed9c9.png)
