### ISSUE TITLE
R4C - Application Title Change 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1346]
![image](https://user-images.githubusercontent.com/47611580/61795868-574f0c80-adf2-11e9-97ff-c9ebf9e42f55.png)
Please change the title block to say "Permit, License and Planning Applications" 

and the language below should read "Apply for a permit, license or planning application."

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/61797143-70ed5580-adec-11e9-9edf-194abf50baf8.png)
