### ISSUE TITLE
IPS- Resubmit /Revision 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1348]
![image](https://user-images.githubusercontent.com/47611580/61797945-6e8ff900-adf6-11e9-9796-a83c86e62ef8.png)

Update " Send back to County with changes" to "Resubmit changes, pursuant to County request"
Update "Save and Do not send to County" to " Applicant request for revision/addendum"

for " Applicant request for revision/addendum" create a log that generates on a report to know some action is being requested. staff will make changes, insert fees and reviews etc.

**Comment by megisys** [comment]
Need Adhoc Report. Looking At Building Logs. And Logtype of CHGREQ where the stop date is no value.

**Comment by mmbanong** [comment]
Created adhoc report Revision addendum
![image](https://user-images.githubusercontent.com/47392173/62543188-56bf6880-b82b-11e9-89d0-3fd1ae1bf2d0.png)

**Comment by dhenry-KCI** [comment]
Confirmed fixed 
![image](https://user-images.githubusercontent.com/4129185/62973716-a3371500-bde4-11e9-947c-b158cdc1268e.png)
