### ISSUE TITLE
PLANNING - JUNK or whatever you want to call it

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1350]
I need the functionality of the work JUNK but it's gone. I don't care what we call it but I need to be able to close an application if it is Junk. AREED

![image](https://user-images.githubusercontent.com/4129185/61819655-76b15e00-ae21-11e9-8d98-92171fee6800.png)

**Comment by megisys** [comment]
We had this.. I lost the fight.. Please dont make me put it back :) Cause we do need it...

**Comment by dhenry-KCI** [comment]
verified correct areed
