### ISSUE TITLE
Building - Capacity - Meter Budget Code Not Set

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1352]
The Destination Budget # is not populating for the E Series 1 meter fee. See the screenshot from Hansen 7 (highlighted in blue) for the correct budget code.

![ips budget code](https://user-images.githubusercontent.com/31770504/61883026-a9159680-aec7-11e9-8e91-9a64c45002ad.png)

![budget code](https://user-images.githubusercontent.com/31770504/61881896-66eb5580-aec5-11e9-8f88-968fc8ac0b14.png)

**Comment by mmbanong** [comment]
Budget Number added for Meter Fees Series 1
![image](https://user-images.githubusercontent.com/47392173/61885130-563dde00-aecb-11e9-86d2-2a17592dc0a1.png)

**Comment by JuanitaMiles** [comment]
fixed
