### ISSUE TITLE
License - Distributor License - DISTRIBUT Resubmit Result

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1356]
When resulting a review with RESUBMIT the application did not go through a resubmittal loop. It went straight to Awaiting Fee Payment.

![image](https://user-images.githubusercontent.com/31770504/62073048-ec487000-b20d-11e9-94fa-226428e5a26c.png)

**Comment by JuanitaMiles** [comment]
For Distributor License - We need to remove all but the Approved option for the DISTRIBUT review as well.

![image](https://user-images.githubusercontent.com/31770504/62130077-3846f380-b2a6-11e9-9ceb-9a5f67fc0803.png)

**Comment by ABonomo21** [comment]
corrected
