### ISSUE TITLE
Planning -SIte Plan - Planning Review Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#136]
The system is generating an incorrect amount for the site plan review fee Type II. The correct amount for a Plan Review Fee - Type II - $678.

![original fees](https://user-images.githubusercontent.com/4129185/53583870-6cc84f00-3b50-11e9-9aa4-2ad65d6343f4.png)

**Comment by megisys** [comment]
Addressed this Issue

**Comment by dhenry-KCI** [comment]
verify fee is now correct-MW 3-1-19
![image](https://user-images.githubusercontent.com/4129185/53660681-6d361800-3c2c-11e9-9260-dc21b313f83a.png)
