### ISSUE TITLE
Business License - Distributor Report - Resubmit Notification Language

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1361]
For the Distributor Report, please update the language in the Awaiting Applicant Resubmit email notification to the following:

Hello (applicant name)- 

More information or details are required on your recent report submission for license # (blah). 

Please Log into our Portal :- https://frederickcountymd.gov/
Your Permitting and Licensing team at Frederick County. 

![image](https://user-images.githubusercontent.com/31770504/62149146-114de900-b2c9-11e9-9ac3-d1be4cf381a3.png)

**Comment by JuanitaMiles** [comment]
Language not updated per issue.

**Comment by megisys** [comment]
Juanita. Distributor REPORT doesn't have its own notification. They are shared for all business licenses. Do we really need to come up with individual template.. THIS is alot of upkeep and Code

**Comment by megisys** [comment]
This is such a small group of folks

**Comment by ABonomo21** [comment]
will look at all notifications with juanita
