### ISSUE TITLE
Trade License - Resubmittal/Applicant Actions

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1366]
Similar to #1031 the comments the applicant received from the County are buried in R4C, requiring the user to Click ALL and the VIEW Details. Per Dan these comments should be displayed within the MORE INFORMATION REQUIRED box.
![Comments Buried - All - View Details](https://user-images.githubusercontent.com/4129185/62225079-c3e38180-b385-11e9-93ee-136a90804c33.PNG)

**Comment by calequin** [comment]
fixed in test and added status check link to the detail page
![image](https://user-images.githubusercontent.com/47603568/62240041-b802ba00-b39b-11e9-8c21-fac38d96ef20.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/63953123-bab20700-ca4e-11e9-8294-22935b1fdf11.png)
