### ISSUE TITLE
Utility License

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1367]
![image](https://user-images.githubusercontent.com/47611580/62225155-e70e3100-b385-11e9-88c9-c2725ae63a03.png)

The Drivers license taken question is already asked on trade license detail page to be consistent with the other trades remove from utility detail page 

![image](https://user-images.githubusercontent.com/47611580/62225252-1329b200-b386-11e9-9f08-899ad1711c02.png)

**Comment by megisys** [comment]
This can not be done. As the Hansen 7 applications historic data will be here

**Comment by ABonomo21** [comment]
good
