### ISSUE TITLE
IPS - PLANNING - PWCONSTRUC - Fees for DUSWM

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1369]
Change fees below to be able to change quantity on fee screen. Be sure not to change the ones that are similar that say "Initial"
AReed

FEE NAME: MAJOR REVISION - DUSWM FEE
VALUE $138
QUANTITY - NEED TO BE ABLE TO CHANGE TO CALCULATE BASED ON NUMBER OF SHEETS

FEE NAME: W & S - FEE (LINES)
VALUE $325
QUANTITY - NEED TO BE ABLE TO CHANGE TO CALCULATE BASED ON NUMBER OF SHEETS

FEE NAME: W & S - FEE (FACILITIES)
VALUE $500
QUANTITY - NEED TO BE ABLE TO CHANGE TO CALCULATE BASED ON NUMBER OF SHEETS

**Comment by megisys** [comment]
Added

**Comment by dhenry-KCI** [comment]
Verified each fee type and quantity works PW244981 PW244982
AReed
