### ISSUE TITLE
Planning - Site Plan - DUSWM Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#137]
The system is generating an incorrect fee for the DUSWM. The Fee should be the DUSWM Site Plan Revision fee for $104.00, NOT the DUSWM Site Plan Feel - Res Intiial.

This is true wherever , Application Type = Site Plan and Work Type = Type II

![original fees](https://user-images.githubusercontent.com/4129185/53583980-a731ec00-3b50-11e9-9ffa-a9d6e2987936.png)

![fees-duswm](https://user-images.githubusercontent.com/4129185/53584027-b87af880-3b50-11e9-9b83-0342634b15d6.jpg)

**Comment by megisys** [comment]
This is addressed..

**Comment by dhenry-KCI** [comment]
DUSWM Fee correct - ok to close AReed

![image](https://user-images.githubusercontent.com/4129185/53660707-8212ab80-3c2c-11e9-8abe-b86f66307625.png)
