### ISSUE TITLE
R4C-Planning (and permits?)-dont allow adding attachments or adding comments while in under review milestone (Excel #68)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1372]
we dont want an applicant to be able to upload attachments while the previous submittal is under review.

MW

**Comment by dhenry-KCI** [comment]
we also dont want an applicant to add any comments and submit from R4C while project is under review

**Comment by calequin** [comment]
sent to dev for review

**Comment by calequin** [comment]
need BeforeAdd formula on attachments and a BeforeUpdate for comments. Description of Work constraint needs to be set to Read Only

**Comment by megisys** [comment]
Add to Dan West List.. I dont his a formula will work as I think it adds to the catalog first and then associates

**Comment by dhenry-KCI** [comment]
failed on Planning.  was able to add attachments during review.  They didnt sow in IPS but in the R4C side it appears they were success.  MW

![image](https://user-images.githubusercontent.com/4129185/64370711-ffa8e100-cfec-11e9-8a3b-673007fd7335.png)

**Comment by megisys** [comment]
There is truly nothing I can do here for this ticket.. It will need to be a business case and pushed to Dan West Through Jimi. As this is core product I don't think we are going to get an alternative solution in time.

**Comment by dhenry-KCI** [comment]
@calequin - looping you in so you are aware.

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/68909048-abb82800-0712-11ea-8390-d0e3a413c1a0.png)

**Comment by dhenry-KCI** [comment]
fixed-MW

![image](https://user-images.githubusercontent.com/4129185/69554875-6dbbcf00-0f70-11ea-8b21-32177671e8f5.png)
