### ISSUE TITLE
IPS-attachments

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1373]
when multiple attachments are in IPS, when you fist open a project one attachment doesnt show up unless you leave attachment tab and go back.

![image](https://user-images.githubusercontent.com/4129185/62238743-9b698080-b3a1-11e9-99d5-ee6ebbcb0500.png)

![image](https://user-images.githubusercontent.com/4129185/62238786-aa503300-b3a1-11e9-85cf-f4eb2608df20.png)

MW

**Comment by megisys** [comment]
I think the record was open when it was unloaded through R4C. Application will need to be fully closed to see the full attachment listing

**Comment by dhenry-KCI** [comment]
Closing. All attachments opened correctly
