### ISSUE TITLE
IPS-completeness check- N/A result needs to be renamed

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1374]
this use to be junk.  We now have two N/A's, one for completeness check and one for reviews and they mean and do two different things.  Rename the completeness check N/A to something else.

MW

**Comment by megisys** [comment]
Created NFC - Not a Frederick County Application

**Comment by dhenry-KCI** [comment]
good

![image](https://user-images.githubusercontent.com/4129185/64176967-7e0a5500-ce2c-11e9-8c9b-7f9d31ac4467.png)


MW
