### ISSUE TITLE
Notifiications - Trade License Notification Language

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1375]
@mmbanong , 
PLease update the notification language for trade licenses based on the attachment below.

[Trade Language Notifications.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3453643/Trade.Language.Notifications.pdf)

**Comment by mmbanong** [comment]
![Trade Lic Notifications](https://user-images.githubusercontent.com/47392173/62485325-689cff00-b78a-11e9-86e2-784e64f2e215.PNG)
Notification language for trade licenses has been updated based on the attachment
![Trade Lic Notifications2](https://user-images.githubusercontent.com/47392173/62485329-6c308600-b78a-11e9-9eb8-ee835f6b9d8d.PNG)
![Trade Lic Notifications3](https://user-images.githubusercontent.com/47392173/62485338-6e92e000-b78a-11e9-86a8-e7d9a13fe29a.PNG)

**Comment by ABonomo21** [comment]
will check all notifications and update ourselves. 9.5.19 ab Dustin to set up a meeting
