### ISSUE TITLE
R4C - Trade License - Confirm Business Details Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1377]
The Confirm Business Details page layout of fields needs to mimic the detail Trade License Details layout.

The "Yes" on the Confirm Details Page should be a back office function only. This is for County staff to confirm they have reviewed and accept the information and attachments pertaining to the renewal.

![image](https://user-images.githubusercontent.com/4129185/62244721-04ef8c00-b3ae-11e9-8d8d-5403bd78f23c.png)

![image](https://user-images.githubusercontent.com/4129185/62244847-4b44eb00-b3ae-11e9-8296-1199b1e0c5fe.png)

**Comment by calequin** [comment]
I have rearranged the fields to mimic as close as possible with the exception of the first label which only applies to the Trade License details. I have also removed the confirm details from being visible in r4c.

**Comment by calequin** [comment]
The confirm license details page populates when an applicant has entered the Issue License milestone. This is used for renewal purposes. The Yes has been set to display in portal = False.

**Comment by JuanitaMiles** [comment]
Company Phone and Email are still mixed up but good enough. Closing. 9/23

![image](https://user-images.githubusercontent.com/31770504/65441197-fe9eee80-ddf7-11e9-9e60-56820c363f2d.png)
