### ISSUE TITLE
Trade License - Appliance - Correspondence Email w/ Card Print Attachment

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1378]
The Correspondence Email with the issued Card Print Attachment did not send for the Appliance Master Trade License. This should have sent at the Active milestone.

**Comment by ABonomo21** [comment]
did not receive a notification of license issuance with a link to download and print card
PU244417

**Comment by mmbanong** [comment]
Awaiting clarification from Tara

**Comment by TaraF** [comment]
Hi Martin - the Appliance Master Trade License falls under PlumbingLicenseCardbyLicense Report.  Both  the Plumbing and Electrical License Official Card Prints use the report TradeLicenseCardByLicense.

**Comment by dhenry-KCI** [comment]
@mmbanong - sometimes the comment doesn't save, what's your question?

**Comment by dhenry-KCI** [comment]
@mmbanong - sometimes the comment doesn't save, what's your question?

**Comment by mmbanong** [comment]
There is a scheduled correspondence but No notification at the Issue License milestone. Do we need one?
I am assuming the correspondence email was not sent due to the identified issues

![image](https://user-images.githubusercontent.com/47392173/64437048-83b5a400-d093-11e9-84ed-7ffba71018f0.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - Same as other CM issues. Please resolve and erroring reports and once fixed change label to ready for retest.

**Comment by mmbanong** [comment]
I am getting notification but correspondence still fails.
I will continue to investigate

![image](https://user-images.githubusercontent.com/47392173/64643793-314fec80-d3df-11e9-8839-59279a4121e0.png)

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
