### ISSUE TITLE
Trade License - Appliance - Renewal Review Result Options

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1379]
The Renewal Review result options on Trade Licenses should be limited to only the APPROVED option.

![image](https://user-images.githubusercontent.com/4129185/62246916-ae388100-b3b2-11e9-8359-c45b55d96f5e.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/63955511-d0293000-ca52-11e9-8c0c-431f7fd4e05f.png)
