### ISSUE TITLE
Case - Health Service Requests - Rodent Complaint Request Type

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#138]
The Health Dept does not investigate rodent complaints. Remove this as a service request type.

![image](https://user-images.githubusercontent.com/31770504/53584651-165c1000-3b52-11e9-9490-e9a2fedc2706.png)

(Reported by Karen Amoss / Nina Stewart / Kim Dillman 1/25/19)

**Comment by calequin** [comment]
removed from Test

**Comment by ABonomo21** [comment]
corrected - removed
