### ISSUE TITLE
Planning - NID - Issue Letter in LOG

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1380]
Issue Letter came up in the LOG. There is no Issue Letter under NID.
AReed

![image](https://user-images.githubusercontent.com/4129185/62298665-70cf0480-b441-11e9-8cc2-96450228125c.png)

**Comment by megisys** [comment]
Ignore these. This is just telling you it went through the milestone. This has no bearing..
