### ISSUE TITLE
PLANNING - NID - CORRESPONDENCE of OUTCOME

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1382]
Need a notification to applicant for completion of NID review. Applicant shouldn't have to go into R4C and look under closed projects to find results.
Areed

![image](https://user-images.githubusercontent.com/4129185/62300015-0f5c6500-b444-11e9-9c16-cab34f109dd8.png)

**Comment by megisys** [comment]
Arent you writing an actual document in Word. Do we have an output for an NID please.

**Comment by dhenry-KCI** [comment]
We are not writing an actual document for this. The review result options are the results and any additional comments concerning the NID will be in the comment field under the review. AReed

**Comment by megisys** [comment]
Needs to include the Review Result and the Review comment of the final approval. as a Correspondence.

**Comment by dhenry-KCI** [comment]
Notification to be generated- opportunity for a future report.
