### ISSUE TITLE
Utility Renewal - Fee Payment

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1384]
Fee payment is not working for renewal on R4C but was able to pay the initial fee 

![image](https://user-images.githubusercontent.com/47611580/62302356-3157e680-b448-11e9-8c3c-9a0df3d19792.png)

**Comment by megisys** [comment]
Fixed as part of larger issue

**Comment by ABonomo21** [comment]
was able to pay both initial  fee and renewal fee on R4C-aw
![image](https://user-images.githubusercontent.com/47611580/63950002-38731400-ca49-11e9-9252-a481aa2fa8af.png)
