### ISSUE TITLE
Trade License - Renewal R4C instructions 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1385]
Once a Renewal log is generate on a trade license the notification email should be sent to the applicant to notify them to log into their portal. 

The instructions page for r4c should automatically be view-able instead of having to drop it down so that we can tell applicants what they need to do to complete their renewal 

confirm license details
upload required documents as attachments 
pay fees

![image](https://user-images.githubusercontent.com/47611580/62302779-ec807f80-b448-11e9-9928-6a7667e43333.png)

**Comment by ABonomo21** [comment]
right not there are no clear instructions for the applicant so when they log in hey can pay their fee and not update anything !

**Comment by calequin** [comment]
I have added the instructions in the "awaiting renewal detail" milestone status check. this allows the citizen to view it in his/hers  outstanding tasks list.

**Comment by ABonomo21** [comment]
the instructions are there on the R4C page, however the instructions reference for them to complete the submittal questions below but there are no questions/fields for them to complete and send back to the county-aw
![image](https://user-images.githubusercontent.com/47611580/63954763-a0c5f380-ca51-11e9-9b2e-c7cc9b8655c8.png)

**Comment by calequin** [comment]
added the following:
Please attach the following documents in addition to completing the Trade License Details below:

During Renewal Period please complete the "Confirm Trade License Details"

also the needs action button will reflect that a confirm license needs to be finished

**Comment by JuanitaMiles** [comment]
The "Confirm Trade License Details" link on Electrical License instructions in R4C does not work properly. When I click the link it opens a new tab with a blank rhythm page.

![image](https://user-images.githubusercontent.com/31770504/64370882-57474c80-cfed-11e9-9173-b13cbca59e12.png)

![image](https://user-images.githubusercontent.com/31770504/64370903-60381e00-cfed-11e9-9c97-2f62a5304026.png)

**Comment by calequin** [comment]
removed the hyperlink and added clear verbiage.

**Comment by JuanitaMiles** [comment]
Instructions have been added

![image](https://user-images.githubusercontent.com/31770504/65441818-0ca13f00-ddf9-11e9-89cb-0c3043156acb.png)
