### ISSUE TITLE
PLANNING - APFO - additional fees owed - no email received

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1386]
An email should be sent any time fees are owed. No email received. LOU review fee added on first review. Notification showing is from the initial fees. 
AReed

![image](https://user-images.githubusercontent.com/4129185/62315397-3bd3a980-b463-11e9-8418-09a5d7da9ac7.png)

**Comment by megisys** [comment]
Saem #1393 Closign as Duplicate
