### ISSUE TITLE
R4C - Look Up 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1389]
Not all details show up on look up for permit record in R4C - why didnt the inspection, review details etc. show up ?? 

![image](https://user-images.githubusercontent.com/47611580/62374532-2c5b6b80-b50a-11e9-837b-e64d9d8793f1.png)

![image](https://user-images.githubusercontent.com/47611580/62374557-35e4d380-b50a-11e9-8070-d40fdf28deae.png)

**Comment by calequin** [comment]
Looks like the is public checkboxes have been turned off in the back office. I believe this was being worked and determined by the county.
![image](https://user-images.githubusercontent.com/47603568/62489801-54a6cc80-b78d-11e9-885e-e88b14a5e403.png)

**Comment by mmbanong** [comment]
Turned on the isPublic for Electrical AP type on as per my conversation with Dan
![image](https://user-images.githubusercontent.com/47392173/62789129-5080f480-ba96-11e9-80c4-f610b1ba50f0.png)

**Comment by calequin** [comment]
sent email to Abbie and Ashlye to get guidance on public lookups

**Comment by JuanitaMiles** [comment]
When retesting - discuss with Juanita first if the issue appears to fail retest. Dan and Christian explained a few things during our 9/10 meeting. Dan also mentioned that he didn't think it is a good idea to put the Conditions on Rhythm and mentioned the Hold/Condition process should be handled a little differently and may need a redesign.

**Comment by ABonomo21** [comment]
conditions need to be shown on R4C as discussed with Dan.

**Comment by megisys** [comment]
Conditions are not going to show up.. We dont use conditions. And if we turn them on all the old ones will turn up. We do not want to go down this path. Which conditions are you most worried about please.

Dan

**Comment by ABonomo21** [comment]
conditions need to show up we can have another larger discussion but it is necessary for applicants to see holds/conditions such as p&i hold, u&o hold, COP hold, trade permits required holds. 

this needs to happen - @dhenry-KCI @megisys

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/65617422-b532d880-df8a-11e9-9d55-a5716ddabad2.png)

i want the comment to show up.

**Comment by ABonomo21** [comment]
christian showed us where conditions generates- ashlye wants the comments so christian will add this as an enhancement

**Comment by ABonomo21** [comment]
explore alternative options if the comments cannot be generated

**Comment by ABonomo21** [comment]
@calequin @dhenry-KCI - is this going to be put on a release for r4c? 

otherwise we will definitely want this addressed in the future/ post go -live

**Comment by calequin** [comment]
spoke to our IPS product team about this. Conditions are meant to be a back office task therefore the comments are meant to be internal and not public facing. If staff wants to inform the constituent of an issue or hold the staff can add it to the review or as a log that is public/customer facing.

**Comment by ABonomo21** [comment]
need to get the notification for holds as conditions

**Comment by megisys** [comment]
Need to add Log to notifications so BP_Hold works
