### ISSUE TITLE
Planning - Site Plan - Ag. Cluster Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#139]
The system is generating an additional Environmental Health Concept Fee for Site Plans with a work type = Ag cluster. The health concept fee should only generate when work type = Multi-agency concept plan (this work type is missing from the drop down see #140 ).

**Comment by megisys** [comment]
This has been addressed..

**Comment by dhenry-KCI** [comment]
Correct fees for Ag Cluster
![image](https://user-images.githubusercontent.com/4129185/53659977-df0d6200-3c2a-11e9-9db6-51cba84d4f0a.png)

**Comment by dhenry-KCI** [comment]
Issue resolved AReed
