### ISSUE TITLE
Code Enforcement - Follow up Inspection

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1392]
waived inspection still populated a follow up inspection on # 2
- should not have 
![image](https://user-images.githubusercontent.com/47611580/62378669-536a6b00-b513-11e9-9efb-9431065f4df2.png)

**Comment by calequin** [comment]
fixed followup inspection formula as follows
'  Formula Name: CE_AddBuildingFLLPInspection_AOC
'  Description: Add building case inspection by case group
'  Created By: Christian Alequin
'  Created On: 09/05/2018

Dim Res as Result
AddonCondition = False
For each oInspection as Hansen.CDR.CodeEnforcement.IInspection in oCase.Inspections

If oInspection.inspectiontype.code = "BLDG-CASE" Then
	If oInspection.InspectionResult.Code = "FAILED" Then
		AddonCondition = True
	
End If
	End If

Next

**Comment by ABonomo21** [comment]
fixed
