### ISSUE TITLE
Master Plumbing Fee - Wrong 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1394]
Master plumbing fee came up at the 50% rate to early - should not start until 8.13.19

![image](https://user-images.githubusercontent.com/47611580/62395024-0dc29800-b53d-11e9-896c-99e00489e47c.png)

![image](https://user-images.githubusercontent.com/47611580/62395109-43678100-b53d-11e9-9b05-26c6393c27ff.png)

**Comment by ABonomo21** [comment]
related to #1401

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/62476094-5adc7f00-b774-11e9-9367-aff848d1a6c5.png)

**Comment by megisys** [comment]
uPDATED IN dev

**Comment by ABonomo21** [comment]
unable to test due to currently being within the last three months of our licensing fee. therefore the 50% rate is correct-aw (today's date: 8/29/2019)

**Comment by ABonomo21** [comment]
closing due to unable to test due to currently being within the last three months our licensing fee.-aw
