### ISSUE TITLE
master plumber- renewal review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1395]
marked renewal review as a resubmit and the license still renewed moved to active and issued a new card- 

![image](https://user-images.githubusercontent.com/47611580/62395477-60508400-b53e-11e9-905e-661cf4a8120f.png)

**Comment by megisys** [comment]
Approved should be the only option

**Comment by ABonomo21** [comment]
renewal review auto generated and approval is the only option-aw
![image](https://user-images.githubusercontent.com/47611580/63952221-2e531480-ca4d-11e9-9ade-aee3d9c87fca.png)
