### ISSUE TITLE
Trade License - MISC Plumbing

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1397]
Sent resubmit back to the county at completeness check and a second review did not generate for the completeness check to be resulted

![image](https://user-images.githubusercontent.com/47611580/62468920-2b724600-b765-11e9-83e3-8a795e8288f4.png)

![image](https://user-images.githubusercontent.com/47611580/62468958-3dec7f80-b765-11e9-9439-83c3e4156c5b.png)

**Comment by megisys** [comment]
Updated Formula to ignore additional information if a resubmit is asked for.

**Comment by ABonomo21** [comment]
second completeness check generated-aw
![image](https://user-images.githubusercontent.com/47611580/63951035-0bbffc00-ca4b-11e9-8db7-4aeac40df8ce.png)
