### ISSUE TITLE
License - Distributor Report - Monthly Sales Grid: Name of Business

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#14]
(Reported by Kelly Vanaman 2/6/19)

On the Distributor Report (License Module) Start License Details page, received an error indicating "Name of Business must have unique value". Distributors will need to enter multiple lines for the same organization, as they can buy several types of Tip Jar "bags" with different profit values within the same month.

Can we make the Name of Business field allow non-unique values?

![image](https://user-images.githubusercontent.com/31770504/52421515-32741080-2ac2-11e9-8280-637aae19412c.png)

**Comment by megisys** [comment]
Added a Review before fees generate.. Just send back to applicant

**Comment by dhenry-KCI** [comment]
Not corrected - still received the same error of "Name of Business must have unique value" when adding a business of the same name  - AB retest 2.11.19
![image](https://user-images.githubusercontent.com/4129185/52591113-0f729500-2e11-11e9-856a-49a288e7d8b5.png)

**Comment by megisys** [comment]
This has been resolved
