### ISSUE TITLE
Planning - Site Plan - Work Type 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#140]
Missing work type = Concept Plan - Multi-Agency from work type drop down. 
When the user selects Wor type = Concept Plan - Multi-Agency the following reviews should generate:
- DPZ (Always)
- DRTE (Always)
- DUSWM (Conditional)
- Health (Always)
- FRO (Always)
- PWDR (Always)
- SHA (Conditional)
- Historic (COnditional)

The following fees should generate:
Planning Fee = $600.00
Engineering Review Fee = $115.00
Health Department Review = $75.00
Water / Sewer (Conditional on DUSWM Review) = $104.00

**Comment by megisys** [comment]
THis is Addressed

**Comment by dhenry-KCI** [comment]
missing work type-concept plan- confirmed fixed. 
![image](https://user-images.githubusercontent.com/4129185/53657765-0eb96b80-3c25-11e9-8c15-9888587a3bf7.png)

DUSWM fee populated twice. 
Health department fee did not populate
![image](https://user-images.githubusercontent.com/4129185/53658100-e8480000-3c25-11e9-9433-31a9031a4751.png)

Historic review not populating
![image](https://user-images.githubusercontent.com/4129185/53659591-f566ee00-3c29-11e9-9e6a-ebe369c6f469.png)

All other agencies populated


Mike Wilkins 3-1-19

**Comment by megisys** [comment]
Ashley Reed and I made Historic - A Add by Reviewer.. PLease Check this again.. You are asking for EH and DUSWM to both add.. This seems backwards. WE can look at this on  Monday

**Comment by dhenry-KCI** [comment]
@megisys - Historic reviews should populate when the user checks the Historic Checkbox on the details page. This should occur on Site, Plat and Pre-Plat Aps

**Comment by dhenry-KCI** [comment]
correct - Dan corrected on site - AReed
