### ISSUE TITLE
Trade License- Misc - Renewal Resubmit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1400]
selected resubmit on renewal review- license went back to active - said there is a pending task in r4c but there is nothing to complete- 
![image](https://user-images.githubusercontent.com/47611580/62470215-eef41980-b767-11e9-9aae-3c7aeb1259b9.png)
![image](https://user-images.githubusercontent.com/47611580/62470229-f5829100-b767-11e9-8ecf-1a9052c7b99c.png)

![image](https://user-images.githubusercontent.com/47611580/62470244-03381680-b768-11e9-9d52-f067e524ffcb.png)

**Comment by megisys** [comment]
Renewal review should only have approved option.. No resubmit cycle.

**Comment by ABonomo21** [comment]
approved is the only option on renewal review-aw
![image](https://user-images.githubusercontent.com/47611580/63953746-ed103400-ca4f-11e9-8d87-35d8fb90952f.png)
