### ISSUE TITLE
Use Permits - Gaming - Gaming Permit Official Issuance Reports

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1404]
Report did not launch in IPS back office, and it did not attach as an attachment in R4C.

**Comment by mmbanong** [comment]
I got an email with an attachment from IPS 
[Gaming_Permit_-_Official_Issuance.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3468603/Gaming_Permit_-_Official_Issuance.pdf)

**Comment by JuanitaMiles** [comment]
Still not getting the report in email, and it is not attaching to the permit on the Attachments tab. Could be due to issue #1479

**Comment by dhenry-KCI** [comment]
@mmbanong - please check again. Juanita was unsuccessful getting the permit to attach.

**Comment by dhenry-KCI** [comment]
@mmbanong - Cm is running now. Please review the batch manager schedule and resolve any CM reports that are still erroring. Once corrected please change label to Ready for retest.

**Comment by mmbanong** [comment]
Got Gaming Permit notification and Correspondence email and attachment

![image](https://user-images.githubusercontent.com/47392173/64637751-702b7580-d3d2-11e9-9b9a-acade36c547b.png)

[Gaming_Permit_-_Official_Issuance_JWISNER_20190910_015052267.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3597072/Gaming_Permit_-_Official_Issuance_JWISNER_20190910_015052267.pdf)

![image](https://user-images.githubusercontent.com/47392173/64637835-9fda7d80-d3d2-11e9-9e90-437e0c6f23ea.png)

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
