### ISSUE TITLE
Notifications - Awaiting Applicant Payment Milestones

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1406]
@mmbanong add language to the notification reading:
_Please disregard this email if fees were paid in-person at the County_

![notifications](https://user-images.githubusercontent.com/4129185/62474407-d1777d80-b770-11e9-98fc-d5c6ff7a3ed1.PNG)

**Comment by mmbanong** [comment]
The change has been made for all Awaiting Applicant Payment notifications
![Awaiting Applicant Payment](https://user-images.githubusercontent.com/47392173/62482175-7d759480-b782-11e9-9648-10f00114ec16.PNG)

**Comment by mmbanong** [comment]
Change had been made on all Awaiting Applicant Payment notifications
![Awaiting Applicant Payment](https://user-images.githubusercontent.com/47392173/62482304-c9c0d480-b782-11e9-8d9b-d4853c05c524.PNG)

**Comment by dhenry-KCI** [comment]
done
