### ISSUE TITLE
Planning - Site Plan - Sketch Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#141]
Fees for the Site plans where work type = Sketch are in correct. Fees should be based on the firsts screenshot below with the exception of the environmental health sketch fee as this should be expired.

![image](https://user-images.githubusercontent.com/4129185/53588217-6939c580-3b5a-11e9-9644-c4420c9ea824.png)

Additionally - this screenshot was from snapshot - the screenshot below is from test where the fees amounts are ALL incorrect.

![sketch](https://user-images.githubusercontent.com/4129185/53588286-8ff7fc00-3b5a-11e9-9f29-907bbda836d5.jpg)

**Comment by megisys** [comment]
This is addressed..

**Comment by dhenry-KCI** [comment]
Fee incorrect.
Environmental Health Sketch Fee is $75.00

![image](https://user-images.githubusercontent.com/4129185/53657993-a5862800-3c25-11e9-8d77-daca4a3c73a6.png)

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
fixed MW
![image](https://user-images.githubusercontent.com/4129185/53744076-3fd6ad80-3e6a-11e9-99bf-a8897d3d6493.png)
