### ISSUE TITLE
Gaming Permit - 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1412]
permit is closed- did not generate a final date or expiration date 

![image](https://user-images.githubusercontent.com/47611580/62485090-b82efb00-b789-11e9-832e-b81707dd9c44.png)

**Comment by megisys** [comment]
What should they be please. When is Expire Date ?

**Comment by megisys** [comment]
End of Year

**Comment by megisys** [comment]
Expiry to match End date once completeness check is completed

**Comment by calequin** [comment]
This particular example is missing the end date on the job description therefore the system did not generate the expiration date. For single occurance an end date is needed.

**Comment by megisys** [comment]
No this is for me

**Comment by JuanitaMiles** [comment]
Expiration populated but the Final Date did not populate upon entering the Complete milestone.

![image](https://user-images.githubusercontent.com/31770504/63280590-13c4b280-c279-11e9-9a09-67aa72cdbff5.png)

**Comment by JuanitaMiles** [comment]
Final Date Generated

![image](https://user-images.githubusercontent.com/31770504/63524601-4c0eff80-c4ca-11e9-9f19-88b52ecd1e5f.png)
