### ISSUE TITLE
Gaming Intake Details Page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1413]
All the gaming intake details pages need to have a beginning and end date - for when the permit is valid for 
![image](https://user-images.githubusercontent.com/47611580/62485275-499e6d00-b78a-11e9-9483-32dd362a5ef3.png)
use same of old permit # 8459

**Comment by ABonomo21** [comment]
disregard - should be entered in start end date on job description 

![image](https://user-images.githubusercontent.com/47611580/62485375-84a0a080-b78a-11e9-90d7-d6b1a988c440.png)

**Comment by ABonomo21** [comment]
Dan to look at this- we need to be able to capture the beg/start or end date somewhere ~ applicant should provide this data staff will confirm /correct 
annual permits are valid from the date of issuance to the end of the current calendar year- 
single occurrence is based on the date of the event beg and end will be the same 
off premise can have 3 month 
carnival for on premis is 10 days-

**Comment by megisys** [comment]
Fixed

**Comment by megisys** [comment]
Expiry date to be set on another ticket #1412
