### ISSUE TITLE
planning-yard mod-denied result keeps project in under review..should close

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1414]
for this ap type, denied should move project to closed/finalized

![image](https://user-images.githubusercontent.com/4129185/62489570-0eee0200-b795-11e9-97fb-00ea718cee14.png)

MW

**Comment by dhenry-KCI** [comment]
not fixed, but we need to have a broader discussion of the denied function.

![image](https://user-images.githubusercontent.com/4129185/62791470-3990d100-ba9b-11e9-8ffb-6298c4973111.png)


MW

**Comment by megisys** [comment]
No it should hold it here. Until a Log is added of DENIED. Need to Test DENIED LOG Functionality - Dan

**Comment by dhenry-KCI** [comment]
There isnt a "denied" option under logs.

With Yard Mods, we either approve them or we do not approve them. There is not an option at present that works when not approving.  Using the denied status doesnt move the project out of "under review", which means there are no notifications being sent to the applicant stating they are denied and R4C still shows the project is under review.

MW

**Comment by megisys** [comment]
Log Entry to be added and Tested - 1 hour

**Comment by dhenry-KCI** [comment]
denied log works well   MW
