### ISSUE TITLE
Use Permit - Awaiting Fee Payment Notification - Standard Format

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1417]
Did not get an Awaiting Fee Payment notification for the Home Occupation permit.

**Comment by megisys** [comment]
There are no fees

**Comment by megisys** [comment]
Are you sure.. I adjusted as well

**Comment by ABonomo21** [comment]
Notification needs to be cleaned up - font needs to be consistent - see notes below 
![image](https://user-images.githubusercontent.com/47611580/62639185-ff91c480-b90c-11e9-8ea5-47a1ca38fe25.png)

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/62640726-387f6880-b910-11e9-979b-b020f1a30624.png)

Should follow the standard format indicated above.

**Comment by mmbanong** [comment]
Requested change has been made
![image](https://user-images.githubusercontent.com/47392173/63104988-ecef3f00-bf4d-11e9-9868-55e680074d06.png)

**Comment by JuanitaMiles** [comment]
@dhenry-KCI Currently not corrected in TEST env. Is this something that was corrected in DEV and needs to be pushed to TEST?

![image](https://user-images.githubusercontent.com/31770504/63268470-38616000-c262-11e9-8ed1-b149f9284ffd.png)

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
