### ISSUE TITLE
Use home occupancy- hours of operation 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1418]
am/ pm time is not showing up on the home occ intake details page - it is an insertable field on r4c 

![image](https://user-images.githubusercontent.com/47611580/62491099-08fa2000-b799-11e9-96d3-f9cb634a88dd.png)

also time should not be military 
![image](https://user-images.githubusercontent.com/47611580/62491251-537b9c80-b799-11e9-8116-4812b7edf2fb.png)

![image](https://user-images.githubusercontent.com/47611580/62491226-3e9f0900-b799-11e9-8af7-3eb376aea960.png)

**Comment by megisys** [comment]
I can not fix this
