### ISSUE TITLE
Case - Hearing - Hearing Attendees Email Notification

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#142]
Building Case Testing 1/23 (Ashlye Bonomo)
During the hearing prep milestone - add a hearing - does the request attendees section notify the persons via email that they have been requested for trial?

Case Testing 1/23 (Tiffany Martin)
SWM/FRO Case: When adding a hearing - does the attendees get notified by email if they are added in that space

![image](https://user-images.githubusercontent.com/31770504/53589049-5fb15d00-3b5c-11e9-9b3f-f935d1e3c693.png)

**Comment by JuanitaMiles** [comment]
Christian requested ticket to Follow Up with Dan on functionality?

**Comment by megisys** [comment]
This is a future enhancement as this is not functionality we currently have.. The attendees is a record of who actually attended. What do yoy do now in Hansen 7. @JuanitaMiles  @dhenry-KCI

**Comment by dhenry-KCI** [comment]
Discussed on 3/13 - hearing attendees defines who attended the hearing not who will attend.
