### ISSUE TITLE
Use Permits - Home Occupation - Applicant Actions Comments

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1420]
The review comments on the Completeness Check did not show on the Applicant Actions section in R4C.

![image](https://user-images.githubusercontent.com/31770504/62540658-1ad5d480-b826-11e9-87e8-283666807370.png)

**Comment by megisys** [comment]
test with a whole new Home Occupancy

**Comment by JuanitaMiles** [comment]
Completeness Check review comments come over properly.
