### ISSUE TITLE
R4C - Use Permits - Home Occupation - Intake Details Hours of Operation (Excel #67)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1421]
Cannot update hours of operation grid on R4C at Completeness Check

![image](https://user-images.githubusercontent.com/31770504/62541116-1cec6300-b827-11e9-8773-fa5e31f4a4cf.png)

**Comment by calequin** [comment]
fixed. changed key column and regenerated detail page

**Comment by JuanitaMiles** [comment]
Does not appear to be working correctly. At the time of submitting my application, I input 5:00 PM as my End HR. I am now at the Awaiting More Information milestone (which is for the Completeness Check resubmittal), and am trying to update the 5:00 PM End Hr to 5:30 PM but the time is always setting itself back to 12:00 AM once I click Save Row.

![image](https://user-images.githubusercontent.com/31770504/63285061-ec72e300-c282-11e9-8754-2962493e5e61.png)

![image](https://user-images.githubusercontent.com/31770504/63285104-06acc100-c283-11e9-9a9c-1e4b4c5399b8.png)

![image](https://user-images.githubusercontent.com/31770504/63285199-3d82d700-c283-11e9-85ec-e4277d96081c.png)

![image](https://user-images.githubusercontent.com/31770504/63285348-7f138200-c283-11e9-9a2f-f08377eaaf84.png)

When I Save the detail page (with the 12:00AM End HR value), R4C throws the following error.

![image](https://user-images.githubusercontent.com/31770504/63285467-cf8adf80-c283-11e9-98dd-15fd6fd8f1eb.png)

**Comment by calequin** [comment]
fixed. had to create a new column for the key column to allow new updates on a row.

**Comment by JuanitaMiles** [comment]
The Hours of Operation details I input in R4C do not show up on my R4C detail page and they do not come through to the back office either. I input Mon - Fri 7:00 to 5:00

![image](https://user-images.githubusercontent.com/31770504/65439416-1d4fb600-ddf5-11e9-9630-61301658b6a2.png)

![image](https://user-images.githubusercontent.com/31770504/65439371-0c06a980-ddf5-11e9-9055-0a36a1c587e9.png)

**Comment by calequin** [comment]
fixed. key column was missing a bind in detail page.

**Comment by ABonomo21** [comment]
was able to update on r4c without error H244674
