### ISSUE TITLE
Cross Module Dashboard Reports

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1423]
County needs configured dashboard  which pull information across modules for permit techs

**Comment by megisys** [comment]
[CustomDashboard.txt](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3570789/CustomDashboard.txt)

**Comment by megisys** [comment]
![CustomDashboards](https://user-images.githubusercontent.com/47392306/64196499-fe8f7c80-ce51-11e9-8d31-4ae6398065c3.png)

**Comment by ABonomo21** [comment]
@dhenry-KCI we need this before training !

**Comment by megisys** [comment]
This is 2 days Effort

**Comment by megisys** [comment]
Dustin PLease Let me know if we are waiting until after go live for this one

**Comment by ABonomo21** [comment]
Ashlye B wants to wait until after go live
will need to follow up with Ashley R

**Comment by dhenry-KCI** [comment]
Closing until post-go live
