### ISSUE TITLE
Use Permits - Home Occupation - R4C Inspection Request

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1426]
Need to update language for the inspection request error.

"Request cannot be completed. Request must be for a future date."

![image](https://user-images.githubusercontent.com/31770504/62543339-c0d80d80-b82b-11e9-9dd2-a90bdf72914a.png)

**Comment by calequin** [comment]
fixed verbiage on translation override and on formulas

**Comment by JuanitaMiles** [comment]
Language Updated
![image](https://user-images.githubusercontent.com/31770504/63293795-e424a300-c296-11e9-99a7-af66c44f8255.png)
