### ISSUE TITLE
New Requirement - ALL Inspections Notification

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1428]
need to create a batch report that generates at 8 am every morning to notify the applicants their inspections have been schedule,, who is assigned etc.

**Comment by ABonomo21** [comment]
or a button not a time

**Comment by ABonomo21** [comment]
bob will push the button

**Comment by megisys** [comment]
This is a DAY Effort.

**Comment by megisys** [comment]
This is a big effort as explained.. PLease log into Dev and provide feedback

**Comment by ABonomo21** [comment]
duplicated tickets closing and will review format with Ashlye and Juanita as a group for all modules
