### ISSUE TITLE
Code Violition for Inspection Code violations for DOLS - USE

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1430]
DOLS inspection does not have any violation codes of descriptions available to select from 

particularly in use permits

**Comment by ABonomo21** [comment]
migrate all code violations - back office issue

**Comment by megisys** [comment]
Commplete

**Comment by JuanitaMiles** [comment]
There are no Code Violation options to choose from. This is the DOLS inspection for a Home Occupation Permit. 

![image](https://user-images.githubusercontent.com/31770504/63546794-9ad38e00-c4f8-11e9-87b2-35b1dde051eb.png)

**Comment by ABonomo21** [comment]
checked home occ permit h244619 and the code violations all appear. will monitor during training 
![image](https://user-images.githubusercontent.com/47611580/65444813-db2b7200-ddfe-11e9-8b87-8a3e4f8f5394.png)

![image](https://user-images.githubusercontent.com/47611580/65444800-d36bcd80-ddfe-11e9-9b44-e74f86c5cda9.png)
