### ISSUE TITLE
Mobile- Open Attachment 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1431]
when opening an attachment in mobile- the session is lost - there is no way to go back automatically to the inspection it just closes the whole application.

**Comment by megisys** [comment]
Also are Attachments synced on first load

**Comment by calequin** [comment]
couldnt replicate issue. I was able to succesfully open up attachment on application # 246113.

**Comment by ABonomo21** [comment]
was able to open an attachment and get back into the Mobile - will monitor
