### ISSUE TITLE
Mobile- Log Comments (Xtreme Ticket # 13805549)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1432]
Log comments in mobile are producing all the back office HTML Tags that does not make sense to the inspectors.... 

![image](https://user-images.githubusercontent.com/47611580/62545299-735d9f80-b82f-11e9-9a82-0fc5511d3803.png)

should look like back office- 
![image](https://user-images.githubusercontent.com/47611580/62545322-82dce880-b82f-11e9-811e-6ed37984d18e.png)

**Comment by calequin** [comment]
Need to pull Rick Monteiro in on this one. Basically the logs is trying to show the notification email that was sent to the customer but it is reading it as html code

**Comment by megisys** [comment]
Christian I saw email chain on this.. We need to close this out

**Comment by calequin** [comment]
@dhenry-KCI is setting up a meeting with Rick Monteiro for a fix to this issue

**Comment by dhenry-KCI** [comment]
@calequin - we have a meeting with Rick on Friday - need to make sure he is aware. Can you please pass to him ahead of Friday's meeting.

**Comment by megisys** [comment]
We changed tack on this.. Notification Render not to be included in the Log Anymore
