### ISSUE TITLE
Use Permits - Home Occupation - Inspection Results on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1434]
Should be able to view the inspection comments and any code violations (when there are vioaltions) in my R4C page.

![image](https://user-images.githubusercontent.com/31770504/62546878-4a8ad980-b832-11e9-948b-d9f202567b18.png)

**Comment by calequin** [comment]
I verified and it is working correctly. The comments appear at the time with the code violations as another box. tagging this as will monitor

![image](https://user-images.githubusercontent.com/47603568/62576129-db2cde00-b861-11e9-90d7-8c108a1e4eec.png)

![image](https://user-images.githubusercontent.com/47603568/62576159-eb44bd80-b861-11e9-997e-4138659fc396.png)

**Comment by JuanitaMiles** [comment]
Comments and Code violations are visible when added to the inspection (Tested using the back office).
