### ISSUE TITLE
Use Permits - Home Occupation - Schedule Inspection button on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1435]
The user should have the ability to click the schedule inspection button, like we would for the initial inspection, from the dashboard.

![image](https://user-images.githubusercontent.com/31770504/62547105-ace3da00-b832-11e9-87ee-d886db02f60a.png)

**Comment by calequin** [comment]
spoke to @JuanitaMiles about this and it looks like it started working correctly during lunch time. Will monitor this

**Comment by JuanitaMiles** [comment]
Request Inspection appears to working properly. It shows on both the Needs Action and All views. Closing.

![image](https://user-images.githubusercontent.com/31770504/63291108-eab01c00-c290-11e9-83bc-738f1ca72fb9.png)

![image](https://user-images.githubusercontent.com/31770504/63291085-dd932d00-c290-11e9-84f8-44505772eae5.png)
