### ISSUE TITLE
Mobile- Inspection scheduling- Fees Due

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1436]
Use permit H244594 was scheduled in  mobile with a re-inspection fee due- 

if a re-inspection is due, we need to collect the fee prior to scheduling any future inspections in back office r4c or mobile

**Comment by megisys** [comment]
See Building

**Comment by megisys** [comment]
Need to make sure you cant request inspection date if fees are outstanding

**Comment by calequin** [comment]
fixed in dev. added USE_ManageInspections_BUF formula that sends an error message if trying to schedule but total unpaid fees is >0

**Comment by ABonomo21** [comment]
tested 246807 and gave use the error
fixed 9.5.19 ab
