### ISSUE TITLE
IPS- Re-inspection Fee notifiacation

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1438]
re-inspection fee notification needs to be send "awaiting re-inspection fee" even under the inspections milestone

**Comment by mmbanong** [comment]
Needs further discussion on inspection fee generation

**Comment by megisys** [comment]
Need formula on Adding Reinspection Fee to Send Notification - Dan Grendon - 1
 Hours

**Comment by megisys** [comment]
Notification to advise that Fee must be paid before attempting to schedule reinsoection

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
