### ISSUE TITLE
Case - Building Case - Inspection Type Popup Options

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#144]
Missing OLS inspection and Follow Up inspection.

![image009](https://user-images.githubusercontent.com/31770504/53591912-24665c80-3b63-11e9-9cf0-99cff4b3f918.png)

(Reported by Ashlye Bonomo 2/11)

**Comment by calequin** [comment]
OLS-CASE and OLS-FOLLP have been added.

**Comment by ABonomo21** [comment]
Confirmed they are available for entry
