### ISSUE TITLE
Land Use - Fees Wrong 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1440]
![image](https://user-images.githubusercontent.com/47611580/62549095-e538e780-b835-11e9-8e44-939e5eb6f525.png)

building fee and application fee are wrong 

![image](https://user-images.githubusercontent.com/47611580/62549128-f4b83080-b835-11e9-8d9c-5ae8bd7fe966.png)

**Comment by mmbanong** [comment]
Updated the Building Fees and Application Fees
![BUILDING FEES](https://user-images.githubusercontent.com/47392173/62551006-34344c00-b839-11e9-80bf-756212b25bd1.PNG)
![Resubmit Revision](https://user-images.githubusercontent.com/47392173/62551013-3696a600-b839-11e9-9b6e-5f32f5e4e363.PNG)
