### ISSUE TITLE
Use Permits - All Inspections - R4C Inspection Request

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1441]
Each inspection record in R4C should have it's own Schedule Inspection button.

![image](https://user-images.githubusercontent.com/31770504/62549558-b53e1400-b836-11e9-8453-faa4b38db14b.png)

**Comment by calequin** [comment]
I added myself as the applicant for this permit and I see the inspection request listed. @JuanitaMiles did you see this in your dashboard? or was this viewed through a lookup on r4c. If so then it would not list inspection request unless you are the applicant.

![image](https://user-images.githubusercontent.com/47603568/62574839-0104b380-b85f-11e9-911a-e2c02eccef90.png)

**Comment by JuanitaMiles** [comment]
Appears correctly in my application now.

![image](https://user-images.githubusercontent.com/31770504/63542947-a2426980-c4ef-11e9-8d12-8786748ee7e7.png)
