### ISSUE TITLE
Use Permits - Land Use - County Comments on Applicant Actions (Excel # 66)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1443]
Need to see the County resubmit comments on the applicant actions page on R4C.

![image](https://user-images.githubusercontent.com/31770504/62550835-eb7c9300-b838-11e9-8eb2-c6d59f757b6c.png)

**Comment by calequin** [comment]
fixed. and working. tested with l244606

**Comment by JuanitaMiles** [comment]
Review comments are visible on the Applicant Actions sections, however the text of the comments appears duplicated...This occurs on the Completeness Check resubmit (Awaiting More Information) only. The Under Review comments come over correctly.

![image](https://user-images.githubusercontent.com/31770504/63545970-a4f48d00-c4f6-11e9-90bd-8f86fbbd2aeb.png)

![image](https://user-images.githubusercontent.com/31770504/63546157-1a605d80-c4f7-11e9-8b43-40778fc75f5d.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/64371604-f91b6900-cfee-11e9-9089-8380668b127f.png)
![image](https://user-images.githubusercontent.com/47611580/64371678-2bc56180-cfef-11e9-9a5d-81241c4372f8.png)
