### ISSUE TITLE
Use Permits - Land Use - Instructions

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1444]
Can we remove the arrow icons within the instructions.

![image](https://user-images.githubusercontent.com/31770504/62550923-11a23300-b839-11e9-8ea8-95df6c8a6d05.png)

**Comment by calequin** [comment]
fixed. had to remove bold lettering.
![image](https://user-images.githubusercontent.com/47603568/62562147-351faa80-b846-11e9-927e-f8836774a243.png)

**Comment by JuanitaMiles** [comment]
fixed
