### ISSUE TITLE
Land Use- Resubmit Review 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1446]
Zoning was the only agency marked for a resubmit review and when the re-submission came back in zoning and hd populated --- only the agency requesting the resubmit should populate a second review and then staff will manually add any additional agencies 
![image](https://user-images.githubusercontent.com/47611580/62551608-54183f80-b83a-11e9-9721-48f1e5c46e0f.png)

**Comment by JuanitaMiles** [comment]
Replicated the details of the permit above and retested. This time the EH review did not populate at all. Confirmed with Ashlye...if Food Service and Portable Sanitary is selected on the detail page, then both the EH AND HEALTH-FD reviews should generate on the application.

![image](https://user-images.githubusercontent.com/31770504/63545469-7c1fc800-c4f5-11e9-8374-280e49a5af5b.png)

![image](https://user-images.githubusercontent.com/31770504/63545508-98bc0000-c4f5-11e9-9179-78e3d071701e.png)

**Comment by calequin** [comment]
fixed formula.

**Comment by ABonomo21** [comment]
both reviews generated  9.5.19 ab 
![image](https://user-images.githubusercontent.com/47611580/64370426-6e396f00-cfec-11e9-9e9a-8aa7a7941a87.png)
