### ISSUE TITLE
R4C Use Permits - Land Use - Inspection Results (Excel #64)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1447]
Bob failed the first Bldg Final inspection in mobile, its not showing the result of the first inspection. It is only asking for me to request the second cycle of the inspection.

![image](https://user-images.githubusercontent.com/31770504/62552379-88d8c680-b83b-11e9-8679-5e8ac1bbb307.png)

**Comment by calequin** [comment]
The inspection results are located in the details of the inspection. You have to click on the inspection id number and all of the details will be listed.

**Comment by megisys** [comment]
This is an issue we need to raise with Dev

**Comment by dhenry-KCI** [comment]
@calequin - i know this is on our master excel - re-assigning so you are aware of the github ticket.

**Comment by dhenry-KCI** [comment]
@calequin - what's the status of this issue? I don't see a release version on it.
