### ISSUE TITLE
Land Use inspection scheduling 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1448]
scheduling an inspection in the back office it is telling me i cannot schedule in the past but i am scheduling for 8.7.19- a date in the future and it is not noon

![image](https://user-images.githubusercontent.com/47611580/62552433-9f7f1d80-b83b-11e9-93d3-51c4dc541ced.png)

**Comment by ABonomo21** [comment]
tested to schedule 8.8. 19 and was unable to schedule that as well

**Comment by calequin** [comment]
I just tested and was able to schedule. was the call date cleared out as well? tagging as question since I could not replicate
