### ISSUE TITLE
Case - Building Case - Failed Compliance Check on Guilty Verdict

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#145]
Failed compliance check after a guilty verdict on hearing prep - should have taken us back to citation milestones and took us back to hearing preparation.

![image008](https://user-images.githubusercontent.com/31770504/53592175-b8d0bf00-3b63-11e9-8f2b-cad5f06e1fd1.png)

(Reported by Ashlye Bonomo 2/11)

**Comment by calequin** [comment]
fixed for all case types

**Comment by ABonomo21** [comment]
Related to Item #272 - noted for Ashley to double check during retest

**Comment by ABonomo21** [comment]
Worked during retest under case # 237140
