### ISSUE TITLE
PLANNING- PREPLAT - comments for completeness check didn't transfer to R4C

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1450]
comments for completeness check didn't transfer to R4C under applicant actions as it does on other applications. We would like the completeness check review comments to populate in Applicant Actions. AReed
PP244929
![image](https://user-images.githubusercontent.com/4129185/62555873-b4f74600-b841-11e9-8360-e506591d93e9.png)

Working on 245013
![image](https://user-images.githubusercontent.com/4129185/62555528-1c60c600-b841-11e9-883c-caadbb64a556.png)

**Comment by megisys** [comment]
Test fully new ones

**Comment by dhenry-KCI** [comment]
fixed

MW/AR
