### ISSUE TITLE
Land Use - Expiration Date 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1451]
can the expiration date for the land use permits match the end date of the event on the details tab 

![image](https://user-images.githubusercontent.com/47611580/62557528-31d7ef00-b845-11e9-8ebd-8670396888ea.png)

**Comment by calequin** [comment]
fixed. added expiration date to be the same as end date if end date is filled out

**Comment by ABonomo21** [comment]
good job christian
