### ISSUE TITLE
Building Permit - Zoning Cert - Applicant Actions Comments

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1458]
Need to be able to see Ashlye's Review Resubmit comments within the Applicant Actions section on R4C.

![image](https://user-images.githubusercontent.com/31770504/62562000-4ec4f000-b84e-11e9-9c6b-3c604929ed40.png)

**Comment by megisys** [comment]
Update detail Page and added COUNTYCOMMENTS - Need formula to update the Detail Page from Completeness Check

**Comment by megisys** [comment]
Added

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/64371285-36332b80-cfee-11e9-9626-515c68f11f0f.png)
