### ISSUE TITLE
All Building Permits- Status Check 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1459]
when resubmitting on a completeness check - I was stuck in completeness check for the priority code - any status check should not stop progression back to the applicant only should stop on the approved completenes check review 

![image](https://user-images.githubusercontent.com/47611580/62562100-82077f00-b84e-11e9-9d7f-e5231f7440f8.png)

**Comment by megisys** [comment]
Update Sop for COmpleteness Check to ensure that the Priority is set first and then result the completeness check

**Comment by dhenry-KCI** [comment]
Duplicate and part of larger ticket #1522 . Closing this ticket
