### ISSUE TITLE
Building - NONRES - Life Safety Final Inspection missing

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#146]
Non-Residential Building Permit was able to be closed out without a Life Safety Final Inspection Ever Generating on the Building Permit.

AP: 238426 (or any new)
Logged By: M. Coffman

![image](https://user-images.githubusercontent.com/4104464/53595613-b8d4bd00-3b6b-11e9-81ca-f569f80d55e2.png)

**Comment by megisys** [comment]
This has been addressed.. Thanks

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/53742355-73173d80-3e66-11e9-8bc4-498da2ddd672.png)

Confirmed fixed on Non Res Addition-AW-going to test a couple more.

**Comment by dhenry-KCI** [comment]
Confirmed Fixed on Non Res New Tenant No Change-AW
![image](https://user-images.githubusercontent.com/4129185/53744203-83311c00-3e6a-11e9-8249-bbe49cff966c.png)

**Comment by dhenry-KCI** [comment]
Confirmed Fixed for Non Res New Tenant Change of Use.-AW
![image](https://user-images.githubusercontent.com/4129185/53745465-0a7f8f00-3e6d-11e9-935c-770793700b80.png)

**Comment by dhenry-KCI** [comment]
Confirmed working-AW
