### ISSUE TITLE
Zoning Cert- Resubmission Completeness check 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1460]
asked for a resubmit on zoning cert- applicant was able to change detail page in r4c to add dirveway open section in r4c but that did not convert over to ips 

![image](https://user-images.githubusercontent.com/47611580/62562280-c98e0b00-b84e-11e9-9f89-35d846912c3c.png)

![image](https://user-images.githubusercontent.com/47611580/62562308-dd397180-b84e-11e9-86bd-c9267673ca7f.png)

**Comment by ABonomo21** [comment]
tried to add open section in the back office-
this is my option 
![image](https://user-images.githubusercontent.com/47611580/62562391-0e19a680-b84f-11e9-9388-8223d2cdec76.png)

**Comment by dhenry-KCI** [comment]
this is the same for grading permits. permit #246218 we tried to submit and update the disturbed area and it did not go over to IPS from r4c

**Comment by ABonomo21** [comment]
zoning cert fixed created new ticket for emily and tiffany to test #1786
