### ISSUE TITLE
R4C - Plan Reviews - break out by review cycle or date (Excel #63)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1462]
Having multiple review cycles listed together makes it confusing for the applicant to follow the current reviews. Most recent reviews should be at the top. Need to differentiate review cycles.
areed
![image](https://user-images.githubusercontent.com/4129185/62563969-04de0900-b852-11e9-98a4-3a8fff92f886.png)

**Comment by megisys** [comment]
Spoke with Product Manager - Hoping for a short term fix of adding Cycle Number. And long term fix of grouping by cycle

Dan

**Comment by dhenry-KCI** [comment]
default to delivery date as newest review date. Would need to make sure due date stays configrued with future release.

**Comment by megisys** [comment]
This will not be ready for GoLive
