### ISSUE TITLE
All building permit -Re-submission 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1466]
need milestone for admin revision review to re-assign reviews add fees etc

**Comment by ABonomo21** [comment]
Zoning Cert and Demo have been tested with the Revision Assignment Review and it works well- need to add to all other a/p's 
tested sign and it did not populate .

**Comment by megisys** [comment]
This is Addressed

**Comment by ABonomo21** [comment]
fixed 9.5.19 ab
