### ISSUE TITLE
R4C - Missing modules (Xtreme #13805526 Excel #62)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1467]
When the user logs into R4C the system will intermittently only display a subset of the available 5 modules. Screenshot below displaying 4/5.
![Missing Module](https://user-images.githubusercontent.com/4129185/62571058-6a37f700-b85e-11e9-8756-193d80c8d851.PNG)

**Comment by JuanitaMiles** [comment]
Here's an instance when I clicked on Submit an Application/Request and the system only loaded one module.

![image](https://user-images.githubusercontent.com/31770504/62783560-af407100-ba8a-11e9-9898-bcb79addf7bb.png)

**Comment by JuanitaMiles** [comment]
Hit refresh to load all five modules but now the County Requests didn't load.

![image](https://user-images.githubusercontent.com/31770504/62783971-6ccb6400-ba8b-11e9-8149-2bf0dabc35bd.png)

**Comment by calequin** [comment]
Infor JIRA Ticket created HPS-106084

**Comment by calequin** [comment]
have been viewed and replicated with development. Valid defect and working out tickets. @christian verify type of logging being done in rest services.

**Comment by calequin** [comment]
fixed on the latest release of rhythm.

**Comment by ABonomo21** [comment]
have not had this happen for a while - will close and monitor
