### ISSUE TITLE
Land Use Official Issuance Report 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1468]
Department of Commerce is not valid any longer it should be occupancy type 

![image](https://user-images.githubusercontent.com/47611580/62569347-7753e680-b85c-11e9-92c7-702fc836c23a.png)

![image](https://user-images.githubusercontent.com/47611580/62569658-db76aa80-b85c-11e9-93b0-3973a534bc7f.png)

Use of Land should be pull from land use on the details page 
![image](https://user-images.githubusercontent.com/47611580/62569974-3c05e780-b85d-11e9-8685-ba8ef89a2263.png)

![image](https://user-images.githubusercontent.com/47611580/62570079-4aec9a00-b85d-11e9-81da-787e570f5ee1.png)

days and and hours can be removed - only the beg and end date should be captures with the start and end time 

![image](https://user-images.githubusercontent.com/47611580/62571375-33161580-b85f-11e9-8d4b-4ba5a9c2129c.png)

![image](https://user-images.githubusercontent.com/47611580/62571407-4628e580-b85f-11e9-91e4-2b9541e2865a.png)

the following should be removed
![image](https://user-images.githubusercontent.com/47611580/62571514-8be5ae00-b85f-11e9-9b08-a5558de2adff.png)

the following should be captured
![image](https://user-images.githubusercontent.com/47611580/62571554-a3249b80-b85f-11e9-9132-f33ade18f9d8.png)

if possible the food service /alcohol/ private /public should be answered based on the check box being marked 

review comments need to be cleaned up- should only generate the final review approved comment for each agency 
![image](https://user-images.githubusercontent.com/47611580/62571650-dd8e3880-b85f-11e9-89fa-fea1799b9a83.png)

should not generate resubmissions

**Comment by dhenry-KCI** [comment]
HI @TaraF - some details to cleanup on this report.

**Comment by dhenry-KCI** [comment]
@gerrykelly - two fixes still outstanding. See highlighted.

![image](https://user-images.githubusercontent.com/4129185/64370741-12231a80-cfed-11e9-8fea-b414f468b668.png)

**Comment by dhenry-KCI** [comment]
@TaraF - this appears to be for the Land Use Report specifically. #1439 is for a Home Occupancy Permit.

**Comment by TaraF** [comment]
@dhenry-KCI , for 'no agency named' - we are using this, when there is no agency named in IPS.  For this example, see AP# L244599, the Review No.  585023.  
![image](https://user-images.githubusercontent.com/4104464/65536550-a4725c00-ded1-11e9-9b53-5ab56a74e989.png)


We need instruction on how the County would like to handle cases like that if 'no agency named' is not preferred.

**Comment by dhenry-KCI** [comment]
@TaraF - reviews type = Completeness check should not be included on the report. This should eliminate your NUll agency issue. If the agency is NUll, use the review type to populate the department.

**Comment by TaraF** [comment]
Fixed and ready for re-test.

**Comment by TaraF** [comment]
![image](https://user-images.githubusercontent.com/4104464/65973715-cb80de80-e439-11e9-9a45-638cca595219.png)

**Comment by ABonomo21** [comment]
fixed will check on during notification and report testing
