### ISSUE TITLE
Building - NONRES, Foundation Only - Fees

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#147]
- Building Fee should be a minimum fee of $48.00
- Life Safety fee is not applicable 
- Site Compliance Fee should not generate on the a foundation only permit, it would be applied to the core structure when that application is submitted

AP: 237369
Logged By: M. Coffman

![image](https://user-images.githubusercontent.com/4104464/53597298-cd1ab900-3b6f-11e9-935b-1e56d4540425.png)

**Comment by megisys** [comment]
This Has been addressed as outlined.. Ready for Retest

**Comment by dhenry-KCI** [comment]
Testing Failed-The Life Safety Fee and the Site Compliance Fee did not generate(which is correct) but the Building Fee of $48 did not generate, which it should.-aw

![image](https://user-images.githubusercontent.com/4129185/53746896-20db1a00-3e70-11e9-82b9-3f646226d466.png)

**Comment by megisys** [comment]
Can I have an understanding when the Building Permit Minimum Fee should Add FOR All NonRes Applications.. I need to build the rules..

**Comment by imazlout** [comment]
Please retest.
I fixed this as part of another issue #310. I also removed criteria AddPlumbing = false and now fee does get added.

**Comment by ABonomo21** [comment]
Permit# 238854-Foundation/Slab Only-Fixed
![image](https://user-images.githubusercontent.com/47611580/54434671-26085680-4705-11e9-968f-5b637d4a4db0.png)

Permit# 238863- Foundation Only (within a town)-Not Corrected- Two Building fees generated
![image](https://user-images.githubusercontent.com/47611580/54436337-b5633900-4708-11e9-8a39-f9b896e20d6a.png)

**Comment by imazlout** [comment]
Please retest. only minimum fee shows up for foundation only now.

**Comment by ABonomo21** [comment]
confirmed fixed -AW
foundation only-in a town-fixed 
![image](https://user-images.githubusercontent.com/47611580/54618376-50298380-4a39-11e9-91ff-452cb36030be.png)
