### ISSUE TITLE
Building Permits - Resubmit Required Notification Standard Language

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1471]
Please update the signature of this Building Permit Resubmit Required notification to read:

_(this language should be standard across the entire Building Module)_

Your Permitting and Licensing team at Frederick County.

![image](https://user-images.githubusercontent.com/31770504/62633238-d0c22100-b901-11e9-9806-b7f2db834f36.png)

**Comment by mmbanong** [comment]
Requested change has been made

![image](https://user-images.githubusercontent.com/47392173/63104346-d399c300-bf4c-11e9-8767-31be09735089.png)

**Comment by ABonomo21** [comment]
signature is correct - other details need to be corrected 
 will do a final correspondence and notification check 9.5.19 ab
