### ISSUE TITLE
Building Permits - Building Application Issued Notification Standard Language

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1472]
Please update the signature on the Building Application Issued notification to read:

_(this language should be standard across the entire Building Module)_

Your Permitting and Licensing team at Frederick County.

![image](https://user-images.githubusercontent.com/31770504/62633510-43330100-b902-11e9-8693-281d9062cf18.png)

**Comment by mmbanong** [comment]
Requested change has been made
![image](https://user-images.githubusercontent.com/47392173/63104674-689cbc00-bf4d-11e9-9e34-91aafb40d69b.png)

**Comment by ABonomo21** [comment]
signature is correct other notification details need to be corrected
will do a final correspondence and notification check 9.5.19 ab
