### ISSUE TITLE
Use Permits - More Information Required Notification Standard Language

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1473]
Please update the signature on the More Information Required notification to read:

_(duplicate to issue #1475 , the language is standard across the Use module)_

Your Permitting and Licensing team at Frederick County.

![image](https://user-images.githubusercontent.com/31770504/62633801-c2283980-b902-11e9-8fe3-3f4c7bffd273.png)

**Comment by dhenry-KCI** [comment]
duplicate - closing
