### ISSUE TITLE
Use Permits - More Information Required Notification Standard Language

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1475]
Please update the signature of the More Information Required notification to read:

Your Permitting and Licensing team at Frederick County.

_(this update should be applied to all Use Permit More Information Required Notifications) duplicate to issue #1473 _

![image](https://user-images.githubusercontent.com/31770504/62634539-12ec6200-b904-11e9-9126-513b4747105b.png)

**Comment by JuanitaMiles** [comment]
The signature is not updated per the request above - "Your Permitting and Licensing team at Frederick County."

![image](https://user-images.githubusercontent.com/31770504/63267812-d522fe00-c260-11e9-84db-669105e64195.png)

**Comment by ABonomo21** [comment]
generally correct - fixed by dan will do a final correspondence and notification check 9.5.19 ab
