### ISSUE TITLE
Use Permits - Gaming - Use Permit Issued Notification Language

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1476]
@megisys Dan - Please chime in if there is an issue with having the language this specific for this notification. I remember you saying some of these notifications are module-wide rather than AP specific.

Update the language of the Gaming Use Permit Issued notification to read:

Your Gaming Permit # (blah) has been issued.

Please log into our portal https://frederickcountymd.gov/ and print a copy of your permit for your records. 

Reports can be emailed to Permits@FrederickCountymd.gov or mailed to 30 N. Market Street Frederick, MD 21701.

Gaming Reports can be found at https://frederickcountymd.gov/1650/Gaming-Permits

Your Permitting and Licensing team at Frederick County. 

![image](https://user-images.githubusercontent.com/31770504/62636037-d4a47200-b906-11e9-8b43-2e6e9cf57dd6.png)

**Comment by JuanitaMiles** [comment]
Not fixed in TEST. Even if the notification is not customized to the Gaming AP with some of the language noted above, the signature is still incorrect, along with punctuation, etc.

 
![image](https://user-images.githubusercontent.com/31770504/63270958-1f0ee280-c267-11e9-8129-01f384a6d26d.png)

**Comment by mmbanong** [comment]
Notification text is fixed in ipsdev
![image](https://user-images.githubusercontent.com/47392173/63367642-50acaa00-c34a-11e9-8ea1-95151a086d27.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - what's the question?

**Comment by mmbanong** [comment]
USE_PermitIssue is for other Use Permits and USE_IssueLicense for Gaming Only
Pending approval from Dan

![useCapture](https://user-images.githubusercontent.com/47392173/64438086-73062d80-d095-11e9-9e34-4f975129376b.PNG)

![image](https://user-images.githubusercontent.com/47392173/64438279-d8f2b500-d095-11e9-8e87-2d9822a695a0.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - yes please do make the change you have outlined above.

**Comment by mmbanong** [comment]
The notifications have been created pending registration guidance from. I have gotten any response from him yet. There parameters that the formulas look for in the notification process that need to be set up

**Comment by mmbanong** [comment]
Dan, I have added U_GISSUE and U_ISSUE as notification types in the configuration manager. I am using the notification types in the formula but the notifications are not sent out. Any suggestions
![image](https://user-images.githubusercontent.com/47392173/66332911-d2a96000-e903-11e9-8703-edc27367daaa.png)



![image](https://user-images.githubusercontent.com/47392173/66332375-932e4400-e902-11e9-8e75-e791423c727c.png)

![image](https://user-images.githubusercontent.com/47392173/66332418-ae994f00-e902-11e9-9911-1f3920cf33f2.png)
