### ISSUE TITLE
BOA-fee explosion!  

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1478]
this wasnt like this yesterday.  every work type fee under BOA is populating on an ADU application

MW

![image](https://user-images.githubusercontent.com/4129185/62640309-4f718b00-b90f-11e9-95fc-187cf8c23017.png)

**Comment by megisys** [comment]
Have Xtreme Ticket in for this

**Comment by dhenry-KCI** [comment]
fixed MW

![image](https://user-images.githubusercontent.com/4129185/62714278-42ff3800-b9cc-11e9-897e-7281b64693c9.png)
