### ISSUE TITLE
Correspondence Batch Manager - Not appearing to be running automatically

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1479]
Batch Manager not running automatically for Correspondence Management.

**Comment by megisys** [comment]
Set to 5 minutes

**Comment by JuanitaMiles** [comment]
"Next Scheduled Time" is currently showing 4 days in the past, which tells me it's not running properly.

![image](https://user-images.githubusercontent.com/31770504/62971944-fad38180-bde0-11e9-8925-c611d39eda9c.png)

**Comment by megisys** [comment]
Juanita, While we are in a Development and Test phase and the server is constantly going up and down. The timing will stop constantly. In a Production environment we are very careful to not stop the system. AS this is regular occurance, we just need the task refreshed to start with Now Date and Time and the function will run again.

**Comment by ABonomo21** [comment]
closing will leave as a will monitor - need to follow up with IIT staff to make sure they are trained on having this functionality working daily @dhenry-KCI
