### ISSUE TITLE
Building - NONRES - Site Compliance Inspections

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#148]
Non-Residential building permits with site compliance; Should Site Compliance Inspections generate before the Building Final or at the same time as the Building Final? 

AP: 237372
Logged By: M. Coffman

![image](https://user-images.githubusercontent.com/4104464/53597887-49fa6280-3b71-11e9-9928-125df7cbd19d.png)

**Comment by dhenry-KCI** [comment]
@ABonomo21 please meet with Tolson and Gary to determine correct order of inspections for Site Compliance and Building Final

**Comment by ABonomo21** [comment]
Site compliance inspection and building final should populate at the same time. - confirmed with GH- ab

**Comment by goggansd** [comment]
Changed AddOn milestone for SITE COMPLIANCE INSPECTION from Inspections milestone to Final Inspection milestone to match the FINAL INSPECTION.

**Comment by ABonomo21** [comment]
Issue Corrected-MCoffman
Permit# 240191
Site Compliance now generates at the same time as Building Final
![image](https://user-images.githubusercontent.com/47611580/55563055-320f8480-56c3-11e9-8ff2-3ee7d1d3507c.png)
