### ISSUE TITLE
Building Permits - RESBLDG - Cannot Group Add from Existing Permit - (Xtreme Ticket #13774270)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1480]
Get the following error when trying to Group Add from an existing RESBLDG permit. I am able to group from a FIRE permit.

![image](https://user-images.githubusercontent.com/31770504/62707584-9d45cc00-b9bf-11e9-8c6e-fbf7d451005b.png)

**Comment by megisys** [comment]
Logged with Infor Support

**Comment by megisys** [comment]
Level of Effort - Debugging and pushing with Support and Development - 4 Hours

**Comment by megisys** [comment]
Still an Issue

**Comment by calequin** [comment]
formula BP_RES_CONAPT_AOC

**Comment by calequin** [comment]
followed up with support on the outcome of this issue.

**Comment by megisys** [comment]
**PLEASE TEST IN DEV _____ http://wh-ipsdevtst/ipsdev/**

**Comment by megisys** [comment]
It is in TEST Now.. But I would have to restart IIS for you to see it. They are training

**Comment by ABonomo21** [comment]
tested in DEV good job
