### ISSUE TITLE
Building Permits - Electrical Permit - Attachments on R4C (Excel # 65)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1481]
On R4C I opened an application I created on 8/5/2019. I added an attachment at the time of application submission, however the Attachments section is not showing for me to view it or at least know that it exists on this application. The attachment does appear on the Attachments tab in IPS.

![image](https://user-images.githubusercontent.com/31770504/62709260-0549e180-b9c3-11e9-993c-f8d2bcfd93e6.png)

![image](https://user-images.githubusercontent.com/31770504/62709295-1561c100-b9c3-11e9-82af-b894ee74c08e.png)

![image](https://user-images.githubusercontent.com/31770504/62709356-31fdf900-b9c3-11e9-9e84-934645eda84d.png)

![image](https://user-images.githubusercontent.com/31770504/62709403-4d690400-b9c3-11e9-9545-53ef114ac93b.png)

**Comment by JuanitaMiles** [comment]
I had to log out of the system and log back in for everything to load correctly. Marking as will monitor.

**Comment by dhenry-KCI** [comment]
have not encountered in a month. Closing ticket.
