### ISSUE TITLE
PLANNING - Fees - Concept Site

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1485]
Planning is $614
Engineering is $118
AR
![image](https://user-images.githubusercontent.com/4129185/62720727-9c6d6400-b9d8-11e9-87b7-c594b1289595.png)

**Comment by mmbanong** [comment]
PLANNING - Fees - Concept Site fees have been updated
![concept planning](https://user-images.githubusercontent.com/47392173/63102879-f4144e00-bf49-11e9-8a38-a1b12b8ed2a8.PNG)
![Concept plan engineering](https://user-images.githubusercontent.com/47392173/63102881-f4144e00-bf49-11e9-94ac-6bc1027da690.PNG)

**Comment by dhenry-KCI** [comment]
fixed

![image](https://user-images.githubusercontent.com/4129185/63447657-64b7e080-c40a-11e9-91b4-e41513a02431.png)
