### ISSUE TITLE
planning-notifications-all ap's-under review emails

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1487]
someone needs to review notifications for under review for all AP types.  On some we are getting notice of the first cycle due dates but not later cycles, and vice versa. So far this morning BOA and Prelim are all over the place.

PP245042- no notification on 1st review cycle.

![image](https://user-images.githubusercontent.com/4129185/62723227-2409a180-b9de-11e9-9680-0d90f5f9bacf.png)

MW

**Comment by dhenry-KCI** [comment]
the only notification i got under the above AP was fees.

**Comment by dhenry-KCI** [comment]
SP245043 -only notification was fees.  Appears all notifications were turned off on Planning side except fee payment

**Comment by dhenry-KCI** [comment]
not sure why this is marked ready for retest when we are still seeing a lack of notifications on all AP types at various milestones.

MW

**Comment by megisys** [comment]
Notification Matrix
