### ISSUE TITLE
Scheduling Inspection - Error 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1489]
when trying to schedule multiple inspections at one time we get an error that the child permits are not final and cannot schedule inspection however- it does not specify which permit inspection cannot be scheduled 
![image](https://user-images.githubusercontent.com/47611580/62727105-bada5c00-b9e6-11e9-8556-38ba813931d4.png)

**Comment by ABonomo21** [comment]
tried to schedule 246126 - inspection # 976049 and permit #246125 inspection 976050

246126 is the one pending trades to be final but 246125 should have been allowed to be scheduled

**Comment by ABonomo21** [comment]
when trying to schedule permits two permits that have two different issues- it gives me the errors but it does not specify which permit 

![image](https://user-images.githubusercontent.com/47611580/62729845-c3ce2c00-b9ec-11e9-8fac-d11bef8cdd8a.png)

**Comment by megisys** [comment]
Will have to work through them one at a time it will report the first it hits.. Added Inspection Number for Troubleshooting

**Comment by ABonomo21** [comment]
fixed 9.5.19 ab
