### ISSUE TITLE
Building - NONRES - extra Inspections

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#149]
Non-Residential Addition Electrical permit# 238379; according to airtable, LVOL and PROG Inspections should not generate on this permit

AP: 238379
Logged by: M. Coffman

![image](https://user-images.githubusercontent.com/4104464/53598057-c12ff680-3b71-11e9-8e57-37314a0e4951.png)

**Comment by dhenry-KCI** [comment]
Confirmed Fixed-AW

![image](https://user-images.githubusercontent.com/4129185/53741841-444c9780-3e65-11e9-83e6-9f112beafac0.png)
