### ISSUE TITLE
Building Permit - Auto Assignment of Inspections 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1490]
Demo permit 246125 was not auto assigned for the inspector

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/62727374-5bc91700-b9e7-11e9-9baa-4a75f8b051ea.png)

**Comment by ABonomo21** [comment]
246176 did not auto generate inspector assignment

**Comment by ABonomo21** [comment]
did not generate for electrical permit 246128 either

**Comment by megisys** [comment]
This is Data Entry and not configuration - County Fix. This is business as usual entry

**Comment by ABonomo21** [comment]
plumbing permit did not autogenerate inspector assignment 

![image](https://user-images.githubusercontent.com/47611580/62882984-123b3d80-bd01-11e9-81d4-63a67aa73cdb.png)

**Comment by mmbanong** [comment]
The election district in the parcel details for the associated address 0068 is not assigned to an inspector. The inspector assignment for this election district needs to be updated

**Comment by dhenry-KCI** [comment]
email Austin and Kevin to update election district values on 8/16

**Comment by JuanitaMiles** [comment]
Tanks does not work - 246548
![image](https://user-images.githubusercontent.com/31770504/64363618-1d6f4980-cfdf-11e9-8134-6157f82801c9.png)

Demolition does not work - 246540
![image](https://user-images.githubusercontent.com/31770504/64363741-61624e80-cfdf-11e9-87ba-ebfe48bf366d.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/64369579-ad66c080-cfea-11e9-8d8d-b007d761da97.png)
fixed 9.5.19 ab
