### ISSUE TITLE
Building Permit - CIP and Municipal Project 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1491]
Please make the CIP and Municipal Projects check boxes only visible in back office 

![image](https://user-images.githubusercontent.com/47611580/62727691-004b5900-b9e8-11e9-8fdb-93e59d046922.png)

**Comment by JuanitaMiles** [comment]
Check boxes not visible on R4C for trailer. Fixed
