### ISSUE TITLE
Demo permit - Reports 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1496]
We would only like to see reports that are applicable to the permit type instead of all building permit reports available at the same milestone. is this possible ?

![image](https://user-images.githubusercontent.com/47611580/62728719-7650bf80-b9ea-11e9-9dc7-0e6855c8cb8a.png)

**Comment by dhenry-KCI** [comment]
@TaraF - see ashlye's comment. Looking to filter reports to the applicable AP.

**Comment by TaraF** [comment]
This should be fixed for demo.  Ready for retest.

**Comment by ABonomo21** [comment]
on demand reports appear to be cleaned up better - will monitor for other a/ps during testing and training 
![image](https://user-images.githubusercontent.com/47611580/65630717-f1266780-dfa3-11e9-849e-4d1f53339784.png)
