### ISSUE TITLE
SMS- Testing error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1497]
getting error when trying to send a sms from mobile device - 
How are we testing this ?? 

i think Christian set up for my county mobile phone to get the texts but i have not received any - which i wouldn't because we cannot send them

**Comment by dhenry-KCI** [comment]
@calequin update to 610.780.7359
 we can test scenarios to ensure they are being sent. If we are comfortable with the process we could then turnoff until training.

**Comment by calequin** [comment]
I have enabled it to work but we need to change all phone numbers in the system to avoid wrongful texts

**Comment by calequin** [comment]
please let me know when we want to test it and i will enable it. disabled it to avoid issues

**Comment by ABonomo21** [comment]
Dustin please set up a time with bob to test this ticket @dhenry-KCI

**Comment by ABonomo21** [comment]
dustin please set up a time to work with Bob and I on this one with Christian @dhenry-KCI

**Comment by ABonomo21** [comment]
emailed dustin and bob 11.6.19

**Comment by ABonomo21** [comment]
![Uploading image.png…]()
