### ISSUE TITLE
Building Permit - Failed Inspection _ Mobile 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1498]
when testing a follow up inspection on mobile for a follow up for a previously failed inspection, we are unable to see the previous code violations lists on the first failed inspection.

**Comment by ABonomo21** [comment]
same problem with the second follow up inspection. - the inspectors need to be able to see the previous code violations on mobile  so they know what they are following up to and can approve or deny what is fixed and what has not been fixed...

**Comment by calequin** [comment]
Code violations trickle down to the follow up inspection if they are outstanding and not resulted. I just tested with permit 246102. I failed the first footing inspection and added violations. They followed onto the next inspection.

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
