### ISSUE TITLE
License - Distributor Report - DISREP Review Resubmit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#15]
(Reported by Kelly Vanaman 2/6/19)

License DR235681 - Completed the Distributor Report Review requesting a Resubmit and it moved straight to a Completed milestone. At times we may require a Resubmit if an attached invoice does not match the amount of bags paid listed on the Distributor Report. 

If a review is resulted with a Resubmit review result, the license should follow the same Applicant Resubmittal loop as the rest of the application.

![image](https://user-images.githubusercontent.com/31770504/52425618-5d626280-2aca-11e9-9e3d-62797618729a.png)

![image](https://user-images.githubusercontent.com/31770504/52425797-bc27dc00-2aca-11e9-83b3-6837d8735c01.png)

**Comment by megisys** [comment]
Moved Review before payment fee generation and added awaiting applicant resubmit

**Comment by dhenry-KCI** [comment]
Testing resubmit for DR235685 went to awaiting applicant resubmit milestone instead of completed.

![image](https://user-images.githubusercontent.com/4129185/52588298-219d0500-2e0a-11e9-98ca-80b212439c0b.png)
