### ISSUE TITLE
Building - NONRES - Sprinkler Fire Suppression - Inspections

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#150]
Fire permit# 238381 Sprinkler Fire Suppression - NFPA 13 & 13R - with a Pneumatic Test or Dry Sprinkler System:
Inspections should be Underground Flush and Underground Hydro, Sprinkler Hydrostatic and Overhead Sprinkler Piping, 24 Hour Air Test, Trip Test - for Dry System, and Main Drain Test and Sprinkler Final

AP: 238381
Logged By: M. Coffman

![image](https://user-images.githubusercontent.com/4104464/53598242-313e7c80-3b72-11e9-95e5-8f21568139d8.png)

**Comment by megisys** [comment]
I need the actual Inspection Type Names please.. Hard for us to ensure we get the right ones. There are 10 types of Suppression options on the detail page.. Can you please give us the matrix .

**Comment by dhenry-KCI** [comment]
@imazlout see issue #153. Matrix exists in airtable. The matrix includes the type of suppression with the associated specialty inspection type (Dry deluge for instance)

**Comment by imazlout** [comment]
Ready for test. 
Updated all inspection formulas to follow exactly what's listed in Airtable for the Fire Permit. I ran each of the following tests to ensure that the inspections added as per airtable. Please see below for details:

**Scenario: Sprinkler Fire Suppression - NFPA 13 & 13R - with a Forward Flow Test or Backflow Preventer (Tested with AP#238530)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.FireSuppression13R = True
- FireSupDetail.FwdFlw = True

**Scenario: Sprinkler Fire Suppression - NFPA 13 & 13R - with a Deluge Dry Pipe Test (Tested with AP#238531)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.FireSuppression13R = True
- FireSupDetail.Deluge = True

**Scenario: Sprinkler Fire Suppression - NFPA 13 & 13R - with a Pneumatic Test or Dry Sprinkler System (Tested with AP#238532)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.FireSuppression13R = True
- FireSupDetail.Pneum = True

**Scenario: NFPA 13D - with Pump and Tank (Tested with AP#238533)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN" 
- FireAlarmDetail.FireSuppression13D = True

**Scenario: Fire Pump NFPA 20 (Tested with AP#238543)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.FirePump = True

**Scenario: Standpipe System NFPA 14 (Tested with AP#238548)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.StandpipeSystem = True

**Scenario: Hood Suppression System NFPA 96 - New Installation (Tested with AP#238550)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.HoodSuppression = True
- oBldgApp.WorkType.Code.Trim() = "NEW"

**Scenario: Other Chemical Extinguishing (Tested with AP#238553)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.OtherChemicalExtinguishing = True

**Scenario: Fire Alarm (Tested with AP#238554)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "ALARM"

**Comment by ABonomo21** [comment]
Issue is half fixed-All the correct inspections generated except for the Sprinkler Hydrostatic. The Visual Inspection of the Hydro Test should be replaced by the Sprinkler Hydrostatic

![image](https://user-images.githubusercontent.com/47611580/54206575-f4964d80-44ae-11e9-894b-81060bd8c63a.png)

**Comment by megisys** [comment]
This is completed

**Comment by ABonomo21** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54300774-f2f28580-4593-11e9-8d74-adb9e2024209.png)
