### ISSUE TITLE
Building permit - Pending Certificate Milestone 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1501]
After the passed final inspection the demolition permits can just go to closed - final it does NOT need to stop in the pending certificate milestone because we do not issue COC's or COO's for demo 

![image](https://user-images.githubusercontent.com/47611580/62730103-52db4400-b9ed-11e9-877b-a4e9910aba21.png)

**Comment by ABonomo21** [comment]
Also for Sign please

**Comment by ABonomo21** [comment]
also tanks do not need to go to pending certificate - they can just go to closed

**Comment by megisys** [comment]
I can not replicate this for DEmolition. If you get another one to stick in that milestone. PLease leave it there and I will review why

**Comment by dhenry-KCI** [comment]
Created both a tank and sign permit. Both stopped in the pending certificate milestone. Application should go to closed after final inspections.

**Comment by dhenry-KCI** [comment]
Both tank and sign permit stopped at pending certificate. 
246203

**Comment by calequin** [comment]
expired pending certificate milestone in tanks, signs and demolition and changed the next milestone from final inspection to complete.

**Comment by JuanitaMiles** [comment]
Demo works - 246540
Sign works - 246543
Tank did not work - 246548
![image](https://user-images.githubusercontent.com/31770504/64360251-15f87200-cfd8-11e9-8d77-a42517166e9f.png)

**Comment by JuanitaMiles** [comment]
Tank works - 246552
