### ISSUE TITLE
Building Permit- Sign - Allowance of requesting an inspection 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1503]
sign permit 246170 was able to request an inspection without the trade permit being obtained, if fees are due or permits are required - the inspection should not be able to be requested it should alert the applicant on the r4c side 

![image](https://user-images.githubusercontent.com/31770504/62731730-d64a6480-b9f0-11e9-8fe1-8cec39c4bc1a.png)

**Comment by calequin** [comment]
the status check is currently not allowing the final inspection without a related trade permit associated. Is this true? If not then we need to place the status check to happen prior to entering the inspections milestone.

**Comment by calequin** [comment]
fixed in dev. added calldatetime to the formula manageinspections

**Comment by megisys** [comment]
Why is this EVEN here. This status check should be on pending issuance ? We dont want to issue a permit without a child elec permit do we ?

**Comment by dhenry-KCI** [comment]
@megisys - what's the status on this ticket?

**Comment by ABonomo21** [comment]
we can issue the sign permit without an electrical permit related- this goes to the larger issue of being able to submit requests for inspections when the subsequent requirements have not been fulfilled.

**Comment by calequin** [comment]
fixed. added formula to stop inspection request and scheduling if the related child permit has an open final inspection
