### ISSUE TITLE
Building Permit Milestones

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1504]
DON'T FREAK OUT :) , just question... kind of a bug

 If there is a submit resulted on a building permit - 

currently the Awaiting Revision Fee milestone generates then Awaiting Applicant Revisions then Revision Assignment

Can we switch the Awaiting Applicant Revisions and the Awaiting Revision Fee Milestone for all building A/p's - just seems to logically make more sense they submit their revision - pay the revision fee and then we get the review.

**Comment by dhenry-KCI** [comment]
adjusted milestones in IPS - emailed Robert to ignore IPS / PDOX handshake at awaiting fees. Closing ticket
