### ISSUE TITLE
R4C errors

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1509]
one was present all morning but system still worked.  Was timing out but hit stay logged in button and three more populated.

![image](https://user-images.githubusercontent.com/4129185/62788171-5e357a80-ba94-11e9-96b2-3d0e6c7c8641.png)

**Comment by megisys** [comment]
Could be Infor making Changes

**Comment by dhenry-KCI** [comment]
Closing this issue. Will continue to monitor and track errors on R4C.
