### ISSUE TITLE
License - Special Event - Agency Review Resubmit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#151]
@calequin Was it decided with the Liquor Board that if a review is resulted with Resubmit during Under Review, the application would still bypass the Awaiting Applicant Revisions milestone for resubmittal? 

In the example I'm working on I resulted a BOARD review with Resubmit, Approved the rest and the application went straight to Awaiting Fee Payment rather than a resubmittal loop.

![image](https://user-images.githubusercontent.com/31770504/53646011-2f26fd00-3c08-11e9-902f-e7fa1da9b895.png)

![image](https://user-images.githubusercontent.com/31770504/53646113-64334f80-3c08-11e9-93a3-cb8950bf1734.png)

**Comment by calequin** [comment]
fixed the milestone formula to allow the resubmittal loop.

**Comment by JuanitaMiles** [comment]
Tested - Application begins the resubmittal loop as expected however the Applicant Actions detail page needs to be made available.

![image](https://user-images.githubusercontent.com/31770504/53652038-e5ddaa00-3c15-11e9-8561-6ef87c202dd1.png)

**Comment by calequin** [comment]
added correct detail page. Make sure to log off and log back in since Access Control was added.

**Comment by JuanitaMiles** [comment]
Confirmed fixed.
