### ISSUE TITLE
PLANNING - R4C - # of pages field visible on R4C (Excel Issue # 45)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1510]
Make # of pages visible on R4C for PLAT and make it a required field so the applicant fills it in and we don't have issues with the resubmit on completeness check.
AR
![image](https://user-images.githubusercontent.com/4129185/62788541-19f6aa00-ba95-11e9-81b2-082921cd4804.png)

![image](https://user-images.githubusercontent.com/4129185/62787643-267a0300-ba93-11e9-9133-66dd4dd2bbf2.png)

**Comment by megisys** [comment]
Marking as an Enhancement as this has been this way for a while. And we discussed that pages would be Processed by the COmpleteness Check as Applicants might know what makes up a page.

**Comment by dhenry-KCI** [comment]
@calequin this only applies to Plats.

**Comment by calequin** [comment]
duplicate of #803

**Comment by dhenry-KCI** [comment]
The underlying problem with this is that when you have # of pages under the completeness check, you cannot result the completeness check as a resubmit because # of pages holds up the milestone from going back to Awaiting Applicant Resubmit. 
We will not know the number of pages unless the applicant provides a copy of the plat they will be submitting through PDOX. This will commonly be a reason to require a resubmit of the completeness check. This is a Bug.

![image](https://user-images.githubusercontent.com/4129185/63461836-8a071780-c427-11e9-9cb0-96ad81ece982.png)

![image](https://user-images.githubusercontent.com/4129185/63461794-7491ed80-c427-11e9-81a6-01e198cafb77.png)

**Comment by megisys** [comment]
Add Other Status Check whichi s bypassed for Resubmits during Completeness Check

**Comment by dhenry-KCI** [comment]
PL245121

This should be a fillable field without the use of a calculator. You used to be able to click in the number of pages field and type the number of pages
AR
![image](https://user-images.githubusercontent.com/4129185/63693921-4162ac00-c7e3-11e9-8181-dac51ebea62d.png)

**Comment by dhenry-KCI** [comment]
tested combo, farm lot, and public taking.  All worked.

MW
