### ISSUE TITLE
PLANNING - completeness check comments to Detail Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1512]
Completeness Check comments should also show under Applicant Actions under all Applications and work types that have a completeness check. 
AR
![image](https://user-images.githubusercontent.com/4129185/62789193-6f7f8680-ba96-11e9-859b-d42becbd6473.png)

![image](https://user-images.githubusercontent.com/4129185/62789157-5b3b8980-ba96-11e9-8ec4-6c2fd32fb653.png)

**Comment by megisys** [comment]
Fixed see PL245066

**Comment by dhenry-KCI** [comment]
tested in site, FRO, and plat.  looks good

MW
