### ISSUE TITLE
grading - major grading - applicant actions

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1515]
under applicant actions these are my action options - i believe that these are wrong and it should be yes or no here - these appear to be relating to a bond release. 

![image](https://user-images.githubusercontent.com/4129185/62792724-da808b80-ba9d-11e9-84ed-bc19e2ec4154.png)

**Comment by megisys** [comment]
No these are correct.. For Applicant Actions

**Comment by ABonomo21** [comment]
we need to test this- it should come through as a log and we need a dashboard report that there has been a log and an applicant actions detail page completed. @dhenry-KCI

**Comment by calequin** [comment]
this is working. Workflow as follows.
1. Intake Review - county submits the result as a resubmit with information of what is missing.
2. Applicant receives a notification with instructions to log in and resubmit
3. applicant fills out applicant actions detail page and submits
4. application goes into the intake review which then falls back into the countys workload. the log is also recorded for information on what the applicant has submitted.
