### ISSUE TITLE
Planning-plat-public taking-no notifications being sent

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1517]
see pl244949

Nothing in logs either.  Didnt get fee notification or any other notification.

MW

**Comment by megisys** [comment]
Add Fee Notification On. As this is Eplans. OTher Notifications should be generated from Project Dox

**Comment by dhenry-KCI** [comment]
did not receive fee notifications.  Should have received two...one for initial fees and one for the $59 mylar fee.

![image](https://user-images.githubusercontent.com/4129185/63440430-cb82cd00-c3fd-11e9-9d67-398fdb94f024.png)

MW

**Comment by dhenry-KCI** [comment]
Closing this ticket as it has been added to #1521
