### ISSUE TITLE
Planning - Plats (All) - Mylar Notifications

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#152]
The system should generate a notification for all Plats at admin closure with the following information:
- Date Recorded
- Plat Book # 
- Page # 

Notification should be sent to owner/applicant and surveyor. See screenshot of below of information to be sent:

![mylar](https://user-images.githubusercontent.com/4129185/53646565-7eb9f880-3c09-11e9-84d2-d54049903b65.png)

**Comment by megisys** [comment]
@dhenry-KCI - This is a new request.. Please Assign to County

**Comment by dhenry-KCI** [comment]
fixed MW
