### ISSUE TITLE
Planning notification language-all notifications

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1520]
on all notifications for Planning,  please replace "from your planning and zoning team at frederick county" with:

Thank You,
Department of Development Review and Planning.

MW

**Comment by megisys** [comment]
Hi Dustin,

Notifications are Data. And will not Transfer. So this needs to be done manually in the required environements

**Comment by dhenry-KCI** [comment]
just got this notification...language not changed. 

![image](https://user-images.githubusercontent.com/4129185/63452993-a7cb8100-c415-11e9-85fb-d19c82cdcd9d.png)


MW

**Comment by dhenry-KCI** [comment]
another one

![image](https://user-images.githubusercontent.com/4129185/63462203-61cbe880-c428-11e9-8b8e-afb1062291ab.png)
