### ISSUE TITLE
PLANNING - IPS NOTIFICATIONS

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1521]
IPS Notifications needed where PDOCS notifications are not duplicated. Some questions on what the actual notification is. AR
[PLANNING NOTIFICATIONS in IPS for PDOCS.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3487525/PLANNING.NOTIFICATIONS.in.IPS.for.PDOCS.xlsx)
[PLANNING.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3487526/PLANNING.xlsx)

**Comment by mmbanong** [comment]
I am not able to identify IPS Notifications where PDOCS notifications are not duplicated.
Can I get the list of required notifications?
