### ISSUE TITLE
Building Permit - Completeness Check result 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1522]
If a result is marked at completeness check on any building permit as NFC, it should ignore all status checks such as priority code !

![image](https://user-images.githubusercontent.com/47611580/62800809-5258b100-bab2-11e9-873c-bfa0ea05459f.png)

**Comment by megisys** [comment]
This is how it works out of the box.. Enter a priority will remove this issue

**Comment by JuanitaMiles** [comment]
Resulted Completeness Check with NFC, but the application is still requiring the Homebuilder license to be added. NFC should ignore all status checks.
 
![image](https://user-images.githubusercontent.com/31770504/65437002-07d88d00-ddf1-11e9-873d-0e99c94e7253.png)

![image](https://user-images.githubusercontent.com/31770504/65437048-19219980-ddf1-11e9-8edb-87f46fcd831c.png)

**Comment by megisys** [comment]
UPdated

**Comment by ABonomo21** [comment]
resulted as nfc and the permit closed without any status checks will monitor
