### ISSUE TITLE
Planning-all plats-mylar fee wrong

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1524]
Mylar fee needs to be $59

![image](https://user-images.githubusercontent.com/4129185/62867995-9d590b00-bce2-11e9-8d17-5c59653e0471.png)

MW

**Comment by mmbanong** [comment]
PLN_PLAT_MylarReviewFee_FVF has hard coded value of $58.00. Formula needs to converted to read from the Rate table

**Comment by dhenry-KCI** [comment]
fixed

![image](https://user-images.githubusercontent.com/4129185/63439960-03d5db80-c3fd-11e9-8efc-c21cb48a2cba.png)
