### ISSUE TITLE
Licensed Contact Search 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1527]
when trying to search for a licensed contact i changed the applicant type to licensed contact and searched the license number and nothing generated. 
then search with the applicant type as property owner and it came up... 

![image](https://user-images.githubusercontent.com/47611580/62875296-ca141f00-bcf0-11e9-9623-4c7dd3a44617.png)
![image](https://user-images.githubusercontent.com/47611580/62875336-dbf5c200-bcf0-11e9-8958-cd4baf89f2f1.png)

![image](https://user-images.githubusercontent.com/47611580/62875258-b963a900-bcf0-11e9-8f20-e4643a6f2b6e.png)

**Comment by megisys** [comment]
Enhancement - And Training Issue. Will need to add a Request to Infor Development to modify this.

Dan
