### ISSUE TITLE
Planning-FRO-missing intermediate/full NRI/FSD 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1528]
there are two NRI/FSD fees depending on if forest is removed or not.  IPS and R4C only has one of the two.  
The one we have is NRI/FSD simplified, which is for project that are not removing forest and has a fee of $81 + $1.00/acre

The one we dont have is Intermediate/Full, which is for project proposing to remove forest, and it has a fee of $237 + $2.00/acre.

The fee code for Intermediate/Full is the same fee as the Preliminary FRO plan (FULLPFCP) if that helps.

Dont know what is easier...changing the simplified application we have to work for both, with a "forest removal y/n" field that drives the fee, or some other approach. 

![image](https://user-images.githubusercontent.com/4129185/62875119-6e499600-bcf0-11e9-8167-914d1f6ea124.png)

![image](https://user-images.githubusercontent.com/4129185/62875131-76a1d100-bcf0-11e9-93cb-b9d3fdb24161.png)

MW

**Comment by megisys** [comment]
You need to scroll up on WorkType it is there..

**Comment by dhenry-KCI** [comment]
no its not.  Maybe you are seeing FSD and Prelim Forest Conserve Plan, which is different than a stand alone Intermediate/Full NRI/FSD-
MW

**Comment by megisys** [comment]
PLease Provide Code and Description

**Comment by dhenry-KCI** [comment]
new code for Intermediate/Full nri/fsd........     

NRIFSDFUL

Description= NRI/FSD Intermediate/Full

Fee= $237 + $2.00/acre

**Comment by dhenry-KCI** [comment]
good!


![image](https://user-images.githubusercontent.com/4129185/63288423-aae63600-c28a-11e9-9161-848b330ffd67.png)


MW
