### ISSUE TITLE
R4C - Building Permits - Electrical Permit - Cannot Pay Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1529]
I cannot pay fees for the Electrical Permit on R4C.

![image](https://user-images.githubusercontent.com/31770504/62876380-d4cfb380-bcf2-11e9-94d5-eb1834df9422.png)

**Comment by megisys** [comment]
Close as Duplicate.. Add on COndition Formulas for Notifications failing causing Payment to roll back..
#1537
