### ISSUE TITLE
Building - NONRES - Fire Suppression System; NFPA 13 & 13R W/ Forward Flow/Backflow test marked yes

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#153]
Fire Suppression System; NFPA 13 & 13R W/ Forward Flow/Backflow test marked yes
Too many inspections generated; Should Only Be Sprinkler Hydrostatic and Overhead Sprinkler Piping

AP: 237322
Logged By: M. Coffman

![image](https://user-images.githubusercontent.com/4104464/53649617-84ffa300-3c10-11e9-844f-110a3404110c.png)

**Comment by megisys** [comment]
Can we please have a matrix written by Type of Suppression as a Check Please..

**Comment by imazlout** [comment]
For these types of issues reported, as Dan mentioned, we need to know the exact criteria in terms of the fields checked/filled out and the actual name of the inspection in the system, so that we can make sure the formulas match appropriately.

**Comment by dhenry-KCI** [comment]
@imazlout The matrix of required inspections is in airtable under Building permit, Fire Tab. It includes required or conditional inspections as well as the required inspection order.

**Comment by imazlout** [comment]
Ready for test. 
Updated all inspection formulas to follow exactly what's listed in Airtable for the Fire Permit. I ran each of the following tests to ensure that the inspections added as per airtable. Please see below for details:

**Scenario: Sprinkler Fire Suppression - NFPA 13 & 13R - with a Forward Flow Test or Backflow Preventer (Tested with AP#238530)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.FireSuppression13R = True
- FireSupDetail.FwdFlw = True

**Scenario: Sprinkler Fire Suppression - NFPA 13 & 13R - with a Deluge Dry Pipe Test (Tested with AP#238531)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.FireSuppression13R = True
- FireSupDetail.Deluge = True

**Scenario: Sprinkler Fire Suppression - NFPA 13 & 13R - with a Pneumatic Test or Dry Sprinkler System (Tested with AP#238532)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.FireSuppression13R = True
- FireSupDetail.Pneum = True

**Scenario: NFPA 13D - with Pump and Tank (Tested with AP#238533)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN" 
- FireAlarmDetail.FireSuppression13D = True

**Scenario: Fire Pump NFPA 20 (Tested with AP#238543)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.FirePump = True

**Scenario: Standpipe System NFPA 14 (Tested with AP#238548)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.StandpipeSystem = True

**Scenario: Hood Suppression System NFPA 96 - New Installation (Tested with AP#238550)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.HoodSuppression = True
- oBldgApp.WorkType.Code.Trim() = "NEW"

**Scenario: Other Chemical Extinguishing (Tested with AP#238553)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "SUPPRSSN"
- FireAlarmDetail.OtherChemicalExtinguishing = True

**Scenario: Fire Alarm (Tested with AP#238554)**
Criteria:

- FireAlarmDetail.FirePermitType.Code.Trim() = "ALARM"

**Comment by ABonomo21** [comment]
Issued partially fixed-all the correct inspections generated except for the Sprinkler Hydrostatic . The Visual Inspection of Hydro Test should be replaced by the Sprinkler Hyrdrostatic.-AW

![image](https://user-images.githubusercontent.com/47611580/54208249-edbd0a00-44b1-11e9-9923-eb82ee4307e9.png)

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54300148-a490b700-4592-11e9-9f38-ffa873060b96.png)
