### ISSUE TITLE
Electrical Issuance - Report Data

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1530]
Fees paid did not generate an amount on the electrical permit 
![image](https://user-images.githubusercontent.com/47611580/62876512-16f8f500-bcf3-11e9-9e64-2dc32f416436.png)
![image](https://user-images.githubusercontent.com/47611580/62876552-2c6e1f00-bcf3-11e9-8253-47be5efcc8ee.png)

**Comment by dhenry-KCI** [comment]
@TaraF - see issue for electrical issuance Report.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/64370100-c15ef200-cfeb-11e9-9c51-90850d384b3c.png)
fixed 9.5.19 ab
