### ISSUE TITLE
FRO-notify applicant of mitigation required

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1535]
need to notify applicant when FRO mitigation is expected.  If  the items in yellow below are checked a notification should go out saying that the checked item is required.  This notification must be sent out after signature set is approved.

![image](https://user-images.githubusercontent.com/4129185/62884257-10bf4480-bd04-11e9-9ed7-043ba6d3fa86.png)

MW

**Comment by dhenry-KCI** [comment]
Will follow-up with Ashley R. to confirm this is inluded in her matrix.

**Comment by dhenry-KCI** [comment]
This is not working 
![image](https://user-images.githubusercontent.com/4129185/63948469-b255ce00-ca46-11e9-971d-e8682dfb7d73.png)

![image](https://user-images.githubusercontent.com/4129185/63948415-92260f00-ca46-11e9-950a-b6cf52db52d4.png)

**Comment by calequin** [comment]
Received planning fees and mitigation notification.
![image](https://user-images.githubusercontent.com/47603568/64459557-cab88f00-d0bd-11e9-9525-de25960389a6.png)
![image](https://user-images.githubusercontent.com/47603568/64459571-d4da8d80-d0bd-11e9-8cce-4dd5201bbbdf.png)

**Comment by dhenry-KCI** [comment]
works, but change "out" portal to "our. 

![image](https://user-images.githubusercontent.com/4129185/64621807-51b68180-d3b4-11e9-9194-6fe803cf64fd.png)


MW

**Comment by dhenry-KCI** [comment]
spelling fixed and amount showing in R4C
![image](https://user-images.githubusercontent.com/4129185/64980123-37cee000-d887-11e9-83c0-275771120d22.png)
