### ISSUE TITLE
R4C - Building Permits - Plumbing Permit - Cannot Pay Fees - Xtreme Ticket

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1537]
Cannot Pay the Fees for Plumbing Permit 246167 on R4C.

![image](https://user-images.githubusercontent.com/31770504/62884602-f46fd780-bd04-11e9-9ce2-04e2f0e0da8f.png)

**Comment by calequin** [comment]
sent email to santhosh and sireesha

**Comment by megisys** [comment]
Notification Error about AOC formulas

**Comment by megisys** [comment]
LInked to Other Effort - Should be included

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
I was able to pay fees for both Plumbing and Resbldg
