### ISSUE TITLE
Planning - Site - Details Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#154]
During the migration the details page the applicant completes and the site intake details page switched. 

The Applicant details page should look like this (from Snapshot):
![intake details snapshot](https://user-images.githubusercontent.com/4129185/53649618-85983980-3c10-11e9-8130-930fd827b0c4.PNG)

The intake details page should include the following:
![ntake details](https://user-images.githubusercontent.com/4129185/53649643-9a74cd00-3c10-11e9-805a-d37161ef859f.PNG)

**Comment by megisys** [comment]
Fixed this Issue

**Comment by dhenry-KCI** [comment]
corrected SP237431 - AReed
