### ISSUE TITLE
Building Permits - Cannot Open Attachments

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1540]
I cannot open attachments in IPS for older existing permits that were migrated. I can open them for new applications I've created in R4C.

Examples that I have tried include:

192752
192721
192908
190828
193269

**Comment by megisys** [comment]
What do they look like in Hansen 7 . PLease provide the Attachments from 7 for one of these.

Dan

**Comment by ABonomo21** [comment]
192752
![image](https://user-images.githubusercontent.com/47611580/62887965-52ec8400-bd0c-11e9-9879-adaea43769de.png)

**Comment by ABonomo21** [comment]
192721
![image](https://user-images.githubusercontent.com/47611580/62888010-6e578f00-bd0c-11e9-946f-744584471f2c.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/62888244-db6b2480-bd0c-11e9-8802-eea1ff7e110b.png)

**Comment by megisys** [comment]
Hi There, This is expected. As we copied from PreProd to Test and Didn't move the corresponding Attachments. if you look at http://wh-ipsprd/ips_preprod . You will see all is well.

**Comment by ABonomo21** [comment]
confirmed it works 9.5.19 ab
