### ISSUE TITLE
Building Permits - In Life Mapping - Linganore Town Ctr

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1541]
All of these LINGANORE TOWN CTR-APT BLD are not in the correct milestone. They are showing as
Status: Open
Milestone: Complete
With Unpaid Fees 

There are 71 of these.

![image](https://user-images.githubusercontent.com/31770504/62888544-81b72a00-bd0d-11e9-8725-9f41b0eb6e10.png)

![image](https://user-images.githubusercontent.com/31770504/62888582-998eae00-bd0d-11e9-9579-4d60fc58d443.png)

![image](https://user-images.githubusercontent.com/31770504/62888618-a9a68d80-bd0d-11e9-8a5a-afd1a5713e1d.png)

![image](https://user-images.githubusercontent.com/31770504/62888641-b7f4a980-bd0d-11e9-819a-8a19238f9611.png)

**Comment by megisys** [comment]
This is the agrees mapping we came up with

**Comment by ABonomo21** [comment]
no - dustin will check the record- this is a pre processed application in hansen. @dhenry-KCI 
![image](https://user-images.githubusercontent.com/47611580/62893106-c051e200-bd17-11e9-9255-06a40a6b8cf4.png)

**Comment by JuanitaMiles** [comment]
milestones appear corrected in pristine environment
