### ISSUE TITLE
PLANNING - APFO Worktypes - formatting

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1544]
Change detail pages accordingly. Email sent 8/6/19
AReed

[APFO STANDARD.docx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3493930/APFO.STANDARD.docx)
[APFO EXEMPTION.docx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3493931/APFO.EXEMPTION.docx)

**Comment by megisys** [comment]
Isnt this #1452

**Comment by dhenry-KCI** [comment]
Yes duplicate, Didn't realize already added as bug.

AREED
