### ISSUE TITLE
Building Permits - RESBLDG - Expired Permit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1545]
If an application's Expires date is past, (meaning the application is now expired) shouldn't the Application Status be updated to Expired to reflect this?

![image](https://user-images.githubusercontent.com/31770504/62891703-6d2a6000-bd14-11e9-95b1-06010613460f.png)

**Comment by megisys** [comment]
This is a batch manager job and they are there to Run.. We dont automatically run at this point.

**Comment by mmbanong** [comment]
The Batch job Expire Building Permits needs to be run but Dan advised me not to ask Dustin for the appropriate time to run the job

**Comment by dhenry-KCI** [comment]
Adding as part of batch manager / go-live checklist- closing
