### ISSUE TITLE
Grading Permit - Fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1550]
SWM fee did not generate on grading permit spawned from a SFD permit -grading permit # 246198

 Storm Water fee 59.00
![image](https://user-images.githubusercontent.com/47611580/62951320-c6979b00-bdb7-11e9-878d-23bbeafd529f.png)

**Comment by mmbanong** [comment]
As per my discussion with Ashley, SWM fee need a formula to meet certain conditions for grading. We talk to Dan about the formula

**Comment by megisys** [comment]
This is not a bug. Grading Detail Disturbed area was never set .

**Comment by dhenry-KCI** [comment]
@ABonomo21 @JuanitaMiles - please confirm during testing. If in agreement close.

**Comment by dhenry-KCI** [comment]
@megisys is RESSFD its always Detached.

**Comment by ABonomo21** [comment]
fixed 9.5.19
![image](https://user-images.githubusercontent.com/47611580/64356288-99ae6080-cfd0-11e9-81be-5b45f9af8fac.png)
