### ISSUE TITLE
Capacity permit- Priority Code

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1551]
priority code should not be required on a capacity permit. 

![image](https://user-images.githubusercontent.com/47611580/62951664-55a4b300-bdb8-11e9-97da-db01e6f52a09.png)

**Comment by JuanitaMiles** [comment]
Fixed - Priority not required on Capacity

![image](https://user-images.githubusercontent.com/31770504/64033827-5610ae00-cb1b-11e9-89a0-4a58c682190e.png)
