### ISSUE TITLE
Pdox- Permit information display

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1552]
not generating permit information on res sfd permit 246191
![image](https://user-images.githubusercontent.com/47611580/62952564-e62fc300-bdb9-11e9-9198-ad5fbfcf3aca.png)

**Comment by ABonomo21** [comment]
upon refresh generated... make sure this is working the first time logged in should not have to refresh 
![image](https://user-images.githubusercontent.com/47611580/62952808-5c342a00-bdba-11e9-924d-eb7d13796328.png)

**Comment by dhenry-KCI** [comment]
We have noticed slow refresh in the past. This is an issue we will need to conitnue to monitor.

**Comment by dhenry-KCI** [comment]
Closing issue as we have noticiced in a month.
