### ISSUE TITLE
Building Permit Resbldg - licensing duplicating 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1553]
![image](https://user-images.githubusercontent.com/47611580/62952889-871e7e00-bdba-11e9-85c8-7257153b3202.png)

**Comment by megisys** [comment]
Because both the parent and the child are listed on the application everything appears twice. Gerry Kelly doesnt need to be added as they are a child already of NVR Homes

**Comment by dhenry-KCI** [comment]
@ABonomo21 @JuanitaMiles - please confirm during testing.
