### ISSUE TITLE
Building Permit - Homebuilders License Expired

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1554]
HB License that expires on 3.1.21 in IPS shows as expired 3.1.19 in pdox.. 

![image](https://user-images.githubusercontent.com/47611580/62953191-08761080-bdbb-11e9-9766-93aa609e8f6d.png)

![image](https://user-images.githubusercontent.com/47611580/62953211-13c93c00-bdbb-11e9-8f1e-2a52b2820317.png)

under contact in IPS the expire dates do not match for the HB and license holder- which data is being pulled to pdox and which data is being pulled to satisfy the HB status check on the completeness check ?  if either license was expired it should have stopped progression for clear updating
![image](https://user-images.githubusercontent.com/47611580/62953409-7ae6f080-bdbb-11e9-8d2f-c6264437fb53.png)

**Comment by megisys** [comment]
Pdox doesn't know to go to License Child Applications. Why does PDox even care about Licenses ? This is a Enhancement and we will need to have a conversation with Dustin and County on Impact here.

**Comment by dhenry-KCI** [comment]
per discussion on 8/19 - will request to remove the following:
![image](https://user-images.githubusercontent.com/4129185/63451101-70f36c00-c411-11e9-9f59-734e57c2ddfb.png)
Email sent to Robert Sosnowski.

**Comment by RS-Avolve** [comment]
I looked at project "251065 - NONRESBLDG - NEW - NRSBUS", which is a non-residential application type.  You can see from the screenshot below that the Licence Information is not shown on the "Applicant Information" tab.  Are you still experiencing this issue on projects?
[Github ticket 1554.docx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3741520/Github.ticket.1554.docx)

**Comment by ABonomo21** [comment]
appears to be working. will continue to check
