### ISSUE TITLE
Email Notification - Resbldg SFD

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1555]
no notification received for impact fee payment required after moving to batch stamp in pdox and current milestone is awaiting applicant payment - permit number 246191

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/63097009-561a8680-bf3d-11e9-8555-1fc49e13b640.png)


You didnt get this one at 11:21 . This is for the impact fees isnt it. You can review from Log Tab
