### ISSUE TITLE
Building Permits - RESBLDG - Grading Child Status at Final Inspection

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1558]
Currently the system will not let you schedule the BLDG Final inspection until the Grading permit (along with all of the other child permits) is in a Complete status. The Grading permit does not have to be in a Complete status for the BLDG Final inspection to be scheduled.

![image](https://user-images.githubusercontent.com/31770504/62959288-707e2400-bdc6-11e9-9815-85e90f3429e6.png)

![image](https://user-images.githubusercontent.com/31770504/62959307-7c69e600-bdc6-11e9-8981-7d2dfe9b9d9d.png)

**Comment by megisys** [comment]
Why is a gaming permit even listed against a RESBLDG . IS this even a requirement

**Comment by ABonomo21** [comment]
fixed 9.5.19 ab
