### ISSUE TITLE
Planning - FRO - Work Type Field

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#156]
The system should move the Work Type field (labeled Type of Project on details tab) from the details tab to the Job Description Field. 

Per meeting between A. Reed and D. Grendon this was to be performed to be consistent across all Planning AP's. 

![missing work type](https://user-images.githubusercontent.com/4129185/53650721-2a1b7b00-3c13-11e9-9601-4682d843cee3.png)

**Comment by megisys** [comment]
This is Addressed

**Comment by dhenry-KCI** [comment]
fixed
