### ISSUE TITLE
Resbldg - report change

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1560]
type of construction is no longer used on the RESBLDG details pages to pull this data 
![image](https://user-images.githubusercontent.com/47611580/62960202-27c76a80-bdc8-11e9-839a-af79ea6eea18.png)

should be pulled by the occupancy type on the job description tab 
![image](https://user-images.githubusercontent.com/47611580/62960273-52192800-bdc8-11e9-9094-ecac8284bb70.png)

**Comment by ABonomo21** [comment]
this is for all future ap's

**Comment by dhenry-KCI** [comment]
@TaraF - please confirm. If confirmed, change label to ready for retest.

**Comment by dhenry-KCI** [comment]
@TaraF - Type of Construction Should be Occupancy Type - be sure to pull the description.

**Comment by TaraF** [comment]
confirmed this is for ALL AP types

**Comment by dhenry-KCI** [comment]
@TaraF is this ready for retest?

**Comment by TaraF** [comment]
Fixed and ready for retest.

**Comment by ABonomo21** [comment]
spoke with tara- going to put the report back to the way it was 
the change would have only been for RESBLDG not all a/p types but it will be to confusing to have it different across all the various a/p's 
sorry for the confusion again just put it back the way it was

**Comment by TaraF** [comment]
This has been reverted and ready for re-test.
