### ISSUE TITLE
PDOX- Resubmit at prescreen review -

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1561]
prescreen corrections task went to county(ashlye) instead of juanita (the applicant)
![image](https://user-images.githubusercontent.com/47611580/62961887-a5d94080-bdcb-11e9-8d04-5092570da587.png)

**Comment by dhenry-KCI** [comment]
Can we walk through this again? Ashlye may still have applicant functionality as Pdox doesn't assign tasks, but the task needs to be accepted by the individual.

**Comment by JuanitaMiles** [comment]
I (as the applicant) now have this task.
