### ISSUE TITLE
PDOX- Comment for resubmit at prescreen 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1562]
unable to see applicant comments at the prescreen review - added comments when resubmitted to the county 
![image](https://user-images.githubusercontent.com/47611580/62962923-f05bbc80-bdcd-11e9-8d08-3d52295f4856.png)

**Comment by dhenry-KCI** [comment]
@ABonomo21 @JuanitaMiles - can you recreate this ticket with a new application? Talking to the trainer she said that the comments are visible to the reviewer via the _Discussion Board Plan Review _Report __ . When you recreate can be sure to save comments.

**Comment by JuanitaMiles** [comment]
We can see the comments from the applicant in the discussion comments
