### ISSUE TITLE
RESBLDG - Details page change 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1566]
![image](https://user-images.githubusercontent.com/47611580/62964165-737e1200-bdd0-11e9-997c-a1459a0c8bbf.png)

building details page has also changed -please compare detail fields
![image](https://user-images.githubusercontent.com/47611580/62964249-9dcfcf80-bdd0-11e9-98ee-36724fce5f23.png)

**Comment by dhenry-KCI** [comment]
@TaraF - do you have what you need here?

**Comment by TaraF** [comment]
@dhenry-KCI  - this is not clear on what is needed.  We were to create the report, and make sure we were pulling from the correct sources.  I am not sure what is being asked here.

**Comment by dhenry-KCI** [comment]
@TaraF - I believe we need to make the following updates:
- update domain value for Sprinkler System Field (should be new, existing,etc.)
- add fields in report under details section for Number of full bathrooms, Number of Half Bathrooms, Number of Baths Rough In

**Comment by TaraF** [comment]
The above updates / fixes have been made.

Ready for re-test.

**Comment by ABonomo21** [comment]
will check in final end to end
