### ISSUE TITLE
Liquor License - Awaiting Document Upload - Stuck in Milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1567]
The application is stuck in the awaiting document upload task in Rhythm for Civics (LI244330). The user is able to upload a document and the documents are visible in both IPS and R4C, when the applicant tries to complete the liquor license document upload task and clicks save, the system generated a Forbidden Resource Can't Be Accessed. Access is Denied Error.

**Comment by calequin** [comment]
added the detail page to the allowed monikers in r4c. fixed

**Comment by dhenry-KCI** [comment]
Resolved.
