### ISSUE TITLE
Liquor / Special Events - Type of Business

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1568]
in R4C the user selects a type of business = LLC, but IPS populates the field with a value = "None" in IPS.

**Comment by calequin** [comment]
can we monitor this? I saw the applications that were tested and it came across correctly. Please retest and add a test ap # please

**Comment by dhenry-KCI** [comment]
Closing this issue. Ashley and Penny can update the the License Description page, the applicant populates this information on the initial application. Penny and Ashley agreed this would be a nice to have but not required to go-live.
