### ISSUE TITLE
Special Events - Intake Detail Pages

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1569]
The user is able to populate the required fields and submit the application via R4C. In IPS the Intake detail page is not populating the corresponding data populated in R4C. 
EV244333

**Comment by calequin** [comment]
I have expired Special Event Details which contained the same information as special event details intake. The intake page is the information provided by the r4c applicant

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/63110293-b535c680-bf50-11e9-81b8-bf70bd3f40ff.png)

**Comment by JuanitaMiles** [comment]
The information I submitted on R4C shows in the back office. 9/23/19

![image](https://user-images.githubusercontent.com/31770504/65437905-a0bbd800-ddf2-11e9-8104-b9a338742ebd.png)
