### ISSUE TITLE
Planning-all-

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#157]
when starting an application using address in primary site field the application will not accept completeness check.

![image](https://user-images.githubusercontent.com/4129185/53659875-90f85e80-3c2a-11e9-9c56-ed1d2cc9b72b.png)

Mike Wilkins 3-1-19

**Comment by megisys** [comment]
@JuanitaMiles  - Look at Miscellaneous.. Must be recorded on a Parcel Tax ID. We said all planning application must be on Parcel

**Comment by dhenry-KCI** [comment]
Dan will automate 1 for 1

MW 3/4/19

**Comment by megisys** [comment]
Added Testing with Mike

**Comment by dhenry-KCI** [comment]
fixed
