### ISSUE TITLE
Resbldg - Under Review Status Checks - Bypass if Reviews are not All Approved

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1572]
selected resubmit in pdox and the building permit 246194 is stuck in under review becasue it is pending the issuance of the child permits but the child permit should not be a check required status until all agencies have approved 
![image](https://user-images.githubusercontent.com/47611580/63111901-c8e72a00-bf5c-11e9-863a-9745aabd821f.png)

**Comment by megisys** [comment]
This will need to be carried out for ALL building permits which go to Project Dox. This is a large effort here. And will require testing

**Comment by ABonomo21** [comment]
was this done on all a/p's to start testing ? 
dustin how do you want me to handle this one? @dhenry-KCI 
close and monitor?
