### ISSUE TITLE
R4C Grading DW - Disturbed Area

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1573]
180033

Disturbed area was submitted through Rythm with a 0. It must be 1 or more. It should not allow the applicant to save and submit with 0.

![image](https://user-images.githubusercontent.com/47611580/63112360-0ac4a000-bf5e-11e9-9a9e-fd7311fd143f.png)

8/15/19 ep

**Comment by megisys** [comment]
If you end up with no Distrurb Area then it is a resubmit.

**Comment by dhenry-KCI** [comment]
Applicant is required to populate a value.If applicant submits 0 then application would be resulted as resubmit during completeness check
