### ISSUE TITLE
Building Permits - Spawned Permits - Notify Applicant of Spawned Permits

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1576]
Currently IPS automatically spawns Grading/Driveway/Capacity permits on building permits. On rhythm the applicant will never know that these have been spawned and require action. Is there a way to notify the applicant that these permits have been created automatically along with their permit number and the associated parent permit?

![image](https://user-images.githubusercontent.com/31770504/63113503-ab1bc400-bf60-11e9-94e6-cd4c1bbf685a.png)

**Comment by dhenry-KCI** [comment]
per meeting on 8/19 - need notification that would alert the applicant to submit plans for driveway, FRO, Grading, Capacity permits that would alert the applicant that a spawned permit has been created. Will add this item to the building notification matrix.

**Comment by dhenry-KCI** [comment]
@mmbanong - stop by tomorrow and let's talk about this. WE will need notifications for spawned permits,

**Comment by megisys** [comment]
Set up for Grading

**Comment by megisys** [comment]
Set up for Driveway

**Comment by megisys** [comment]
Capacity done

**Comment by ABonomo21** [comment]
generated need to clean up lang. dan will fix will make sure it is good at final end to end

**Comment by JuanitaMiles** [comment]
When an ESD permit spawns from the Grading permit, ensure the notification sends as well.

**Comment by megisys** [comment]
ESD Permit Doesn't spawn from a GRADING. Confused here.. They are told to resubmit and create one

**Comment by megisys** [comment]
BP_GRADINGPWDR_BU - Needs Notification Added

**Comment by ABonomo21** [comment]
i have been getting notifications, of spawned permits
