### ISSUE TITLE
Planning - Site Plan Type I - DUSWM Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#158]
The system is generating an incorrect SITE PLAN TYPE I - DUSWM review fee
It should be $486 if commercial
![image](https://user-images.githubusercontent.com/4129185/53661705-f3ebf480-3c2e-11e9-81b5-0cdc9a61986d.png)
![image](https://user-images.githubusercontent.com/4129185/53662235-6c06ea00-3c30-11e9-88bd-5b273db2129c.png)

**Comment by megisys** [comment]
Paired with another Issue. This has been addressed and pointed to the right Fee Desc..

**Comment by dhenry-KCI** [comment]
fixed MW

![image](https://user-images.githubusercontent.com/4129185/53743513-fafe4700-3e68-11e9-870f-3bb861fffee1.png)

**Comment by dhenry-KCI** [comment]
correct - AReed
SP237429
