### ISSUE TITLE
PLANNING - FEES -PWCONSTRUC -  Worktype CMBDEVIMP - per sheet fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1580]
engineering per sheet fee incorrect. Should be $458/sheet pulling from the # of pages field as the calculator. Also, is should be minus 1 sheet in the formula since the first sheet is paid with initial submission.
AR

![image](https://user-images.githubusercontent.com/4129185/63171032-b1fe1180-c008-11e9-9f5b-85a9c2ba8a00.png)

**Comment by mmbanong** [comment]
Per sheet fees has been changed from 447.0 to 458.0
![image](https://user-images.githubusercontent.com/47392173/63187063-f51dac00-c02b-11e9-810a-5f56fc5328a6.png)

**Comment by dhenry-KCI** [comment]
fixed

![image](https://user-images.githubusercontent.com/4129185/63446571-739d9380-c408-11e9-8838-68ea1022ea6b.png)
