### ISSUE TITLE
PLANNING - FEES -PWCONSTRUC - Worktype REVMNIMPRV-WRONG duswm FEE

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1586]
the $162 fee should not populate on this work type.

![image](https://user-images.githubusercontent.com/4129185/63188071-76763e00-c02e-11e9-8503-dfa55e5bfa2a.png)

MW

**Comment by mmbanong** [comment]
Fees may require a formula to decide when it is charge and when it is not. Needs further discussion
![image](https://user-images.githubusercontent.com/47392173/63360347-3e2b7400-c33c-11e9-9bf3-a3810e358f20.png)

**Comment by dhenry-KCI** [comment]
PW245209 DUSWM fee corrected. AR
