### ISSUE TITLE
inspections - view (Xtreme # 13822147)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1587]
when trying to view in grid view user interface error populates

error code:  arg_targetinvocationexception

**Comment by megisys** [comment]
This means nothing to me.. I need a screen shot as a bare minimum please

**Comment by calequin** [comment]
fixed according to Rick M.

**Comment by ABonomo21** [comment]
per bob this has been corrected
