### ISSUE TITLE
PLANNING - GIS - Water/Sewer Designation - EMPTY

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1588]
W/S designation field empty
![image](https://user-images.githubusercontent.com/4129185/63188674-f7820500-c02f-11e9-9a36-0df4e3d261c6.png)

**Comment by dhenry-KCI** [comment]
14320873
01036289

![image](https://user-images.githubusercontent.com/4129185/63188793-665f5e00-c030-11e9-9b7d-6c5e5d435fd8.png)
![image](https://user-images.githubusercontent.com/4129185/63188827-8131d280-c030-11e9-862c-14f62ebed9eb.png)

**Comment by dhenry-KCI** [comment]
Following up with the GIS Team.

**Comment by dhenry-KCI** [comment]
parcel 14320873 is well and septic and won't have a water and sewer designation in the GIS as they are private. 

Parcel 01036289 is a parcel that is missing this classification. We recognized that a percentage of water and sewer data may be missing this classification as we aren't pulling the most recent DUSWM data. If the values are known, Water and Sewer Designation can be updated.

Lastly confirmed water and sewer designation is populating when the data is present  09280898

**Comment by dhenry-KCI** [comment]
GIS found that the Gp script didn't complete. Re-running and will apply update via Geoadmin.

**Comment by dhenry-KCI** [comment]
missing water/sewer designation under parcel 2345220
ar

![image](https://user-images.githubusercontent.com/4129185/63443393-b8263080-c402-11e9-97f8-6f796453bec6.png)

**Comment by dhenry-KCI** [comment]
Water/Sewer designation didn't populate. Should be W3 S3 (tax id 09-592235)
AR
![image](https://user-images.githubusercontent.com/4129185/65339327-eaf64c80-db99-11e9-8af0-dfe68c84415a.png)
Water/Sewer designation didn't populate. Should be W3 S3 (tax id 09-592234)
![image](https://user-images.githubusercontent.com/4129185/65340183-b84d5380-db9b-11e9-9401-dc2c41099496.png)

Is there still an issue with the W3/S3 designations? @dhenry-KCI

**Comment by megisys** [comment]
Duplicate
