### ISSUE TITLE
Planning - Site Plan Type I - DUSWM Review - Residential

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#159]
The system is generating an incorrect SITE PLAN TYPE I - DUSWM review fee
It should be $540 if residential
![image](https://user-images.githubusercontent.com/4129185/53662340-a8d2e100-3c30-11e9-992f-941b5de4ee45.png)
 
![image](https://user-images.githubusercontent.com/4129185/53662381-c011ce80-3c30-11e9-9f81-89f511858989.png)

**Comment by megisys** [comment]
@JuanitaMiles  what if it isn't residential ? Id it a different amount. Are we Sure these are the EXACT fees being used in Hansen 7.. Something sounds off here..

**Comment by megisys** [comment]
@JuanitaMiles - I Fixed this . This is the wrong fee adding.. Added right fee desc

**Comment by dhenry-KCI** [comment]
Fixed.  MW
