### ISSUE TITLE
inspections - passed

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1590]
when a passed inspection is completed for any grading, fro, or driveway permit that doesn't have a guarantee should get an admin review so the admin can confirm that the permit should be closed prior to just closing 

ap #1508 
tm 8/16/19

**Comment by megisys** [comment]
On these APPlication Type. WE Need Certificate of Completion as correspondence set-up on Issue Certificate Milestone

**Comment by dhenry-KCI** [comment]
ok tm 9/5/19
