### ISSUE TITLE
PLANNING - FEES -PWCONSTRUC - Worktype REVMJIMPRV-work per sheet fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1592]
must be $148

![image](https://user-images.githubusercontent.com/4129185/63190502-534e8d00-c034-11e9-9de3-93a334263fda.png)

MW

**Comment by mmbanong** [comment]
Updated fees in the Rate Table
![image](https://user-images.githubusercontent.com/47392173/63359771-4c2cc500-c33b-11e9-95c3-05368ec85ff3.png)

**Comment by dhenry-KCI** [comment]
verified corrected PW245100
AR
