### ISSUE TITLE
PLANNING - TOWN REVIEW - PWCONSTRUC

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1593]
Town review didn't transfer to PDOX
PW245084
AReed
![image](https://user-images.githubusercontent.com/4129185/63190643-a6c0db00-c034-11e9-96d9-67c5c93e3759.png)

**Comment by dhenry-KCI** [comment]
When town review didn't transfer to PDOX. First cycle never left Under review as not all reviews resulted.

**Comment by megisys** [comment]
What are we expecting here

**Comment by dhenry-KCI** [comment]
Town needs to be able to result a review. This can be achieved in IPS/R4C. We need to make sure that review doesn't cause communication issues with PDOX. 
This needs further internal discussion
AR

**Comment by dhenry-KCI** [comment]
per 10/14 meeting with everyone, using additional contacts to add towns so they get all notifications.

**Comment by dhenry-KCI** [comment]
Closing per discussion on 10/14. Town reviews will now be automatically populated based if application or permit is in a town.
