### ISSUE TITLE
Use Permit - Application Outcome Notification

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1596]
Upon progressing a Gaming Permit application to the Closed/Complete milestone, I received the Use Permit Application Outcome below.

Is this a new addition to the types of notifications being sent to the applicant? I have never seen this one until today (8/19/19). 

If it is a legitimate notification that will be going out, it is a problem that the language says that my permit has been denied. This permit (G244631) was not denied. All reviews were ultimately approved along with the RPTRCVD condition.

![image](https://user-images.githubusercontent.com/31770504/63274979-c2172a80-c26e-11e9-83e3-acb046927559.png)

**Comment by dhenry-KCI** [comment]
@megisys @JuanitaMiles  - there is a both a denied and issue permit notification template. It looks like when we hit the issue permit milestone we are sending the denied notification template. I will @mmbanong look into this.

**Comment by dhenry-KCI** [comment]
@mmbanong - if the application is denied use the denied template, if approved use the approved template.

**Comment by mmbanong** [comment]
Added code to evaluate the last review code and only send notification if not approved

![image](https://user-images.githubusercontent.com/47392173/64632487-24270380-d3c7-11e9-8e1e-4f422fa2deca.png)

**Comment by JuanitaMiles** [comment]
I am still getting the "denied" notification when reviews have been approved and the Rptrcvd has been approved.

![image](https://user-images.githubusercontent.com/31770504/65061044-12a1a680-d947-11e9-8fcd-3427d6683fd3.png)
![image](https://user-images.githubusercontent.com/31770504/65061093-2a792a80-d947-11e9-8a90-1843c5c92670.png)

**Comment by mmbanong** [comment]
The above code changes were reverted to the old formula. Is there any reason why the code was reverted? I need to know before I redo the formula

![image](https://user-images.githubusercontent.com/47392173/65152072-43d8b000-d9f5-11e9-96f3-97d7f743f757.png)

**Comment by megisys** [comment]
Duplicate
