### ISSUE TITLE
Planning-rezone-all work types

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1597]
not getting a check alert on REZONE when water/sewer classification isnt populated.  Tis resulted in DUSWM not getting a review.

![image](https://user-images.githubusercontent.com/4129185/63278921-2f7a8980-c276-11e9-9cb4-28931dc1e7b9.png)

![image](https://user-images.githubusercontent.com/4129185/63278992-41f4c300-c276-11e9-85a6-297ba0378828.png)

MW

**Comment by dhenry-KCI** [comment]
not fixed.

![image](https://user-images.githubusercontent.com/4129185/63452432-46ef7900-c414-11e9-8ee0-3c7a5ca078fc.png)

![image](https://user-images.githubusercontent.com/4129185/63452458-55d62b80-c414-11e9-9159-ef883fc26b32.png)


![image](https://user-images.githubusercontent.com/4129185/63452477-61295700-c414-11e9-901b-5d86d9a02969.png)


MW

**Comment by dhenry-KCI** [comment]
IIT updated W/S layer over weekend.  having difficulty finding a parcel that doesnt have a w/s designation.  Will monitor.   MW

**Comment by megisys** [comment]
Duplicate
