### ISSUE TITLE
License - Distributor Report - Monthly Sales Grid Requirement

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#16]
On a Distributor Report (License Module) Start License Details page:

Can we make the Monthly Sales grid require an entry? Currently you can hit save without creating a monthly sales entry. 

![image](https://user-images.githubusercontent.com/31770504/52427466-f6df4380-2acd-11e9-9e34-1d6fc463b16e.png)

**Comment by megisys** [comment]
Added Review before payment fees are generated.. So if they miss just resubmit..

**Comment by dhenry-KCI** [comment]
Did not work during retest, still allowed me to save the report without any data being added to the monthly sales grid. - AB 2.11.19
DR235685

**Comment by megisys** [comment]
@dhenry-KCI . This is not possible - If they submit with no grid lines - Then kick it back as a resubmit.. I can not make grids required.

**Comment by JuanitaMiles** [comment]
Duplicate of #54
