### ISSUE TITLE
planning-pwconstruct-CMBDEVIMP-not getting per sheet fee notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1601]
didnt get email about paying per sheet fee

![image](https://user-images.githubusercontent.com/4129185/63446886-00e0e800-c409-11e9-8965-624c77bc47b0.png)

MW

**Comment by megisys** [comment]
Add this to the notification Matrix please.

**Comment by dhenry-KCI** [comment]
added to planning notification matrix #1521 . Closing this ticket
