### ISSUE TITLE
Building Permits - RESBLDG - Permit Issued Report Correspondence Not Generating

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1612]
We are not getting the Building Permit Official Issuance report correspondence as an email. They are also not attaching to the application in IPS or R4C. I manually ran the batch manager to be sure that wasn't the issue.

**Comment by mmbanong** [comment]
The correspondence seems to be tied up in the below error. Dan can you provide some guidance


![correspondence error](https://user-images.githubusercontent.com/47392173/63939719-ed033a80-ca35-11e9-9821-7c19fb37bb36.PNG)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/64729389-0df27380-d4ab-11e9-99c9-7e760ba18da7.png)

did not get a notification for an issued permit. 
permit 246644

**Comment by calequin** [comment]
fixed. notifcation was expired.

**Comment by JuanitaMiles** [comment]
I received both the Correspondence and the Notification of Permit Issuance. Ultimately these two items should be combined. I believe the text of the notification should be added to the body of the correspondence email.

@dhenry-KCI - I'm not sure who is handling this..

**Comment by dhenry-KCI** [comment]
@mmbanong - similar to comment on other ticket's at permit issuance we should only get CM, notification laguage should be included in body of email.

**Comment by mmbanong** [comment]
Combining the notification language in th correspondence email may require further discussions

The verbage on the notifications contains module and AP type specific values returned by the business objects. Incorporating that into the body of an email needs further discussions may be with Dan

**Comment by dhenry-KCI** [comment]
@mmbanong - apply same logic you use for other CM reports.

**Comment by mmbanong** [comment]
There is no current logic that combines correspondence reports and notification. I think further discussion is required. We have an of the correspondence or the notification but not both unless we come up with a way to incorporate AP type specific values returned by the business objects into the body of the correspondence email

**Comment by dhenry-KCI** [comment]
@mmbanong - this is an SSRS template that would define the email body. Leverage infomration provided by Tara on 10/1 and 10/2 to complete.

**Comment by megisys** [comment]
Closing Keeping this as 2 emails
