### ISSUE TITLE
Pending Certificate Review- Result Options

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1614]
is it possible to add a denied or a hold option for pending certificate review that will trigger a notification to the applicant
we often deny COO's or COC's for other tasks to be complete i.e. if this is a child apartment unit to a parent apartment building the COO cannot be issued until the parent COC is issued and the pending certificate review would go on hold (currently in hansen it goes in as denied)

![image](https://user-images.githubusercontent.com/47611580/63705540-606d3800-c7fb-11e9-84cb-ccf7a0a84465.png)

**Comment by ABonomo21** [comment]
we would not call or email, i would like to have a denied or a hold result for this milestone. We often put holds at these reviews now with instructions to the applicant to for example change a sales office back to a garage. i would like them to be notified based on the comments.

**Comment by megisys** [comment]
New Notification Created and Result of ONHOLD Created.. Please test this out.

**Comment by ABonomo21** [comment]
thank you... 
![image](https://user-images.githubusercontent.com/47611580/65544004-5b75d400-dee0-11e9-9139-997ba71dd94a.png)
allowed me to add comments and generated a second review so we can see outstanding items this is perfect
![image](https://user-images.githubusercontent.com/47611580/65544099-8eb86300-dee0-11e9-8015-c523585c59d8.png)
