### ISSUE TITLE
PLANNING - SITE PLAN - REVIEW RESULTS

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#162]
Site Plan Review Results - need to narrow to correct results

![image](https://user-images.githubusercontent.com/4129185/53665038-4847a200-3c38-11e9-9377-2aa4a2dd730d.png)
![image](https://user-images.githubusercontent.com/4129185/53665083-6c0ae800-3c38-11e9-932b-8437e9f9b28d.png)

**Comment by dhenry-KCI** [comment]
New issue logged by AReed

**Comment by JuanitaMiles** [comment]
Which review were you trying to result? If you were completing a bulk result of many reviews at once, it has been a known issue that the result codes do not filter properly across all APs/Modules. 

Infor can indicate if there has been any new information on resolving this item. @megisys

**Comment by megisys** [comment]
@dhenry-KCI  @JuanitaMiles Hi Dustin. If they bulk select this is standard functionality..  In Real life no one results multiple reviews at once.

Dan

**Comment by dhenry-KCI** [comment]
Occurring on single reviews under site

**Comment by dhenry-KCI** [comment]
resolved with Dan on site - AReed

**Comment by dhenry-KCI** [comment]
Occurring on Site Plan Review under Signature Review - only Signature Review selected
![image](https://user-images.githubusercontent.com/4129185/54535339-b98b9280-4964-11e9-886d-f7a7a0d07b03.png)
![image](https://user-images.githubusercontent.com/4129185/54535368-c7411800-4964-11e9-974f-4cc6cb1ca1a0.png)

**Comment by dhenry-KCI** [comment]
SP237796 see PWDR review vs. signature set review options. Remove denied from Signature review
![image](https://user-images.githubusercontent.com/4129185/54628934-e74c0680-4a4c-11e9-81c0-e98326f4da94.png)
![image](https://user-images.githubusercontent.com/4129185/54629447-f7b0b100-4a4d-11e9-9f7b-dd8651531f48.png)
AREED

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
fixed per SP238917  MW
