### ISSUE TITLE
PLANNING/BUILDING R4C Map Feature - ERROR (Xtreme 13846241 Excel Issue #72)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1624]
When using MAP feature to select the parcel with the tax ID in R4C, it errors out and says "Frederick County doesn't accept this type of Application for this Parcel"

AR

![image](https://user-images.githubusercontent.com/4129185/63711741-1b043700-c80a-11e9-845e-4fa6fc00b049.png)
![image](https://user-images.githubusercontent.com/4129185/63711779-34a57e80-c80a-11e9-8711-5030c22487d0.png)

**Comment by calequin** [comment]
Infor JIRA Ticket created HPS-106082

**Comment by calequin** [comment]
validated as an issue with Dev. in progress.

**Comment by dhenry-KCI** [comment]
not fixed.  R4C application on 12401 Glissans Mill Rd but IPS says its Pioneer Cir.
![image](https://user-images.githubusercontent.com/4129185/67037575-c3889600-f0eb-11e9-82a6-9ba8c3aa9cbd.png)
![image](https://user-images.githubusercontent.com/4129185/67037589-cc796780-f0eb-11e9-8205-6b74de28b4a2.png)


MW

**Comment by dhenry-KCI** [comment]
Looked up parcel on Map feature and only listed once. However, when trying to submit it says ADDRESS IS NOT A VALID RECORD.
AR
![image](https://user-images.githubusercontent.com/4129185/68217753-2796cf80-ffb1-11e9-8205-0fab8cf4b72f.png)
![image](https://user-images.githubusercontent.com/4129185/68217800-4006ea00-ffb1-11e9-91be-50b051654eaf.png)
When I put it in under the parcel it worked SP252183 but it gave me the wrong city and zip code. It should be mt airy 21771 and it came up Union Bridge 21791. AR
![image](https://user-images.githubusercontent.com/4129185/68219446-ff5ca000-ffb3-11e9-8992-d28df1991371.png)

**Comment by dhenry-KCI** [comment]
Address is not a valid record
11671 Baldwin Rd E
![image](https://user-images.githubusercontent.com/4129185/68233754-d517dc00-ffcd-11e9-838c-37ea1c942526.png)

**Comment by ABonomo21** [comment]
#2063 linked will need to check once addresses are fixed
