### ISSUE TITLE
Building - Capacity Permit - Spawned Capacity Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#163]
The system should only spawn a capacity permit when water designation =W1 or W3 or W4 or W5 OR Sewer designation = S1 OR S3 or S4 or S5

**Comment by megisys** [comment]
@dhenry-KCI - These detail are on the parcel. Building permits are against addresses.. Maybe we have a check box on Building - saying Capacity needed ?? Thoughts

**Comment by dhenry-KCI** [comment]
Per discussion with Dan will add formula to relate address to parcel record for those instance with a 1:1 relationship. If two parcels will add capacity permit.

**Comment by dhenry-KCI** [comment]
Confirmed capacity permits are spwning as designed.
