### ISSUE TITLE
Building Permits - ADU - COO Report Correspondence

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1630]
We are not receiving the Certificate of Occupancy - Res, NonRes, & All AP Types report correspondence. We were testing Accessory Dwelling Unit Residential Building Permits.

**Comment by dhenry-KCI** [comment]
Seeing a COO CM in the Correspondence Schedule, closing this ticket as its related to larger CM release issue.
