### ISSUE TITLE
Building Permits - On Demand Reports - Certificate Reports not Launching

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1631]
The **Certificate of Occupancy - Res, Nonres, & All AP Types** and **Certificate of Completion Res, NonRes, All AP Types** is not launching in IPS using Chrome.

![image](https://user-images.githubusercontent.com/31770504/63775621-b4385980-c8ad-11e9-814a-d1441663b344.png)

![image](https://user-images.githubusercontent.com/31770504/63775910-56f0d800-c8ae-11e9-8d71-f510dca1bbce.png)

**Comment by TaraF** [comment]
@JuanitaMiles @dhenry-KCI  - Those reports shouldn't even be showing up now.  It was removed and replaced with "Certificate of Occupancy / Completion - Res, NonRes & All AP Types":

**Comment by dhenry-KCI** [comment]
This is a duplicate of #1411 - closing
