### ISSUE TITLE
Preliminary Plat- incorrect Health Department fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#164]
PP237448
Generated a single $25 per lot fee for Health but this application has 30 lots.  Per lot fee should be $25 x 30
![image](https://user-images.githubusercontent.com/4129185/53753883-6273c100-3e80-11e9-8490-77f1b63b9d35.png)

![image](https://user-images.githubusercontent.com/4129185/53753932-7b7c7200-3e80-11e9-9969-a6350b8d1518.png)

**Comment by dhenry-KCI** [comment]
EDIT: this AP was created using wells but public sewer, so the # of septic lots should be zero, in which case there should not be a per-lot fee for the health department

**Comment by megisys** [comment]
What happens if someone fills out both boxes.. What do I do then. Add then or just take the largest number ??

**Comment by dhenry-KCI** [comment]
the HD fee is generated only from the # of septic lots field. $25 per lot.

**Comment by dhenry-KCI** [comment]
Corrected on PrePlat and PLAT COMBO 
Tested with and without lots
AREED
