### ISSUE TITLE
R4C-All Applicant Actions Revision Comments HTML Tags (XTREME TICKET #13846198 Excel Issue #71)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1641]
HTML Tags Are showing up in Rhythm

**Comment by calequin** [comment]
Infor JIRA Ticket created HPS-106083

**Comment by calequin** [comment]
need to change each county comments box to a label and add the "setinnerhtml" box = Yes. Update on 19.11 with a fix for r4c.

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/69190395-ef7da980-0ae5-11ea-8811-66486e404510.png)
