### ISSUE TITLE
Res Building - Parent / Child - Townhouse, Condo, Apt

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1643]
based on discussion on 08/27, apartment, townhouses and condos will follow the workflow below:

Townhouse
•	Applicant must submit each Townhouse and associated Unit through Rhythm
•	The Initial and Each unit will be resulted at completeness check as e-plan review
•	Parent / children must be issued together
•	The Initial and Each unit will progress to pending issuance
•	Nightly batch job will run that will progress all units from pending issuance to issuance. 
Apartments / Condos
•	Applicant must submit each apartment / condo through Rhythm
•	Parent unit will be resulted as an e-plan review
•	Child units will be resulted as internal review 
•	Child units will be treated as tenant fit-outs and resulted in IPS
2 over 2 (Res Condo)
•	Applicant must submit each unit through Rhythm as well as parent site plan
•	Parent unit will be resulted at completeness check as e-plan review
•	Each child unit will be resulted at completeness check as e-plan review
•	All reviews performed in PDox

**Comment by megisys** [comment]
I need a refresher on this one. I lost all memory of what we are trying to achieve in fine detail. I know we want to release everything as a batch. So Parent cant go on a TownHouses until all child permits are pending issuance. child permits cant move until parent structure at pending issuance
