### ISSUE TITLE
Building - Driveway - Related Plat Records

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#165]
The system is requiring that a plat plan must be related to the driveway apron where primary residential entrance apron was checked. 

The system should only require a plat plan be related to the driveway apron where common entrance apron is checked. 

AP # 238491

Logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
Ready for Test..

**Comment by dhenry-KCI** [comment]
item has been corrected

tiffany martin 3/5/19
