### ISSUE TITLE
PLANNING - PWCONSTRUC - per page fee notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1656]
We need a notification after the first review cycle when the per sheet fee is owed on PWCONSTRUC. I only want this to send when fees are owed.  AR

![image](https://user-images.githubusercontent.com/4129185/63869504-3c8a2d80-c986-11e9-8086-c4e52c713080.png)
![image](https://user-images.githubusercontent.com/4129185/63869694-94c12f80-c986-11e9-9a72-dd81730b0428.png)

**Comment by calequin** [comment]
need meeting with AReed on this one. @dhenry-KCI

**Comment by dhenry-KCI** [comment]
verified email received on PW245382

**Comment by calequin** [comment]
fixed. one fees per page notification will send out and one more information required notification will send out

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/64726190-b8fb3100-d49b-11e9-974e-f654354ca277.png)

**Comment by dhenry-KCI** [comment]
Emails not being received in email when project is going through PDOX. AR
PW245398

![image](https://user-images.githubusercontent.com/4129185/64728396-daaee500-d4a8-11e9-9416-0021971703d7.png)

**Comment by megisys** [comment]
Ashley Lets Test this tomorrow please together

**Comment by dhenry-KCI** [comment]
Verified email is going to web services. Ok to close. AREED
