### ISSUE TITLE
PLANNING - PDOCS - Initial notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1657]
We need the initial notification to provide more instruction to the applicant that they need to upload plans in PDOX. The second screen shot, which is for a resubmit provides helpful details to the applicant about what is needed.
AR
![image](https://user-images.githubusercontent.com/4129185/63870540-28473000-c988-11e9-88bc-13928b6f2089.png)
![image](https://user-images.githubusercontent.com/4129185/63870692-73f9d980-c988-11e9-87db-e5abf97c839a.png)

**Comment by RS-Avolve** [comment]
After taking a closer look at this request, I think it would be better to add the clarifying language about uploading documents to the Applicant Upload task.  The invitation email just tells the user they have been invited to the project,  The Applicant Upload email task can take the user directly to the project through the "Project Access" hyperlink.  The Invitation email does not have this link.  I have included a copy of the Applicant Upload email.  Please take a look and let me know what words you want me to add to provide the direction for the customer.  Thanks.

**Comment by RS-Avolve** [comment]
![Screenshot - Frederick County 1657 ticket](https://user-images.githubusercontent.com/53225350/67051426-457ebc00-f0f8-11e9-9c17-fa9d9a954bb3.PNG)

**Comment by dhenry-KCI** [comment]
looks good.

MW

**Comment by RS-Avolve** [comment]
Hi, just a verification that the Applicant Upload email, as shown above, is good as it is and that it does not need wording modification.  Thanks.
