### ISSUE TITLE
Building - Driveway - Bond Required

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#166]
The system did not require a bond to be posted prior to issuance.  The Driveway Intake details were completed as bond required but no bond review populated or was required prior to issuance and the permit went to inspections. 

The system should have had a bond review or a check to see if a bond has been posted prior to issuance since the driveway intake details stated that a bond was required. 

AP # 238491

Logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
This is Addressed

**Comment by dhenry-KCI** [comment]
this has been confirmed.

tiffany martin 3/5/19
