### ISSUE TITLE
Resbldg- Unit Number Check 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1665]
for apartments At completeness check there should be a status check like condo's that makes sure the number of units indicated on the details tab are related as child applications. 

![image](https://user-images.githubusercontent.com/47611580/63884689-a7e2f800-c9a4-11e9-83ae-5b048487cb24.png)

![image](https://user-images.githubusercontent.com/47611580/63884718-b6c9aa80-c9a4-11e9-981f-40b07b9eae0f.png)

**Comment by JuanitaMiles** [comment]
The Parent Apartment application gets a status check during Completeness Check saying that the Number of Units doesn't match the number of Related Records. BUT...
![image](https://user-images.githubusercontent.com/31770504/64289140-aaf46000-cf31-11e9-9623-7152fadb703a.png)

The Parent Condo application does not get a status check during Completeness Check.
![image](https://user-images.githubusercontent.com/31770504/64289283-04f52580-cf32-11e9-8443-1d8c97687582.png)

**Comment by JuanitaMiles** [comment]
fixed on condo

![image](https://user-images.githubusercontent.com/31770504/64358112-d3cd3180-cfd3-11e9-8811-8a1a1155c30c.png)
