### ISSUE TITLE
Building Permits - RESBLDG - Duplicating Driveway Child Permit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1667]
The Driveway child permit is continuously adding every time we enter Under Review. It should only add once.

![image](https://user-images.githubusercontent.com/31770504/63887674-4bcfa200-c9ab-11e9-95b2-eeb1d5cb531e.png)

**Comment by ABonomo21** [comment]
entered under review 2 times and it did not generate another driveway permit 

fixed 9.5.19 ab 
![image](https://user-images.githubusercontent.com/47611580/64360289-2c9ec900-cfd8-11e9-92f9-25181f00d105.png)
