### ISSUE TITLE
Building Permits - RESUSE - Detail Page "Rooms" Grid on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1668]
The Add Row portion of the Addition/Alteration Details section on the details page is very awkward/confusing. There is no indication of what I should being adding rows of or that there is even a grid there at all. It seems like a random button. This is the New Room / Existing Room grid from the back office.

![image](https://user-images.githubusercontent.com/31770504/63902750-df6b9780-c9d8-11e9-8aaa-7416ac659746.png)

![image](https://user-images.githubusercontent.com/31770504/63902801-1477ea00-c9d9-11e9-8106-be3b3b69d736.png)

**Comment by calequin** [comment]
added verbiage
![image](https://user-images.githubusercontent.com/47603568/64201404-3e576380-ce54-11e9-8174-79d39dc3a9ee.png)

**Comment by ABonomo21** [comment]
while the verbiage is good, the grid is not for a new construction. the grid is for alterations/room type changes-aw
![image](https://user-images.githubusercontent.com/47611580/64202786-f3434d80-ce5f-11e9-81d6-128982808efd.png)

**Comment by calequin** [comment]
fixed verbiage

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/64371791-747d1a80-cfef-11e9-9b1b-cc036f00cb70.png)
