### ISSUE TITLE
Building Permits - RESUSE - R4C Not Accepting Application in a Town

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1669]
I tried to submit an application for an address in Middletown and R4C will not accept it.

![image](https://user-images.githubusercontent.com/31770504/63903511-c3b5c080-c9db-11e9-8750-ce91544f9873.png)

![image](https://user-images.githubusercontent.com/31770504/63903540-db8d4480-c9db-11e9-9406-bda484d6c863.png)

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
failed not working related to issue #1708

**Comment by calequin** [comment]
see comment on #1708

**Comment by ABonomo21** [comment]
was abel to submit 
![image](https://user-images.githubusercontent.com/47611580/64359516-78507300-cfd6-11e9-9bf0-d1be5f86fbc4.png)
9.5.19 ab
