### ISSUE TITLE
Building - Driveway - Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#167]
The system did not generate an ECSLegalPckg when it previously did. If placard is going to be sent automatically to the applicant - then this is not needed. However, if we are going to manually be sending these - the ECSLegalPCkg needs to populate. I am almost certain that this populated previously during testing. The permit went straight to inspections. 

The system should generate ECSLegalPckg if a placard needs to be sent by us, manually. 

AP # 238491

Logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
This is a Correspondence Request.. To Have Placards Send as a report..  at  the Pending issuance..

**Comment by megisys** [comment]
@dhenry-KCI - Need to add to report Piece. I have added the connector in See Logs
![image](https://user-images.githubusercontent.com/47392306/53770206-47b74180-3eac-11e9-8676-80315ce07ace.png)

**Comment by dhenry-KCI** [comment]
@TaraF - add this issue to our reporting repo for Gerry to address.

**Comment by dhenry-KCI** [comment]
Closing - logged with reporting.
