### ISSUE TITLE
Use-Temp Outdoor Activity-Health Review did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1671]
#L244651- the sanitation type is Portable so the Environmental Heath Review should have generated. the fee generated but the review did not. -aw
![image](https://user-images.githubusercontent.com/47611580/63947042-38244a00-ca44-11e9-831b-172589a84f70.png)
![image](https://user-images.githubusercontent.com/47611580/63947059-41151b80-ca44-11e9-9ace-d53352f517fe.png)

**Comment by calequin** [comment]
Fixed in dev

**Comment by JuanitaMiles** [comment]
EH review generated
![image](https://user-images.githubusercontent.com/31770504/65076644-66bc8300-d967-11e9-8ba3-bff8763c19cb.png)
