### ISSUE TITLE
Use-Temp Outdoor Activity-Follow up inspection did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1672]
#L244651-after passing the first building and fire inspections. the permit automatically issued and then closed. The BLDG Follow up inspection needs to generate before the permit closes.-aw
![image](https://user-images.githubusercontent.com/47611580/63947855-b2a19980-ca45-11e9-81d8-fc12910c59ca.png)
![image](https://user-images.githubusercontent.com/47611580/63947915-ccdb7780-ca45-11e9-8675-95543a5a4246.png)

**Comment by calequin** [comment]
currently the bldg followup only happens if the Temp construction structure is checked off on the intake form. This application does not have it checked therefore it did not load.

![image](https://user-images.githubusercontent.com/47603568/64200474-38608300-ce52-11e9-882a-dc735951fa6b.png)

**Comment by ABonomo21** [comment]
fixed confirmed 9.4.19 ab 
Perfect- should only generate if the temp construction structure tested and works 
![image](https://user-images.githubusercontent.com/47611580/64258574-7e225780-cef5-11e9-82de-b95c2c98ce8c.png)
![image](https://user-images.githubusercontent.com/47611580/64258613-8d090a00-cef5-11e9-8a66-b61b7d5b92ed.png)
