### ISSUE TITLE
Planning-FRO notification-mitigation required

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1673]
Dan worked on this on 8/28.  tested 8/29 and the email didnt come through. See F245206

![image](https://user-images.githubusercontent.com/4129185/63948000-f1375400-ca45-11e9-92d9-bc2865450160.png)

MW

**Comment by dhenry-KCI** [comment]
Added to 1535 - Closed this ticket

**Comment by calequin** [comment]
planning mitigation notification and planning fees successfully received upon entering the admin closure milestone.
![image](https://user-images.githubusercontent.com/47603568/64459416-6f869c80-d0bd-11e9-8a3c-9de85f0ce88f.png)
![image](https://user-images.githubusercontent.com/47603568/64459441-7f05e580-d0bd-11e9-9b57-3222b3e6830e.png)
![image](https://user-images.githubusercontent.com/47603568/64459461-89c07a80-d0bd-11e9-9b56-c4c1a1419ca1.png)

**Comment by dhenry-KCI** [comment]
works, change "out" to "our

MW

**Comment by calequin** [comment]
fixed verbaige

**Comment by dhenry-KCI** [comment]
email doesn't have project ID information on it. AR
![image](https://user-images.githubusercontent.com/4129185/65153165-46d4a000-d9f7-11e9-95f4-1360b2853329.png)

**Comment by dhenry-KCI** [comment]
This isn't what I had in mind. Please make it look like the other notifications. Please incorporate it into the message.
AReed
![image](https://user-images.githubusercontent.com/4129185/65171709-7f857100-da19-11e9-93cb-2baba3a1be5c.png)

![image](https://user-images.githubusercontent.com/4129185/65171873-de4aea80-da19-11e9-82d1-2f5ca0fe7ad2.png)

**Comment by dhenry-KCI** [comment]
change "permit" to application.  This isnt a permit.

![image](https://user-images.githubusercontent.com/4129185/65699594-53d33e00-e04c-11e9-822f-1018d6d0f9f2.png)

MW

**Comment by mmbanong** [comment]
Changed permit to application
![image](https://user-images.githubusercontent.com/47392173/66589096-cb7c8f00-eb5b-11e9-8edb-1a8e54425c11.png)

**Comment by dhenry-KCI** [comment]
wasnt fixed.  Juanita had to fixed it.

however, the mitigation information that the notification says to find on R4C isnt on R4C.

![image](https://user-images.githubusercontent.com/4129185/66854838-1f1e1c80-ef50-11e9-9f28-31fa2420543a.png)
