### ISSUE TITLE
fro inspections

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1674]
#246238 passed install inspection and it generated a final inspection instead of a periodic inspection. We worked through the process previously of what was required for 2 year and 3 year FRo permits.

**Comment by calequin** [comment]
FRO-PERIOD was expired. I unexpired the inspection type and added it to the final inspection milestonwe.

**Comment by dhenry-KCI** [comment]
For 3 Year Fipa- 2 FRO Periodic Inspections should generate- automatically
For 2 Year Fipa- 1 FRO Periodic Inspections should generate - automatically
this is in addition to the FRO Final (this is correct)

246490- is a 3 year- only one FRO periodic generated

9/4/19 ep/tm

**Comment by dhenry-KCI** [comment]
tm ep 9/5/19 ok
