### ISSUE TITLE
COO and COC report

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1677]
![image](https://user-images.githubusercontent.com/47611580/63950580-42494700-ca4a-11e9-93c2-1d42a8aed14d.png)

Formatting in general does not look good. some details are capitalized and some are not. - old applications because of formatting in hansen everything was capitalized we need to be able to make the report look clean for both new and old data- potentially, need to have everything converted to be capitalized. **Everything appears to be squished up at the top of the report.** please compare the spacing on the old reports to the new reports that are generating. 

missing the zoning use and special stipulations- **these can be found under the application details** these fields were previously automatically generated field on our original coo and coc

data is not pulling the sprinkler system required and installed. 
**for current application the sprinkler detail can be found on the building details page under sprinkler system- it will generate as new/existing/ not applicable 
the old system only had yes or no**

![image](https://user-images.githubusercontent.com/47611580/63950789-a4a24780-ca4a-11e9-888b-878255180761.png)

**the sprinkler installed need to be pulled from the related records tab to see if there was a sprinkler fire suppression permit issued and final under.** 
![image](https://user-images.githubusercontent.com/47611580/63950811-af5cdc80-ca4a-11e9-9fb5-eee3bc41e636.png)

![image](https://user-images.githubusercontent.com/47611580/63950836-b97edb00-ca4a-11e9-9293-4d83cbba4875.png)

**Comment by ABonomo21** [comment]
see #1137 for when the details are required to print on COO COC reports 

added comments above for more clarification!

**Comment by gerrykelly** [comment]
@TaraF @dhenry-KCI 

I'm dropping my assignment here.  Some (most?) of this has already addressed in:
https://github.com/kcigeospatial/fredCo_landMgt/issues/22

Still-needed updates need to be more explicitly defined and I'll look for that info when the related info in the other repo is assigned back to me

**Comment by TaraF** [comment]
Ready for re-test.

Please note the following:

1) Zoning Use is only available for COO/COC NonRes reports, as per the samples we were given, where data is available in IPS.

2) Special Stipulations has been updated to reflect the details page, but please note this is the odd data issue on the INFOR DB side noted here https://github.com/kcigeospatial/fredCo_landMgt/issues/22

3) Sprinkler System / Installed has been updated as specified above.

**Comment by ABonomo21** [comment]
Thank you for the fixes will do a final test with juanita - during report testing and will re-open if needed
