### ISSUE TITLE
planning-plat-fee notify-didnt send

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1678]
didnt get fee notification

![image](https://user-images.githubusercontent.com/4129185/63951141-37db7d00-ca4b-11e9-8d46-d32be6486947.png)

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/63953121-b980da00-ca4e-11e9-9cf1-17eeb7258d58.png)

**Comment by megisys** [comment]
Formula was expired.

**Comment by dhenry-KCI** [comment]
got it.

![image](https://user-images.githubusercontent.com/4129185/64175412-3cc47600-ce29-11e9-9768-1d5b96925178.png)
