### ISSUE TITLE
Resuse- Detail page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1679]
please remove the occupancy load detail page from resuse permits 
![image](https://user-images.githubusercontent.com/47611580/63951388-a4ef1280-ca4b-11e9-92c7-27e94d0fc78c.png)

**Comment by calequin** [comment]
expired occupancy load details

**Comment by ABonomo21** [comment]
fixed confirmed 9.4.19 ab 
![image](https://user-images.githubusercontent.com/47611580/64258316-06542d00-cef5-11e9-92ba-96996d9a89af.png)
