### ISSUE TITLE
Planning - Verification Letters - Spelling Error - A/P# VP237450

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#168]
![spell error](https://user-images.githubusercontent.com/4129185/53755826-81288680-3e85-11e9-948b-21978481229c.PNG)
Verification is misspelled in the Verification Review

**Comment by mmbanong** [comment]
Spelling Error has been corrected

**Comment by mmbanong** [comment]
Spelling Error fixed

**Comment by dhenry-KCI** [comment]
![verification spell error fixed](https://user-images.githubusercontent.com/4129185/53835145-bf43aa00-3f5a-11e9-831a-9e74b8de2ad2.PNG)
Fixed
