### ISSUE TITLE
Building Permits - RESUSE - R4C Applicant Resubmit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1680]
Please remove the arrow icons in the "Please fill out applicant actions" sentence.

![image](https://user-images.githubusercontent.com/31770504/63951475-cfd96680-ca4b-11e9-94f7-9561c5b805de.png)

**Comment by calequin** [comment]
fixed the status check hyperlink arrows. The html code in the comments is being worked on another ticket

**Comment by ABonomo21** [comment]
hyperlink arrows are fixed-aw
![image](https://user-images.githubusercontent.com/47611580/64257823-13bce780-cef4-11e9-9396-0eae548df41b.png)
