### ISSUE TITLE
Building Permits - RESUSE - R4C Applicant Actions Comments

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1681]
Please remove the code <br> stuff within the Applicant Actions review comments.

![image](https://user-images.githubusercontent.com/31770504/63951588-057e4f80-ca4c-11e9-8c0e-0d3ab75d70c6.png)

**Comment by megisys** [comment]
Duplicate. I have this as a ticket already..
