### ISSUE TITLE
grading - swm permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1683]
ap 246358

the stormwater subcategory should be a required field by us at the dre-cost est review or at the under review milestone for vijay to complete. logging this in case i am not here to confirm this.

tm 8/29/19

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - discuss during tomorrow's session. If a bug, change label.

**Comment by JuanitaMiles** [comment]
SWM Permits - Apply this requirement for Vijay or Eric to complete.

**Comment by ABonomo21** [comment]
this needs to be in our SOP for Vijay to complete at his review. swm sub category is populating as a red line under intake review. 

tm 9/19/19 - ap 246773
