### ISSUE TITLE
grading - swm inspectino fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1684]
ap 246358

inspection fee seems to be inaccurate - 47.13 - however, i calculated 48.18 which is 2.75% of 1,752.03

![image](https://user-images.githubusercontent.com/4129185/63953964-5132f800-ca50-11e9-87e9-fb7dcb0ad90f.png)
 
tm /ep 8/29/19

**Comment by mmbanong** [comment]
Value of custom variable needs to be updated
![image](https://user-images.githubusercontent.com/47392173/64282010-6f05ce80-cf22-11e9-9bf2-db41ac6a4769.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - please update in test.

**Comment by mmbanong** [comment]
Updated in Test

![image](https://user-images.githubusercontent.com/47392173/65063459-492df000-d94c-11e9-8530-67b6efa9b1f5.png)

**Comment by ABonomo21** [comment]
corrected tm 9/19/19 ap 246772
