### ISSUE TITLE
Building - Minor Grading - Related Records

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#169]
The system is holding up the permit from issuing due to a building permit must be listed as a parent.

The system should not require a building permit as a related record in all cases of a minor grading permit. The applicant can come in and the grading not be associated with a new house requiring a building permit to be listed as a parent. 

AP # 238494

logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
No Building Permit needed for WorkType = MN


if oBldgApp.WorkType.Code = "MN" then

StateCheck = False

End if

**Comment by dhenry-KCI** [comment]
This is still not working correctly. The permit is being held up at pending issuance milestone for building permit must be listed as a parent. However, a building permit is not always required to be attached or linked with a minor grading permit.

AP # 238568

tiffany martin 3/5/19

**Comment by megisys** [comment]
How would you like this to work .. @dhenry-KCI  ?

**Comment by dhenry-KCI** [comment]
Confirmed fixed by TM on 3/14/2019
