### ISSUE TITLE
Building Permits - RESUSE - Inspections Not Auto-Assigning

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1690]
The inspections for this RESUSE - Alteration permit did not automatically assign the inspector.

![image](https://user-images.githubusercontent.com/31770504/63957705-eb963a00-ca56-11e9-949d-e592ab4749a9.png)

**Comment by mmbanong** [comment]
We have a couple of problems here
1. The assigned election district 0034 is not one of the current assignment areas
2. RESUSE-Residential BLDG does not have any inspection assignments
![image](https://user-images.githubusercontent.com/47392173/63959887-3a45d300-ca5b-11e9-8712-661d83ebd26f.png)

![image](https://user-images.githubusercontent.com/47392173/63959931-56497480-ca5b-11e9-8489-76ed5645ad8e.png)

**Comment by dhenry-KCI** [comment]
@megisys - see issue

**Comment by megisys** [comment]
We use Area field on the address. that is what electoral district is looking at. Parcel are for planning. so the entry is 11.

**Comment by mmbanong** [comment]
RESUSE-Residential BLDG does not have any inspection assignments. Do you want me to populate the inspector assignments as assigned in RESBLDG?
Can you identify other building application types that required inspector assignments so we can tackle this as a single ticket?

**Comment by dhenry-KCI** [comment]
@mmbanong - every inspection type in building needs to have the same inspection setup.

**Comment by mmbanong** [comment]
I will move the scheduled inspections for the highlighted types from RESBLDG to RESUSES

The others will require inspector assignment definitions from ECS, OLS and ZONING per Bob

![image](https://user-images.githubusercontent.com/47392173/65168378-5dd4bb80-da12-11e9-9173-ba9f765647fe.png)

**Comment by mmbanong** [comment]
Inspection assignments are now complete for all Building AP Types that are effective

**Comment by ABonomo21** [comment]
you need to double check all inspection - a footing inspection on a resuse test permit was not auto assigned 
![image](https://user-images.githubusercontent.com/47611580/65993368-1e20c180-e45f-11e9-88e4-6a8f16d19b4f.png)

**Comment by mmbanong** [comment]
Footing inspections are assigned for resuse. please take a look and me know what is missing so I can make the assignment update.

![image](https://user-images.githubusercontent.com/47392173/65994392-2bd74680-e461-11e9-8fc6-54f70734986c.png)

**Comment by JuanitaMiles** [comment]
Footing Inspection is now auto-assigned.

![image](https://user-images.githubusercontent.com/31770504/66053735-d8b4d080-e500-11e9-8186-5254713f98fa.png)
