### ISSUE TITLE
grading permit - structural/non structural - esd

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1691]
on a grading permit - the PWDR review needs the ability to determine if the esd is structural or not. there should be a checkbox for structural and non structural  - if the structural box is checked then we need a swmesd permit to spawn from the grading permit. if the non structural box is checked then only a inspection needs to populate not an additional permit - swm final inspection.

**Comment by megisys** [comment]
SOP of the PWDR Review.

**Comment by megisys** [comment]
APPROVEDS and APPROVEDNS added - if APPROVEDS then it will spawn a Child Grading SWM

**Comment by dhenry-KCI** [comment]
good to go  tm 9/4/19
