### ISSUE TITLE
ResBldg-SFD details page-driveway options dupicate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1693]
there are duplicate options on the details page for drive way options.-aw
![image](https://user-images.githubusercontent.com/47611580/63961452-d6250e00-ca5e-11e9-9975-cefa450847f0.png)

**Comment by megisys** [comment]
Not Duplicate.. The H7 is showing the old Hansen 7 way of inputting. The one above is the new method for Rhythm

**Comment by ABonomo21** [comment]
the historic will only come up back office
