### ISSUE TITLE
ResBldg-Sfd-incorrect fee

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1695]
the fee for a single family dwelling over 6500 square feet is incorrect. it should be the current FY2020 fee of $1276 -aw
![image](https://user-images.githubusercontent.com/47611580/63962807-94e22d80-ca61-11e9-8034-d30c24c450a6.png)
![image](https://user-images.githubusercontent.com/47611580/63962826-a4fa0d00-ca61-11e9-84ce-fbf9ec1ee8a6.png)

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/64283130-d4f35580-cf24-11e9-85f3-0045de3f31c8.png)

**Comment by ABonomo21** [comment]
fixed 
9.5.19 ab 
![image](https://user-images.githubusercontent.com/47611580/64355012-74205780-cfce-11e9-86c6-0f8b4ccc1281.png)
