### ISSUE TITLE
R4C- Inspection Requests

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1698]
We need R4C to stop the request of inspections if there are outstanding fees 
additionally, the applicant should not be able to request an inspection if there is a prerequisite inspection required to be completed prior to the inspection being requested, 

the inspection rules established in IPs should communicate with R4C

**Comment by JuanitaMiles** [comment]
R4C stops me from requesting inspection when i had a re-inspection due. We just need it to stop me from requesting if a prerequisite is not completed.

**Comment by megisys** [comment]
This was never requested.. It is only outstanding fees. Any other status check are on the County and should not hold up the applicant. This is for requesting an Inspection.. Scheduling is done by the County

**Comment by ABonomo21** [comment]
Why would this be a nice to have. It works well in back office so the applicant should be notified as well. Do not agree its a nice to have but should be a must have.

**Comment by dhenry-KCI** [comment]
@ABonomo21 - I agree that a notification should be sent to the applicant via the "Bob button" that requested inspections where either successfully scheduled or applicant will need to re-request an inspection. "Nice to Have" was in relation to the original ticket where R4C would prevent the applicant from requesting the inspection. Hopefully that helps...

**Comment by dhenry-KCI** [comment]
@calequin - can you provide an estimate to configrue the R4C rules like back office that would prevent the applicant from requesting an inspection.

**Comment by ABonomo21** [comment]
duplicate ticket
