### ISSUE TITLE
IPS- Inspection notificaition

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1699]
Bob and Dan had a discussion about creating a "final inspection approval button" that in the morning once all inspection have been moved around, approved for inspection i.e. scheduled for inspection, a notification should go out to the applicant to say your inspection has been scheduled or your inspection has not been scheduled.

**Comment by megisys** [comment]
This was completed in Development and I asked for feedback on another ticket for this

**Comment by megisys** [comment]
Now in Test

**Comment by ABonomo21** [comment]
This is not sending a notification - tested under permit 246839

no notification was sent to be to tell me the inspection was scheduled. Is that because it was scheduled for the 9th and the notification button says "send today's notifications" ???

**Comment by megisys** [comment]
Only works for TODAY

**Comment by JuanitaMiles** [comment]
Getting an error when clicking the button:

![image](https://user-images.githubusercontent.com/31770504/67511075-1fab6700-f664-11e9-9271-69a19b089b01.png)

**Comment by ABonomo21** [comment]
closed - new issue created for notifications being sent #2206
