### ISSUE TITLE
License - Distributor Report - Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#17]
(Reported by Kelly Vanaman 2/6/19)

We need to ensure notification piece is working when an upcoming report is due, if a report is late, and if a fine is issued.

**Comment by megisys** [comment]
No !! NO !!! This is net new.. for 7 Licenses we can get a person to review.. This doesnt exist in Hansen 7

**Comment by dhenry-KCI** [comment]
At end of 45 days need to see monthly's and the end of every year need to see yearly - need system to determine those that are not in compliance with when monthly and yearly report is due.

**Comment by dhenry-KCI** [comment]
email notification requesting report within 45 days of past due

**Comment by mmbanong** [comment]
Passing this to Tara for further discussions

**Comment by dhenry-KCI** [comment]
Sent to Tara. Closing issue
