### ISSUE TITLE
Building - Minor Grading - Bond Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#170]
The system generated a bond review on a minor grading application. 

The system should not red line for a bond review for a minor grading permit. This was previously not populating and working as it should. 

AP # 238494

logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
WEIRD !! - But Fixed

**Comment by dhenry-KCI** [comment]
This has been corrected

tiffany martin 3/5/19
