### ISSUE TITLE
IPS - Inspections 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1700]
related to #1699 if a notification goes out that the inspection has not been scheduled they should be removed for the "request list"

**Comment by megisys** [comment]
I Dont understand this requirement. Cna you please give me more information here ?

**Comment by ABonomo21** [comment]
i would like a notification to be sent to the applicant stating why there inspection has not be scheduled, and i want the pending request to be removed from the request list of unscheduled inspections 

more importantly i would like the applicant to not even be able to submit the request
