### ISSUE TITLE
Failed Inspection report 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1701]
![image](https://user-images.githubusercontent.com/47611580/63966146-a24ee600-ca68-11e9-8f13-d63303a80b7c.png)

report is not generating the inspectors name or contact information and the report is showing 2 $47.00 reinspection fees when there is no fees due on the application- 246352

![image](https://user-images.githubusercontent.com/47611580/63966239-cad6e000-ca68-11e9-9017-f5f02abd83f2.png)

**Comment by TaraF** [comment]
Fixed and ready for re-test.

**Comment by ABonomo21** [comment]
checked the report now showing inspector contact and name 
and is showing the correct fee
however, it is not showing comments and comments were entered
![image](https://user-images.githubusercontent.com/47611580/65630076-a9531080-dfa2-11e9-9847-c1cc6f8d26c8.png)
![image](https://user-images.githubusercontent.com/47611580/65630118-be2fa400-dfa2-11e9-80d8-6443f24bc9ae.png)

and the highlighted section below is over the boarder
![image](https://user-images.githubusercontent.com/47611580/65630067-a22c0280-dfa2-11e9-85c4-4a3b6a78d212.png)

**Comment by TaraF** [comment]
Fixed, ready for re-test.

**Comment by ABonomo21** [comment]
fixed 
![image](https://user-images.githubusercontent.com/47611580/66337950-1f923400-e90e-11e9-8856-71daf9c45cba.png)
