### ISSUE TITLE
ResBldg-Condo-Parent Structure Issued without child unit permits.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1705]
The condo parent permit issued without having the correct number of unit permits attached as child permits.-aw
![image](https://user-images.githubusercontent.com/47611580/63968387-974a8480-ca6d-11e9-92cd-248a707d3cb8.png)
![image](https://user-images.githubusercontent.com/47611580/63968421-a598a080-ca6d-11e9-8621-fcd7b7737fd4.png)

**Comment by megisys** [comment]
Small bug in formula was starting count at 1 instead of 0

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/64194441-20d2cb80-ce4d-11e9-9fe5-83778a3d7200.png)
