### ISSUE TITLE
Building Permit - RESUSE - Final Inspection not showing in R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1707]
It gives me the instructions to schedule but the inspection isn't showing.

![image](https://user-images.githubusercontent.com/31770504/63969196-50f62500-ca6f-11e9-9d40-52a0fc1aab05.png)

**Comment by calequin** [comment]
fixed. the status check formula was causing rhythm to bypass the needs all button. Formula was looking for an inspection to be resulted.

**Comment by ABonomo21** [comment]
tested and it worked for me
![Uploading image.png…]()
