### ISSUE TITLE
Building Permits - Fire Permit - Cannot Submit in Town on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1708]
I am trying to submit an application for a Fire Permit within the town of Woodsboro through R4C and it will not let me.

![image](https://user-images.githubusercontent.com/31770504/64175500-6da4ab00-ce29-11e9-9774-c965b7c4bc0c.png)

![image](https://user-images.githubusercontent.com/31770504/64175543-844b0200-ce29-11e9-95a2-234dbc10ddb5.png)

**Comment by ABonomo21** [comment]
Failed 9.4.19 ab
![image](https://user-images.githubusercontent.com/47611580/64258132-a8bfe080-cef4-11e9-8f8f-05e011f71b92.png)

**Comment by ABonomo21** [comment]
tried two addresses 604 Glenbrook Drive Middletown got the same error

**Comment by calequin** [comment]
both addresses worked for me. Is this issue happening when searching address via map? If so, this is a known issue and it is being worked on with development. Please test by searching with the map off.

![image](https://user-images.githubusercontent.com/47603568/64292095-2d2f5500-cf2f-11e9-845d-191b7e771af9.png)

**Comment by ABonomo21** [comment]
was able to submit with the two town addresses tested 9.5.19 confirmed fixed - will monitor
