### ISSUE TITLE
Blanket Changes Needed

### ISSUE THREAD

**Issue by megisys** [kcigeospatial/Fred_Co_Land-Management#1709]
1. Status Check on  RESBLDG Under Review. IF Attached to Model check is the related child of a BPREview is completed.

2. PLNREV on RESBLDG to do option Selection and options of Model Home

3.CreatePDox Formula to bypasss EPLANS Check on AddonCOndition Formula

**Comment by ABonomo21** [comment]
this is not ready for retest as the blanket permit will not go through to PDOX - see #1856

**Comment by megisys** [comment]
Need to ensure the PLANSUB applicant is on the BPPlanReview
