### ISSUE TITLE
Building - Minor Grading - Mitigation Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#171]
The system is requiring the total balance of the required bond to match the total mitigation details page.  

The system should not require the mitigation details page to be completed on a minor grading permit. This is only for MJ/SWM/PI.

AP # 238494

logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
This is no valid.. This issue was caused due to another issue. Closing to Duplicate

**Comment by dhenry-KCI** [comment]
this has been corrected

tiffany martin 3/5/19
