### ISSUE TITLE
Building Permits - NONRESBLDG - NonRes Intake Details Page in R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1710]
I am trying to submit a NONRESBLDG permit through R4C but my Non Residential Intake Details page is not loading correctly. There are no details available to fill out. I've tried refreshing and logging out and back in but it never loads.

![image](https://user-images.githubusercontent.com/31770504/64189833-13b0df00-ce43-11e9-880d-463644129557.png)

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
fixed confirmed 9.4.19 ab
![image](https://user-images.githubusercontent.com/47611580/64257906-3c44e180-cef4-11e9-99e1-2d1e4fb95b5f.png)
