### ISSUE TITLE
fro - notifications - ready for payment notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1713]
the time on the ready for payment notification is 12:00 am not the actual time. 
Also, the language used does not appear to be correct. It should only say permit application - not planning application. 

![image](https://user-images.githubusercontent.com/4129185/64192204-20840180-ce48-11e9-99c0-f39295976080.png)

tm 9/3/19  246407

**Comment by mmbanong** [comment]
Corrected in ips dev

![image](https://user-images.githubusercontent.com/47392173/64266435-99479400-cf02-11e9-9d3f-47c187b614b2.png)

**Comment by dhenry-KCI** [comment]
Looks good.

9/5/19 EP
