### ISSUE TITLE
fro - notifications - ready for payment and bond

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1714]
this notification states ready for payment and bond - but the email is blank. I received a second email regarding only the ready for payment that had text - but I don't think that we should receive two notifications back to back like that. 

![image](https://user-images.githubusercontent.com/4129185/64192468-bd469f00-ce48-11e9-9599-59a4b553d31c.png)

tm 9/3/19 246407

related to #1713

**Comment by dhenry-KCI** [comment]
@mmbanong this is a comment to combine in the excel created by Juanita and Ashlye B.

**Comment by mmbanong** [comment]
There is no definition for this notification. Needs to be defined

![image](https://user-images.githubusercontent.com/47392173/64266000-dcedce00-cf01-11e9-9423-be7349ee29b8.png)
