### ISSUE TITLE
fro - notifications - issued permit notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1716]
the system did not notify me of the issued FRO permit. But, it did send me a planning application completed notification stating that the fro planning application was finalized.

![image](https://user-images.githubusercontent.com/4129185/64194057-34316700-ce4c-11e9-8db4-90b0d01d9692.png)

tm 9/3/19 246407

**Comment by mmbanong** [comment]
There is no notification at the permit issued milestone

![image](https://user-images.githubusercontent.com/47392173/64281431-1d107900-cf21-11e9-8819-29feec7cb13c.png)

**Comment by dhenry-KCI** [comment]
@mmbanong  - confirm there is Correspondence Report associated to the Permit issued milestone. There will be not be a notification at this milestone. If CM generating at correct milestone but being held up by batch manager, close ticket.

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/64359537-81d9db00-cfd6-11e9-98f4-b5f6de3481a2.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - more CM - confirm this report is in the batch manager. If correct change the label to ready for retest.

**Comment by mmbanong** [comment]
Sorry wrong Module-Building insatead of Planning
I don't see a Notification or Correspondence for PLN FRO.  I don't see a permit issued miletone for FRO either
![image](https://user-images.githubusercontent.com/47392173/64614964-925bce00-d3a7-11e9-80d4-b4e20da3a53d.png)

![image](https://user-images.githubusercontent.com/47392173/64615159-07c79e80-d3a8-11e9-8cfc-11ea8ca51dcd.png)

**Comment by mmbanong** [comment]
emailed Tiffany for guiduance

![image](https://user-images.githubusercontent.com/47392173/64623652-503a8880-d3b7-11e9-8866-b6e5e87f1d27.png)

**Comment by dhenry-KCI** [comment]
@mmbanong what tiffany is saying is that when she was testing a FRO Permit (building application) the notification she received was a FRO Planning application, which is incorrect. The notification template that is used here needs to be for a Fro Permit

**Comment by mmbanong** [comment]
I AM GETTING THE CORRESPONDENCE, PAYMENT NOTIFICATION AND BOND for building. Is this correct? 
![image](https://user-images.githubusercontent.com/47392173/65067040-9b264400-d953-11e9-9190-cdfedcb9ab45.png)

![image](https://user-images.githubusercontent.com/47392173/65066918-569aa880-d953-11e9-9d61-0bc75c469f32.png)

![image](https://user-images.githubusercontent.com/47392173/65066839-2c48eb00-d953-11e9-8c1c-946675bd77ba.png)

**Comment by dhenry-KCI** [comment]
@mmbanong with the issued permit we should receive Correspondence only - we shouldn't have both CM and a notification.

**Comment by mmbanong** [comment]
FRO - notifications - issued permit notification has been removed at the Permit Issued milestone
See before and after screenshots
![image](https://user-images.githubusercontent.com/47392173/65174535-130d7080-da1f-11e9-88e3-75421563cb20.png)


![image](https://user-images.githubusercontent.com/47392173/65173748-7d251600-da1d-11e9-8732-7165b1f6befb.png)

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
