### ISSUE TITLE
fro - notifications - ready for payment and bond

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1717]
this specific permit does not need a bond but i still received the notification stating the payment and bond is needed

![image](https://user-images.githubusercontent.com/4129185/64194597-8b840700-ce4d-11e9-96d5-138cdc71cdcb.png)

tm 9/3/19 246417

**Comment by mmbanong** [comment]
It is generated at the Awaiting Plan Review Payment milestone. Does it need to be removed?

**Comment by dhenry-KCI** [comment]
9/5/19 ep/tm
