### ISSUE TITLE
fro - permit fees not calculating correctly

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1718]
Only 187 generated for the permit fees. however, the fees should be based on the cost estimate which in this case are under 1,000 but it should still be used to populate fees - no bond is required since it is under 1,000

![image](https://user-images.githubusercontent.com/4129185/64194676-b706f180-ce4d-11e9-95b4-0d291a093432.png)
 
tm 9/3/19 246417

**Comment by mmbanong** [comment]
Can I have some guidance on the fees need to be genrated

**Comment by dhenry-KCI** [comment]
ok - tm 9/5/19
