### ISSUE TITLE
fro - notification - ready for payment 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1719]
see attached. 

![image](https://user-images.githubusercontent.com/4129185/64194853-182ec500-ce4e-11e9-90c7-7c7a667482a9.png)

tm 9/3/19 246417

**Comment by mmbanong** [comment]
Change made in ips dev. Server date and formatting need to addressed by Dan
![image](https://user-images.githubusercontent.com/47392173/64264854-f7bf4300-ceff-11e9-9605-19c810fc1ce4.png)

**Comment by dhenry-KCI** [comment]
closed good to go tm 9/5/19
