### ISSUE TITLE
Yard Mod average

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#172]
![image](https://user-images.githubusercontent.com/4129185/53757597-13328e00-3e8a-11e9-9631-c615de2ffe6f.png)
Dustin, 

See attached.  System will not recognize Zero as an average depth, only 1 or more.

Thanks, Tolson

**Comment by megisys** [comment]
Resovled

**Comment by dhenry-KCI** [comment]
fixed MW 3/7/19
