### ISSUE TITLE
fro - notification - permit issued

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1720]
did not receive the permit issued notification for this permit

246417

tm 9/3/19

**Comment by mmbanong** [comment]
There is no current permit issued notification for FRO
![image](https://user-images.githubusercontent.com/47392173/64280563-5e078e00-cf1f-11e9-9335-bf2af9b2b61f.png)

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/64354902-463b1300-cfce-11e9-86a0-847eb98cb61e.png)

this should include a notice of permit approval letter - or should place an admin hold for someone to manually send that notice out.
 
tm 9/5/19 246525

**Comment by dhenry-KCI** [comment]
fixed 9/5/19
