### ISSUE TITLE
planning-verify-zoning verification-wrong fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1723]
fee should be $215

![image](https://user-images.githubusercontent.com/4129185/64195505-a6f01180-ce4f-11e9-9508-149a814274fb.png)

MW

**Comment by megisys** [comment]
You Sure.. we have this logic Value = 115

if oPlanningApp.WorkType.Code = "PSRVER" then
	
	Value = 215
	
End if

**Comment by dhenry-KCI** [comment]
yes, meant to say $118.  It is fixed now.

MW

![image](https://user-images.githubusercontent.com/4129185/64254474-7959a580-ceed-11e9-8ddd-687d0dc38ea3.png)
