### ISSUE TITLE
major grading - notification - payment and bond

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1724]
i received a blank notification for payment and bond - there is no bond required for this AP so it should have only been payment only not bond.

![image](https://user-images.githubusercontent.com/4129185/64195488-963f9b80-ce4f-11e9-9a99-80b1c390c4fb.png)

ap 246420 tm 9/3/19

**Comment by dhenry-KCI** [comment]
It is at the "awaiting applicant payment" milestone

9/4/19 ep

**Comment by mmbanong** [comment]
The payment and bond notification template contains no definition. We need one

![image](https://user-images.githubusercontent.com/47392173/64278769-84c3c580-cf1b-11e9-83e6-8d1525f154c2.png)

**Comment by mmbanong** [comment]
The  payment and bond notification is currently generated at the Awaiting Plan Review Payment not  "awaiting applicant payment" What change is required here? Should I change the milestone to Awaiting Applicant Payment and use the BLDG_AwaitingPayment instead?

**Comment by dhenry-KCI** [comment]
Thank you Dan!! This looks good. 

9/5/19 EP
