### ISSUE TITLE
major grading - notification - issued permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1725]
language in the body of the notification needs spiffed up some. 

ap 246420 tm 9/3/19

![image](https://user-images.githubusercontent.com/4129185/64195627-f2a2bb00-ce4f-11e9-85ce-666c8af3ee13.png)

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/64282725-091a4680-cf24-11e9-8f88-461552215488.png)

**Comment by dhenry-KCI** [comment]
looks good! 

9/5/19 ep
