### ISSUE TITLE
Grading- Minor Notifications  (Correspondence Failing after update on 8/6) 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1726]
minor grading permit 246419

![image](https://user-images.githubusercontent.com/4129185/64195658-08b07b80-ce50-11e9-9561-ddcf65c0bb4a.png)

9/3/19 ep

**Comment by dhenry-KCI** [comment]
@mmbanong - see comments correspondance comments and notifications not generating.

**Comment by mmbanong** [comment]
Correspondences have been stuck in the "CreatingPending" status since yesterday .Can Dan take a look whenever he has a chance?

![image](https://user-images.githubusercontent.com/47392173/64278245-48dc3080-cf1a-11e9-98bd-1fdac9ab004c.png)

**Comment by megisys** [comment]
Batch Manager wasnt running to pick these up,. But there is a Infor Bug Here

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
Was able to test completely under permit 246762

Received notifications (correctly) for permit issued and awaiting applicant payment.
Unable to test resubmit and awaiting plan review payment because the resubmit isn't working
DID NOT RECIEVE a notification for Issue Certificate
Notification I did receive for "Inspection Results" needs to be modified.  Please change to:
         email subject line: "Frederick County Inspection Results"
         body of email: "The (insert inspection type) Inspection for your Grading Permit  # (insert ap #)       was resulted as (insert result) and the inspector made the following comments:- "

9/19/19 EP

**Comment by mmbanong** [comment]
Changed  "Inspection Results" to "Frederick County Inspection Results"
Correspondence was stuck in Creation pending status. Manually ran batch manager and the got the correspondence
![image](https://user-images.githubusercontent.com/47392173/65254928-03e3fc80-dacb-11e9-87f5-55201f7f27a1.png)


![image](https://user-images.githubusercontent.com/47392173/65254096-be72ff80-dac9-11e9-908b-4e6b51715ed6.png)

**Comment by ABonomo21** [comment]
Dustin - please set up a meeting to go through the notifications with Emily, Ashlye and Juanita- I will have us go through it and i am closing this ticket for now @dhenry-KCI
