### ISSUE TITLE
grading - major grading - certificate of completion COC

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1727]
ap 246420 tm 9/3/19

no notification came through once the permit was finalized. 

![image](https://user-images.githubusercontent.com/4129185/64195900-9b511a80-ce50-11e9-9be6-07b22ff241d6.png)

**Comment by mmbanong** [comment]
Got a grading permit
![image](https://user-images.githubusercontent.com/47392173/64280971-2e0cba80-cf20-11e9-9d45-c1b089ef4155.png)

**Comment by dhenry-KCI** [comment]
@megisys - please confirm this is related to the IPS update. If so close.

**Comment by ABonomo21** [comment]
Certificate of Completion notification not received for major grading permit
246767.   no notification, no attachment. nothing. 

9/19/19 ep/tm

**Comment by mmbanong** [comment]
The batch manager does not seem to be working. Got the notification but not correspondence

![image](https://user-images.githubusercontent.com/47392173/65785321-19d46b80-e122-11e9-9144-c8269717354e.png)

![image](https://user-images.githubusercontent.com/47392173/65784996-5c497880-e121-11e9-8f3d-ec394f87550b.png)

**Comment by mmbanong** [comment]
The batch manager log indicates that the correspondence task ran successfully but no correspondence came through

![image](https://user-images.githubusercontent.com/47392173/65786200-2659c380-e124-11e9-84cb-2a5374f75ca2.png)

**Comment by calequin** [comment]
fixed. manually ran batch manager and received pdf via email.

![image](https://user-images.githubusercontent.com/47603568/66140729-3bbd6a80-e5c8-11e9-9243-02bca4fe0ef2.png)

**Comment by ABonomo21** [comment]
need to set up a meeting with Ashlye, Juanita, Emily and Eric to Review notifications and Correspondence for ECS @dhenry-KCI 

Closing ticket for meeting
