### ISSUE TITLE
Building Permits - Fire Permit - Remove CIP/Municipal Checkboxes on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1728]
CIP and Municipality check boxes should not be available on R4C for a Fire Permit.

![image](https://user-images.githubusercontent.com/31770504/64197913-35b35d00-ce55-11e9-8551-f857fdb3a81f.png)

**Comment by calequin** [comment]
fixed. removed show in portal on test

**Comment by ABonomo21** [comment]
fixed
