### ISSUE TITLE
R4C-single visit/minor permit details

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1729]
need to confirm with Ashlye the wording/description for single visit and minor permits on R4C so the customer will understand the application process-aw

**Comment by dhenry-KCI** [comment]
@ABonomo21 - see question for Abbie

**Comment by dhenry-KCI** [comment]
updating to ready for retest so @ABonomo21 can take a look

**Comment by ABonomo21** [comment]
checked resuse- plumbing, electrical and all the single visit one trips seem to make sense to me on r4c - not sure what a/p this ticket was created for
