### ISSUE TITLE
Planning Yard Mod 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#173]
![image](https://user-images.githubusercontent.com/4129185/53757547-f39b6580-3e89-11e9-87af-38b946a441ac.png)

went to start a new application with the same information and got this error message

**Comment by megisys** [comment]
Ready for Restest

**Comment by dhenry-KCI** [comment]
![piccard](https://user-images.githubusercontent.com/4129185/53835215-ee5a1b80-3f5a-11e9-9236-b8148d5a9619.PNG)
Problem has been fixed but property is defaulting to this Piccard Drive address

**Comment by megisys** [comment]
Defaul Addresskey of 1000 - Actual has address details.. This was fixed

**Comment by ABonomo21** [comment]
Fixed - 3/7/19 - KVanaman
