### ISSUE TITLE
Inground Pool-Building Fee is incorrect.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1731]
ap #246422-the building fee for inground pool is incorrect. It should be $177-aw
![image](https://user-images.githubusercontent.com/47611580/64198195-cc801980-ce55-11e9-82fa-cf592a179512.png)
![image](https://user-images.githubusercontent.com/47611580/64198266-f46f7d00-ce55-11e9-8299-49f93c77e18e.png)

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/64282587-c8223200-cf23-11e9-9072-7e0318747e6a.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - confirmed corrected.

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/64347292-a6778800-cfc1-11e9-94e5-c2fbd71a15e0.png)

**Comment by ABonomo21** [comment]
fixed 9.5.19 
![image](https://user-images.githubusercontent.com/47611580/64354399-5f8f8f80-cfcd-11e9-9795-cec6a228d9a4.png)
