### ISSUE TITLE
Building Permits - Fire Permit - Fire Intake Details Page Not Loading in R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1732]
As part of my Completeness check Resubmit, I need to update my details page. The Fire permit Intake Details page is not loading properly.

![image](https://user-images.githubusercontent.com/31770504/64198229-e1f54380-ce55-11e9-989c-a80c7f93f2ec.png)

**Comment by calequin** [comment]
fixed.

**Comment by JuanitaMiles** [comment]
fire intake details is showing now.

![image](https://user-images.githubusercontent.com/31770504/64354632-cca32500-cfcd-11e9-89d8-2e6ad8238e82.png)
