### ISSUE TITLE
Building Module- Under Review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1733]
Need to have a status check at the under review milestone for building use, zoning use and building code edition to be completed by the reviewer prior to progressing the next milestone for the following a/p types 

Resuse
Resbldg
NonRes
Trailer

**Comment by megisys** [comment]
Should be SOP and can run a report if missed. Status Check will hold up Pdox.

**Comment by ABonomo21** [comment]
this is not a training issue it needs to happen @dhenry-KCI

**Comment by ABonomo21** [comment]
Dustin this is not an enhancement- i would like for those status checks to be in place for those a/p types listed @dhenry-KCI

**Comment by megisys** [comment]
This is 2 Tickets.. PLease Seperate

**Comment by megisys** [comment]
Code Edition piece is ready.. PLease Test this and add Fire Permit to new ticket

**Comment by JuanitaMiles** [comment]
fixed for the 4 original
