### ISSUE TITLE
Building Permits - Inspection - Component ID not working for Inspection.InspectionKey (Xtreme Ticket # 13837913)

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#1734]
In SRM, **Building Permits**, Inspections, Inspection InfoViewer, we need the parameter for INSPECTNO (inspection number) to be picked up by the system to generate the report.  

The Component ID  being used is Inspection.InspectionKey.   Confirmed with Dan this looks correct, but the system is generating a prompt for the user to enter the inspection no.  

The same issue is happening for **Use Permits**, Inspections also.  Please see screen captures below:

**Building Permits:**
![image](https://user-images.githubusercontent.com/4104464/64198460-3f899000-ce56-11e9-9732-feee6b012422.png)

**Use Permits:**
![image](https://user-images.githubusercontent.com/4104464/64198548-7364b580-ce56-11e9-84a6-e6d6d1f076ad.png)

**Prompt when running report:**
![image](https://user-images.githubusercontent.com/4104464/64198735-d3f3f280-ce56-11e9-8ea3-4fe3bedeed72.png)

REPORT GENERATES FINE ONCE NUMBER IS INPUT.

*****
Testing environment:  http://wh-ipsdevtst/IPStest/

**Comment by dhenry-KCI** [comment]
@megisys - this is the issue per yesterday's email you had tara create and assign to you. 

From: Tara Feaga <Tara.Feaga@kci.com> 
Sent: Tuesday, September 3, 2019 2:14 PM
To: Dan Grendon <Dan.Grendon@infor.com>
Cc: Dustin Henry <Dustin.Henry@kci.com>
Subject: RE: Report - on demand parameter

Will do – thank you.

Tara

From: Dan Grendon <Dan.Grendon@infor.com> 
Sent: Tuesday, September 3, 2019 2:11 PM
To: Tara Feaga <Tara.Feaga@kci.com>
Cc: Dustin Henry <Dustin.Henry@kci.com>
Subject: RE: Report - on demand parameter

HI Tara,

I am too busy for this right now. Please add a Github ticket and I will get to it in due course. I will need to log an internal ticket and get Development help as it should work as you expect. I am just swarmed.

Thanks

Dan

**Comment by dhenry-KCI** [comment]
@calequin @megisys - can i get a status update on this one?

**Comment by calequin** [comment]
Support responded back with a couple of tips. Testing them out 10/2/2019

**Comment by calequin** [comment]
Need to verify if the SSRS integrator is running on version 1908. @TaraF can you confirm which server houses the reports?

**Comment by megisys** [comment]
SSRS Integrator ? What is that !

**Comment by TaraF** [comment]
@calequin  -- SSRS reports are on **nt1s114.nt1.local** :

The root folder:
https://nt1s114.nt1.local/Reports/Pages/Folder.aspx?ItemPath=%2fIPS_Reports
