### ISSUE TITLE
Minor Permit-Hot Tub & Solar Panels-incorrect fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1736]
The building minimum and the single visit fee both generated for minor permits. only the single visit building fee should generate-aw
#246426-hot tub
![image](https://user-images.githubusercontent.com/47611580/64198996-5c729300-ce57-11e9-86e4-9d0aa738a66e.png)
#246425-solar panel
![image](https://user-images.githubusercontent.com/47611580/64199232-d6a31780-ce57-11e9-818e-06b5f710aa7d.png)

**Comment by mmbanong** [comment]
Both fee values are in the fee library and not dependent on a formula. Dan I am not sure of the logic that generates fees for minor permits. Any suggestions?

**Comment by ABonomo21** [comment]
failed-aw
246457-hot tub
![image](https://user-images.githubusercontent.com/47611580/64263317-75ce1a80-cefd-11e9-92c8-3d3d20619856.png)
246458-solar panel
![image](https://user-images.githubusercontent.com/47611580/64263504-bb8ae300-cefd-11e9-9c3c-479a4988b816.png)

**Comment by ABonomo21** [comment]
fixed-aw
solar panels #246465
![image](https://user-images.githubusercontent.com/47611580/64266984-97320500-cf03-11e9-9ae0-c71bbf3c8123.png)
hot tub #246466
![image](https://user-images.githubusercontent.com/47611580/64267121-d2cccf00-cf03-11e9-90d4-75718c8a2814.png)
