### ISSUE TITLE
Fire permit - Wrong Fee

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1737]
Plan review fee for Fire is the old fee- 

![image](https://user-images.githubusercontent.com/47611580/64199084-8deb5e80-ce57-11e9-987e-fdcb677da7fe.png)

![image](https://user-images.githubusercontent.com/47611580/64199105-96439980-ce57-11e9-83c6-2c8e0395ffa4.png)

**Comment by ABonomo21** [comment]
also missing a budget number 
![image](https://user-images.githubusercontent.com/47611580/64199237-dc98f880-ce57-11e9-987c-8fb0f2c2ffb7.png)

**Comment by mmbanong** [comment]
Fees has been updated. What is the expected Budget number?
![image](https://user-images.githubusercontent.com/47392173/64280195-a2def500-cf1e-11e9-8816-c57aac481186.png)

Missing budget number

![image](https://user-images.githubusercontent.com/47392173/64280269-bbe7a600-cf1e-11e9-932b-9fceb2f3659d.png)

**Comment by dhenry-KCI** [comment]
@mmbanong 

10.98.998.999   42455 0000
--

**Comment by mmbanong** [comment]
Budget number has been updated in Test

![image](https://user-images.githubusercontent.com/47392173/64346702-93b08380-cfc0-11e9-93a2-a19b9c0f3435.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - please confirm you updated the fee in test as well.

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/64347605-33224600-cfc2-11e9-9f2d-63ee7ff807e4.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/64357638-0b87a980-cfd3-11e9-844e-1cdac7110b92.png)
fixed 9.5.19
