### ISSUE TITLE
Fire - PDOX

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1738]
Asking for number of alarm devices on a sprinkler suppression permit-  should pull from type of permit on fire details page 
![image](https://user-images.githubusercontent.com/47611580/64199922-67c6be00-ce59-11e9-8129-977499642a95.png)
![image](https://user-images.githubusercontent.com/47611580/64200062-b4aa9480-ce59-11e9-9edd-ccf96fb49112.png)
stops me for all four fields to be filled in when they are not applicable to the application type

**Comment by dhenry-KCI** [comment]
Short-term will have user populate fields with 0's. Opportunity for Phase IB to add additional review types. Closing.
