### ISSUE TITLE
Building - Minor Logging Permit - Related Records

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#174]
The system is requiring a building permit must be listed as a parent for a minor logging permit.

A building permit being listed as a parent is not applicable to this type of permit.

AP # 238495

logged 3/4/19 TM

**Comment by dhenry-KCI** [comment]
This has not been corrected. The permit was not able to issue due to the red line of building permit must be listed as a parent. This is not applicable for this type of permit.

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
corrected 3/15/19 tiffany martin
