### ISSUE TITLE
PDOX - Reminder

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1741]
Update the pop ups for accepting a task to give directions on what need to be completed prior to accepting the task i.e. sop's telling staff to complete task in ips prior to accepting this task 
check with robert to make sure we can do this.

**Comment by ABonomo21** [comment]
@dhenry-KCI 
do we know if we can do this ? and do we have it in the schedule to make sure we update all the popups?

**Comment by RS-Avolve** [comment]
I had responded to this separately - outside of GitHub.  The wording for the message box AFTER completion of the eForm can be changed per eForm and per workflow.   However, the message box for the acceptance of a task is different.  It could possibly be changed in the Translations section as screenshot shows below, however it could only be changed once replacing all cases of "Do you want to accept the task".  So it could not be customized per eForm, nor could it be customized per workflow.  This would not work for what you want to do.
 


![image](https://user-images.githubusercontent.com/53225350/69194946-acbcd100-0ae7-11ea-8d64-bf95f728083c.png)

**Comment by dhenry-KCI** [comment]
@ABonomo21 - please look at this. We can not update the initial accept task wording, except with a single message for AP type.

**Comment by ABonomo21** [comment]
will address if there is an issue after go live
