### ISSUE TITLE
Error when trying to check status on fire permit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1744]
![image](https://user-images.githubusercontent.com/47611580/64201419-a6aa4300-ce5c-11e9-9a8c-810df69064dd.png)

**Comment by ABonomo21** [comment]
at the pending issuance milestone.

**Comment by dhenry-KCI** [comment]
@ABonomo21 - can you give us an AP number?

**Comment by megisys** [comment]
Turned off BP_COR_FIRE_PERMIT_PLACARD on Fire Permit. Reference incorrecting codeing

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/64282295-1256e380-cf23-11e9-86ea-9383f76e0c08.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - ithis should be coorespondance milestone.  See comment from the notification spreadsheet.


FIRE | Permit Issued | NOT_ISSUE | Always | Upon issuance of the fire permit, the permit issued notification   should be sent along with corresspondence containing the Official Issuance   and Placard reports. These two emails should be combined so only one email   gets sent to the applicant.
-- | -- | -- | -- | --
FIRE | Permit Issued | COR_??? | Always

**Comment by mmbanong** [comment]
I thought we were focusing on notifications and then we will do correspondences next.
Correspondence process has been generating errors or is in "creationpending" status all week. I have notified you and Dan. That needs to be addressed

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/64338130-ebde8a00-cfae-11e9-9950-0f46c1ad06fe.png)

**Comment by dhenry-KCI** [comment]
@megisys - review correspondance schedule as on 8/6 all CM stopped working.

**Comment by megisys** [comment]
13837198

**Comment by dhenry-KCI** [comment]
@mmbanong - the formula is looking for a permit that doesn't existing (FirePermit vs. Fire Permit) additionally, if it was to work it would attached a FRO Permit instead of the Fire Permit.

**Comment by mmbanong** [comment]
The correspondence name has been updated in Dev from FirePermit to Fire Permit

**Comment by mmbanong** [comment]
The screenshot I sent to you is from dev when the name has been corrected

**Comment by mmbanong** [comment]
This is from Test..Correspondence is broken in Dev and Test
![image](https://user-images.githubusercontent.com/47392173/64345125-bf7e3a00-cfbd-11e9-8add-68222f57f4e5.png)

**Comment by ABonomo21** [comment]
i have no clue who fixed this or what happened to fix it but i was able to check the status on a fire permit therefore i am closing this issue. 9.11.19
