### ISSUE TITLE
planning-

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1745]
entered address into R4C to create application.  IPS should flip it to parcel but it didnt.

![image](https://user-images.githubusercontent.com/4129185/64201502-df4a1c80-ce5c-11e9-9bc5-d439eb61c830.png)

MW

**Comment by dhenry-KCI** [comment]
It looks like there is a record in the database for a gravel hill that does not have a street number, preventing the system from finding a related parcel. @megisys - sounds like this a data cleanup for GIS, correct?

**Comment by megisys** [comment]
This address is junky

**Comment by dhenry-KCI** [comment]
Confirmed bad address. Closing issue.
