### ISSUE TITLE
Fire- Inspection Assignment

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1746]
need to revisit the fire inspection assignments - MBIRD is only part time now. Talk with Bob Ensor, should all fire go to Kim Fulcher??

**Comment by dhenry-KCI** [comment]
Emailed Bob. Will post follow-up.

**Comment by dhenry-KCI** [comment]
Per Bob, update Mark Bird to Kim Fulcher.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/64368310-0719bb80-cfe8-11e9-9093-a202cecf9086.png)
246125
9.5.19 ab fixed
