### ISSUE TITLE
Yard mod rear yard measurement 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#175]
![image](https://user-images.githubusercontent.com/4129185/53758649-5857bf80-3e8c-11e9-8834-c77d810b548c.png)

The rear yard modification is only for one house there is only two measurements that are required for a rear yard modification.  House measurement A and House measurement B are the two fields that should be filled out. the CL and Home address field should not be usable.

**Comment by megisys** [comment]
Fixed.. Duplicarte issue

**Comment by dhenry-KCI** [comment]
good to go.  MW 3/7/19
