### ISSUE TITLE
Planning-R4C-due dates not showing up

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1750]
per Dan the email notification for "under review" for internal reviews cannot include the due date information.  The solution is for the notification to direct the applicant to their R4C dashboard.  But R4C is not showing due dtaes.

![image](https://user-images.githubusercontent.com/4129185/64259217-ae1e2a80-cef6-11e9-836b-46137b8a5d77.png)

MW

**Comment by megisys** [comment]
Its not UNDER the View Details

**Comment by calequin** [comment]
this is a duplicate ticket already in with Infor Development.

**Comment by dhenry-KCI** [comment]
closing duplicate
