### ISSUE TITLE
Non Res - Site Plan Requirement 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1752]
for non res application that need to be associated to an approved sp - add a approved sp # box on the intake details page to capture plan - remove expiry date, associate and add. 
![image](https://user-images.githubusercontent.com/47611580/64270185-268de700-cf09-11e9-96a0-96cf0a8c9c9f.png)

**Comment by megisys** [comment]
This detail page is erroring

**Comment by calequin** [comment]
not sure what this means. The detail page adds and and not erroring. need more details

**Comment by megisys** [comment]
Christian. I think we need to rebuild this page from Scratch and if it errors again. Then we need to log a support ticket here

**Comment by dhenry-KCI** [comment]
the approved site plan box will only accept a single letter or number.  Field needs to allow at least four letters/numbers

**Comment by calequin** [comment]
fixed. changed length on schema from 1to 10

**Comment by ABonomo21** [comment]
if expired will relate the permit to the planning application and it will satisfy the requirement
