### ISSUE TITLE
Building Permits - NONRESBLDG - Pay Fees Verification Screen (R4C) 

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1755]
When paying fees for an application the AP Type and Hansen Project / AP # is duplicating for every fee type. Does it have to look like this?

![image](https://user-images.githubusercontent.com/31770504/64271083-b3857000-cf0a-11e9-94c6-dbe861954987.png)

**Comment by calequin** [comment]
email sent to Sireesha and Santhosh for clarification.

**Comment by ABonomo21** [comment]
appears to be fixed will monitor throughout all a/p types 
![image](https://user-images.githubusercontent.com/47611580/65436231-d612f680-ddef-11e9-991c-8a2b1f04ada5.png)
