### ISSUE TITLE
All Modules - Status Checks on R4C (Excel Issue #73)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1757]
We need the ability to make certain status checks from IPS back office not visible to the applicant in R4C. These can be confusing to the applicant when they aren't applicable. Especially under completeness check.

**Comment by calequin** [comment]
@dhenry-KCI  need priority on this. At the moment this would need to be an enhancement request to Infor. Currently each status check can have a portal description in order for the constituent to know that backoffice work is being done.

**Comment by dhenry-KCI** [comment]
@calequin - let's discuss this timorrow morning.

**Comment by megisys** [comment]
Duplciate
