### ISSUE TITLE
Building Permits - NONRESBLDG - CIP/Municipal Checkboxes on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1766]
The CIP Fees and Municipal Fees checkboxes should not be visible on the NonResidential Details page in R4C. Should be back office only.

![image](https://user-images.githubusercontent.com/31770504/64350372-89918380-cfc6-11e9-88a9-1e1af4ee5451.png)

**Comment by ABonomo21** [comment]
removed confirmed 9.5.19

**Comment by JuanitaMiles** [comment]
No longer fixed - 9/19/2019

![image](https://user-images.githubusercontent.com/31770504/65264700-2ed74c00-dadd-11e9-941f-44aee14236d8.png)
