### ISSUE TITLE
Planning - Yard Mod (Rear) - Required Fields

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#177]
![image](https://user-images.githubusercontent.com/4129185/53759438-5858bf00-3e8e-11e9-9518-7247a8f7e283.png)

Can not put a 0 setback in for rear yard.  System won't accept it

**Comment by megisys** [comment]
if you can have 0 then you cant have it be required.

**Comment by ABonomo21** [comment]
![yardmod fix](https://user-images.githubusercontent.com/47611580/53980448-5dac4880-40de-11e9-9ee2-a5eb16c55633.PNG)
Fixed - 3/7/19 - KVanaman
