### ISSUE TITLE
FRO Reporting 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1770]
permit 246417 is under inspections
Certificate of Occupancy is available as a report.... this is not applicable for this permit and should not be available! 

FRO permits do not receive COO/COC...  they do not receive anything when the permit is finalized.

9/5/19 ep/tm

**Comment by dhenry-KCI** [comment]
Water and sewer application AND Building permits- 11 month extension letter AND Building Permits- expiration notices 2nd letter AND Building Permits- Official Issuance  reports should not be available for FRO permits 

FRO PErmit - Official Placard and FRO Permit- Official Issuance are shown same. We are missing the notice of permit approval letter 

9/5/19 ep

**Comment by TaraF** [comment]
FROPERM AP Type was removed from displaying on:

COO/COC report, 
AND Building permits- 11 month extension letter, 
AND Building Permits- expiration notices 2nd letter ,
AND Building Permits- Official Issuance

FRO Permit - Official Issuance has been removed, and FRO Permit - Approval Letter is available, which should be the same as the notice of permit approval letter. That is set at the milestone of permit issued or greater as directed.

**Comment by ABonomo21** [comment]
thank you!
