### ISSUE TITLE
Building Permits - NONRESBLDG Intake Details Page on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1774]
NONRESBLDG Intake Details page not loading in R4C.

![image](https://user-images.githubusercontent.com/31770504/64362210-1bf05200-cfdc-11e9-8fe9-dd9dc84c0532.png)

**Comment by calequin** [comment]
Fixed

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/64371967-df2e5600-cfef-11e9-9537-35f95f24fe51.png)
