### ISSUE TITLE
Trade License - Electrical License - Completeness Check Review Result Options

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1784]
Can we narrow these down to the correct options for the Completeness Check Review please?

![image](https://user-images.githubusercontent.com/31770504/64369576-ac359380-cfea-11e9-84f4-c24434b09a09.png)

![image](https://user-images.githubusercontent.com/31770504/64369821-2108cd80-cfeb-11e9-8d25-def6f179b1c9.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/64372476-61b71580-cff0-11e9-85ed-841bf683341d.png)
