### ISSUE TITLE
Grading Detail Resubmission at Completeness Check 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1786]
Emily and Tiffany can you make sure that if you change details on a resubmission for grading permits that the data goes into IPS --

I closed ticket #1460 if you want to look at it you comment was -  this is the same for grading permits. permit #246218 we tried to submit and update the disturbed area and it did not go over to IPS from r4c

**Comment by ABonomo21** [comment]
permit 246695 
made changes on the applicant actions and it changed the intake details but did not change the grading details anything prior to or at the completeness check that changes should convert to both details pages.

**Comment by ABonomo21** [comment]
unauthorized access- dan will talk to christian

**Comment by JuanitaMiles** [comment]
This is also a problem for Driveway Permits. Need to be able to update detail page at completeness check resubmit.

**Comment by megisys** [comment]
Christian worked on this yesterday
