### ISSUE TITLE
grading - question - cip and municpal projects

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1787]
how are we confirming that these projects are truly CIP? Should we have a required field for the CIP # or continue with the way we currently handle it and confirm it by looking at the planning/project #? 

ap 246603

tm/ep 9/6/19

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - please discuss tomorrow during your grading, fro and driveway

**Comment by JuanitaMiles** [comment]
Should follow permit workflow. If a project is CIP/Municipal customer will need to put it in comments on R4C, then county staff will verify.

**Comment by dhenry-KCI** [comment]
Confirmed training issue. Closing ticket.
