### ISSUE TITLE
Grading- Town CIP Project

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1788]
For Town CIP Projects the Attorney and PWDirector reviews should not populate.
246603
For both Major and Minor Grading Permits

![image](https://user-images.githubusercontent.com/4129185/64430571-89f15380-d086-11e9-976c-fc271fa3409c.png)

9/6/19 EP/TM

**Comment by dhenry-KCI** [comment]
same for BOE projects- there should be no attorney or Director review

**Comment by ABonomo21** [comment]
director review did not populate but the attorney review still populated.. see permit 246691

**Comment by ABonomo21** [comment]
now pwdr is not populating in this situation...it should. 

ap 246768 9/19/19

**Comment by ABonomo21** [comment]
looks like its been corrected tm 9/19/19
