### ISSUE TITLE
Verification Letter-Piccard Dr Error

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#179]
![image](https://user-images.githubusercontent.com/4129185/53759675-e7fe6d80-3e8e-11e9-8e0e-00113e9abac1.png)
After application is created and fees are paid, hit 568167, then go to Site/Property and Piccard Drive always pops up 

![image](https://user-images.githubusercontent.com/4129185/53759798-28f68200-3e8f-11e9-8b6a-52d700f87b76.png)

**Comment by megisys** [comment]
Ok This ticket is all sorts of messed up.. Verification letters is Planning. Application Number is not 568167.

That Address is an incomplete address and should be cleaned up.. 

Address Data Issue.. Look at the zip..

Dan

**Comment by ABonomo21** [comment]
appears to be corrected
