### ISSUE TITLE
Planning-yard mod-resubmittal result needs to require comments

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1790]
am able to result yard mod as resubmit without entering comments.  Entering a comment should be required as it is on other AP types.

![image](https://user-images.githubusercontent.com/4129185/64533458-83124d00-d2e1-11e9-9e86-7eb857632e4d.png)

MW

**Comment by calequin** [comment]
FIXED

**Comment by dhenry-KCI** [comment]
fixed!

![image](https://user-images.githubusercontent.com/4129185/64557970-c932d500-d310-11e9-985d-7d65e2284962.png)


MW
