### ISSUE TITLE
R4C - PLANNING - YARD MOD Application- ADD LANGUAGE ABOUT PAYMENT TO R4C

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1791]
YARD MOD - Add language in the Confirmation that says: Please click on the project link below to pay fees.
AR

![image](https://user-images.githubusercontent.com/4129185/64533480-93c2c300-d2e1-11e9-8304-3e7f1c77c7d8.png)

**Comment by megisys** [comment]
This is universal and for most applications fees are not ready to be paid until after a review. We can add please click below to see the details of your application.

**Comment by dhenry-KCI** [comment]
We should send a notification by email to the applicant that fees are owed instead of adding to R4C. AR

**Comment by calequin** [comment]
added more descriptive verbiage after submittal. Also, email notification for fees comes after submittal.
![image](https://user-images.githubusercontent.com/47603568/64534746-a3d7a400-d2db-11e9-9620-c06d395ad239.png)

**Comment by dhenry-KCI** [comment]
Add a period (.) to the end of the sentence. Thanks, AR

**Comment by calequin** [comment]
fixed

**Comment by dhenry-KCI** [comment]
Thanks.
