### ISSUE TITLE
Planning-yard mod-denied result needs to require comments

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1792]
was able to result yard mod as denied without entering comments.  Need to require comments like we do on other AP types.

MW

**Comment by calequin** [comment]
fixed

**Comment by dhenry-KCI** [comment]
fixed!

![image](https://user-images.githubusercontent.com/4129185/64559726-f2556480-d314-11e9-90a7-7584fcd0412f.png)


MW
