### ISSUE TITLE
R4C - PLANNING - VERIFICATION LETTER Application- ADD LANGUAGE ABOUT PAYMENT TO R4C

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1793]
Add language in the Confirmation that says: Please click on the project link below to pay fees.
AR

![image](https://user-images.githubusercontent.com/4129185/64533826-4b57d500-d2e2-11e9-80d3-217bdced8be8.png)
****

**Comment by megisys** [comment]
Same as previous Issue. This is univeral page
