### ISSUE TITLE
Planning-yard mod-notification-additional information required

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1794]
when resulting a yard mod review as "resubmit" we need the standard "additional information required" notification to be sent to applicant. 

MW

**Comment by calequin** [comment]
fixed. add pln_checkreviewcomments formula

**Comment by dhenry-KCI** [comment]
did not receive notification

![image](https://user-images.githubusercontent.com/4129185/64558224-6aba2680-d311-11e9-8740-28ccf36560ac.png)

MW

**Comment by calequin** [comment]
my apologies, resubmittal condition was not added. fixed
![image](https://user-images.githubusercontent.com/47603568/64558963-c6cd7c80-d30a-11e9-91d1-129a27566c8f.png)

**Comment by dhenry-KCI** [comment]
fixed

![image](https://user-images.githubusercontent.com/4129185/64559586-aaced880-d314-11e9-937e-dbed5e68358b.png)


MW
