### ISSUE TITLE
Planning-Verification letter-NFC result should finalize/close ap

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1795]
choosing NFC result moves ap into issue letter milestone.  It should be closed/finalized.

![image](https://user-images.githubusercontent.com/4129185/64535347-1dc05b00-d2e5-11e9-9631-5aa44a6d12f6.png)

MW

**Comment by calequin** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
fixed

![image](https://user-images.githubusercontent.com/4129185/64618807-f5049800-d3ae-11e9-9f24-d93afabffc57.png)


MW
