### ISSUE TITLE
Planning-verification letter-more information required notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1797]
need the standard "more information required" notification to be sent when verification letter resulted as "resubmit".

MW

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/65064317-33b9c580-d94e-11e9-97e7-544365774948.png)

**Comment by dhenry-KCI** [comment]
verified correct on V245421 - resubmitted twice
