### ISSUE TITLE
planning-verification letter-getting finalized notification when at issue letter milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1799]
happend on the NFC resulted ap as well as an approved ap.

![image](https://user-images.githubusercontent.com/4129185/64535721-c53d8d80-d2e5-11e9-8ab6-d7c17bdc7784.png)

![image](https://user-images.githubusercontent.com/4129185/64535753-d1c1e600-d2e5-11e9-8dd9-5ec3870e2447.png)

![image](https://user-images.githubusercontent.com/4129185/64535930-29605180-d2e6-11e9-9d23-6a7e6c693a88.png)

![image](https://user-images.githubusercontent.com/4129185/64535949-354c1380-d2e6-11e9-831b-b88f4d8d74b4.png)

MW

**Comment by calequin** [comment]
fixed. this notification will only come after the application is in complete milestone. Not during issue letter.

**Comment by dhenry-KCI** [comment]
fixed


MW
