### ISSUE TITLE
Use - Home Occupation - Type of Business Codes on the Detail Page

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#18]
(Reported by Kelly Vanaman and Tolson DeSa 2/6/19)

We would like to update the Type of Business Codes on the Start Application Details page of the Home Occupation (Use Permit Module). Please refer to the attached Zoning Use Code Excel document for the required updates.

![image](https://user-images.githubusercontent.com/31770504/52437527-1b92e580-2ae5-11e9-920e-c66fafd5b316.png)

[Zoning Use Code.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/2842395/Zoning.Use.Code.xlsx)

**Comment by calequin** [comment]
Added the new business types to the detail page and expired the old
![homeoccupbusinesstypefix](https://user-images.githubusercontent.com/47603568/53143858-73a6fe80-355f-11e9-9274-a0db20e4ad30.PNG)

**Comment by ABonomo21** [comment]
Confirmed work type is updated- 3/8/19 ab 
![image](https://user-images.githubusercontent.com/47611580/54035757-0d89c080-4188-11e9-91d3-88a472ca54a1.png)
