### ISSUE TITLE
Building - Minor Logging Permit - Bond Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#180]
The system is requiring a bond review for a minor logging permit.

The minor logging permit will never require a bond review.

AP # 238495

logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
Duplicate Issue

**Comment by dhenry-KCI** [comment]
This has been corrected. 

tiffany martin 3/5/19
