### ISSUE TITLE
Capacity - Error when trying to result a review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1800]
Christian, 
When tryig to result the review as approved Terry is getting the following error (capacity AP). 

![image001](https://user-images.githubusercontent.com/4129185/64537688-4ba79e80-d2e9-11e9-871f-6c67f36a0cba.png)

**Comment by calequin** [comment]
replicated with same information and was succesfully delivered. TMAY's email address was not set up in the system therefore the formula doesnt know where to send the test notifcation
