### ISSUE TITLE
Liquor License - Pro-Rated Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1801]
Liqour license and endorsements need to be pro-rated based on the following schedule:

August 1 - October 31st - 25% reduction
November 1 - January 31st - 50% reduction
February 1 - April 30th  - 75% reduction

**Comment by megisys** [comment]
Have a Quantity Formula on the fees. which then reduces by this.

**Comment by calequin** [comment]
fixed

**Comment by dhenry-KCI** [comment]
Confirmed fixed.
