### ISSUE TITLE
Licenses - R4C / IPS - Status Check (Xtreme # 13788552)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1802]
The system is not moving the application to the next milestone unless the user clicks "status check".  A similar ticket was added for planning and permitting, but has not been applied to Licenses.

**Comment by calequin** [comment]
xtreme ticket reopened because issue is happening in other milestone with formula in place

**Comment by calequin** [comment]
fixed in liquor.

**Comment by JuanitaMiles** [comment]
Will monitor this. All APs appear to be working correctly so far.
