### ISSUE TITLE
grading/driveway - notifications

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1803]
the following notifications recd spell Frederick wrong... Fredrick instead of Frederick

![image](https://user-images.githubusercontent.com/4129185/64551570-4b1c0180-d303-11e9-8cae-6bb7b2f529e5.png)

tm 9/9/19

**Comment by mmbanong** [comment]
These have been corrected in Test

**Comment by mmbanong** [comment]
Added comment on GitHub #1559

![image](https://user-images.githubusercontent.com/47392173/64718557-78e48000-d494-11e9-8e08-888c348cab71.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/65051843-a9fefd80-d937-11e9-8301-800a76d895e8.png)
checked notification templates and they are correct - Dan Corrected any that were not changed.
