### ISSUE TITLE
Building Permits - Grading Permits - PWDR Review for Logging

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1804]
Minor and Major Logging - Vijay needs to be added as a reviewer. He will need to waive his review if it is not applicable.

Per Tiffany, Vijay

**Comment by ABonomo21** [comment]
ap 246763 - no pwdr review populated for this minor logging permit.

![image](https://user-images.githubusercontent.com/47611580/65249424-faa26200-dac1-11e9-9ab5-ec946e5ca6ee.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/65445235-bdaad800-ddff-11e9-930a-1d948264b0da.png)

**Comment by JuanitaMiles** [comment]
@ABonomo21 Please confirm whether or not the PWDR review should be added.

**Comment by ABonomo21** [comment]
fixed 
![image](https://user-images.githubusercontent.com/47611580/67310868-8bf36280-f4cc-11e9-9e86-78b367ebc6ee.png)
