### ISSUE TITLE
PLANNING - MYLAR FEE - PLAT

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1805]
Mylar fee is a calculation of $59/per page. 2 pages should calculate to $118. 3 pages $177 etc.
AR
![image](https://user-images.githubusercontent.com/4129185/64624546-d0152280-d3b8-11e9-9541-2e1e1677a599.png)

**Comment by megisys** [comment]
Isnt 1 page included in the initial fees

**Comment by dhenry-KCI** [comment]
nope. not included in initial fees. 

MW

**Comment by dhenry-KCI** [comment]
corrected PL245385 AR
