### ISSUE TITLE
Building Permits - Grading Permits - ESD Reviews

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1806]
Grading ESD Permits - If PWDR review is resulted with RESUBMIT it should ignore the PWDIRECTOR review and allow the Permit to progress to Awaiting Resubmit. The RESUBMIT means Vijay needs the Easement Legal Documentation from the applicant. The Director review will be the final sign off when the easement has been recorded.

**Comment by megisys** [comment]
Had to add new milestone for this Director Review

**Comment by ABonomo21** [comment]
i am unable to test this ticket because the permit is holding me up at the awaiting applicant revision. i resulted pwdr as resubmit and did the applicant actions detail page and the permit is still stuck at awaiting applicant revision. 

tm 9/19/19

**Comment by megisys** [comment]
Which AP Number

**Comment by ABonomo21** [comment]
@dhenry-KCI - 

can you see if emily knows the permit number her and tiffany tested this under?

**Comment by dhenry-KCI** [comment]
246760

**Comment by calequin** [comment]
needed to result applicant actions as resubmit to progress application. please retest

**Comment by ABonomo21** [comment]
Closing this ticket to cover under training.
