### ISSUE TITLE
Major Grading - PI AND SWM permits auto generating 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1808]
If the grading details on a major grading permit ONLY have SWM involved and or public improvements involved - those applications need to spawn automatically 

![image](https://user-images.githubusercontent.com/47611580/64630122-6f8ae300-d3c2-11e9-9dd7-4fe055ca072c.png)

![image](https://user-images.githubusercontent.com/47611580/64630083-5bdf7c80-d3c2-11e9-8044-cfa84e90c321.png)

![image](https://user-images.githubusercontent.com/47611580/64630011-38b4cd00-d3c2-11e9-990b-99e1eaab572a.png)

**Comment by megisys** [comment]
Where did this come from ? We have status checks reminding that they need to be searched or entered by clerk or by applicant. This is going to have to wait.

**Comment by ABonomo21** [comment]
after speaking with Tiffany further- we are going to change the SOP to instruct the applicants to submit all three applications separately if needed. currently in Hansen we create 3 based of the MJ permit application submitted- if the applicant missed applying for all 3 when Eric does the cost est review he will have to group add and create 
closing this issue okay by ash and gary
