### ISSUE TITLE
Bond Release - MJ/ SWM

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1809]
We created one BT 4990 to two permits MJ 246625 and SWM 246486 
![image](https://user-images.githubusercontent.com/47611580/64632225-b24eba00-d3c6-11e9-9a90-016c07503ae6.png)

when we released the bond for the MJ it did not removed the status check under bond release milestone because there is still a remain balance tied to the SWM permit. 

![image](https://user-images.githubusercontent.com/47611580/64632287-c98da780-d3c6-11e9-9cf2-8010c1e62337.png)

We need the system to recognize that the bond amount for each individual permit, if release progresses the permit to final

**Comment by megisys** [comment]
It cant. In this scenerio you would have to supervisor override. As the system will not know if an amount of release is for which permit

**Comment by megisys** [comment]
This is working correctly.. You will need to supervisor override here
