### ISSUE TITLE
Major Grading Townhouse 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1810]
work type of MJ 
occupancy type - restow, rescon, resapt

![image](https://user-images.githubusercontent.com/47611580/64633791-e11a5f80-d3c9-11e9-8463-59e03cb51874.png)

and on the grading details page the not part of overall plan is checked 

![image](https://user-images.githubusercontent.com/47611580/64633831-f3949900-d3c9-11e9-81f5-730094189021.png)

then the drecostest need to be automatically waived 

![image](https://user-images.githubusercontent.com/47611580/64633899-0d35e080-d3ca-11e9-8b60-f7bc61fa204f.png)

**Comment by megisys** [comment]
Not part of overall plan was selected after intake and teh DRECOSTTEST has already generated. Will need to be waived.

**Comment by ABonomo21** [comment]
will manually waive since the system has already generated the review to populate at intake review- 
we need to add this to the SOP's for grading @dhenry-KCI
