### ISSUE TITLE
Planning-ALL PROJECTS-END OF REVIEW CYCLE NOTIFICATION for internal review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1812]
at the end of each review cycle, need notification sent telling applicant that review cycle has ended and to address comments/resubmit.  Maybe discuss with KCI team as this could be duplicate effort with a review outcome/agency comment report.

MW/AR

**Comment by dhenry-KCI** [comment]
@mmbanong - this will need to be CM for the Project Pending Letters Report - when the application was in-life prior to go-live or where the application is new in IPS 11 but the completeness check is resulted as internal review.  @TaraF for any questions.

**Comment by mmbanong** [comment]
Tara I have not understanding of what is required here. Any clarifications
Will require further discussions

**Comment by megisys** [comment]
Not Needed as PDox, Does this process in 90% of the Occurances
