### ISSUE TITLE
PLANNING - PWCONSTRUC - DASHBOARD for # of pages

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1815]
Create dashboard for PWCONSTRUC **# of pages** that must be filled out on first review. This dashboard is needed for AReed and Vijay Kapoor. He is the person who will be completing the # of pages field in IPS. 
AR

**Comment by TaraF** [comment]
@dhenry-KCI  - is this a reporting issue?

**Comment by dhenry-KCI** [comment]
When I go in to test the projects that are in this dashboard I get errors. I am using the Check Status, Check Box. AREED
![image](https://user-images.githubusercontent.com/4129185/66847604-aca64000-ef41-11e9-921f-fa74467554c0.png)

**Comment by dhenry-KCI** [comment]
Dashboard has been created for AReed. Closing ticket
AReed
