### ISSUE TITLE
Building Permits - Capacity Permit - Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1816]
All Capacity Fees are the 2018 values. Please update **ALL** Capacity Fees per the 2019 DUSWM fee schedule. 

DUSWM has provided their fee schedule to Jeff Wisner.
![DUSWMFees](https://user-images.githubusercontent.com/31770504/64711159-30729580-d487-11e9-90dd-328b9ef8f409.png)

**Comment by mmbanong** [comment]
Awaiting clarification from Jeff Wisner

**Comment by JuanitaMiles** [comment]
@dhenry-KCI - we need to have DUSWM test these fees. We also need to ensure all the fees are adding automatically at all of the appropriate milestones instead of getting the status check requiring them to sometimes be manually added.
