### ISSUE TITLE
Building Permits - Capacity Permit - Payment Method Data Issue

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1817]
This Permit is showing that fees were paid with Cash in IPS, however these fees were paid by Check, as shown on the old Hansen 7 receipt. 

![cash_check](https://user-images.githubusercontent.com/31770504/64712806-dde6a880-d489-11e9-84cf-aa822aefaff7.png)
![cash_check1](https://user-images.githubusercontent.com/31770504/64712808-dde6a880-d489-11e9-8679-5d358981ed97.png)

**Comment by dhenry-KCI** [comment]
Closing data issue. If needed, can provide ticket to GDS team for adjustments post go-live
