### ISSUE TITLE
Building Permits - Capacity Permit - Fee Receipt Format

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1818]
Please make the DBA right adjusted rather than centered on the page.

![FeeReceipt](https://user-images.githubusercontent.com/31770504/64713133-5b121d80-d48a-11e9-9cf7-5d5c9d3cb018.png)

**Comment by TaraF** [comment]
Updated, ready for re-test.

**Comment by JuanitaMiles** [comment]
Looks good.

![image](https://user-images.githubusercontent.com/31770504/65993315-f893b800-e45e-11e9-880a-e5b9c48588f6.png)
