### ISSUE TITLE
Building Permits - Capacity Permit - Capacity Permit Construction Report Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1819]
Capacity Permit - Construction Report Updates:

![image](https://user-images.githubusercontent.com/31770504/64715944-69af0380-d48f-11e9-8f93-96c1d8f9cde7.png)

1) DBA needs to be added to the report at the top (right adjusted). This should be pulled from the "DBA" field on the Capacity Comments and Rep Details page.

![image](https://user-images.githubusercontent.com/31770504/64716638-b6dfa500-d490-11e9-9b68-feebaddd7c88.png)

2) Comments is currently being pulled from the Job Description tab Comments, instead, these comments should be pulled from the Capacity-Specific Comments field on the Capacity Comments and Rep Details page. 

![image](https://user-images.githubusercontent.com/31770504/64716657-c2cb6700-d490-11e9-8722-1246549b4104.png)

3) Subdivision is currently pulling from the Subdivision Description on the Address, instead, this should be pulled from the Subdivision field on the Capacity Details page and should display the subdivision Description.

![image](https://user-images.githubusercontent.com/31770504/64715979-7b90a680-d48f-11e9-86a4-f91ac2e5f419.png)

![image](https://user-images.githubusercontent.com/31770504/64716129-cf9b8b00-d48f-11e9-8ccd-c6471f0739b8.png)

**Comment by JuanitaMiles** [comment]
Also, this particular permit is not applicable, but another permit report we ran had all unpaid fees and the Date Paid field showed 1/1/1990. If all fees are unpaid the Date Paid field should be empty.

**Comment by TaraF** [comment]
@JuanitaMiles  -  need clarification / potentially a sample AP#  on the last comment regarding date paid field.  I am wondering if this was meant to be a comment for another report?  I don't think there is an explicit Date Paid field on this report.

**Comment by TaraF** [comment]
Fixed, ready for re-test.

**Comment by JuanitaMiles** [comment]
All requested updates have been made.

![image](https://user-images.githubusercontent.com/31770504/65993748-d484a680-e45f-11e9-9557-90a6b6aed291.png)

![image](https://user-images.githubusercontent.com/31770504/65993760-db131e00-e45f-11e9-8d4d-dd54315e02f9.png)
