### ISSUE TITLE
Building - Major Logging Permit - Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#182]
The PWDR review is populating on a major logging permit. 

The PWDR review is not required for this type of permit.

AP # 238496

logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
Added NO PWDR for Any MJ Grading

if oBldgApp.Worktype.Code="MJ" then

AddonCondition = False

End if

**Comment by dhenry-KCI** [comment]
This is not corrected. The PWDR review still populated on a MJL permit. Looking at the code it appears that PWDR will not populate for MJ permits - and that is not correct. The review should populate on MJ permits.

tiffany martin 3/5/19

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
corrected 3/15/19 tiffany martin
