### ISSUE TITLE
Building Permits - Capacity Permit - Cannot Pay Fees on Rhythm

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1820]
Fee payment was unsuccessful on Rhythm. Permit #246635

![image001](https://user-images.githubusercontent.com/31770504/64718059-7a617880-d493-11e9-9cb3-40d8c4c65779.png)

**Comment by JuanitaMiles** [comment]
Still cannot pay, get the following error.

![image](https://user-images.githubusercontent.com/31770504/65434082-343dda80-ddec-11e9-99f2-814ad9770aa9.png)

**Comment by calequin** [comment]
sent sireesha and santhosh an email to verify issue

**Comment by JuanitaMiles** [comment]
still cannot pay fees on R4C. This is the only AP i'm not able to pay for today.

![image](https://user-images.githubusercontent.com/31770504/66951353-2a447b80-f028-11e9-8979-6e2afdf5d64a.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/67013033-70e5b480-f0c0-11e9-84dd-dcdaa160bdc4.png)
