### ISSUE TITLE
Building Permits - Capacity Permit - Notification for Awaiting Fixture Payment

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1822]
We did not get a notification for fee payment at the Awaiting Fixture Payment milestone for Capacity permits.

**Comment by mmbanong** [comment]
There is no scheduled notification for this milestone


![image](https://user-images.githubusercontent.com/47392173/64719945-54d66e00-d497-11e9-9e15-21f4de55842c.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - we need you to create this notification

**Comment by mmbanong** [comment]
Created new notification. Awaiting directives from Dan

![image](https://user-images.githubusercontent.com/47392173/65073498-fd397600-d960-11e9-9bd9-ea281882d137.png)

**Comment by dhenry-KCI** [comment]
@mmbanong what do you need from Dan? It seems like you have the notification template created...

**Comment by mmbanong** [comment]
New Notification types need to be registered with web services or so. I don't understand that process and need clarifications

**Comment by dhenry-KCI** [comment]
@calequin - any help you can provide here?

**Comment by JuanitaMiles** [comment]
still getting an error because of the notification.

![image](https://user-images.githubusercontent.com/31770504/66953824-3121bd00-f02d-11e9-8853-52b618412367.png)

**Comment by JuanitaMiles** [comment]
FIXED
