### ISSUE TITLE
R4C- PW Construct Number Location 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1826]
![image](https://user-images.githubusercontent.com/47611580/64726073-dcc27500-d4a3-11e9-899f-608179ef22e1.png)
the new pw construct field needs to be moved to be by the building application and major grading permit number boxe
![image](https://user-images.githubusercontent.com/47611580/64726142-ffed2480-d4a3-11e9-85ab-3ff1ae96e9dd.png)

**Comment by calequin** [comment]
Grading Detail Intake - Fixed

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/65167472-a1c6c100-da10-11e9-8162-84bf6b88caf9.png)
