### ISSUE TITLE
Code Enforcement - Fire Case - R4C Complaint Options

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1828]
Can we remove the Overgrown Vegetation and Poor Living Conditions options and add just "Fire or Life Safety Hazard" as an option?

![image](https://user-images.githubusercontent.com/31770504/64814769-19f53880-d572-11e9-85c8-bfc0dee1e9e6.png)

**Comment by megisys** [comment]
Are you asking if we can. OR asking us to do this ?

**Comment by megisys** [comment]
And as a Citizen of a county. the new description makes no sense to me. Are we sure we want this

**Comment by JuanitaMiles** [comment]
@calequin - What was the reason these other complaint types are not included under the Fire category and shown in Rhythm? The types highlighted were the ones that they (without seeing this list) threw out as types that would be more legitimate complaints. They told me they actually have no power to enforce overgrown vegetation or poor living conditions, that's why they wanted to remove them.

If we can't make the Description required then I agree we would need more specific complaint types. (Having a generic complaint type may also cause problems when trying to track duplicate call types, now that I think about your response on issue #1831 ...)

![image](https://user-images.githubusercontent.com/31770504/64878759-423c7000-d622-11e9-8857-f6c0812a1054.png)

**Comment by calequin** [comment]
I found a list of service requests. I will update them in back office
Fire Marshal Office Common Complaints
•	Overgrown Vegetation
•	Vacant Structures
•	Blighted Properties
•	Poor Living Conditions (i.e. hoarding)
•	Hazardous Conditions, odors from chemicals, gas etc.
•	Overcrowding
•	Fire Hazards
•	Unsafe Condition
•	Grilling/cooking on balconies
•	Outside fires
•	Fire Alarm System Issues
o	Nuisance alarms, trouble alarms, system not serviced, devices not maintained
•	Broken or activated sprinklers
•	Smoke and/CO Alarms
o	Lacking, not working, out of date,  nuisance alarms
•	Illegal Discharge of Fireworks
•	Overstock Mercantile
•	Obstructed Egress/Exits
•	Fire Lane Issues, lack of, unmarked, parking or obstructions. Etc
•	Fire Department Access Issues
•	Elevator Issues
•	Illegal Use or Unpermitted Event

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Confused as to what is showing in Rhythm versus the list of complaints above. Dan is looking into this...
![image](https://user-images.githubusercontent.com/31770504/65059263-aec9ae80-d943-11e9-82bc-6d4d654ce109.png)

**Comment by calequin** [comment]
fixed the description per the list kenny sent
![image](https://user-images.githubusercontent.com/47603568/65062200-26e2a500-d941-11e9-91e8-45bb6a2d541e.png)
