### ISSUE TITLE
Code Enforcement - Fire Case - Description Field on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1829]
Can we make the Description field required for FIRE only? Not sure if this would impact the other request options...

![image](https://user-images.githubusercontent.com/31770504/64814917-72c4d100-d572-11e9-980f-c7e0e09684c1.png)

**Comment by megisys** [comment]
This is not possible. It is free text for the applicant

**Comment by dhenry-KCI** [comment]
Will monitor use after go-live. Closing ticket for now.
