### ISSUE TITLE
Building - Major Logging Permit - Reviews after Inspections

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#183]
The system issued the major logging permit, inspections were completed and then went back to under review and a second DPZ review populated.

Once the inspections have been completed and passed, the permit should close.

AP # 238496

logged by tiffany martin 3/4/19

**Comment by megisys** [comment]
Fixed .. Ready for TEst

**Comment by dhenry-KCI** [comment]
this is now corrected

tiffany martin 3/5/19
