### ISSUE TITLE
Code Enforcement - FIRE CASE - Instructions in R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1830]
Is it possible to add the "Instruction" section to the Fire complaint wizard to allow Kenny/Charlie to provide general information to the complainants as they fill out their request info?

They would like to use this section to prompt the complainants for certain information: is the Property occupied or vacant? Is it a rental? Please add photos if you have them.

![image](https://user-images.githubusercontent.com/31770504/64815184-f979ae00-d572-11e9-9ba3-f8b67cfab820.png)

**Comment by megisys** [comment]
This would be a detail page for the SR. Currently not designed

**Comment by calequin** [comment]
Portal instructions are provided out of the box. For this case. the portal instructions are empty.
To add instructions, go to Customer Service > Service Request Type > Right click on the type and this will take you to the editor.

![image](https://user-images.githubusercontent.com/47603568/64873107-07c8d800-d60e-11e9-9352-79c79229bfda.png)

**Comment by JuanitaMiles** [comment]
Thank you Christian, I put a sample comment in there and it worked. We will work with Kenny and Charlie to get instructions uploaded.
