### ISSUE TITLE
Code Enforcement/Service Request - Duplicate Complaint Question

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1831]
What happens if someone online submits a service request regarding an issue that has already been reported to the county? Does it stop you on R4C and alert you that a complaint of that type has already been made on that property?

What should that workflow be?

**Comment by calequin** [comment]
Duplicate complaints come into the system and gets added as additional callers if it uses the same address and same complaint type.
Also, backoffice users can associate them as additional callers if they are indeed similar.
This is located under Call Details
![image](https://user-images.githubusercontent.com/47603568/64872890-a274e700-d60d-11e9-9d75-723e9e95be05.png)

**Comment by ABonomo21** [comment]
meeting with christian would like them to link related requests either as a call or related record. for same type of complaint on the same property address.

**Comment by ABonomo21** [comment]
will manually add to the existing service request as another caller - if a second one is received.
