### ISSUE TITLE
Code Enforcement/Service Request - Fire Case - Adding Comments when Assigning Inspectors

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1832]
Kenny and Charlie would like the ability to add a note (comments) as they assign the service request to an inspector, that will give the inspector an idea of what to look for, etc.

For now we've instructed them to continue to use email communication for this.

@dhenry-KCI - Assigning this issue to you so you can apply the appropriate label.

**Comment by calequin** [comment]
They can use the additional information comment box on the form or the location box if it is location specific. If they want internal comments then they should use a log that wont be visible to the customer.
Location - Is visible
Additional Information - is visible
Logs - can be configured visible/private in the config

**Comment by dhenry-KCI** [comment]
Noted for training. Closing issue.
