### ISSUE TITLE
Contact popup (Xtreme # 13873458)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1837]
![image](https://user-images.githubusercontent.com/47611580/65048440-1676fe00-d932-11e9-931f-51a25147ef6f.png)

over lay on "no match"

**Comment by calequin** [comment]
xtreme ticket logged with support. @ABonomo21 is this using chrome?

**Comment by dhenry-KCI** [comment]
@calequin - using chrome. Also had a zoon of 110%. I was unable to recreate.

**Comment by ABonomo21** [comment]
@calequin can you provide an update for us please on this one?
@megisys

**Comment by calequin** [comment]
fixed.
![image](https://user-images.githubusercontent.com/47603568/68881761-5d376900-06d3-11ea-8cb8-cb1ad2c8e540.png)
