### ISSUE TITLE
R4C - IPS - CONTACT Property owner entry populating as licensed contact

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1838]
Why did it change from Property Owner to Licensed Contact? This is a problem.
AR

![image](https://user-images.githubusercontent.com/4129185/65056544-0ade0400-d93f-11e9-983c-593503e1f863.png)
![image](https://user-images.githubusercontent.com/4129185/65056566-17625c80-d93f-11e9-980e-f43c9f360fee.png)

**Comment by calequin** [comment]
I couldnt replicate this issue. The application on Rhythm has two fields. The primary applicant selects the role they are a part of. In this case Ashley selected her role as Licensed Contact which we see it listed as the primary.  The additional applicant gets listed as primary = False.

**Comment by dhenry-KCI** [comment]
This works for Mike. It doesn't work for AReed. Will Monitor
