### ISSUE TITLE
Non-Res Building Review 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1839]
my building plan review did not generate on a nonres alteration permit 
![image](https://user-images.githubusercontent.com/47611580/65056959-d3bc2280-d93f-11e9-950e-c25a9c645c0b.png)

**Comment by ABonomo21** [comment]
fire inspection generated 
![image](https://user-images.githubusercontent.com/47611580/65057081-0534ee00-d940-11e9-8ce0-3858c7def80d.png)

**Comment by megisys** [comment]
Alter WorkType was a no PlnRev. Do you want this ADDED in ?

**Comment by ABonomo21** [comment]
yes-
