### ISSUE TITLE
R4C - Fire Detail Pages 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1840]
Would like intake details to be mapped to the fire detail page updated by in-take staff and automatically populate.

**Comment by dhenry-KCI** [comment]
Would like intake details to be automatically populated to the back office detail pages. Current manual population is acceptable - would like fields mapped in the future. 
@calequin - how many hours would it take to complete the mapping of mutiple fire detail pages

**Comment by ABonomo21** [comment]
post go live correction - closed for now
