### ISSUE TITLE
Building Permits - AP Name Illegal Characters Erroring for PDox

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1841]
Check for illegal characters within the A/P Name for Building Permits. We have figured out the apostrophe "'" stops it from going into PDOX but the additional characters need to be tested ($, &, @, etc.)

**Comment by megisys** [comment]
Strip out

**Comment by JuanitaMiles** [comment]
At least leave the spaces between words, everything is just smushed together now.

![image](https://user-images.githubusercontent.com/31770504/65274812-31906c00-daf2-11e9-8700-1a39ed42ae7d.png)
