### ISSUE TITLE
ILM-permit-case-inspection details cant be viewed

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1844]
inspection type didnt populate

![image](https://user-images.githubusercontent.com/4129185/65070139-15f25d80-d95a-11e9-9d3b-e9767a3e9764.png)

cant access
![image](https://user-images.githubusercontent.com/4129185/65070191-2acef100-d95a-11e9-82a1-1a8fc7ae32fd.png)

hansen
![image](https://user-images.githubusercontent.com/4129185/65070276-50f49100-d95a-11e9-9b01-e046611a82f0.png)

MW

**Comment by dhenry-KCI** [comment]
also on building


![image](https://user-images.githubusercontent.com/4129185/65071600-222bea00-d95d-11e9-92e5-2539c0e0032d.png)

![image](https://user-images.githubusercontent.com/4129185/65071612-2a842500-d95d-11e9-8113-5ca51b643184.png)

**Comment by megisys** [comment]
Look at Pristine for this one.

Thanks

Dan

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68421781-ea773c80-016c-11ea-9948-b7ce8dc37ab8.png)

in pristine
