### ISSUE TITLE
Fire Permit - Plan Review Fee Wrong 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1845]
Plan Review fee should be $118.00 not $115.00 the old fee ! 
![image](https://user-images.githubusercontent.com/47611580/65074272-81402d80-d962-11e9-9cfa-efa7e3dab90f.png)
![image](https://user-images.githubusercontent.com/47611580/65074324-961cc100-d962-11e9-9a4d-c6976b78e76c.png)

**Comment by mmbanong** [comment]
PLAN REVIEW FOR FOR FS 13D has been updated

![image](https://user-images.githubusercontent.com/47392173/65145338-5815b080-d9e7-11e9-953f-286c82c816de.png)

**Comment by ABonomo21** [comment]
fee is still not fixed ! it is 13 and 13 R not 13 D !
![image](https://user-images.githubusercontent.com/47611580/65163732-78566700-da09-11e9-8b5d-8aaea2f755fb.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - please review the ticket. The wrong fee amount was updated.

**Comment by mmbanong** [comment]
Rate table values used by formula also needed to be updated

![image](https://user-images.githubusercontent.com/47392173/65166101-0b919b80-da0e-11e9-9821-64c9608d79e2.png)

**Comment by ABonomo21** [comment]
fixed 
![image](https://user-images.githubusercontent.com/47611580/65434862-88958a00-dded-11e9-93c7-9d1a8e7e3289.png)
