### ISSUE TITLE
ILM-Case-process case w/ RESLV should go to closed

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1848]
should go to closed

![image](https://user-images.githubusercontent.com/4129185/65156354-f19b8d00-d9fc-11e9-8d4c-bdf63d7a3f00.png)

![image](https://user-images.githubusercontent.com/4129185/65156384-0546f380-d9fd-11e9-911f-427c45256879.png)

MW

**Comment by ABonomo21** [comment]
dan fixed in test 10.16.19
