### ISSUE TITLE
PLANNING - WSPLANA - WORKTYPE

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#185]
Remove worktype - only option is NEW and it is not needed. AReed

![image](https://user-images.githubusercontent.com/4129185/53813863-8987cc80-3f2c-11e9-9b3c-59258a108595.png)
![image](https://user-images.githubusercontent.com/4129185/53813901-a4f2d780-3f2c-11e9-9cd3-d5755f6a7ace.png)

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
corrected

**Comment by dhenry-KCI** [comment]
areed
