### ISSUE TITLE
ILM-Case-hansen process case milestone w/ NRSLV code

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1851]
hansen process case milestone w/ NRSLV code where a failed inspection is resulted should go to "follow up inspection" milestone in IPS

![image](https://user-images.githubusercontent.com/4129185/65161884-5b6c6480-da06-11e9-8066-c7893fc2ff67.png)

![image](https://user-images.githubusercontent.com/4129185/65161900-61fadc00-da06-11e9-931f-9157e61b6736.png)

![image](https://user-images.githubusercontent.com/4129185/65161931-7048f800-da06-11e9-9e40-6b5cc4fa576c.png)

MW

**Comment by ABonomo21** [comment]
dan fixed in test 10.16.19
