### ISSUE TITLE
ILM-case-process case w/INFO res code

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1852]
process case w/INFO res code should go to awaiting action in IPS

![image](https://user-images.githubusercontent.com/4129185/65163439-eea69980-da08-11e9-9188-7fc13538e95c.png)

![image](https://user-images.githubusercontent.com/4129185/65163462-f5cda780-da08-11e9-9780-6bd42383c3f6.png)

![image](https://user-images.githubusercontent.com/4129185/65163486-00883c80-da09-11e9-8ad5-bf46be3763bf.png)

MW

**Comment by ABonomo21** [comment]
dan moved in test - ashlye checked 10.16.19
