### ISSUE TITLE
Cannot pay fees-Non Res

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1857]
getting the grading permit error when trying to pay fees 
![image](https://user-images.githubusercontent.com/47611580/65174378-cb86e480-da1e-11e9-8d1c-1d2292295e9f.png)

**Comment by JuanitaMiles** [comment]
Cannot pay the fee at the Awaiting Applicant Payment milestone for NONRes 246697.

![image](https://user-images.githubusercontent.com/31770504/65251823-ff691500-dac5-11e9-8a50-494869c8d7a9.png)

**Comment by megisys** [comment]
PLease try one more time

**Comment by megisys** [comment]
Also if not working. Create new ticket . As if someone looks at above t hey will think it is related and I fixed that issue

**Comment by ABonomo21** [comment]
will monitor
