### ISSUE TITLE
PLANNING-REZONE-reviewers

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#186]
WRONG REVIEWERS FOR REZONE-REZONE

DUSWM is conditional add CA and parcel is NPS/well & septic

![image](https://user-images.githubusercontent.com/4129185/53815166-192e7a80-3f2f-11e9-8edf-3822b8d65d0f.png)
![image](https://user-images.githubusercontent.com/4129185/53815206-35321c00-3f2f-11e9-882a-44808f6c1bf1.png)

MAP/FLOAT/REZONE |  
-- | --
COPZ | AA
DUSWM | CA
SHA | CA
DRTE | AA

**Comment by megisys** [comment]
fixed

**Comment by dhenry-KCI** [comment]
correct - areed
w/duswm RZ237504
no DUSWM RZ237502
