### ISSUE TITLE
Building Permits - NONRESBLDG - Applicant Actions Instructions on Rhythm

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1860]
Remove the arrow icons.

![image](https://user-images.githubusercontent.com/31770504/65248880-ead64e00-dac0-11e9-9bd4-66324c5377f0.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Arrows have been removed. 9/23/19

![image](https://user-images.githubusercontent.com/31770504/65434774-5c7a0900-dded-11e9-8b3d-a1f6a6a8dc84.png)
