### ISSUE TITLE
Non Res Building Fee- Wrong Fee

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1861]
Non Res- Building fee should calculate at .22 per sq. ft. but not less than the minimum and the fees are calculating at the old rate of .21 cents per sq.ft. 
permit 246698 has a sq. ft. on of 9080 and the fee calculated at $1906.80- should be $1997.60
![image](https://user-images.githubusercontent.com/47611580/65249853-a8ae0c00-dac2-11e9-866d-20ceffae1eb4.png)
![image](https://user-images.githubusercontent.com/47611580/65250019-e0b54f00-dac2-11e9-9a7c-e7a6b0396aa6.png)

FEES SHOULD NOT BE WRONG AT THIS POINT IN THE PROJECT !!!!!!

**Comment by ABonomo21** [comment]
fixed 
![image](https://user-images.githubusercontent.com/47611580/65434650-28064d00-dded-11e9-834e-b1a7b208b086.png)

**Comment by ABonomo21** [comment]
testing non-res life safety see the building fee did not calculate correctly for application 246856
sq. footage is 2471 and the building fee should calculate at .22 cents per sq. foot which is 543.62
the fee calculated as 2199.78
this should generate at .22 cent on new building, addition, core, vanilla box, tenant occupancy, existing tenant change to space (fit out)
![image](https://user-images.githubusercontent.com/47611580/66505701-dcfd6280-ea99-11e9-9f4c-8421e4800fe9.png)

**Comment by megisys** [comment]
The Gross Floor Altered is 9999. 

![image](https://user-images.githubusercontent.com/47392306/66562172-0fa26c00-eb29-11e9-94a4-0dd508e2f8df.png)

**Comment by megisys** [comment]
Do you want to change it to the high level SQ Footage. Or is this just a mistake ?

**Comment by ABonomo21** [comment]
Dan - have the sq. footage pull from the back details tab for building fee and ols! @megisys 
![image](https://user-images.githubusercontent.com/47611580/66664049-d4cc3100-ec19-11e9-9fb9-75e14a1d67dd.png)

**Comment by ABonomo21** [comment]
will do a final check at end to end testing next week
