### ISSUE TITLE
non res - issuance before grading permit issued 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1864]
grading permit was not issued for permit 246697 and the building permit issued. this should not happen the building permit should wait for issuance of any grading or capacity permits just like res. 

![image](https://user-images.githubusercontent.com/47611580/65260930-32ff6b80-dad5-11e9-9a68-df5cd80aa100.png)

**Comment by megisys** [comment]
I fixed this issue when working on another of similar type

**Comment by ABonomo21** [comment]
did not work - 246858 issued before the generated grading permit was even out of intake review. # 246859
--

**Comment by ABonomo21** [comment]
will confirm during final end to end
