### ISSUE TITLE
non res- review duplication

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1865]
review for pwdr duplicated even though it was already approved in the first cycle did not manually check 
![image](https://user-images.githubusercontent.com/47611580/65261187-af924a00-dad5-11e9-9773-88faed2f4e50.png)

**Comment by calequin** [comment]
added formula to look at most recent review and determine if needs needs to add

**Comment by ABonomo21** [comment]
tested and did not generate second review for approved will monitor.
