### ISSUE TITLE
non res inspections- assignment 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1866]
no assignment was added to the non res inspections for permits 246697
![image](https://user-images.githubusercontent.com/47611580/65262016-722ebc00-dad7-11e9-9b1e-3b424c560319.png)

**Comment by mmbanong** [comment]
I am working on updating every inspection type for non res

**Comment by mmbanong** [comment]
Inspection assignments are now complete for all Building AP Types that are effective

**Comment by JuanitaMiles** [comment]
The Ceiling inspection for this NONRES permit did not have an inspection assignment.

![image](https://user-images.githubusercontent.com/31770504/65992084-891cc900-e45c-11e9-9514-5f5571e147c4.png)

**Comment by mmbanong** [comment]
Ceiling inspection assignments for NONRES are in place
![image](https://user-images.githubusercontent.com/47392173/65993210-c5512900-e45e-11e9-8f83-6163ec3747f4.png)

**Comment by JuanitaMiles** [comment]
The Site Compliance Inspection did not assign.

![image](https://user-images.githubusercontent.com/31770504/65995295-3a266200-e463-11e9-8cb1-124e4e426005.png)

**Comment by mmbanong** [comment]
Can you look at the inspector assignments and let me know what is missing. It looks like the assignments need to be updated.
I can only assign what I am given

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/65996104-c71deb00-e464-11e9-8570-e95ce884b1c0.png)

**Comment by ABonomo21** [comment]
will monitor during end to end testing and training
