### ISSUE TITLE
non res - inspection duplication 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1867]
non res fire final inspection duplicated after the fire final was already passed when it was at the final inspection milestone 
![image](https://user-images.githubusercontent.com/47611580/65262102-97232f00-dad7-11e9-9105-ca0f178b6daa.png)

**Comment by calequin** [comment]
the system has two fire final inspections. I noticed there is a Fire Pre Final. Which Fire inspection needs to happen in the inspection milestone? seems to be missing.

**Comment by ABonomo21** [comment]
we do not use the fire prefinal. 

the fire final needs to generate at the inspections milestone and the building final will generate at the final inspection milestone as it is the very last inspection that is completed.

**Comment by calequin** [comment]
fixed. expired final fire inspection duplicate. added fire final to the inspections milestone.

**Comment by ABonomo21** [comment]
thank you.
