### ISSUE TITLE
non- res site compliance fee 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1868]
site compliance fee did not generate on a non res addition associated to an approved site plan and should have 
![image](https://user-images.githubusercontent.com/47611580/65263107-d18dcb80-dad9-11e9-8363-f1bae9e03b60.png)

**Comment by mmbanong** [comment]
non- res site compliance fee is currently set at 215.00. I am not sure why it did not generate

![image](https://user-images.githubusercontent.com/47392173/65424069-9ab8fd80-ddd8-11e9-9e31-7d0a75bc5336.png)

**Comment by mmbanong** [comment]
I may need for guidance on how to research this one

**Comment by megisys** [comment]
Removed Incorp Town Check and Planning Region Coding. Tested and Addressed

**Comment by ABonomo21** [comment]
generated 246860
