### ISSUE TITLE
non- res site compliance inspection fee did not generate 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1869]
site compliance fee did not generate on an addition with an approved site compliance. 
![image](https://user-images.githubusercontent.com/47611580/65263195-13b70d00-dada-11e9-8b51-eef037fa58b7.png)

**Comment by megisys** [comment]
Addressed this through another Ticket

**Comment by ABonomo21** [comment]
retested under 246860 and it generated
