### ISSUE TITLE
REZONE-DRRA - add BOE

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#187]
Add BOE as an Always ADD reviewer
![image](https://user-images.githubusercontent.com/4129185/53816182-1e8cc480-3f31-11e9-9e64-341dc4cece1e.png)

DRRA |  
-- | --
COUNTYEXEC | AA
COPZ | AA
DPZ | AA
DUSWM | CA
BOA | AA

**Comment by dhenry-KCI** [comment]
BOA should be BOE - sorry. AReed

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
correct rz237495
