### ISSUE TITLE
non res- reinspection fee wrong 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1870]
the non res reinspection fee is wrong it generated at $48.00 and should be $49.00

![image](https://user-images.githubusercontent.com/47611580/65263368-80320c00-dada-11e9-9f10-75c4e628ccbf.png)

**Comment by mmbanong** [comment]
non res- reinspection fee HAS BEEN UPDATED TO 49.00

![image](https://user-images.githubusercontent.com/47392173/65422672-2892e980-ddd5-11e9-87ee-719884d81800.png)

**Comment by ABonomo21** [comment]
fixed 
![image](https://user-images.githubusercontent.com/47611580/65434470-df4e9400-ddec-11e9-82a4-bbdfc69c04f9.png)
