### ISSUE TITLE
Building Permits - Re-inspection Fees Due Notification

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1871]
We should receive an email notification when Re-inspection fees are due, as soon as the fee populates at the Inspections or Final Inspection milestone.

![image](https://user-images.githubusercontent.com/31770504/65263926-8bd20280-dadb-11e9-8e73-4a3568fe5c48.png)

**Comment by mmbanong** [comment]
There are no scheduled notifications at the Inspections or Final Inspection milestone. I will like some clarification on adding the new notification if there is a need for it

![image](https://user-images.githubusercontent.com/47392173/65422974-e5854600-ddd5-11e9-9e24-c209652d4403.png)

![image](https://user-images.githubusercontent.com/47392173/65423033-0c437c80-ddd6-11e9-87e2-bce55a8fb805.png)

**Comment by ABonomo21** [comment]
the notification needs to be sent and generated when a "re-inspection fee" is created. this could happen at either the inspections milestone or the final inspections milestone. i am not sure what needs to be made more clear?  @dhenry-KCI

**Comment by mmbanong** [comment]
These are the current notifications for Building. Are we reusing a notification or creating a new one. If creating what is the expected layout and verbiage?

![image](https://user-images.githubusercontent.com/47392173/65454577-67479480-de13-11e9-9750-b2784a79b99f.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - use fees are due notification language.

**Comment by mmbanong** [comment]
Re-inspection Fees Due Notification has already been created. upon discussion with Christain, Dan has it scheduled on an event and not a milestone. The inspection object is not currently returning values. Reassigning to Dan

![image](https://user-images.githubusercontent.com/47392173/65782678-35d50e80-e11c-11e9-8f11-3b0d253dad1e.png)

**Comment by megisys** [comment]
This Notification Fires on the Adding of a reinspection Fee

**Comment by ABonomo21** [comment]
thanks  dan - i got the notification 
![image](https://user-images.githubusercontent.com/47611580/66504310-de795b80-ea96-11e9-9a3a-d8116269a1e1.png)
