### ISSUE TITLE
Non Res- Grading and Driveway condition 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1872]
condition needs to be corrected for condition that says grading and driveway permits need to be issued like it was for resuse #1685 

![image](https://user-images.githubusercontent.com/47611580/65264097-e10e1400-dadb-11e9-9f9b-baf6c5c15ba9.png)

this should be correct for all a/ps that could have this hold !

**Comment by ABonomo21** [comment]
the hold did not generate to make sure the grading application was issued prior to the building permit being issued like it should have. I cannot determine if the language was corrected because now the hold is not working and needs to 
![image](https://user-images.githubusercontent.com/47611580/65435531-a9121400-ddee-11e9-930f-8ebb5f51bf1e.png)

**Comment by megisys** [comment]
Fixed this Issue

**Comment by ABonomo21** [comment]
did not work - 246858 issued before the generated grading permit was even out of intake review. # 246859

**Comment by ABonomo21** [comment]
will do final confirmation during final end to end testing
