### ISSUE TITLE
non - res town project fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1873]
detail page for permit 246774 is marked as in a town and they are not subject to any fees including extension and re-inspection fees. this fee should have generated and automatically waived like the initial building permit fees 
![image](https://user-images.githubusercontent.com/47611580/65265930-09980d00-dae0-11e9-8b22-89c789b881f0.png)
![image](https://user-images.githubusercontent.com/47611580/65265956-161c6580-dae0-11e9-8895-95618741f706.png)

**Comment by megisys** [comment]
REinspection Fees and Extension Fees will not add. I can not add them and then waive them. AS they are not applicable and a small amount I assume this is better than waiving manually

**Comment by ABonomo21** [comment]
we need to be able to track the fees that are waived and therefore they need to add and be waived the the initial fees for town projects. 

I did another test to see if the fee would add and it did.. 246774

![image](https://user-images.githubusercontent.com/47611580/66506843-18009580-ea9c-11e9-81cf-398ca85e9c77.png)
