### ISSUE TITLE
New work flow  in pdox for revisions 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1874]
after starting a new work flow in pdox, the reviews went back into ips as they should have however, it comes up still as cycle 1 - if a duplicated review is created no matter the workflow cycle in pdox it should count up on the review number ... 
![image](https://user-images.githubusercontent.com/47611580/65266850-dc4c5e80-dae1-11e9-8eed-ab0ad16e6e80.png)

**Comment by megisys** [comment]
I can attempt to fix this. AS I will add a before Review Add Formula to update the Type Number accordingly. But would like to do this onsite when we can test it out completely

**Comment by ABonomo21** [comment]
fixed tested 251065
