### ISSUE TITLE
Revision Review required for all building permits 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1875]
we need to be able to manually insert a revision review which allows front office staff to re-issue a permit once the revised review agencies have approved their reviews 
![image](https://user-images.githubusercontent.com/47611580/65267890-f6873c00-dae3-11e9-9f7c-bd1cd976d5b6.png)

**Comment by calequin** [comment]
Do we need a Revision review for each department? Or one Review called Revision that will cover all?
For example: Revision – P&I , Revision – Health, Revision – DPZ Etc.
Or
Revision Review – All Departments

**Comment by ABonomo21** [comment]
This is the signature review that we discussed we talked about in ticket #1858 - will close this ticket @calequin
