### ISSUE TITLE
Non Res Temp COo Inspections 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1876]
need to be able to add the temp coo inspections for building, fire, site compliance and  when a temp coo request has been made - pop up does not have those inspection types available- plumbing, electrical and fire permits should also have the temp coo inspections available 
![image](https://user-images.githubusercontent.com/47611580/65269139-9219ac00-dae6-11e9-9581-cccf658e7366.png)

**Comment by calequin** [comment]
fixed. temp coo inspections had an expiration date of 9/17/2018

**Comment by ABonomo21** [comment]
checked plumbing, electirc, fire and nonres all the temp coo inspections are available for selection.
