### ISSUE TITLE
Building Permits - NONRESBLDG - Code Violations for FIRE-FIN Inspection

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1877]
There are no available code violations to select for the FIRE-FIN for a NonRes Bldg Permit.

![image](https://user-images.githubusercontent.com/31770504/65270723-bfb42480-dae9-11e9-9ef6-05d2e035821f.png)

**Comment by calequin** [comment]
looks like all of the Fire code violations are expired from v7 migration.
![image](https://user-images.githubusercontent.com/47603568/65271816-811b6b80-dae3-11e9-8d4c-c5f873e186aa.png)

**Comment by calequin** [comment]
should they be expired @JuanitaMiles

**Comment by JuanitaMiles** [comment]
@calequin if you look the Code violation category beneath the one you have open in the screenshot above - "FIRENEW - Active Fire Violations". I think this is the narrowed down list of the 1200 or so original violations. This should be what is available for inspectors to choose from. It just looks like no inspection types for NONRES have been setup yet.

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
appear to be there now 
thanks 
![image](https://user-images.githubusercontent.com/47611580/65630534-a278cd80-dfa3-11e9-9843-6ad0ca313532.png)
