### ISSUE TITLE
Extension Request -details page - notification 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1879]
a notification needs to be sent out at the 11 month, one month prior to permit expiration. it should send a notice to the applicant to tell them to log in to complete and action specified in the correspondence details. Ashlye can provide.

**Comment by ABonomo21** [comment]
need a better way to test that the extension request details page generates at the appropriate time. Dan do you have a solution for being able to test this ?

**Comment by ABonomo21** [comment]
reminder that all applications expired 6 months from the date the application is processed and all permits expired one year the the date of permit issuance - in discussing this with dan he was going to set up the applications to have  a 6 month expiration date and once the permit issues change the date to one year from the issuance date !

**Comment by mmbanong** [comment]
May require Dan's input on this one

**Comment by ABonomo21** [comment]
dan look into this one please @megisys

**Comment by ABonomo21** [comment]
Tara - dan said we can use the report you have created and send it out as a correspondence can you get with him on this one. 
@TaraF

**Comment by ABonomo21** [comment]
The 11 month letters should be a correspondence when the extension request log generates on a permit or application - grading and fro have different letter but same action should occur.

**Comment by megisys** [comment]
I set up the Building Permit Extension Correspondence for this. It will add whenever you add a log of EXTR - Extension Request. Batch Manager will eventually add the logs nightly.

**Comment by ABonomo21** [comment]
I added the log to two permits and did not get a correspondence... 

251065 and  251261

**Comment by ABonomo21** [comment]
received
