### ISSUE TITLE
non res final only fees did not generate correctly 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1881]
![image](https://user-images.githubusercontent.com/47611580/65272855-e6745a00-daed-11e9-9efb-241814b9c11e.png)

![image](https://user-images.githubusercontent.com/47611580/65272867-ef652b80-daed-11e9-9164-dff9c1a886c2.png)

final only non res should generate a flat rate building fee of $118.00  permit 246780 the building fee did not even generate !

**Comment by megisys** [comment]
Address is Terrible.. This needs to be cleaned up.

**Comment by ABonomo21** [comment]
fee did not generate not sure what that has to do with the address ? 
![image](https://user-images.githubusercontent.com/47611580/66507205-c1478b80-ea9c-11e9-9f13-373c78520ac8.png)
246864

**Comment by ABonomo21** [comment]
if it is not a valid address why is it still in the system - where is that data clean up??? @dhenry-KCI

**Comment by ABonomo21** [comment]
used a "good address" and it still did not generate the fees correctly.. 
![image](https://user-images.githubusercontent.com/47611580/66507446-374bf280-ea9d-11e9-95d0-ee64133e9f01.png)
and if you notice the life safety fee is also wrong now! do i need a separate ticket this is ridiculous

**Comment by ABonomo21** [comment]
will manually correct the fee - only 6 ever processed in hansen
