### ISSUE TITLE
Non Res- Foundation fees 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1883]
foundation permit did not generate the correct fees only generated automation and filing, where is the building fee ??? 

![image](https://user-images.githubusercontent.com/47611580/65273748-dfe6e200-daef-11e9-94be-581c1b6f07a6.png)

![image](https://user-images.githubusercontent.com/47611580/65273734-d8273d80-daef-11e9-8ace-d47d2697a2e2.png)

**Comment by megisys** [comment]
Which Fee are you expecting.. The Building Fee on the Second Shot. IS coded not to add for foundation or FOUND-SLAB. IS there another fee for these. Eg the Minimum ??

**Comment by ABonomo21** [comment]
will retest in end to end
