### ISSUE TITLE
Non Res - Capacity Permit generate 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1884]
a capacity permit did not generate on a core building that is on public water and sewer. 
![image](https://user-images.githubusercontent.com/47611580/65274598-b0d17000-daf1-11e9-9206-7335b1744116.png)

**Comment by megisys** [comment]
Look at the screenshot. Water and Sewer are not set. They are blank this is why this didnt happen

**Comment by ABonomo21** [comment]
This is the mall - can we find out from GIS why it was not set ? @dhenry-KCI
