### ISSUE TITLE
PLANNING - R4C - SITE PLAN - *required fields

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1885]
Please make Total Parcel Area and Proposed Development Area required fields with a red *. These fields are fee related on a TYPE I site plan and should be required on all SITE applications. AR

![image](https://user-images.githubusercontent.com/4129185/65337081-833e0280-db95-11e9-9454-0e0944c426bf.png)

**Comment by calequin** [comment]
fixed. made required

**Comment by dhenry-KCI** [comment]
submitted application leaving fields blank.
![image](https://user-images.githubusercontent.com/4129185/65697202-87ac6480-e048-11e9-8426-e8189962ee9b.png)

first time i populated the fields, then hit back button to blank them out.  allowed me to proceed.

Tried it a second time. left everything blank and got the items highlighted in red preventing me from moving forward, but hitting the back button and then proceeding allowed me to submit the application without the fields being entered.

Also appears that "0" allows the application to move forward.  Need the total parcel area and proposed development area fields to be greater than 0

MW

**Comment by dhenry-KCI** [comment]
Verified site plan stopped and would not proceed when field is empty. Application does allow 0 to be entered, but we are going to accept that at this point and will make corrections if needed in the future. 

AReed
