### ISSUE TITLE
License - Liquor License - Applicant Actions Instructions in R4C (Arrows)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1886]
Please remove the arrow icons at Awaiting More Information, and any other resubmit milestones these instructions generate for the Liquor License.

![image](https://user-images.githubusercontent.com/31770504/65435426-83850a80-ddee-11e9-80bb-717e22e52fdd.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Looks good.

![image](https://user-images.githubusercontent.com/31770504/65446501-82f66f00-de02-11e9-84a4-85fb1adbcce4.png)
