### ISSUE TITLE
Use Permits - Home Occupation - Reviews Not Visible on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1889]
I am logged into Rhythm looking at my Home Occupation permit, and it looks like the reviews have been set to not be visible to the applicant. I should see my Completeness Check review here.

![image](https://user-images.githubusercontent.com/31770504/65439736-a9fa7400-ddf5-11e9-8160-502db9d44a65.png)

**Comment by calequin** [comment]
seems to be intermittent. Researching to see if it correlates to the missing modules issue
