### ISSUE TITLE
PLANNING-REZONE- due date

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#189]
Set due date for all reviewers to 4 weeks for REZONE - MAP/FLOAT/REZONE/DRRA & WSPLANA

![image](https://user-images.githubusercontent.com/4129185/53818075-834a1e00-3f35-11e9-8b6f-859e98fbe85d.png)

![image](https://user-images.githubusercontent.com/4129185/53818429-0cf9eb80-3f36-11e9-84ef-a3fd1b0df7f1.png)

**Comment by megisys** [comment]
Updated

**Comment by dhenry-KCI** [comment]
corrected on all EXCEPT WSPLANA

![image](https://user-images.githubusercontent.com/4129185/53828696-64a35180-3f4c-11e9-9841-5b115df73902.png)

**Comment by megisys** [comment]
Set as 4 weeks - Ready to Test

**Comment by dhenry-KCI** [comment]
Correct - WS237521 - AREED
