### ISSUE TITLE
Trade License - Electrical Trade License - Renewal Fee Needs to be Updated

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1890]
The Electrical License Renewal Fee needs to be updated to reflect the updated fee schedule. ($162.00)

![image](https://user-images.githubusercontent.com/31770504/65440812-4d985400-ddf7-11e9-923f-d6b2a494123f.png)

**Comment by mmbanong** [comment]
Trade License - Electrical Trade License - Renewal Fee has been updated from $158.0 to $162.0
![image](https://user-images.githubusercontent.com/47392173/65444565-49bc0000-ddfe-11e9-80cf-ba1878166a7b.png)

**Comment by ABonomo21** [comment]
recalculated and it came up at the correct fee 
![image](https://user-images.githubusercontent.com/47611580/65445962-5c840400-de01-11e9-9988-0966782191b8.png)
