### ISSUE TITLE
Building Permits - RESBLDG - Error When Resulting CERTREV Review

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1892]
On a RESBLDG permit, I get the error below when trying to Approve the CERTREV review.

![image](https://user-images.githubusercontent.com/31770504/65472064-aab7f800-de3f-11e9-8aa8-47c6d6657e4a.png)

**Comment by calequin** [comment]
fixed.  formula had a + instead of a = for the logic.

**Comment by ABonomo21** [comment]
tested and did not get the error 246801
