### ISSUE TITLE
Sop Update- Revision Process

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1893]
Revision of an issued permit if in pdox

Applicant actions- review log
Change detail page
Notate front description tab
Add fees
Start a new work flow in pdox
Reviews will auto generate
Assign reviews 
Manually insert revision review –
Enter a stop on the log entry to the applicant action 
Once all agencies have approved and batch stamp has been completed approve the revisions review and send an email to the applicant with the issued permit and placard. 

Revision of an issued permit if internal

Applicant actions- review log
Change detail page
Notate front description tab
Add fees
Add reviews in IPS 
Assign reviews 
Manually insert revision review –
Enter a stop on the log entry to the applicant action 
Once the stop date is entered a notification will be sent with all the log comments – be sure to add those comments to the log i.e. your request was processed or you need to submit another request with the following attachments 
Once all agencies have approved, result the revisions review and send an email to the applicant with the issued permit and placard. 

@dhenry-KCI - need to add these to the SOP's

**Comment by dhenry-KCI** [comment]
pulled into SOP document.
