### ISSUE TITLE
Resuse - Addition 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1895]
please change the description of those types of additions that have the word expired- 

removed the word expired
![image](https://user-images.githubusercontent.com/47611580/65531928-efd43c80-dec8-11e9-9454-988bae41d3a6.png)

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
fixed 
![image](https://user-images.githubusercontent.com/47611580/65540351-392c8800-ded9-11e9-89de-bfd4830bb9eb.png)
