### ISSUE TITLE
Time stamp in notifications 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1896]
time stamp always says 12 am - we need to correct these to generate the time the notification was generated. 
![image](https://user-images.githubusercontent.com/47611580/65534180-eea50e80-decc-11e9-8978-f616d4624521.png)

**Comment by calequin** [comment]
fixed. added GetDateNow to the notification as opposed to GetDateToday
![image](https://user-images.githubusercontent.com/47603568/65543178-45fbac80-ded6-11e9-92c9-53088ec054cb.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/65543887-1b165600-dee0-11e9-9c48-2ee7bde0ed08.png)
confirmed fixed
