### ISSUE TITLE
Inspection Result notification

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1897]
we do not want to have a notification sent out to the applicant for waived inspection results. only for pass or fail 
this should be applied to building and use permit modules 

![image](https://user-images.githubusercontent.com/47611580/65538063-8ce8a280-ded4-11e9-819a-e24500a9500c.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - let's talk about this ticket in the morning.

**Comment by mmbanong** [comment]
Formula BP_InspectionResultNotification_BU is currently excluding Waived inspection results

if oInspection.InspectionResult.Code <> "WAIVED" or oInspection.InspectionResult.Code <> "NA" then
	
		If (oInspection.IsDataChanged("InspectionResult")) Then
		
		res = SendNotify.BuildingInspNotifications("BP_INSPRES", oInspection)

		End If
	
End if

**Comment by ABonomo21** [comment]
got a notification after testing a waived inspection 
![image](https://user-images.githubusercontent.com/47611580/65992621-879fd080-e45d-11e9-9833-1be0396be07e.png)

**Comment by mmbanong** [comment]
Let me reseach and see why the formula is not working

**Comment by mmbanong** [comment]
The formula BP_InspectionResultNotification_BU is currently excluding Waived inspection results. 
	The Waived inspection results are still generating. Sent email to Dan for clarifications

**Comment by JuanitaMiles** [comment]
Did not get a notification for a WAived result.
