### ISSUE TITLE
re-inspection fee notification 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1898]
the re-inspection fee due did not generate and should for all building permits once a re-inspection fee generates on a building permit. 

tested 246819 resuse permit and it did not send 
![image](https://user-images.githubusercontent.com/47611580/65538673-cff74580-ded5-11e9-9770-28a0297f8344.png)

however it did send on a resbldg permit 
![image](https://user-images.githubusercontent.com/47611580/65538844-3a0fea80-ded6-11e9-9ece-a1eecfe1b033.png)

**Comment by mmbanong** [comment]
The formula BLDG_SendReInspectionFee_Not_AAF is currently sending  re-inspection fee notifications
        for all building permits
	If oFee.FeeDescription.ToUpper().Contains("REINSPECTION") Or oFee.FeeDescription.ToUpper().Contains("RE-INSPECTION") Then

	If oFee.CDRProductFamily = Hansen.CDR.CDRProductFamily.Building Then

		Dim oBldgApp As Hansen.CDR.Building.IBuildingApplication = ServerApplication.NewComponent(Of Hansen.CDR.Building.IBuildingApplication)()

		oBldgApp.BuildingApplicationKey = oFee.Application.CDRProductFamilyApplicationKey

		oBldgApp.LoadByID()

		res = SendNotify.BuildingNotifications("BP_REINSP", oBldgApp)

	End If

	End If

**Comment by JuanitaMiles** [comment]
I did not get the re-inspection fee due notification.

![image](https://user-images.githubusercontent.com/31770504/65990220-2fff6600-e459-11e9-9429-5283c51e3db3.png)

**Comment by mmbanong** [comment]
The re inspection fees notification is not set on miles stones. The code is there but the setup is different. We need Dan to assist with the setup at the module level

**Comment by megisys** [comment]
Closing Due to Duplicate Issue
