### ISSUE TITLE
duplicated notifications 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1899]
i received duplicated notifications that an inspection failed 
i think it was because i tried to save prior to inserting comments but even if i do that it should only send the notification once the result is technically in the system and that requires me to add comments 
![image](https://user-images.githubusercontent.com/47611580/65539074-b5719c00-ded6-11e9-9fac-91dacb3c5df2.png)
permit # 246789

**Comment by mmbanong** [comment]
Inspection result notifications are sent from the Before update event. Any actions that will trigger multiple updates will result in multiple notifications sent out
![image](https://user-images.githubusercontent.com/47392173/66583437-5441fd80-eb51-11e9-8802-5c9399005752.png)

**Comment by ABonomo21** [comment]
dan fixed not a training issue. @dhenry-KCI 
ordering issue in 11
