### ISSUE TITLE
Use - Home Occupation -Applicant Resubmit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#19]
When the user is resulting reviews the 2nd review resulted as a resubmit, will always populate the Applicant Actions Details page with an Action = Select. For the initial resubmitted review and subsequent resubmitted reviews the system will not auto-populate this field. 

Steps to Recreate:
1. Create Home Occupation and progress to Review Milestone
2. Result first review as resubmit
3. Result second rview as resubmit. 
4. click on Use Application Detail Infor Viewer and Click Details tab

![image](https://user-images.githubusercontent.com/4129185/52439683-2c922580-2aea-11e9-9c07-61776199855d.png)

![image](https://user-images.githubusercontent.com/4129185/52439694-31ef7000-2aea-11e9-8102-0ae54bf50eef.png)

**Comment by calequin** [comment]
Retested the issue and both times the Action button was blank prompting the user to select a result.

**Comment by ABonomo21** [comment]
Still a problem unable to select resubmit for a second re-submission.

**Comment by megisys** [comment]
PLease Retest.

**Comment by ABonomo21** [comment]
Testing Failed-This is the first attempt to resubmit as the applicant actions and I keep getting this error message.-AW
![image](https://user-images.githubusercontent.com/47611580/54711721-fac8a180-4b20-11e9-93d4-211ab336c838.png)

![image](https://user-images.githubusercontent.com/47611580/54711769-12a02580-4b21-11e9-9f95-92046359a00a.png)

**Comment by megisys** [comment]
This has been Addressed

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54922518-b9e4da00-4ede-11e9-8538-aefeb7995b04.png)
