### ISSUE TITLE
Partial passed - inspection notification

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1900]
we need the system to get know when there has been a partially passed inspection and reflect that on the notification of the inspection results

![image](https://user-images.githubusercontent.com/47611580/65539671-e3a3ab80-ded7-11e9-886e-6ce539a7771e.png)

**Comment by mmbanong** [comment]
There is a notification that captures the requested information. I need some clarification on what needs to be done here

**Comment by dhenry-KCI** [comment]
@mmbanong the notification above is for a passed inspection this inspection was resulted as a partial pass. If you look at AP 246813, inspection 976676 (same as the notification) the resulted inspection was partial pass (checkbox on the Building Inspection tab. Can the inspection notification be updated to reference as a partial pass as well?

**Comment by mmbanong** [comment]
The is no inspection result definition for partial pass so we cannot capture and render Partial Pass in the inspection result description from the business object

![image](https://user-images.githubusercontent.com/47392173/65991794-f419d000-e45b-11e9-8940-f6f7938012cc.png)

**Comment by ABonomo21** [comment]
dan look at me...

**Comment by ABonomo21** [comment]
retest failed - no notification sent 198641

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68407605-da9e2f00-0151-11ea-942e-d1b34cbd4f2a.png)
