### ISSUE TITLE
BP_REINSP Notification Template Not Pulling Values

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1904]
The BP_REINSP notification is not pulling the appropriate values when it is sent to the applicant. We've tried setting this template up a couple different ways and it still will not work.

![image](https://user-images.githubusercontent.com/31770504/65541931-35e6cb80-dedc-11e9-98cb-8b304709daf9.png)

**Comment by mmbanong** [comment]
Re-inspection Fees Due Notification has already been created. upon discussion with Christain, 
Dan has it scheduled on an event and not a milestone. The inspection object is not currently returning values. Reassigning to Dan as Bug

**Comment by megisys** [comment]
Formula Issue.

**Comment by JuanitaMiles** [comment]
now pulling values

![image](https://user-images.githubusercontent.com/31770504/66507313-fc49bf00-ea9c-11e9-88d2-ca6960c437ca.png)
