### ISSUE TITLE
Map X Y Coordinates not generating 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1907]
possibly related to #1050

the x y coordinates are not generating - testing service request map will not open 
![image](https://user-images.githubusercontent.com/47611580/65614617-f4aaf600-df85-11e9-9db0-9185069a042a.png)

**Comment by ABonomo21** [comment]
none of the parcels in any module have x y coordinates.

**Comment by dhenry-KCI** [comment]
Field is available - Lat_it and Long_it
