### ISSUE TITLE
Error When Trying to Print Ad Hoc Report

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1909]
I get this Runtime error when clicking on the print button while in the results tab of the Ad Hoc Reporting window.

![image](https://user-images.githubusercontent.com/31770504/65628960-832c7100-dfa0-11e9-8d57-dec77e55f0f8.png)

**Comment by megisys** [comment]
You can not print adhoc reports. Only Export to Excel. The system doesnt know how to lay it out.. This is a product issue. But will not be fixed in time for go live.

**Comment by JuanitaMiles** [comment]
@dhenry-KCI - assign labels as you see fit
