### ISSUE TITLE
Building - Driveway - Intake Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#191]
The system has the Driveway Intake Details populating for the applicant to complete.

The system should have a separate details page where the intake details page is completed by us on the back end.

AP # 238539

logged by 3/5/19 tiffany martin

**Comment by megisys** [comment]
Ready for Retest..

**Comment by dhenry-KCI** [comment]
related to item #516 

tm 4/4/19

**Comment by dhenry-KCI** [comment]
tm 4/16/19
