### ISSUE TITLE
Failed Inspection Report 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1910]
can you make the inspection on the failed inspection report popup say 
"Inspection #" ?? 

![image](https://user-images.githubusercontent.com/47611580/65630022-8aed1500-dfa2-11e9-946d-f98ad2238b87.png)

**Comment by TaraF** [comment]
This is NOT a reporting issue,  please see reference here:  https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1734

@ABonomo21  -- this is an issue in IPS, see bug above.  You should NOT have to enter the Inspection No at all, the system should pick it up but it's not working. 

@dhenry-KCI - Can we follow up with previous bug?

**Comment by calequin** [comment]
duplicate of 1734
