### ISSUE TITLE
PLANNING - R4C - Clean up the list of Contact options in R4C

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1911]
We need to reduce the number of options for this field. Please see options that Planning uses in Hansen 7 in the last image below. Please add Contractor, Engineer, Surveyor in addition to the list below.
@ABonomo21 Do you have any feedback for this? 

![image](https://user-images.githubusercontent.com/4129185/65697823-9ba49600-e049-11e9-9b45-f370376677ec.png)
![image](https://user-images.githubusercontent.com/4129185/65697871-ad863900-e049-11e9-9d7d-6b83e5b37e56.png)
![image](https://user-images.githubusercontent.com/4129185/65697932-c393f980-e049-11e9-98c3-b4c34ee0bd13.png)

**Comment by dhenry-KCI** [comment]
submitted by AREED

**Comment by calequin** [comment]
fixed

**Comment by dhenry-KCI** [comment]
Happy with corrected list. AReed
![image](https://user-images.githubusercontent.com/4129185/65898878-7cc33e00-e380-11e9-8deb-d6fa26548b9d.png)
