### ISSUE TITLE
Planning-FRO-fee notification language

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1912]
remove "fro not". 

![image](https://user-images.githubusercontent.com/4129185/65699270-d4456f00-e04b-11e9-9d1c-3db0fa230952.png)

MW

**Comment by mmbanong** [comment]
The highlighted phrase is captured applicant comment and not part of the notification language

![image](https://user-images.githubusercontent.com/47392173/65778094-403eda80-e113-11e9-896f-bed0bd66f919.png)
