### ISSUE TITLE
PLANNING - R4C - Keep Informed on Contat

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1913]
No options for **keep informed** under Contact Details. This should be Yes or No.
AREED

![image](https://user-images.githubusercontent.com/4129185/65699137-a2cca380-e04b-11e9-9855-cbc84586e90f.png)

![image](https://user-images.githubusercontent.com/4129185/65699204-bd9f1800-e04b-11e9-821e-8bc1255555b7.png)

**Comment by calequin** [comment]
fixed

**Comment by dhenry-KCI** [comment]
verified corrected PL245463
