### ISSUE TITLE
PLANNING - R4C - New Contact Details Box will not allow you to submit 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1914]
Appears from Error message, the new Contact Details will not allow you to submit a plat through R4C when filled out properly.  I have tried 3 different times with no success when adding to the new contact field. It also shows * as required but I was able to process application without completing contact. Please make this actually required and allow application to submit when it is required.
AR
![image](https://user-images.githubusercontent.com/4129185/65699804-a3196e80-e04c-11e9-88f8-8d6df8705337.png)

**Comment by calequin** [comment]
fixed

**Comment by dhenry-KCI** [comment]
verified corrected PL245463

**Comment by dhenry-KCI** [comment]
this is not corrected

**Comment by dhenry-KCI** [comment]
Used the contact boxes in R4C and project does not go through on batch manager to PDOX
PL245503
![image](https://user-images.githubusercontent.com/4129185/66316961-a501ee00-e8e6-11e9-99e3-c0b2ab52a03b.png)

**Comment by megisys** [comment]
Missing Applicant in Capcity of PLANSUBMIT

**Comment by megisys** [comment]
Someone Filtered Capacity Codes. This can not be done

**Comment by dhenry-KCI** [comment]
ID 18365413 This one says Address is not a valid record
Happened again
AR
![image](https://user-images.githubusercontent.com/4129185/66504631-8e4ec900-ea97-11e9-9c41-64b6173557a1.png)
![image](https://user-images.githubusercontent.com/4129185/66504658-9870c780-ea97-11e9-8f40-f1e2d2969d43.png)
![image](https://user-images.githubusercontent.com/4129185/66504674-a45c8980-ea97-11e9-8f35-413755ecaff6.png)

**Comment by dhenry-KCI** [comment]
Verified corrected on PL245506
