### ISSUE TITLE
Planning-FRO notification-application complete language

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1915]
remove "fro not"

![image](https://user-images.githubusercontent.com/4129185/65700418-aeb96500-e04d-11e9-99b7-d2868bdb2393.png)

MW

**Comment by mmbanong** [comment]
FRO not is a project phrase entered by the applicant and not part of the custom notification language
Example the phrase Test was entered by me

![image](https://user-images.githubusercontent.com/47392173/65777572-441e2d00-e112-11e9-828f-a5cf831ddc03.png)

![image](https://user-images.githubusercontent.com/47392173/65777350-df62d280-e111-11e9-9207-816c5ef4247c.png)
