### ISSUE TITLE
preplat-admin closure check alert-number of septic lots

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1918]
we dont want this to be a required field.  We dont recall seeing this before.

![image](https://user-images.githubusercontent.com/4129185/65904429-6cb15b80-e38c-11e9-8800-e348f52f60bd.png)

MW

**Comment by calequin** [comment]
expired this status check

**Comment by dhenry-KCI** [comment]
verified check alert condition for septic lots was removed. PP245505 AR
![image](https://user-images.githubusercontent.com/4129185/66319848-c6190d80-e8eb-11e9-9f32-dc3862b98cf4.png)
