### ISSUE TITLE
Building - Driveway - Pending Certificate

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#192]
The system is in pending certificate and certrev is a review that populated.

I believe we decided to get rid of this and have the permit close after final inspection when no bond is required. In this case, the permit was for a common drive.

AP # 238555 

logged by tiffany martin 3/5/19

**Comment by megisys** [comment]
Lets Leave these until Correpondacne is in place.. @dhenry-KCI

**Comment by ABonomo21** [comment]
Corrected.Thank you.

5/2/19EP
