### ISSUE TITLE
ECS - Deed of Easement 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1920]
Need to have a discussion with County attorney to determine if deed of easement maintenance agreement for SWM ESD permits needs to be original or can be electronic.

**Comment by dhenry-KCI** [comment]
please include Ashley and Mike on this meeting so we can try to have a similar process in all departments.-MW

**Comment by ABonomo21** [comment]
@dhenry-KCI

**Comment by dhenry-KCI** [comment]
Scheduled for 10/24. Closing for now
