### ISSUE TITLE
Permit Fee Refunds

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1921]
Need a discussion related to permit fee refunds.

**Comment by ABonomo21** [comment]
@dhenry-KCI meeting with dan emily and gary

**Comment by dhenry-KCI** [comment]
Scheduled for 10/11

**Comment by dhenry-KCI** [comment]
As part of simulation training, walk through process of reverse payments (need examples). Refund would be the same. Will need to confirm process from Cashier's on how refunds, reverse, etc. work.

How would this affect reporting? Need to move AP to the appropriate milestone. 

Fees would show up as "paid" on a refunded application.
