### ISSUE TITLE
Lookup Bonds (CCLB) - need search field added

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#1924]
Under CDR Common --> Lookup Bonds, we need the field "Bond #" to be added to the search query:

Current Bond Search:
![image](https://user-images.githubusercontent.com/4104464/65969678-34188d00-e433-11e9-8bf7-9a70f0a39b8c.png)

Field we need to add:
![image](https://user-images.githubusercontent.com/4104464/65969859-7fcb3680-e433-11e9-99d3-5a13c6acb92c.png)

*********
Reference: 
Lookup Search for Letter of Credit Number
qry_Search_By_Bank_Account
Search / Query to identify record based on Letter of Credit Number

**Comment by calequin** [comment]
ADDED
![image](https://user-images.githubusercontent.com/47603568/66668931-05ad6580-ec1c-11e9-8205-7884dbc7f2c5.png)

**Comment by JuanitaMiles** [comment]
done. @TaraF - does this work for your reporting purposes?

![image](https://user-images.githubusercontent.com/31770504/66762124-5bc81600-ee73-11e9-8552-91ee15d848de.png)
