### ISSUE TITLE
FRO - Internal Review Milestone Progression - Under Review Resubmit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1928]
For FRO applications that are reviewed internally, applications are:

1) Generating a REVREC log type at random times. (This happens on ePlans and Internal Review).
2) Milestones are also generating out of order and/or blowing through Under Review and going straight back to Awaiting Applicant Revisions.

EPlans seems to be progressing fine but the REVREC log is still generating randomly.

![pic1](https://user-images.githubusercontent.com/31770504/65991389-44dcf900-e45b-11e9-963f-e405ec0a1b83.png)

![pic2](https://user-images.githubusercontent.com/31770504/65991393-473f5300-e45b-11e9-8a20-fb94a7d96d81.png)

![pic3](https://user-images.githubusercontent.com/31770504/65991396-48708000-e45b-11e9-9176-e832c0ad3604.png)

**Comment by megisys** [comment]
It is whenever a Review is generated by Project Dox. All it is saying is that a Revision or similar is happeining in Pdox

**Comment by megisys** [comment]
Dug a little deeper. This was a bug..

**Comment by dhenry-KCI** [comment]
internal review tested under F252012 and is working properly. 

![image](https://user-images.githubusercontent.com/4129185/66757139-7a291400-ee69-11e9-94fb-388fbc9371b7.png)

MW
