### ISSUE TITLE
Grading - Resubmission

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1929]
unable to bypass condition on resubmission at completeness check - resubmit on completeness check needs to bypass all status checks like every other permit .. 
![image](https://user-images.githubusercontent.com/47611580/65994341-16621c80-e461-11e9-8395-9989371425a9.png)

**Comment by dhenry-KCI** [comment]
@calequin - can you look at this issue? We want to be able to test this tomorrow.

**Comment by calequin** [comment]
fixed. added logic to status check formulas to look at resubmittal and bypass

**Comment by ABonomo21** [comment]
failed- unable to resubmit on completeness check for permit 246847 due to a status check 
![image](https://user-images.githubusercontent.com/47611580/66336579-5adf3380-e90b-11e9-8689-fdfa38de7699.png)

**Comment by ABonomo21** [comment]
tested 251053
