### ISSUE TITLE
Building - Major Logging - Pending Certificate

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#193]
The system populated a certrev under review when in the pending certificate milestone

I believe that we had this removed originally not to populated

AP # 238558

logged by tiffany martin 3/5/19

**Comment by megisys** [comment]
@dhenry-KCI - Correspondance for Grading.

**Comment by dhenry-KCI** [comment]
CORRECTED TM 5/2/19
