### ISSUE TITLE
R4C- Error 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1930]
getting error when trying to open a logging permit on my dashboard 
![image](https://user-images.githubusercontent.com/47611580/65994453-4c9f9c00-e461-11e9-9bda-a21e2a5c7942.png)

**Comment by calequin** [comment]
can you provide permit #. so that I can mimic the information

**Comment by ABonomo21** [comment]
I dont have a permit number. will close the ticket and monitor
