### ISSUE TITLE
Building Permits - NONRESBLDG - Site Compliance Inspection Generating

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1931]
This application generated a Site Compliance Inspection and it should not have.

![image](https://user-images.githubusercontent.com/31770504/65994840-40680e80-e462-11e9-872d-1534279b208d.png)

**Comment by calequin** [comment]
The current formula is looking to see if the application work type = new and not in FR plan region. This application satisfies this requirement therefore it added the site inspection. If it needs to be updated please let me know the logic of adding a site inspection and I will update.

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - please review with @ABonomo21 and reply to Christian.

**Comment by megisys** [comment]
I fixed this during another fix

**Comment by ABonomo21** [comment]
will test during final end to end
