### ISSUE TITLE
Fire Details- Fire Suppression System Type :Popup

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1936]
nothing to select in the pop up in back office or r4c
![image](https://user-images.githubusercontent.com/47611580/66057715-34825800-e507-11e9-9e98-118e0f5743ed.png)
![image](https://user-images.githubusercontent.com/47611580/66057761-43690a80-e507-11e9-9d31-18714c47cbe3.png)

**Comment by ABonomo21** [comment]
unable to test until the DLL issue and the drop down is available.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/66057900-78755d00-e507-11e9-8eae-62bc0210f6ef.png)

**Comment by ABonomo21** [comment]
Application Type(above suppression type): 3 options
Suppression, Alarm or Smoke Control

then remove this drop down 
![image](https://user-images.githubusercontent.com/47611580/66059083-701e2180-e509-11e9-8b79-9b6c7da41310.png)

**Comment by ABonomo21** [comment]
removed the highlighted.. 
![image](https://user-images.githubusercontent.com/47611580/66059179-9774ee80-e509-11e9-9e84-3ed82cc5a07e.png)

**Comment by calequin** [comment]
fixed.
removed suprresion type drop down
added application type drop down
removed fire alarm.

**Comment by ABonomo21** [comment]
great 
![image](https://user-images.githubusercontent.com/47611580/66074784-07926d00-e528-11e9-819b-4bc4ae74c7dc.png)

![image](https://user-images.githubusercontent.com/47611580/66074803-12e59880-e528-11e9-8cbe-4bbe1abf8b11.png)
