### ISSUE TITLE
Building Permits - Fire Permit - Fire Intake Details

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1937]
Can we make each section header stand out a bit more? They still seem to run together. Maybe underline each one.

Also be sure to have a colon after each header for consistency.

![image](https://user-images.githubusercontent.com/31770504/66057994-9c38a300-e507-11e9-8f71-975c705ca6b3.png)

**Comment by calequin** [comment]
fixed the colon on each header. Unfortunately headers dont allow styling and formatting like labels do. In order for it to appear consistent in back office as a group box we would need the headers to stay as group box labels instead of blue labels like in planning.

**Comment by JuanitaMiles** [comment]
Confirmed with Ashlye: Can we make the sections the same format as the blue labels? I believe we have this for other building permit applications as well don't we? 

Also, I see the colons in the back office, but I do not see them in R4C. Does this just require a re-sync?

**Comment by megisys** [comment]
As Christian Said. We can not adjust the headings. We do have blue labels in other detail pages. But we put fields into group boxes to keep them together and to stop them being all jumbled together, This is not a how stopper at this point. And can wait for the product to allow for formatting of group box headers.

**Comment by ABonomo21** [comment]
post go live - closed for now
