### ISSUE TITLE
Trade License - Electrical License - License Category Options

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1938]
Can we make the Electrical General option camel case to be consistent with the other two options.

![image](https://user-images.githubusercontent.com/31770504/66058387-4ca6a700-e508-11e9-9814-e26227e1a9fc.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Looks good

![image](https://user-images.githubusercontent.com/31770504/66074374-175d8180-e527-11e9-9d74-9571c7eb1653.png)
