### ISSUE TITLE
Trade License - Resubmit at completeness check 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1939]
When we do a resubmit on an initial submission (completion check) the applicant should be able to update any details asked for by the County - like all other applications once we approve the completeness check no changes should be made until the confirm details page is available at the renewal

Currently we are unable to update the any details

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/66063003-7f549d80-e510-11e9-8b9e-821c5bfa7ac9.png)

**Comment by megisys** [comment]
Updated to Included Awaiting More Information

**Comment by ABonomo21** [comment]
was able to update without error
