### ISSUE TITLE
Building - Minor Logging - Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#194]
The system did not generate fees for this permit type. The permit went straight to under review.

AP # 238565

logged by tiffany martin 3/5/19

**Comment by megisys** [comment]
Which fees should added please ? @dhenry-KCI

**Comment by dhenry-KCI** [comment]
The system should add the following fees -
Minor Logging Fee - $94
SCD Logging Review Fee - $60

**Comment by megisys** [comment]
This is fixed I believe

**Comment by dhenry-KCI** [comment]
fees populated - corrected 3/15/19 tiffany martin
