### ISSUE TITLE
Trade License - Electrical License - Issued By

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1941]
This application shows that the Applicant (Gerry Kelly) issued the permit because I was the last one to pay fees.

Instead this should default to the person who approved the completeness check.

![image](https://user-images.githubusercontent.com/31770504/66064764-0a836280-e514-11e9-9105-e38ce28de885.png)

**Comment by megisys** [comment]
This is not important. This is how the system works. Fees are paid after completeness check

**Comment by megisys** [comment]
Added

**Comment by ABonomo21** [comment]
shannon paid the fee - on her r4c account for license # e245511 and it shows issued by Gerry Kelly.... 

![image](https://user-images.githubusercontent.com/47611580/66330670-dedeee80-e8fe-11e9-90df-98f2c183b01d.png)

**Comment by megisys** [comment]
Updated to another method/

**Comment by ABonomo21** [comment]
corrected 
![image](https://user-images.githubusercontent.com/47611580/66488135-749f8880-ea7b-11e9-85b7-f7b55f83f156.png)
