### ISSUE TITLE
Electrical Trade License Notification 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1942]
A log did not generate for a notification sent that the license was in the awaiting renewal milestone. 

![image](https://user-images.githubusercontent.com/47611580/66065233-f724c700-e514-11e9-8a70-b1c8a4a97f08.png)

Also - The notification did not send that there were fees due for a renewal 

Finally- the correspondence did not send for license card when it did issue. 

License # E244494

**Comment by mmbanong** [comment]
Investigating why the notifications, logs and correspondence did not generate 
 for Electrical Trade License.

**Comment by mmbanong** [comment]
A log was not generated for a notification sent that the license was in the awaiting renewal milestone because we donot currently have a  notification scheduled at that mileston. See all the scheduled notifications for Electrical Trade License

![image](https://user-images.githubusercontent.com/47392173/66322311-ea76e900-e8ef-11e9-95b5-48b92877a170.png)

**Comment by ABonomo21** [comment]
Dustin - There were a few issues within this ticket, I do not feel I received a valid answer or correction to any of them. If there is no notification then one should be created, correct?

I was not asked a question... The ticket was just changed to awaiting response?? @dhenry-KCI

**Comment by dhenry-KCI** [comment]
@mmbanong - moving forward when you see a ticket that reads:

A log did not generate for a notification sent that the license was in the awaiting renewal milestone.

Also - The notification did not send that there were fees due for a renewal

Finally- the correspondence did not send for license card when it did issue.

The request is to create a notification at the appropriate fee milestone, ensure the log is created and generate the CM at permit issuance. This ticket has three issues. please address 

Anything assigned to you in github has been confirmed missing or not working

**Comment by mmbanong** [comment]
1. Our code currently sends out  expiration notification at the awaiting renewal details milestone while in TestMode. The Renewal notification is not sent in Testmode
2. I can schedule the renewal fee notification but I am not sure at what milestone. 
3. We already have a CM at the Issue Lic milestone. Do we need to schedule diferently for Lic renewal?
![image](https://user-images.githubusercontent.com/47392173/66405436-24132700-e9b8-11e9-839e-dc05c0f88292.png)

![image](https://user-images.githubusercontent.com/47392173/66408274-a998d600-e9bc-11e9-8f30-0f4ac5aa5458.png)

![image](https://user-images.githubusercontent.com/47392173/66408513-11e7b780-e9bd-11e9-9d5a-eaf3f0803b95.png)

**Comment by ABonomo21** [comment]
notification generated- Juanita will combine the fee and renewal notification
