### ISSUE TITLE
Trade License - Plumbing Master - Trade License Details Update on Rhythm

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1943]
During the Awaiting More Information (Completeness Check resubmit) it did not save my updates on the detail page. I tried to change the phone number. I should be able to make detail page updates during completeness check resubmit.

![image](https://user-images.githubusercontent.com/31770504/66067997-c34ca000-e51a-11e9-919c-5a30d10b63fa.png)

**Comment by megisys** [comment]
Addressed this during fixing another issue

**Comment by ABonomo21** [comment]
was able to update details page e245511
