### ISSUE TITLE
Plumbing Trade License- Master Plumber

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1944]
Need a check box under the state license number that states " Insured for Plumbing Work"
![image](https://user-images.githubusercontent.com/47611580/66068018-d19abc00-e51a-11e9-90fd-b00938ce5400.png)
![image](https://user-images.githubusercontent.com/47611580/66068055-dd867e00-e51a-11e9-94b4-b9c6e790d687.png)

**Comment by ABonomo21** [comment]
also needed on confirm details page

**Comment by ABonomo21** [comment]
I think because the trade license detail page is the same for all trade licenses - we will need to add a master plumber detail page for this license type to answer the question is "Insured for Plumbing Work"...

**Comment by megisys** [comment]
This was discussed and is not needed. They need to provide documents to prove this. Old H7 licenses will have this but has no benefit for the new process

**Comment by ABonomo21** [comment]
will be fine without this for go-live if it become an issue after go live we will have it added
