### ISSUE TITLE
Plumbing and Electrical Trade Notification 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1945]
Please remove the 12 am after the dates within the notification stating when the license will be eligible for renewal and when it will expire 
![image](https://user-images.githubusercontent.com/47611580/66068725-212db780-e51c-11e9-8486-b44f043280d5.png)

**Comment by megisys** [comment]
As Talked about in the past this is not possible. In Future Release it has been addressed but it is a product issue.

**Comment by ABonomo21** [comment]
The time is not going to work.. the license does not expire at 12 AM.. it would be 11:59PM which putting that on an email to me is ridiculous. I think this is a must have possibly need to discuss when dan is on site with Gary @dhenry-KCI

**Comment by ABonomo21** [comment]
do not remove my Bug code until we have a meeting set up...

**Comment by megisys** [comment]
Ok.. But there is no option for this. It simple is not available in the current software. We could add one day to all trade Licenses

**Comment by megisys** [comment]
Removed Dates
