### ISSUE TITLE
Plumbing and Electrical Trade License Cards

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1946]
Is it possible to bold the text on the license cards so it stands out more in front of the seal ?? 
![image](https://user-images.githubusercontent.com/47611580/66068901-7073e800-e51c-11e9-87a2-7c790d072819.png)

I know this was QC'ed but looking at it again in final walk through it is a little hard to read.

**Comment by TaraF** [comment]
Ready for re-test.

**Comment by ABonomo21** [comment]
thank you 
![image](https://user-images.githubusercontent.com/47611580/66322718-8ef92b00-e8f0-11e9-9926-0a40dc6aaa59.png)
