### ISSUE TITLE
Plumbing and Electrical Trade License - On Demand Printing 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1947]
I am not able to print the license cards after issuance?? They are not a selectable on demand report 
![image](https://user-images.githubusercontent.com/47611580/66069137-c052af00-e51c-11e9-9c1b-718e247a6ccf.png)

after the first time the license card is issued up to the date it expires or is renewed with a new expiration date the card should be able to be printed on demand.

**Comment by TaraF** [comment]
Notes taken from a previous review -  requested that the report should be available on milestone of "Active" or "Pre-Renew", which is how it was set.

Based on your feedback above, I have updated this to show on milestone "Active" or greater.

Ready for re-test.
