### ISSUE TITLE
Trade License - Confirm License Details 

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1948]
FOR ALL TRADE LICENSES:

At Awaiting Renewal Details, prepopulate the Confirm License Details page with the existing Trade License Details information. A check box should be added to the Confirm detail page that will show to the applicant on R4C, to confirm that they have reviewed and updated their details as necessary. The Confirm Details field that currently exists should remain a back office only field for intake staff to confirm the review of these updates.

 
![image](https://user-images.githubusercontent.com/31770504/66069916-5509dc80-e51e-11e9-8543-e1664498c340.png)

**Comment by megisys** [comment]
No this is not how it was intended. The REnewal Review is approved and the details entered here will become the license details. We talked about this previously

**Comment by JuanitaMiles** [comment]
Configure them all consistently, with whatever you think is the appropriate way to confirm details. Currently they do not all work the same way.

**Comment by JuanitaMiles** [comment]
Worked with Dan to clean up the confirm detail process on the Electrical License. He will apply these changes to the remaining license types.
