### ISSUE TITLE
Plumbing License - Missing Notification  

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1949]
Did not get a notification that the license renewal period is open nor did we get a notification of the renewal fee being due - logs show there was never one generated. 
![image](https://user-images.githubusercontent.com/47611580/66070163-ce093400-e51e-11e9-92a8-733a3169d08f.png)

**Comment by mmbanong** [comment]
These are the scheduled notifications for Plumbing. I am not sure which notification is for the license renewal period is open or for the renewal fee. Do we need to create a notification? If so at what milestone should we expect the notification?

![image](https://user-images.githubusercontent.com/47392173/66130901-7f13db00-e5c0-11e9-8efe-61794fdc3b9f.png)

**Comment by megisys** [comment]
Hi Martin,

The ticket is due to the fact they are not generating for the above license. So something is a miss. The above notification schedule looks right you are referencing but they are not there.

**Comment by mmbanong** [comment]
Dan here are the scdelued notifications for Plumbing License.
I am not sure which notification is for the license renewal period is open or for the renewal fee. 
Do we need to create a notification at the License Renewal milestone? 

![image](https://user-images.githubusercontent.com/47392173/66319898-db8e3780-e8eb-11e9-9833-fd91aa0171f9.png)

**Comment by ABonomo21** [comment]
notifications did not send

**Comment by megisys** [comment]
Can you provide the AP number and the notification which you were expecting.

**Comment by ABonomo21** [comment]
Got the email just need to clean up the notification - emailed juanita 
![image](https://user-images.githubusercontent.com/47611580/68408034-94959b00-0152-11ea-9f51-6bff6615f952.png)
