### ISSUE TITLE
Building - Minor Logging - Pending Certificate Milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#195]
The system is requiring certrev to be completed at pending certificate. 

We decided that the permit should go straight to close once the final inspection passes.

AP # 238565

logged by tiffany martin 3/5/19

**Comment by megisys** [comment]
Need Correspondence

**Comment by dhenry-KCI** [comment]
See - #196

**Comment by dhenry-KCI** [comment]
CORRECTED TM 5/2/19
