### ISSUE TITLE
Trade License - Plumbing Master - Confirm License Details Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1950]
At the Awaiting Applicant Payment milestone I am not able to update the Confirm License Details page. I get the following error.

![image](https://user-images.githubusercontent.com/31770504/66070308-10cb0c00-e51f-11e9-9626-f425f8020350.png)

**Comment by ABonomo21** [comment]
did not get the error
