### ISSUE TITLE
Plumbing License Milestone Issues 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1951]
Confirmed renewal details in the back office - did the license renewal review and it went right back to awaiting renewal details - never changed any of the expiration dates and added another fee... 
![image](https://user-images.githubusercontent.com/47611580/66070775-f3e30880-e51f-11e9-8e30-8863ed96c3e0.png)

**Comment by megisys** [comment]
Addressed This

**Comment by ABonomo21** [comment]
will review after meeting for ticket #1999

**Comment by ABonomo21** [comment]
this is not working - still have all the wrong expiration dates to start pm250942

**Comment by megisys** [comment]
Changing to Data Issue. As the Permits Have all moved along due to the renewal period. We will need to look at this later now.
