### ISSUE TITLE
Trade License Detail Report 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1952]
Is it possible to be able to select what items print on the detail report? 

In Hansen - we are able to turn on and off information we want to print in the information report 
![image](https://user-images.githubusercontent.com/47611580/66071179-b29f2880-e520-11e9-812b-8dd9581060c2.png)

**Comment by ABonomo21** [comment]
@TaraF

**Comment by TaraF** [comment]
@ABonomo21  -  please see my email in regards to this one, and please test out the report "Trade License Details Test".   

![image](https://user-images.githubusercontent.com/4104464/68887039-42222480-06e6-11ea-80aa-7dcc07dcfcf8.png)

This is not an ideal solution, and IPS is limiting in how parameters are set when working with SSRS reporting.  You must enter "Y" or "N"  (yes = to display, no = do not display).   If you enter any other letter, the report will never generate.   In SSRS this is a drop down selection but we can not get that to show in IPS. 

Let me know if you'd rather revert to the other with all selections, or if this will meet your needs (even though its not ideal).
