### ISSUE TITLE
Trade License Detail Report  #2 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1953]
What are the brackets for at the top right of the report- ?? A license or permit number ?

![image](https://user-images.githubusercontent.com/47611580/66071271-dd897c80-e520-11e9-87d7-76231d68abf0.png)

**Comment by TaraF** [comment]
This is a placeholder, in case the type has a License Category.  For example, it would show like this:

![image](https://user-images.githubusercontent.com/4104464/66216185-03cf2980-e693-11e9-89e4-11b5677cb12e.png)


It is one report -- so it needs to be determined if it should be kept for all, or removed for all. Currently in the cases where there isn't a license category, it will show as you see above, with empty ( ). 

Please re-test for all cases, and then advise if a change needs to occur.

**Comment by ABonomo21** [comment]
Can you take the brackets out- that way if there is no category it will not look bad?

**Comment by ABonomo21** [comment]
@TaraF

**Comment by TaraF** [comment]
Parenthesis have been removed.  Ready for re-test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68711697-2ee94a80-0568-11ea-9c77-71fcc3386b95.png)
