### ISSUE TITLE
Appliance Master License 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1954]
please make the section complete on the applicant master details page a drop down - yes.. like all the others
![image](https://user-images.githubusercontent.com/47611580/66071633-7c15dd80-e521-11e9-875a-aca286217992.png)

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/66323225-73425480-e8f1-11e9-9471-6f2abb9cd90c.png)
