### ISSUE TITLE
Fee pay - back office on Appliance License

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1955]
We are not able to pay fees back office for appliance - i get this error 
![image](https://user-images.githubusercontent.com/47611580/66071816-ceef9500-e521-11e9-90cc-da930cca84b3.png)

**Comment by calequin** [comment]
There is an error on correspondence formula TL_COR_ISSUED therfore causing the fees to not be paid.
@mmbanong please take a look.

**Comment by mmbanong** [comment]
I was able to generate and pay fees
![image](https://user-images.githubusercontent.com/47392173/66229404-bf9e5200-e6af-11e9-84db-ee9a7ba757a4.png)

![image](https://user-images.githubusercontent.com/47392173/66229148-2e2ee000-e6af-11e9-912a-d21e621da3e7.png)

**Comment by ABonomo21** [comment]
was able to pay fees on lic pa245509
