### ISSUE TITLE
Trade License - Journeyman - Available Fees to Add 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1956]
why are appliance installer fees select-able on a journeyman license 
![image](https://user-images.githubusercontent.com/47611580/66072938-0b23f500-e524-11e9-88b9-642337ce9eef.png)

license #  PJ244499

**Comment by calequin** [comment]
removed appliance

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/66332133-fcfa1e00-e901-11e9-904b-8d05a82c6dea.png)
