### ISSUE TITLE
Use Permits - Home Occupation - Hours of Operation R4C Update

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1958]
Went to update my Hours of Operation record from 5:00 to 5:30 for my End Hr, and it reset my time to 12:00 am. In the back office it reset to 0

![image](https://user-images.githubusercontent.com/31770504/66149311-d164f400-e5e0-11e9-96af-e32961dafeea.png)

**Comment by ABonomo21** [comment]
in the back office the end hours come over as 00:00
![image](https://user-images.githubusercontent.com/47611580/66149356-ec376880-e5e0-11e9-9052-7c65c4cb3199.png)

**Comment by calequin** [comment]
Amy C. has confirmed that this will be fixed on the 19.10 release of R4C

**Comment by calequin** [comment]
fixed with the 19.10 update of r4c.

**Comment by ABonomo21** [comment]
until it is really ready for retest i am leaving this as a bug- ashlye

**Comment by calequin** [comment]
this has been fixed and tested by me. 
Steps taken
1. application H250747
2. changed the hours from original 8:30 and changed to 9:am and it worked and saved.
3. it did not change the time to 00:00 like the original issue stated.

**Comment by ABonomo21** [comment]
fixed test h250771
