### ISSUE TITLE
Building - Minor Grading - Pending Certificate Milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#196]
Certrev is populating under the pending certificate milestone.

We discussed that this should not be populating 

AP # 238569

logged by tiffany martin 3/5/19

**Comment by megisys** [comment]
@dhenry-KCI Correpondence

**Comment by dhenry-KCI** [comment]
@megisys once the inspection passes the milestone can go straight to close and this is where the email would generate alerting the applicant the permit is closed.  We want to remove the pending certificate milestone to eliminate the extra review

**Comment by megisys** [comment]
When this is set up we will expire the review type.. But for now lets leave it to ensure it is happening

**Comment by dhenry-KCI** [comment]
Will leave as -is for now but will need to circle back to remove pending certificate milestone

**Comment by dhenry-KCI** [comment]
did not get an email when the permit closed. The certrev is still on there and it should be removed per our meeting we recently had. 

tiffany martin 4/3/19

**Comment by megisys** [comment]
This is Correspondence

**Comment by goggansd** [comment]
@dhenry-KCI this issue is related to Correspondence, which @megisys tells me is Frederick County's to address.

**Comment by dhenry-KCI** [comment]
pending certificate shold be sent out per correspondence of the final permit.

**Comment by mmbanong** [comment]
Passing to Tara to automate correspondence process

**Comment by dhenry-KCI** [comment]
There is a reporting piece as well as a go-live label that prevents inadvertent errors from generating.
