### ISSUE TITLE
Use - Home Occupation - Error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1961]
unable to progress in testing past the under review milestone for home occupation because once i approved the reviews i received the following message - 
![image](https://user-images.githubusercontent.com/47611580/66151690-d8423580-e5e5-11e9-938b-1d561a88f0d7.png)

**Comment by ABonomo21** [comment]
christian fixed - called him and he changed the access control, Dustin you will need to touch base with Christian to see what needs to be done with access control permissions..

**Comment by ABonomo21** [comment]
@dhenry-KCI

**Comment by ABonomo21** [comment]
reopen to make sure the access control is working for staff

**Comment by calequin** [comment]
added as a will monitor since the bug was fixed
