### ISSUE TITLE
Use Permit _Home Occupation 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1962]
no Expiration date generated on my home occupation number # H244677
![image](https://user-images.githubusercontent.com/47611580/66152168-e9d80d00-e5e6-11e9-9f9d-f4cc13cbdd21.png)

**Comment by calequin** [comment]
FIXED. Added homeoccup expiration date formula as well as the set expiration date to happen in the inspection milestone

**Comment by JuanitaMiles** [comment]
Expiration date is now populating however, Home Occupation permits should expire one year from the issued date.

![image](https://user-images.githubusercontent.com/31770504/66323406-c4524880-e8f1-11e9-8624-c5523046f359.png)

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
fixed 
![image](https://user-images.githubusercontent.com/47611580/66503557-88f07f00-ea95-11e9-9634-0b5a1ff5dc40.png)
