### ISSUE TITLE
Use Permits - Home Occupation - Issued Notification

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1963]
The Issued Permit Notification should be sent at the inspections milestone. It is currently not sending.

**Comment by calequin** [comment]
fixed. moved it from Active milestone to Inspections

**Comment by JuanitaMiles** [comment]
Fixed. Now sending at the appropriate time.

![image](https://user-images.githubusercontent.com/31770504/66323070-3aa27b00-e8f1-11e9-831e-350db12bccd2.png)
