### ISSUE TITLE
Use Permit - Home Occupation Inspection 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1964]
DOLS inspection did not assign for a home occupation permit 

![image](https://user-images.githubusercontent.com/47611580/66152360-4d623a80-e5e7-11e9-96b0-be84685ed950.png)

same rules established for building should apply to use home occ and land use

**Comment by calequin** [comment]
@mmbanong  can you take a look and apply same rules as building assignments?

**Comment by mmbanong** [comment]
Ashley, Inspector assignments in Building are based on the Election Districts. We don't have Election Districts for USE. Should I make the assignments on the Sub Division instead?

![image](https://user-images.githubusercontent.com/47392173/66154044-b0a19c00-e5ea-11e9-8758-5986872d68a2.png)

![image](https://user-images.githubusercontent.com/47392173/66154102-cadb7a00-e5ea-11e9-9bf6-b6b2ad36c406.png)

**Comment by ABonomo21** [comment]
no... you should us the election district it does not change from use to building....

**Comment by mmbanong** [comment]
Created new inspection assignment group for Election Districts and completed inspection assignements for Home Occupation and Land Use AP Types for USE module except for types that  returned Error: Inspection type is not Effective

![image](https://user-images.githubusercontent.com/47392173/66320875-a4208a80-e8ed-11e9-9d6d-60201f0289cd.png)

**Comment by JuanitaMiles** [comment]
Not fixed. Still no assignment.

![image](https://user-images.githubusercontent.com/31770504/66322748-9caeb080-e8f0-11e9-9ed9-efbe01089deb.png)

**Comment by mmbanong** [comment]
Juanita, I scheduled the inspections for Life Safety Inspection same as assigned for Building as reflected in the above screenshot
But Office of Life Safety returns the following Error and I am not sure what needs to be done 
![image](https://user-images.githubusercontent.com/47392173/66323224-72a9be00-e8f1-11e9-952f-5e64017181c8.png)

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/66323488-df24bd00-e8f1-11e9-955f-344d838d24a5.png)

**Comment by megisys** [comment]
Please Test.

**Comment by ABonomo21** [comment]
The Life Safety Inspections should have been assigned to the Life Safety inspectors not the building inspectors 

the same as how it is set up in the building module for life safety - retest failed

**Comment by ABonomo21** [comment]
dan fixed 
![image](https://user-images.githubusercontent.com/47611580/66855007-6efce380-ef50-11e9-9ed8-006bc3b3791c.png)
