### ISSUE TITLE
Use Permits - Land Use and Home Occupation - Requests of Inspections

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1965]
I was able to request an inspection on Thursday at 2:05 for Friday morning. I should have received a message that I cannot request for this time.

![image](https://user-images.githubusercontent.com/31770504/66152519-9c0fd480-e5e7-11e9-8203-ed2b20ca8edf.png)

**Comment by calequin** [comment]
fixed. added scheduleinspection logic for web user to formula

**Comment by JuanitaMiles** [comment]
Does not appear fixed. At 12:56 I made my request for an inspection for tomorrow morning. It allowed me to submit the request when it should not have.

![image](https://user-images.githubusercontent.com/31770504/66503634-b4736980-ea95-11e9-998d-b0a6386ecf8a.png)

**Comment by calequin** [comment]
just tried it today at 12:53pm CST. and it worked. 
![image](https://user-images.githubusercontent.com/47603568/66593651-0af7ab00-eb5d-11e9-94a2-17f113b772eb.png)

**Comment by JuanitaMiles** [comment]
fixed.
