### ISSUE TITLE
Use Home occupation -Inspection comments needs to be required

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1967]
I was able to fail an inspection without adding any comments- there should be a popup like all other inspections that tells me i am required to add comments - please mimic the building 
![image](https://user-images.githubusercontent.com/47611580/66152760-2c4e1980-e5e8-11e9-92b6-648f4ca7b45b.png)

**Comment by calequin** [comment]
fixeed
