### ISSUE TITLE
Use Permits - Home Occupation - Inspection Request

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1968]
I was also able to request an inspection for the weekend and should not be able to.

![image](https://user-images.githubusercontent.com/31770504/66153021-b5655080-e5e8-11e9-82a3-9c99c082ffd8.png)

**Comment by JuanitaMiles** [comment]
This applies to holidays as well.

**Comment by mmbanong** [comment]
Dan it looks like I need a formula to evaluate all inspection requests and only confirm a request if it is not scheduled on a weekend. Can I have some directions on this?

**Comment by JuanitaMiles** [comment]
This looks like it was fixed.
