### ISSUE TITLE
Building - Minor Grading - Grading Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#197]
We discussed previously and may have corrected it but it is not showing under the details page. We need the impervious area to be a field under site specifics for all grading permits.

AP # 238569

logged by tiffany martin 3/5/19

**Comment by megisys** [comment]
Huh.. How does grading have impervious area.. If you are grading it.. you have the opposite problem.. CON --- FUSED --- :)

**Comment by dhenry-KCI** [comment]
This is part of stormwater compliance - need to know impervious area. This field is on the paper application for a minor grading permit. Need to add the field to the Grading Details tab, under Site Specific Section

![image](https://user-images.githubusercontent.com/4129185/54370525-22fe5f00-464e-11e9-829a-b0f84f6541ea.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
This has been corrected tm 3/19/19
