### ISSUE TITLE
Use - Land use 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1970]
missing the NFC not Frederick county option in the results for completeness check on land use permits. 
![image](https://user-images.githubusercontent.com/47611580/66155360-75549c80-e5ed-11e9-9382-8fbb151bae3e.png)

**Comment by calequin** [comment]
added nfc to filter code

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/66329864-45fba380-e8fd-11e9-9f09-f009b5bd92ac.png)
