### ISSUE TITLE
Use- Land Use - Fees 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1971]
did not get the health department $50.00 fee which should have populated because the check box was marked for portable being used 
did not get a review for the health department - should have had two reviews 
one for hd food services and one for environmental health because there is portables 
![image](https://user-images.githubusercontent.com/47611580/66155697-383cda00-e5ee-11e9-9ec0-333388c8ec68.png)

**Comment by calequin** [comment]
reviews did populate
![image](https://user-images.githubusercontent.com/47603568/66162106-50fbbe80-e5f3-11e9-8fe0-9b0492aebf6b.png)

**Comment by calequin** [comment]
fixed fee formula

**Comment by JuanitaMiles** [comment]
May need to update the formula further. If an application has Food Service only, and not portable toilets, the health review fee should not populate. It should only populate when Portables are checked and/or the parcel is on well/septic.

Any fees required for food service are paid directly to the Health department and are not assessed by Ashlye's department.

![image](https://user-images.githubusercontent.com/31770504/66327211-74c34b00-e8f8-11e9-90cf-d5f5a923dbe9.png)

![image](https://user-images.githubusercontent.com/31770504/66327253-87d61b00-e8f8-11e9-8d8f-89202e489b14.png)

![image](https://user-images.githubusercontent.com/31770504/66327355-b5bb5f80-e8f8-11e9-999c-439443603539.png)

**Comment by ABonomo21** [comment]
created a new permit and the retest failed- did not get a health fee when there was portables L245700
![image](https://user-images.githubusercontent.com/47611580/66502604-96a50500-ea93-11e9-81b8-d1b994088b2c.png)

![image](https://user-images.githubusercontent.com/47611580/66502631-a4f32100-ea93-11e9-94c4-b016de46157a.png)

**Comment by JuanitaMiles** [comment]
Appears to work fine for when portables is required and not required.
