### ISSUE TITLE
Use -Land Use _ revision fee 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1972]
system generated a revision fee when only the health department did a resubmit - this should not require a revision fee automatically. 

if their re-submission requires us to add internal agency or amend the application then staff should manually add the fee 
![image](https://user-images.githubusercontent.com/47611580/66155972-c022e400-e5ee-11e9-8ac8-2466361babf8.png)

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
tested l244624
