### ISSUE TITLE
Use- Land Use - Inspection assignment 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1974]
no inspection assignment was completed for land use inspection permit l244679
building and fire 
![image](https://user-images.githubusercontent.com/47611580/66156267-5820cd80-e5ef-11e9-9f9b-c9cca6111506.png)

**Comment by mmbanong** [comment]
Created new inspection assignment group for Election Districts and completed inspection assignements for Home Occupation and Land Use AP Types for USE module
	Except the following that returned Error: Inspection type is not Effective
   1. HOMEOCCUP-Home Occupation
	SITE- SITE INSPECTION
	BLDG-FRAME FRAMING INSPECTION
	DOLS22- OFFICE OF LIFE SAFETY
   2. LANDUSE-Land Use-Temp Outdoor Activity
	FIRE-FIN- FIRE FINAL INSPECTION []
	BLDG-FRAME FRAMING INSPECTION
	DOLS22- OFFICE OF LIFE SAFETY

**Comment by JuanitaMiles** [comment]
Not Fixed. Inspections are not assigning for this Land Use permit.

![image](https://user-images.githubusercontent.com/31770504/66327655-2c585d00-e8f9-11e9-9134-cd35f8553c19.png)

**Comment by mmbanong** [comment]
I donnot know what else to do because I have assigned the inspections as requested from building
 Maybe Dan needs to take a look at this point

![image](https://user-images.githubusercontent.com/47392173/66328505-c1a82100-e8fa-11e9-9986-02a022ac9351.png)

**Comment by ABonomo21** [comment]
dan fixed 10.15.19
