### ISSUE TITLE
Use Permits - Land Use - Update to Detail Page during Awaiting Applicant Resubmit

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1975]
I was able to update my Land Use Intake Details during the Awaiting Applicant Resubmit milestone (Under Review resubmit). I should not be able to make changes to the detail page at this point. I should only be able to make changes the Completeness Check resubmit.

![image](https://user-images.githubusercontent.com/31770504/66156290-6373f900-e5ef-11e9-83e0-6f688eb3872b.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
fixed
