### ISSUE TITLE
Use - Land Use Inspection 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1976]
also let me result a failed inspection with out comments L244679

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
It is now requiring comments but i put in a fairly long comment (in comparison to what we normally enter) but it keeps asking me to enter comments.

![image](https://user-images.githubusercontent.com/31770504/66329130-fe284c80-e8fb-11e9-8b67-645a1c6278a1.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
fixed
