### ISSUE TITLE
Use- Land Use - Reinspection fee wrong ! 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1977]
re- inspection fee for land use permit l244679 generated at $48.00 instead of $49.00... 
![image](https://user-images.githubusercontent.com/47611580/66156619-02005a00-e5f0-11e9-92ac-3e3ffbcf0d01.png)

also the fee generated as a fire re-inspection 1st fee, that is a fire marshal inspection not a life safety fee/ this needs to be corrected.. if you have the correct fee generating then the value would have been correct 
![image](https://user-images.githubusercontent.com/47611580/66156705-3247f880-e5f0-11e9-8b10-f26cd990d8c6.png)

**Comment by calequin** [comment]
fixed. apologies, thought fire fee went with the fire final. changed it to life safety reinspection fee

**Comment by ABonomo21** [comment]
cannot test due to ticket #1990 - unable to fail an inspection to make sure the correct re-inspection fee generates with the correct fee.

**Comment by calequin** [comment]
fixed 1990 please try again

**Comment by JuanitaMiles** [comment]
Looks good

![image](https://user-images.githubusercontent.com/31770504/66333060-24ea8100-e904-11e9-8a68-40f8f57fe404.png)
