### ISSUE TITLE
Use- Land Use - Re-inspection fee notification 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1978]
i am not receiving notifications via email when a re-inspection fee is required to be paid.

**Comment by mmbanong** [comment]
Created new notification for Use- Land Use - Re-inspection fee
![image](https://user-images.githubusercontent.com/47392173/66402309-a26cca80-e9b2-11e9-93e2-98350757475c.png)

![image](https://user-images.githubusercontent.com/47392173/66401544-51100b80-e9b1-11e9-841f-eee7f21e9d3c.png)

![image](https://user-images.githubusercontent.com/47392173/66400414-6dab4400-e9af-11e9-8482-a08640f3260f.png)

![image](https://user-images.githubusercontent.com/47392173/66398998-c4fbe500-e9ac-11e9-8f17-72764de8d69a.png)

**Comment by ABonomo21** [comment]
tested Re-inspection fee generated on L244665 and i did not receive any notification

**Comment by mmbanong** [comment]
Added new formula in the Fee AfterAdd Event. Give it another try
![image](https://user-images.githubusercontent.com/47392173/66507767-cfe27280-ea9d-11e9-9789-e963f680e42c.png)

**Comment by JuanitaMiles** [comment]
cannot test. get the following error when trying to result an inspection as failed.

![image](https://user-images.githubusercontent.com/31770504/66761614-5918f100-ee72-11e9-9290-e49c9cf6ec84.png)

**Comment by ABonomo21** [comment]
dan fixed
