### ISSUE TITLE
Use - Land Use- Partial Passed Inspection 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1979]
partial passed inspection does not show as partially passed on the result, you have to go into the inspection- we need the is partial-ed column to show next to the inspection result 
![image](https://user-images.githubusercontent.com/47611580/66157519-ee55f300-e5f1-11e9-93ae-e73cfda9ce71.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/66163404-e009d600-e5f5-11e9-81c2-a6a4189d984d.png)

**Comment by JuanitaMiles** [comment]
confirmed the column is added.

![image](https://user-images.githubusercontent.com/31770504/66329288-46476f00-e8fc-11e9-9726-03d9473b8f11.png)
