### ISSUE TITLE
Planning - pwConstruct - Expire Date

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#198]
The approved date on the JOb Description tab should = the Public Works Mylar Review date. 

Currently approved date set as date of completion check.

See AP237284 for issue

**Comment by megisys** [comment]
Approved Date will not Set.. Will use the detail page date for reports

**Comment by dhenry-KCI** [comment]
If we need to use the details page, we need to make that a condition and add an admin closure review or somehow require it at the time of MYLAR review.
Closed with no date 
areed
![image](https://user-images.githubusercontent.com/4129185/55356831-a070fe80-5499-11e9-973d-287a3c121414.png)
![image](https://user-images.githubusercontent.com/4129185/55356845-abc42a00-5499-11e9-9b59-a3d55c9ac9ce.png)

**Comment by megisys** [comment]
Status Check added at Admin Closure

**Comment by dhenry-KCI** [comment]
corrected - verified PW239036, application will not close without expiration date completed on details page
areed
