### ISSUE TITLE
Use Permits - Land Use - Inspection Results on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1980]
When I look at my permit in Rhythm, I see all of my inspection results listed. However, the highlighted building final inspection was a partial passed inspection. The results showing here are misleading. People will wonder why another building final inspection has generated if the 2nd shows as "passed".

Is there a better way for them to know that it was a partial passed inspection?

![image](https://user-images.githubusercontent.com/31770504/66157790-8522af80-e5f2-11e9-956f-da8fd09ad832.png)

**Comment by calequin** [comment]
The view details tab of the application gives them the partial pass information. If we want the result code to be partial passed then a result of partial passed needs to be created and workflow changes.

**Comment by ABonomo21** [comment]
I think this is something we will have to deal with until we get complaints or enough confusion that would require us to re-design all those inspection workflows. I am going to close the ticket knowing the applicant can see a partial passed under view details. Will re-address in the future if needed.
