### ISSUE TITLE
Use - Land Use- Official issuance 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1982]
please see highlighted below
drawing 
construction and plot should be removed from the report... 
total paid fees says $0.00??? 
and we need to be consistent on how we are dating 
![image](https://user-images.githubusercontent.com/47611580/66157991-ef3b5480-e5f2-11e9-8629-546cd7815cc1.png)

**Comment by ABonomo21** [comment]
finally, i would like the formatting to be consistent as far as capital letters or lower case letters- i know this is being pulled by how it is in the system but i think it would look better if it was all uniform.

**Comment by TaraF** [comment]
Updated / fixed from above:

1) construction and plot should be removed from the report...
2) total paid fees says $0.00???
3) and we need to be consistent on how we are dating

ready for re-test.

**Comment by ABonomo21** [comment]
fixed dan fixed l250750
