### ISSUE TITLE
Use- Land Use - Permit issued 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1983]
i received two emails that my permit was issued for land use
![image](https://user-images.githubusercontent.com/47611580/66158185-6244cb00-e5f3-11e9-9340-edbc413eb7b7.png)
![image](https://user-images.githubusercontent.com/47611580/66158213-6e308d00-e5f3-11e9-88f9-920b41443009.png)
same email...

**Comment by calequin** [comment]
fixed. two conditions were listed in the use app. I expired NOT-ISSUE

**Comment by ABonomo21** [comment]
only received one notification for land use permit L245682

![image](https://user-images.githubusercontent.com/47611580/66335475-12bf1180-e909-11e9-825f-91157d0f8edf.png)
