### ISSUE TITLE
Use- Land Use - Batch Manager 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1984]
we had to manually run the batch manager- when we did 
after batch manager was run i received two emails with the attached issued permit 
![image](https://user-images.githubusercontent.com/47611580/66158327-b3ed5580-e5f3-11e9-90b5-b68a756a6a94.png)

**Comment by megisys** [comment]
Someone Added it twice. Updated Batch Manager and removed duplicate

**Comment by JuanitaMiles** [comment]
Appears fixed. batch manager ran automatically and i got one official issuance corresspondence. L245704
