### ISSUE TITLE
Use - Land use - Placard 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1985]
i am not receiving any notifications with the attached placard for land use only the issued permit- after manually running the batch manager -  related to ticket #1984

**Comment by mmbanong** [comment]
I got both the Permit Issued notification and the Correspondence email with attachment

![image](https://user-images.githubusercontent.com/47392173/66220116-6aa41100-e69a-11e9-9236-483a06693d88.png)

![image](https://user-images.githubusercontent.com/47392173/66220238-a8a13500-e69a-11e9-9d26-0f4ae3a2a9dc.png)

**Comment by ABonomo21** [comment]
I did not receive a copy of the **PLACARD**. That is the issued permit. @dhenry-KCI

**Comment by mmbanong** [comment]
Created new correspondence formula USE_PLACARDISSUANCE
 Changed report name from "PLC-300 Single Use Placard" to Single_Use_Permit_Placard
 Added new report to Correspondence set up
 Scheduled correspondence at the Permit issued milsestone

![image](https://user-images.githubusercontent.com/47392173/66676027-9bed8580-ec34-11e9-9ece-d121972203a0.png)

**Comment by ABonomo21** [comment]
dan fixed tested under l250750
