### ISSUE TITLE
Use Permits - Land Use - EH Review Generating

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1989]
This Land Use permit was submitted with N/A as the sanitary type and the parcel is on public water/sewer. An EH review should not have generated.

![image](https://user-images.githubusercontent.com/31770504/66328240-40508e80-e8fa-11e9-9d8d-c570010600d8.png)

![image](https://user-images.githubusercontent.com/31770504/66328318-6bd37900-e8fa-11e9-902f-c7bff5db7341.png)

![image](https://user-images.githubusercontent.com/31770504/66328373-80b00c80-e8fa-11e9-8ac6-9a4f552f43fe.png)

**Comment by megisys** [comment]
Addressed THis

**Comment by JuanitaMiles** [comment]
CORRECT

![image](https://user-images.githubusercontent.com/31770504/66504056-5d21c900-ea96-11e9-98f7-bfac1ba63ae7.png)
