### ISSUE TITLE
Planning - PwConstruct - Expire Date

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#199]
The Expire date should = the Approved Date + 2 years.

Currently Expire date set to 5 years.

See AP PW237284

**Comment by megisys** [comment]
This will set after the hearing milestone.. As approval will not be set until later.. Which means applications before this milestone will never have an expiry date.

**Comment by dhenry-KCI** [comment]
failed.  There isnt a hearing milestone in PWCONS

![image](https://user-images.githubusercontent.com/4129185/54767515-ac280f80-4bd3-11e9-8c16-bb040115a681.png)

**Comment by megisys** [comment]
When does it get appproved ?

**Comment by dhenry-KCI** [comment]
Corrected - areed
