### ISSUE TITLE
Use- Failed inspection comments 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1990]
I am entering comments in the for the failed inspection and the system is still telling me i need comments to be entered 
![image](https://user-images.githubusercontent.com/47611580/66329344-5d865c80-e8fc-11e9-8965-187d07f38bf3.png)
![image](https://user-images.githubusercontent.com/47611580/66329379-670fc480-e8fc-11e9-80e9-16c8467b493d.png)

**Comment by calequin** [comment]
fixed. added text amount check to the formula and also included it to check if it is a partial inspections

**Comment by JuanitaMiles** [comment]
fixed

![image](https://user-images.githubusercontent.com/31770504/66334465-1ce01080-e907-11e9-8f6c-0203016d75b8.png)
