### ISSUE TITLE
Trade License Card Information 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1991]
Shannon's name generated on her card with her title which is intended to be used for Jr. Sr. III. etc.  

Shannon was able to put her job title in the field which resulted in that being added to her name on the license card. This is going to be a larger issue, is is possible to limit the number of characters in the field or re-title somehow so that customers know what is intended by title i.e. Suffix..?? 

![image](https://user-images.githubusercontent.com/47611580/66331561-e0a9b180-e900-11e9-97ed-22b31b49433c.png)

**Comment by dhenry-KCI** [comment]
will check with @calequin to add tooltip functionality here.

**Comment by calequin** [comment]
on the report. which field is this pulling from? @dhenry-KCI

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/66490092-9fd7a700-ea7e-11e9-9daa-b9b03e49bbd2.png)

the title block the contact information

**Comment by ABonomo21** [comment]
@calequin see above

**Comment by dhenry-KCI** [comment]
@calequin - let's meet 10/10 to discuss

**Comment by calequin** [comment]
The title portion doesnt come across in Rhythm since you dont input your own information when applying. Title box is strictly back office and has a tool tip box with instructions.
![image](https://user-images.githubusercontent.com/47603568/66582882-0f659900-eb48-11e9-88a9-b2686e97f144.png)
