### ISSUE TITLE
R4C- Updating Contact information 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1992]
Updating contact information on R4C seems to be a challenge and not all the original information asked for is not in the update contact information. 

Need to re-test as a group to see how many data fields are not showing up on the update contact information one we know of was "title"

**Comment by dhenry-KCI** [comment]
![r4c Contacts](https://user-images.githubusercontent.com/4129185/66336051-55351e00-e90a-11e9-8be8-33b14cf45ccd.PNG)
![creat contactr4c](https://user-images.githubusercontent.com/4129185/66336054-57977800-e90a-11e9-9b8a-e3ce7bdf90b7.PNG)

was able to edit and update my information in r4c.  Scheduling meeting to look at how infomration is reported in IPS.

**Comment by ABonomo21** [comment]
I don't think this is the correct screen- Lets meet to discuss.

**Comment by ABonomo21** [comment]
@dhenry-KCI 
need a meeting

**Comment by dhenry-KCI** [comment]
@ABonomo21 - can you confirm a meeting is needed for this?

**Comment by ABonomo21** [comment]
only change 
last name
address 
phone number 
add note if changing email you will need to create a new account
