### ISSUE TITLE
Building Permits - Fire Permit - Inspection Assignment

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1993]
The second cycle Fire-Insul inspection did not assign to anyone when it generated. It should have assigned to Kim Fulcher.

![image](https://user-images.githubusercontent.com/31770504/66339351-fa52f500-e910-11e9-939d-5260b8a9fad0.png)

**Comment by ABonomo21** [comment]
@dhenry-KCI

**Comment by JuanitaMiles** [comment]
inspection assignments appear to be adding, will monitor for additional inspection types during end to end.

![image](https://user-images.githubusercontent.com/31770504/66950114-c7ea7b80-f025-11e9-8864-fa32888fd0a2.png)
