### ISSUE TITLE
Building Permits - Missing Fee and Review Generation 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1994]
Testing another issue for COP I created a building permit 246848 and it skipped over plan review payment and plan review and went straight to impact fee generation ... why... ???? 
![image](https://user-images.githubusercontent.com/47611580/66340435-266f7580-e913-11e9-9a64-3958dce589db.png)

**Comment by megisys** [comment]
That Address has a FR Planning Region still set.  I cleared this out as we are not using this method anymore

**Comment by ABonomo21** [comment]
retested under permit 246853 and the fees came up. and reviews and related permits generated
