### ISSUE TITLE
Liquor License Renewal Notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1996]
Create notification at awwaiting renewal fee.

**Comment by TaraF** [comment]
There is no fee amount associated, it says $0 on the notification.  AP#   Fee should be $650.

**Comment by megisys** [comment]
NOTIFY log piece was missing - I added this.. NOT related to this issue

**Comment by calequin** [comment]
fixed

**Comment by dhenry-KCI** [comment]
Confirmed fixed.
