### ISSUE TITLE
Recalculation of unpaid fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1997]
Need to have a system wide job that updates all unpaid fees- should have a meeting @dhenry-KCI with Mike, Ash 2x and gary, dan  to make review these requirements

trade license, 
permit app fees,
planning fees 
impact fees 

not applicable to distributor report fees.

**Comment by dhenry-KCI** [comment]
Scheduled. Will reopen depending on outcome.

**Comment by megisys** [comment]
Need a Job to Recalculate Unpaid Fees as a Batch Manager Job

**Comment by dhenry-KCI** [comment]
Need a batch job that looks for outstanding fees for each AP that would update based on the new fee amount. Would automate 2x per year - December 31st, and June 30th. Would allow manual run as well. 

Building permits - school construction fees that will have an increase before permit is issued but have already paid the impact fee. 

Ad Hoc- planning with unpaid construction fees (end of December, end of June for all outstanding fees - separated by fee type
