### ISSUE TITLE
New Licenses created within the renewal period

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1999]
need a meeting to discuss when dan is here next week should have Gary, Shannon, Ash Juanita and Dan @dhenry-KCI

**Comment by ABonomo21** [comment]
PM245519

**Comment by dhenry-KCI** [comment]
scheduled.

**Comment by dhenry-KCI** [comment]
Would like to see this configured before go-live if time allows. Needed for April 2021
