### ISSUE TITLE
License - Plumbing License - Renewal Review Result Codes

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2]
Resulting the Renewal Review:
- When trying to input a result for the Renewal Review, there are too many Review Result code options. These options need to be filtered to include only the normal options: Approved, Denied, Resubmit, and Waived (N/A? Are we replacing waived with N/A like the rest of the application?)

This occurs on Plumbing Master License, Pluming Journeyman License, 
Steps to Replicate:
>Click Reviews Tab
>Click Check Box next to Renewal Review type.
>Click Record Results
>Click the pop up icon on the Result field.

![image](https://user-images.githubusercontent.com/31770504/52235564-77b1fb80-2892-11e9-885a-b1360073ccf8.png)

**Comment by pooldaddy** [comment]
fixed see screenshot


![screenshot](https://user-images.githubusercontent.com/47391482/52356473-45271080-2a02-11e9-9306-77c3c14cb35e.jpg)

**Comment by JuanitaMiles** [comment]
Tested - Result Codes appear to be filtered properly for the Renewal Review.

**Comment by dhenry-KCI** [comment]
leaving open to confirm security and permissions associated to denied result option - ab 2.13.19
