### ISSUE TITLE
Use - Land Use - Land Use Codes on the Details Page

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#20]
(Reported by Kelly Vanaman and Tolson DeSa 2/7/19)

We would like to update the Land Use code options on Start Application Land Use permit (Use Module). Please refer to the attached Land Use Codes excel spreadsheet for the requested updates.

![image](https://user-images.githubusercontent.com/31770504/52439982-ec7f7280-2aea-11e9-9fc1-97952598aebb.png)

[Land Use Code Updated 2.7.19 revised.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/2842525/Land.Use.Code.Updated.2.7.19.revised.xlsx)

**Comment by ABonomo21** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54832869-67fc4400-4c93-11e9-920f-69409c42ce1c.png)
