### ISSUE TITLE
PLANNING-PWCONSTRUC - remove minor type

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#200]
Remove minor type under Details page under PWCONSTRUC
![image](https://user-images.githubusercontent.com/4129185/53963774-f1205200-40bb-11e9-8a21-54588b2704c6.png)

**Comment by megisys** [comment]
They are read only now as historic Applications you will need to see this

**Comment by dhenry-KCI** [comment]
Confirmed read only under PWCONSTRUC - details
