### ISSUE TITLE
Trade License - Plumbing Master - Automatic Resubmit Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2001]
I resubmitted as the applicant on completeness check on R4C, and the application did not automatically move back to Completeness Check.

![image](https://user-images.githubusercontent.com/31770504/66499490-f13b6280-ea8d-11e9-8956-66d130207073.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/66499536-03b59c00-ea8e-11e9-979a-c35db9e2474f.png)

**Comment by ABonomo21** [comment]
when we try to check status on this application it gives the following errors.. 
![image](https://user-images.githubusercontent.com/47611580/66499703-52fbcc80-ea8e-11e9-8567-4299a65e1dd3.png)

**Comment by ABonomo21** [comment]
once i close out of the application for the **second** time it moves into completeness check.

**Comment by calequin** [comment]
fixed. tested on a resubmit for the first time around and it progressed correctly.

**Comment by JuanitaMiles** [comment]
fixed.

![image](https://user-images.githubusercontent.com/31770504/66946889-e483b500-f01f-11e9-9a7e-013bb45d0253.png)
