### ISSUE TITLE
Trade License - Plumbing - Processed and Issued by 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2002]
The processed name originally was Ashlye but when the permit moved to issued it changed to Juanita( Gerry) and the issued name is ashlye 
![image](https://user-images.githubusercontent.com/47611580/66500034-e2a17b00-ea8e-11e9-95ed-9084a947c35e.png)

lic# pm245520

**Comment by ABonomo21** [comment]
it did the same thing on PJ245521 and i was able to capture the before and after
![image](https://user-images.githubusercontent.com/47611580/66500648-e8e42700-ea8f-11e9-9268-a4a6bd2a1ae9.png)
![image](https://user-images.githubusercontent.com/47611580/66500806-2ba5ff00-ea90-11e9-9f06-351884163b71.png)

**Comment by JuanitaMiles** [comment]
need to test this when the Fees are working on R4C. Our issue occurred when processing through rhythm.
