### ISSUE TITLE
Trade License - Plumb Master - Awaiting Renewal Details Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2003]
At the Awaiting Renewal Details milestone, I paid the renewal fee on R4C then it immediately went to Renewal Review without requiring the Confirm License Details page to be populated.

![image](https://user-images.githubusercontent.com/31770504/66500382-6ce9df00-ea8f-11e9-94fc-8deeae014983.png)

![image](https://user-images.githubusercontent.com/31770504/66500397-75421a00-ea8f-11e9-9121-b95084e4c28d.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/66500470-94d94280-ea8f-11e9-9cd0-5958a85c4075.png)

**Comment by ABonomo21** [comment]
did the same on pj245521

**Comment by calequin** [comment]
sent email to Amy C. for a webex walkthrough on this issue

**Comment by calequin** [comment]
working. added updateparentobject formula.
steps taken: applied for new tl, took TL to renewal period. paid fees first and then updated detail pages. went to the correct renewal review milestone.

**Comment by calequin** [comment]
readded ready for retest label. looks like it was removed but not sure if it failed retest

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68421592-8c4a5980-016c-11ea-9f37-129d93d41333.png)
![image](https://user-images.githubusercontent.com/47611580/68421601-92403a80-016c-11ea-8069-86a7f6f22d8b.png)
