### ISSUE TITLE
Use Permit - Land Use - Work Type Not Needed

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2004]
The only option available for Land Use Work Type is INDIVIDUAL, can we just auto fill this with individual instead of making this a required field the applicant has to pick??

![image](https://user-images.githubusercontent.com/31770504/66501852-2f3a8580-ea92-11e9-8409-7145209f4f23.png)

**Comment by calequin** [comment]
this will require lots of formula changes in back office under fees, reviews. Originally Landuse was using Seasonal as a work type therefore formulas have that as a call.

**Comment by ABonomo21** [comment]
Dan fixed in 3 minutes.
