### ISSUE TITLE
R4C - Address on the Create a Profile Page

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2008]
The address on the Create a Profile page says 1 E Church Street. This should say 30 N Market to be consistent with the rest of the site.

![image](https://user-images.githubusercontent.com/31770504/66754883-f2d9a180-ee64-11e9-8128-f57ab714dbba.png)

**Comment by calequin** [comment]
fixed

**Comment by JuanitaMiles** [comment]
fixed

![image](https://user-images.githubusercontent.com/31770504/66947768-7809b580-f021-11e9-92a5-f9fa76c40fba.png)
