### ISSUE TITLE
Building Permits - Accessory - Building Fee Not Generating

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2011]
The Building fee did not generate for this RESUSE Accessory permit.

![image](https://user-images.githubusercontent.com/31770504/66762612-55866980-ee74-11e9-811a-e53114a90eaf.png)

**Comment by megisys** [comment]
Construction Type was not set.. Made it Required

**Comment by JuanitaMiles** [comment]
My bad, it is working as it should, and the Construction Type is now required.

![image](https://user-images.githubusercontent.com/31770504/66770159-ea915e80-ee84-11e9-9c20-abcadec5664b.png)
