### ISSUE TITLE
PLANNING - PWCONSTRU - Health Fee CMBDEVIMP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#202]
Well and Septic - Health Fee of $75 didn't populate

![image](https://user-images.githubusercontent.com/4129185/53964483-7821fa00-40bd-11e9-9bcb-d242c58f0e08.png)
![image](https://user-images.githubusercontent.com/4129185/53964535-8b34ca00-40bd-11e9-855a-12f1a64d3148.png)
![image](https://user-images.githubusercontent.com/4129185/53964560-95ef5f00-40bd-11e9-9fb2-3ed95610b11e.png)

**Comment by megisys** [comment]
Addressed

**Comment by megisys** [comment]
Addressed

**Comment by megisys** [comment]
See PW237529

**Comment by dhenry-KCI** [comment]
Health Fee is there now but $447 Engineering fee is gone. 2nd image below is from image above showing 447 fee
![image](https://user-images.githubusercontent.com/4129185/55029767-4aa3de80-4fe1-11e9-92de-02b5eeb9892a.png)
![image](https://user-images.githubusercontent.com/4129185/55029812-64ddbc80-4fe1-11e9-8542-09cf5b8131d0.png)

**Comment by dhenry-KCI** [comment]
areed

**Comment by dhenry-KCI** [comment]
corrected - duplicate - areed
