### ISSUE TITLE
Electrical Trade License - Data Migration issue 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2021]
Electrical trade licenses have the wrong expiration dates - Em3137 expired in h7 6.30.19 and it shows as expiring in 11 as 6.30.20
![image](https://user-images.githubusercontent.com/47611580/66841127-34d31800-ef37-11e9-9a9c-28fa12b05242.png)
![image](https://user-images.githubusercontent.com/47611580/66841157-41577080-ef37-11e9-9bb6-0734362acae0.png)
they are all like that ... why is the data not one for one
![image](https://user-images.githubusercontent.com/47611580/66841401-a317da80-ef37-11e9-9ca7-49fe0adcbeac.png)

**Comment by megisys** [comment]
Data Issue. Need to Monitor After Next Migration
