### ISSUE TITLE
R4C - Contact Phone numbers on R4C Portal

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2027]
Wrong number on main R4C Log in page. This number is to the LIBRARY. 
We need to have 3 numbers: 

Permits & Inspections: 301-600-2313
Development Review and Planning: 301-600-1138
Website Support: 301-600-1010
![image](https://user-images.githubusercontent.com/4129185/66927205-6adacf80-effd-11e9-87c1-ab9f0646812e.png)

**Comment by megisys** [comment]
Make the Above information an image on the front page please Christian

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/66934730-94e1c100-f000-11e9-9052-5c0bb4d4b0b0.png)

**Comment by dhenry-KCI** [comment]
love it.

MW
