### ISSUE TITLE
PLANNING - BOND - Details didn't transfer

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2029]
Bond Tracking - Details Tab did not transfer from Hansen7. This is used on all Road Escrow Bonds
Areed

![image](https://user-images.githubusercontent.com/4129185/66945283-c49ec200-f01c-11e9-8168-b5391502dc1e.png)

**Comment by megisys** [comment]
3936 is the Bond

**Comment by dhenry-KCI** [comment]
Spot checked multiple bonds and tracking details are populating. AReed
Closing ticket

**Comment by dhenry-KCI** [comment]
bond is not populating again.  Information was there when retested 11 days ago.

![image](https://user-images.githubusercontent.com/4129185/67709417-46cfa480-f994-11e9-8dc9-9d1f0424baf6.png)

MW/AR

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/67709516-78e10680-f994-11e9-97fe-19009e2ca7ec.png)

**Comment by megisys** [comment]
Data Issues are addressed in Pristine..
