### ISSUE TITLE
Building Permits - Capacity Permit - Meter Description Needs to be Updated

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2030]
Meter Descriptions needs to be updated. Change the highlighted "6"s to "8"s. 

![MeterDesc](https://user-images.githubusercontent.com/31770504/67017516-e5702180-f0c7-11e9-8ace-e91ea2804bef.png)

**Comment by JuanitaMiles** [comment]
@dhenry-KCI @pooldaddy Dustin - Dan said this change needs to be made in Hansen 7.

**Comment by megisys** [comment]
I fixed in IPS 11

**Comment by pooldaddy** [comment]
Corrected in H7  see below:
![image](https://user-images.githubusercontent.com/47391482/67043376-ed47ba00-f0f7-11e9-83da-ee12687eb9e6.png)

**Comment by dhenry-KCI** [comment]
Confirmed fixed.

![image](https://user-images.githubusercontent.com/4129185/67304425-c9062780-f4c1-11e9-933e-89893c5dd572.png)
