### ISSUE TITLE
Building Permits - Capacity Permit - Capacity Receipt and Construction Reports

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2032]
Lauren used a parcel instead of an address for her capacity permit. This seems to be causing issues when pulling information into the reports.

![image](https://user-images.githubusercontent.com/31770504/67020533-587b9700-f0cc-11e9-8d43-b776ff9e6f5d.png)

![image](https://user-images.githubusercontent.com/31770504/67020645-806afa80-f0cc-11e9-8ee3-6fce559209e7.png)

**Comment by JuanitaMiles** [comment]
In addition, the C of O date should never populate with a date. Always leave this blank.

**Comment by TaraF** [comment]
This issue is fixed - and ready for re-test.  Please note, there is likely a data issue with Parcel / address association now because sometime we are seeing 20+ addresses associated to one parcel.

**Comment by JuanitaMiles** [comment]
fixed

**Comment by JuanitaMiles** [comment]
fixed
