### ISSUE TITLE
Building Permits - Capacity Permit - Available Reports

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2033]
Can we remove the highlighted reports from being available for the Capacity Permit?

![image](https://user-images.githubusercontent.com/31770504/67021246-5e25ac80-f0cd-11e9-8cfb-283b0bdbeaa8.png)

**Comment by TaraF** [comment]
Done as requested. Please re-test.

**Comment by JuanitaMiles** [comment]
fixed
