### ISSUE TITLE
Building Permits - Capacity Permits - Report for DUSWM Transactions Completed

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2034]
Tara - DUSWM talked with you about a report for DUSWM Transactions Completed for a date range. 

There were additional reports discussed as well, per email sent by you on 6/28/19. Can you provide a status update for these?

**Comment by TaraF** [comment]
@JuanitaMiles  - let's discuss....your comment above doesn't specify what reports, but my last correspondence with Terry May was that the one additional report she requested was already combined with another report and that it met their needs (with requested few fields additions).
