### ISSUE TITLE
Building Permits - Capacity Permits - Water Fees Manual Add

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2036]
Staff should not be required to manually insert water fees. They should automatically add. The fee base value is always the same and then the detail page information drives the additional calculation. This is the same for sewer fees.

![image](https://user-images.githubusercontent.com/31770504/67024180-fa51b280-f0d1-11e9-8f43-c8ac7207c290.png)

**Comment by megisys** [comment]
Understand also why the Sewer Fee is not Calculating.

**Comment by megisys** [comment]
The Sewer Fee didn't calculate as it was a skating rink and the Override CAF method needs to be used,
Subdivision o4T100 has no associated water fee. So it has to be manually added.. Other subdivision add if they were provided.

**Comment by JuanitaMiles** [comment]
Combining all fee issues into this ticket. We need to capture fee issues as we come across them and fix them for now. Closing tickets #1196  #1819 .

**Comment by JuanitaMiles** [comment]
added this issue to "Future_Phases" tracking repository.
