### ISSUE TITLE
PLANNING - PWCONSTRUC # of pages dashboard is wrong

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2037]
PW252078 #of pages is showing and the application is not showing on the dashboard report.
AReed
![image](https://user-images.githubusercontent.com/4129185/67024954-39ccce80-f0d3-11e9-95bd-38b591f4b170.png)
![image](https://user-images.githubusercontent.com/4129185/67025015-4fda8f00-f0d3-11e9-84ba-ecd31ecdc8ba.png)

**Comment by megisys** [comment]
Did you hit refresh ?

**Comment by dhenry-KCI** [comment]
tested and verified on PW252078 

AR
