### ISSUE TITLE
PLANNING-PWCONSTRUC - fees for CMBDEVIMP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#204]
Fee for $145 populated on re submission. This is incorrect. Remove $145 fee

![image](https://user-images.githubusercontent.com/4129185/53965588-7eb17100-40bf-11e9-8fad-912b46eb3b1f.png)

**Comment by megisys** [comment]
What Type is a resubmission ? PLease ensure you are keeping an eye on all PWConstucts.. if WorkType of XYZ then no Fee, but all other are oko..

**Comment by dhenry-KCI** [comment]
A resubmission is any submission after the first review on any plan type. Please see Application number referenced PW237529. Please note the $145 for Engineering Fee-Improvement Plan does not apply to any applications. The only place we have a $145 fee is under a Major Revision REVMJIMPRV and it is under Major Revision - Engineering Fee $145 so it is different. I believe you can remove the $145 for Engineering Fee-Improvement Plan 
![image](https://user-images.githubusercontent.com/4129185/54381407-11c04d00-4664-11e9-8861-c30c6cacd6ec.png)
![image](https://user-images.githubusercontent.com/4129185/54381433-243a8680-4664-11e9-942b-4e5006d6f389.png)

**Comment by megisys** [comment]
Completed

**Comment by dhenry-KCI** [comment]
Fees incorrect CMBDEVIMP
Missing DUSWM fee for lines $325
Missing Engineering - Initial fee $447
![image](https://user-images.githubusercontent.com/4129185/54942808-45259600-4f06-11e9-9ba4-e0a44d16fbdb.png)
![image](https://user-images.githubusercontent.com/4129185/54942844-57073900-4f06-11e9-9898-399b7c806574.png)
![image](https://user-images.githubusercontent.com/4129185/54942881-6d14f980-4f06-11e9-9243-5e71e0c85ba9.png)

**Comment by dhenry-KCI** [comment]
areed

**Comment by dhenry-KCI** [comment]
corrected - duplicate areed
