### ISSUE TITLE
PLANNING - Dashboard for Mylar Review & Signature Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2041]
New dashboard needed for All plans that get a Mylar Review/Signature review so we can assign the review. AReed

**Comment by JuanitaMiles** [comment]
The PL - Paperwork Review Assignments Required dashboard report has been created.

**Comment by dhenry-KCI** [comment]
Verified report and added to my dashboard. AREED
