### ISSUE TITLE
planning-town review populated on PWConst but parcel not in town

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2043]
![image](https://user-images.githubusercontent.com/4129185/67039397-452df300-f0ef-11e9-973d-1154a7aef5d5.png)

![image](https://user-images.githubusercontent.com/4129185/67039424-4fe88800-f0ef-11e9-9aa6-a0f6fc979fc4.png)

MW

**Comment by megisys** [comment]
No LInked Parcel
