### ISSUE TITLE
planning-pwcon-went to 2nd review without applicant resubmittal

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2045]
did internal review

![image](https://user-images.githubusercontent.com/4129185/67039908-5d524200-f0f0-11e9-893d-355c3580b1e1.png)

did it again on 3rd.
![image](https://user-images.githubusercontent.com/4129185/67040027-a0141a00-f0f0-11e9-87bf-11b1b36b2d1c.png)

MW

**Comment by megisys** [comment]
Changed it incase we change paths.. Test the waive readd

**Comment by dhenry-KCI** [comment]
PW252124 Verified Corrected AREED
