### ISSUE TITLE
Planning - Address is supposed to auto flip to parcel ID

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2046]
If address is entered, it is supposed to automatically flip to the parcel ID. This feature is not working. 
PW252093 AReed
![image](https://user-images.githubusercontent.com/4129185/67097527-4a8b4c00-f188-11e9-817d-b7569c57dfe2.png)

**Comment by megisys** [comment]
This address has no linked Parcel.

**Comment by dhenry-KCI** [comment]
Duplicate Address - GIS to correct. This one corrected by DG and AR
