### ISSUE TITLE
Building Permits - Driveway - R4C Detail Page Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2048]
Disturbed Area should not be required.
Building App No # clean up to read Building Application "#"
Plat No # clean up to read Project # for Related Plat (if applicable)
Remove Historical Data Header.

![image](https://user-images.githubusercontent.com/31770504/67210987-fed6dd80-f3e7-11e9-8fd5-5409d80e5797.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/67313260-afb8a780-f4d0-11e9-9a5c-900cf9345462.png)
