### ISSUE TITLE
Building Permits - Driveway - Notification for Awaiting Fee Payment

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2049]
Dan needs to fix the Awaiting Payment Bond Check Ntoficiation formula. It is erroring when trying to result the completeness check. He turned it off for now.

And BP Awaiting Fee Payment Notification, erroring on trying to result Review with resubmit

And Issue Permit Notification

**Comment by ABonomo21** [comment]
issued permit notification worked

**Comment by ABonomo21** [comment]
Dan needs to fix the Awaiting Payment Bond Check Ntoficiation formula. It is erroring when trying to result the completeness check. He turned it off for now.- working 10.22.19 ab notification came through

And BP Awaiting Fee Payment Notification, erroring on trying to result Review with resubmit- working 10.22.19
