### ISSUE TITLE
General-Error Message When Creating New Permit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#205]
Started a New Application for and Electrical Permit. Started Application, input Application Type as Electrical Permit and then this Error Message Generated-MCoffman

![image](https://user-images.githubusercontent.com/47611580/53965936-1ca53b80-40c0-11e9-8f65-ae6d88607723.png)

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
confirmed fixed-aw-was able to create new permit.
![image](https://user-images.githubusercontent.com/47611580/54148788-3e2d5c80-440b-11e9-8309-94c97ba82cdb.png)
