### ISSUE TITLE
Building Permits - Driveway - Applicant Action on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2050]
Remove the "link" hyperlink.
And the html language.

![image](https://user-images.githubusercontent.com/31770504/67212950-28ddcf00-f3eb-11e9-8224-3c5f89124858.png)

**Comment by megisys** [comment]
The HTML Stuff is known and will be addressed in a future release.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/67313638-4be2ae80-f4d1-11e9-8c76-a23a11b7de7e.png)
