### ISSUE TITLE
Building PErmits - Driveway - Intake Details on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2051]
Did not save the original detail page information from application. We are resubmitting at the Under Review milestone and should not be able to edit these details, but the original ones need to be saved.

![image](https://user-images.githubusercontent.com/31770504/67213204-9a1d8200-f3eb-11e9-9034-beb4aa7c3ae2.png)

**Comment by megisys** [comment]
Why are we resubmitting after completeness check. When we get to under review. The changes will need to be made by back office as set out in the applicant actions.

**Comment by JuanitaMiles** [comment]
The details page is clearing itself out of all original information that was input when we entered the awaiting revision fee payment milestone. We werent trying to edit the details at this stage, but we found that there was no longer any information on this page.

**Comment by megisys** [comment]
Awaiting Christian

**Comment by calequin** [comment]
fixed. added moniker to rest services.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68415946-797e5780-0161-11ea-939c-fe09f2c28d14.png)
