### ISSUE TITLE
Building Permit - Driveway/Grading/FRO - Assigned To Inspections

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2053]
Need to have auto assignments on inspections for Driveway, Grading and FRO.

Eric to deliver the assignments then Dan to update.

**Comment by JuanitaMiles** [comment]
@megisys Please make the following inspection assignments for Driveway, Grading and FRO permits.

ECS Inspector region assignments:

Bob Cramer: 1,6,7,10,12,14,21-25

Matt McGrew: 3,4,5,8,11,13,15-20,26

**Comment by megisys** [comment]
This is a forever changing piece. And is pure data entry. Who in the county is the responsible person for this ?

**Comment by aritterbusch** [comment]
I'm taking this on on the County side (aritterbusch@frederickcountymd.gov)
Andreas.

**Comment by aritterbusch** [comment]
**Completed**.
Handed back to dhenry-KCI (email notification)

**Comment by ABonomo21** [comment]
this was not completed - Dan checked - see inspections PI_BASECS

**Comment by dhenry-KCI** [comment]
@aritterbusch@frederickcountymd.gov it looks like you completed the inspection assignmanets for FRO and Driveway but we still need the assignments completed for the following Grading Inspection Types

![image](https://user-images.githubusercontent.com/4129185/67502468-e539ce00-f653-11e9-8ca2-12a25a6dd630.png)

**Comment by aritterbusch** [comment]
No, can't.
**None of these allow entry**. Any with a ...=1234 (numeric value) in the name will kick back with the following error message:
![image](https://user-images.githubusercontent.com/22638668/67503299-62197780-f655-11e9-9164-e11ea8ffff06.png)
My understanding was that these are some sort of duplicates and to ignore them.

**Comment by ABonomo21** [comment]
assignments fixed

**Comment by ABonomo21** [comment]
inspectors are not auto assigning - are just a few examples

251597
251602

**Comment by megisys** [comment]
These permits were added to Parcels. Building Permits need to be addresses

**Comment by megisys** [comment]
Please test Parcel Inspections

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69353245-32f22800-0c4c-11ea-9ef9-1e494fdf541e.png)

**Comment by ABonomo21** [comment]
added inspector to employee
![image](https://user-images.githubusercontent.com/47611580/69353342-5b7a2200-0c4c-11ea-9adf-6e60b146fce1.png)

**Comment by ABonomo21** [comment]
once the application got to the inspections milestone bob cramer was automatically the inspector assigned.
