### ISSUE TITLE
Building Permits - Driveway - Reinspection Fee

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2056]
Reinspection Fee is not generating after two failed inspections on Driveway.

![image](https://user-images.githubusercontent.com/31770504/67214060-182e5880-f3ed-11e9-992a-076b2adcd784.png)

**Comment by megisys** [comment]
Hansen 7 Details or new detail to be provided from County.

**Comment by ABonomo21** [comment]
The fee needs to be added as this is a building permit- it should be happening now in 7
the account number is 10.98.998.999.40710.0000
same rules should be the same as building permits

**Comment by ABonomo21** [comment]
fee generated 
![image](https://user-images.githubusercontent.com/47611580/68137974-d249b800-fef5-11e9-8fb1-a7f0db5cd283.png)
