### ISSUE TITLE
planning-preplat extension- wrong fees and reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2057]
should not generate a engineering fee and should not generate a BOE fee.  This work type is a DPZ only application.

MW
![image](https://user-images.githubusercontent.com/4129185/67215465-82e09380-f3ef-11e9-98ae-74f30ac72de6.png)

![image](https://user-images.githubusercontent.com/4129185/67215489-8e33bf00-f3ef-11e9-8712-815b041b8153.png)

**Comment by megisys** [comment]
When would you need the Engineering for Prelim-Ext add ? It is set to for PREPLATEX
