### ISSUE TITLE
Building Permits - Driveway - Official Issuance Correspondence

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2058]
Not receiving the Official Issuance Correspondence for Driveway permit.

We got the COC correspondence when batch manager ran.

**Comment by megisys** [comment]
Driveway seems to have 2 COC Correspondence set-ups . They are looking for an Offical Issuance

**Comment by ABonomo21** [comment]
certificate of completion was send out instead of the issued permit

**Comment by TaraF** [comment]
Updated: Building Permit Official Issuance is sent out at Permit Issued milestone.
COC is still sent out at completion milestone - if that is incorrect please comment below and we will update. 

Ready for re-test.

**Comment by ABonomo21** [comment]
received the official issuance- but instead of the placard i got a COC and i was still in the inspection milestone 
![image](https://user-images.githubusercontent.com/47611580/68420892-46d95c80-016b-11ea-9286-00a6c1dd7020.png)

![image](https://user-images.githubusercontent.com/47611580/68420903-4b9e1080-016b-11ea-9052-0aad124e4b30.png)

**Comment by TaraF** [comment]
Official Issuance and Placard are coming through on milestone of Permit Issued. 

COC is set on milestone of Complete.  I didn't run into what you were seeing above, but please re-test and let me know if it is happening again. 

Ready for re-test.

**Comment by ABonomo21** [comment]
tara it happened again on permit 251483
 i got the permit to issuance and it sent me the official issuance, placard and the certificate of completion correspondence. 
![image](https://user-images.githubusercontent.com/47611580/68877812-ae942800-06d4-11ea-80bf-f5e303280169.png)

**Comment by ABonomo21** [comment]
in training today we received the COC correspondence when we should have received the official issuance and placard - example permit # 251489

**Comment by TaraF** [comment]
This is fixed and confirmed - see 251598 (There was a ghost CM set in IPS that couldn't be seen from the normal milestone screen.  Has been removed.)

Ready for re-test.

**Comment by ABonomo21** [comment]
the DW is now sending the correct correspondence. - this has been fixed. 

one small favor can you please make the headers consitant. 

DW COC
![image](https://user-images.githubusercontent.com/47611580/69274642-c7a34a00-0ba8-11ea-8ce0-a5c9c19eef72.png)

ResUse COC
![image](https://user-images.githubusercontent.com/47611580/69274847-397b9380-0ba9-11ea-8e1e-47ee552295ce.png)
