### ISSUE TITLE
Building Permits - Driveway - Contact Details not Coming Over to Back Office

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2059]
Ashlye added a contact on the Contact Details page, but it did not come over to Back Office.

**Comment by megisys** [comment]
Permissions Issue - Need to propagate to other Roles

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/67316433-69664700-f4d6-11e9-9494-88ca4d36693b.png)
