### ISSUE TITLE
Building Permits - Driveway - Site Plan Expired Related Records

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2061]
Trying to add a Site Plan to an application. saying it is expired. Dan was going to create a method to remove the expiration allow us to add, then reapply the expiration.

![image](https://user-images.githubusercontent.com/31770504/67218509-7d397c80-f3f4-11e9-81f5-a804bc1ad7f2.png)

**Comment by megisys** [comment]
Can not associate Expired Permits. Hence why we created a detail page place for it. There is formula on that method. Which unexpires it. Associates and then re expires the application

**Comment by ABonomo21** [comment]
it is not a training issue it is a configuration issue because i have the sp number on the details page and it did not relate the record. 

see permit # 251102

**Comment by megisys** [comment]
Added a New Field SitePlanNO to Driveway Details

**Comment by megisys** [comment]
This is fixed.. Added to Intake Page.. The above screenshot FYI was a FRO AP Number

**Comment by megisys** [comment]
Add the Building Permit to the Expired Planning Application.. System is built this way over the product wide

**Comment by ABonomo21** [comment]
will add the permit to the planning record in the event the planning application is expired.
