### ISSUE TITLE
IPS Addresses - Cleanup Needed

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2063]
There are still duplicate addresses in the system. As an applicant I would not know the appropriate on to choose.

Dan just expired the one in the screenshot.

Dan said this is a GIS cleanup task. @dhenry-KCI

**Comment by megisys** [comment]
We have 70,000 Addresses

**Comment by megisys** [comment]
I sql deleted these out

**Comment by ABonomo21** [comment]
Per discussions with IIT addresses will be resolved prior to go live- Will check with data migration post go live.
