### ISSUE TITLE
Building Permits - FRO Permit - Detail Page Changes

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2064]
Change FRO Planning No # to read FRO Planning/Project # 
Remove the County, Town, Board of Education and FRO from R4C. These should be back office only.
Remove the Colons from the Plantings, Eradication, Regeneration
Make Passing Inspection Required check box back office only.
Approved Cost Estimate Amount should be added to the Fro Permit Details page. Should show in both R4C and back office.

![image](https://user-images.githubusercontent.com/31770504/67222524-7eba7300-f3fb-11e9-85d5-47b38bd542f4.png)

**Comment by ABonomo21** [comment]
everything else is fixed - dan per our discussion please add the **Approved Cost Estimate Amount** should be added to the Fro Permit Details page. Should show in both R4C and back office.
does not need to drive/generate any data just freedorm number box with the title

**Comment by JuanitaMiles** [comment]
fixed
