### ISSUE TITLE
Building Permits - FRO Permit - Intake Review Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2065]
Skipping status checks after resubmit on Intake Review. Went straight to Awaiting Payment.

![image](https://user-images.githubusercontent.com/31770504/67224229-ba0a7100-f3fe-11e9-84f4-7c22625960aa.png)

**Comment by JuanitaMiles** [comment]
Not fixed. Permit didn't require the Completeness Check review to be completed. It went straight to Awaiting Plan Review Payment

![image](https://user-images.githubusercontent.com/31770504/68140624-22c31480-fefa-11e9-911e-2c9ef2c1afa7.png)

**Comment by megisys** [comment]
Completed by David Lucier

**Comment by ABonomo21** [comment]
tested in dev and test dev a/p 251145 test a/p 251323
failed - still goes right to awaiting plan review payment

**Comment by ABonomo21** [comment]
fixed

**Comment by ABonomo21** [comment]
251330
