### ISSUE TITLE
Building Permit - FRO Permit - Permit Issuance Correspondence

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2068]
FRO Placard should not be sending through correspondence. The Approval Letter (rpt_Fee_FRO_Inspection_ONLY) should be sent instead.

**Comment by TaraF** [comment]
This is ready for re-test.

**Comment by ABonomo21** [comment]
the wrong report was send during the issuance correspondence. 
![image](https://user-images.githubusercontent.com/47611580/68419563-76d33080-0168-11ea-8117-9c9c62bf1016.png)

**Comment by TaraF** [comment]
Approval Letter is the only CM being sent now on Permit Issued milestone.  Please re-test, OR let me know if there is something else that is needed.

**Comment by ABonomo21** [comment]
Tara the correct report is now being send via correspondence but when IPS permit 251090 it does not generate the inspector information and there is an employee record
this is the report i ran from on demand for one permit 
![image](https://user-images.githubusercontent.com/47611580/69258565-cd8a3280-0b8a-11ea-8ef8-1f22c1abfbf8.png)

this is the report i received for a different permit which is generating the to schedule a meeting and inspector information that should print. 
![image](https://user-images.githubusercontent.com/47611580/69258677-fca0a400-0b8a-11ea-9af6-92f62f5d5b14.png)

**Comment by ABonomo21** [comment]
@TaraF - please see above

**Comment by TaraF** [comment]
You will not see the inspector info unless there is a FRO-INSTAL inspection and a value for Assigned-to.  Talked to Emily P.  on 11/20/19 -- the inspectors as supposed to be auto populating but are not  (see:  https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2053 ).

This is a non-issue, but should be tested again - contingent of #2053 being properly fixed.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69359956-9fbeef80-0c57-11ea-8934-c15119acf349.png)

fixed

**Comment by ABonomo21** [comment]
I received two notifications for this recevied 5 min apart-  we only need one to send. The correct approval letter should be the approval letter sent @ 1:29pm with Eric as Chief and also Eric as the ECS inspector. 
[FRO_Permit_-_Approval_Letter_HANSEN8_20191121_012418654.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3876177/FRO_Permit_-_Approval_Letter_HANSEN8_20191121_012418654.pdf)
[FRO_Permit_-_Approval_Letter_HANSEN8_20191121_012918455.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3876178/FRO_Permit_-_Approval_Letter_HANSEN8_20191121_012918455.pdf)

**Comment by ABonomo21** [comment]
refreshed and now it looks good.
