### ISSUE TITLE
Building Permits - Grading/Driveway/FRO - Dashboard for When a Bond is ready to be Released

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2069]
Dan - can you please start a dashboard ad hoc that shows when the final inspection has been passed and the remaining balance of the bond needs to be released.

**Comment by megisys** [comment]
I attempted to do this.. But I can not get system to see if all reviews are resulted. I can only look if reviews individually are resulted or not resulted. This HAS to be a SSRS Report.

**Comment by TaraF** [comment]
@dhenry-KCI  - need to know if this is a needed report before go live?

**Comment by megisys** [comment]
BP - Bond Release - Added as Adhoc report

**Comment by ABonomo21** [comment]
report is working however when I release the bond the application is not automatically closing out to the next milestone which is finalized. Currently you have to check the check status button to close the permit and remove the record from the adhoc repot. 

![image](https://user-images.githubusercontent.com/47611580/69270127-624b5b00-0ba0-11ea-88b8-87fb3275e400.png)

![image](https://user-images.githubusercontent.com/47611580/69270156-7000e080-0ba0-11ea-94f6-ff6ca1827aa5.png)

![image](https://user-images.githubusercontent.com/47611580/69270186-7d1dcf80-0ba0-11ea-9848-5b41b95acd67.png)

**Comment by ABonomo21** [comment]
thanks
