### ISSUE TITLE
PLANNING-PWCONSTRUC - fees for CMBDEVIMP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#207]
Was not prompted for Applicant Actions for resbmittal. Fees were paid but nothing submitted to re-review but IPS went back to Under Review milestone.
![image](https://user-images.githubusercontent.com/4129185/53966829-ff716c80-40c1-11e9-9e0f-7658fcbe2c32.png)

**Comment by dhenry-KCI** [comment]
So far this occurred under CMBDEVIMP & CMBSWMDEV

**Comment by megisys** [comment]
Are you using Pdox.. What AP Number.. So Many quesitons...

**Comment by dhenry-KCI** [comment]
CMBDEVIMP PW237529/PW237530/PW237662
CMBSWMDEV PW237532/PW237536/PW237538
Not using Pdox. Fees are paid and it immediately goes back to under review without applicant resubmission.
AReed

![image](https://user-images.githubusercontent.com/4129185/54379824-85f8f180-4660-11e9-891f-2bf9c7619729.png)

**Comment by megisys** [comment]
This is address for INTRNALREV

**Comment by dhenry-KCI** [comment]
Awaiting applicant revisions has been confirmed on internal review PW237897/PW237889 AREED
