### ISSUE TITLE
Building Permits - FRO Permit - Reports

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2070]
All permits need to be reviewed for completeness and accuracy.

**Comment by JuanitaMiles** [comment]
FRO BOND RELEASE INSPECTION REPORT. Need to find this report

**Comment by TaraF** [comment]
@JuanitaMiles, @ABonomo21  -

This report is generated only if there is a "GUARANTEE RELEASE INSPECTION" Inspection type on it.   Currently, under FROPERM, in IPS, you cannot choose that type of inspection to add.   So, I think stakeholders need to determine:

1) If that is an Inspection type they need to add to FROPERM  OR

2) If this report is the correct report and shows the information they need (and if there is another type of inspection it should be driven off of instead) OR

3) There is another similar report out there that wasn't given to us that we should incorporate in our que ASAP. 

Below is an example of a grading variation of the first page of the current report (please keep in mind the look has changed from the original, as instructed by stakeholders):
![image](https://user-images.githubusercontent.com/4104464/68037303-d1b6e480-fc9d-11e9-8211-59efab66e937.png)

**Comment by ABonomo21** [comment]
tara - the inspection is FRO BOND Release
![image](https://user-images.githubusercontent.com/47611580/68501824-0e9a5280-022d-11ea-9dfb-c8a81105a4dc.png)

The report you have attached is not correct for the FRO release - see the attachment below for the correct report.
[121659.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3825797/121659.pdf)

**Comment by TaraF** [comment]
Guarantee Release has been updated to include FROs.  This is working, ready to test.  

Updates happening for all the bonds, this to be updated with the correct attached letter once complete.

**Comment by ABonomo21** [comment]
251638 - retest failed 

Unable to retest- report blank - please also adjust header to be consistent with all correspondence.
![image](https://user-images.githubusercontent.com/47611580/69365692-d64e3780-0c62-11ea-8c85-faafb5def722.png)

Guarantee release inspection did not generate- in order to generate report
![image](https://user-images.githubusercontent.com/47611580/69365724-e534ea00-0c62-11ea-95d6-bef6e02a0467.png)

**Comment by TaraF** [comment]
@ABonomo21  - for this one, in the thread above, you indicated that for FRO, the report was triggered on an Inspection Type of FRO BOND RELEASE.  The example above you indicate is failing, doesn't even have that inspection type, so it wouldn't ever generate. 

Here is an example of one that has that inspection type, that is generating:  APNO 121659

![image](https://user-images.githubusercontent.com/4104464/69455228-f1d64280-0d35-11ea-847b-fb2a390a123e.png)

Also, let's discuss the headers in person, as I was going off of what Gary indicated- I'm not sure what you are expecting, but we can update if needed.

**Comment by ABonomo21** [comment]
need to check on what happens when there is more than one bond - please use example 134867

otherwise overall format is good and is generating correctly.

**Comment by TaraF** [comment]
Updated, ready for re-test.

**Comment by ABonomo21** [comment]
fixed
