### ISSUE TITLE
Building Permits - Grading/Driveway/FRO - CIP Fees Waived

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2072]
If County is checked under the detail page, the Fees should add and automatically waive.

![image](https://user-images.githubusercontent.com/31770504/67229751-f099b900-f409-11e9-956e-1d567d62e4bb.png)

**Comment by megisys** [comment]
Too much change and retest to achieve this now.

**Comment by ABonomo21** [comment]
Dustin can you confirm this is on the 1B phase? @dhenry-KCI

**Comment by ABonomo21** [comment]
i am okay with this being a 1B

**Comment by ABonomo21** [comment]
closing for now
