### ISSUE TITLE
planning -plat-farm lot-mylar fee not populating

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2077]
should have generated a $59 per page mylar fee.

![image](https://user-images.githubusercontent.com/4129185/67314828-59009d00-f4d3-11e9-80dd-26ab04bfdf0e.png)

MW

**Comment by megisys** [comment]
Mike this is the code we have had for a number of months. This PLAT is FARM. Please Advise


if	(oPlanningApp.WorkType.Code = "FINAL" or 
		oPlanningApp.WorkType.Code = "COMBO" or 
		oPlanningApp.WorkType.Code = "ROAD" or 
		oPlanningApp.WorkType.Code = "OPEN" or
		oPlanningApp.WorkType.Code = "PUBLIC" or
		oPlanningApp.WorkType.Code = "OUTLOT" or
		oPlanningApp.WorkType.Code = "CORRECT" or
		oPlanningApp.WorkType.Code = "ADD")  then

	AddonCondition = True
	

End if

**Comment by dhenry-KCI** [comment]
The mylar fee $59/# of pages is on all plats. 
![image](https://user-images.githubusercontent.com/4129185/67410003-6aa47c00-f589-11e9-8312-7ca2a93e047f.png)

**Comment by dhenry-KCI** [comment]
verified corrected PL252145 ar
