### ISSUE TITLE
planning-plat- didnt get email notifications

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2078]
farm lot
![image](https://user-images.githubusercontent.com/4129185/67316781-150f9700-f4d7-11e9-94ec-76cb6da0221f.png)

public taking
![image](https://user-images.githubusercontent.com/4129185/67316848-2d7fb180-f4d7-11e9-9c8c-86231e406389.png)

MW

**Comment by megisys** [comment]
Mike your email got cleared out..

**Comment by dhenry-KCI** [comment]
fixed.

MW
