### ISSUE TITLE
Resbldg - Land Owner Affirmation

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2084]
Need to be able to bypass the home builder requirement when a landowner affirmation is signed by a landowner constructing their own house. 

We will need a log type created for Landowner Affirmation

Dan- i think we talked about this a while back and i think we just missed it :)

**Comment by megisys** [comment]
LANDOWN Log Type

**Comment by JuanitaMiles** [comment]
fixed
