### ISSUE TITLE
Building Permits - Grading (Minor and Major Logging) - Status Check for Grading Details on Intake Review 

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2085]
Enforce the status check to require the Grading Details to be completed during the Intake Review milestone.

![image](https://user-images.githubusercontent.com/31770504/67418251-721f5180-f598-11e9-9b2c-942c7f71283a.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/67418686-40f35100-f599-11e9-8c35-76a34f7ff18c.png)
