### ISSUE TITLE
Building Permits - Grading - Corresspondence at Issuance

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2087]
Wrong Report is sending at issuance. 
![image](https://user-images.githubusercontent.com/31770504/67499619-6a6eb400-f64f-11e9-99e1-1d0e15df0d07.png)

Emily - please attach the correct report and which AP/Work Types it should send for.

**Comment by ABonomo21** [comment]
file:///C:/Users/empearl/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/2XUPRCJ4/rpt_Permit_Approved_Pre-con_Required%20200374.pdf

should send out this correspondence

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/67499954-e49f3880-f64f-11e9-9758-7289a867e574.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/67500332-832b9980-f650-11e9-93d8-0f00d92c80b0.png)

SWM, MJ, PI (work types under Grading AP) and FRO permits

**Comment by ABonomo21** [comment]
employee tab is where the inspector should pull from and the contact should pull from the primary applicant listed on the application.

**Comment by TaraF** [comment]
This is updated and ready for re-test for grading.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68403904-bc353500-014b-11ea-8b6a-562e4aae7ce4.png)
whoop whoop !
