### ISSUE TITLE
Building Permits - Grading & FRO - Employees Tab to Populate With Assigned Inspector

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2088]
When an inspector is assigned to an inspection, we then need to migrate that employee record to the Employees tab. This needs to be populated for reporting.

This needs to be done for Grading and FRO permits.

**Comment by ABonomo21** [comment]
cannot test in test environment- are we supposed to check this in dev?

**Comment by ABonomo21** [comment]
@megisys

**Comment by ABonomo21** [comment]
working tested on multiple permits 251321
![image](https://user-images.githubusercontent.com/47611580/68403835-9740c200-014b-11ea-9961-ff4fc8613429.png)
