### ISSUE TITLE
Building Permits - Grading - COC Correspondence

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2089]
We got a correspondence for issuance of the Certificate of Completion. We do not issue COCs for Public Improvements, SWM, and Major Grading (Grading AP Work Types).

![image](https://user-images.githubusercontent.com/31770504/67507664-65186600-f65d-11e9-9252-1558ba49e1ed.png)

**Comment by TaraF** [comment]
This was set to run for everything but "SWMESD" only, no idea why.  Reset it to reflect what on demand is, which is:  will only be sent for MNL, MJL, and MN (all minor grading).

Ready for re-test.

**Comment by JuanitaMiles** [comment]
fixed
