### ISSUE TITLE
Planning-PWCONSTRU - PROJECT DOCS

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#209]
How can we facilitate two separate agencies to complete a batch stamp without the first one closing the project out. 
DUSWM and PWDR on PWCONSTRUC

**Comment by megisys** [comment]
Question for Robert.. @dhenry-KCI

**Comment by dhenry-KCI** [comment]
render stamp. Discussed in training. Closing issue can leverage ticket in trainings.
