### ISSUE TITLE
Building Permits - Grading - As Built Submission Process

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2091]
@dhenry-KCI We need a discussion on how the submission of CAD as builts will be delivered to the County and routed to Eric. Currently Mary M in GIS is receiving the documentation for GIS database purposes. So we want to see if the delivery to her will be part of the routing to the ECS team.

**Comment by ABonomo21** [comment]
dustin can you set up a 30 min meeting with Eric, Mary and Gary? @dhenry-KCI
