### ISSUE TITLE
Planning-NID-turn off auto assignment of reivewer

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2092]
NID goes straight to under review (as designed) and auto assigns to Ron Burns.  Please turn the auto assignment off so that it will remain unassigned and show up in Ashley Reed's dashboard.  She can use dashboard as a make shift completeness check.  I believe the same change was recently made to Verify. 

![image](https://user-images.githubusercontent.com/4129185/67511415-d90a3c80-f664-11e9-86e7-b3a71c937156.png)

not a bug but thought best label to use.

MW

**Comment by dhenry-KCI** [comment]
@megisys  The auto assignment to RBurns has been removed, but the review is not showing on my _Review Assignments Required_ Dashboard. Is that the part that is "In Development"?
N252159
AR
![image](https://user-images.githubusercontent.com/4129185/67779956-ca909c00-fa3b-11e9-9c93-2c835dfde8fd.png)

**Comment by megisys** [comment]
Reporting Issue

**Comment by JuanitaMiles** [comment]
@megisys This does have to do with the adhoc report but it has to do with whatever formula you wrote for the AutoAddReviews filter. I created a private copy, removed this filter and NID shows up on my list. I can't fix this.

![image](https://user-images.githubusercontent.com/31770504/67890409-03f20600-fb27-11e9-93da-ffccc8308aa7.png)

**Comment by megisys** [comment]
If I remove the formula this will break everything.. It is the same logic for YARDMOD.

if oReview.PlanningApplication.ApplicationType.ApplicationType ="VERIFY" or oReview.PlanningApplication.ApplicationType.ApplicationType = "YARDMOD" or oReview.PlanningApplication.ApplicationType.ApplicationType = "NID" Then

			oReview.PlanningApplication.AutoAddReviews = True
			oReview.PlanningApplication.Update()

End if

Your filters will need to be adjusted

**Comment by JuanitaMiles** [comment]
Dan and I discussed a potential solution to utilize the priority code within planning to indicate whether or not an application is Internal or EPlans. He added the options to the priority field code list, it just needs testing, confirmation that the priority isnt used for anything else on the planning side, and then have the ad hoc updated accordingly.

**Comment by megisys** [comment]
Now Using I as a Priority for Internal Review

**Comment by megisys** [comment]
Updated report

**Comment by dhenry-KCI** [comment]
created new NID but it doesnt show up in the report
![image](https://user-images.githubusercontent.com/4129185/68406517-f9032b00-014f-11ea-8b22-8a8ef9ba0a2b.png)
![image](https://user-images.githubusercontent.com/4129185/68406779-69aa4780-0150-11ea-8114-6ff9b6c8986c.png)
MW

**Comment by JuanitaMiles** [comment]
I just tested this as well. it doesn't work because the Priority doesn't add to NID, YARDMOD, or VERIFY until after the review is resulted and moves to the next milestone.

**Comment by dhenry-KCI** [comment]
fixed with Dan's and Juanitia's new report
