### ISSUE TITLE
Building Permits - Spawned Permits

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2093]
Whenever a permit is spawned from a Building Permit start the spawned application at Awaiting Applicant Resubmit. Excludes Capacity permit.

**Comment by JuanitaMiles** [comment]
Make sure that the Grading back office details page still auto fills with the intake details.

![image](https://user-images.githubusercontent.com/31770504/67978033-91009200-fbef-11e9-8c41-5775730b2629.png)

**Comment by megisys** [comment]
These are not the same detail pages. This is not possible. They are coming from Non ECS building permits

**Comment by megisys** [comment]
All spawn at Awaiting Applicant Rebumit
