### ISSUE TITLE
Building Permits - SWM ESD Status check on RESLDG

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2094]
Need to make sure there needs to be a status check at Pending Issuance on the Parent Building permit to make sure the SWM ESD grandchild permit is issued.

![image](https://user-images.githubusercontent.com/31770504/67516045-e677f480-f66d-11e9-9e23-33ac88368bb9.png)

**Comment by megisys** [comment]
I need to work with you on this one . lets talk tomorrow
