### ISSUE TITLE
R4C- look up records

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2097]
I didnt log in (this was under R4C website) lookup record and i was able to see the location details (where lockbox information can be entered). this information should not be shared. 

![image](https://user-images.githubusercontent.com/4129185/67683564-fb070600-f967-11e9-84e3-b9da766f8513.png)

10/28/19 EP

**Comment by dhenry-KCI** [comment]
permit 251138
inspection ID 1006115

**Comment by megisys** [comment]
Then dont put this information here. Add it as a log.
