### ISSUE TITLE
Town Assignment for sending reports

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2098]
we need to make sure that when we set up the parcels to automatically add a the town contact to an application that is within the town that we take it a step further to only send coc and coo's to that town contact when the address is in the town limits

**Comment by megisys** [comment]
We cant actually test this.. As we dont want to send them test data.

**Comment by ABonomo21** [comment]
we need to see that the towns are adding as an additional applicant pre golive i know we cannot test the notification part until after go live

**Comment by ABonomo21** [comment]
we need an email from the towns that they would like to use to receive notifications - need to have the town meeting first.

**Comment by dhenry-KCI** [comment]
@dhenry-KCI request generic email address from towns @ABonomo21 
draft email to towns.

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/69343094-ea7e3e80-0c3a-11ea-9288-2164efd2570f.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/69345105-95dcc280-0c3e-11ea-9e22-2b81d5b8b0d5.png)

**Comment by megisys** [comment]
All going to me as a safe guard

**Comment by ABonomo21** [comment]
town reviewer generated will need to make sure notifications are working correctly after go live 
![image](https://user-images.githubusercontent.com/47611580/69349705-384c7400-0c46-11ea-8fc8-2ba21302bc6f.png)

**Comment by ABonomo21** [comment]
need to assign the correct town emails as well - ashlye will draft an email to send to the towns to get email
