### ISSUE TITLE
License - Distributor License - Monthly Report Tab

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#21]
Remove Monthly reporting info from Distributor License since we have a separate distributor report that links in the related records.

See Screenshot of what to remove
![image](https://user-images.githubusercontent.com/4129185/52587624-67f16480-2e08-11e9-947d-45940533d284.png)

**Comment by megisys** [comment]
Resolved - Expired from all new Distributor Licenses

**Comment by ABonomo21** [comment]
The entire details has been removed. Want to check with @ABonomo21 to ensure this is correct for the application. -AW
![image](https://user-images.githubusercontent.com/47611580/54754339-a6bdcb80-4bb9-11e9-920e-ba5b02a90e3a.png)

**Comment by ABonomo21** [comment]
resolved- these will be added back office only
