### ISSUE TITLE
PLANNING-PWCONSTRU

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#210]
Duswm Mylar Rev DUSWMMYLAR should only populate on a PWCONSTRUC when Parcel Details indicated a DUSWM review is required. W1-W5 and/or Public

![image](https://user-images.githubusercontent.com/4129185/53967142-a48c4500-40c2-11e9-8235-2d04ae4f1518.png)

**Comment by megisys** [comment]
Addressed this

**Comment by dhenry-KCI** [comment]
fixed PW237900  MW
