### ISSUE TITLE
Building Permits - Signs - 11th Month Letter

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2104]
Please update the $48.00 fee value (highlighted in blue) to $49.00. In the 11th Month Letter report.

![image](https://user-images.githubusercontent.com/31770504/67776484-bf873d00-fa36-11e9-868a-345f69a89936.png)

**Comment by JuanitaMiles** [comment]
moving forward someone from the county will need to update the value every time the fee goes up. (each year)

**Comment by TaraF** [comment]
Updated - ready for re-test.

**Comment by ABonomo21** [comment]
fixed
