### ISSUE TITLE
Building Permits - Signs - Official Issuance

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2105]
Official Issuance Report:

Need to make all fonts consistent as well as font size.

Can remove the Building Details page for Signs only.

![image](https://user-images.githubusercontent.com/31770504/67776786-33294a00-fa37-11e9-9791-810c28c4c8b0.png)

![image](https://user-images.githubusercontent.com/31770504/67776834-489e7400-fa37-11e9-95a3-56e3354c762b.png)

**Comment by TaraF** [comment]
Fixes are made, ready for re-test.

**Comment by TaraF** [comment]
AP# 251163

- remove line next to details
- agency comments section should be filled out

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68310175-8cb7f700-007d-11ea-8626-2d2881e48976.png)

**Comment by TaraF** [comment]
Per discussion, agency comments section now only shows those which have an approved type of approved or conditionally approved. 

Ready for re-test.
