### ISSUE TITLE
Building Permits - Signs - Placard Report

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2106]
The Placard Report is not available to run. It should become available at Issuance.

![image](https://user-images.githubusercontent.com/31770504/67777232-d37f6e80-fa37-11e9-9af9-d909341af288.png)

**Comment by TaraF** [comment]
This fixed, and now available for Signs - on demand. 

Ready for re-test.

**Comment by TaraF** [comment]
Note: Checked with AB - she kicked it back because she is also expecting this for CM - currently in the works.

**Comment by TaraF** [comment]
As directed, for CM - there is now the following for Signs on Permit Issued:
- Official Placard
- Official Issuance

READY FOR RE-TEST!

**Comment by ABonomo21** [comment]
received on 251163
