### ISSUE TITLE
PLANNING - PWCONST - DUSWM REVIEW

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#211]
Parcel is public water/sewer. Fee populated but no review
PW237530

![image](https://user-images.githubusercontent.com/4129185/53968270-b2db6080-40c4-11e9-86d8-0158dcc26064.png)
![image](https://user-images.githubusercontent.com/4129185/53968294-c25aa980-40c4-11e9-915a-208e104047e9.png)

**Comment by megisys** [comment]
Issue Addressed

**Comment by dhenry-KCI** [comment]
DUSWM review populated PW237915 Areed. Closed
