### ISSUE TITLE
Building Permits - Tanks - Correspondence at Issuance

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2110]
We are not receiving correspondence at Issuance.

![image](https://user-images.githubusercontent.com/31770504/67783210-4f7db480-fa40-11e9-8246-d1ba94d8aca5.png)

**Comment by TaraF** [comment]
CM - Certificate of Issuance is now sent on milestone of "Permit Issued".

Ready for re-test.

**Comment by TaraF** [comment]
@ABonomo21  - I think this was a batch manager issue.  Dan seems to have resolved.  Please re test.

**Comment by TaraF** [comment]
As directed, for CM - there is now the following for Tanks on Permit Issued:

Official Placard
Official Issuance
READY FOR RE-TEST!

**Comment by ABonomo21** [comment]
thank you
