### ISSUE TITLE
Building Permits - 11th month letter & Expiration Notices Reports

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2114]
We need the 11th Month Letter and Expiration Notices reports need to be available on the Lookup Application screen for Ashlye to run in bulk.

![image](https://user-images.githubusercontent.com/31770504/67784473-383fc680-fa42-11e9-8568-5e441159d4b0.png)

**Comment by megisys** [comment]
Unless your report has bursting this is not how this works.. WE are using notifications for this piece. PLease confirm requirements. As reports do not support bursting.

**Comment by ABonomo21** [comment]
will print from the monitored email box - print and mail them. 

We need the email address that will need to be checked.
