### ISSUE TITLE
Building Permits - Trailers - Correspondence at Issuance

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2119]
Not receiving correspondence when the permit is issued. 

![image](https://user-images.githubusercontent.com/31770504/67793910-19493080-fa52-11e9-9131-56b0a2e29a7b.png)

**Comment by TaraF** [comment]
Certificate of Issuance is now sent on milestone of "Permit Issued"

**Comment by ABonomo21** [comment]
received both
