### ISSUE TITLE
PLANNING - PWCONSTRU - CMBSWMDEV

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#212]
# of pages is populating with completeness check on CMBSWMDEV. I am unable to progress to fees without it. # of pages should populate with the 1st review (under review milestone). Should not hold up initial fees.

**Comment by megisys** [comment]
Addressed on Another Ticket

**Comment by dhenry-KCI** [comment]
fixed per AR
