### ISSUE TITLE
Building Permits - Trailers - COO Report Correspondence

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2120]
A COO should be sent upon application completion for Trailers when, the trailer is permanent. This can be found on the Trailer Details page Perm or Temp? field.

![image](https://user-images.githubusercontent.com/31770504/67794135-88bf2000-fa52-11e9-9df3-1c573dbb7f34.png)

**Comment by TaraF** [comment]
@ABonomo21  - this is now working for TRAILER - COO for CM only when Trailer is Perm only AND on the milestone of "Complete".
