### ISSUE TITLE
Building Permits - Trailers - 11th Month Report Name

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2121]
We are not sure why the 11th month report name includes expire letters. Can we change the name to just "11th Month Extension Letters" to be consistent with the other APs?

![image](https://user-images.githubusercontent.com/31770504/67794435-0551fe80-fa53-11e9-93cb-dcfb1eb6fd87.png)

**Comment by TaraF** [comment]
This report is the same report for all APs in Building Permit (not just Trailer), so the name persists across the board.  I have updated it as asked above.

Ready for re-test.

**Comment by JuanitaMiles** [comment]
fixed
