### ISSUE TITLE
Building Permits - Trailer - Official Issuance 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2122]
Font on the issuance is not consistent 

![image](https://user-images.githubusercontent.com/47611580/67794430-02570e00-fa53-11e9-8538-017076a88261.png)

building detail page is not required 
![image](https://user-images.githubusercontent.com/47611580/67794454-0c790c80-fa53-11e9-9cbb-3d34b135b27a.png)

only the trailer information is needed 
![image](https://user-images.githubusercontent.com/47611580/67794513-2581bd80-fa53-11e9-9000-c14c44da61e0.png)

font sizing- 
![image](https://user-images.githubusercontent.com/47611580/67794538-303c5280-fa53-11e9-902e-6aa2a046bf29.png)

**Comment by TaraF** [comment]
Fixes are made.  Ready for re-test.

**Comment by ABonomo21** [comment]
Remove the y/n from is electrical wiring being done, plumbing being done, food served 
remove drawings: section 
figure out where the is the trailer permanent/temporary being pulled from - just fill the P/T - 
![image](https://user-images.githubusercontent.com/47611580/68244001-caffd880-ffe1-11e9-9bee-be80ff48a948.png)


fill agency name comments and approval dates 
![image](https://user-images.githubusercontent.com/47611580/68243990-c4716100-ffe1-11e9-9a8e-1be52517dce2.png)

**Comment by ABonomo21** [comment]
For trailers- the details for the official issuance should be pulled from the trailer detail page 
![image](https://user-images.githubusercontent.com/47611580/68313086-0356f380-0082-11ea-8877-e2745e81b626.png)

ignore duplicted details for offical issuance that may be on the building details page 
![image](https://user-images.githubusercontent.com/47611580/68313160-22558580-0082-11ea-8ebd-d6fe56b672b5.png)

**Comment by ABonomo21** [comment]
on the coo report you will need to pull the building code addition from the building details page 
![image](https://user-images.githubusercontent.com/47611580/68313267-47e28f00-0082-11ea-8ef6-e491d6b76d45.png)
![image](https://user-images.githubusercontent.com/47611580/68313453-9d1ea080-0082-11ea-97d0-5066777bd17d.png)

**Comment by ABonomo21** [comment]
coo issue addressed

**Comment by TaraF** [comment]
Fixed- updated made as specified above - please re-test.

**Comment by ABonomo21** [comment]
fixed - 11.6.19 need to check the capacity issue to make sure contractor is working
