### ISSUE TITLE
Zoning Certificate - Details Page Clean Up 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2125]
under septic information 

![image](https://user-images.githubusercontent.com/47611580/67798329-ac399900-fa59-11e9-8705-2d68d683ce08.png)

the line reading - If installing new installation please also select Conventional or Sandmound
should read - If installing new septic, please also select Conventional or Sandmound
the line reading- If connecting to existing please do not select a type
should read - If connecting to existing septic, please do not select a type

**Comment by ABonomo21** [comment]
Also please make the name box for the septic installer smaller it does not need to have so much entry space.

**Comment by JuanitaMiles** [comment]
fixed
