### ISSUE TITLE
PLANNING PWCONSTRUC - CMBSWMDEV - fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#213]
Life Safety Review fee $210 populating in error. Life Safety(DOLS) does not review this plan.
![image](https://user-images.githubusercontent.com/4129185/53970198-2a5ebf00-40c8-11e9-9513-64cfd3395ad7.png)
![image](https://user-images.githubusercontent.com/4129185/53970233-3ea2bc00-40c8-11e9-8751-f9a1bfa08ba4.png)

**Comment by megisys** [comment]
Removed from All PWCOnstructs

**Comment by dhenry-KCI** [comment]
DOLS $210 fee has been removed.
Engineering $421 fee removed in error - needs to be added
AReed
![image](https://user-images.githubusercontent.com/4129185/54946099-bcaaf380-4f0d-11e9-9989-fd17f6a0835f.png)

![image](https://user-images.githubusercontent.com/4129185/54946159-dba98580-4f0d-11e9-9558-743c37d4d48f.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
verified correct PW238951 AReed
