### ISSUE TITLE
Building Permits - Zoning Certificate - Zoning Certificate Issuance Report

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2130]
Fonts need to be consistent
Remove Parent Permit No
It is missing the outline blocks around each detail page.
Fees are not being pulled.
Agency Comments: Should only show the final approved agency/comment. Tara can you make sure these agency comments are listed in the issuance report for all APs.
Tolson' title needs to be updated to Zoning Administrator.

![image](https://user-images.githubusercontent.com/31770504/67801280-3f290200-fa5f-11e9-808f-78ef7506bb46.png)

**Comment by TaraF** [comment]
Corrections made - ready for re-test.
