### ISSUE TITLE
Building Permits - Zoning Certificate - Health Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2131]
Should have gotten a 50.00 health fee, 30.00 connection fee for Connection to existing septic check box on the detail page. When served by well and septic. May be missing because the water and sewer details are not populated on the parcel.

![image](https://user-images.githubusercontent.com/31770504/67802517-a9db3d00-fa61-11e9-97e2-848d6fab4f60.png)
![image](https://user-images.githubusercontent.com/31770504/67802460-8fa15f00-fa61-11e9-99de-beab4dd37235.png)
![image](https://user-images.githubusercontent.com/31770504/67802467-95974000-fa61-11e9-93f9-2b872a02af49.png)

**Comment by megisys** [comment]
Bad Addresses

**Comment by JuanitaMiles** [comment]
fixed
