### ISSUE TITLE
planning-yardmod-two applicant actions details.

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2136]
there should only be one.

![image](https://user-images.githubusercontent.com/4129185/67865978-9f22b580-fafe-11e9-8f3e-1047cc6a1979.png)

MW

**Comment by dhenry-KCI** [comment]
now there are no applicant actions details.

![image](https://user-images.githubusercontent.com/4129185/67957943-ba5bf680-fbcc-11e9-8fe8-84260fa1fe70.png)


MW

**Comment by dhenry-KCI** [comment]
UPDATE: applicant actions appeared after resulting review as resubmit.  Strange, other AP types have Ap Actions there from the start.

![image](https://user-images.githubusercontent.com/4129185/67958857-360a7300-fbce-11e9-9b61-a5b7bfc63c25.png)


MW

**Comment by megisys** [comment]
Adjusted to Add on Start

**Comment by dhenry-KCI** [comment]
fixed

![image](https://user-images.githubusercontent.com/4129185/68235662-a00d8880-ffd1-11e9-9780-bafc1afeb3aa.png)



mw
