### ISSUE TITLE
PLANNING-PWCONSTRUC- CMBSWMDEV

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#214]
Remove PWCONSTRU Engineering Fee - Improvement $145. This per sheet fee should only populate on Improvement Plans
![image](https://user-images.githubusercontent.com/4129185/53970757-66deea80-40c9-11e9-9a6a-5cb47b5923cd.png)

**Comment by megisys** [comment]
What are improvement plans.. Are they PWconstructs with a different worktype.. Please be careful in logging you rtickets.

Dan

@dhenry-KCI

**Comment by dhenry-KCI** [comment]
Please note: Improvement Plans are the work type labeled... Improvement Plan
AREED
![image](https://user-images.githubusercontent.com/4129185/54377622-dd489300-465b-11e9-975e-82b1cc7d8ab7.png)

**Comment by megisys** [comment]
Addressed this

**Comment by dhenry-KCI** [comment]
PW237923  CMBSWMDEV $145 engineering fee has been removed. AReed
