### ISSUE TITLE
Building Permits - Fire Permits - Permit Issuance Correspondence

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2143]
We are not getting correspondence upon issuance of a fire permit.

**Comment by TaraF** [comment]
Note: checked with Juanita, it sounds like both Building Permit Official Issuance, and Placard are necessary.  Official Issuance was not built out before for Fire AP types, based on previous session feedback so that is being built out first.

**Comment by TaraF** [comment]
Fire is sending out placard and issuance now upon Permit Issued milestone.  I think this is a duplicate issue.  Additionally, as noted in previous bug, the issuance is brand new and needs to be tested for content.

 Regardless, ready for re-test.

**Comment by JuanitaMiles** [comment]
fixed
