### ISSUE TITLE
Building Permit- Fire Permit - Inspection Request 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2144]
I was able to request inspections for Fire for tomorrow 10.31.2019 and it is after 12 noon. 

![image](https://user-images.githubusercontent.com/47611580/67878250-67713900-fb11-11e9-8993-54a0a49e5098.png)

**Comment by calequin** [comment]
tested with ap #251042 and it seems to be working correctly. I also checked logs to see if the server time is correct and it is indeed looking at EST time zone.

**Comment by JuanitaMiles** [comment]
retest failed for FIRE. it was 12:35 and it allowed us to request for tomorrow.

![image](https://user-images.githubusercontent.com/31770504/68322794-140f6580-0092-11ea-85b3-0831f927cf82.png)

**Comment by megisys** [comment]
Christian see 251181

**Comment by JuanitaMiles** [comment]
electrical works

**Comment by ABonomo21** [comment]
electrical fixed - now only electrical

**Comment by megisys** [comment]
I made changes.. Need to Sync REST and Try again.. @calequin

**Comment by ABonomo21** [comment]
tested 198879
