### ISSUE TITLE
Building Permits - Fire Permit - Officical Issuance Report

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2145]
The Official Issuance report is blank when we run it from the application.

![image](https://user-images.githubusercontent.com/31770504/67879756-e1a2bd00-fb13-11e9-91e8-3665428c8354.png)

![image](https://user-images.githubusercontent.com/31770504/67879776-eb2c2500-fb13-11e9-8629-5bd1454e7153.png)

**Comment by TaraF** [comment]
This is because there was never one for FIRE in the past, as discussed with AB / Emily.

We have created one per request, it is now available, but will need feedback as we had no example to use since it doesn't currently exist. 

Ready for test.

**Comment by JuanitaMiles** [comment]
done
