### ISSUE TITLE
Building Permit- Fire Permit-Placard 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2146]
I do not have a fire placard report which should generate when the permit issues and send with the correspondence

![image](https://user-images.githubusercontent.com/47611580/67879820-fc753180-fb13-11e9-9744-88507e880ed1.png)

**Comment by TaraF** [comment]
For on-demand, this is available, but the Permit must be issued before it shows up for selection:
![image](https://user-images.githubusercontent.com/4104464/68216110-5fe8de80-ffae-11e9-9dcb-978148f0e240.png)

**Comment by TaraF** [comment]
Official issuance and placard are working for CM - Permit Issued milestone.  Ready for re-test.

**Comment by JuanitaMiles** [comment]
fixed
