### ISSUE TITLE
Building Permits - All building permit- Expired Permit Letters

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2147]
The expired notices should send out at the 13 month (after the permit expired)

all permits except Grading and Fro which have different letters that get send out. 

![image](https://user-images.githubusercontent.com/47611580/67880631-63dfb100-fb15-11e9-99b9-f59d42bb5880.png)

**Comment by megisys** [comment]
I will build this as per EXTR - Minimal time here - 30 Minutes. Batch Manager task to be configured after Go Live.

**Comment by megisys** [comment]
Add a EXPIRE Log and these will go.. batch manager after go live will do this piece

**Comment by ABonomo21** [comment]
tested on permit 251453 i did not get a correspondence. 
![image](https://user-images.githubusercontent.com/47611580/68876687-dedac700-06d2-11ea-9b84-6cca09c0e5cf.png)

**Comment by ABonomo21** [comment]
disregard-i did not wait long enough 
![image](https://user-images.githubusercontent.com/47611580/68876891-29f4da00-06d3-11ea-9f65-46b207b90aed.png)
