### ISSUE TITLE
PLANNING PWCONSTRU CMBSWMDEV

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#215]
Health Review didn't populate - Parcel NPS and well septic

![image](https://user-images.githubusercontent.com/4129185/53972961-d35be880-40cd-11e9-8414-3d886d61c4fb.png)

![image](https://user-images.githubusercontent.com/4129185/53972994-ea9ad600-40cd-11e9-8a58-8a21fc5d79af.png)

**Comment by megisys** [comment]
Please Retest.. Addressed on Another Ticket

**Comment by dhenry-KCI** [comment]
fixed PW237898  MW
