### ISSUE TITLE
Building Permits - Fire Permits - Smoke Control Inspection Fee

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2152]
This Fire permit should have also generated the Smoke Control Inspection Fee

![image](https://user-images.githubusercontent.com/31770504/67886155-5c250a00-fb1f-11e9-89f6-952d346d05cc.png)

![image](https://user-images.githubusercontent.com/31770504/67886175-69da8f80-fb1f-11e9-8bcd-4ef92add724a.png)

**Comment by megisys** [comment]
I need the rules please @JuanitaMiles

**Comment by megisys** [comment]
Add Duct work as a Checkbox
![image](https://user-images.githubusercontent.com/47392306/67951355-b8406a80-fbc1-11e9-9e11-a3bd942a0e59.png)

**Comment by megisys** [comment]
If Checked then add fee. Smoke Control Inspection Fee .If Type of Permit = Smoke Control always add .

**Comment by megisys** [comment]
Added like the Smoke Review Fee for now..  FirePermitType.Code.ToUpper.Trim() = "CONTROL"

**Comment by ABonomo21** [comment]
also add the inspection when the check box is set

**Comment by megisys** [comment]
InforClient.AgencyCDR.BuildingApplet.FireDetails

**Comment by ABonomo21** [comment]
tested 251482 and worked great... 
![image](https://user-images.githubusercontent.com/47611580/68875963-ac7c9a00-06d1-11ea-8ceb-b10de1b3e1b6.png)
