### ISSUE TITLE
Building Permits - Fire Permit - Extension Requests

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2154]
We added the extension request detail page and completed it, but not review, or log generated on the permit altering staff a request has been made.

![image](https://user-images.githubusercontent.com/31770504/67888701-fd15c400-fb23-11e9-97f7-b2ab658b3087.png)

**Comment by megisys** [comment]
You dont add the page.. You add the log and it does the rest

**Comment by ABonomo21** [comment]
Add log - which will automatically add via batch manager for the 11 month or 5th month for app
log will add details page - submit request 
under review - grant or deny (granting will add the fee)
date will update based on 3, 6 or 9 month - then close log
