### ISSUE TITLE
Building Permits - Electrical Permit - Electrical License for Additional Applicant

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2158]
The application is not recognizing the electrical license of the additional applicant.

![image](https://user-images.githubusercontent.com/31770504/67957079-76b4bd00-fbcb-11e9-876d-194fd84c2054.png)

![image](https://user-images.githubusercontent.com/31770504/67957126-859b6f80-fbcb-11e9-9ca2-aa1a90eef403.png)

**Comment by megisys** [comment]
David Lucier Addressed. Move BP_ELEC_Check_SCF

**Comment by ABonomo21** [comment]
close
