### ISSUE TITLE
PLANNING PWCONSTRU - CMBSWMDEV

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#216]
Health Fee $75 didn't populate. Parcel NPS Well and Septic

![image](https://user-images.githubusercontent.com/4129185/53973136-2a61bd80-40ce-11e9-84c0-8ce31e55b96b.png)
![image](https://user-images.githubusercontent.com/4129185/53973153-33eb2580-40ce-11e9-8605-c3d210f7cd86.png)

**Comment by megisys** [comment]
PLease Retest

**Comment by dhenry-KCI** [comment]
Corrected PW237925 areed

**Comment by dhenry-KCI** [comment]
missing engineering fee but addressed on another ticket
