### ISSUE TITLE
Building Permits - Electrical Permits - Inspector Assignment

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2162]
@dhenry-KCI Can you touch base with Bob to find out who has taken VMCFARLANE's position. We'll need to get that information to Dan for him to update the inspection assignments.

![image](https://user-images.githubusercontent.com/31770504/67959283-d9f41e80-fbce-11e9-8260-da24cfae7ea1.png)

**Comment by megisys** [comment]
This piece needs to be handed over to the county as it is pure data entry and changes constantly

**Comment by ABonomo21** [comment]
James Miller should be in place of VMcfarland

**Comment by JuanitaMiles** [comment]
fixed
