### ISSUE TITLE
Building Permits - Electrical Permit -  DPZ Review

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2163]
Resulted DPZ review with RESUBMIT and the application went to Inspections. It should have gone to Awaiting Applicant Revisions. We will need to add the Under Review/Awaiting Applicant Revisions milestones to the Electrical Permit or some other solution.

![image](https://user-images.githubusercontent.com/31770504/67961097-a1097900-fbd1-11e9-9e92-15769f6bc751.png)

**Comment by megisys** [comment]
This is new as we never allowed for Electrical Permits to have reviews cycle.

**Comment by ABonomo21** [comment]
worked tested under 251283
