### ISSUE TITLE
Building Permit- Electrical Permit- Extension Request 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2166]
Extension Request notification was sent twice. 

![image](https://user-images.githubusercontent.com/47611580/67966991-39582b80-fbdb-11e9-8dde-730630bd1be7.png)

**Comment by megisys** [comment]
Believe this to be linked to another issue. But I added a fix for this...

**Comment by JuanitaMiles** [comment]
not fixed. no change in the issue, still getting two emails

![image](https://user-images.githubusercontent.com/31770504/68323418-61d89d80-0093-11ea-98c5-9f9923d38898.png)

**Comment by JuanitaMiles** [comment]
kind of fixed, closing
