### ISSUE TITLE
Building Permit- All Permit- Extensions 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2167]
When an extension is granted on building permits- we need to not only have the notification sent but a correspondence needs to be sent with a new official issuance (showing the new expiration date) and placard (with the new expiration date) when applicable for those a/p's that receive placards

**Comment by TaraF** [comment]
This is not something we can just throw over the fence to me- it is not an easy CM fix. ...we need to discuss with everyone to see what the system can do, what is reasonable in the amount of time left before go live.

**Comment by megisys** [comment]
Addressed under another Ticket

**Comment by ABonomo21** [comment]
251261- did not get another issued permit and placard ....

**Comment by megisys** [comment]
For Dan.. When we send the Granted Notifcaiton - Run both Placard and Issuance Correspondance with new dates..

**Comment by megisys** [comment]
Can you please provide the correct correspondence set-up's for ECS and Building permits
I will add to custom code  @TaraF @dhenry-KCI

**Comment by ABonomo21** [comment]
Building Permits with official issuance they get new **official issuance and placard** 

plumbing and electrical get just **official issuance** 

grading and driveway just get the **placard**

**Comment by TaraF** [comment]
@megisys CM is set up on milestones already in the system.  You should have what you need from me already in IPS:

![image](https://user-images.githubusercontent.com/4104464/69674876-6b8a6b00-106b-11ea-9bf0-578f2a4673b1.png)

**Comment by megisys** [comment]
Hi Tara, I think I do. I need to make the changes above.. You are clear on this ticket @TaraF

**Comment by megisys** [comment]
This is configured

**Comment by ABonomo21** [comment]
tested on permit 151453 - worked great, did not originally receive the placard but Dan fixed
