### ISSUE TITLE
Building Permit - Plumbing Permits - Notification at Issuance

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2169]
We did not receive any notification at issuance.

![image](https://user-images.githubusercontent.com/31770504/67969452-bb4a5380-fbdf-11e9-8e2c-984259afe060.png)

**Comment by megisys** [comment]
How was this paid ? Through Rthyhm >

**Comment by megisys** [comment]
Notification would have attempted to send to Hansen 8 User as it goes to the user which moves it to that milestone.. Will need to test this again.

**Comment by megisys** [comment]
Hansen8 User didn't have email address

**Comment by JuanitaMiles** [comment]
fixed
