### ISSUE TITLE
Building Permits - Plumbing Permits - Extension Detail Page

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2170]
Ashlye requested an extension a second time, and the application added a second extension  request detail page. There should only be one.

![image](https://user-images.githubusercontent.com/31770504/67970365-3eb87480-fbe1-11e9-93c0-3dd14da7eb31.png)

![image](https://user-images.githubusercontent.com/31770504/67970251-10d33000-fbe1-11e9-82dd-09704545ad8d.png)

**Comment by ABonomo21** [comment]
new ticket created #2207
