### ISSUE TITLE
PLANNING/BUILDING - R4C - CONTACT - CAPACITY to be required across all work types 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2171]
I was able to add contact without selecting capacity. This needs to be a required field for all applications types. B252177
Building and Planning should have all the same reqired fields. There is not phone number space on the Sign Permit under building.
We need required: CAPACITY, FIRST NAME, LAST NAME, EMAIL on all Contact Records.
AReed
![image](https://user-images.githubusercontent.com/4129185/67969450-b9809000-fbdf-11e9-8ba0-fce7ec3b6d04.png)

![image](https://user-images.githubusercontent.com/4129185/67969407-9ce45800-fbdf-11e9-9410-8572155bfa17.png)
![image](https://user-images.githubusercontent.com/4129185/67969615-06646680-fbe0-11e9-8244-678a112285e0.png)
![image](https://user-images.githubusercontent.com/4129185/67970560-91922c00-fbe1-11e9-9765-830f1ce5be0e.png)

**Comment by megisys** [comment]
Addressed by David Lucier

**Comment by dhenry-KCI** [comment]
tested 6 planning aps and several permit aps and it appears to be fixed.

MW
