### ISSUE TITLE
Building Permits - Plumbing Permits - Order or Events Issue for Comments in Resulting Review

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2172]
Ashlye went to deny the EXT review but didn't put in comments before savings. Then she added comments and hit save again so it sent the notification twice and most likely caused the Expiration date to be updated twice.
![image](https://user-images.githubusercontent.com/31770504/67970834-0b2a1a00-fbe2-11e9-8874-7510f111c769.png)

**Comment by megisys** [comment]
Adjusted this

**Comment by JuanitaMiles** [comment]
fixed
