### ISSUE TITLE
Building Permits - Electrical and Plumbing - Homeowner Exam Licenses

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2173]
Dan - please confirm that the "Licensed is REquired" status checks take the Homeowner licenss options into consideration. The following types should satisfy the status check.

![image](https://user-images.githubusercontent.com/31770504/67974649-33694700-fbe9-11e9-818f-657ac25d8f04.png)

**Comment by ABonomo21** [comment]
Electrical - 

![image](https://user-images.githubusercontent.com/47611580/67974664-3a905500-fbe9-11e9-9724-2bbb02e43419.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68225219-1902e500-ffbe-11e9-89a2-42c8a5358a10.png)

![image](https://user-images.githubusercontent.com/47611580/68225250-26b86a80-ffbe-11e9-896e-73c37dcfa1d3.png)

**Comment by JuanitaMiles** [comment]
worked for electrical

**Comment by ABonomo21** [comment]
electrical worked 
plumbing did not

**Comment by ABonomo21** [comment]
sorry electrical did not work i had a license.

**Comment by megisys** [comment]
Parts of Formula where missing

**Comment by JuanitaMiles** [comment]
fixed
