### ISSUE TITLE
Building Permits - Grading - DRTECOSTEST Review

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2174]
If a Grading, Work Type: MJ, Occupancy Type: RESTOWN OR CONDO, never add the DRTECOSTEST review at Intake Review. This is also the case for the PWDIRECTOR condition.

![image](https://user-images.githubusercontent.com/31770504/67976303-39145c00-fbec-11e9-8f4e-a186a40bcd1e.png)
 
![image](https://user-images.githubusercontent.com/31770504/67978436-7aa70600-fbf0-11e9-8d47-194a5d87af36.png)

**Comment by megisys** [comment]
GRADING_DRECostEst_AOC - Formula Updated in DEV
GRADING_PWDirector_AOC - Formula Updated in DEV

**Comment by megisys** [comment]
Mitigation Detail Page also to Hide if the above conditions match too

**Comment by ABonomo21** [comment]
thank you david !! 
![image](https://user-images.githubusercontent.com/47611580/68418980-5d7db480-0167-11ea-8adf-c0c25a9e5e60.png)
