### ISSUE TITLE
Building Permits - Grading - By Pass Status Checks

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2175]
Resulted Completeness Check with Resubmit but being held up for detail page updates.
Permit 251197.
![image](https://user-images.githubusercontent.com/31770504/67977644-df616100-fbee-11e9-896e-dc37be39ef90.png)

**Comment by megisys** [comment]
Move the Formulas associated

**Comment by ABonomo21** [comment]
tested 25137
