### ISSUE TITLE
Building Permits - Resbldg - Grading Permit Status Check

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2176]
A Grading Permit automatically spawns on the resbldg permit. We shouldn't get a status check requiring a GRading Permit to be added.

![image](https://user-images.githubusercontent.com/31770504/67978583-d7a2bc00-fbf0-11e9-9212-3a426611d118.png)

**Comment by ABonomo21** [comment]
fixed
![image](https://user-images.githubusercontent.com/47611580/68239978-04cce100-ffda-11e9-991f-1a5cd66a356a.png)
