### ISSUE TITLE
Building Permits - Grading - DPZ Review in Town

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2177]
The address/parcel used is in a town (township code 05) therefore the DPZ review shouldn't have added.

![image](https://user-images.githubusercontent.com/31770504/67979458-afb45800-fbf2-11e9-928f-2e6d6839978a.png)

**Comment by megisys** [comment]
I have never heard this requirement before ? Is this new ?

**Comment by ABonomo21** [comment]
this will have to be completed :) in talking with Dan, Tiffany never told him to remove town reviews when in a town which needs to happen
