### ISSUE TITLE
Refund Requests on R4C

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2178]
Can we remove the Request Refund links in Rhythm? It currently does not work properly, and applicants should just use the Request Withdrawal function, which could result in a refund.

![image](https://user-images.githubusercontent.com/31770504/67979794-67e20080-fbf3-11e9-9a11-656f88529902.png)

**Comment by calequin** [comment]
fixed.
Set allow refunds = false on rest services

**Comment by ABonomo21** [comment]
removed
