### ISSUE TITLE
PLANNING PWCONSTRU - CMBSWMIMP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#218]
Health Review didn't populate on NPS Well/Septic Parcel for CMBSWMIMP

![image](https://user-images.githubusercontent.com/4129185/53975315-89c1cc80-40d2-11e9-9f27-328ad0fb0ec8.png)
![image](https://user-images.githubusercontent.com/4129185/53976089-4ec09880-40d4-11e9-83cc-6bb8f2e3c116.png)

**Comment by megisys** [comment]
Duplicate

**Comment by dhenry-KCI** [comment]
PW238957 verified corrected - Areed
