### ISSUE TITLE
PDOX - SNAPSHOT on Changemark Report is not working. 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2181]
Snapshot box should be filled with image of mark up. This is not populating on the report. This was identified during training with MARA and was supposed to be corrected. 
AR/MW
![image](https://user-images.githubusercontent.com/4129185/68131667-6cf0c980-feeb-11e9-8503-be2de7e580a0.png)

**Comment by RS-Avolve** [comment]
I have followed up on this, will reply with information as soon as I know more.

**Comment by RS-Avolve** [comment]
This is in progress; I followed up internally on this issue.  I sent the email to Chuck Sharp and Rick Little (below the asterisks).  Chuck responded; we need to follow up with him.

****************************************************************************************************
The Frederick County ProjectDox Changemarks report is not showing snapshots; for this report, the snapshots are the thumbnail images of the changemarks.  We have looked at this and have verified the following is correct:
-	the report and stored procedures look good 
-	the markup image is being created
-	the markup image is stored appropriately in the UFP directory

Based on the above, we suspect the cause of the missing snapshots may be application filtering turned on in the firewall between the web server and the SQL server.  When application filtering is enabled it blocks the request to retrieve the image for display in the report.  Can you review to see if application filtering is turned on,  and if it is, disable any application filtering between the web server.**

**Comment by dhenry-KCI** [comment]
still not working in report
![image](https://user-images.githubusercontent.com/4129185/69967353-30ae8a00-14e6-11ea-93df-b5883677eec2.png)

Can see snapshots under the view/edit changemark in the complete review task
![image](https://user-images.githubusercontent.com/4129185/69967667-e4b01500-14e6-11ea-974f-9945bd0bf127.png)

MW

**Comment by dhenry-KCI** [comment]
Verified corrected SP253341 AR
![image](https://user-images.githubusercontent.com/4129185/69992099-f7dad900-1516-11ea-8eae-dc89df53b743.png)
