### ISSUE TITLE
Building Permits - RESUSE - Margins on the Official Issuance Report

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2186]
Is there a way to fix the margins on the report. They appear to be shifted to the left.

![image](https://user-images.githubusercontent.com/31770504/68147914-0e3a4880-ff09-11e9-91ca-ed023d9d92c5.png)

**Comment by TaraF** [comment]
Margins have been updated.  Please re-test.

**Comment by JuanitaMiles** [comment]
ok, left justified is fine
