### ISSUE TITLE
Building Permits - RESUSE - Official Issuance Report

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2187]
Is there a way to make the Building Details appear on one page rather than being split between two pages.

![image](https://user-images.githubusercontent.com/31770504/68148207-7db03800-ff09-11e9-8852-a25355ac9d7b.png)

Make the fonts in this section the same size. The italic seems to be larger.
![image](https://user-images.githubusercontent.com/31770504/68148307-b3edb780-ff09-11e9-8619-a7a5c5029a14.png)

**Comment by JuanitaMiles** [comment]
i believe this was changed to remove the box outlines and keep details all together. per conversation between tara and ashlye on 11/5

**Comment by TaraF** [comment]
This has been fixed as discussed - the box outlines for the major sections have been dropped, titles have been underlined for sections and there are not gaps between sections anymore.

Ready for re-test.

**Comment by ABonomo21** [comment]
y/n boxes removed 
applicant shift right 
building details should start on 2nd page

**Comment by TaraF** [comment]
This is fixed, please re-test.
