### ISSUE TITLE
Building Permits - RESUSE - Inspection Assignments

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2188]
None of the inspections on this permit were assigned to anyone. Assignments should follow the same rules as RESBLDG.

![image](https://user-images.githubusercontent.com/31770504/68149762-79d1e500-ff0c-11e9-81cd-b7dbfa7a02fc.png)

**Comment by JuanitaMiles** [comment]
Permit 251232
Septic inspection should not assign to RBarbeito. Leave unassigned for now. 
Also the BLDG-Final should have assigned to RBarbeito.
![image](https://user-images.githubusercontent.com/31770504/68152010-cc150500-ff10-11e9-8de5-94ae94620d05.png)

**Comment by megisys** [comment]
Election District 15 Was Not in the listing completed by Martin.

**Comment by megisys** [comment]
ONLY UPDATED FOR RESUSES.. May need county to review..

**Comment by JuanitaMiles** [comment]
fixed
