### ISSUE TITLE
Building Permits- Resuse- COC notification and correspondence

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2189]
I did not receive a notification or a correspondence for the certificate of completion on permit 251231.

**Comment by ABonomo21** [comment]
also did not get a notification for 251232 another resuse - different work type

**Comment by TaraF** [comment]
11/6 - AB/Dan decided no notification needed.

**Comment by TaraF** [comment]
This is set, ready for re-test.

**Comment by JuanitaMiles** [comment]
fixed
