### ISSUE TITLE
PLANNING-PWCONSTRUC - Fee CMBSWMIMP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#219]
Remove ENGINEERING FEE-IMPROVEMENT fee from CMBSWMIMP. It is for Improvement only
![image](https://user-images.githubusercontent.com/4129185/53976475-1cfc0180-40d5-11e9-87c9-15501de3e791.png)

**Comment by megisys** [comment]
Duplicate issue

**Comment by dhenry-KCI** [comment]
resolved - AReed PW238922
