### ISSUE TITLE
Building Permits - RESUSE - Not Getting Official Issuance and Placard Correspondence

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2190]
For resuse permits, we did not receive any Official Issuance or Placard Correspondence.

![image](https://user-images.githubusercontent.com/31770504/68150034-f1077900-ff0c-11e9-83f3-19af055b29a6.png)

**Comment by TaraF** [comment]
This is fixed and working.  Please re-test.

**Comment by JuanitaMiles** [comment]
fixed
