### ISSUE TITLE
Batch Stamp - Building Permits 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2192]
Whose signature is on this batch stamp ? 

Is this what we deiced for location? 

Would like to talk more about this. @dhenry-KCI 
![image](https://user-images.githubusercontent.com/47611580/68151606-07630400-ff10-11e9-9c40-b9a04e1bf449.png)

**Comment by dhenry-KCI** [comment]
Stamp was agreed upon to be in upper left. Issue logged with Robert regarding signature.

**Comment by ABonomo21** [comment]
closed #1320 because it was a duplicate

**Comment by dhenry-KCI** [comment]
@ABonomo21 - per robert the only templates the COunty should use are listed below. The one lableded "old" is a place holder for testing. please ignore.
The only 3 batch stamp templates that the County should use are as follows:
- Building Batch Stamp Approved (tied to the Building Batch Stamp called "Building Batch Stamp Approval Gary Hessong")
- Engineering Batch Stamp Approved (tied to the Engineering Batch Stamp called "Engineering Batch Stamp Approved Vijay Kapoor")
- Planning Batch Stamp Approval (tied to the Planning Batch Stamp called "Planning Batch Stamp Approval Offset")
