### ISSUE TITLE
Building Permits- Resuse Accessory Structure Fees 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2193]
need to speak with Dan on how the Accessory Structure fees are calculated in IPS

fees are not coming up correctly and need to understand how it is coded and where the fee is pulling from i.e. accessory type or construction type

![image](https://user-images.githubusercontent.com/47611580/68154272-2c0daa80-ff15-11e9-8e23-1efab34afe8e.png)

**Comment by megisys** [comment]
Construction Type needs to ACC400

**Comment by JuanitaMiles** [comment]
fixed
