### ISSUE TITLE
Use Permits - Land Use - Revision Fees (Life Safety vs. Admin Only)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2196]
While Under Review I resulted only the DOLS review with resubmit. Upon entering the Awaiting Applicant Resubmit milestone, two different revision fee types generated: Life Safety - Revision; and Revision - Admin Only.

Need to discuss with Ashlye when is the appropriate time for each of these revision fees to add. 

![image](https://user-images.githubusercontent.com/31770504/68221597-aabb2400-ffb7-11e9-9a48-0f5af78d0782.png)

![image](https://user-images.githubusercontent.com/31770504/68221663-c6262f00-ffb7-11e9-84d5-424d10aa93b1.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68226605-55374500-ffc0-11e9-9c6d-6f9c3a7fb5b2.png)

**Comment by JuanitaMiles** [comment]
@megisys  Configure as you did for EH revisions. If DOLS asks for a resubmit add the Life Safety Revision fee.

**Comment by JuanitaMiles** [comment]
If more than DOLS is resulted as resubmit, it should go to the Admin revision fee

![image](https://user-images.githubusercontent.com/31770504/68314171-becc5780-0083-11ea-80a8-e939e64573ec.png)

**Comment by JuanitaMiles** [comment]
fixed
