### ISSUE TITLE
Project - Blanket - Assign Reviewers Task Error in PDox

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2198]
Assign Reviewers Task is throwing this error message when trying to assign reviews for BPREVIEW ap type.
![image](https://user-images.githubusercontent.com/31770504/68233190-b1a06180-ffcc-11e9-81fd-22094a21c837.png)

**Comment by JuanitaMiles** [comment]
@dhenry-KCI  - Dan tried to figure this out and could not, can we check with Robert?

**Comment by RS-Avolve** [comment]
I have followed up with Alejandro to see if he can identify the issue.

**Comment by ABonomo21** [comment]
this is needed before simulation need to be able to test prior to showing to staff @dhenry-KCI

**Comment by RS-Avolve** [comment]
I will let you know what Alejandro says, I know for certain we have seen this error multiple times but I don't remember if the issue is on the ProjectDox side or the IPS side.  I believe Alejandro will be able to provide good insight on this.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69352658-4c46a480-0c4b-11ea-9d1e-117ce589506d.png)
