### ISSUE TITLE
PLANNING-PWCONSTRUC - PWIPPLAN - DUSWM REVIEW

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#220]
DUSWM review didn't populate on PWIPPLAN
![image](https://user-images.githubusercontent.com/4129185/53977459-0e164e80-40d7-11e9-9dc3-3e4b262ee7d0.png)
![image](https://user-images.githubusercontent.com/4129185/53977485-1bcbd400-40d7-11e9-842c-cb11b60eb9cf.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
fixed per PW237895
