### ISSUE TITLE
Building Permits - RESBLDG - Not Receiving Correspondence on Issuance

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2202]
We are currently not receiving any correspondence for RESBLDG permits. These should get a placard and official issuance.

**Comment by JuanitaMiles** [comment]
Got issuance just need the placard.

**Comment by TaraF** [comment]
This is fixed and working.  Ready for re-test.

**Comment by ABonomo21** [comment]
received tested on 251261
