### ISSUE TITLE
Building Permits - RESBLDG - Inspection Requests When Child Permits are not Complete (Ashlye Talk to Gary)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2203]
We initially told Christian to not allow requests if child permits are not completed. It turns out this is not true for certain inspection types. However, the condition is applied to all inspection types, it cant be only for certain ones. We have to not apply this condition at all then let the applicant know that this inspection cant be scheduled.

Ashlye to talk with Gary and Bob about this.

![image](https://user-images.githubusercontent.com/31770504/68241243-54aca780-ffdc-11e9-8fce-5007cf12b2c9.png)

**Comment by megisys** [comment]
Matrix APTYPE and INSPECTION CODE which can be schedule if Child permits are not issued

**Comment by ABonomo21** [comment]
basic rules will be sent to dan ASAP for some corrections prior to go live and additional correction may be made post go -live.

**Comment by ABonomo21** [comment]
bob is working on updating airtable with the rules... yes i said airtable hahaha

**Comment by dhenry-KCI** [comment]
Airtable Link

https://airtable.com/tblgyTlGmmutKLoy2/viwohSeD0pRasjx7r?blocks=hide

**Comment by megisys** [comment]
Email Sent on this. @dhenry-KCI @ABonomo21

**Comment by ABonomo21** [comment]
this will be addressed post go live - will need to create a excel spreadsheet.

At go live inspectors will still check to make sure any subsequent inspections have been completed. 

Will code more specific rules after go live.

**Comment by ABonomo21** [comment]
this was per a meeting with with dustin, bob, gary , ashlye and dan on 11.26.19

**Comment by ABonomo21** [comment]
APTYPE | INSPTYPE | CHILDAPTYPE | CHILDINSPTHATMUSTBEPASSED
-- | -- | -- | --
RESBLDG | BLDGAPP | ELEC | ALL
NONRESBLDG | BLDG-FINAL | FIRE | FIRE-FINAL
NONRESBLDG | BLDG-SLAB | ALL | NONE

**Comment by ABonomo21** [comment]
email on 11.25.19 from dan on what he needs from staff
