### ISSUE TITLE
Fire Permit - Status Check 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2204]
we also need status checks for Fire permits to have the Fire suppression review details page and the fire suppression rev/inspection details completed by the reviewer prior to batch stamp approval in pdox so at the pending issuance milestone

**Comment by ABonomo21** [comment]
Fire Suppression Rev/Insp Details
Fire Suppression Review Details
![image](https://user-images.githubusercontent.com/47611580/68311368-73b04580-007f-11ea-91ca-6ab213a0c7aa.png)

**Comment by JuanitaMiles** [comment]
fixed
