### ISSUE TITLE
Building Permits - All Permits - Extension Detail Page Not Clearing Out for a Second Time

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2207]
Ashlye added a second extension request and the detail page did not clear out from the first one.
![image](https://user-images.githubusercontent.com/31770504/68326585-b8e17100-0099-11ea-8e33-9a25168921ac.png)

related to #2172

**Comment by megisys** [comment]
See 251310

**Comment by ABonomo21** [comment]
worked like a charm good job dan
