### ISSUE TITLE
PLANNING/BUILDING - IPS OVERRIDE to complete reviews in IPS for PDOX Plan

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2208]
As discussed with Dan. Supervisor override needed to result reviews in IPS for projects that are using PDox when necessary. In the past, we have had situations where we have extra reviews in IPS (ex. Health) and the systems do not line up. This will allow us to result the extra review to keep the systems in sync. 
AREED

**Comment by ABonomo21** [comment]
tested and was able to change the review on an eplans in the back office. 251318
