### ISSUE TITLE
Mobile- Keyboard 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2211]
Need to get a fix for the keyboard being over the inspection result fields 
![image](https://user-images.githubusercontent.com/47611580/68422369-0c24f380-016e-11ea-8c58-baf76c47490e.png)

**Comment by dhenry-KCI** [comment]
This is a known ticket that Rick M. is working with Infor Development on.

**Comment by megisys** [comment]
Apply Latest Mobile..

**Comment by dhenry-KCI** [comment]
confirmed fixed.
