### ISSUE TITLE
Building Permits - Demolition - Not Getting Notification of Issuance

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2212]
My demo application is closed/complete and I never received a notification that my permit was issued. I processed this permit completely in the back office.

![image](https://user-images.githubusercontent.com/31770504/68422862-fbc14880-016e-11ea-8491-b3761890ece1.png)

**Comment by JuanitaMiles** [comment]
@megisys - Why are you assigning Tara? This is not a correspondence issue, its a notification issue. I  created a separate CM issue for tara to fix.

**Comment by ABonomo21** [comment]
received 251335
![image](https://user-images.githubusercontent.com/47611580/68426575-6924a780-0176-11ea-85bf-377c1afdc062.png)
