### ISSUE TITLE
Building Permits - Demolition - Not Getting Issuance Correspondence

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2213]
My demo permit is in a closed and complete status and I never received the official issuance or placard correspondence.

Per AB - It should get both.

![image](https://user-images.githubusercontent.com/31770504/68423125-81dd8f00-016f-11ea-946a-37b5c88a3853.png)

**Comment by TaraF** [comment]
This is fixed.  Please re-test.

**Comment by ABonomo21** [comment]
received 251335
![image](https://user-images.githubusercontent.com/47611580/68426642-8bb6c080-0176-11ea-82ca-ec7e078b9d52.png)

![image](https://user-images.githubusercontent.com/47611580/68426666-983b1900-0176-11ea-81a4-09e6bd539def.png)
