### ISSUE TITLE
Building Permits - Demolition - Awaiting Application Revisions Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2214]
When i enter the Awaiting Applicant Revisions milestone and the $27 revision fee generates, I get two different emails: Building Application Payment Required & Building Permit Resubmit Required.

I should not be getting the Building Application Payment Required notification at this milestone.

![image](https://user-images.githubusercontent.com/31770504/68423897-ed742c00-0170-11ea-9282-af4f4772e1a3.png)

![image](https://user-images.githubusercontent.com/31770504/68423924-f8c75780-0170-11ea-990f-e0c53b25c0cd.png)

![image](https://user-images.githubusercontent.com/31770504/68423950-04b31980-0171-11ea-966c-b09da0eb7ba4.png)

**Comment by ABonomo21** [comment]
only got one in my retest 
![image](https://user-images.githubusercontent.com/47611580/68426446-2b278380-0176-11ea-838d-79fa7334d6fb.png)
![image](https://user-images.githubusercontent.com/47611580/68426455-2fec3780-0176-11ea-8ee9-74c8a4d9b969.png)
