### ISSUE TITLE
Building Permits - Signs - Awaiting Applicant Revisions Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2215]
When i enter the Awaiting Applicant Revisions milestone and the $27 revision fee generates, I get two different emails: Building Application Payment Required & Building Permit Resubmit Required.

I should not be getting the Building Application Payment Required notification at this milestone.

![image](https://user-images.githubusercontent.com/31770504/68432891-52d11880-0183-11ea-929e-fcff4a38d4f8.png)

![image](https://user-images.githubusercontent.com/31770504/68432924-60869e00-0183-11ea-830a-a5cbc46dfa27.png)

![image](https://user-images.githubusercontent.com/31770504/68432949-6ed4ba00-0183-11ea-997d-87634893d3e7.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68710626-de70ed80-0565-11ea-9ae7-e0ad96c7841d.png)
![image](https://user-images.githubusercontent.com/47611580/68710657-edf03680-0565-11ea-93c7-f76945e3b70a.png)
