### ISSUE TITLE
Building Permits - Signs - Fee Payment Status Check at Awaiting Revisions (ASHLYE PLEASE CONFIRM)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2216]
Ashlye please confirm that the sign AP should be consistent with the rest of the building aps and should not require the revision fee to be paid at the Awaiting Applicant Revisions milestone.

![image](https://user-images.githubusercontent.com/31770504/68433205-fc180e80-0183-11ea-905f-fdf01bc79c44.png)

**Comment by ABonomo21** [comment]
That is correct-it should follow the same workflow as the other applications. I will have Dan look at this one today. @megisys

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68710682-01030680-0566-11ea-97c1-94f9d1e33556.png)
