### ISSUE TITLE
Building Permit- Non Residential - R4C Details page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2219]
all the non res text boxes on r4c have "NaN" in them?? I am not sure what this is but it should not be there.. 

![image](https://user-images.githubusercontent.com/47611580/68484242-e39f0700-020a-11ea-9453-66ae035451f4.png)

![image](https://user-images.githubusercontent.com/47611580/68484262-ed286f00-020a-11ea-9360-e7394a6a87ac.png)

**Comment by calequin** [comment]
fixed. remove popup enabled = false from decimal/integer edit boxes
![image](https://user-images.githubusercontent.com/47603568/68608555-d38c5f00-0478-11ea-9993-6f92bc349b85.png)
