### ISSUE TITLE
Building Permit - Non Residential- Unable to submit in r4c

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2220]
I am not able to submit non res permits in r4c 
![image](https://user-images.githubusercontent.com/47611580/68484494-59a36e00-020b-11ea-8c4e-6385e59b8283.png)

**Comment by ABonomo21** [comment]
christian will try to resync after mobile at 12-

will pick up where i left off with permit 251341 non res to pay fees

**Comment by megisys** [comment]
DO not use your account AShlye. You have too much data in your dashboard. Use Emily for Rhtyhm please

**Comment by megisys** [comment]
I also Made sure things were alligned

**Comment by ABonomo21** [comment]
still unable to submit. 

![image](https://user-images.githubusercontent.com/47611580/68502590-ca0fb680-022e-11ea-8005-270b953fff9e.png)

**Comment by ABonomo21** [comment]
okay to submit online 251382
