### ISSUE TITLE
planning-verify-provide comments error when paying fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2223]
cant pay fee because its asking for review comments

![image](https://user-images.githubusercontent.com/4129185/68485912-126aac80-020e-11ea-9c9a-e22ba02808e6.png)

MW

**Comment by dhenry-KCI** [comment]
same result on V252219 and V2052222

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/68486694-9f623580-020f-11ea-9f99-b43102f608a1.png)

![image](https://user-images.githubusercontent.com/4129185/68486718-b143d880-020f-11ea-80d5-96d356719b5a.png)

**Comment by megisys** [comment]
Believe it or not this is due to the report change i made. Adjusted this

**Comment by dhenry-KCI** [comment]
fixed per V252225

MW
