### ISSUE TITLE
Building Permits - Trailer - Fee Payment Status Check at Awaiting Revisions

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2224]
The Trailer AP should be consistent with the rest of the building APs and should not require the revision fee to be paid at the Awaiting Applicant Revisions milestone.

![image](https://user-images.githubusercontent.com/31770504/68486163-902eb800-020e-11ea-9d22-cd8b82d6ad05.png)

**Comment by megisys** [comment]
Juanita. We only wanted to turn these off to stop Pdox confusion and order of events. Are trailers going through Pdox. Turned off for now.. Same as Signs.
