### ISSUE TITLE
Building Permits - Trailer - Awaiting Applicant Revisions Notifications 

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2225]
When I enter the Awaiting Applicant Revisions milestone and the $27 revision fee generates, I get two different emails: Building Application Payment Required & Building Permit Resubmit Required.

I should not be getting the Building Application Payment Required notification at this milestone.

![image](https://user-images.githubusercontent.com/31770504/68486326-dd128e80-020e-11ea-8206-8b78fd7ee968.png)

![image](https://user-images.githubusercontent.com/31770504/68486369-f3b8e580-020e-11ea-838c-a30c71656da9.png)

![image](https://user-images.githubusercontent.com/31770504/68486399-ff0c1100-020e-11ea-84b6-a814a31c7ebb.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68710888-71aa2300-0566-11ea-86ec-628052f1383a.png)
