### ISSUE TITLE
Building Permits - Tanks/Zoning Certificate - Awaiting Applicant Revisions Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2226]
For both Tanks and Zoning Certificate
When I enter the Awaiting Applicant Revisions milestone and the $27 revision fee generates, I get two different emails: Building Application Payment Required & Building Permit Resubmit Required.

I should not be getting the Building Application Payment Required notification at this milestone.

![image](https://user-images.githubusercontent.com/31770504/68495895-1b17ae80-021f-11ea-8c4f-f6dd486b8eb4.png)

![image](https://user-images.githubusercontent.com/31770504/68495917-2bc82480-021f-11ea-82af-ae4bb414d15b.png)

![image](https://user-images.githubusercontent.com/31770504/68495936-3682b980-021f-11ea-8062-34bc5373ad70.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68710847-5808db80-0566-11ea-9185-233f9bdb0b2b.png)
![image](https://user-images.githubusercontent.com/47611580/68710871-6525ca80-0566-11ea-838a-fee0f0ea27c5.png)
