### ISSUE TITLE
Building Permits - Tanks/Zoning Certificate - Fee Payment Status Check at Awaiting Revisions

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2227]
The Tanks and Zoning Certificate AP should be consistent with the rest of the building APs and should not require the revision fee to be paid at the Awaiting Applicant Revisions milestone.

![image](https://user-images.githubusercontent.com/31770504/68496174-b741b580-021f-11ea-809b-1db2e10b6f7a.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68711044-d1083300-0566-11ea-9c73-00a7e75c7339.png)
![image](https://user-images.githubusercontent.com/47611580/68711265-4c69e480-0567-11ea-9653-6a65e3bc793c.png)
![image](https://user-images.githubusercontent.com/47611580/68711292-57247980-0567-11ea-9ef0-d087ce6835ab.png)
