### ISSUE TITLE
Official Issuance- spelling error 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2229]
should be county not country
![image](https://user-images.githubusercontent.com/47611580/68530511-98522a80-02d6-11ea-9613-c4d7d95b468d.png)

**Comment by TaraF** [comment]
This is fixed.  Ready for re-test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68862273-27868600-06bb-11ea-8892-dd4519ce42c1.png)
