### ISSUE TITLE
R4C - Inspection Comments 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2230]
Inspection comments are not view able in R4c
![image](https://user-images.githubusercontent.com/47611580/68531090-a86d0880-02dc-11ea-9e66-ead852bd2800.png)
![image](https://user-images.githubusercontent.com/47611580/68531093-aefb8000-02dc-11ea-92e5-c992cad53f62.png)

**Comment by megisys** [comment]
Comments says See Violations online.

**Comment by calequin** [comment]
comments on a violation come accross on rhythm 
![image](https://user-images.githubusercontent.com/47603568/68613555-a34abd80-0484-11ea-9410-f59aff1f770a.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69256121-fe686880-0b86-11ea-8c3a-199acf71c822.png)
