### ISSUE TITLE
Contact Records on Parcel/Address

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2236]
The customer service techs do not have all the required tabs to edit contacts for a parcel
![image](https://user-images.githubusercontent.com/47611580/68534111-a3b94c00-02fe-11ea-8f9e-cf57bf3cf659.png)

they only have Info, Legal and Address

**Comment by megisys** [comment]
There are no Edit options here..  You click on Contacts for an Address. Or you click on Linked Parcels and drill down through there.

**Comment by ABonomo21** [comment]
#2245
