### ISSUE TITLE
A/P Name Requirement 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2237]
Is it possible to make the a/p name field a required field for building and use permits? I found during training staff was missing making this entry.

**Comment by ABonomo21** [comment]
Dan - these a/ps still need the requirement for a/p name

city impact
demolition
fro
signs
tanks
zoning cert
trailer
driveway

home occ
land use

**Comment by megisys** [comment]
Added
