### ISSUE TITLE
Service Requests/Code Enforcement Cases - Not Public

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2239]
We need to make sure that Service Requests and Code Enforcement Cases are not Public. 

Service requests can turn into violations which are not public.

**Comment by calequin** [comment]
service requests turn into cases and those have been turned off from portal for public and customer. I have also turned off any case related record from being visible or searchable.
![image](https://user-images.githubusercontent.com/47603568/68621038-65ee2c00-0494-11ea-9be5-578acce83fe4.png)

**Comment by ABonomo21** [comment]
thanks christian- 

do you know why the search fields are still showing up in the look up record for the highlighted below, they are all "service requests"

and blighted properties should not even be an option as Frederick County does not have a blighted properties ordiance

![image](https://user-images.githubusercontent.com/47611580/68707958-b763ed00-0560-11ea-8731-5d769081b348.png)


![image](https://user-images.githubusercontent.com/47611580/68707997-cea2da80-0560-11ea-886d-adb85b407963.png)

![image](https://user-images.githubusercontent.com/47611580/68708034-e4b09b00-0560-11ea-97e2-1f70188cf92e.png)

![image](https://user-images.githubusercontent.com/47611580/68708088-fd20b580-0560-11ea-8b66-1b70796116a3.png)

![image](https://user-images.githubusercontent.com/47611580/68708125-0e69c200-0561-11ea-9229-44cc901a5d40.png)

![image](https://user-images.githubusercontent.com/47611580/68708148-1d507480-0561-11ea-90ab-646500b33e29.png)

**Comment by calequin** [comment]
Blighted Properties is a Fire Marshal service request. I have removed all public searched of service requests from R4C

**Comment by megisys** [comment]
Turn off for Public. Christian with Infor Development to follow up.

**Comment by calequin** [comment]
removed is public from Service Requests

**Comment by calequin** [comment]
setting as ready for retest because is public has been removed. Need to get development to look at allowing the public to submit a request without logging in but disabling the searchable options.

**Comment by calequin** [comment]
is public has been turned off. The search bar will still show them listed but once you click on the record it is not visible to the public unless you created the request.

**Comment by ABonomo21** [comment]
they are all still there??? these cannot be an option -

![image](https://user-images.githubusercontent.com/47611580/69166692-a9aeea00-0ac1-11ea-9fa1-63de985b76eb.png)

**Comment by dhenry-KCI** [comment]
Enhancement request with development. closing for Post go-live

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69571226-8edfe800-0f8f-11ea-8d8d-2aefa55f3486.png)

we need to be able to allow citizens to submit service request - hide as many fields as possible under the look up records

**Comment by ABonomo21** [comment]
Dan corrected this with an alternative solution that MW and I checked and are okay with for go live will want to improve this after go live
