### ISSUE TITLE
Monitored Email Setup and Confirmation

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2241]
I need to be able to test the "monitored email for permits" 

I think these were created but I need to make sure that reports that cannot be emailed to applicants  such as 11 month extension letters and expired permit letters/ COO and COC etc. are being sent to this email to be printed and mailed. I am not sure if there is a way to test this but at a minimum I need to make sure the email is set up.

**Comment by megisys** [comment]
This to be completed on the Thursday and Friday before Go Live Weekend

**Comment by dhenry-KCI** [comment]
Also duplicate of a ticket #2292 closing
