### ISSUE TITLE
Building Permit - Non Res- Official Issuance and Placard Correspondence

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2242]
I did not receive the correspondence at permit issuance for my non res permit 251382- there is nothing set u[ in the system we made sure that batch manager for correspondence was running. 

I should have gotten the official issuance and a placard.

**Comment by dhenry-KCI** [comment]
Waiting to release until we can confirm fix. Dependent on fix for #2251
--

**Comment by TaraF** [comment]
Official Issuance and Placard are now generated on milestone of Permit Issued.  Ready for re-test.
