### ISSUE TITLE
Building Permit- Non Res- Certificate of Completion- Correspondence

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2243]
I did not get a certificate of completion for permit 251382 once the pending certificate review was approved and the building permit was finalized -

**Comment by dhenry-KCI** [comment]
Waiting to release until we can confirm fix. Dependent on fix for #2251

**Comment by TaraF** [comment]
This is now generating on the milestone of Complete.  Ready for re-test.
