### ISSUE TITLE
Securities and Permissions Clean Up 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2245]
we need to make sure securities and permissions are set up as accurately as possible 

Some corrections need to be made as a result of the simulation training on 11.09.19- see white board will discuss with Dustin.

**Comment by ABonomo21** [comment]
one of the corrections that needs to be made for securities and permissions is to remove the edit function from all staff. 
![image](https://user-images.githubusercontent.com/47611580/68620493-9be2de80-049b-11ea-8192-5513a97f3d9a.png)

**Comment by ABonomo21** [comment]
Here are the securities and permissions issues we found on Saturday

Shannon Walters need to be able to waive, edit and recalculate fees 
Shannon Walters needs to be able to change status/ milestone 
All other techs need to have the permission for changing status and milestone removed
Linda Wivell needs to be added as a contact in the system
All techs with the exception of Emily Pearl and Ashlye Bonomo need to have the permissions removed to be able to pay fees
Bob was had issues with code enforcement - please follow up with him to confirm what permissions he and the chief inspectors should have

**Comment by ABonomo21** [comment]
Training 11.15.19- @dhenry-KCI 

Eric and Vijay had supervisor override permission and should not 
they also should not have the change status and milestone permissions
![image](https://user-images.githubusercontent.com/47611580/68969758-becf0480-07b3-11ea-9300-a0d619e2bae7.png)

**Comment by dhenry-KCI** [comment]
Edit, Disable Page and SHow Tabindex will be removed at Go-live. Securities and permissions from testing on 11.09 are corrected. Will confirm updates for vj and eric 11.22

**Comment by ABonomo21** [comment]
we need to make sure that only supervisors have the permissions to remove logs

**Comment by dhenry-KCI** [comment]
updated.
