### ISSUE TITLE
Data Migration- Discussion

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2246]
We need to have a follow up discussion on the data migration and in life mapping- we have a number of permits showing up in Dashboards that will need to be cleaned up prior to go live.

**Comment by megisys** [comment]
Run the Expired Building Permit Process

**Comment by megisys** [comment]
Run the Batch Manager Task

**Comment by ABonomo21** [comment]
will clean up dan showed us how even thought this should have been done in H7 and the data should not have been migrated
