### ISSUE TITLE
Building Permit- Resbldg - Placard

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2248]
Building Placard is not available at the permit issuance milestone for a resbldg permit - specifically a work type of and ADU - 
![image](https://user-images.githubusercontent.com/47611580/68616789-c29d1700-0493-11ea-8fb4-a24c513db4ef.png)

**Comment by TaraF** [comment]
@ABonomo21  -  for on demand reports, it looks like I have the placard set to show at the milestone of Permit Issued or higher.   However, for Official Issuance, nothing is set for milestones.  

Do you want them both set that way?  or would you like me to lift the milestone restrictions from placard?

**Comment by ABonomo21** [comment]
report is available - must go out of the application when progressing to refresh on demand reports
