### ISSUE TITLE
Building Permit- Gross Alter Floor Area

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2250]
Dan- i do not remember what we discussed this morning - but do we think we need to make the gross altered floor area required on building permit applications for Resbldg, Resuse and NonRes since that is what drives the fee? 

I am thinking it may be a good idea?? thoughts?? 

![image](https://user-images.githubusercontent.com/47611580/68620317-3abb0b00-049b-11ea-9a9e-b185658adea8.png)

**Comment by megisys** [comment]
I made it required. If we don't like it. We will have to make status checks on Completeness check for where we are expecting it to be greater than 0

**Comment by ABonomo21** [comment]
thanks
