### ISSUE TITLE
Correspondence 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2251]
I know Tara emailed me that correspondence was not working - but i wanted to make sure it was noted that i am not getting any correspondence for Resbldg Permits in addition to the non-res permit from earlier.

**Comment by dhenry-KCI** [comment]
We are hvaing system wide CM issues. Dan is looking into this. Until resolved we can't confirm fixes for:
#2243 
#2242 
#2068 
#2058

**Comment by ABonomo21** [comment]
received a ton of emails for correspondence will monitor throughout simulation training
