### ISSUE TITLE
Code Violations - Mobile and R4C

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2252]
Please follow up with Bob @dhenry-KCI 

Electrical Violations -text not showing up in R4C 
Building Violations are not available to add

**Comment by calequin** [comment]
need to switch Electrical Violations from Code Text to Code Descritpion in order to view on R4C.
Building Violations are listed against NonRes, Res, Signs, Tanks, Trailer. Should they be listed on all AP types and Inspections?

**Comment by megisys** [comment]
SQl Update to move data around..

**Comment by megisys** [comment]
Added Code to Desc. Manually clean up from here. As Code Text is too long for the description field. Inspection reports should include full violation details

**Comment by ABonomo21** [comment]
per bob okay
