### ISSUE TITLE
Official Issuance Language

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2253]
Emailed Tara

**Comment by TaraF** [comment]
The language is part of the original reports we received.  See email and see attached below.  Please compare and let me know if there is some updates you want. 
[BuildingPermitReport_AllAPs.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3843255/BuildingPermitReport_AllAPs.pdf)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69166231-e8907000-0ac0-11ea-9a6c-e09029aa3eb9.png)

**Comment by ABonomo21** [comment]
provided tara documentation on 11.25.19

**Comment by TaraF** [comment]
These updates were made based on our understanding.  Ready for re-test.

**Comment by ABonomo21** [comment]
checked 11.27.19
