### ISSUE TITLE
Planning-problems-not transferring from 2nd review cycle to 3rd cycle-need to change transfer description

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2255]
added problem during first review.  Those selected to be transferred to the 2nd cycle transferred successfully.  On 2nd cycle those that were selected to be transferred to the 3rd cycle did not transfer.  See A252229

MW

**Comment by megisys** [comment]
I feel like the User added transfer manually to one of the problems. They need to leave it blank. Only Set Addressed. System will take care of these automatically

**Comment by dhenry-KCI** [comment]
Problems is a PROBLEM. FRO F252232 is not transferring problems. They were entered to transfer from 1st cycle to 2nd. They are not showing under 2nd. They are not showing under 3rd. AREED
1st cycle
![image](https://user-images.githubusercontent.com/4129185/68702379-b75eef80-0556-11ea-8e3c-ac64588f76de.png)
2nd cycle
![image](https://user-images.githubusercontent.com/4129185/68702427-ce9ddd00-0556-11ea-88dc-46428bb9c5fe.png)
3rd cycle
![image](https://user-images.githubusercontent.com/4129185/68702465-df4e5300-0556-11ea-8e14-3038d98a2654.png)

**Comment by dhenry-KCI** [comment]
problems didn't transfer

![image](https://user-images.githubusercontent.com/4129185/68863793-05dace00-06be-11ea-8047-db3de399e735.png)


![image](https://user-images.githubusercontent.com/4129185/68863754-f52a5800-06bd-11ea-8200-53723e3e6af1.png)

MW

**Comment by megisys** [comment]
Leave unaddress Problems blank.. All non resulted problems move

**Comment by dhenry-KCI** [comment]
clicking the transfer box results in the problem not transferring to the next review cycle.  As discussed with Dan, change the description to say something like "do not select this!".  

MW

![image](https://user-images.githubusercontent.com/4129185/68952967-e364b580-078e-11ea-9785-db8e93f15a95.png)

**Comment by megisys** [comment]
F252234 See this Application. Only approve Problems.. Any blank result problems will move to the next review after being added.

**Comment by dhenry-KCI** [comment]
tested during training yesterday and works

MW
