### ISSUE TITLE
Liquor License - R4Civics will not create a new profile 

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#2256]
R4Civics will not create a new profile sometimes, there is no successful message. Also the  'im not a robot' selection does not come up, everything seems frozen.

**Comment by calequin** [comment]
part of the connection reset issue we see globally. I have removed notification per @megisys which should also clear out the wait time.

**Comment by dhenry-KCI** [comment]
Confirmed Fixed
