### ISSUE TITLE
Liquor License - system needs to add the Transfer Fee to Transfer applications process

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#2258]
Transfer fee should be $20.  Right now the wrong fees are showing in IPS, - it is showing what a brand new application (non transfer) would be.  

The fee type exists in the system.  If application type is Transfer, regardless of class, need a flat fee of $20.  Fee type is TRANSFER FEE.

**Comment by dhenry-KCI** [comment]
Confirmed fixed
