### ISSUE TITLE
PLANNING - FRO PROJECT DETAILS - condition check or redline needs moved so fee in lieu fee will populate

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2259]
Application Details - FRO Project Details needs to have a requirement that it is completed before the last fee milestone. Otherwise, if fee in lieu is a mitigation type the fees do not generate and the project will finalize without the fee in lieu mitigation.
AReed/MWilkins

![image](https://user-images.githubusercontent.com/4129185/68706886-b205a300-055e-11ea-807f-f87462e28846.png)
![image](https://user-images.githubusercontent.com/4129185/68707478-d6ae4a80-055f-11ea-91de-8249d3e7f8f2.png)

**Comment by megisys** [comment]
I added to Under Review and wont hold up if their is a RESUBMIT. it will enforce after all reviews are approved. Let me know.

**Comment by dhenry-KCI** [comment]
works great!



![image](https://user-images.githubusercontent.com/4129185/68957448-0f386900-0798-11ea-96b2-ca8326a49a3f.png)
