### ISSUE TITLE
Resuse details Page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2260]
Resuse Details Page is not generating on R4C to be completed 
![image](https://user-images.githubusercontent.com/47611580/68768487-98ad3700-05f0-11ea-90c8-b0cbf457034b.png)

**Comment by calequin** [comment]
fixed. resuses detail page comes up on application.
![image](https://user-images.githubusercontent.com/47603568/68805026-a088cd80-0628-11ea-9fca-c5e08cc15457.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68875010-1bf18a00-06d0-11ea-8a36-34699c905765.png)
