### ISSUE TITLE
Inspection Error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2261]
unable to schedule inspection back office for same day
![image](https://user-images.githubusercontent.com/47611580/68777181-46bfdd80-05ff-11ea-98fe-83d7a1111adb.png)
inspection # 1006659

**Comment by megisys** [comment]
I believe I solved. this PLEASE test

**Comment by ABonomo21** [comment]
i was able to put a scheduled date in for the same date. 1006793 but i was not able to put a **request** **date** in for the same date and should be able to put the **request date** in for the same day or after 12 noon if i am inserting an inspection in the back office.

**Comment by ABonomo21** [comment]
need to change the time on the inspection if it happens 
![image](https://user-images.githubusercontent.com/47611580/68877551-41809280-06d4-11ea-8dd4-f3e553e84e94.png)
