### ISSUE TITLE
Planning - PREPLAT - First Completeness Check Cycle #

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#2263]
Created a back office PREPLAT application from scratch and first Completeness Check review is showing as a second cycle.

![image](https://user-images.githubusercontent.com/31770504/68782119-d452fb80-0606-11ea-82ce-5ed7fcdf38ba.png)

**Comment by dhenry-KCI** [comment]
fixed per below test

![image](https://user-images.githubusercontent.com/4129185/68956022-35103e80-0795-11ea-968f-7d10124c2555.png)


MW
