### ISSUE TITLE
Monthly Building Permit Applications Report- Reporting

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2265]
only Building permits should appear on the Monthly Building Permit Applications Report

Water and Sewer Capacity, Grading, Fire , Driveway aprons (DWS), FRO, City Impact Fees, Electrical and Plumbing  should not populate on this report. 

Only Building Permits- resuse, resbldg, nonres, tanks, signs, demo, trailer - should generate on this report. 

11/13/19 ep

**Comment by TaraF** [comment]
This has been updated. Ready for re-test.
