### ISSUE TITLE
Planning/ Building-IPS-unable to resubmit on Hansen7 projects

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2267]
tried using resub log to generate another review cycle on a hansen7 application but it didn't work.  There isn't a applicant resubmit option under application details either.

![image](https://user-images.githubusercontent.com/4129185/68861810-420c2f80-06ba-11ea-837c-ae204180e323.png)

MW

**Comment by dhenry-KCI** [comment]
also have no idea where the water/sewer report came from.  That's not a planning report

**Comment by megisys** [comment]
OK.. So you will need to result the outstanding reviews... But you need to first ensure that the Application has the applicant actions detail page added

**Comment by dhenry-KCI** [comment]
19578 - I resulted all outstanding reviews and I received the standard email for after a cycle is complete. There was no Application details page, however... I added the Resubmittal Submitted RESSUB log and a new cycle was started. The problem is... It didn't populate all of the necessary reviews. I should have a review for all denied or cond approved results. I had did not get another review for PWDR. But I did get one for EH. Both of those reviews transferred from HANSEN 7 at COND APPROVED.
AREED
![image](https://user-images.githubusercontent.com/4129185/69063541-af85cc00-09ea-11ea-9504-ff7cd21ad935.png)

**Comment by megisys** [comment]
We don't have Cond Approve anymore. You will need to add these manually. Also you need to add the Applicant Action Page Manually. There is no bug here. @dhenry-KCI

**Comment by dhenry-KCI** [comment]
I understand that we do not have Cond Approve anymore. What I don't understand is why it would ad EH that was Cond Approved and not PWDR that was also Cond Approved. AR

**Comment by dhenry-KCI** [comment]
19575 worked when Dan changed cond approved and denied to Resubmit. 
FOR all in life applications that are "under review" need to change cond approved and denied review result to RESUBMIT. Also need to automatically add the "Applicant Actions" detail page to those applications. AREED

**Comment by ABonomo21** [comment]
We need to make time for me to test how this will affect building permit applications as well- ab

**Comment by dhenry-KCI** [comment]
fixed
