### ISSUE TITLE
Planing-IPS-missing our reports

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2268]
where did all of our reports go?

![image](https://user-images.githubusercontent.com/4129185/68867515-f2326600-06c3-11ea-946d-047390a24d3d.png)

**Comment by megisys** [comment]
If you progress and Application to a new Milestone where there are formulas to not allow reports to show up until certain milestones. You need to close the application and reopen. As the report links need to refresh
