### ISSUE TITLE
Building-Demo-NonRes-Certificate Review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#227]
The Certificate Review is generating at the wrong milestone. It should generate after the final inspection has passed.

![image](https://user-images.githubusercontent.com/47611580/53982945-2345aa00-40e4-11e9-9686-73791adabb12.png)

**Comment by megisys** [comment]
Moved to Admin Closure After Final Inspection

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54129306-5b026980-43e4-11e9-9033-c149ebefec28.png)
