### ISSUE TITLE
Planning-IPS-ips not updating when resub sent to PDOX

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2270]
this was the issue Juanita found a month or two ago.  It was fixed but now the bug is back.  Resub in Pdox, opened application in IPS and the milestone is off.  Have to hit the check box for IPS to move to under review.  If you don't and you result your Pdox review then IPS is out of whack.

![image](https://user-images.githubusercontent.com/4129185/68950710-b57d7200-078a-11ea-86a8-0e13a5705120.png)
![image](https://user-images.githubusercontent.com/4129185/68950741-c29a6100-078a-11ea-987b-6b0eced56f9b.png)

MW

**Comment by megisys** [comment]
Tested with Mike.. We look Good..

**Comment by dhenry-KCI** [comment]
tested yesterday with Dan and tested PP252282, SP252283, and PL252284.  worked on all

MW
