### ISSUE TITLE
PDox-adding checklist items is missing!

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2271]
![image](https://user-images.githubusercontent.com/4129185/68959085-63911800-079b-11ea-9581-25fc3d6ee0c7.png)

![image](https://user-images.githubusercontent.com/4129185/68959217-a652f000-079b-11ea-897e-cfcde1d00e88.png)

MW

**Comment by RS-Avolve** [comment]
Issue resolved - Planning miscellaneous checklist items added

**Comment by dhenry-KCI** [comment]
checked plat, site, FRO, and PWCons and everything is working now

MW
