### ISSUE TITLE
DW- Related Records

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2273]
25149

**Comment by ABonomo21** [comment]
251489 required a PW Construct be related - Ashlye manually inserted one, There was a redline that stopped it

251490 did not require a PW construct- one was not added. But it should have been held up by a redline.

**Comment by megisys** [comment]
There is no Functionality for PWconstruc for Driveway. The Reviewer is to make this determination on review. 

![image](https://user-images.githubusercontent.com/47392306/69068063-2377a280-09f2-11ea-80ab-28af8e381433.png)

**Comment by dhenry-KCI** [comment]
@ABonomo21 - please work with @megisys in the morning.

**Comment by ABonomo21** [comment]
Vijay will review if a PW construct is required prior to approving his review on the common drive. 

The plat cannot be recorded until the apron is completed, need to make sure we have a process in place to notify DR when  the apron is approved for plat redecoration.
