### ISSUE TITLE
Building Permits- Driveway Placard 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2275]
Placards for Driveway are not filling the work type and should be, the work type will always be blank because it should be pulled by the a/p type on this application which would be Driveway Apron

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68968091-baa0e800-07af-11ea-99fd-1f87672df316.png)

**Comment by TaraF** [comment]
Updated. Ready for re-test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69351451-59fb2a80-0c49-11ea-9fc2-3e8b4949e3fe.png)
