### ISSUE TITLE
Building Permits- Driveway Official Issuance / Addressing issue?

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2276]
I used an address that was on the valid address list and it is not pulling any of the parcel details on to the official issuance report- 

is this a bad address or is this a reporting issue
![image](https://user-images.githubusercontent.com/47611580/68968203-03f13780-07b0-11ea-8d25-400454aa633d.png)

**Comment by megisys** [comment]
This address is bad now.. No Parcel

**Comment by dhenry-KCI** [comment]
Bad address / Duplicate to other tickets.
