### ISSUE TITLE
Building Permit - Driveway - Inspection Assignment 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2277]
Permit number 251489 and 251490 did not generate an inspector which as a result did not relate the inspector as an employee record.

**Comment by ABonomo21** [comment]
also permit number 251495 (which was probably all the same address)

**Comment by megisys** [comment]
Bad Address - No Parcel

**Comment by dhenry-KCI** [comment]
Bad addressing / parcel issue. Duplicate to other tickets.
