### ISSUE TITLE
Planning-APFO-Exemption

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#228]
selected exemption criteria, including non-residential, and a school review generated.  There should not be a school review for non-res.

![image](https://user-images.githubusercontent.com/4129185/53983166-9f3ff200-40e4-11e9-96bb-c4a408a49769.png)

![image](https://user-images.githubusercontent.com/4129185/53983199-b1219500-40e4-11e9-806d-9ecacc89ee5f.png)

MW 3/7/19

**Comment by megisys** [comment]
But your occupancy is RES Single Family Dwelling

![image](https://user-images.githubusercontent.com/47392306/53983501-4de43280-40e5-11e9-9f96-4162e36aede4.png)

**Comment by dhenry-KCI** [comment]
smart ass

**Comment by megisys** [comment]
LOL
