### ISSUE TITLE
Building Permits- Grading _ MJ/PI/SWM

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2280]
All reviews at the under review milestone need to generate a due date once the attorney review and director condition have been approved. 
![image](https://user-images.githubusercontent.com/47611580/68970001-474da500-07b4-11ea-9b74-042ef889948b.png)
![image](https://user-images.githubusercontent.com/47611580/68970015-53d1fd80-07b4-11ea-8e3d-9b9d32748414.png)

this is because the review process for all agencies does not start until the performance agreement routing form has been accepted by the county attorney and department director. Because we are continue to route via paper and not electronically, we need to have this corrected. Right now in IPS the review due dates for all agencies is due the same day as the attorney review.

![image](https://user-images.githubusercontent.com/47611580/68970166-a8757880-07b4-11ea-90df-bb2c1668efde.png)

My solution to fix this is to make the **Attorney Review** a **condition** just list the **PWDirector** and not generate the due dates for all other agencies until both conditions are approved as YES. 
![image](https://user-images.githubusercontent.com/47611580/68970340-01451100-07b5-11ea-965b-9f4548e3c279.png)

**Comment by dhenry-KCI** [comment]
Will add a milestone prior called administrative review - remove Attorney Review

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69354050-8153f680-0c4d-11ea-987f-e8e7005b21a0.png)

director review milestone added, PW director and attorney review once those are approved, at the under review milestone ecs and pwdr generate with a 1 week review date from when they were added.
