### ISSUE TITLE
Mobile Training 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2281]
Dustin- 

Eric would like more mobile training he said he just got his tablet 2 days ago and did not feel that the intro was enough for him or his staff. Please work with Bob to schedule training

Apparently Eric had a tablet previously but he just got his issued tablet 2 days ago- Eric's tablet was one of the three tablets that went missing....

once you have scheduled please close this ticket

**Comment by dhenry-KCI** [comment]
scheduled close
