### ISSUE TITLE
Building Permit - Grading Permit- work type PI/SWM/MJ

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2282]
Routing form should be available for grading permits with a work type of PI/SWM and MJ at the  under review milestone and nothing is populating in the details 
permit example 251494

![image](https://user-images.githubusercontent.com/47611580/68973116-6ac81e00-07bb-11ea-8cbe-ec6cdf76f50a.png)

the details should be pulled from the related bond information- related bond is located under 

Also the please return executed documents to Tiffany Martin for Delivery to DPW should be removed from the form automatically printing- this section should pull the comments from the comments section on the bond (related bond number - 5051)

![image](https://user-images.githubusercontent.com/47611580/68972866-cb0a9000-07ba-11ea-8aa7-2ea390dd502b.png)

![image](https://user-images.githubusercontent.com/47611580/68973011-276daf80-07bb-11ea-91aa-20d3518534db.png)

**Comment by TaraF** [comment]
This is ready for re-test.
 
NOTE: Meeting Notes from 5/3/2019 with Eric D., VJ, Tiffany M. :
This report is now going to be consolidated with B2 - 39 - rpt_PA_Routing_Multiple_Fund_Types, and it will handle cases of multi fund types against one tracking number and/or multiple APNOs.

**Comment by ABonomo21** [comment]
remove the summary of included bonds from this report 

![image](https://user-images.githubusercontent.com/47611580/69662946-4be74880-1053-11ea-9b91-2530a4339151.png)

**Comment by ABonomo21** [comment]
we do not need the summary on the bottom
![image](https://user-images.githubusercontent.com/47611580/69663884-35da8780-1055-11ea-803a-f26fd435ad45.png)

**Comment by TaraF** [comment]
Summary section removed - ready for re-test. 

![image](https://user-images.githubusercontent.com/4104464/69665996-7fc56c80-1059-11ea-868a-c5593fce4c88.png)

**Comment by ABonomo21** [comment]
thank you
