### ISSUE TITLE
Building Permit- Grading - PI / SWM/MJ

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2283]
no correspondence was received with the pre-construction meeting required notification 
![image](https://user-images.githubusercontent.com/47611580/68973197-a367f780-07bb-11ea-8719-d0275fb27b95.png)
Additionally, the pre-construction meeting checklist should have also gone out with the precon meeting notification. 
![image](https://user-images.githubusercontent.com/47611580/68973394-29843e00-07bc-11ea-8d24-27a22fe360ce.png)
![image](https://user-images.githubusercontent.com/47611580/68973376-1ffad600-07bc-11ea-8776-847cb7c08119.png)

**we also need to add language to this form in the highlighted box after the grading permit placard will be delivered at this meeting it should read...

APPROVED PLANS MUST BE ON SITE AT THE TIME OF PRE-CONSTRUCTION MEETING**

**Comment by TaraF** [comment]
CM is ready for re-test.

@ABonomo21  - please pull out the wording update - and clarify.  I am not sure where you want it or if you want it to replace some existing text or just added at the end. Thanks!

**Comment by TaraF** [comment]
Clarification on 11/25/19, - text needs to be added to the first report above in the Black box.

**Comment by TaraF** [comment]
Both the CM and the language updates have been made.  Ready for re-test.

**Comment by ABonomo21** [comment]
closing
