### ISSUE TITLE
Bond Release Documents 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2284]
All of the bond documents are blank when trying to open

![image](https://user-images.githubusercontent.com/47611580/68973669-deb6f600-07bc-11ea-80ba-5c7b3fb7600f.png)

Also where it reads **Security Instrument** it should say **Bond**.

**Comment by megisys** [comment]
Updated the Names of Reports.

**Comment by megisys** [comment]
The set-up of these reports looks wrong.. The Paramater in Building Application NO. and not Bond

**Comment by TaraF** [comment]
@megisys we are already working on this on the SSRS side. thanks

**Comment by TaraF** [comment]
Notes for follow up meeting with EP:

1) Report - Bond Class to drive it
Amend Letter of Credit - LCREDIT
Cancel Letter of Credit - LCREDIT
Amend Security (Bond) Instrument - BOND
Amend Security (Bond) Instrument - BOND
Release - County Escrow - none (currently, is there another driver for this besides APNO?)
Release - Town - none (currently, is there another driver for this besides APNO?)

2) Historically these reports used a PRINCIPAL = Y on contact field which was only carried over int he comments and not reliable in IPS.  Can we base this instead on Bond Contact with a Capacity type of BANK?  is that true in all cases?

3) Currently these reports only run if there is a release.  Could there ever be the case where you have a deposit with no release and need to run an amend? (thinking no - just confirming)

4)Confirm: Cancel Letter and Cancel Security are only needed if $0 (deposit and releases cancel out)

5) Based on what the report is asking for, it may be best to pass in APNO AND BONDNO.  Need to confirm IPS can support as it seems deployment is no longer supporting APNO parameters under CDR Bond.

**Comment by TaraF** [comment]
Work around has to be manually typing in APNO once prompted (BONDNO is automatically picked up), reviewed with Ashlye and Emily 12/2/19.  Tested, approved, finalized.
