### ISSUE TITLE
Building Permit - Minor Grading 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2286]
Permit 251499 was an spawned minor grading permit from a building permit # 251496
it went directly to awaiting applicant resubmit which it should, however, it generated 2 completeness checks, the first completeness check should have automatically had a result as resubmit so that staff knows to only result the second one or they will not be able to progress the permit. 
![image](https://user-images.githubusercontent.com/47611580/68974000-a6fc7e00-07bd-11ea-8b9b-a5e24c20b4d4.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69164847-b716a500-0abe-11ea-9250-b5bac094b72c.png)
