### ISSUE TITLE
Monitored Inbox Checking & set-Up Test

### ISSUE THREAD

**Issue by megisys** [kcigeospatial/Fred_Co_Land-Management#2292]

**Comment by megisys** [comment]
BuildingIPS@FrederickCountyMD.gov - Just sending Building Notifications where the applicant has an email of NOEMAIL.

Will not turn on for all Notifications.

**Comment by megisys** [comment]
PLease Test that the monitored email boxes are getting emails on accounts with NOEMAIL email contact records

**Comment by ABonomo21** [comment]
linked to a new ticket # 2350
