### ISSUE TITLE
Building Permit - Resbldg

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2293]
the sprinkler and fire condition are both populating on a SFD 
![image](https://user-images.githubusercontent.com/47611580/69147132-4e6c0000-0a9f-11ea-89b0-e195770b82d4.png)

**Comment by megisys** [comment]
Slightly different rules. A fire permit of any kind will satisfy both.. Can fix later.

**Comment by dhenry-KCI** [comment]
closoing until post go-live
