### ISSUE TITLE
Resbldg - Impact Fee budget codes

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2294]
![image](https://user-images.githubusercontent.com/47611580/69147200-6e032880-0a9f-11ea-9870-b07ae096f96b.png)

budget accounts are entered incorrectly

**Comment by ABonomo21** [comment]
Please recheck these as well

![image](https://user-images.githubusercontent.com/47611580/69158441-6e59ee80-0ab4-11ea-83a5-2af1303a6901.png)

permit #251556

**Comment by ABonomo21** [comment]
also may want to check cases:

![image](https://user-images.githubusercontent.com/47611580/69158768-ea543680-0ab4-11ea-84bc-5c16eb019035.png)

Building Case  should be 10.98.998.999.44125
may need to double check- zoning, plumbing and electrical

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69173939-d1587f00-0ace-11ea-8fe5-bae60e95bda8.png)

**Comment by ABonomo21** [comment]
we should check all the budget codes to ensure that they are correct.

currently we use peoplesoft codes in Hansen 7- in IPS we are using the new infor codes- we need to ensure that codes have crosswalked over correctly.

broadening this ticket to include all fees not just impact fees

**Comment by pooldaddy** [comment]
Ashlye,
I am verifying impact fees as we speak.   Some have the correct # but not the correct format. Fixing as I go.

Jeff Wisner
Staff Software Integrator
Frederick County Government, IIT
301-600-1811

**Comment by pooldaddy** [comment]
These should all be correct now. Please verify.

**Comment by ABonomo21** [comment]
will do the final check at post go live with data migration
