### ISSUE TITLE
pdox - permissions 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2297]
![image](https://user-images.githubusercontent.com/47611580/69159677-4e2b2f00-0ab6-11ea-9671-8540486f38a1.png)

all intake staff should have these permissions to batch stamp

**Comment by ABonomo21** [comment]
abbie retested on permit 251316 and she received the same error as above

**Comment by megisys** [comment]
Solved
