### ISSUE TITLE
Bond Contacts 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2298]
Bond contacts are not carrying over under capacitites in Bond

IPS Bond #4658 
![image](https://user-images.githubusercontent.com/47611580/69162110-263dca80-0aba-11ea-896e-adb2137573a2.png)

In Hansen 7 Bond #4658
Contact is Josh Mitchell
![image](https://user-images.githubusercontent.com/47611580/69162175-39e93100-0aba-11ea-8785-21a719ed0092.png)
Company is Lexon
![image](https://user-images.githubusercontent.com/47611580/69162212-49687a00-0aba-11ea-8e77-8739e274fc41.png)

The release docs are mailed to the companies.

**Comment by megisys** [comment]
What is there capacity in Hansen 7 ??

**Comment by megisys** [comment]
Hansen 7 didn't have capacity . I checked Production Hansen 7

**Comment by dhenry-KCI** [comment]
@megisys to meet with Emily and @ABonomo21

**Comment by ABonomo21** [comment]
thank you
