### ISSUE TITLE
Use - Landuse - Life Safety Review Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#23]
The system should generate an additional $26.00 review fee if the the DOLS (Life Safety) review is denied.

Logged by. Megan Coffman on 2/7

![image](https://user-images.githubusercontent.com/4129185/52590090-717dcb00-2e0e-11e9-8077-7e72969a5397.png)

**Comment by ABonomo21** [comment]
Testing Failed-The Land Use permit closed and completed after resulting the DOLS review to denied. No revision fee generated either.-AW

![image](https://user-images.githubusercontent.com/47611580/53973740-4c0f7480-40cf-11e9-9d62-fa03564fe86b.png)

**Comment by calequin** [comment]
Per conversation with Ashlye... Only supervisors can deny a review. Keeping this open until a solution is in place on how the application will progress.
