### ISSUE TITLE
Bond InfoViewer - Bond Track 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#230]
The system does not separate contacts and companies like it currently does in Hansen 7. 

The contact is the applicant or the person that the check goes back to. The companies is the Bank, Surety Company, or the County if it is a check.

Bond Tracking # 4917

logged by tiffany martin 3/7/19

**Comment by megisys** [comment]
That is what capacity is for. @dhenry-KCI

**Comment by dhenry-KCI** [comment]
Closing for future enhancement.
