### ISSUE TITLE
Planning-PDox-DPZ reviewers cannot result reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2303]
this error popped up.  Happened to Ashley Moore and Cody Shaw.  Others may be affected but we stopped using PDOX due to errors before they go to this part.

![image](https://user-images.githubusercontent.com/4129185/69179323-5c3e7700-0ad9-11ea-8e67-6e86c88ee861.png)

MW

**Comment by dhenry-KCI** [comment]
FYI, I was able to result reviews on the same PC that Cody was using earlier today so its not the laptops.

**Comment by megisys** [comment]
Out of sync

**Comment by dhenry-KCI** [comment]
those with errors yesterday were able to result today.

MW
