### ISSUE TITLE
PLANNING - REPORTS - copy and paste issue

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2304]
I copied and pasted comments from the PLANNING APPLICATION DETAILS report into problems and they did not populate correctly into the Planning - Project Pending Letter. I pasted into a notepad to try to remove any coding. AREED.

![image](https://user-images.githubusercontent.com/4129185/69178558-de2da080-0ad7-11ea-8d13-28f0c00339f7.png)

![image](https://user-images.githubusercontent.com/4129185/69178708-1b922e00-0ad8-11ea-8c94-d008b94c0ecb.png)

**Comment by TaraF** [comment]
This is fixed - let us if you see this anywhere else as it is not easy to detect on our end. 

Ready for re-test.

**Comment by dhenry-KCI** [comment]
tested on 19793 and looks good.- MW

![image](https://user-images.githubusercontent.com/4129185/69660463-623ed580-104e-11ea-8a04-02a0b00bf737.png)
