### ISSUE TITLE
Planning-to do list report-projects not showing up

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2305]
Ashley routed a review to herself, me, and Jerry and it didnt appear on our "to do list" report on our dashboards.  it was ap 19576

![image](https://user-images.githubusercontent.com/4129185/69181504-361ad600-0add-11ea-8253-09a6219c4066.png)

MW/AR

**Comment by dhenry-KCI** [comment]
Reviewed 19576 with Dan. He confirmed issue and will need to send to development team.

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/69266050-6a9f9800-0b98-11ea-93bc-91e1c14e198c.png)

**Comment by megisys** [comment]
Need to ensure Show Expired in TO DO Lists is on..

**Comment by dhenry-KCI** [comment]
All fixed up with this check box. AREED
![image](https://user-images.githubusercontent.com/4129185/69267152-96238200-0b9a-11ea-86be-bea5c76f534c.png)
