### ISSUE TITLE
Electrical permit 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2307]

**Comment by ABonomo21** [comment]
contractor did not generate on the electrical permit official issuance 
![image](https://user-images.githubusercontent.com/47611580/69182729-990d6c80-0adf-11ea-97b1-240172a4d88f.png)

**Comment by ABonomo21** [comment]
fields are also overlapping...

**Comment by TaraF** [comment]
This is fixed, ready for re-test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69659883-25261380-104d-11ea-9d4c-ceeb72f709b9.png)
