### ISSUE TITLE
Cannot search for a contact 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2309]
i am still not able to search for a licensed contact when the applicant type is licensed contact only when it is set as property owner 
![image](https://user-images.githubusercontent.com/47611580/69183054-34064680-0ae0-11ea-873e-baee6596a1e4.png)

![image](https://user-images.githubusercontent.com/47611580/69183102-4e402480-0ae0-11ea-8368-c438b0b9bf3f.png)
![image](https://user-images.githubusercontent.com/47611580/69183117-58622300-0ae0-11ea-99ce-27c57178656d.png)

![image](https://user-images.githubusercontent.com/47611580/69183131-644de500-0ae0-11ea-98d4-c32aeae082c0.png)

this needs to be corrected - previously addressed as an issue

**Comment by megisys** [comment]
They are not licensed.

![image](https://user-images.githubusercontent.com/47392306/69242994-1254a000-0b70-11ea-9126-f9f4581d21ba.png)

**Comment by ABonomo21** [comment]
Contact Property Browser
Action 
Create Contact 
Contact information + to create contact information
Licenses Tab
+ License for this contact (add MHIC, Home Builder License, Sprinkler etc)
Save grid and approve 
(Example was Test Subject)
Then create contact for the company
Contact Property Browser
Action 
Create Contact 
Contact information + to create contact information
Then under the relationship tab – create the relationship between the company and the license holder or individual 
Relationships+ create contact relationship

Testing Company is the Company of (individual/license holder)
Test Subject is the license holder/employee of Testing Company
Select the also add as a licensed child check box 

Plumbing and Electrical Trade will automatically create these relationships
