### ISSUE TITLE
Electrical Demo-Minor Fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#231]
Residential Electrical Demolition Permit- When Demolition is selected on the detail page the fees should generate as the minimum residential fees($48.00 and $10.00). On Permit# 238647 the non-residential minimum fees generated-MCoffman

![image](https://user-images.githubusercontent.com/47611580/53985831-a8cc5880-40ea-11e9-94ed-42322ee1091d.png)

![image](https://user-images.githubusercontent.com/47611580/53985807-97834c00-40ea-11e9-8e6c-1b9cc7ade63d.png)

**Comment by imazlout** [comment]
This was fixed in #96 and issue was closed. According to Hansen 7 minimum fees only get added for REAPFL. If work type = Remove, then the demo fee gets added (for res and nonres respectively). Plumbing and electrical demo are both set this way in Hansen 7. Are you sure this request is correct?

**Comment by megisys** [comment]
@imazlout  - This is residential and the non res fee is coming up

**Comment by imazlout** [comment]
@megisys I think that was a typo because when you lookup the application 238647 in TEST environment, the occupancy type is NONRES and so the correct fee is showing up. See screenshot:

<img width="960" alt="issue231" src="https://user-images.githubusercontent.com/47784290/54047067-0b355f80-41a4-11e9-9e06-396e7c2fbfe0.png">

**Comment by ABonomo21** [comment]
I retested and it looks like it is corrected. It must have been an error when it was processed-MCoffman

Permit# 238706
![image](https://user-images.githubusercontent.com/47611580/54129562-ebd94500-43e4-11e9-8440-2346320bb9b3.png)
