### ISSUE TITLE
Planning-IPS-problems-new resolution code "waived" appeared

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2310]
Dan,

what does this new waived resolution code mean?  the existing "addressed" option will expire a problem.  I dont want this new one causing confusion with users. @dangrendon

MW

**Comment by megisys** [comment]
Where ??

**Comment by dhenry-KCI** [comment]
DISCUSSED AND REMOVED


mw
