### ISSUE TITLE
Trade License - Plumbing Permit 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2311]
Added a contact with an expired license - went into the trade license # pm00222 and completed the renewal on this license however, the licenses for the contact did not update on the contact record. 
![image](https://user-images.githubusercontent.com/47611580/69185140-281c8380-0ae4-11ea-9360-d3e2c90bb5cb.png)
i had to manually change it - this is going to be a large problem at go live if we have to manually change the date

**Comment by ABonomo21** [comment]
failed testing pm1621

**Comment by megisys** [comment]
TL_AddContactLicenseDetails

**Comment by ABonomo21** [comment]
update worked 
![image](https://user-images.githubusercontent.com/47611580/69360465-96825280-0c58-11ea-9950-30f9eb753c14.png)
