### ISSUE TITLE
Cashiering - Generate Cash Drawer

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2312]
When user selects generate cash drawer the system presents a blank screen.

![image](https://user-images.githubusercontent.com/4129185/69239807-0ca78c00-0b69-11ea-94e7-c0b0e5212a7b.png)

**Comment by calequin** [comment]
fixed.

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/69285545-2673be00-0bbf-11ea-866e-8cfd44dfca60.png)
