### ISSUE TITLE
PLANNING - SUBDIVISION CODE DATA TRANSFER

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2313]
Subdivision Code Data needs to transfer from Hansen 7 to IPS. Did not transfer. AREED
![image](https://user-images.githubusercontent.com/4129185/69249522-ff47cd00-0b7b-11ea-9001-8f4d99b882de.png)
![image](https://user-images.githubusercontent.com/4129185/69249555-0d95e900-0b7c-11ea-8828-b3eca06f7fdc.png)

**Comment by megisys** [comment]
Sent to GDS

**Comment by megisys** [comment]
This will be completed as part of Go Live

**Comment by megisys** [comment]
Added as they were a few months ago to prove that they will come across. Taken from an older back up

**Comment by dhenry-KCI** [comment]
not ready for retest.  Must review at go-live.  Tagging as pre-go-live correction per Dustin.


![image](https://user-images.githubusercontent.com/4129185/69553688-92af4280-0f6e-11ea-9e97-2be6923bbe1b.png)

MW
