### ISSUE TITLE
PLANNING - REPORT ISSUES 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2314]
BUDGET NUMBERS for Daily Receipts - Road Escrow Report are still the old numbers. 
![image](https://user-images.githubusercontent.com/4129185/69270847-ccb0cb00-0ba1-11ea-8316-e434e0aeed01.png)

Total Cost and Dev% is missing on Escrow Transactions History by Tracking Number report
![image](https://user-images.githubusercontent.com/4129185/69271132-4a74d680-0ba2-11ea-98ea-8ca6b801c2ba.png)

The remainder issues regarding blank data and the budget numbers (migration issues) – Tara still has no access to pristine to make these corrections.  AR/MW
@dhenry-KCI @megisys

**Comment by megisys** [comment]
Pristine ?? Changes need to be made in Test

**Comment by megisys** [comment]
I took care of the budget number issue. I reran the crosswalk piece..

**Comment by megisys** [comment]
http://wh-ipsprd/ips_pristine/

**Comment by megisys** [comment]
Run the report here.. But the report wont exist of course.

**Comment by megisys** [comment]
Did a catch up Data Migration

**Comment by dhenry-KCI** [comment]
Tested Daily Receipts Road Escrow Report. Budget numbers still incorrect.
![image](https://user-images.githubusercontent.com/4129185/69347632-d5a5a900-0c42-11ea-9c13-0d860e74d996.png)
Total cost and Dev% missing from Escrow Transactions History Report
![image](https://user-images.githubusercontent.com/4129185/69349313-890f9d00-0c45-11ea-82f0-6d548a8e7432.png)

**Comment by megisys** [comment]
OK.. I see the issue here. Bond is being used as Budget Number.. But it isn't a Budget Record.

These will need to be updated manually by the county here

**Comment by megisys** [comment]
This is how it is in Hansen 7

**Comment by dhenry-KCI** [comment]
Complete. CLosing
