### ISSUE TITLE
Blanket Report 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2318]
blanket permit MH250622
![image](https://user-images.githubusercontent.com/47611580/69366998-6beac680-0c65-11ea-91a5-c70e138ece61.png)

-please make header consistant
-there are question marks on the report 

Ashlye wasn't able to pull up these details (Emily was )
![image](https://user-images.githubusercontent.com/47611580/69367135-afddcb80-0c65-11ea-80d5-7944939646d7.png)
![image](https://user-images.githubusercontent.com/47611580/69367170-c1bf6e80-0c65-11ea-8d82-7ff0a53794a9.png)

**Comment by TaraF** [comment]
Looks like some DB changes happened 11/5/19.  We have pivoted and updated - to try to include both the old for old APs and new for new APs.  

Ready for re-test.

**Comment by ABonomo21** [comment]
looks good checked under mh250623
