### ISSUE TITLE
Electrical Demo-Inspections

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#232]
Residential Electrical Demo- Only an Electrical Final inspection should generate-MCoffman

Permit#238647 

![image](https://user-images.githubusercontent.com/47611580/53986096-43c53280-40eb-11e9-93f3-10a98665248c.png)

**Comment by imazlout** [comment]
Ready for test.
Demo is a new code that was added recently and so it wasn't in the formulas. It has been added now.

**Comment by ABonomo21** [comment]
Electrical A/P# 238706-Corrected-MCoffman
\![image](https://user-images.githubusercontent.com/47611580/54129994-e7f9f280-43e5-11e9-87c3-ebc4a313f887.png)
