### ISSUE TITLE
Bond Class Cleanup 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2321]
Can we do a clean up of the Bond Class type's available?
![image](https://user-images.githubusercontent.com/47611580/69369750-9b500200-0c6a-11ea-9f92-bc5a99a25b0e.png)

**Comment by megisys** [comment]
Just go into Code Definition Management - This is an everyday type task]
![image](https://user-images.githubusercontent.com/47392306/69429102-ce44d500-0d00-11ea-8474-55e4bedc7d17.png)

**Comment by megisys** [comment]
Expire. Dont delete

**Comment by dhenry-KCI** [comment]
Closing ticket. Adding to post go-live correction items
