### ISSUE TITLE
PLANNING - SCHOOL CONSTRUCTION FEES - DESTINATION BUDGET missing

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2322]
MUST HAVE destination budget for school construction fees. There are 9 possible options in school construction fees. AREED

![image](https://user-images.githubusercontent.com/4129185/69370931-e2d78d80-0c6c-11ea-8a11-6aa5a3148cce.png)
![image](https://user-images.githubusercontent.com/4129185/69371045-12869580-0c6d-11ea-8f98-25bf84bafe25.png)

**Comment by dhenry-KCI** [comment]
@pooldaddy - additional fee updates.

**Comment by pooldaddy** [comment]
For the phase 4 schl. const where destbgt # missing set to 43.98.480.999 42101 0000

**Comment by dhenry-KCI** [comment]
Verified corrected PL252285
![image](https://user-images.githubusercontent.com/4129185/70246019-06a6d300-1745-11ea-9282-3ff7f1b32ca3.png)
