### ISSUE TITLE
Pending Permit/ Project Reviews- On Demand Report 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2323]
If a permit application is void and a review is assigned to a reviewer- the review should not generate on the pending permit/ project report
![image](https://user-images.githubusercontent.com/47611580/69372026-ebc95e80-0c6e-11ea-901a-65d6e62d2bfc.png)

![image](https://user-images.githubusercontent.com/47611580/69372103-15828580-0c6f-11ea-8f38-ed19e12f8722.png)
![image](https://user-images.githubusercontent.com/47611580/69372158-2b904600-0c6f-11ea-8d38-495897c8c091.png)

**Comment by megisys** [comment]
This Application wasn't voided correctly. A Void Log should have been added and it would close out reviews and they will not appear on reports or dashboards

**Comment by ABonomo21** [comment]
will need to check post go live to make sure that the applications that were made void in H7 are migrated correctly - spoke with dan 11.26.19
