### ISSUE TITLE
Liquor Board - application cutting off to the left

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#2325]
The whole application is cutting off to the left.  Please see screen capture below:

![image](https://user-images.githubusercontent.com/4104464/69433200-2c75b600-0d09-11ea-9fc5-1f09056b18ee.png)

**Comment by megisys** [comment]
What is your zoom level here ?

**Comment by megisys** [comment]
Hi Tara. There is an EDIT Page button you have when you are an Admin. Can you be Extra careful to not hit this button. This causes the pages to jump. This is the same issue as the generate cash drawer issue. Not blaming you. just letting you know that this is how this happens
