### ISSUE TITLE
R4C-list of issue or complaint is missing-Planning and Permits

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2326]
list of issue or complaint is missing

![image](https://user-images.githubusercontent.com/4129185/69439050-318c3280-0d14-11ea-8458-cd20b10ff003.png)

MW

**Comment by megisys** [comment]
We were asked to turn them off

**Comment by dhenry-KCI** [comment]
still not there.

![image](https://user-images.githubusercontent.com/4129185/69552068-cf2d6f00-0f6b-11ea-8efa-285adceb08fd.png)

MW

**Comment by dhenry-KCI** [comment]
it only appears when logged into my account.  We werent going to require citizens to have an account to log a complaint.

![image](https://user-images.githubusercontent.com/4129185/69554463-d0f93180-0f6f-11ea-8595-e500481a11a0.png)


MW

**Comment by megisys** [comment]
This is right. AShley Bonomo asked for them to be turned off

**Comment by dhenry-KCI** [comment]
as discussed need a fix.

**Comment by megisys** [comment]
New Mention Offered in Email. Please Test

**Comment by ABonomo21** [comment]
reviewed with mike ash and dan - goo work around for golive - 
![image](https://user-images.githubusercontent.com/47611580/69653175-c8246080-1040-11ea-88e0-9fe8ebcb7b22.png)

**Comment by ABonomo21** [comment]
follow up after go live to see if we can improve
