### ISSUE TITLE
Liquor Board - missing endorsements 

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#2329]
@calequin  - per our discussion, these are the endorsements that are missing that need to be added:

- Entertainment (no fee associated)
- Patio (no fee associated)
-  Growler Permit Wine Beer/Wine
-  Growler Permit Wine Only

![image](https://user-images.githubusercontent.com/4104464/69442380-80d56180-0d1a-11ea-8a4e-edef2700360b.png)

**Comment by calequin** [comment]
Added endorsements to IPS11.

**Comment by ABonomo21** [comment]
dustin emailed jeff wisner to update
