### ISSUE TITLE
Building - Minor Logging - Logging Conditions - Spelling Errors

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#233]
Logging is spelled incorrectly under logging conditions

It is spelled 'loggin' but should be spelled 'logging'
![image](https://user-images.githubusercontent.com/4129185/53986267-a9192380-40eb-11e9-8312-cf3286240d1d.png)

**Comment by megisys** [comment]
We are from the south.. Loggin !

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
spelling error corrected tiffany martin 3/15/19
