### ISSUE TITLE
Planning-look up application-by employee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2330]
either we are doing it incorrectly or its not working.  Trying to look up by employee but not getting any results

![image](https://user-images.githubusercontent.com/4129185/69443622-cdba3780-0d1c-11ea-9cc7-aabd357e0937.png)

MW

**Comment by megisys** [comment]
That is right. You are doing it wrong. WE dont list employees on Applications 

If you search by AREED you will now get one. This is due to being listed on the employee tab

**Comment by dhenry-KCI** [comment]
so how does one search for reviews by employee?   MW

**Comment by megisys** [comment]
Under Lookup Reviews

![image](https://user-images.githubusercontent.com/47392306/69634068-7e774e00-101f-11ea-861c-e5146c42822d.png)

**Comment by dhenry-KCI** [comment]
ok, thanks
