### ISSUE TITLE
R4C - PWCONSTRUC ERROR

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2331]
R4C not populating construction details or contact details sections - unable to submit - ERROR
@calequin @dhenry-KCI @megisys 
AREED
![image](https://user-images.githubusercontent.com/4129185/69454586-83dd4b80-0d34-11ea-9b8c-3cd9ff261253.png)

![image](https://user-images.githubusercontent.com/4129185/69454546-72943f00-0d34-11ea-92f0-85042ec18112.png)

**Comment by calequin** [comment]
fixed. environment was out of sync

**Comment by dhenry-KCI** [comment]
Verified corrected AREED
