### ISSUE TITLE
Fire Permit - Project dox 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2336]
unable to batch stamp or open anything in pdox i get this error 
![image](https://user-images.githubusercontent.com/47611580/69459120-0965f900-0d3f-11ea-8e1d-b38475ee0f09.png)

**Comment by ABonomo21** [comment]
i was using the laptop in the basement training room - it was working yesterday and will not work today.

**Comment by dhenry-KCI** [comment]
This is an issue with the laptop. Requested IIT to install. Closing ticket.
