### ISSUE TITLE
Batch Stamp - PDOX

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2337]
![image](https://user-images.githubusercontent.com/47611580/69459167-2995b800-0d3f-11ea-89f7-f70796d0a4d1.png)
![image](https://user-images.githubusercontent.com/47611580/69459193-37e3d400-0d3f-11ea-9e26-34fceec499d6.png)

what is OLD  and PROMPT in my building batch stamps

**Comment by dhenry-KCI** [comment]
closing as it relates to #2192
