### ISSUE TITLE
Blanket- 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2338]
all of the items under the blanket details page, are not avaliable for selection - is this a migration issue?
total in IPS 44
![image](https://user-images.githubusercontent.com/47611580/69459941-e50b1c00-0d40-11ea-9d19-fe20f73dbd37.png)

in H7 there are 131
![image](https://user-images.githubusercontent.com/47611580/69460050-26033080-0d41-11ea-9f0d-6531a7d77e47.png)

**Comment by megisys** [comment]
Need a new code for ones in Hansen 7 which are over 10 characters long.. PLease Provide ASAP

**Comment by dhenry-KCI** [comment]
see attached

[Blanket_Codes.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3894905/Blanket_Codes.xlsx)

**Comment by ABonomo21** [comment]
need to check this with the final data migration
