### ISSUE TITLE
Fro Permit 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2339]
fro permit 251638 made us supervisor override because there was a condition that a planning ap had to be associated and there was a fro planning application attached 
![image](https://user-images.githubusercontent.com/47611580/69460130-564acf00-0d41-11ea-88e0-e79ff04a5e33.png)

![image](https://user-images.githubusercontent.com/47611580/69460152-65ca1800-0d41-11ea-80b1-df835dee6dbb.png)

**Comment by megisys** [comment]
Believe this to be fixed. Please retest

**Comment by ABonomo21** [comment]
looks like it is fixed for permit 251674
