### ISSUE TITLE
Building - Minor Logging - Logging Conditions

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#234]
The logging conditions has a declaration that states if any boxes were checked below that the plan should be prepared by a licensed forester - this means a Major Logging permit is required.

Is this something that we should be checking at completeness check or the system will not allow the applicant to check any and progress if applying for a minor logging? This currently did not stop me when I chose a box as yes.

AP # 238649

logged by tiffany martin 3/7/19

![image](https://user-images.githubusercontent.com/4129185/53986595-9fdc8680-40ec-11e9-9e53-145e20e55599.png)

**Comment by megisys** [comment]
Applicant should input to the best of their abilities.. Completeness Check will advise if it should be a major.

Dan

**Comment by dhenry-KCI** [comment]
confirmed - completed during completeness check 3/15/19 tiffany martin
