### ISSUE TITLE
Planning-IPS-PWConst- review cycle issues w/ DOL on in life ap

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2340]
AP# 19536

DOLS populated 2nd review on 3rd cycle.

![image](https://user-images.githubusercontent.com/4129185/69548296-1401d780-0f65-11ea-9fe8-e32bc7781877.png)
![image](https://user-images.githubusercontent.com/4129185/69548383-40b5ef00-0f65-11ea-9595-e2c76759d826.png)
![image](https://user-images.githubusercontent.com/4129185/69548446-59260980-0f65-11ea-9aca-18466dcc7512.png)

MW for AR

**Comment by megisys** [comment]
Cause it is the second DOLS review. The count isn't full cycles. It is the count of that type of review.

**Comment by dhenry-KCI** [comment]
DOLS did not populate on 2nd cycle like it should have (it was resubmit on 1st cycle).  Then it magically populated when the 3rd cycle began.

MW

**Comment by megisys** [comment]
See this now.. My Apologises. I tried on others but I need to change the work type first. Was this done in a timely manner for this one..

**Comment by dhenry-KCI** [comment]
fixed per 19586
MW
