### ISSUE TITLE
Planning-IPS-PWConst-SHA review cycle issue

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2341]
A/P 19536 
SHA didn’t populate on the review cycle. When added manually, it inserted as cycle 1. 

![image](https://user-images.githubusercontent.com/4129185/69548676-c2a61800-0f65-11ea-986c-4d79659bf870.png)

MW for AR

**Comment by megisys** [comment]
Can I ask what the impact of this is ? These will eventually drop off ?

**Comment by megisys** [comment]
Data Flag Issue.. Please Retest this

**Comment by dhenry-KCI** [comment]
added SHA and DOLS manually on 2nd cycle (first IPS cycle).  On 3rd cycle DOLS came through but SHA is still not auto populating

![image](https://user-images.githubusercontent.com/4129185/69647743-09644280-1038-11ea-8a94-9ae5146be59b.png)


MW

**Comment by dhenry-KCI** [comment]
see also 19586-mw

**Comment by megisys** [comment]
SHA is a manual add. But I added a formula that said if this type was added previously with a result of resubmit please readd. If this works we can apply this to all manual add reviews across all of planning.


Thoughts ?

PLease Test

**Comment by dhenry-KCI** [comment]
didn't work on 19682
![image](https://user-images.githubusercontent.com/4129185/69655362-5e0dba80-1044-11ea-994f-1dccc35d9684.png)


MW

**Comment by megisys** [comment]
hmmmm

**Comment by megisys** [comment]
Please TEST a PWConstruc for SHA REview

**Comment by dhenry-KCI** [comment]
see 19497.  SHA corrected came up as cycle two but four other agencies that were "resubmit on first cycle didn't populate on 2nd cycle

MW

**Comment by dhenry-KCI** [comment]
PWCONSTRUC has been corrected.  Will monitor level of work after go live with remaining a/p types. AREED
