### ISSUE TITLE
Planning-DUSWM reviewer-JHagy vs JHagy2

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#2345]
there is some confusion with JHagy's record.  Plans auto route to JHagy but his dashboard report only has items routed to JHagy2.  Need to pick one.

MW for AR

**Comment by megisys** [comment]
We only have a JHagy2 in IPS. SO this is the one needed. Some one will need to update Pdox to have this the same.

Thanks

Dan

**Comment by dhenry-KCI** [comment]
Pdox has James Hagy's email as jhagy2 and his hansenID as jhagy 2. Talking to AShley earlier the problem seems to be how my infor routes his plans.

![image](https://user-images.githubusercontent.com/4129185/69594798-7a214580-0fcb-11ea-8a0d-7550b78f3d7d.png)

![image](https://user-images.githubusercontent.com/4129185/69594812-83121700-0fcb-11ea-9f12-7c9d5127a283.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/69647263-26e4dc80-1037-11ea-9b75-75e8a4d6da73.png)

**Comment by megisys** [comment]
Make sure the Reviews are New and Not resulted..

**Comment by dhenry-KCI** [comment]
fixed per PW252327

MW
