### ISSUE TITLE
Trade Licenses- Duplicated Relationships 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2346]
A duplicate relationship for a company is created when you approve the renewal review 

![image](https://user-images.githubusercontent.com/47611580/69647197-0d439500-1037-11ea-9bd9-39152bb26186.png)

License # EM250953

**Comment by megisys** [comment]
Addressed this Issue

**Comment by ABonomo21** [comment]
will confirm this is correct after data migration worked now
