### ISSUE TITLE
Trade Licenses - Grace Exp Date

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2347]
grace expiration date is generating on all old licenses as the the same as the expiration date 

this will be a problem for plumbing after go live because plumbing will still be in the grace period of 90 days after expiration 

![image](https://user-images.githubusercontent.com/47611580/69647597-c6a26a80-1037-11ea-906f-fc22c48951af.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69647637-d7eb7700-1037-11ea-9922-515c055ab528.png)

**Comment by ABonomo21** [comment]
when checking the status button on a migrated license that was in "pre-renew" it took me to awaiting renewal details gave the wrong fee and was past the grace expiration dated
![image](https://user-images.githubusercontent.com/47611580/69647718-fcdfea00-1037-11ea-9aa0-9e5898d2ac9a.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/69649034-5fd28080-103a-11ea-9a7f-2d65bafd56d0.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69649085-7aa4f500-103a-11ea-9238-d0d0f255002e.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/69649129-8e505b80-103a-11ea-8489-758958fb1ff4.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/69650101-15ea9a00-103c-11ea-843c-43e58cf0d9f8.png)

**Comment by ABonomo21** [comment]
will confirm this is accurate in the data migration post go live.
