### ISSUE TITLE
Contact Record- Expiration Date 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2348]
![image](https://user-images.githubusercontent.com/47611580/69647756-0d906000-1038-11ea-9fed-e2dcb03a0c6b.png)

**Comment by megisys** [comment]
Will raise a defect with Product. Doesn't cause any workflow issues at this point

**Comment by ABonomo21** [comment]
will check with data migration and improve after go live

**Comment by calequin** [comment]
knwon issue. being fixed by dev in 1912 release
