### ISSUE TITLE
Demo Residential Building-Zoning Fee and Zoning Review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#235]
Demo-Residential Public Water and Sewer- No Zoning Fee or Zoning Review Generated-MCoffman
![image](https://user-images.githubusercontent.com/47611580/53982292-89313200-40e2-11e9-9f16-17e93a6ba389.png)

![image](https://user-images.githubusercontent.com/47611580/53982329-a1a14c80-40e2-11e9-8667-dade24a487dc.png)

The Check Boxes for if Plumbing and Electrical work is being completed should be available on the details page; however it should not red line you to have separate Electrical and Plumbing permits
![image](https://user-images.githubusercontent.com/47611580/53983347-fe9e0200-40e4-11e9-96d0-3faac5668174.png)

**Comment by imazlout** [comment]
Duplicate of #232. Please see comments in that ticket

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55731644-87f86b00-59e8-11e9-95b8-fcd701b58dca.png)

![image](https://user-images.githubusercontent.com/47611580/55731709-a5c5d000-59e8-11e9-9b63-989b17052872.png)
