### ISSUE TITLE
Issued Building Permit On Demand Report

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2351]
Tara please switch the start and end date on the building permit issued and applied for on demand report 
![image](https://user-images.githubusercontent.com/47611580/69648204-ce164380-1038-11ea-8100-a2c1face33f2.png)

![image](https://user-images.githubusercontent.com/47611580/69648219-d7071500-1038-11ea-8a24-46b3e6591767.png)

**Comment by TaraF** [comment]
This is updated. Ready for re-test.
