### ISSUE TITLE
Trade License- Renewal Review 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#2352]
We need a resubmit approval at renewal review for trade licenses - right now only approved is an option.... applicant could be missing details 

![image](https://user-images.githubusercontent.com/47611580/69648911-344f9600-103a-11ea-8c17-1e62d798b0ab.png)

![image](https://user-images.githubusercontent.com/47611580/69648896-2e59b500-103a-11ea-8419-7205f623b7c8.png)

**Comment by megisys** [comment]
This was not the intention. It was only to have the County check the person was not changing companies and being a master of two companies.. This is a County reviewing their side. Not for the applicant

**Comment by ABonomo21** [comment]
Will check after go live - closing for now
