### ISSUE TITLE
Bond reports not rendering in IPS

### ISSUE THREAD

**Issue by TaraF** [kcigeospatial/Fred_Co_Land-Management#2354]
Parameters are set - need to pass in APNO and BONDNO (which is Bond.BondKey) per County stakeholder request.  These parameters are working fine in SSRS (see https://ssrs16.nt1.local/Reports/report/Planning%20and%20Permitting/Permits%20and%20Inspections/IPS_Reports/rpt_Authorization_Amend_Letter_of_Credit )

Cannot get the report to render in IPS - it just shows blank.  I have tried deleting and recreating and adding brand new ones, still the same result.  

For BONDNO - using Bond.BondKey ( I have tried BondDetail.BondKey - but it is producing an error in IPS).

![image](https://user-images.githubusercontent.com/4104464/69673656-c9698380-1068-11ea-911e-4edcdc03dfa7.png)

Need resolution to move forward with this: #2284 

**Please also note, when these reports were generating on just APNO months ago it was working in IPS.

**Comment by megisys** [comment]
@TaraF  you cant use the parameter of APNo from here

**Comment by TaraF** [comment]
Will confirm with the County they are OK with inputting the APNO parameter.
