### ISSUE TITLE
Planning-FRO-

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#238]
FullPFCP- asking for "guarantee details required" even though the guarantee required check box is not checked in the project details page.  Across all FRO types, the requirement to enter  "guarantee details required" should only populate if the guarantee required check box. 

![image](https://user-images.githubusercontent.com/4129185/54034422-ca7a1e00-4184-11e9-9c66-7a98231f66fb.png)

![image](https://user-images.githubusercontent.com/4129185/54034399-ba623e80-4184-11e9-9bd8-3db8b8dbbe32.png)

![image](https://user-images.githubusercontent.com/4129185/54034560-2a70c480-4185-11e9-9a8f-70b24d1d813c.png)

**Comment by dhenry-KCI** [comment]
P.S.  the only way to clear   "guarantee details required" is to check the guarantee required box.  This needs to be fixed on all FRO AP types.

**Comment by megisys** [comment]
@dhenry-KCI - If Guareentee is required is Checked.. then what am I checking for has been done ? A condition is approved ? A review is complete.. No idea here

**Comment by dhenry-KCI** [comment]
If guarantee IS checked then the system should make sure the declared and actual valuation in the job details tab is filled in.  However, I just went through this again using a final FRO application (F237589) and with the grantee required box checked and the declared and actual valuation filled in I cant get the "guarantee details required" to go away.

![image](https://user-images.githubusercontent.com/4129185/54050168-8995ff80-41ac-11e9-849f-7f3772bec7c6.png)

![image](https://user-images.githubusercontent.com/4129185/54050193-9b77a280-41ac-11e9-9403-5bfcae6363d4.png)

![image](https://user-images.githubusercontent.com/4129185/54050241-ae8a7280-41ac-11e9-9379-edbd6d8f3b90.png)


MW

**Comment by dhenry-KCI** [comment]
Fixed
