### ISSUE TITLE
Planning-FRO- exemption-email to applicant requesting paperwork

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#239]
on FRO exemptions, we need to remove the auto-generated email notice asking the applicant to submit paperwork after hearing.  There is no additional paperwork required at that stage of the process.

MW on behalf of Graham 3/8/19

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
FIXED (re-tested under F237830)
