### ISSUE TITLE
Use - Landuse - # of persons using Sanitary

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#24]
On the details page the field , Number of Persons Using Sanitary is not always required. Should only be required where Sanitation Type = Portable

Steps to Recreate:
1. Create new Land Use Application
2. click details tab - populate Sanitation TYpe = INBLG (In Building) - # of persons using sanitary still required.

![image](https://user-images.githubusercontent.com/4129185/52590318-fe288900-2e0e-11e9-9154-2eafe708e84c.png)

**Comment by calequin** [comment]
Unfortunately, detail pages do not allow us to designate required fields according to the selection of a previous answer. I have deselected # of persons using sanitary to = Not Required.

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54210709-61f9ac80-44b6-11e9-9430-8f1f527838f8.png)
