### ISSUE TITLE
Demo Residential Building-Reviews

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#240]
On Demos for a Residential Property on well and septic -MCoffman

This was a Partial Demo for RESTWN, a DOLS review is generating and it should be DUSWM
Permit# 238679
![image](https://user-images.githubusercontent.com/47611580/54041519-ecc86780-4195-11e9-9168-044648ac08c5.png)

On Permit# 238682, a Demo for a Residential Property on Well and Septic, but this is a RESSFD and a Demo of an Entire Structure; the DUSWM Review did not generate
![image](https://user-images.githubusercontent.com/47611580/54042000-20f05800-4197-11e9-9e90-334e002dcf97.png)

**Comment by megisys** [comment]
PLease ReTest - Did you change the worktype after you entered review ??

**Comment by ABonomo21** [comment]
Testing failure-#238787-ResTownhouse-partial demo-DOLS review still generated when it shouldn't. DUSWMF is not required according to airtable, need to confirm with @ABonomo21 -AW

#238788-ResSFD-entire demo-Correct reviews generated according to airtable. need to confirm with Ashlye regarding DUSWMF review.

![image](https://user-images.githubusercontent.com/47611580/54286414-32ac7380-457a-11e9-83cd-10ae38dd1aeb.png)

![image](https://user-images.githubusercontent.com/47611580/54287259-b2870d80-457b-11e9-9af6-3bc8da737ab1.png)

**Comment by ABonomo21** [comment]
Testing failure-#238798-ResTownhouse-Partial demo-DOLS review generated when it should be DUSWMF review. 

Per Abonomo-DUSWMF review is required when additional plumbing is involved and/or the property is on public water/sewer.
![image](https://user-images.githubusercontent.com/47611580/54290981-3e9c3380-4582-11e9-8baa-edcf058a3c8f.png)
![image](https://user-images.githubusercontent.com/47611580/54291004-49ef5f00-4582-11e9-9eec-d50218cca1de.png)

**Comment by ABonomo21** [comment]
#238800-ResSFD -entire demo-DUSWMF review did not generate and this permit has additional plumbing.

![image](https://user-images.githubusercontent.com/47611580/54291352-ceda7880-4582-11e9-9981-c5e6eea520e7.png)
![image](https://user-images.githubusercontent.com/47611580/54291386-db5ed100-4582-11e9-8c9e-739f7cade0a8.png)

**Comment by imazlout** [comment]
Ready for test.
DOLS review now generates if worktype does not equal "ENTIRE" and Occupancy type is Non-res (as per Hansen 7).
DUSWM review now adds if water = public or sewer = public or Additional Plumbing is checked on detail page

**Comment by ABonomo21** [comment]
Confirmed fixed- DUSWMF review generated-AW

![image](https://user-images.githubusercontent.com/47611580/54371027-175f6800-464f-11e9-9da7-5d997757de60.png)

![image](https://user-images.githubusercontent.com/47611580/54371039-1deddf80-464f-11e9-9f95-5d1ad09a2e02.png)
