### ISSUE TITLE
Planning- Verification Letters

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#241]
Would like the Review Result description for Approved to read Approved/Completed 

![image](https://user-images.githubusercontent.com/47611580/54041625-3022d600-4196-11e9-9e50-7450c8776c95.png)

![image](https://user-images.githubusercontent.com/47611580/54041630-33b65d00-4196-11e9-8cbf-bd7826ac5f73.png)

**Comment by mmbanong** [comment]
Changing the description for Approved review result will apply not only to Verify but to all review results that have Approved in the planning module. Is this what we want?

**Comment by ABonomo21** [comment]
We do not want to change this for all planning. Please leave it the way it is. Thanks!
