### ISSUE TITLE
Electrical-Trailer

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#242]
Too Many Inspections generated. According to Airtable only a Temp Service and Underground Inspection should generate. and then the final will take place later.-AW
![image](https://user-images.githubusercontent.com/47611580/54049910-e2b16380-41ab-11e9-9af9-6dd3e0a726b6.png)

**Comment by imazlout** [comment]
@ABonomo21 how do I know the electrical permit is for a trailer? Is it if occupancy type = Nonreseducational?

**Comment by ABonomo21** [comment]
Based on the related building permit which is an application type of trailer.

**Comment by goggansd** [comment]
This logic won't work without a hierarchy as to which parent application type supersedes which other one(s). The example provided has BOTH a TRAILER parent permit AND a SIGNS parent permit. Please advise...

**Comment by megisys** [comment]
Just focus on if there is a Parent of Trailer and addoncondition = false for the inspections mentioned..

**Comment by megisys** [comment]
Ready for Retest.. Trailer as Parent..

**Comment by ABonomo21** [comment]
Incorrect inspections still generated; Should be a Temp Service, Underground, and Final Inspections-MCoffman

Permit# 240164 
![image](https://user-images.githubusercontent.com/47611580/55487586-61a78980-55fc-11e9-88b2-6be573eb8bb1.png)

**Comment by ABonomo21** [comment]
see #553 same issues

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55730007-3f8b7e00-59e5-11e9-89f6-a50d25a4219e.png)
