### ISSUE TITLE
General-Tank Permit Error Message

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#243]
Residential Tank Permit; Resulted the Reviews as "Passed" and this error message popped up-MCoffman
Permit# 238686
![image](https://user-images.githubusercontent.com/47611580/54051584-27d79480-41b0-11e9-8d59-06e5b5984985.png)

**Comment by megisys** [comment]
Ready to test

**Comment by ABonomo21** [comment]
Confirmed fixed-was able to complete all steps of the permit and close it out.-AW
![image](https://user-images.githubusercontent.com/47611580/54209622-7a68c780-44b4-11e9-927f-6a0fd50e937f.png)
