### ISSUE TITLE
Error Message when saving review result

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#244]
I received this error message when I was trying to save the result for a completeness check on trailer permit #238688.-AW

![image](https://user-images.githubusercontent.com/47611580/54052265-f65fc880-41b1-11e9-876e-b247e550f310.png)

**Comment by ABonomo21** [comment]
Tried a new permit of the same type and when I went to result the review just like before I got another error message. This error message is different even thought the permit/action was the same. -AW
![image](https://user-images.githubusercontent.com/47611580/54052767-3d01f280-41b3-11e9-9805-a1420c263a71.png)

**Comment by megisys** [comment]
resolved

**Comment by ABonomo21** [comment]
Confirmed Fixed-was able to complete the review for the completeness check.-AW'
![image](https://user-images.githubusercontent.com/47611580/54131460-c4847700-43e8-11e9-8e29-7256424ae8ad.png)
