### ISSUE TITLE
Use- Home Occupation- Milestone  (waiting for 547 fix)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#245]
After the inspection was passed for Home Occupation # H235803 the status went to active, with an alert to add a void log to close out?? - This is not needed.

![image](https://user-images.githubusercontent.com/47611580/54052217-da5c2700-41b1-11e9-9690-ef5671f5c039.png)

The milestone should have gone to "Complete" and the final inspection date should have been recorded on the front tab

![image](https://user-images.githubusercontent.com/47611580/54052358-30c96580-41b2-11e9-98bc-500e2dbf1224.png)

**Comment by calequin** [comment]
Once the home occupancy is approved and active it stays in the active milestone until a log by the county is added. If we change it to go to completed the permit gets closed therefore placing it as inactive. How would the county keep track of active home occupancy permits?

**Comment by megisys** [comment]
This is right.. Training Issue.. Home Occ are Active until advised otherwise..

**Comment by ABonomo21** [comment]
Dustin - I need to follow up with this one with Tolson.

**Comment by ABonomo21** [comment]
Permit should go to a finalized milestone once the inspections pass.

**Comment by megisys** [comment]
I changed this..

**Comment by ABonomo21** [comment]
Trying to test this issue, but it can not be tested correctly until issue #547 is fixed.-AW

**Comment by ABonomo21** [comment]
confirmed fixed-aw
![3](https://user-images.githubusercontent.com/47611580/55486078-aed62c00-55f9-11e9-8136-22a0aae9ee25.PNG)
