### ISSUE TITLE
Building - Minor Logging - General Error Message

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#246]
Get this error message when I was logging an event log to bypass case. This is happening in a minor logging permit.

AP # 238689

logged by tiffany martin 3/8/19

![image](https://user-images.githubusercontent.com/4129185/54052637-f57b6680-41b2-11e9-837e-428f4ce4aa80.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
corrected 3/15/19 tiffany martin
