### ISSUE TITLE
Use- Home Occupation- Applicant Actions

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#247]
The applicant actions tab for Home Occupation has a code called " Release" If applicable -Bond Request"

![image](https://user-images.githubusercontent.com/47611580/54052615-e399c380-41b2-11e9-9717-018ff9ae66bb.png)

This action would never be used for a home occupation. Are these applicant action fields based per module? 

 H235803

**Comment by megisys** [comment]
@based per Module.. They are not per AP Type - Can Change Desc - If applicabel

**Comment by ABonomo21** [comment]
Understood, no need to change description. I would like to make sure staff understands this process, keeping it marked as training.
