### ISSUE TITLE
Planning- BOA- Review Results

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#249]
Review Results in completeness check for BOA should not include Junk- It should be Not Applicable -a/p # 237580

![image](https://user-images.githubusercontent.com/47611580/54052960-c3b6cf80-41b3-11e9-82ec-4fb7620726ff.png)

**Comment by megisys** [comment]
NA = Review Not Needed.
Junk Means the application is completely in Error. Awaiting new Vocabulary option for this event.. Junk is only used on Completeness Check Reviews

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58962793-ea1be500-8779-11e9-8c77-b680cf234d22.png)

fixed - AP # 244575
