### ISSUE TITLE
Use - Landuse - Health Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#25]
System should only generate a Health Review (and fee) when the user selects Sanitation type = Portable or when the user clicks "food service" on the details page. 

Steps to recreate:
1. Create new Landuse permit
2. Populate Sanitation = INBLG
3. leave Food service Unchecked
4. Health review will generate.
Logged by Megan Coffman on 02/07/2019

![image](https://user-images.githubusercontent.com/4129185/52590816-4dbb8480-2e10-11e9-8a1c-07e513c6a20a.png)

**Comment by calequin** [comment]
Currently if address is on well and septic the Health Review populates. If we change to in blg and the address is on well and septic a review will still populate. Is this correct?

**Comment by dhenry-KCI** [comment]
for Use if @calequin If Sanitation = Portable AND the address is on well and septic then Health Review should populate.

**Comment by megisys** [comment]
This is not Right.. Health Department wants to see all when on Well and Septic..   I am positive to this,
@dhenry-KCI.  It is all about capacity of the Septic System.

**Comment by ABonomo21** [comment]
We are not sending all of these to the health department. We only send charge the $50.00 health review fee and generate a  health department review if there is a "temporary structure" being used or if sanitation type is = to portable. 

We generate a health department "food service" review but not a fee if food services is marked yes.

**Comment by megisys** [comment]
Changed as Requested..

**Comment by ABonomo21** [comment]
Not fixed-This land use permit does not have a temporary structure and the restrooms are in building so the health review fee should not have generated -AW

![image](https://user-images.githubusercontent.com/47611580/55182381-ec533900-5163-11e9-8505-963b46c394d1.png)

![image](https://user-images.githubusercontent.com/47611580/55182418-00973600-5164-11e9-8ccb-d7c99471e853.png)

**Comment by ABonomo21** [comment]
the health review generated as well. the review and the fee should not have generated-aw
![image](https://user-images.githubusercontent.com/47611580/55182649-81eec880-5164-11e9-80a3-da09e0d470cb.png)

**Comment by megisys** [comment]
PLease Retest..

**Comment by ABonomo21** [comment]
corrected

**Comment by ABonomo21** [comment]
Re-opening due to Health Reviews not generating now in IPS. -aw
#L244651- the sanitation type is Portable so the Environmental Heath Review should have generated. the fee generated but the review did not.
![image](https://user-images.githubusercontent.com/47611580/63947042-38244a00-ca44-11e9-831b-172589a84f70.png)
![image](https://user-images.githubusercontent.com/47611580/63947059-41151b80-ca44-11e9-9ace-d53352f517fe.png)
