### ISSUE TITLE
Building - Major Logging - General Error Message

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#251]
This error message keeps popping up. This happened at a different time with a Major Logging Permit. This time, I was trying to complete the completeness check review.

AP # 238693

logged by tiffany martin 3/8/19

![image](https://user-images.githubusercontent.com/4129185/54053236-a20a1800-41b4-11e9-8455-8a020dc63258.png)

**Comment by dhenry-KCI** [comment]
error appears similar to #244

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
corrected - tiffany martin 3/15/19
