### ISSUE TITLE
Planning- BOA- Agency Review Results

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#252]
The review results for BOA are populating incorrectly. a/p # # 237580

![image](https://user-images.githubusercontent.com/47611580/54053193-830b8600-41b4-11e9-8d8d-f485e561bffd.png)

I am not sure if something was changed with this module that resulting in all of these review options being populated. These were not populating when previously tested. 

Did a conversation happen with Mike or Ashley regarding the review result codes that differed from previous discussions?

**Comment by megisys** [comment]
Ready to Test

**Comment by dhenry-KCI** [comment]
fixed 237755 MW
