### ISSUE TITLE
Building - SWMESD - Duplicate Inspections

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#254]
The system generated the same two inspections after both initial inspections had been passed.

AP # 238695

logged by tiffany martin 3/8/19

![image](https://user-images.githubusercontent.com/4129185/54053888-b18a6080-41b6-11e9-9081-c085d32bc03d.png)

**Comment by megisys** [comment]
PLease REtest.. Something Wacky here

**Comment by dhenry-KCI** [comment]
corrected tm 4/16/19
