### ISSUE TITLE
Tank Non-Residential Building-Life Safety Review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#256]
Non-Residential Tank- Life Safety Review did not generate-MCoffman

Property is in a Town Permit# 238698
![image](https://user-images.githubusercontent.com/47611580/54054338-ec40c880-41b7-11e9-82be-6e443189e506.png)

**Comment by megisys** [comment]
Ready for ReTest

**Comment by ABonomo21** [comment]
Testing Failure-Life Safety Review still did not generate even though the fee did-AW
![image](https://user-images.githubusercontent.com/47611580/54285397-41922680-4578-11e9-8f55-e6ff70c29429.png)

**Comment by imazlout** [comment]
@ABonomo21  We copied the formula from Hansen 7 which checks that the Tank Capacity is >=10000. Is that still valid or should we remove that requirement from the formula?

**Comment by ABonomo21** [comment]
According to Airtable and previous permits the Fire Final is required for Non Res Tanks.-AW

![image](https://user-images.githubusercontent.com/47611580/54766482-b6490e80-4bd1-11e9-843d-5a24a5e6bf82.png)

![image](https://user-images.githubusercontent.com/47611580/54766528-c4972a80-4bd1-11e9-827c-8a05b4222af6.png)

![image](https://user-images.githubusercontent.com/47611580/54766547-d11b8300-4bd1-11e9-8270-b411b1b6c7e6.png)

**Comment by goggansd** [comment]
Altered TANKS_DOLS_Review_AOC to remove check for >10,000 gallons.

**Comment by ABonomo21** [comment]
Confirmed Fixed-Fire final inspection generated-AW

![image](https://user-images.githubusercontent.com/47611580/55240426-40ffbe00-520f-11e9-89d7-da227983718a.png)
