### ISSUE TITLE
Non Res-Electrical Low Voltage-Extra Inspection

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#260]
According to Airtable, the progress inspection is not needed for a Non Res Low Voltage Inspection.-AW
![image](https://user-images.githubusercontent.com/47611580/54130567-001e4180-43e7-11e9-8e84-0ddf7a7bf265.png)

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54283813-2a9e0500-4575-11e9-971e-4391097db05c.png)
