### ISSUE TITLE
PLANNING PREPLAT & PWCONSTRUC

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#261]
Missing eplan status check for PREPLAT AND PWCONSTRUC

![image](https://user-images.githubusercontent.com/4129185/54131488-d49c5680-43e8-11e9-8939-e4ffc05e7b63.png)

**Comment by megisys** [comment]
ready for retest

**Comment by dhenry-KCI** [comment]
Unclear issues - reviewed with MWilkins. ok to close

**Comment by dhenry-KCI** [comment]
areed
