### ISSUE TITLE
PLANNING - DUE DATE WHEN GOING PROJECTDOX

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#262]
Due Date is populating in IPS when project selection is EPLANS. This is across project types for planning. Due date should depend on when plans are received which will not happen in IPS. IT will happen in PDOCS.

![image](https://user-images.githubusercontent.com/4129185/54131599-0e6d5d00-43e9-11e9-84f6-a745b43722ed.png)

**Comment by megisys** [comment]
This is not possible. WE have to set it in IPS. We need to find the first hand shake from Project Dox..

**Comment by dhenry-KCI** [comment]
Not training issue - need to resolve with PDOCS. Can't provide a due date in IPS when we have nothing to review. AREED

**Comment by megisys** [comment]
Dates are now set appropriately in IPS

**Comment by dhenry-KCI** [comment]
still assigning due date when Eplan review is selected.  AReed is correct; we cannot start the "review clock" before the plans are submitted via PDox for review.  Im sure this issue is not unique to FRO, but probably a problem an all Planning AP types.

![image](https://user-images.githubusercontent.com/4129185/57096317-fb895180-6ce2-11e9-973c-613f65a00670.png)

![image](https://user-images.githubusercontent.com/4129185/57096435-40ad8380-6ce3-11e9-97a9-cdc7c841e1cd.png)

MW

**Comment by megisys** [comment]
DueDates for Eplans are now empty

**Comment by dhenry-KCI** [comment]
WORKING WELL AS OF 6/27
