### ISSUE TITLE
ResBldg-Square Footage/Gross Floor Area-Unable to click

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#263]
I am unable to click on the box to type the information in on the Square Footage/Gross Floor Area. Due to this the fees are not calculating correctly because there is no square footage to base the fees off of.
AP #238717-life safety fee

![image](https://user-images.githubusercontent.com/47611580/54133447-7cffea00-43ec-11e9-82ca-a6a92c7ed4d4.png)

**Comment by ABonomo21** [comment]
As discussed Dan- 

We need to move this field down by building height. Then on ResUse and NonRes permits we need to add a field to capture total square footage of space being altered.

**Comment by megisys** [comment]
PLease ReTest

**Comment by ABonomo21** [comment]
Issued is partially fixed-I am able to clink on the box and input the number of square footage and it is located in the correct place. However this is a Res Us Permit an there is not a field to capture total square footage of space being altered.-AW

![image](https://user-images.githubusercontent.com/47611580/54284468-5bcb0500-4576-11e9-8817-e80376fc4450.png)

**Comment by ABonomo21** [comment]
Non Res is the same issue-we are missing the field to capture the total square footage of space being altered.
![image](https://user-images.githubusercontent.com/47611580/54284870-2a066e00-4577-11e9-8ce5-5204cb61deef.png)
![image](https://user-images.githubusercontent.com/47611580/54284884-325ea900-4577-11e9-9d1c-ef4f7cf0b58a.png)

**Comment by ABonomo21** [comment]
fixed-aw

![image](https://user-images.githubusercontent.com/47611580/55638265-c990d800-5794-11e9-97cb-0f6771aab37d.png)

![image](https://user-images.githubusercontent.com/47611580/55638366-fd6bfd80-5794-11e9-9862-c47247eccb8e.png)
