### ISSUE TITLE
Residential Townhome- Fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#264]
RESTWN A/P# 238710- DT State Homebuilder Guaranty $50 is missing-MCoffman
![image](https://user-images.githubusercontent.com/47611580/54132272-4e810f80-43ea-11e9-8af4-f2b1ab393771.png)

This issued continued for the rest of the row of townhouses Permit#'s 238710, 238711, 238714, 238715

**Comment by megisys** [comment]
I need the rules for this one please. WHen should or shouldnt this fee add.. Please and Thank You

**Comment by ABonomo21** [comment]
@megisys 
On all RESBUILD permits for the construction of Townhouses, when the work type is NEW the DT State Homebuilder Guaranty of $50 should generate. -MCoffman

**Comment by imazlout** [comment]
Ready for test.
Now fee adds when occupancy code = RESTOW and Worktype = NEW, 
(Also, If parent structure = False and HOMEB license exists for the applicant, it will add the fee as well (this was the original portion which remained unchanged, I just added the restow portion now)

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54615475-916b6480-4a34-11e9-89b5-2e54dab21aab.png)
