### ISSUE TITLE
Mobile - Building Inspection - Cannot Result Inspection

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#265]
Cannot currently result my Building Footing Inspection. I am getting the following error. 
AP Number - 238712
Inspection Number - 940238

![error](https://user-images.githubusercontent.com/31770504/54137127-6f019780-43f3-11e9-93f4-dcb1dd3063e5.png)

**Comment by megisys** [comment]
PLease reTest

**Comment by JuanitaMiles** [comment]
Every time I login, and get to the home page (where the inspections are listed) I get this error message. I can close this error and move forward. But the system is still glitchy when trying to use the app.

![file-3](https://user-images.githubusercontent.com/31770504/54147041-ab3ef300-4407-11e9-9992-955b62871689.jpeg)

**Comment by megisys** [comment]
You need to resync.. See me tomorrow

**Comment by ABonomo21** [comment]
corrected
