### ISSUE TITLE
Building - Major Logging - Under Review - Resubmit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#266]
When a review is completed with the action of RESUBMIT a second DPZ review auto generates and should not. 

![image](https://user-images.githubusercontent.com/4129185/54142126-6d3cd180-43fd-11e9-8b39-39717a5a2b61.png)

![image](https://user-images.githubusercontent.com/4129185/54142146-79c12a00-43fd-11e9-871a-12ec1b94f77a.png)

AP # 238729

logged by tiffany martin 3/11/19

**Comment by megisys** [comment]
Ready for Retest

**Comment by dhenry-KCI** [comment]
corrected 3/15/19 tiffany martin
