### ISSUE TITLE
Building - FRO - Error Result

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#267]
I keep getting an error result when trying to save the application created. 

![image](https://user-images.githubusercontent.com/4129185/54142753-c5c09e80-43fe-11e9-8c1c-bae14d3cfc1f.png)

AP # ??

logged by tiffany martin 3/11/19

**Comment by megisys** [comment]
PLease ReTest

**Comment by dhenry-KCI** [comment]
seems to be working. tm 4/4/19
