### ISSUE TITLE
Case- Building Case Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#268]
Notification details and permit details needs to be hidden for building case. Permits will be linked via related records and the notice of violation will be recorded within the log entries. 

![image](https://user-images.githubusercontent.com/47611580/54144310-d0306780-4401-11e9-99a3-1fe71f6b27ee.png)

**Comment by ABonomo21** [comment]
This is still not corrected, but I did not originally assign it. My mistake.

**Comment by megisys** [comment]
Not Active but fields are present for any historical data..

**Comment by ABonomo21** [comment]
Perfect- confirmed no entry can be made in those fields.
