### ISSUE TITLE
Electric-Additional Meter-Zoning Fee did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#269]
For the electrical permit for an additional meter, the zoning review fee of $43 did not generate alongside the additional meter fee. #238736-AW
![image](https://user-images.githubusercontent.com/47611580/54150082-01af3000-440e-11e9-8440-836d26d2c3ae.png)

**Comment by megisys** [comment]
Ready for Retest

**Comment by ABonomo21** [comment]
Confirmed Fixed-Fee generated and review generated-AW
![image](https://user-images.githubusercontent.com/47611580/54281923-2bcd3300-4571-11e9-9596-185804c49360.png)
![image](https://user-images.githubusercontent.com/47611580/54282068-8d8d9d00-4571-11e9-8a41-61b4ed5c8287.png)
