### ISSUE TITLE
Use - Landuse - Re-inspection Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#27]
The system should generate re-inspection fees for any inspection type AFTER the second failed inspection of that type. Each additional failed inspection, of that type should generate a re-inspection fee as well. Re-inspection fee = $48.00

Steps to recreate issue:
1. create Use permit and progress to inspections milestone.
2. Fail Fire-Fin inspection (or any inspection type) once. No fees generate.
3. Fail Fire -Fin inspection second time. No fees generate ($48.00 fee should generate at this point)

**Comment by calequin** [comment]
added resinpection fees for all inspection in LANDUSE.

**Comment by dhenry-KCI** [comment]
confirmed fixed-aw
![image](https://user-images.githubusercontent.com/4129185/53909319-6f7ae680-401f-11e9-9b82-14dbc9e891f2.png)
