### ISSUE TITLE
Case- Building/Zoning/ ECS- Fine Review Milestone

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#270]
During the fine review milestone on building, ecs and zoning cases the hold for fine review and all fees being paid should happen at the same time. 

Instead the first time you check status it says fees must be paid, then when you check status after paying the fines, it remains in fines milestone and the fine review populates. 

There should also be instructions for the fees to be added, modified or waived and review must be resulted. (this has been done on other milestones) in the grayed out section under case type in the photo below. 

![image](https://user-images.githubusercontent.com/47611580/54152003-8439ee80-4412-11e9-9e2d-7aa4636bb71f.png)

![image](https://user-images.githubusercontent.com/47611580/54152480-b4ce5800-4413-11e9-87a0-be357005a09a.png)

**Comment by ABonomo21** [comment]
added the instructions - still have a bug with the check status

**Comment by megisys** [comment]
Ashley is doing this work..

**Comment by ABonomo21** [comment]
I am adding these details
