### ISSUE TITLE
Case - Building -Reinspection population issue

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#271]
OLS follow up populated without that type of code enforcement being checked and without an initial inspection of that type case # 237140. only the follow up inspections for the types of code enforcement should populate the subsequent re inspections should only populate for the inspection types that failed the first time. 

![image](https://user-images.githubusercontent.com/47611580/54152099-c6633000-4412-11e9-9d5b-722ad9119db9.png)

**Comment by megisys** [comment]
Ready for Retest

**Comment by ABonomo21** [comment]
This is not corrected the same issue is happening- see log entry and screen shot of the inspections that populated 

![image](https://user-images.githubusercontent.com/47611580/54754581-31062f80-4bba-11e9-8999-a735812710d1.png)

![image](https://user-images.githubusercontent.com/47611580/54754705-80e4f680-4bba-11e9-83e6-552bfa24a965.png)

**Comment by megisys** [comment]
addressed

**Comment by ABonomo21** [comment]
confirmed correction
