### ISSUE TITLE
Case- Building, ECS and Zoning- Milestone Issue

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#272]
Testing zoning, building and ecs case after passing the follow up inspections at the compliance check milestone after awaiting fee payment the milestone went to citation- should have gone to admin closure. It should have only gone to citation if the follow up inspections failed 
Case # 237143, 237141, 237140

![image](https://user-images.githubusercontent.com/47611580/54152193-075b4480-4413-11e9-9490-86dbab0c0d69.png)

**Comment by ABonomo21** [comment]
Also happened in FRO case # 237156

**Comment by ABonomo21** [comment]
Went to retest this and after adding the CPRO in the log to progress past the 30 awaiting applicant actions milestone, the system progressed right through follow up inspection and went to admin closure. 

![image](https://user-images.githubusercontent.com/47611580/54635893-9abbf780-4a5b-11e9-8758-d47c090a7016.png)

**Comment by ABonomo21** [comment]
Still not corrected, Went to retest this and after adding the CPRO in the log to progress past the 30 awaiting applicant actions milestone, the system progressed right through follow up inspection and went to admin closure.

![image](https://user-images.githubusercontent.com/47611580/54753956-b7ba0d00-4bb8-11e9-8699-40e028834ac2.png)

**Comment by goggansd** [comment]
When creating the CPRO log, you need to set the log Start Date to a FUTURE date in order for this to function as you want. The case is waiting for 30 days from the date you input as the CPRO log Start Date. Please retest.

**Comment by ABonomo21** [comment]
confirmed fix.
