### ISSUE TITLE
Building -Electrical and Plumbing -Create License Type

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#273]
We need to set up additional license types in the contact record for each of our difference types of homeowners exams. This way we can eliminate the homeowner passing of 70% or greater check box from electrical and plumbing permits. 

![image](https://user-images.githubusercontent.com/47611580/54152763-61103e80-4414-11e9-896a-72c904e5f4d9.png)

![image](https://user-images.githubusercontent.com/47611580/54152767-63729880-4414-11e9-9b1e-4902fe81bbeb.png)

I am not sure who will work on this County or IPS?

**Comment by ABonomo21** [comment]
We will need to set up training to make sure staff understands were to log passed homeowner exams in IPS.

**Comment by ABonomo21** [comment]
Electrical Exams:
Addition/Alteration/Accessory
New Dwelling
Low Voltage Wiring
Generator
Swimming Pool/Hot Tub
Service Overhead/Underground
Solar Panels
 
Plumbing Exams:
Utility Service
Waste, Vent, Water

**Comment by ABonomo21** [comment]
Attached the various types of exams offered for homeowners above. Martin should meet with Dan to train on how to enter these in the licensed contact records. 
Per discussion with Dustin 3.14.19-

**Comment by ABonomo21** [comment]
License Type is Elect. H.O.E 
Description is :
-Addition/Alteration/Accessory
-New Dwelling
-Low Voltage Wiring
-Generator
-Swimming Pool/Hot Tub
-Service Overhead/Underground
-Solar Panels

License Type is Plumb. H.O.E
Description is :
-Utility Service
-Waste, Vent, Water

![image](https://user-images.githubusercontent.com/47611580/54370388-e6cafe80-464d-11e9-8a0d-1489274838ea.png)

**Comment by mmbanong** [comment]
I have added new Building Electrical and Plumbing License types in ipsdevcopy
Please verify and confirm if that works so I will move it to ipstest

**Comment by ABonomo21** [comment]
I am not able to get into ipsdev copy can you provide the link ?

**Comment by megisys** [comment]
Please do this in IPSTest. I will then CTT

**Comment by dhenry-KCI** [comment]
@mmbanong - see Dan's comment. Please move to IPS Test

**Comment by mmbanong** [comment]
awaiting directions from Dan

**Comment by megisys** [comment]
License Type is Elect. H.O.E
Description is :
-Addition/Alteration/Accessory
-New Dwelling
-Low Voltage Wiring
-Generator
-Swimming Pool/Hot Tub
-Service Overhead/Underground
-Solar Panels

License Type is Plumb. H.O.E
Description is :
-Utility Service
-Waste, Vent, Water

**Comment by megisys** [comment]
License Type is Elect. H.O.E
Description is :
EHOEAAA-Addition/Alteration/Accessory
EHOEND-New Dwelling
EHOELVW -Low Voltage Wiring
EHOEG-Generator
EHOEPOOL-Swimming Pool/Hot Tub
EHOESO-Service Overhead/Underground
EHOESP-Solar Panels

License Type is Plumb. H.O.E
Description is :
PHOEUS -Utility Service
PHOEWVW-Waste, Vent, Water

**Comment by ABonomo21** [comment]
all have been added-aw
