### ISSUE TITLE
Building Permit- NonRes Detail Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#274]
This is a reminder for Dan that we need to add the check boxes for CIP/ Municiple Project and Site Plans on nonresidential building permits. 

CIP projects are exempt from all fees in the fee schedule, with the exception of licensing, re-inspection fees, Temporary COO fees and permit extension fees. 

Municipal government projects are exempt from all fees.

We want the fees to populate and automatically be waived- this was discussed multiple times in the past.- Dustin perhaps you can locate the meeting notes? 

Permits associated with an Approved Site Plan are required to pay a site compliance inspection fee.

**Comment by goggansd** [comment]
Addressed everything except Licensing Fees (NONRESBLDG doesn't seem to have anything by that name, or similar name, in the fees setup).

Here's the list to promote from Dev to Test:

BP_NRES_CIP_WaiveFees_AOC
BP_NRES_Muni_WaiveFees_AOC
NRESBLDG AP Type (Added conditions for waiving fees)
NonResidentialDetails detail page (added checkbox controls for CIP Project, Municipality project, and Approved Site Plans)

**Comment by ABonomo21** [comment]
This needs to be configured for Tanks, Signs, Demo, Trailer- all permits that can be non-res. 

Also need to make sure that Fire, Electrical and Plumbing  check for the building/parent permit CIP/Muni per discussion.

**Comment by megisys** [comment]
Tanks Done...

**Comment by megisys** [comment]
COmpleted All the Non Res Permits... Need to add the CHild Check

**Comment by megisys** [comment]
Added to Children too.

**Comment by ABonomo21** [comment]
Tanks, Signs, Demos, and Trailers (and all their child trade permits) all working-AW

**Comment by ABonomo21** [comment]
CIP/Municipality check boxes are not on the NonRes Detail Page-AW
![image](https://user-images.githubusercontent.com/47611580/56048782-361c5180-5d16-11e9-87d7-1ad9a125d169.png)

**Comment by goggansd** [comment]
Added the fields back in the IPSTest environment. Please retest.

**Comment by ABonomo21** [comment]
fixed for non res-AW
![image](https://user-images.githubusercontent.com/47611580/56136482-e2517880-5f60-11e9-862f-74d725c88349.png)
![image](https://user-images.githubusercontent.com/47611580/56136523-f6957580-5f60-11e9-8484-1ba77d318327.png)
