### ISSUE TITLE
Building Permit- Misc. Detail Pages

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#275]
Reminder for Dan 
Building Use, Zoning Use needs to be captured and completed by reviewers on and available as a detail page for Resbldg/ NonRes to print on the COO
Occupancy Load should be available for non-res. 
Building code edition is captured on building detail pages, we need to discuss if this is the best place for the reviews to complete this entry.

**Comment by megisys** [comment]
PLease Retest - Added to Completeness Check

**Comment by ABonomo21** [comment]
closed - open new issues with the outstanding items so they are separate.
