### ISSUE TITLE
PLANNING- APFO Exemption

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#277]
APFO EXEMPTION should not ask for LOU review. Only a regular APFO Application.
![image](https://user-images.githubusercontent.com/4129185/54207222-2956d480-44b0-11e9-994a-c70737a0e571.png)
 
![image](https://user-images.githubusercontent.com/4129185/54207245-35db2d00-44b0-11e9-89bf-4055a0665dd3.png)

**Comment by dhenry-KCI** [comment]
AReed - this may need discussion

**Comment by dhenry-KCI** [comment]
Reviewed with Dan. On APFO details page - if Exemption Fee selected (see image) and review selection = Approved - close application after all reviews are resulted.  No need to continue through remaining milestones. 
*Only concern is if DUSWM review and DRTE review both need to be resulted as approved to close exemption application. AREED

![image](https://user-images.githubusercontent.com/4129185/54210496-f9aacb00-44b5-11e9-97b7-0af20a310514.png)

**Comment by megisys** [comment]
Ready for Test

**Comment by dhenry-KCI** [comment]
Exemption fee selected and reviews resulted to approved. Project did not move to close. It continued to require me to input a hearing, result signature set, complete APFO additional details page. 
AReed
![image](https://user-images.githubusercontent.com/4129185/54630669-c4235600-4a50-11e9-9441-b37bbbf7f143.png)
![image](https://user-images.githubusercontent.com/4129185/54630635-ac4bd200-4a50-11e9-8b88-d8c9fa0207b7.png)

**Comment by dhenry-KCI** [comment]
failed. A237866.  AR

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
tested and confirmed, reviews approved and project moved to closed A238956
