### ISSUE TITLE
PLANNING APFO Review results

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#278]
Review results for LOU Review and Signature sets to be corrected
![image](https://user-images.githubusercontent.com/4129185/54208193-e0078480-44b1-11e9-8018-0996260dfdf6.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
LOU and signature set review have narrowed results. A237803 AREED - correct
