### ISSUE TITLE
License- Plumbing Master - Confirmation Details Page /Data Migration

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#28]
Confirm License Detail page still does not transfer data information over for what was originally filled in on Trade License Detail Page. The data should convert over, the applicant should update on R4C and the tech should confirm details based on attachments and select the Y for confirmation. 
![image](https://user-images.githubusercontent.com/4129185/52722217-351aae00-2f79-11e9-8bd0-422d3b9217d3.png)

**Comment by megisys** [comment]
This is resolved.. Please Retest

**Comment by ABonomo21** [comment]
information transferred over-fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54756945-a0325280-4bbf-11e9-84a7-f7694a3af6f5.png)
