### ISSUE TITLE
PLANNING- FRO Exemption

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#280]
On FRO, FROEXEMPT work type if FRO Review is Approved - Move to close application. No need to proceed through remaining milestones. 
AREED

(This request is to match what is being done to APFO Exemption selections after discussion with Dan)

![image](https://user-images.githubusercontent.com/4129185/54213095-38db1b00-44ba-11e9-8a8f-26a271393b75.png)

![image](https://user-images.githubusercontent.com/4129185/54213227-73dd4e80-44ba-11e9-8a1d-28eabfbe4622.png)

**Comment by megisys** [comment]
Please ReTest

**Comment by dhenry-KCI** [comment]
FIXED
