### ISSUE TITLE
ProjectDox - ResUse - Awaiting Revision Fee Payment

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#281]
The second cycle of reviews have been resulted in ProjectDox with a status = approve. IPS has progressed from a current milestone = under review to "Awaiting Revision Payment". 

The system should progress from "Under Review"  to "Add Fees" milestone.

See AP 238752

![image](https://user-images.githubusercontent.com/4129185/54215260-06332180-44be-11e9-97dd-efc54b120c69.png)

**Comment by megisys** [comment]
Resolved This. PLease Retest
