### ISSUE TITLE
Planning - PREPLAT - Stuck in Paperwork Review

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#282]
Trying to complete a PREPLAT application and the application is stuck in the Paperwork Review milestone. All status checks have been satisfied, therefore the application should progress to the next milestone.

![image](https://user-images.githubusercontent.com/31770504/54216385-ebfa4300-44bf-11e9-9d7f-67e5a50efcb7.png)

![image](https://user-images.githubusercontent.com/31770504/54216427-ff0d1300-44bf-11e9-9f28-c0b50a07d02c.png)

**Comment by megisys** [comment]
Ready for Retest,. Had a return Res in Status Check Formula

**Comment by dhenry-KCI** [comment]
Issue resolved AReed PP237633
