### ISSUE TITLE
PLANNING - PREPLAT - detail page Pends R4C Development

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#284]
The detail page on PREPLAT has many fields that should not be viewable to the applicant. Are we able to make only certain fields viewable on Rhythm 4 Civics?

**Comment by dhenry-KCI** [comment]
AREED

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/54223539-16eb9380-44ce-11e9-90a7-326c52e7c8e2.png)

**Comment by dhenry-KCI** [comment]
revisit when this AP is developed in R4C  MW

**Comment by calequin** [comment]
Which fields need to be disabled for R4C?

**Comment by dhenry-KCI** [comment]
see #768

MW
