### ISSUE TITLE
PLANNING PREPLAT details page - fees y/n

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#285]
Remove Fees Y/N field. The purpose of this y/n should be covered under the Municipality/County CIP check box. AReed

![image](https://user-images.githubusercontent.com/4129185/54224167-55ce1900-44cf-11e9-815f-f37f337d5d5c.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
Resolved PP237635 AREED
