### ISSUE TITLE
Building - Major Logging - Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#286]
Fees are not populating for a Major Logging permit. Went straight to Under Review. 

AP # 238762

Logged by Tiffany Martin 3/12/19

**Comment by megisys** [comment]
Which fees should have based on selections ?

**Comment by dhenry-KCI** [comment]
The following fees should populate for Major Logging-
- Major Loggin Fee - $414
- SCD Loggin Review Fee - $60

**Comment by megisys** [comment]
PLease ReTest

**Comment by dhenry-KCI** [comment]
The fees that populated are the fees associated with a minor logging permit - not a major logging permit.

AP # 238874

logged by tiffany martin

**Comment by dhenry-KCI** [comment]
Major Logging Fee did not populate. Should be $414.00

![image](https://user-images.githubusercontent.com/4129185/54618070-c7aae300-4a38-11e9-98d6-0a5aaca1822d.png)

AP # 238942

logged by tiffany martin 3/19/19

**Comment by megisys** [comment]
Addressed this one..

**Comment by dhenry-KCI** [comment]
CORRECTED 3/26/19 TM
