### ISSUE TITLE
PLANNING - PRE PLAT - CIP/MUNICIPALICY Fees 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#287]
PP237629 Fees need to populate then automatically waive when CIP/Municipality is selected. 

![image](https://user-images.githubusercontent.com/4129185/54224545-1eac3780-44d0-11e9-988d-d2751df8b866.png)
![image](https://user-images.githubusercontent.com/4129185/54224645-50250300-44d0-11e9-8105-e256d66f346d.png)

**Comment by megisys** [comment]
This is resolved

**Comment by dhenry-KCI** [comment]
Resolved PP237635 AREED
