### ISSUE TITLE
Building - Completeness Check Review Results

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#29]
Need to change the review result of "Junk" to "Not Applicable" for all completeness check reviews that include the result code of "Junk" - AB 2.13.19

![image](https://user-images.githubusercontent.com/4129185/52724334-2209dd00-2f7d-11e9-9364-d43b8ae96bad.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Replaced JUNK with NA. Updated the following formulas as a result:

- PLUMBPERM_CompletenessCheck_NSF
- BP_CompletenessCheck_NSF

Please screenshot for proof of test. (Tested with AP#236103 in DEV)
<img width="960" alt="issue29_fixed" src="https://user-images.githubusercontent.com/47784290/53137800-22dcd900-3552-11e9-856e-263a99d0b3c0.png">

**Comment by dhenry-KCI** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/4129185/53908704-f62ec400-401d-11e9-85e7-1a4f44ae7f17.png)
