### ISSUE TITLE
Building - SWMESD - Pending Issuance - Issue # 2

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#290]
The system should redline us for the ESD Type to be completed prior to issuance - this is typically done by Vijay during his review. 

![image](https://user-images.githubusercontent.com/4129185/54226841-0559ba00-44d5-11e9-8724-eb7f2be358b9.png)

AP #238770

logged by tiffany martin 3/12/19

**Comment by megisys** [comment]
Red line how.. It should be a standard operating procedure of him completing the review in question.. AS if none are applicable then it would get stuck or if he used other and how do I check he has selected all the options he needs // @dhenry-KCI

**Comment by dhenry-KCI** [comment]
Discussion with TM - confirmed population of ESD field will be a training exercise.
