### ISSUE TITLE
Building - SWMESD - Pending Issuance - Issue # 3

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#291]
At pending issuance the system redlined me to attach a building permit as a parent as a related record. This should be moved and the applicant should provide this information to us. This permit will only be created once and after a building permit has been applied for.

I think that we need to add under grading details, under ESD types the building permit # 

Ask Dan if this should be added to the detail page or under rhythm for civics as a related record requirement 

![image](https://user-images.githubusercontent.com/4129185/54227755-fc69e800-44d6-11e9-82b0-60e0e9e0cac2.png)

AP # 238770

logged by tiffany martin 3/12/19

**Comment by megisys** [comment]
Duplicate

**Comment by ABonomo21** [comment]
no longer an issue - permits will automatically be generated and linked as a child. if one is submitted as a stand alone- the application will be reviewed under completeness check where the tech will check property browser to make sure there is a building permit
