### ISSUE TITLE
Building - Auto-populating different fields for all permit types 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#293]
The words are not auto-populating when we are typing application type for example. I remember that this was supposed to get fixed or was going to at some point. Just wanted to make note that it still isn't working correctly. I have checked with Ashlye and her staff as well.

logged by tiffany martin 3/12/19

**Comment by ABonomo21** [comment]
closing for now will re-open if it is an issue
