### ISSUE TITLE
Building - Nonres - Fire Final Inspection

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#294]
The system did not generate the fire final inspection on a non res building permit where work type = new and has a construction type = Vanilla Box.  

See airtable for inspection rules

AP - 238383
Logged by Abbie White

![image](https://user-images.githubusercontent.com/4129185/54285488-6eded480-4578-11e9-97d5-940526d217d5.png)

**Comment by imazlout** [comment]
Ready to test. 
Fire-Final inspection now gets added

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54696938-1e7cef00-4b03-11e9-8521-e08a48eec32b.png)
