### ISSUE TITLE
Building - Major Grading - Mitigation Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#295]
All of the mitigation details are not listed as options. Please see attached spreadsheet showing what all should be in mitigation details as an option. There are currently only 18 options shown in IPS 7 and on the spreadsheet below there is 8 pages.

After entering quantity in the mitigation details - no total cost populate

https://www.frederickcountymd.gov/DocumentCenter/View/1020/APPROVED-UNIT-PRICES---PDF?bidId= 

AP # 238781

logged by tiffany martin 3/13/19

**Comment by ABonomo21** [comment]
@mmbanong

**Comment by mmbanong** [comment]
Updated Building - Major Grading - Mitigation Details

**Comment by dhenry-KCI** [comment]
@calequin - is there a way we can combine the code and description to display in R4C?

**Comment by calequin** [comment]
@dhenry-KCI - unfortunately no, rhythm only reads description fields from back office. This is purposefully intended since most constituents don't understand what a backoffice code would be.

**Comment by ABonomo21** [comment]
@dhenry- closing because this is a duplicate #1228
