### ISSUE TITLE
Tank Non Res- Fire Final Inspection did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#296]
The Fire Final Inspection did not generate even though the life safety fee was paid. See issue #256 
![image](https://user-images.githubusercontent.com/47611580/54285696-d85ee300-4578-11e9-9673-9efee49dfd27.png)

**Comment by imazlout** [comment]
@ABonomo21 I have the same question as #256. We copied the formula from Hansen 7 which checks that the Tank Capacity is >=10000. Is that still valid or should we remove that requirement from the formula?

**Comment by ABonomo21** [comment]
According to Airtable and previous permits the Fire Final is required for Non Res Tanks.-AW

![image](https://user-images.githubusercontent.com/47611580/54766482-b6490e80-4bd1-11e9-843d-5a24a5e6bf82.png)

![image](https://user-images.githubusercontent.com/47611580/54766528-c4972a80-4bd1-11e9-827c-8a05b4222af6.png)

![image](https://user-images.githubusercontent.com/47611580/54766547-d11b8300-4bd1-11e9-8270-b411b1b6c7e6.png)

**Comment by goggansd** [comment]
Changed FIRE-FIN inspection AOC formula TANKS_WrkTypeRemoveInspection_AOC to remove check for > 10,000 gallons. Ready to promote for retesting.

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55488538-45a4e780-55fe-11e9-8a19-cccbf2b3a9af.png)
