### ISSUE TITLE
NonRes Building - Health Fees 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#298]
The system did not generate the appropriate Health FD Fee. The user checked the Food Related checkbox, and the proper review generated, but not the associated health fee.

AP - 238432
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/54287761-b10a1500-457c-11e9-80e7-604dbfa583fb.png)

![image](https://user-images.githubusercontent.com/4129185/54287772-b5363280-457c-11e9-9e95-374d9123a7dd.png)

**Comment by imazlout** [comment]
Health review fee didn't populate because address used is in an incorporated town.

**Comment by ABonomo21** [comment]
This has nothing to do with the fact that it is in an incorporated town. 

However, we can disregard this issued, per an email with the HD, Karen Amoss and Barry G. we do not charge the $50.00 health review fee is only Food Services is involved. The review should still populate if food services is checked.

AB 3.25.19
