### ISSUE TITLE
Building - Driveway - Inspections

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#299]
Driveway final inspection failed - went to reschedule but i get an error stating that it cannot schedule inspection. all related child permits must be completed.

![image](https://user-images.githubusercontent.com/4129185/54288263-908e8a80-457d-11e9-92d7-d50292893025.png)

AP # 238791

logged by tiffany martin 3/13/19

**Comment by goggansd** [comment]
I believe this is by design. The Final inspection is typically the last thing to occur. Should the system allow the Final inspection on the Driveway permit to be scheduled even though the Grading permit is not finished?

**Comment by dhenry-KCI** [comment]
To me, you should be able to fail the final inspection and schedule another inspection without having to close the associated/linked building permit.

tiffany martin 3/22/19

**Comment by dhenry-KCI** [comment]
remove requirement for child permits (grading) to be finaled if related to driveway

tm 4/30/19

**Comment by megisys** [comment]
PLease Retest. I made changes

**Comment by ABonomo21** [comment]
Corrected. Thank you.

5/2/19 EP
