### ISSUE TITLE
License - Plumbing Master - Section Complete Dropdown

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#3]
The system does not present the user with values to select for the Section Complete dropdown. This occurs when the user is trying to renew a license (PM01529). 

System should present the user with value Section Complete dropdown values.

Logged by K. Vanaman on 2/4

![image](https://user-images.githubusercontent.com/4129185/52348584-acd55f80-29f2-11e9-8309-4eaa4fccf654.png)

**Comment by goggansd** [comment]
Dan Grendon has removed the Section Complete field for this detail page, since it already has required fields. Please retest.

**Comment by dhenry-KCI** [comment]
Trade License Detail page no longer looks like the initial one Kelly logged an error for- confirmed correct AB 2.13.19
![image](https://user-images.githubusercontent.com/4129185/52721041-cc323680-2f76-11e9-9d74-fbf3ae5a711f.png)
