### ISSUE TITLE
Building- Sign Permit 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#30]
Allowed site inspection to be completed on sign permit, prior to electrical inspection being issued, site inspection should occur after electrical permit is issued and passes final inspection- this is only a requirement if the sign requires and electrical permit 
![image](https://user-images.githubusercontent.com/4129185/52725216-bf194580-2f7e-11e9-962f-a4c7970c70c1.png)

**Comment by imazlout** [comment]
Training Needed. Duplicate of Issue #68 and #80

**Comment by dhenry-KCI** [comment]
AP - 237355 with same issue

Logged by A. White.

**Comment by ABonomo21** [comment]
Closed-Marked as Training Issue under duplicate issue #68 and #80 -MCoffman
