### ISSUE TITLE
NonRes - Alteration - Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#302]
The system generated the appropriate value of the filing fee but the Amount generated added an additional $22.00 to the fee.

AP-238478
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/54289366-676ef980-457f-11e9-8dc7-774149a4e6ab.png)

**Comment by imazlout** [comment]
Ready for test. For some reason the use minimum checkbox was checked on the config for the fee (Maybe I accidentally checked it during config, I apologize). I have since removed he minimum fee check box of $48, so now it should be charging the $26 only

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54691748-2dab6f00-4afa-11e9-9ad4-11b7e16671cf.png)
