### ISSUE TITLE
Building - Bond Track - Bond Transaction

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#305]
We would like the deposit, release, and balance information from the bond information tab to also carry over to the bond transaction detail. 

![bond trans](https://user-images.githubusercontent.com/4129185/54290531-82db0400-4581-11e9-972b-3fcef83e58e2.png)
![bond trans 2](https://user-images.githubusercontent.com/4129185/54290534-84a4c780-4581-11e9-9585-4e4fb0023a9a.png)

BT-4924/4925

logged by tiffany martin 3/13/19

**Comment by megisys** [comment]
Not Possible

**Comment by dhenry-KCI** [comment]
Closing for potential future enhancement
