### ISSUE TITLE
Impact Fees- City Payment 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#308]
Need to create a a/p type called impact fees for the allowance to process impact fee payments for properties in the City of Frederick. 

It needs to include all Residential Occupancy Types and should have the City Library and School impact fee budget strings. 

Example of City Permits numbers in H7
![image](https://user-images.githubusercontent.com/47611580/54290797-fbda5b80-4581-11e9-977f-6a721c740ef2.png)

![image](https://user-images.githubusercontent.com/47611580/54290968-3ba14300-4582-11e9-9cf6-eef63bafee3a.png)

![image](https://user-images.githubusercontent.com/47611580/54291031-55db2100-4582-11e9-952a-8ab047e0a1ea.png)

**Comment by megisys** [comment]
Ready for Testing

**Comment by ABonomo21** [comment]
no apt type created closed this issue
