### ISSUE TITLE
Building- Review Results

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#31]
The application is in a "pre-issued permit" (milestone) which is actually a stage progression in H7, the review type was a signature review migrated from H7 which is no longer used in IPS. 
![image](https://user-images.githubusercontent.com/4129185/52725970-313e5a00-2f80-11e9-8f6e-9aa64bc17dfb.png)

When I went to record the Review Results of that signature review for a sign permit that was migrated from H7 it populated the following results,
![image](https://user-images.githubusercontent.com/4129185/52725870-094ef680-2f80-11e9-91e8-209928ae9467.png)

Currently in H7 these are the result options:
![image](https://user-images.githubusercontent.com/4129185/52726433-2e903480-2f81-11e9-82be-64ce2c65d65e.png)

Would like existing a/p's with a pre-issued permit milestone in H7 pending signature review when migrated to IPS to only have a review result of "Approved" and "Not Applicable" then staff with the permissions to have Denied, should have "Denied" available.

AB 2.13.19

**Comment by ABonomo21** [comment]
All building permits appear to have the same review result options. These need to be corrected. 

![image](https://user-images.githubusercontent.com/47611580/52800497-e0933380-3049-11e9-8703-c57af6509430.png)

**Comment by imazlout** [comment]
This a migration thing of how information is brought into IPS11 from H7. Assigning to Dan.

**Comment by megisys** [comment]
This is a Data Issue.. We are not going to configure for old data which is not closed.. We will provide training support here. We need to have a meeting to move old data to new milestones.. @dhenry-KCI I have asked for this to be set up for a while now.. Old Data to New Data Progression

**Comment by ABonomo21** [comment]
Data Issue-Closed-AW
![image](https://user-images.githubusercontent.com/47611580/55732170-87ac9f80-59e9-11e9-91fb-8ae3166cdf01.png)
