### ISSUE TITLE
Non Res - New Construction - Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#310]
The system did not generate the appropriate fees for a Non-Residential Building Permit with a COntruction Type = Foundation. System was missing the $48.00 Foundation only Building Fee

https://airtable.com/tblgyTlGmmutKLoy2/viwohSeD0pRasjx7r?blocks=hide

AP - 238485
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/54292768-24178980-4585-11e9-83e6-27ad7f652249.png)

**Comment by imazlout** [comment]
Ready for test.
Added Construction Type ="Found-Slab" to formula so that the minimum $48 building fee gets added in the scenario the user tested

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54690509-f1770f00-4af7-11e9-8199-e3cd560b7317.png)
