### ISSUE TITLE
Building - Non Res (Foundation Only) - Fire Final Inspection

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#313]
The system is generating a fire final inspection for a Non Res Foundation only AP. The fire final inspection should be not applied to a Non Res Foundation AP.

https://airtable.com/tblgyTlGmmutKLoy2/viwohSeD0pRasjx7r?blocks=hide

AP - 238485

![image](https://user-images.githubusercontent.com/4129185/54293748-ea478280-4586-11e9-8975-9fca0c154b35.png)

**Comment by imazlout** [comment]
Similar to question for #311 and #312, @ABonomo21 Please let me know the details of when fire inspection is required for nonresbldg and I'll go ahead and make the change. Looks like worktype = New is too broad and more criteria needs to be added.

**Comment by ABonomo21** [comment]
See highlighted section in photo from Airtable 

![image](https://user-images.githubusercontent.com/47611580/54711896-5135e000-4b21-11e9-9345-46fc8cb0fe8c.png)

**Comment by megisys** [comment]
Ready for Retest

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55491582-ba2e5500-5603-11e9-8de7-7723d8634902.png)
