### ISSUE TITLE
PLANNING - PWCONSTRUC - duswm REVIEW MISSING

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#315]
DUSWM fee didn't populate on public water/sewer. Health fee to be removed under separate BUG. 
AREED

![image](https://user-images.githubusercontent.com/4129185/54294808-419a2280-4588-11e9-9a25-232710c6f132.png)

**Comment by megisys** [comment]
PLease Retest this one..

**Comment by dhenry-KCI** [comment]
fixed PW237893
MW
