### ISSUE TITLE
PLANNING - PWCONSTRUC - remove DOLS REVIEW

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#316]
Remove DOLS fee on Minor -Improvement Revision, REVMNIMPRV
DOLS does not review minor improvement revisions

![image](https://user-images.githubusercontent.com/4129185/54300352-10731f80-4593-11e9-97e0-2e8356fc97e6.png)
![image](https://user-images.githubusercontent.com/4129185/54300440-3bf60a00-4593-11e9-84d8-20a0613198ff.png)

**Comment by megisys** [comment]
Please ReTest

**Comment by dhenry-KCI** [comment]
fixed  PW237891
MW
