### ISSUE TITLE
PLANNING - PWCONSTRUC - SWM Concept Plan - wrong fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#317]
Only fee should be Concept Plan - Engineering $789

![image](https://user-images.githubusercontent.com/4129185/54302064-8dec5f00-4596-11e9-937d-c79a984c2595.png)
![image](https://user-images.githubusercontent.com/4129185/54302117-a6f51000-4596-11e9-9692-339726b58e4b.png)
![image](https://user-images.githubusercontent.com/4129185/54302207-d015a080-4596-11e9-831f-4681fa565ee4.png)

**Comment by megisys** [comment]
PLease Retest..

**Comment by dhenry-KCI** [comment]
failed.

![image](https://user-images.githubusercontent.com/4129185/54763856-19847200-4bcd-11e9-80c1-602873b9bdea.png)

MW

**Comment by megisys** [comment]
Adjusted

**Comment by dhenry-KCI** [comment]
confirmed fee correct PW238958 areed
