### ISSUE TITLE
Building-Holds not showing up on Check Status

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#318]
The holds on a permit are not showing up on the check status-AW

![image](https://user-images.githubusercontent.com/47611580/54302559-85e0ef00-4597-11e9-8e86-17234546e691.png)

![image](https://user-images.githubusercontent.com/47611580/54302577-8f6a5700-4597-11e9-9fdc-cc1f980c5848.png)

**Comment by imazlout** [comment]
Hold check for PI Hold is on Pending Issuance milestone
Hold check for UO hold is on Pending Certificate milestone

@ABonomo21 if the above is incorrect, please list all milestones where the hold checks should redline

**Comment by ABonomo21** [comment]
the U & O hold is fine on the pending certificate stage however as mentioned in Issue #319 the P&I hold can have multiple meanings/uses and needs to show on the check status and prevent the permit from progressing onto the next stage.-AW

**Comment by ABonomo21** [comment]
Closed along with issue #319 -AW
