### ISSUE TITLE
Building- Permit closed with two open holds

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#319]
Permit closed with two open holds. Holds (conditions) should not let a permit close and finalize if they are still open.-AW
![image](https://user-images.githubusercontent.com/47611580/54302935-3bac3d80-4598-11e9-9c18-f3e2187e19f2.png)

**Comment by imazlout** [comment]
Seems to be working fine for me. I added the PIHold, and then when i got to Pending Issuance milestone, i wasn't allowed to proceed until there was a stop date.

<img width="956" alt="Issue319" src="https://user-images.githubusercontent.com/47784290/54377967-a921a200-465c-11e9-884b-8635c086c6b7.PNG">

**Comment by ABonomo21** [comment]
@imazlout   Holds/Conditions need to be shown on the check status. For example-If this permit #238994 has a new property owner but we do not have proof of ownership (copy of a deed) we would put the application on hold for a copy of the deed. This permit should not be able to be issued until we receive that deed.  The same situation can apply to PIHold, This hold was placed on the permit to stop the permit from issuing until new permits are applied for to replace the expired permits on the property. If the holds do not show up on the check status and only stop the permit during the pending certificate, then it is like the holds do not exist at all and work can be completed before the requirements of these holds are met. Currently in Hanson 7, we place the hold on the permit after the fees are paid and the reviews are generated/assigned. placing the holds on at this moment stops the permit from issuing even if the reviews are complete.-AW

#238994
![image](https://user-images.githubusercontent.com/47611580/54763610-aa0e8280-4bcc-11e9-9b6d-1ddd9c1c24f5.png)


Example from Hansen 7-This permit has a hold on it for a fee to be paid. It appears on the check status and this hold will stop the permit from issuing even though the reviews are being completed. So it will stay in Pre-Issue Permit status until the hold is approved.
![image](https://user-images.githubusercontent.com/47611580/54764221-be9f4a80-4bcd-11e9-97a1-07be7b906e4b.png)

**Comment by megisys** [comment]
Hi This is a training Issue.. in IPS11 we are using LOGS !! Not Conditions... Please retest using LOGS !

**Comment by ABonomo21** [comment]
Per Ashlye, Holds are the same as conditions, they need to hold up permits and potentially stop them from being issued or closing/finalizing.-AW

**Comment by ABonomo21** [comment]
re-test as a log entry

**Comment by ABonomo21** [comment]
logs as holds works!-AW
![image](https://user-images.githubusercontent.com/47611580/55960573-12d0a400-5c3b-11e9-828e-533326bc9435.png)
