### ISSUE TITLE
Building- Electrical Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#32]
Existing electrical permit migrated from H7 that has a pending signature review in a pre-issued milestone, would not progress forward once the results were recorded as approved. stuck in the pre-issued milestone. 

![image](https://user-images.githubusercontent.com/4129185/52727651-aeb79980-2f83-11e9-9ce6-6991e4ec19df.png)

ab 2.13.19

**Comment by megisys** [comment]
This is expected @dhenry-KCI we talked about this.. We need to come up with the rules again from old to new milestones.. This is the transistion task we need to do after the latest clean up. Will need to be done for  all AP Types over all modules

**Comment by ABonomo21** [comment]
This is still occurring. The resuse permit #186606 is not yet issued in Hanson. However when you go to check status there is nothing there to be able to move it forward. I'm sure there will be many permits that this will affect when we go live if we are not able to move them forward.-AW
![image](https://user-images.githubusercontent.com/47611580/56986928-1d0b0180-6b5a-11e9-8b4a-b51421b7d36d.png)

**Comment by megisys** [comment]
Closed - Old Ticket
