### ISSUE TITLE
PLANNING - PWCONSTRUC - SWM Concept Plan Reviewers

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#320]
The only reviewer for this plan is PWDR. Remove health and DUSWM (this seems to be populating based on parcel layer review. Duswm and health are never reviewers for SWM concept plan. AReed

![image](https://user-images.githubusercontent.com/4129185/54302943-3fd85b00-4598-11e9-9e92-5aaf43fac167.png)
![image](https://user-images.githubusercontent.com/4129185/54303104-a3628880-4598-11e9-876a-be34814970ff.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
fixed PW237890

MW
