### ISSUE TITLE
Planning- Preplat- stuck in paperwork review 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#323]
stuck in paperwork review again after this mornings fix.

![image](https://user-images.githubusercontent.com/4129185/54308191-d4948600-45a3-11e9-8ed6-a3e47ea14c84.png)

thinking it may be the occupancy type.  should check all occ types to make sure the earlier fix is applied to all.

**Comment by dhenry-KCI** [comment]
Dan - Completed app with same options that were tested earlier today that worked and it no longer works.
PP237633 worked 3/13 earlier in day
PP237659 same but stuck in Paperwork Review

**Comment by megisys** [comment]
Issue Addressed..

**Comment by dhenry-KCI** [comment]
still stuck in paperwork review

![image](https://user-images.githubusercontent.com/4129185/54436403-d592f800-4708-11e9-9562-812a6b653272.png)

![image](https://user-images.githubusercontent.com/4129185/54436995-0d4e6f80-470a-11e9-9891-2917835ac8dd.png)

MW

**Comment by goggansd** [comment]
Group Add from PP237675 to copy all details (effectively cloning the original), moved through to Admin Closure without a hitch...
![image](https://user-images.githubusercontent.com/28841997/54537941-bba42000-4969-11e9-904d-184ccbb8f95b.png)

**Comment by dhenry-KCI** [comment]
corrected on test pp237844 areed
