### ISSUE TITLE
Building-ResSFD-Homebuilder fee not generating

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#324]
#238812  The Hombuilder fee did not generate even though the primary applicant is a licensed homebuilder. could possibly be related to issue #325 -AW

![image](https://user-images.githubusercontent.com/47611580/54366319-d4999200-4646-11e9-82a7-c3b1e79d3554.png)

![image](https://user-images.githubusercontent.com/47611580/54366405-ff83e600-4646-11e9-980f-b4067b806e4e.png)

**Comment by imazlout** [comment]
@ABonomo21 the license is a BUSLIC, while the formula is looking for a HOMEB license type. Should I update the formula to allow for both license types, either HOMEB or BUSLIC?

**Comment by ABonomo21** [comment]
You should have the formula look for a license type of HOMEB

![image](https://user-images.githubusercontent.com/47611580/54711314-08c9f280-4b20-11e9-8625-1bb3266083a8.png)

**Comment by goggansd** [comment]
@ABonomo21 I think Ibti is saying that the code already checks for HOMEB, but that the contractor in question does not, in fact, have a HOMEB license. Instead, it has a BUSLIC license.

![image](https://user-images.githubusercontent.com/28841997/55178906-b9f20d80-515c-11e9-8785-d518a72a8d91.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/55508400-d217d000-5627-11e9-83ed-656ae5190288.png)
See in H7 that the license type is a homebuilder, why is is a buslic in 11??? Data Migration issue??

**Comment by megisys** [comment]
When was this added ??

**Comment by megisys** [comment]
You need to add BUSCH as a contact. AS he is the Home Builder.. Not the Company he works for..

**Comment by ABonomo21** [comment]
same as #324

**Comment by megisys** [comment]
Ready for Retes in PreProd

**Comment by ABonomo21** [comment]
245641- fee generated
