### ISSUE TITLE
Building-ResSFD-Duplicate Egress Type

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#329]
On the ResSFD Egress type Bilco Door is duplicated. Bilco is the correct spelling, not Belco-AW

![image](https://user-images.githubusercontent.com/47611580/54369268-03663700-464c-11e9-9245-d537c316bd35.png)

**Comment by imazlout** [comment]
Ready for test. Expired BELCO

**Comment by ABonomo21** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54438064-530c3780-470c-11e9-8a7f-f5031fb91644.png)
