### ISSUE TITLE
Building- Demolition- Work type options

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#33]
Interior Only option needs to be removed from the work type selection on Demolition permit. If an interior demolition is being completed, that needs to be permitted as an alteration permit. 
AB 2.13.19
![image](https://user-images.githubusercontent.com/4129185/52734870-40c79e00-2f94-11e9-8d53-3003ec60e46f.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.
Removed Interior from options for Demolition Worktype. Please screenshot for proof of test:
<img width="960" alt="issue 33_fixed" src="https://user-images.githubusercontent.com/47784290/53138123-3177c000-3553-11e9-9818-88f369804657.png">

**Comment by ABonomo21** [comment]
NOT Corrected-MCoffman

Demo A/P# 238592
![image](https://user-images.githubusercontent.com/47611580/53893155-a5a66f00-3ffb-11e9-9af8-4a29fdd5c9c3.png)

**Comment by imazlout** [comment]
Ready for Test.
It looks like that change that I made in Dev didn't migrate to Test. I went ahead and reapllied the change directly to Test environment.

<img width="903" alt="issue33_fixed" src="https://user-images.githubusercontent.com/47784290/53897466-2f5a3a80-4004-11e9-9642-0e6c377762df.PNG">

**Comment by dhenry-KCI** [comment]
confirmed fixed-aw
![image](https://user-images.githubusercontent.com/4129185/53909903-aa314e80-4020-11e9-8dc6-ba7c73fb31be.png)
