### ISSUE TITLE
Use-Gaming-New Gaming Permits

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#330]
The check status states that there is an open case on the property but there is no attached attached to this permit. Gaming permits do not always have addresses attached to the permit. (Supervisor overriding to move forward and continue with the permit testing)-AW

![image](https://user-images.githubusercontent.com/47611580/54377033-bc337280-465a-11e9-99ce-aed5a33951b3.png)

**Comment by megisys** [comment]
Addressed this

**Comment by ABonomo21** [comment]
Retest failed, open case notification still generated even though there is no address on the permit.-AW
![image](https://user-images.githubusercontent.com/47611580/54440991-23f8c480-4712-11e9-9c01-95e758b88ccf.png)

**Comment by ABonomo21** [comment]
This also happened for a new tip jar permit today.-AW
![image](https://user-images.githubusercontent.com/47611580/54709015-087b2880-4b1b-11e9-973e-bb77bb7a6cc7.png)

**Comment by ABonomo21** [comment]
appears to be working
