### ISSUE TITLE
Use-Gaming-Conditions(Holds) not appearing on check status

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#331]
For all Gaming permits-The holds/conditions placed on the gaming permit are not appearing on the check status. We need to have the holds/conditions appear on the check status to stop the permit from closing out until we have received all gaming reports for the permit for the year.-AW
![image](https://user-images.githubusercontent.com/47611580/54377877-724b8c00-465c-11e9-8aef-e1212d43c437.png)
![image](https://user-images.githubusercontent.com/47611580/54377886-7a0b3080-465c-11e9-9686-14a7ca303917.png)

**Comment by megisys** [comment]
Added Check

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54709444-dfa76300-4b1b-11e9-97d8-bc7615328dda.png)
