### ISSUE TITLE
Planning-Plat-Combined prelim/Final

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#332]
Historic review populated even though historic was not selected on details page (PL237661)

![image](https://user-images.githubusercontent.com/4129185/54378559-f0f4f900-465d-11e9-9c83-29b181da95c9.png)
![image](https://user-images.githubusercontent.com/4129185/54378578-f7837080-465d-11e9-919e-8594bc117b0d.png)

**Comment by megisys** [comment]
Bug @goggansd Can you attempt

**Comment by goggansd** [comment]
Attempted fixes applied, but to no avail:

Removed suspect sections of workflow formula code, one at a time.
Verified workflow formula logic/coding.
Verified all detail page object and class names in workflow manager formula editor, using copy/paste to ensure no typographical errors in naming.
Replaced Historic field with new YesNo enumeration field using Schema Manager and synchronized table.
Bound existing checkbox control to new YesNo enumeration field
Replaced existing checkbox control with new checkbox control bound to new YesNo enumeration field.
Bound new checkbox control to original YesNo enumeration field.

@megisys, any other ideas?

**Comment by megisys** [comment]
NO>>> IT IS DRIVING ME CRAZY >>> I HATE LIFE RIGHT NOW !!

**Comment by megisys** [comment]
FIXED>>>>>>> WOOO HOOOOOO FIXED>>>>>> CAN NOT BELIEVE IT

**Comment by dhenry-KCI** [comment]
resolved per pl237854

MW
