### ISSUE TITLE
Planning-plat-combined prelim/final 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#333]
Historic review results list too long. PL237661

![image](https://user-images.githubusercontent.com/4129185/54378802-80021100-465e-11e9-90bc-b5c09f718042.png)

![image](https://user-images.githubusercontent.com/4129185/54378836-960fd180-465e-11e9-8ad8-131e5f2bd043.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
fixed pl237765

MW
