### ISSUE TITLE
Preliminary-Plat-Combined Prelim/Final

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#334]
Historic review populated on second review after that review was waived on first review

![image](https://user-images.githubusercontent.com/4129185/54379807-7ed1e380-4660-11e9-8d70-4e15b3273832.png)

**Comment by megisys** [comment]
Resolved.. Fixing the fact it is loading all the time on another ticket

**Comment by dhenry-KCI** [comment]
PL237812 
DUSWM populated a 2nd review after approved. Historic populated a 2nd review after NA review result on 1st review
AReed
![image](https://user-images.githubusercontent.com/4129185/54633276-36e30000-4a56-11e9-8f3f-da5ec62f486f.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
fixed per PL238920

MW
