### ISSUE TITLE
Use-Gaming-Food/Liquor License expiry dates 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#335]
The Expiry dates for the Food & Liquor board license are not required however we need to make sure we are check for that info during completeness check

We also need to have on Rhythm for Civics, the customer can see a notice that copies of their Food and Liquor license will need to be uploaded during time of application.
![image](https://user-images.githubusercontent.com/47611580/54379909-bb054400-4660-11e9-95a3-58a1fb6dcb5f.png)

**Comment by dhenry-KCI** [comment]
COnfirmed training issue
