### ISSUE TITLE
Planning-plat-combined prelim/final

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#336]
move school construction fees added to later milestone.  It is populating after initial review and stopping stage progression, but it is too early in the process to know if school fees will be required.  Move it to awaiting paperwork milestone :)

![image](https://user-images.githubusercontent.com/4129185/54380689-80041000-4662-11e9-8f92-515af5903edc.png)

MW 3/14/19

**Comment by megisys** [comment]
Added to PaperWork Review.. cant add to awaiting Milestones. As these are milestone awaiting on the applicant to complete details.

DAn

**Comment by dhenry-KCI** [comment]
fixed MW
