### ISSUE TITLE
Use-Gaming-Distributor License-Open Case on property

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#337]
After completing the completeness check, the check status states that an open case exists. There is no address on the property so not sure where the case is coming from. Similar to issue #330 -AW 

![image](https://user-images.githubusercontent.com/47611580/54381263-b4c49700-4663-11e9-81aa-8797c8a40991.png)

**Comment by megisys** [comment]
Please Retest

**Comment by ABonomo21** [comment]
Fixed-was able issue Distributor License-AW
![image](https://user-images.githubusercontent.com/47611580/54441759-c49bb400-4713-11e9-8423-2472cdb4fe73.png)
