### ISSUE TITLE
Error Message-Use-Gaming-Distributor License

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#338]
when trying to bypass an open case on a distributor license, this error message occurred.-AW   See issue #337 

![image](https://user-images.githubusercontent.com/47611580/54381437-269ce080-4664-11e9-851d-fad86dae34b6.png)

**Comment by megisys** [comment]
Issue Fixed

**Comment by ABonomo21** [comment]
fixed-AW
