### ISSUE TITLE
Building - Demolition - Work type and Construction type duplicated info

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#34]
There is no need for construction type "entire or partial" to be entered if the work type "entire or partial" is already capturing the same information. 

Should only have to enter this information into one time- AB 2.13.19

![image](https://user-images.githubusercontent.com/4129185/52735087-c4818a80-2f94-11e9-8604-fe5526f334cc.png)

![image](https://user-images.githubusercontent.com/4129185/52735143-e11dc280-2f94-11e9-876c-eaf9e63af6a2.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Removed construction type from detail page and updated the following formulas as a result of the change to be based on the work type instead:
DEMOLITION_DOLS_Review_AOC
DEMOLITION_ConstructionTypeRequired_SCF (disabled formula)

Please screenshot for proof of test

<img width="960" alt="issue34_fixed" src="https://user-images.githubusercontent.com/47784290/53138639-04c4a800-3555-11e9-940c-b980cc9b4954.png">

**Comment by ABonomo21** [comment]
Issue Corrected-MCoffman

Demo A/P# 23851
![image](https://user-images.githubusercontent.com/47611580/53892654-b1ddfc80-3ffa-11e9-938a-1a4e3c9e804f.png)

![image](https://user-images.githubusercontent.com/47611580/53892677-bd312800-3ffa-11e9-9026-5971d9b1b4a8.png)
