### ISSUE TITLE
Use-Gaming-Single Occurrence Tip Jar Report

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#340]
There are duplicate Gaming Report Details pages. Only one is needed and when only one is filled it, it will not let the permit closed/complete-AW
![image](https://user-images.githubusercontent.com/47611580/54383663-f441b200-4668-11e9-98ca-6c3140608ff7.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54610395-531d7780-4a2b-11e9-8e92-f8235a0ad83f.png)
