### ISSUE TITLE
Planning-Plat-Combined Prelim/Final

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#342]
need to require a FRO as a child to Combined Prelim/Final Plat

**Comment by megisys** [comment]
When ..  What happens if the land has no existing trees ? Are we saying FOR ALL PLAT COMBO - Must have FRO ?

Dan

**Comment by dhenry-KCI** [comment]
Yes we are saying for all Plat Combo's FRO is required.

**Comment by goggansd** [comment]
@dhenry-KCI 
Additional questions:
1) Required at which milestone?
2) Assuming this is a FRO Planning application, and not a FROPERMIT (Building Permit) Is this correct?
3) Is it required that one reach a certain state before the other? If so, which state/how? (e.g. should the FRO be in Admin Closure, or Under Review, or not expired, etc. and/or the reverse for the Combo Plat)?

**Comment by megisys** [comment]
FRO Planning.. Add it to Intake Review for now.

**Comment by dhenry-KCI** [comment]
you did great Dan, but now that we know we cant leave Completeness Check we need to remove this function.

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
fixed

MW
