### ISSUE TITLE
Use-Gaming-Single Occurrence Conditions Approval

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#343]
After inputting the report for a single occurrence tip jar permit and approving the conditions, the permit stays stuck in the "awaiting last report" milestone. We tried all the options of condition approvals (RECVD, RPTCMP, & YES)-AW

![image](https://user-images.githubusercontent.com/47611580/54384211-1425a580-466a-11e9-8933-e64a8a2d62b3.png)

![image](https://user-images.githubusercontent.com/47611580/54384234-21db2b00-466a-11e9-87d7-6b5bffe4ab2b.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54610452-71837300-4a2b-11e9-92c7-d25ce518e1ac.png)
