### ISSUE TITLE
Planning-Plat-Final

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#345]
Historic review populating even though historic not checked in details page

![image](https://user-images.githubusercontent.com/4129185/54384672-2d7b2180-466b-11e9-9993-b881f4bcd670.png)

![image](https://user-images.githubusercontent.com/4129185/54384726-4f74a400-466b-11e9-8151-81da83b3c97a.png)

**Comment by dhenry-KCI** [comment]
this is happening across all plat types

**Comment by goggansd** [comment]
Duplicate of issue 332.

**Comment by dhenry-KCI** [comment]
corrected
