### ISSUE TITLE
Planning-Preliminary Plat

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#347]
APFO child is closed but system is still saying APFO not approved.

![image](https://user-images.githubusercontent.com/4129185/54435247-73d18e80-4706-11e9-8d72-94db76e4a7ce.png)

![image](https://user-images.githubusercontent.com/4129185/54435277-82b84100-4706-11e9-8141-5a2028468dcd.png)

MW

**Comment by goggansd** [comment]
@dhenry-KCI, This is because the workflow is looking for a parent application of type APFO, and the test case is using a child application instead. Please advise...

**Comment by megisys** [comment]
Update Language. Needs to be a parent...

**Comment by dhenry-KCI** [comment]
good PP237810
