### ISSUE TITLE
Building - Major Grading - Awaiting Plan Review Payment - Fee Issue

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#348]
The system generated the minor logging fee as part of the fees for this permit. This is not correct

![image](https://user-images.githubusercontent.com/4129185/54435300-8cda3f80-4706-11e9-9f44-530fbab6eb9e.png)

AP # 238859

logged by tiffany martin 3/15/19

**Comment by megisys** [comment]
Retest.. Please

**Comment by dhenry-KCI** [comment]
corrected 3/26/19 tm
