### ISSUE TITLE
Building - Major Grading - Apts/Towns/Condos -  Under Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#349]
For Major Grading Townhouses we previously discussed that no reviews or inspections will populate (inspections did not populate) and the permit will go straight to closure after fees have been paid. There is no other way to differentiate townhouse/apartments/condo permits other than a check box on the grading details page - that could be completed by the applicant. Also, with that they should provide the overall MJ permit number. 

AP # 238859

![image](https://user-images.githubusercontent.com/4129185/54435642-55b85e00-4707-11e9-8ecb-18f1233d6057.png)

logged by tiffany martin 3/15/19

**Comment by dhenry-KCI** [comment]
PWDR needs to be removed as a reviewing agency. Only ECS should populate in case comments are needed regarding the building permit or grading permit associated with this type of application. 

4/2/19

**Comment by megisys** [comment]
Ready

**Comment by dhenry-KCI** [comment]
tiffany martin 4/3/19

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/67977017-965cdd00-fbed-11e9-8911-99c0788db8c3.png)

**Comment by JuanitaMiles** [comment]
Only ECS should populate as a reviewer on these type of permits

**Comment by ABonomo21** [comment]
see note  about only ECS being a reviewer

**Comment by megisys** [comment]
GRADING_PWDR_AOC Formula Removed from GRADING, PWDR Review. New Formula  GRADING_PWDRReview_AOC Attached to PWDR Review

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68424740-9cfdce00-0172-11ea-908d-0bd7322a99f5.png)
