### ISSUE TITLE
Building- Applicant Actions Detail Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#35]
Applicant action detail page, gives the option for an application to select resubmit, save, select, or withdraw. 
![image](https://user-images.githubusercontent.com/4129185/52736469-eb8d8b80-2f97-11e9-9815-759bc44ad0c9.png)

After selecting withdraw it allowed the permit to move to a application finalized on the milestone.
![image](https://user-images.githubusercontent.com/4129185/52736504-ffd18880-2f97-11e9-9364-7ce1952a3c2f.png)

Applicants must get approval to request to"void" an application or a permit, the work has to be verified via a field inspection that it was not completed and if inspection have been performed the applicant cannot get approval for the void request.

If an applicant request a void it needs to be sent over to staff for approval. This would be a staff person with the securities to process a void.

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Removed formula that moved the application to closed if Applicant requests to withdraw. Instead the withdraw log is added and it is up to the user to decide on next steps.

Please screenshot for proof of test (AP#236145 in DEV)
<img width="960" alt="issue35_fixed" src="https://user-images.githubusercontent.com/47784290/53182310-3e35fb80-35c7-11e9-8d80-0e69f741e7b6.png">

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/53971946-e2419b80-40cb-11e9-9e2e-e75b4b8cce6b.png)
