### ISSUE TITLE
PLANNIING - PLAT - ADDITION, OPEN SPACE - HISTORIC review repopulated after approval

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#350]
PL237674
Historic Review resulted as aproved. Populated on 2nd review cycle. AReed
![image](https://user-images.githubusercontent.com/4129185/54435396-c57a1900-4706-11e9-94c9-46983ef585e0.png)

![image](https://user-images.githubusercontent.com/4129185/54435726-7d0f2b00-4707-11e9-82df-3decec3c7da7.png)

**Comment by dhenry-KCI** [comment]
OPEN SPACE PL237688

**Comment by goggansd** [comment]
@megisys, This might be related to the other two issues on PLAT with HISTORIC, but your code to deal with existing reviews of the same type which are already approved did not work in this case. Thinking it may be related to the other issue where I tagged you and documented all the things I've already tried to get HISTORIC reviews to add only when one of the two appropriate checkboxes have been added...

**Comment by megisys** [comment]
Please retest this.. I believe this is working

**Comment by dhenry-KCI** [comment]
duplicate to HISTORIC review repopulating on 2nd review cycle. AReed
