### ISSUE TITLE
PLANNING - PLAT - Recordation email notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#351]
Email notification needs to be sent to the applicant/surveyor/engineer with Date Recorded, Plat Book # and Page # when application closes.

![image](https://user-images.githubusercontent.com/4129185/54436955-f9a30900-4709-11e9-9a8d-ae7a9515b01f.png)

**Comment by megisys** [comment]
This will send once you enter the above details and save

**Comment by dhenry-KCI** [comment]
not receiving the emails

MW

**Comment by megisys** [comment]
Fixed..

**Comment by dhenry-KCI** [comment]
not getting email

MW

**Comment by goggansd** [comment]
@megisys you will need to look at this again. I found an issue in cross-reference between Notification Template setup and Configuration Editor Email node setup and corrected it, but I cannot get the email to generate still.

**Comment by dhenry-KCI** [comment]
fixed-mw

![image](https://user-images.githubusercontent.com/4129185/55408838-d7452400-552e-11e9-9e93-39b0981ffe20.png)
