### ISSUE TITLE
Planning-Plat-HISTORIC review in error - Multiple Plat Types - COMBO, FINAL, CORRECTION, OPEN SPACE

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#352]
Historic populated w/o checking historic on details page

![image](https://user-images.githubusercontent.com/4129185/54437491-1ab82980-470b-11e9-8d33-7aaae1703aff.png)

![image](https://user-images.githubusercontent.com/4129185/54437511-299edc00-470b-11e9-9d7c-1aa6c7414866.png)

**Comment by dhenry-KCI** [comment]
PL237699

**Comment by goggansd** [comment]
Duplicate of issue 332.

**Comment by goggansd** [comment]
Duplicate of issue #332.

**Comment by dhenry-KCI** [comment]
Resolved PL237853 AReed
