### ISSUE TITLE
PLANNING - FRO Exemption

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#355]
"PaperWork Reviewed" milestone prevents FRO exemption application from progressing.
![image](https://user-images.githubusercontent.com/4129185/54439157-a41d2b00-470e-11e9-9345-d5d29b38e8de.png)

**Comment by dhenry-KCI** [comment]
ISSUE RESOLVED

**Comment by dhenry-KCI** [comment]
NOT RESOLVED

**Comment by megisys** [comment]
Please Restest

**Comment by dhenry-KCI** [comment]
RETESTED UNDER F237830.
FIXED.
