### ISSUE TITLE
PLANNING - CORRECTION PLAT - Reviews repopulating in error

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#356]
DUSWM and HISTORIC repopulated. They were approved on 1st review cycle
PL237684

![image](https://user-images.githubusercontent.com/4129185/54440583-62da4a80-4711-11e9-86f8-50c93c999c8b.png)

**Comment by megisys** [comment]
PLease ReTest

**Comment by dhenry-KCI** [comment]
not fixed.  But now DUSWM is also regenerating after being approved on the first review

![image](https://user-images.githubusercontent.com/4129185/54635703-2aad7180-4a5b-11e9-9e7a-edb8cac99e2d.png)

MW

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
fixed per PL238918

MW
