### ISSUE TITLE
Planning-Plat-Road Dedication

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#357]
DRTE should be an Auto Add reviewer on Road Dedication plats.

![image](https://user-images.githubusercontent.com/4129185/54450053-d423f880-4725-11e9-8a9c-fd06df7ec858.png)

MW

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
PL237766 correct AREED
