### ISSUE TITLE
PLANNING - PLAT - PUBLIC TAKING - DUSWM fee incorrect

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#359]
DUSWM Public Taking Plat fee should be $75. AReed

![image](https://user-images.githubusercontent.com/4129185/54450592-2c0f2f00-4727-11e9-8704-3877ed1fa5c2.png)

**Comment by dhenry-KCI** [comment]
fee value is correct but fee didnt generate

![image](https://user-images.githubusercontent.com/4129185/54635277-2b91d380-4a5a-11e9-8727-993d6d6084d8.png)

**Comment by megisys** [comment]
It auto Waived

**Comment by megisys** [comment]
This was another issue causing this.

Dan

**Comment by dhenry-KCI** [comment]
fixed per PL238942

MW
