### ISSUE TITLE
PLANNING - PLAT - PUBLIC TAKING - Add FRO reviewer

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#360]
Add FRO as a reviewer - Always Add
AReed
![image](https://user-images.githubusercontent.com/4129185/54450808-b5befc80-4727-11e9-99a3-761cec0f5081.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
corrected PL237760

**Comment by dhenry-KCI** [comment]
areed
