### ISSUE TITLE
Building - Major Grading - Intake Review - Mitigation Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#361]
After entering the mitigation details, the check mark was selected and the application was created. The approval cannot be something that the applicant can do - only the entry. Dave needs to be able to make changes to the mitigation details and be the "approver."

Logged by tiffany martin 3/15/19

AP # 238880

**Comment by goggansd** [comment]
@megisys not clear on what the issue is here. Please advise...

**Comment by dhenry-KCI** [comment]
this is not quite correct. i am now able to modify and make changes once the applicant submits, however, i can continue to make changes and we do not want that to be the case. once it is approved by us on the back end - it will not change. want to think about this a little more before any changes. 4/4/19

**Comment by megisys** [comment]
Tested with Tiff
