### ISSUE TITLE
Building - Major Grading - Intake Review - PI required

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#362]
The Public Improvement involved box was checked under grading details on the MJ permit but we did not get a redline for a PI permit being linked to this permit. 

![image](https://user-images.githubusercontent.com/4129185/54451134-7e9d1b00-4728-11e9-8a6a-8c67720d9f06.png)

![image](https://user-images.githubusercontent.com/4129185/54451147-8ceb3700-4728-11e9-9149-6972fd923845.png)

AP # 238880/238878

logged by tiffany martin 3/15/19

**Comment by megisys** [comment]
Ready for Testing

**Comment by dhenry-KCI** [comment]
corrected 3/26/19  tm
