### ISSUE TITLE
Planning-Site-ADMCON

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#363]
Public hearing auto populated with hearing date.  We agreed that system would stop on schedule hearing milestone and we would manually enter hearing/date.

![image](https://user-images.githubusercontent.com/4129185/54451250-c6bc3d80-4728-11e9-9537-18540dfdaacc.png)

MW

**Comment by dhenry-KCI** [comment]
this is an issue with all SITE work types

**Comment by megisys** [comment]
Addresssed

**Comment by dhenry-KCI** [comment]
fixed SP237815
MW
