### ISSUE TITLE
Planning-Site-All

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#364]
Paperwork review has too many result options

![image](https://user-images.githubusercontent.com/4129185/54451488-5366fb80-4729-11e9-8d5f-21effb7e2b84.png)

![image](https://user-images.githubusercontent.com/4129185/54451558-742f5100-4729-11e9-9af0-a0f0f4e8d931.png)

MW

**Comment by megisys** [comment]
Resolved
