### ISSUE TITLE
Building - Major Grading (Mass Grade) - Fee Payment

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#365]
The minor logging fee populated in this permit along with the correct fees. Minor logging should not populate

![image](https://user-images.githubusercontent.com/4129185/54452397-70043300-472b-11e9-8ae4-09ef18888afb.png)

AP # 238880

logged by tiffany martin 3/15/19

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
corrected tm 3/26/19
