### ISSUE TITLE
Building - Stormwater Management - Intake Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#367]
The system generated a redline stating must have associated GRADING - Public Improvement Application which is not correct on an SWM permit. This should be a requirement on the MJ permit. 

See item #362 - similar issue

Logged by tiffany martin 3/15/19

![image](https://user-images.githubusercontent.com/4129185/54452782-544d5c80-472c-11e9-8f67-20286b78cec2.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
This has not yet been corrected. The SWM Permit # 240034 still has a redline for a PI - the PI requirement should be under the MJ,

logged tiffany martin 3/26/19

**Comment by goggansd** [comment]
@megisys, either you or @imazlout will need to address this. No idea what an MJ or a PI are or how they are related or what indicates them in IPS.

**Comment by dhenry-KCI** [comment]
This is marked because it is bulk added from the MJ and also if it wasn't bulk added the project does require a public improvements so I think it should still work the same

![image](https://user-images.githubusercontent.com/4129185/55820967-56f06700-5aca-11e9-9649-b62127331175.png)
 
![image](https://user-images.githubusercontent.com/4129185/55820977-61126580-5aca-11e9-975f-171564b499f7.png)

**Comment by megisys** [comment]
System Cant.. If that checkbox is check is how it works

**Comment by dhenry-KCI** [comment]
I GUESS THIS IS OK   TM 4/16/19
