### ISSUE TITLE
R4C/IPS- Configuration of Extension Process Grading Permits (Excel Issue #42)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#369]
Dan needs to configure R4C and IPS to allow for applicants to request extensions on permits and applications- See notes from meeting below.

**Grading Permits:**  
Applicant Actions
Log Extension Request 
Automatically Add Fee - Based on priority code on the permit could have an admin fee in addition to the % calculation based on the current bond amount – this is only for Major Grading and SWM
Minor grading/minor logging - $188.00 – two separate lines of $94.00 each one admin and one inspection 
Major logging – one fee of $414.00
Once the fee is paid the expiration date will generate from the current expiration date

**Comment by calequin** [comment]
part of the November release of r4c will have 3 additional buttons similar to the Request Extension process for rhythm

**Comment by ABonomo21** [comment]
again this is not a nice to have this needs to be worked out - as it was discussed with Dan and Gary and I month and months ago about items that need to be address and extension process for grading needs to be completed @dhenry-KCI

**Comment by dhenry-KCI** [comment]
@ABonomo21 - i should have been more clear on this. We have a process int he short-term where the County will add a log of extension which will allow the application to populate an extension request via Rhtyhm  per dan this is in place. The "nice to have" was a reference to the fact that the Extension button will not be released via R4C until November.

**Comment by dhenry-KCI** [comment]
@megisys - need to configure expireation process for grading permits. These permits would automatically be created.
