### ISSUE TITLE
Building- Solar Panel- Issuance prior to required trade application

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#37]
The solar panel permit issued without an electric permit being attached. The building permit for the solar panel permits should not be issued until the electrical permit has been applied for and then they should both issue at the same time. 2.14.19 AB 

![image](https://user-images.githubusercontent.com/47611580/52797477-fa317c80-3043-11e9-9802-8acbdf7d04a6.png)

**Comment by imazlout** [comment]
Training Needed. Duplicate of #68 and #80.

**Comment by ABonomo21** [comment]
per @ABonomo21 okay to close-AW
