### ISSUE TITLE
Expired Permit Configuration 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#370]
Need to have the system set up to run reports and generate notifications of expired permits - allowing a 90 day grace period for allowing an extension on all permit types. 
#368 #369 #366

**Comment by megisys** [comment]
2 New LogTypes.. EXP30DAYS and EXP90DAYS..  These will send one of 2 notifications.. You can test this.. There will be a nightly job which adds these.

**Comment by ABonomo21** [comment]
30 and 90 day expiration notices are available however I received the error message below when I tried to add the 90 day expiration log to the permit.
![image](https://user-images.githubusercontent.com/47611580/56157141-c49a0880-5f8c-11e9-9336-26ea5fe4ffc7.png)
![image](https://user-images.githubusercontent.com/47611580/56157220-f7dc9780-5f8c-11e9-9e38-e99e7d13cbb1.png)

**Comment by megisys** [comment]
Please Retest

**Comment by ABonomo21** [comment]
fixed-aw
90 days
![image](https://user-images.githubusercontent.com/47611580/56223094-19945800-603b-11e9-82c5-71e5df701df0.png)
![image](https://user-images.githubusercontent.com/47611580/56223082-126d4a00-603b-11e9-88cc-417d996e04ca.png)

30 days
![image](https://user-images.githubusercontent.com/47611580/56223197-4e081400-603b-11e9-888c-8fa70e10e551.png)
![image](https://user-images.githubusercontent.com/47611580/56223174-45afd900-603b-11e9-8eac-85bba317f311.png)
