### ISSUE TITLE
Building - Public Improvements - Intake Review - Linkage Issues

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#373]
The SWM and PI permits should listed as children to the MJ..

The PI permit should list the MJ as the parent.

The SWM permit should list the MJ as the parent.

**Comment by megisys** [comment]
What is the Issue.. Why not associate them this way ?

**Comment by dhenry-KCI** [comment]
ok 4/16/19
