### ISSUE TITLE
Planning-Site Plan-ALL

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#374]
denied signature and went to closed/finalized.  Same case where PC was denied and it stage progressed. when a project is denied there should be different language other than "finalized"

![image](https://user-images.githubusercontent.com/4129185/54454816-b1e3a800-4730-11e9-94aa-f4488125fad1.png)

MW

**Comment by megisys** [comment]
PLease Retest

**Comment by dhenry-KCI** [comment]
works SP237758

MW
