### ISSUE TITLE
Building - Major Grading/SWM - Bond Track - Bond Transaction

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#375]
For a deposit the close date would not be a required field. The only time that we will complete the close date is when a release is taking place. THIS PREVIOUSLY WASN'T LIKE THIS....

![image](https://user-images.githubusercontent.com/4129185/54455086-51a13600-4731-11e9-979d-1575ad312747.png)

BT-4926

LOGGED BY TIFFANY MARTIN 3/15/19

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
corrected 3.26.19 tm
