### ISSUE TITLE
Planning-Site-ALL

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#376]
fees generating and require payment when CIP box is checked in details.  Fees should populate and auto waive.

![image](https://user-images.githubusercontent.com/4129185/54455176-86ad8880-4731-11e9-9816-0a732ed9c0f7.png)

![image](https://user-images.githubusercontent.com/4129185/54455214-9d53df80-4731-11e9-85a2-0fba13e337ca.png)

MW

**Comment by megisys** [comment]
Ready for Retest

**Comment by dhenry-KCI** [comment]
ok per SP237801

MW
