### ISSUE TITLE
Building - SWM - Awaiting Plan Review Payment - Fees incorrect

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#378]
The Minor logging permit fee populated on a SWM permit. This should be happen. 

![image](https://user-images.githubusercontent.com/4129185/54455277-d0966e80-4731-11e9-8cb8-b02af9055958.png)
 

AP # 238883

tiffany martin 3/15/19

**Comment by goggansd** [comment]
Fixed in IPSTest - altered add on condition for minor logging fee

![image](https://user-images.githubusercontent.com/28841997/55244078-d5b9ea00-5216-11e9-9ff5-5acdf458bf3e.png)

**Comment by goggansd** [comment]
Please retest...

**Comment by dhenry-KCI** [comment]
corrected tm 4/16/19
