### ISSUE TITLE
Building- ResUse- Review Population

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#38]
Permit #237149-alteration permit
The DUSWMF review generated on this res use alteration permit when it shouldn’t. this review would never be applicable to a res use permit.
![image](https://user-images.githubusercontent.com/47611580/52797633-411f7200-3044-11e9-98ae-e22ac75b0ccd.png)

**Comment by dhenry-KCI** [comment]
DUSWM reveiw incorrectly generated on a deck permit (property is on public water). DUSWM reviews should not generate on a deck permit.

AP237144
Logged by A. White

 
![image](https://user-images.githubusercontent.com/4129185/53026762-8cb19180-3431-11e9-9b7f-c9d96378e866.png)

**Comment by imazlout** [comment]
Duplicate of #36. Sent an email to @ABonomo21 and awaiting response

**Comment by ABonomo21** [comment]
fixed-AW-(this was not a duplicate of #36)


![image](https://user-images.githubusercontent.com/47611580/55736663-c181a400-59f1-11e9-90fd-8b5c9001ccb0.png)
