### ISSUE TITLE
Building - SWM - 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#380]
The partial as-built inspection should not populate with the pre-con meeting. That inspection should populate after the pre-con has passed.

![image](https://user-images.githubusercontent.com/4129185/54455397-14897380-4732-11e9-9110-67811ee95815.png)

AP # 238883

logged by tiffany martin 3/15/19

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
corrected 4/16*/19 tm ep
