### ISSUE TITLE
Building - Grading Permits - Inspections Milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#381]
Compliance inspections that get resulted as partial passed should either show as partial passed as the result code or be a result option. However, after the first inspection was resulted as partial passed, the reinspection has a partial passed result option. This should be a result option initially. 

![image](https://user-images.githubusercontent.com/4129185/54455837-1c95e300-4733-11e9-9754-918e53e0a471.png)

AP # 238880
 
logged by tiffany martin 3/15/19

**Comment by megisys** [comment]
ReTest. Expired Partial Past

**Comment by dhenry-KCI** [comment]
I guess this is ok tm 4/2/19
