### ISSUE TITLE
Electrical Trade Lic- Category Removal

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#382]
Electrical General by Exam needs to be removed from the category. 

Only options should be Electrical General, Electrical Limited and Electrical Restricted. 

![image](https://user-images.githubusercontent.com/47611580/54456070-a47bed00-4733-11e9-8825-273bf8576e9e.png)

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54708268-67d83900-4b19-11e9-998b-9a4fb4913752.png)
