### ISSUE TITLE
Electrical Trade License Type Removal

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#383]
Electrical Limited License Type needs to be removed 

![image](https://user-images.githubusercontent.com/47611580/54456135-cd03e700-4733-11e9-8c75-4265d96363c9.png)

**Comment by megisys** [comment]
Huh ?

**Comment by goggansd** [comment]
Not enough information. Which AP Type is this for?

**Comment by megisys** [comment]
ELEC

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
Testing Failed-AW
![image](https://user-images.githubusercontent.com/47611580/54708582-0d8ba800-4b1a-11e9-834b-3fa398eed83d.png)

**Comment by megisys** [comment]
Where are you seeing this. Which LICENSE type ?

**Comment by ABonomo21** [comment]
This issue is not resolve --- please fix ! 
![image](https://user-images.githubusercontent.com/47611580/55026654-d580db00-4fd9-11e9-9ea4-2b462af6eb03.png)

**Comment by megisys** [comment]
DONE !!! LOL Sorry

**Comment by ABonomo21** [comment]
confirmed removal - good job Dan
