### ISSUE TITLE
Planning-Site- Concept

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#384]
health fee did not populate (which is fine because this is a DUSWM/public water/sewer site) but a review generated.  Health should be a conditional add if not on public water and sewer.

![image](https://user-images.githubusercontent.com/4129185/54456189-f15fc380-4733-11e9-9365-631224dc405c.png)

![image](https://user-images.githubusercontent.com/4129185/54456203-fb81c200-4733-11e9-8576-3e08cbd399c7.png)

![image](https://user-images.githubusercontent.com/4129185/54456251-12281900-4734-11e9-97ff-e97d3a4918b1.png)

MW

**Comment by megisys** [comment]
Issue Addressed

**Comment by dhenry-KCI** [comment]
fixed.  SP237747

MW
