### ISSUE TITLE
Electrical Trade License- Electrical Detail Information

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#385]
This electrical detail information page needs to be made available for entry prior to submission of the electrical license. 

![image](https://user-images.githubusercontent.com/47611580/54456269-223ff880-4734-11e9-87e2-67c65969409c.png)

Currently when processing a new license or a renewal only the license detail page is populating. 

![image](https://user-images.githubusercontent.com/47611580/54456317-3a177c80-4734-11e9-81b4-4d4033fda607.png)

**Comment by megisys** [comment]
resolved

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54708395-aec62e80-4b19-11e9-81f8-a350ccfbc4b4.png)
