### ISSUE TITLE
Residential Building Townhomes: Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#386]
RESBUILD New RESTOWM; On the details page, it is missing the section that asks if this permit is the parent, how many townhouses are in the row, and if it is a blanket which we need to be able to completely process a row of townhouses. -MCoffman

![image](https://user-images.githubusercontent.com/47611580/54456469-b0b47a00-4734-11e9-84b2-1fcf9b910660.png)

![image](https://user-images.githubusercontent.com/47611580/54456298-3257d800-4734-11e9-8aa6-dd0075c07b59.png)

![image](https://user-images.githubusercontent.com/47611580/54456457-a5614e80-4734-11e9-984a-c32a1e6236d1.png)

**Comment by megisys** [comment]
@ABonomo21  - We did the redesign.. Thoughts

**Comment by ABonomo21** [comment]
When we did the redesign, the detail page based on occupancy type should populate. For this one it the townhouse detail page with the details above should populate.

**Comment by goggansd** [comment]
Could not replicate in IPSTest using same information from screenshots (see below). Presumably, this has been fixed by someone else. Please retest to verify...

![image](https://user-images.githubusercontent.com/28841997/55241801-44487900-5212-11e9-8145-4d30cfdca852.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55504270-7d238c00-561e-11e9-9cbb-a3a47c57617f.png)
