### ISSUE TITLE
Building - Major Grading - Bond Release Milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#387]
We created one bond track - 4927 and linked it to two different permits - MJ & SWM 238880 & 238883. We released the bond for the MJ - 238880 in full but the major grading permit states that the total bond balance must be 0 - however the bond balance is 0 for the mj permit.

![image](https://user-images.githubusercontent.com/4129185/54456517-db9ece00-4734-11e9-952b-ae68982b48ab.png)

AP # 238880 & # 238883

logged by tiffany martin 3/15/19

**Comment by megisys** [comment]
I cant fix this issue.. When this happens you will need to supervisor override these one..s

**Comment by dhenry-KCI** [comment]
OK TM 4/16/19
