### ISSUE TITLE
Planning-Site- Residential Cluster

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#388]
Fees are wrong- SP237715   

Planning fee didnt populate, should be 1173.00
two strange $1.00 fees populated
PWDR fee did not populate, should be $141

The health fee and OLS fee are correct.

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
same problems, only now health fee didnt populate


![image](https://user-images.githubusercontent.com/4129185/54632337-3cd7e180-4a54-11e9-9667-952a8573d58b.png)
