### ISSUE TITLE
Residential Building Condo- Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#389]
RESBUILD New RESCON; On the details page, it is missing the section that asks if this permit is the parent structure, how many units there are, and if it is a blanket which we need to be able to completely process a condo building. -MCoffman

![image](https://user-images.githubusercontent.com/47611580/54457069-cb87ee00-4736-11e9-9f94-2eab75ee8991.png)

![image](https://user-images.githubusercontent.com/47611580/54456997-94194180-4736-11e9-9e58-38668aabd1f3.png)

![image](https://user-images.githubusercontent.com/47611580/54457119-fa05c900-4736-11e9-9628-5105d91a91ee.png)

**Comment by megisys** [comment]
Addressed this

**Comment by ABonomo21** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54690204-436b6500-4af7-11e9-80e3-7643cfb23fdc.png)
