### ISSUE TITLE
Building- Solar Permit- Review Population

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#39]
Solar Panel Permit #237146
DUSWMF review generated when it shouldn’t. On a minor permit only the building review and in this case (since the property is within the town of Emmitsburg) the town review should generate.
![image](https://user-images.githubusercontent.com/47611580/52797823-ad9a7100-3044-11e9-8434-4ba108d65aaa.png)

**Comment by imazlout** [comment]
Duplicate of #36. Sent an email to @ABonomo21 and awaiting response

**Comment by ABonomo21** [comment]
Issue Corrected-MCoffman

Permit# 240249
![image](https://user-images.githubusercontent.com/47611580/55806577-898c6680-5aae-11e9-8fca-251df5e8edac.png)
