### ISSUE TITLE
Planning-site plan-residential cluster

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#390]
incorrect fees populated.

DUSWM=$104
DPZ=1173
PWDR= 141

OLS is correct as is.

![image](https://user-images.githubusercontent.com/4129185/54532591-78907f80-495e-11e9-98b0-616961a354a1.png)

**Comment by dhenry-KCI** [comment]
MW

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
now none of these fees are generating.

![image](https://user-images.githubusercontent.com/4129185/54632136-cd61f200-4a53-11e9-9cf6-4d862eaf4221.png)
MW

**Comment by megisys** [comment]
This is a residential cluster.. These fees always came up for a residential cluster.. Are you syaing they shouldn't. Please provide a Hansen 7 v v ersion

**Comment by dhenry-KCI** [comment]
we need fees. Looks like you need to add DUSWM fee of $104 to resolve this github issue.

MW

**Comment by megisys** [comment]
DONE ! :)

**Comment by dhenry-KCI** [comment]
fixed per SP239049   MW
