### ISSUE TITLE
planning-site plan-site plan type I

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#391]
remove the word "initial" be removed from Office of Life Safety and DUSWM fee description?

![image](https://user-images.githubusercontent.com/4129185/54533522-c312fb80-4960-11e9-92e4-f034be275492.png)

MW

**Comment by megisys** [comment]
resolved

**Comment by dhenry-KCI** [comment]
Remove Initial, see highlight - Areed
![image](https://user-images.githubusercontent.com/4129185/54698772-40c43c00-4b06-11e9-91e5-d813e73f87f8.png)

**Comment by megisys** [comment]
This can not be fixed.. Will cause a larger issue.. Can fix AFTER Go LIve/

**Comment by megisys** [comment]
To be done AFTER GO LIVE. If done sooner will cause it to be readded

**Comment by dhenry-KCI** [comment]
Closing as a duplicate of
