### ISSUE TITLE
PLANNING - SITE PLAN TYPE III - HEARING Auto generated in error

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#393]
Hearing auto populated with schedule date. Hearing will never be associated to a SITE plan Type III. However, to remain consistent across Site Plan types, process should be held at hearing milestone until Hearing is manually added.
![image](https://user-images.githubusercontent.com/4129185/54534033-e4281c00-4961-11e9-82ed-9aa870150023.png)

**Comment by dhenry-KCI** [comment]
areed

**Comment by megisys** [comment]
Addressed this

**Comment by dhenry-KCI** [comment]
fixed bu Dan on site 3/18/19 SP237739
