### ISSUE TITLE
Planning-site-site plan type I

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#394]
first review cycle needs to generate a 3 week review.  System generated a 2 week review, and for some reason DRTE was given only a 1 week review

![image](https://user-images.githubusercontent.com/4129185/54536150-834f1280-4966-11e9-8dc8-b8657f547ccc.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
fixed per SP238939

MW
