### ISSUE TITLE
PLANNING - SITE PLAN - Review Time Frame

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#395]
Site PlanType III review Due Date should be 1 week. ALL Signature Sets for site plans should have a Due Date of 1 week.
![image](https://user-images.githubusercontent.com/4129185/54536127-7af6d780-4966-11e9-8565-e88509a6e3da.png)

**Comment by megisys** [comment]
Ready for Retest

**Comment by dhenry-KCI** [comment]
type III- fixed

Type II- review dates good, but signature review date needs to change from 2 weeks to 1 week

Type I- initial review period is populating as 4 weeks and 1 day.  Needs to be 3 weeks.  
Second review period is correct at 2 weeks.  
Signature set review is correct at 1 week

MW

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
type II still generating a two week signature set review...should be 1 week
![image](https://user-images.githubusercontent.com/4129185/55026787-18db4980-4fda-11e9-95d0-ccc123b0d526.png)

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
still generating a two week signature review.  needs to be 1 week

![image](https://user-images.githubusercontent.com/4129185/55410098-47ed4000-5531-11e9-907e-97c364e0d2e1.png)

**Comment by megisys** [comment]
Change Made

**Comment by dhenry-KCI** [comment]
fixed per SP239048   MW
