### ISSUE TITLE
PLANNING - SITE - SKETCH - Reviewers

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#399]
DUSWM is missing. Health should not have populated-parcel is public water/sewer. Missing Street Name review
![image](https://user-images.githubusercontent.com/4129185/54537472-ea6dc680-4968-11e9-9060-ff349a2e535f.png)
![image](https://user-images.githubusercontent.com/4129185/54538026-e5f5dd80-4969-11e9-85dd-9d985057a74f.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
not fixed.  Health didnt populate but neither did DUSWM

![image](https://user-images.githubusercontent.com/4129185/54557451-8dd2d180-4991-11e9-8cf3-01b629ae7330.png)


![image](https://user-images.githubusercontent.com/4129185/54557432-83b0d300-4991-11e9-98cd-3ae70513b01c.png)

MW

**Comment by megisys** [comment]
SKETCH never had STRNAME - this is the matrix we worked on together..  I added to Sketch..  Also DUSWM has a manual add.. Why have we changed our matrix  ? @dhenry-KCI

**Comment by dhenry-KCI** [comment]
street added.  DUSWM is not a manual add, its a conditional add, but appears it was programmed this way.  Issues fixed per SP238923

MW
