### ISSUE TITLE
Building- All Permits- Finalization of Permits prior to Trades being Final

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#40]
This is a problem occurring on ALL a/p types where the building permits are able to be made final and closed out prior to the trade permits being completed and final. While this example specifically shows the building permit for solar panels being final prior to the electrical trade permit being final, it needs to be address on ALL a/p's. 

The building permit for the solar panels closed and finalized without the electrical permit having its final inspection. Building permit #237146 and Electrical permit #237147

![image](https://user-images.githubusercontent.com/47611580/52797973-0407af80-3045-11e9-8a0f-13fc1a508d50.png)

**Comment by imazlout** [comment]
Duplicate of #80 and #68

**Comment by ABonomo21** [comment]
Agreed- We need to make sure staff is trained to know that inspections should be scheduled prior to being resulted.
This will affect inspectors using mobile and administrative staff using the back office (in the event and inspection is requested at the customer service counter, email or phone) when this project goes live- in the future all inspection request should be submitted via the portal.
