### ISSUE TITLE
PLANNING - Site Plan - Concept Fees 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#400]
Only 1 $75 health fee should populate on Sketch Plan. Remove Health Site Plan Reveiw Fee - Initial. 
Areed

![image](https://user-images.githubusercontent.com/4129185/54540217-f90aac80-496d-11e9-88bc-d8a3959a40f5.png)
![image](https://user-images.githubusercontent.com/4129185/54540261-0b84e600-496e-11e9-93c5-8d3d74ced89a.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
resolved MW SP237745
