### ISSUE TITLE
R4C Verify - comments not showing on R4C

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#402]
VP237727 - resubmit requested and Craig could not see comments on R4C side
AReed

![image](https://user-images.githubusercontent.com/4129185/54541387-3708d000-4970-11e9-9969-004fb2057143.png)

**Comment by megisys** [comment]
IT is under the review itself. IT is above the details of the review

**Comment by JuanitaMiles** [comment]
Dan and I tested together, I was able to see the comments of the review. This was user error on both Juanita and Craig's part. The review must be clicked on to view the comments.

Closing the issue.
