### ISSUE TITLE
R4C - VERIFY - RESUBMITTAL

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#403]
Resubmittal processed in R4C - did not progress out of milestone Awaiting Applicant Resubmit.

![image](https://user-images.githubusercontent.com/4129185/54542711-b3041780-4972-11e9-884a-2f155cc79478.png)

**Comment by megisys** [comment]
Please Retest

**Comment by dhenry-KCI** [comment]
Craig was not able to process a resubmission on R4C under VP237811

![image](https://user-images.githubusercontent.com/4129185/54634656-0c467680-4a59-11e9-8825-f11b6fe5fff7.png)
![image](https://user-images.githubusercontent.com/4129185/54634734-313ae980-4a59-11e9-9b0b-aaed4362369c.png)

**Comment by megisys** [comment]
This is working SEE - VP237811
