### ISSUE TITLE
Building - SWM/PI - Issuance

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#404]
When a MJ, SWM and PI are associated together - the SWM and/or PI permit cannot be issued prior to the MJ permit.

AP # 238880/238883/238884

logged by tiffany martin 3/18/19

**Comment by megisys** [comment]
I need to know which are children of which and on what permit please.

Dan

**Comment by dhenry-KCI** [comment]
The SWM and PI should be the children. 

tm 4/2/19

**Comment by megisys** [comment]
Please test

**Comment by dhenry-KCI** [comment]
The MJ 240418 was not issued it was under review and the PI 240410 went to inspections prior to the MJ being approved/issued. 

THE issuance of the swm and pi must be contingent on the MJ issuance. This should happen simultaneously. 

Swm 240414

tm 4/16/19

**Comment by ABonomo21** [comment]
This corrected. 

5/2/19EP
