### ISSUE TITLE
Building - PI - Intake Review - SWM Application must be attached

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#405]
Under intake review, it is redlining us for SWM application must be attached, however, it's already attached.

AP # 238884

![image](https://user-images.githubusercontent.com/4129185/54550778-139b5080-4983-11e9-8656-310246ae71cd.png)

![image](https://user-images.githubusercontent.com/4129185/54550856-3463a600-4983-11e9-8ce5-343b1aca4106.png)

Logged by tiffany martin 3/18/19

**Comment by megisys** [comment]
Please REtest -

**Comment by dhenry-KCI** [comment]
corrected tm 4/16/19
