### ISSUE TITLE
Building - Public Improvement - Awaiting Plan Review Payment

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#406]
Minor Logging fee should not populate on a PI permit.

![image](https://user-images.githubusercontent.com/4129185/54551152-e307e680-4983-11e9-99e3-3c1668a99e62.png)

AP # 238884

logged by tiffany martin 3/18/19

**Comment by megisys** [comment]
Fixed please Retest

**Comment by dhenry-KCI** [comment]
this still has not been corrected - no fees are populating at all now

tm 4/16/19

**Comment by dhenry-KCI** [comment]
corrected tm 5/2/19
