### ISSUE TITLE
Building - PI - Pending Certificate 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#407]
This is not a requirement. The certrev is not needed. Their certificate is the release of their funds.

![image](https://user-images.githubusercontent.com/4129185/54552259-151a4800-4986-11e9-9822-da1d7677db12.png)

AP # 238884

logged by tiffany martin 3/18/19

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
certrev is still populating under review however, under condition it is not populating anymore (which is correct)

tm 4/16/19

**Comment by dhenry-KCI** [comment]
corrected tm 5/2/19
