### ISSUE TITLE
R4C Testing- Tank Permit- Case on a property

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#408]
Unable to process a completeness check re submission due to a case on the property. 
Had to insert the bypass case log to be able to select resubmit. We need the to be able to select resubmit without bypassing the case because when the applicant resubmitted we need to add any working without permit fees and have the case notification 

![image](https://user-images.githubusercontent.com/47611580/54552497-95d94400-4986-11e9-842b-9ba14464be93.png)

![image](https://user-images.githubusercontent.com/47611580/54552509-996ccb00-4986-11e9-9171-45da140e2ab0.png)

**Comment by megisys** [comment]
Ready For Retest

**Comment by ABonomo21** [comment]
fixed
