### ISSUE TITLE
R4C-Application submission without a site property 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#409]
Should not have allowed applicant to submit an application without a site added

![image](https://user-images.githubusercontent.com/47611580/54552798-4a736580-4987-11e9-992d-22ad8f7a94eb.png)

Related to #408

**Comment by calequin** [comment]
This was fixed with the custom validation formula which prompts the user to search and add an address in order to progress. Please Retest

**Comment by ABonomo21** [comment]
seems to be requiring addresses for a/p types will recheck as new a/p types are added.
