### ISSUE TITLE
Building- All ResUse, ResBldg, NonRes, Trailer, Signs, Tanks and Demo- COO and COC

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#41]
All resuse, resbldg, nonres, trailer, signs, tank and demo permits need to stop in the pending certificate milestones to allow for administrative review prior to issuance of either the certificate of occupancy or certificate of completion, depending on a/p type and work type. Currently the system skips over these milestones and goes to closed milestone. 

![image](https://user-images.githubusercontent.com/47611580/52802179-6b296200-304d-11e9-8c51-a099bfe330f6.png)

**Comment by imazlout** [comment]
Sent email to @ABonomo21 to confirm list, since original list didn't have Signs and Demo as ones that require this review.

**Comment by dhenry-KCI** [comment]
Signs and Demo should be included in this list.

**Comment by imazlout** [comment]
Ready for test once changes are move to TEST Environment
Change made as part of effort on #69. I added CERTREV on the Final Inspection milestone for Signs and DEMO since they don't have a pending certificate milestone

**Comment by ABonomo21** [comment]
Issue closed under duplicate issue #69  -MCoffman
