### ISSUE TITLE
Sign Permit - log entry required

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#410]
Sign permit # 238896- stopping me for a BLDGAPP (building application required) log needing to be added at completeness check- application submitted via R4C 

![image](https://user-images.githubusercontent.com/47611580/54552933-91f9f180-4987-11e9-913f-f11d426f69e4.png)

**Comment by megisys** [comment]
Training Issue

**Comment by ABonomo21** [comment]
Added comments to milestone in sign permit to explain to staff what is needed for this log entry - marked as a training issue.
