### ISSUE TITLE
Home Occupation - Impact/ No Impact 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#411]
Impact was already generated at completeness check- where was that selection made on R4C ??Should be back office only for staff to select during completeness check review 

![image](https://user-images.githubusercontent.com/47611580/54553243-23696380-4988-11e9-92d2-2c48421cec5d.png)

**Comment by ABonomo21** [comment]
On R4C the system is asking the applicant to fill in these details with the comment back office only... 
![image](https://user-images.githubusercontent.com/47611580/54555360-ece21780-498c-11e9-915f-13818e0e2b85.png)

**Comment by megisys** [comment]
This is addressed

**Comment by ABonomo21** [comment]
confirmed fix on IPS side
