### ISSUE TITLE
Building - FRO - Awaiting Plan Review Payment 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#412]
The fee for this is higher than it should be. I have attached the fee calculation. The fee for this populated as $1,283.00 but should have been $898.00

![image](https://user-images.githubusercontent.com/4129185/54554672-624ce880-498b-11e9-9e76-d46412cab3bc.png)

AP # 238909

logged by tiffany martin 3/18/19

**Comment by megisys** [comment]
Resvolded

**Comment by dhenry-KCI** [comment]
seems to have been corrected 4/4/19 tm
