### ISSUE TITLE
Home Occupancy Permit- Detail Page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#413]
Home occupancy permit is being held up for home occupancy detail page to be completed at the completeness check milestone- there is no more home occupancy detail page no longer exist. It was removed when we created the new intake detail page. 

![image](https://user-images.githubusercontent.com/47611580/54554674-62e57f00-498b-11e9-87e7-99bb0c20a7d6.png)

**Comment by megisys** [comment]
Retest

**Comment by ABonomo21** [comment]
Fixed
