### ISSUE TITLE
R4C - Trailer Permit 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#415]
No direction on am or pm time frame or Temporary or Permanent in R4C 

![image](https://user-images.githubusercontent.com/47611580/54555092-64fc0d80-498c-11e9-8178-f38483b79260.png)

**Comment by megisys** [comment]
Ready for TEst

**Comment by ABonomo21** [comment]
not available in R4C to Retest. 

![image](https://user-images.githubusercontent.com/47611580/56831761-030aaf80-6838-11e9-9245-a6e986b5e084.png)

**Comment by ABonomo21** [comment]
Still not corrected. 
![image](https://user-images.githubusercontent.com/47611580/56966458-292c9a00-6b2d-11e9-8e0f-bad777f7b168.png)

**Comment by ABonomo21** [comment]
linked to #423

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57002365-daaee800-6b8c-11e9-9db8-d13f60d0c5bb.png)

**Comment by ABonomo21** [comment]
Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/57034608-fb734e00-6c1d-11e9-8a49-5bb8fac992f5.png)
