### ISSUE TITLE
Residention Building Permit-Impact Fee Offset

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#417]
RESBUILD; When the property is within a subdivision that has a offset a negative fee should generate. This example is of a Single Family Dwelling in the Linton at Ballenger Creek Subdivision (subdivision code S1128 section 4). The Permit number is 238908. There is also a separate offset that would generate for Townhomes in this subdivision.-MCoffman

Right now the offset does not generate, and if you try to insert it its generates as a $1.00 fee
![image](https://user-images.githubusercontent.com/47611580/54554842-d5eef580-498b-11e9-9d19-6cd142fea7d1.png)
![image](https://user-images.githubusercontent.com/47611580/54554907-fc149580-498b-11e9-81c6-93108f236fef.png)
![image](https://user-images.githubusercontent.com/47611580/54554965-1a7a9100-498c-11e9-9b66-c427a64fa1cb.png)

This is how the offset currently generates in Hansen7
![image](https://user-images.githubusercontent.com/47611580/54555072-557cc480-498c-11e9-9fa4-d663050fd823.png)

**Comment by megisys** [comment]
IPS 11 Does not allow Negative Fees... Can we not adjust the fee down if in this subdivision. Manual Process. Small number of these in Reality ? Lets Talk

**Comment by ABonomo21** [comment]
There are 3 lots that require permits for this Offset of the Impact fees. We will manually waive the difference. 

Okay per AB/ GH - marked as a training issue
