### ISSUE TITLE
Planning-Plat-Preliminary Plat

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#418]
the "pud or MXD Phase III" fee description should be the DUSWM fee. Ive nefer seen this PUD/MXD fee before

![image](https://user-images.githubusercontent.com/4129185/54555466-329ee000-498d-11e9-9171-7bf537a6526c.png)

MW

**Comment by megisys** [comment]
Completed

**Comment by dhenry-KCI** [comment]
fixed MW/AR
