### ISSUE TITLE
Home Occupation - Detail page change

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#420]
Can we add in the goods and services section, a freeform for how goods will be sold? It is important for us to capture if product will be sold on site or internet sales

![image](https://user-images.githubusercontent.com/47611580/54611848-1f901c80-4a2e-11e9-9f1e-68eb749f48cb.png)

**Comment by megisys** [comment]
Completed

**Comment by dhenry-KCI** [comment]
please create a drop down grid under "Where Sold" to select "in home" or "internet"

Create drop down grid under "Goods or Services" to select "goods" or "services

![image](https://user-images.githubusercontent.com/4129185/54711043-66aa0a80-4b1f-11e9-9efb-369a84856a1b.png)

MW

**Comment by kellyjj** [comment]
Created two code def tables   InforClient.AgencyCDR.Use.GoodServiceCDL and InforClient.AgencyCDR.Use.WhereSold

on the table InforClient.AgencyCDR.Use.HomeGrd  added 2 columns   GoodServiceCDL (GOODSERVICECDL)  ,  WhereSoldCDL (WHERESOLDCDL)

I changed the bind on the grid to point to new columns.  

ready for retest

**Comment by ABonomo21** [comment]
confirmed fix
