### ISSUE TITLE
Yard Modification - Detail Page Change 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#421]
Front Yard

![image](https://user-images.githubusercontent.com/47611580/54611977-6251f480-4a2e-11e9-877d-583a8c28d0ea.png)

 
Center Line from the Road- Front yard
Average Depth in feet 
House (A) Address _______________ measures _______ feet from the centerline of the road to the face of the dwelling. (B) Address _______________ measures _______ feet from the centerline of the road to the face of the dwelling. The applicant’s existing / proposed dwelling measures __________ feet from the centerline of the road to the face of the dwelling. The average depth of the total distance of House (A) _________feet and House (B) _________feet from the centerline of the road is ___________ feet (A+B/2).

Rear Yard & Side Yard:
Point (A) measures _______ feet from the corner wall of the structure to the property line. Point (B) measures _______ feet from the corner wall of the structure to the property line. The average of the Total distance of Point (A) _____ and Point (B) _____ from the property line is ___________ feet.

Would like update two detail pages for the three different work types. 
Is it possible to set up the detail pages in the format above?

**Comment by megisys** [comment]
No it is not.. You have no option to layout fields in Rthym for civics.. Best to layout this in Portal Insturctions like the SOP's

**Comment by ABonomo21** [comment]
Kelly J Please update this detail page - thanks

**Comment by kellyjj** [comment]
what specifically do you want?

do you want the text just put on the detail page?   Do you need columns added for data entry.

I am not clear on the change being asked for.

**Comment by megisys** [comment]
This can not be done.. KellyJ has no silver bullet for R4C :)

**Comment by dhenry-KCI** [comment]
added SOPs in R4C and IPS back office.

MW
