### ISSUE TITLE
USe- Land Use - Detail Page Change 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#422]
![image](https://user-images.githubusercontent.com/47611580/54612038-87defe00-4a2e-11e9-97d2-d6bb1b6fa13b.png)

Need to be able to capture the date of the event and hours of operation
Need the dimensions of the temporary structure

**Comment by megisys** [comment]
Can we not make it a submital requirement they attach operating hours ? Also we never have in Hansen 7 had dimensions of Temporary Structure ?

**Comment by dhenry-KCI** [comment]
Move start/end date from Job Description to Details
![image](https://user-images.githubusercontent.com/4129185/54710479-29914880-4b1e-11e9-87c9-9f3469ca32e3.png)

H7 has sqft field for temp structures.  Please add a dimension field to details tab as discussed.

MW

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
need a field for the dimensions.... 
![image](https://user-images.githubusercontent.com/47611580/55579954-7280f980-56e7-11e9-8590-9fde1ff00699.png)

**Comment by kellyjj** [comment]
I have added the control to the detail page.  I have also added the column SiteDimensions ot the table AgencyCDR.Use.LandDetail  

![image](https://user-images.githubusercontent.com/27238685/55654616-bf77d500-57a6-11e9-99b9-03f2dda50254.png)

**Comment by ABonomo21** [comment]
corrected
