### ISSUE TITLE
R4C-Trailer- Detail Page Change

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#423]
![image](https://user-images.githubusercontent.com/47611580/54612216-ea37fe80-4a2e-11e9-8096-90b2537e3438.png)

Agreement Rec’d needs to be a back office only field and should be listed in the submittal requirements if portable facilities are being used

**Comment by megisys** [comment]
This is Resolved

**Comment by ABonomo21** [comment]
not available in R4C to retest 

![image](https://user-images.githubusercontent.com/47611580/56831798-20d81480-6838-11e9-98fa-d5b0662d47a6.png)

**Comment by ABonomo21** [comment]
back office issue corrected
