### ISSUE TITLE
Gaming - Detail Page Change 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#424]
![image](https://user-images.githubusercontent.com/47611580/54612339-266b5f00-4a2f-11e9-8a6d-9b8b50040b9f.png)

**Comment by kellyjj** [comment]
Added Cate (CATE) CDL,  IrsTax (IRSTAX) CDL, IrsDetLtr (IRSDETLTR) check box, ByLaws (BYLAWS) check box to the table InforClient.AgencyCDR.Use.GamingRequiredDoc

**Comment by kellyjj** [comment]
detail page will now have the fields available.

**Comment by kellyjj** [comment]
Can not generate r4c until enhancements are synced since columns were added.

setting to retest

**Comment by megisys** [comment]
Generated Detail Page

**Comment by ABonomo21** [comment]
looks good- except can you capitalize the "s" in IRS

![image](https://user-images.githubusercontent.com/47611580/55633024-88df9180-5789-11e9-8705-aa758a175d01.png)

**Comment by ABonomo21** [comment]
Fixed
