### ISSUE TITLE
Zoning Certificate- Detail Page Change 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#426]
![image](https://user-images.githubusercontent.com/47611580/54612515-7a764380-4a2f-11e9-8695-cbcb0cee43a9.png)

**Comment by kellyjj** [comment]
this has been done.   and seems ready for r4c

**Comment by kellyjj** [comment]
since detail page name did not change, no need to update formulas

**Comment by kellyjj** [comment]
successfully generated page for r4c.   setting to retest

![image](https://user-images.githubusercontent.com/27238685/55365047-ddd48c80-5497-11e9-825f-96959337fb71.png)

**Comment by ABonomo21** [comment]
I don't see any changes on the detail page-AW
![image](https://user-images.githubusercontent.com/47611580/55737211-c72bb980-59f2-11e9-987e-fab3b5cc3089.png)

**Comment by megisys** [comment]
InforClient.AgencyCDR.BuildingApplet.BuildingDetail 

We need a zoning version of this detail page for zoning with the above changes please

**Comment by kellyjj** [comment]
I have created the detail page InforClient.AgencyCDR.BuildingApplet.BuildingDetailZoneCert based on trhe above detail page.

**Comment by megisys** [comment]
Please Retest

**Comment by ABonomo21** [comment]
Missing the following fields - 

**Total Impervious Area**: under the Site information

![image](https://user-images.githubusercontent.com/47611580/55829587-01718580-5add-11e9-8b96-4391e5484fd7.png)

Total **gross floor area** should not have the word altered

**Comment by ABonomo21** [comment]
corrected
