### ISSUE TITLE
Non-Res Detail Page Change 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#429]
![image](https://user-images.githubusercontent.com/47611580/54612814-025c4d80-4a30-11e9-9cf4-2d23049cf84b.png)

![image](https://user-images.githubusercontent.com/47611580/54612856-1738e100-4a30-11e9-95e9-0d02262c6eb8.png)

**Comment by kellyjj** [comment]
I have made the changes in hansen for this detail page.  it is called Non Residential Intake Details applet = InforClient.AgencyCDR.BuildingApplet.NonResIntake

**Comment by kellyjj** [comment]
failed to create r4c page.  error = Could not find the given applet node in the agency personalization configuration file for moniker=InforClient.AgencyCDR.BuildingApplet.NonResIntakeseverityNone

**Comment by kellyjj** [comment]
this is waiting for page generation for sycning of enhancement by dan g.

**Comment by kellyjj** [comment]
![image](https://user-images.githubusercontent.com/27238685/55346573-ad74fa00-5467-11e9-8e24-f354dc544847.png)

**Comment by kellyjj** [comment]
sync of enhancement done.   success in generating page for r4c

**Comment by kellyjj** [comment]
there are 44 formulas to update with proper name

**Comment by kellyjj** [comment]
all formulas are updated.    setting to retest,

**Comment by ABonomo21** [comment]
I don't see any of the requested changes to this detail page-AW

![image](https://user-images.githubusercontent.com/47611580/55731081-8aa69080-59e7-11e9-92d9-3bea3cae0e80.png)

**Comment by kellyjj** [comment]
detail page should be there now.
setting back to retest

**Comment by ABonomo21** [comment]
The detail page is now missing, therefore the permit is being held up at the completeness check stating that the "Non Residential detail page must be completed". The only detail pages showing are the last two screenshots below. 
![image](https://user-images.githubusercontent.com/47611580/55966418-5c72bc00-5c46-11e9-9890-199868ed89cf.png)
![image](https://user-images.githubusercontent.com/47611580/55966438-68f71480-5c46-11e9-8891-e0bb98a99a79.png)
![image](https://user-images.githubusercontent.com/47611580/55966461-71e7e600-5c46-11e9-996b-2e7ffe9b0805.png)

**Comment by goggansd** [comment]
Made Non-Residential Building Intake Details visible in Start Application. Fixed - see AP # 240324.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/56048633-e9d11180-5d15-11e9-8bb6-4fdfbbb3c98f.png)
