### ISSUE TITLE
Building - Garage- Incorrect review population

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#43]
Detached Garage: Permit #237156-The DUSWMF review generated on this permit when according to airtable, that review is not required for this type of permit.

![image](https://user-images.githubusercontent.com/47611580/52814485-48f20d00-306a-11e9-8051-754e35f15589.png)

**Comment by imazlout** [comment]
Duplicate of #36. Sent email to @ABonomo21 and awaiting response

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55734983-7fa32e80-59ee-11e9-88e1-1cdc37466bd4.png)
