### ISSUE TITLE
Construction Type Changes 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#430]
I emailed this to Dan and KCI on 3.7.19- i want to make sure the changes get completed 
![image](https://user-images.githubusercontent.com/47611580/54613126-929a9280-4a30-11e9-98de-9773e2fda291.png)

**Comment by megisys** [comment]
This is cleaned up

**Comment by ABonomo21** [comment]
99% fixed-everything is correct but there are still two "Retaining Wall" when there should be only one.-AW
![image](https://user-images.githubusercontent.com/47611580/55969098-37cd1300-5c4b-11e9-8937-e2f17d16d1c3.png)

**Comment by goggansd** [comment]
Expired RETAINWLL, kept RETAINWALL. Please retest.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/56048271-205a5c80-5d15-11e9-8327-695b9f4a4e13.png)
