### ISSUE TITLE
PLANNING - CORRECTION PLAT - remove fro as a reviewer

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#432]
FRO populated as a reviewer on Correction Plat in error. FRO is not a reviewer on Correction Plats. AREED
![image](https://user-images.githubusercontent.com/4129185/54613503-308e5d00-4a31-11e9-8d76-eae27ed9dbc1.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
fixed per PL237856
MW
