### ISSUE TITLE
Distributor License- Proof of Business

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#433]
Proof of Business needs a drop down menu

![image](https://user-images.githubusercontent.com/47611580/54614875-7d733300-4a33-11e9-9bb5-d4f31a7decc8.png)

This is the menu currently in Hansen 7 

![image](https://user-images.githubusercontent.com/47611580/54614811-65031880-4a33-11e9-9423-a5a4a82dda1d.png)

**Comment by ABonomo21** [comment]
Additionally, should read proof of business located in the State of Maryland. 

There is no longer a requirement for distributors to maintain an office in Frederick County.

**Comment by goggansd** [comment]
Created new field called ProofOfBusiness on table AgencyCDR.BusinessLicense.DistributorLicDetail.
Created new code definition called AgencyCDR.BusinessLicense.ProofOfBusiness.
Added code table values as per Hansen V7 screenshot above in table AgencyCDR.BusinessLicense.ProofOfBusiness.
Altered InforClient.AgencyCDR.BusinessLicenseApplet.DistributorDetails to have edit box control bound to new ProofOfBusiness field in AgencyCDR.BusinessLicense.DistributorLicDetail, also addressed inability to add/edit grid items by deleting existing Hours of Operation and Monthly Report Info group box controls and replacing with new group area controls, then repositioning grids atop new controls, and finally corrected Proof of Business label to read "Proof of Business Located in State of Maryland".

**Comment by ABonomo21** [comment]
This is not corrected 

![image](https://user-images.githubusercontent.com/47611580/55648515-86dbf980-57ae-11e9-8cba-ec634644d2d9.png)

**Comment by goggansd** [comment]
What, exactly, are you saying is not fixed, @ABonomo21?

**Comment by megisys** [comment]
Fixed

**Comment by ABonomo21** [comment]
This is not corrected still... there should be a drop down menu in the proof of business with the following options. 
![image](https://user-images.githubusercontent.com/47611580/55818148-f52cfe80-5ac3-11e9-9148-5dac923b6501.png)

**Comment by megisys** [comment]
Fixed

**Comment by ABonomo21** [comment]
corrected
