### ISSUE TITLE
Distributor License- Monthly Reporting Information Details Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#434]
Is the reporting information going to show up when a report is submitted? If not this section needs to be removed from the detail page 

![image](https://user-images.githubusercontent.com/47611580/54614994-b8756680-4a33-11e9-9208-07794f440ca2.png)

**Comment by megisys** [comment]
Made read only for historic ones

**Comment by ABonomo21** [comment]
Perfect.
