### ISSUE TITLE
Distributor License- Detail Page Change

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#436]
Need Labels on these detail page items

Hours of Operation 

Distributor Representative Contact Information- See item # 425 (what is best practice? should these be added as additional applicants and if so can we capture details such as drivers license number and DOB? ) 

![image](https://user-images.githubusercontent.com/47611580/54615100-e5297e00-4a33-11e9-8dc7-8069f36f5d98.png)

**Comment by megisys** [comment]
Should just be listed Additional Applicants

**Comment by megisys** [comment]
We can manually keep a hold of these.. These are low use permits and we only have 7

**Comment by ABonomo21** [comment]
I am fine listing the representatives under the applicants tab, knowing we can add the details needed however, we still need to be able to edit the proof of business. see item #433 and the hours of operation. ( I see the label was added but I am not able to edit the fields) 

![image](https://user-images.githubusercontent.com/47611580/55180735-929d3f80-5160-11e9-8f6b-b3ff983e7fd9.png)

The monthly reporting field should be read only as applicants will submit reports online under new a/p distributor reports - per convo with Dan this data will migrate over.

**Comment by goggansd** [comment]
Created new field called ProofOfBusiness on table AgencyCDR.BusinessLicense.DistributorLicDetail.
Created new code definition called AgencyCDR.BusinessLicense.ProofOfBusiness.
Added code table values as per Hansen V7 screenshot above in table AgencyCDR.BusinessLicense.ProofOfBusiness.
Altered InforClient.AgencyCDR.BusinessLicenseApplet.DistributorDetails to have edit box control bound to new ProofOfBusiness field in AgencyCDR.BusinessLicense.DistributorLicDetail, also addressed inability to add/edit grid items by deleting existing Hours of Operation and Monthly Report Info group box controls and replacing with new group area controls, then repositioning grids atop new controls, and finally corrected Proof of Business label to read "Proof of Business Located in State of Maryland".
