### ISSUE TITLE
Distributor License - Open Case Exists 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#437]
1.	On every license application I create I get a status check that says “Open Cases Exists” during the Completeness Check milestone. However, there are no related Cases on the Related Records tab AND I’m not sure how it would even be possible that there is an open case since the Address is not required on this AP, and I didn’t input one on Start Application. (I used the “Bypass Case Holds” Log to get passed this)
![image](https://user-images.githubusercontent.com/47611580/54615817-1ce4f580-4a35-11e9-8677-79b04ab57cea.png)
![image](https://user-images.githubusercontent.com/47611580/54615843-24a49a00-4a35-11e9-9048-2ac3b4c23dee.png)

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54697212-90edcf00-4b03-11e9-83ae-7ec04846921a.png)
![image](https://user-images.githubusercontent.com/47611580/54697240-9a773700-4b03-11e9-998f-20000b626b43.png)
