### ISSUE TITLE
Distributor License- Review Results

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#438]
The DISTRIBUT review result codes are not filtered properly.

Only need approved result or resubmit, if we need to deny an application that should be available for a supervisor with those privileges. 

![image](https://user-images.githubusercontent.com/47611580/54616541-21f67480-4a36-11e9-81d7-72b3d6f06428.png)

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54710413-fd75c780-4b1d-11e9-89b3-94ec849a27ad.png)
