### ISSUE TITLE
Planning-site-all

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#439]
resulted Hearing as waived and still stuck in hearing milestone

![image](https://user-images.githubusercontent.com/4129185/54616943-d98b8680-4a36-11e9-9c6c-1524ac30fc11.png)

**Comment by megisys** [comment]
Addressed this.. Sorry I introduced this trying to solve another issue

**Comment by dhenry-KCI** [comment]
ok on SP237779

MW
