### ISSUE TITLE
Building- Garage Permit - Closing with open trades

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#44]
Garage Permit #237156 & Electrical Permit #237158-the building permit closed and finalized with the attached electrical permit still open. All trade permits must be closed and finalized before the building permit final inspection can occur.

![image](https://user-images.githubusercontent.com/47611580/52814627-94a4b680-306a-11e9-93b8-f4c43ee6c95e.png)

![image](https://user-images.githubusercontent.com/47611580/52814632-98d0d400-306a-11e9-9d7a-ce0b75f0f58c.png)

**Comment by imazlout** [comment]
Training needed. Duplicate of #68 and #80

**Comment by ABonomo21** [comment]
Agreed- We need to make sure staff is trained to know that inspections should be scheduled prior to being resulted.
This will affect inspectors using mobile and administrative staff using the back office (in the event and inspection is requested at the customer service counter, email or phone) when this project goes live- in the future all inspection request should be submitted via the portal.
