### ISSUE TITLE
Distributor License- Renewal 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#442]
After paying the license fee, the application moves to Active and Awaiting Key Date Anniversaries. In the Trade License module we would normally use the “CREN” log type to initiate a renewal period, however, I am not seeing the “CREN” log type (or any other renewal type log entry). I do not know of any other way to kick the application into a renewal, therefore, I can’t test it. In the test scripts attached I copied the typical way we would do a renewal for a trade license and put it in red at the bottom, but I’m unsure if this would be anywhere close to the way we would do it for Distributor. We might need further instruction from Dan on how this works.

**Comment by megisys** [comment]
THIS IS Valid and needs to be fixed

**Comment by goggansd** [comment]
Fixed in IPSTest. Added following log types: CREN, CPRO, CGRACE, CEXP, along with code to make these log types change the corresponding date on the business license.

**Comment by ABonomo21** [comment]
This did not work on existing licenses- because we will not create new distributor license as we only have 5 the renewal process needs to work on migrated licenses from V7 - when I pay the renewal fee the application moves right to another fee payment being required. 

![image](https://user-images.githubusercontent.com/47611580/55651368-5ef09400-57b6-11e9-934f-582692201807.png)

Can we walk through this issue when you (Dan) are on site?

**Comment by megisys** [comment]
Need to move them all to Active First

**Comment by ABonomo21** [comment]
corrected all 5 moved to active
