### ISSUE TITLE
Building - Driveway - Bulk Add from ResBldg permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#444]
When trying to bulk add a driveway permit off of a resbldg permit - we got the below error message. Bulk add was being done off of AP # 238947. We were not able to save the driveway permit.

![image](https://user-images.githubusercontent.com/4129185/54620927-4efa5580-4a3d-11e9-8468-d72e3c656e45.png)

![image](https://user-images.githubusercontent.com/4129185/54620978-646f7f80-4a3d-11e9-92d4-40ca51a007ad.png)

logged by tiffany martin 3/19/19

**Comment by megisys** [comment]
Resolved.. See  238952

**Comment by dhenry-KCI** [comment]
CORRECTED TM 4/4/19
