### ISSUE TITLE
Fire Permit- Detail Page Changes

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#445]
![image](https://user-images.githubusercontent.com/47611580/54626641-f3819500-4a47-11e9-9070-6ef1ade94ea6.png)

![image](https://user-images.githubusercontent.com/47611580/54626661-ff6d5700-4a47-11e9-9ed0-7bc605ba27f4.png)

**Comment by kellyjj** [comment]
the page InforClient.AgencyCDR.BuildingApplet.FireDetails (Fire Details) has been updated with changes, and ready for generation

**Comment by kellyjj** [comment]
successfully created r4c page  with this url:  https://onlinepermitting.frederickcountymd.gov/IPSTest_RS/api/core/detailpage/generate/InforClient.AgencyCDR.BuildingApplet.GradingDetailsIntake

**Comment by kellyjj** [comment]
update to clarify this issue:

the detail page InforClient.AgencyCDR.BuildingApplet.FireDetails (Fire Details)  was updated prior to this ticket.  there are no other detail pages for v7.

however,  the detail page in this is the fire suppresion page.  that does need to be updated.

**Comment by kellyjj** [comment]
page has been generated for r4c

![image](https://user-images.githubusercontent.com/27238685/55363511-212bfc80-5492-11e9-9e74-99597dc11e6f.png)

**Comment by kellyjj** [comment]
Who ever did the detail page didn't change the name of the page, so any formula pointing to it doesn't need to be updated.

**Comment by kellyjj** [comment]
setting to ready for retest

**Comment by ABonomo21** [comment]
I do not see any of the requested changes in IPS-AW

![image](https://user-images.githubusercontent.com/47611580/56135679-407d5c00-5f5f-11e9-8264-e0d69f0a5cde.png)
![image](https://user-images.githubusercontent.com/47611580/56135700-4a06c400-5f5f-11e9-87db-6f63f420e03c.png)
![image](https://user-images.githubusercontent.com/47611580/56135712-525eff00-5f5f-11e9-9fe6-ebdcf8d990b1.png)

**Comment by ABonomo21** [comment]
on the fire details page, the Expedited Plan Review Hours box still needs to be deleted and the After Hours Inspection Box, needs to be moved to the inspection page. Both are on the notes Ashlye provided above. Can't test the R4C side of the details page yet due to fire permits not being an option on there yet.-AW
![image](https://user-images.githubusercontent.com/47611580/57034371-56587580-6c1d-11e9-9981-5fc58e0455cc.png)

**Comment by ABonomo21** [comment]
not fixed. only the hours box was to be removed from Expedited Plan Review. and the After Hours Inspection is not on the inspection details page where it should be under the Inspection Hours-AW
![image](https://user-images.githubusercontent.com/47611580/57086592-6c713f00-6ccc-11e9-8724-1706b8292f4b.png)

![image](https://user-images.githubusercontent.com/47611580/57087227-970fc780-6ccd-11e9-951b-45a9ebf53bba.png)
