### ISSUE TITLE
Distributor Report- Awaiting Applicant Payment Milestone

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#446]
Once I get to the Awaiting Applicant Payment milestone on the Distributor Report I get stuck because I will pay the fee, then as soon as I pay it, another fee generates (along with another email) and you do this in an endless loop.

![image](https://user-images.githubusercontent.com/47611580/54627622-30e72200-4a4a-11e9-9fd1-609aea628e82.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
proceeds to closed once fee is paid
