### ISSUE TITLE
Distributor Report- Error when resubmit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#447]
When trying to resubmit as an applicant, I receive system errors when I open the Applicant Actions detail page.
![image](https://user-images.githubusercontent.com/47611580/54627861-a3f09880-4a4a-11e9-8736-4cd8ebd5433c.png)

![image](https://user-images.githubusercontent.com/47611580/54627891-b23eb480-4a4a-11e9-86e7-cfb1edf9dd75.png)

![image](https://user-images.githubusercontent.com/47611580/54627912-bd91e000-4a4a-11e9-97a5-f325b46244bb.png)

**Comment by megisys** [comment]
Issued Addressed

**Comment by ABonomo21** [comment]
Was able to resubmit applicant actions-AW
![image](https://user-images.githubusercontent.com/47611580/54758017-c0631100-4bc1-11e9-8e59-811f3bef969e.png)
![image](https://user-images.githubusercontent.com/47611580/54758060-d7096800-4bc1-11e9-9b25-3352f751f942.png)
