### ISSUE TITLE
Planning-Site-

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#449]
under details, need to change "# of buildings" to "#buildings/dwelling units".  This also needs to be a required field since fees are generated from this field for residential uses.  # of lots must also be a required field as it also may generate fees.

![image](https://user-images.githubusercontent.com/4129185/54629189-693c2f80-4a4d-11e9-95eb-c56adea41bb5.png)

MW

**Comment by megisys** [comment]
Addresswed

**Comment by dhenry-KCI** [comment]
good  MW
