### ISSUE TITLE
Planning- BOA - Resubmission Review Results

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#452]
Testing resubmit for BOA review generated additional reviews that were not previously generated as agencies that required a review. The system should only populate the review for the agency that requested the resubmit and staff will determine if additional agencies need an additional reviews. 
![image](https://user-images.githubusercontent.com/47611580/54633975-98579e80-4a57-11e9-8723-2b9300c4c4c5.png)

**Comment by megisys** [comment]
Ready for REttest

**Comment by dhenry-KCI** [comment]
generated a Health review even though they were approved on 1st review and SHA populated on 2nd review, they weren't on first review
MW

**Comment by megisys** [comment]
Please Retest

**Comment by dhenry-KCI** [comment]
works see 237869
