### ISSUE TITLE
Planning-site-all

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#453]
make # of lots field required only for Type I site plan with a residential occupancy type

MW

![image](https://user-images.githubusercontent.com/4129185/54634042-be7d3e80-4a57-11e9-8342-7c570dcc3152.png)

**Comment by megisys** [comment]
Need to remove it and set it during completeness check.. Added Label explaining this..

**Comment by dhenry-KCI** [comment]
Dan,  lets discuss this.

![image](https://user-images.githubusercontent.com/4129185/54686965-dc4ab200-4af0-11e9-942e-c59cf76f658a.png)

**Comment by dhenry-KCI** [comment]
check for alert in completeness check

**Comment by dhenry-KCI** [comment]
areed
