### ISSUE TITLE
planning-site-admconcept fee error

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#454]
got this error message when I tried to pay fees on SP237815

![image](https://user-images.githubusercontent.com/4129185/54634413-8a564d80-4a58-11e9-93d5-6bd8c76fe505.png)

MW

**Comment by megisys** [comment]
Solved

**Comment by dhenry-KCI** [comment]
fixed SP237833  MW
