### ISSUE TITLE
Planning- BOA- Expiry Date

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#457]
The requirement at completeness check for the expiry date should only populate if the work type is Administrative Error. All other work types should not require the expiration date to be entered. 

If this is an appeal of administrative error the expiry date should be set by staff for 30 days from the original denial

![image](https://user-images.githubusercontent.com/47611580/54689211-7280d700-4af5-11e9-80dc-98d858502eec.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
fixed.

MW
