### ISSUE TITLE
PLANNING - PREPLAT - Review due date - 4th review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#459]
4th review should be 1 week review due date. AReed
![image](https://user-images.githubusercontent.com/4129185/54692234-0b662100-4afb-11e9-8541-a7a0c24a45af.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
corrected PP237855 Areed
