### ISSUE TITLE
Building- Ground Mounted Solar Panel- No fee population 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#46]
Ground Mounted Solar Panels Permit #237164-The building fee did not generate for this permit. For ground mounted solar panel permits, the building fee is determined by the square footage of the project. 399sf or less has a building fee of $110, 400sf or more has a building fee of $173. This permit should have had the $110 building fee generate along with the zoning, filing, and automation fee.

![image](https://user-images.githubusercontent.com/47611580/52814938-565bc700-306b-11e9-945e-3969c64ec0e5.png)

**Comment by imazlout** [comment]
Duplicate of #57. Fix was already done as a part of that Issue.

**Comment by ABonomo21** [comment]
Fees generated correctly for both the ACC339 & ACC400-AW

![image](https://user-images.githubusercontent.com/47611580/55806765-ea1ba380-5aae-11e9-90f3-af722cda66dd.png)
![image](https://user-images.githubusercontent.com/47611580/55807708-a6c23480-5ab0-11e9-859b-08875cacbbc2.png)
