### ISSUE TITLE
Non Res-New Tenant Change To Space-Error Message

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#460]
I received this error message when trying to complete a new permit application. No matter what stage I was at in the application or what address I tried to enter, these errors kept generating.-AW
![image](https://user-images.githubusercontent.com/47611580/54692395-54b67080-4afb-11e9-89f0-1e193f93571f.png)
![image](https://user-images.githubusercontent.com/47611580/54692417-60099c00-4afb-11e9-9221-a42c78068960.png)

**Comment by megisys** [comment]
Addressed This

**Comment by ABonomo21** [comment]
confirmed fixed=AW
