### ISSUE TITLE
PLANNING - PREPLAT - HEARRING result

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#461]
1st hearing resulted at deferred. Milestone should have stayed under hearing but moved to awaiting paperwork.

**Comment by dhenry-KCI** [comment]
PP237844 AREED

**Comment by megisys** [comment]
Ready for Retest

**Comment by dhenry-KCI** [comment]
1st hearing not resulted - milestone changed to awaiting paperwork
![image](https://user-images.githubusercontent.com/4129185/54709205-79224500-4b1b-11e9-8d1f-2ded50dbe6ad.png)
![image](https://user-images.githubusercontent.com/4129185/54709164-67d93880-4b1b-11e9-87e4-ab1050e01dc6.png)

**Comment by megisys** [comment]
Ready for Retest

**Comment by dhenry-KCI** [comment]
still fails.  Denied PC and it went to awaiting paperwork

![image](https://user-images.githubusercontent.com/4129185/55102601-27d70000-509d-11e9-9238-6a8220908944.png)

**Comment by megisys** [comment]
This is right... No More Hearings.. If Denied...
