### ISSUE TITLE
PLANNING - PREPLAT - admin closure Miscellaneous

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#462]
Need to add Miscellaneous for "APFO Project not approved"
![image](https://user-images.githubusercontent.com/4129185/54694796-33578380-4aff-11e9-9b4b-c4dbaf2ecb41.png)

**Comment by dhenry-KCI** [comment]
areed

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
Not to be picky... but... the two highlighted items are saying the same thing. I would like the language to be the same. :) areed
![image](https://user-images.githubusercontent.com/4129185/54709789-90adfd80-4b1c-11e9-9e22-a0b1055f7337.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
corrected AReed PP237867
