### ISSUE TITLE
PLANNING - PLAT - Remove Initial from fee description

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#464]
Remove Initial from fee description. Areed

![image](https://user-images.githubusercontent.com/4129185/54699499-82a1b200-4b07-11e9-977d-acccdc387123.png)

**Comment by megisys** [comment]
I need a new word.. as if I remove one of them we will end up with duplicates.. County Issue

**Comment by mmbanong** [comment]
After discussion with Dan, this issue is postponed until after go live

**Comment by dhenry-KCI** [comment]
Will need to perform Post Go-Live

**Comment by dhenry-KCI** [comment]
will reopen ticket when go-live approaches
