### ISSUE TITLE
R4C - Add Primary Site - Map Issue

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#466]
When trying to add a primary site using the Map function, you find that the map will not pan around past a certain point. Depending on the direction in which you are panning, that point can vary. If you are zoomed in, you aren't able to pan throughout the entire county.

![image](https://user-images.githubusercontent.com/31770504/54752846-db2f8880-4bb5-11e9-9f85-8c2d50516a00.png)

(Issue found by Craig Terry 3/19/19)

**Comment by megisys** [comment]
fixed

**Comment by dhenry-KCI** [comment]
fixed
