### ISSUE TITLE
PLANNING - NID - Pop up blank

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#467]
This should have 3 options. Commercial, Residential, Other. AReed

![image](https://user-images.githubusercontent.com/4129185/54753126-a8d25b00-4bb6-11e9-86ca-b61b498752fe.png)
![image](https://user-images.githubusercontent.com/4129185/54753175-c8698380-4bb6-11e9-9b02-5f4eb8073d90.png)

**Comment by megisys** [comment]
Shouldnt have a pop up.. Should be a free text as the Applicant wont know our standards.. Completeness Check will review this..

**Comment by dhenry-KCI** [comment]
ok-MW
