### ISSUE TITLE
R4C - NID - Details Page

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#469]
Cannot select any options to populate the 'Existing Use' and 'Proposed Use' fields. When clicking the dropdown arrows on either field, there are no options to choose from. These fields are marked as required, therefore we cannot move forward and submit an application for the NID AP Type. It cannot be fully tested.

![image](https://user-images.githubusercontent.com/31770504/54753231-eb943300-4bb6-11e9-821a-25b8b5c01efa.png)

(Issue reported by Craig Terry and Charles Freeman 3/18, 3/19)

**Comment by megisys** [comment]
Addressed
