### ISSUE TITLE
Building- Ground Mounted Solar Panels- Partial pass final inspection 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#47]
Ground Mounted Solar Panels permit #237164-I was able to partial pass the final inspection of the building permit. Final inspections cannot be partially passed. I was also able to do this final inspection result while the attached electrical permit #237166 was not yet issued. All trade permits must be closed and completed before the building permit final inspection can occur.

![image](https://user-images.githubusercontent.com/47611580/52815004-8905bf80-306b-11e9-9e91-2b592cf7e70e.png)

![image](https://user-images.githubusercontent.com/47611580/52815040-9f138000-306b-11e9-8a46-b009f8adb168.png)

I then was able to pass the 2nd final inspection while the electrical permit #237166 stayed in the status of awaiting applicant payment. All trade permit must be closed and completed before the building final inspections can occur.

![image](https://user-images.githubusercontent.com/47611580/52815061-a8045180-306b-11e9-8a18-ce3a27b7f417.png)

**Comment by imazlout** [comment]
Training Needed.

For the first part, this was discussed as part of airtable item #324 (comment on that item says: If a user decides to partial pass a final inspection they can do so by checking the Partial Inspection checkbox. It will be a County training exercise to let staff know which Final inspections can be partialed and which cannot.)

For the second portion, this is a duplicate of #68 and #80. The inspection needs to scheduled first.

**Comment by ABonomo21** [comment]
Agreed- We need to make sure staff is trained to know that inspections should be scheduled prior to being resulted.
This will affect inspectors using mobile and administrative staff using the back office (in the event and inspection is requested at the customer service counter, email or phone) when this project goes live- in the future all inspection request should be submitted via the portal.
