### ISSUE TITLE
NID - R4C Detail Page Change 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#470]
drop box for "existing use" field doesnt work.  Tried typing use in and it disappears.

"proposed commercial type of use" drop box needs a comprehensive list of commercial uses and "residential" shouldnt be a choice under this field

"proposed use" drop box has no options and you cant type anything in it
![image](https://user-images.githubusercontent.com/4129185/54753414-62c9c700-4bb7-11e9-8f94-3213b8e233cc.png)

![image](https://user-images.githubusercontent.com/4129185/54753649-f00d1b80-4bb7-11e9-817f-a405bb2bf4b1.png)

![image](https://user-images.githubusercontent.com/4129185/54753557-b76d4200-4bb7-11e9-83bc-1a8183028e96.png)

**Comment by megisys** [comment]
This has been addressed.. County to update dropdown list items as required .. Training Issue

**Comment by dhenry-KCI** [comment]
why not make this a free form text box like you did in the NID application?

**Comment by megisys** [comment]
Ready for Retest

**Comment by dhenry-KCI** [comment]
fixed
