### ISSUE TITLE
R4C - Attachment Errors

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#473]
- Can’t attach jpg or pdf with drag n drop (this was working yesterday with explorer)
- Browse for files worked initially, then began to fail

(Issue reported by Craig Terry 3/19)

**Comment by JuanitaMiles** [comment]
It appears as though Craig was not using Internet Explorer during this round of testing. Infor has made us aware that R4C does not always work well in Chrome. We may have to just make staff aware that they should be testing in IE or Edge.   -Juanita

**Comment by dhenry-KCI** [comment]
Need to have a staff meeting about various browser types needed for different applications. AReed
Meeting with ABonomo, GHessong, MWilkins, AReed, DHenry, JMiles
