### ISSUE TITLE
R4C - BLIGHTED PROPERTY

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#474]
My blighted property request never sent a confirmatory email. The case was closed without notification the applicant.
![image](https://user-images.githubusercontent.com/4129185/54754701-7f1b3300-4bba-11e9-9cec-da45c337ab7d.png)

**Comment by dhenry-KCI** [comment]
Also, could not remain anonymous so now everyone can see my complaint (including my neighbor with the nasty mattress).

**Comment by calequin** [comment]
The anonymous functionality is available for users who are not logged into the system. If logged in the system will use the contact information of the logged in user. Currently there is no notifications set up for cases. Do we want a progress sent to the user who logged the complaint?

**Comment by megisys** [comment]
Removed

**Comment by ABonomo21** [comment]
corrected has been removed
