### ISSUE TITLE
R4C - Payment of Fees - Confirmation Screen (Excel Issue #23)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#476]
After paying fees with a credit card and being redirected back to the portal, the Payment Confirmation screen that contains the Reference number only flashes momentarily on the way back to the portal. This isn't enough time for the customer to record their payment confirmation number.

(Issue reported by Craig Terry 3/18)

**Comment by calequin** [comment]
I will be reaching out to our team to see if there is a workaround to this issue.

**Comment by calequin** [comment]
The transaction # is auto refreshed and sent directly to the dashboard for the applicant to see the outcome. The notification sent to the customer contains the transaction # and information of the payment.

**Comment by ABonomo21** [comment]
payment via R4C is currently not working therefore I am unable to test this issue-AW

**Comment by ABonomo21** [comment]
payment via R4C is now giving me this error-aw
![image](https://user-images.githubusercontent.com/47611580/57931923-9e1b0600-7887-11e9-89d7-e2fa5e5f068c.png)

**Comment by megisys** [comment]
WebServices Out of Sync..

**Comment by ABonomo21** [comment]
Permit# 245647- Can't test- still unable to pay-MCoffman

![image](https://user-images.githubusercontent.com/47611580/59039087-274baa00-8842-11e9-907f-0b4cb009a53e.png)

**Comment by calequin** [comment]
fixed in preprod. Web services were out of sync
![image](https://user-images.githubusercontent.com/47603568/59242808-acccb280-8bd2-11e9-91ff-34dfca1a06c9.png)

**Comment by ABonomo21** [comment]
have been able to pay fees- have a white board check list to make sure all a/ps can be paid online - staff will mark Confirm Successful Payment (CSP) on the white board if it works
