### ISSUE TITLE
PLANNING - NID - Remove drop down on Proposed Commercial Type of Use

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#478]
Remove drop down on Proposed Commercial Type of Use. AReed
![image](https://user-images.githubusercontent.com/4129185/54755813-2b5e1900-4bbd-11e9-86fc-d54b9cacea2b.png)

**Comment by megisys** [comment]
Covered in another ticket

**Comment by dhenry-KCI** [comment]
areed
