### ISSUE TITLE
R4C -Submission without an address - resulting in case existing

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#479]
Applicaiton was able to be submitted without any address being related and on the IPS side I have a code stating open case exists 

![image](https://user-images.githubusercontent.com/47611580/54755880-62342f00-4bbd-11e9-8fb0-77c7ea7fa6cd.png)

**Comment by JuanitaMiles** [comment]
I have also been able to submit all applications on R4C with no address/parcel information or Location Information thus far (Verification Letters, Special Event). -Juanita 3/21

**Comment by calequin** [comment]
This issue has been fixed with a customvalidation formula which looks at the site as required field. Please retest

**Comment by ABonomo21** [comment]
seems to be requiring addresses to submit applications. will retest on other a/p types as they are added
