### ISSUE TITLE
Building Permit- Sign - R4C testing 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#480]
Unable to tell the applicant to resubmit on a sign permit that was submitted without an address without resulting the log with the occupancy number, in this case if no address was provided we would not be able to perform a property browser check to enter a log 

![image](https://user-images.githubusercontent.com/47611580/54756107-e8507580-4bbd-11e9-967a-1eed3e7ac89a.png)

**Comment by megisys** [comment]
PLease ReTest.. Will only check for Log once the COMPLETE review is resulted...

**Comment by ABonomo21** [comment]
this is still not working. 
![image](https://user-images.githubusercontent.com/47611580/56831672-b030f800-6837-11e9-91d2-e61838225fbb.png)

**Comment by megisys** [comment]
Addressed Formula. A Resubmit bypasses this status check

**Comment by ABonomo21** [comment]
able to resubmit which bypassed the log entry for the BLDGAPP. However, I am creating another github issue #783 for the completeness check being held up for the final signs detail page to be completed? there is no final sign detail page. 
![image](https://user-images.githubusercontent.com/47611580/56967273-e10e7700-6b2e-11e9-9cf4-d406d67932f2.png)
![image](https://user-images.githubusercontent.com/47611580/56967303-ecfa3900-6b2e-11e9-9b0d-eb9f271dd3a7.png)
not closing until issue is addressed and i can confirm the resubmit action goes back to the applicant

**Comment by megisys** [comment]
I addressed this issue - DAN

**Comment by ABonomo21** [comment]
resolved
