### ISSUE TITLE
R4C - YARDMOD - Rear/Side Details Page

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#482]
Side and Rear yard mods – being prompted to enter House A & B address and info. This doesn’t apply to side and rear mods, only front yard mods. This may confuse applicants.

![image](https://user-images.githubusercontent.com/31770504/54756200-19c94100-4bbe-11e9-87ba-314f07f05f1e.png)

(Issue Reported by Craig Terry 3/19)

**Comment by megisys** [comment]
Update the Application Instructions.. See Ashlye to find out how.

**Comment by JuanitaMiles** [comment]
We already know how to do this. This is a task Martin will be responsible for completing. The appropriate County staff has already been asked to provide drafted versions of their Application Instructions, we are awaiting that documentation for configuration.

**Comment by dhenry-KCI** [comment]
fixed- MW
