### ISSUE TITLE
Building Permit - R4C- Attachment Issues 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#483]
An attachment was inserted for this application #238978 on the R4C side and it did not show up on the IPS side 

![image](https://user-images.githubusercontent.com/47611580/54756356-775d8d80-4bbe-11e9-92b7-1ddbcc0f4324.png)

**Comment by megisys** [comment]
I can not replicate this issue.. Please screenshot each step to replicate..
