### ISSUE TITLE
R4C- Random Attachment Type

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#484]
Submitted a Subdivision Potential Verification request. Paid fees. Did not upload any attachments. However, an erroneous file attachment appeared but cannot download to see what it is.

![image](https://user-images.githubusercontent.com/4129185/54756250-3796a600-4bbe-11e9-92b0-bac97d251178.png)

**Comment by calequin** [comment]
Couldnt replicate. Please retest

**Comment by ABonomo21** [comment]
marking as will monitor - unable to duplicate
