### ISSUE TITLE
PLANNING - NID - Increase text fields

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#485]
Increase text field size. Typically people write full sentences in these fields. Need to be able to read without scrolling. Also increase the other field that has been requested to be added to the bottom of both sections existing use and proposed use.  AReed

![image](https://user-images.githubusercontent.com/4129185/54756653-16828500-4bbf-11e9-9e11-0ab41d702c4b.png)

**Comment by megisys** [comment]
Addressed. But these are only test fields not Comments..

**Comment by dhenry-KCI** [comment]
ok-MW
