### ISSUE TITLE
R4C - DASHBOARD WIPED

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#486]
My Dashboard got wiped and all applications submitted, fees paid, etc. are missing.
![image](https://user-images.githubusercontent.com/4129185/54757724-32872600-4bc1-11e9-8683-dfd0fd7bfa84.png)

**Comment by calequin** [comment]
This was due to a rest services timeout issue. This has been extended to 30 minutes. Please retest

**Comment by dhenry-KCI** [comment]
fine on 4/24/19- MW
