### ISSUE TITLE
R4C - FEE PAYMENT

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#487]
Cannot pay any fees "online"...?
![image](https://user-images.githubusercontent.com/4129185/54759129-d96cc180-4bc3-11e9-95f5-2d98da1785e3.png)

**Comment by megisys** [comment]
Fixed this issue. This is a back office issue

**Comment by dhenry-KCI** [comment]
verified in R4C 3/27. AReed
