### ISSUE TITLE
ResBldg-Townhouse-Egress Type duplicate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#488]
The egress types on the details page should only be Areaway, Bilco Door, Walkout, and Window. Door is a duplicate of Bilco Door.-AW
![image](https://user-images.githubusercontent.com/47611580/54759187-f4d7cc80-4bc3-11e9-86ce-71a5ca153029.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55022514-158f9000-4fd1-11e9-822d-9fc45ff7838a.png)
