### ISSUE TITLE
PLANNING - NID - Review Result edits

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#489]
Testing should say: APFO Testing - > 50 new trips during street peak hours or > 50 during site peak

![image](https://user-images.githubusercontent.com/4129185/54758923-7da23880-4bc3-11e9-8aeb-fa3251639272.png)

Put a space between <6
![image](https://user-images.githubusercontent.com/4129185/54759110-cfe35980-4bc3-11e9-8520-7bd92cc461b2.png)

Put a space between -6
![image](https://user-images.githubusercontent.com/4129185/54759135-de317580-4bc3-11e9-890a-d26acff960a2.png)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
good-MW
