### ISSUE TITLE
Building - Electrical Permit - Building Mounted Sign

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#49]
In the Inspection milestone, the inspection that should populate is Final. 
AP# 236109
Logged by K. Vanaman on 2/7

![electrical_permit-signs](https://user-images.githubusercontent.com/4129185/52869247-367fde00-3113-11e9-8df1-1457ff05c6ef.png)

**Comment by imazlout** [comment]
@ABonomo21 Could you clarify if the user meant only ELEC-Final should have populated for this scenario? What's the criteria for why only Final should have populated and not the others?

**Comment by dhenry-KCI** [comment]
That's correct- only final inspection.

**Comment by imazlout** [comment]
Could you please provide more information for this scenario so that I can update the formula accordingly? 
If Non-residential and Electrical details has Signs in the list, then only final inspection is needed? is that correct?

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Updated formulas so that only ELEC-FINAL displays if Electrical details has a record for SIGNS

Please screenshot for proof of test (AP#236173 in DEV)

<img width="960" alt="issue49_updated" src="https://user-images.githubusercontent.com/47784290/53214043-1bccce00-3619-11e9-83eb-4473e053641d.png">

**Comment by dhenry-KCI** [comment]
Testing failed-only the final inspection should generate for a building mounted sign electrical permit.-AW
![image](https://user-images.githubusercontent.com/4129185/53908506-786ab880-401d-11e9-8acb-5bb78ddb7a6e.png)

**Comment by imazlout** [comment]
Ready for Test. The edit to the ELEC-LVOL formula to address issue #149 interfered with this ticket. I have since updated that formula to exclude Signs, so that only ELEC-Final populates now.

**Comment by ABonomo21** [comment]
Issue Corrected-MCoffman
Training Note: Make sure staff knows to insert an Underground for Monument Signs

Electrical Sign Permit# 238620- Replacement Signs-Correct
![image](https://user-images.githubusercontent.com/47611580/53971142-4b281400-40ca-11e9-800f-99e0b3fb2c11.png)

Electrical Sign Permit# 238626-New Signs-Correct
![image](https://user-images.githubusercontent.com/47611580/53977269-a8c25d80-40d6-11e9-83da-aa875c4f4872.png)
