### ISSUE TITLE
PLANNING - NID - Review Result – Resubmit went to closed

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#490]
Review Result – Resubmit – If selected needs to go through the application resubmit loop and needs to require comments. Same as any other application type. 
![image](https://user-images.githubusercontent.com/4129185/54759303-28b2f200-4bc4-11e9-8cfc-838b8448c146.png)

**Comment by megisys** [comment]
This is crazy... This application is suppose to be a quick fire application.. Completeness Check is the one that gets a resubmit.. The NID Review should always come out to be approved.. The same person who is doing the NID Review should be doing the NID COmpleteness CHeck

**Comment by dhenry-KCI** [comment]
completeness check will not be done by the reviewer.  NID's often require additional details before a finding can be made.

MW

**Comment by megisys** [comment]
ALL NID Applications should be reviewed by the right person.. As They have paid a fee for this upfront.. Dont want to delay by having 2 parties review..

Dan

**Comment by dhenry-KCI** [comment]
No fee for NID. Corrected with Dan to get rid of completeness check and automatically assign reviews to RBURNS
