### ISSUE TITLE
PLANNING - PWCONSTRUC - CMBSWMIMP - Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#492]
Fees incorrect PW237888
Same Parcel ID used previously when fees were correct.
Fees were correct on PW237539 when it was tested on 3/7/19 - **What happened?**
Areed

![image](https://user-images.githubusercontent.com/4129185/54762136-e12f6480-4bc9-11e9-9c27-738d1aa52025.png)
![image](https://user-images.githubusercontent.com/4129185/54762152-e9879f80-4bc9-11e9-8b93-dbeb1a856991.png)

CORRECT FEES TO MATCH FROM PREVIOUS TEST
![image](https://user-images.githubusercontent.com/4129185/54762493-a2e67500-4bca-11e9-866c-f7731358f3f7.png)

**Comment by megisys** [comment]
I fixed this.. But I think it was wrong because another ticket forced us down another path.. Will find it

**Comment by megisys** [comment]
PLANNING PWCONSTRUC - CMBSWMDEV - fees #213
Need to be clear in your tickets..

**Comment by dhenry-KCI** [comment]
#213 is for CMBSWMDEV only. This work type application is CMBSWMIMP. It's in the title on both issues.

PW238938 - no selection on details page/ PW238940 - lines / PW238941 - facilities 
CMBSWMIMP - DUSWM is not populating from the parcel layer. It's populating from the Water/Sewer Lines or facilities check box on the Construction Details Page. 
Dan - Lets talk about the best way to configure this. Concern is two different fees for DUSWM depending on type of review. AReed

**Comment by dhenry-KCI** [comment]
retested - will keep IP involvement to check boxes for w/s on detail page. areed
