### ISSUE TITLE
PLANNING - PWCONSTRUC - Health repopulated after resulted Approved

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#494]
Health repopulated on 2nd review after resulted Approved on 1st review. AReed

![image](https://user-images.githubusercontent.com/4129185/54766849-6a4a9980-4bd2-11e9-9b86-746d212d5d5f.png)

**Comment by megisys** [comment]
Completed

**Comment by dhenry-KCI** [comment]
ok per PW237924  MW
