### ISSUE TITLE
Rhythm for Civics - Home Occupation - Error

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#495]
When trying to add a primary site for home occupation, dir and suffix are not working and receiving the error message "unauthorized access"

![image](https://user-images.githubusercontent.com/4129185/54773843-cb796980-4be0-11e9-8aa6-fbcb0d261f9a.png)

**Comment by calequin** [comment]
Please retest. The user will have the ability to search his/her address by inputting a couple of characters. The data in the system has the address listed as Renn Rd and using S as the dir.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/57034999-fc58af80-6c1e-11e9-9b0d-61d9a4e3f768.png)
