### ISSUE TITLE
Rhythm for Civics - YardMod - Direction

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#497]
If the Direction is accidently filled out it cannot be undone without canceling out and starting over. 

Logged By: J.Horman
Logged Date: 3/21/2019

![image](https://user-images.githubusercontent.com/4129185/54774346-de406e00-4be1-11e9-8727-a06ff87296f9.png)

**Comment by megisys** [comment]
Defect.. With Develop,ment

**Comment by calequin** [comment]
Once the address is searched and selected the user will have to click on the x button and search again. This is done in order for a user to select an address that it is currently in the system. Please retest

**Comment by dhenry-KCI** [comment]
works 4/24/19  MW
