### ISSUE TITLE
Rhythm for Civics - YardMod - Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#498]
House A information fields need to match house B fields.

Logged By: J.Horman
Logged Date: 3/21/2019

![image](https://user-images.githubusercontent.com/4129185/54774426-16e04780-4be2-11e9-9fd3-c099a5502234.png)

**Comment by dhenry-KCI** [comment]
Need to follow-up with Justin on workflow and expectations for applicant data entry

**Comment by megisys** [comment]
Fields REalligned
