### ISSUE TITLE
Rhythm for Civics - YardMod - Add Applicant

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#499]
Cannot edit to add an email address have to start over

Logged By: J.Horman
Logged Date: 3/21/2019

![image](https://user-images.githubusercontent.com/4129185/54774569-75a5c100-4be2-11e9-96fa-aade4f90c688.png)

**Comment by ABonomo21** [comment]
Christian is going to work on this with Dan West

**Comment by dhenry-KCI** [comment]
Closing as this is a duplicate of issue #530
