### ISSUE TITLE
License - Septic Installer - License Renewal

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#5]
When renewing a septic license the system should auto-populate the License Details on the Confirm Details License Page (PI236029).  

Logged by Kelly V. on 2/4

![image](https://user-images.githubusercontent.com/4129185/52349028-a72c4980-29f3-11e9-86b0-49d94feadb76.png)

**Comment by calequin** [comment]
added the SYSCOPY condition to the config for it to copy over detail page information just like electrical trade license applications

**Comment by ABonomo21** [comment]
CONFIRMED FIXED-AW (This screen shot was taken after I completed the review, but it did correctly require all the steps)

![image](https://user-images.githubusercontent.com/47611580/53975345-9a724280-40d2-11e9-9cb9-6d675c2de776.png)
