### ISSUE TITLE
Building -Signs - Incorrect Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#50]
The system generated a historic review and a town review, but the parcel was not in a town and the Historic "checkbox" was not marked.

AP#236104
Logged by K. Vanaman

![town_historic](https://user-images.githubusercontent.com/4129185/52869785-6c719200-3114-11e9-8273-c49875c75791.png)

**Comment by imazlout** [comment]
Could not replicate issue. I create a SIGNS application with the exact same information as the one above and the town and historic reviews were not added as expected. Was the primary site updated in the middle of testing the application perhaps? Please try testing again and assign back to me if you were able to replicate the issue.

See screenshot for proof of testing (AP#237275 in TEST environment)
<img width="960" alt="issue50_cannotduplicate" src="https://user-images.githubusercontent.com/47784290/53141106-e498e700-355c-11e9-8d63-2c02a745d164.png">

**Comment by dhenry-KCI** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/4129185/53896985-2f0d6f80-4003-11e9-81ca-c3318b58acfc.png)
