### ISSUE TITLE
Rhythm for Civics - YardMod - Submission

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#500]
Could not  submit rear yard and side yard modification once all required fields were filled out. 
Did not receive an email for the completion of yard mod YD237876. 

Logged By: J.Horman
Logged Date: 3/21/2019

![image](https://user-images.githubusercontent.com/4129185/54774813-f4026300-4be2-11e9-889c-b33a2ab89a7c.png)

**Comment by megisys** [comment]
Addressed this.. Expanded allowable upload types
