### ISSUE TITLE
Rhythm for Civics - YardMod - Dashboard

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#501]
Error returned when navigating back to dashboard.

Logged By: J.Horman
Logged Date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54775046-7f7bf400-4be3-11e9-9095-a49a5c070f66.png)

**Comment by calequin** [comment]
This has been addressed and fixed with the server timeout. Please retest
