### ISSUE TITLE
Building - Capacity - Capacity Adjustment

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#502]
When creating a new capacity permit, the system should not require the number of pages to be populated. 

Logged by Lauren Englar

![image](https://user-images.githubusercontent.com/4129185/54775195-daade680-4be3-11e9-93d3-a90232ff33ab.png)

**Comment by megisys** [comment]
Addressed in TEst

**Comment by JuanitaMiles** [comment]
Confirmed fixed L Englar
