### ISSUE TITLE
Rhythm for Civics - YardMod - Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#503]
Error returned when I went into my fees to verify if I paid my fees for the yard modification.  It appears I was logged out. I was able to log back in and withdrew application prior to paying fee. IPS show it was finalized but R4C is showing fee still need to be paid.  Mike Wilkins is providing the IPS side of this issue in his log. In addition, YD237882,YD237883 and YD237884 are all duplicates. The application that shows continue was the original application that the error message occurred on. 

Logged by: J.Horman
Logged Date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54775349-25c7f980-4be4-11e9-98de-4c4c62373bcf.png)
![image](https://user-images.githubusercontent.com/4129185/54775371-32e4e880-4be4-11e9-87e9-b641bef43299.png)

**Comment by calequin** [comment]
pending status has been added for a withdrawn application. Please retest

**Comment by dhenry-KCI** [comment]
fixed per YD 239336
