### ISSUE TITLE
Rhythm for Civics - YardMod - Application Upload

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#504]
Unable to upload the completed application.

Logged By: J.Horman
Logged Date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54775537-9b33ca00-4be4-11e9-9467-7ae9c2880893.png)

**Comment by megisys** [comment]
aAddressed this issue. Expanded allowable files types

**Comment by dhenry-KCI** [comment]
fixed per testing on 4/17/19-mw
