### ISSUE TITLE
Building - Grading - Project Specifics - Details Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#505]
The language - Board of County should be changed to Frederick County or County

![image](https://user-images.githubusercontent.com/4129185/54775884-4b093780-4be5-11e9-9585-f86b39fffdab.png)

logged by tiffany martin 3/21/19

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
CORRECTED 3/26/19 TM
