### ISSUE TITLE
Rhythm for Civics - HomeOccupation- Submission

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#506]
Unable to submit the home occupation application. Error message returned above.  When navigating to the dashboard the application was submitted. The one that I could not submit is below H235846.

Logged By: J.Horman
Logged Date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54775685-dd5d0b80-4be4-11e9-9fa0-56ba4b1140ee.png)

**Comment by calequin** [comment]
please retest.

**Comment by ABonomo21** [comment]
was not able to duplicate - created home occ only one populated on dashboard
