### ISSUE TITLE
Rhythm for Civics - LandUse - Land Use Intake Details 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#509]
Need ability to add multiple additional entertainment entries. System only allows user to select 1 entry from entertainment and 1 value from Add. Entertainment

Logged By: M.Rowley
Logged Date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54781013-8f9ad000-4bf1-11e9-828c-97fe2e594420.png)

**Comment by megisys** [comment]
No this is not supported in the Babck office or in Hansen 7. 2 entertainment types is the way it has always been

**Comment by ABonomo21** [comment]
two is fine- if there are more they should be added in the details
