### ISSUE TITLE
Use - Land Use - Temp. Outdoor Activity 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#51]
The system should only generate an environmental health review if the parcel is on well and septic or Sanitation Type = Portable

AP - 235770
Logged By. K. Vanaman

![lu - temp](https://user-images.githubusercontent.com/4129185/52870509-084fcd80-3116-11e9-9ff7-2d82f169078f.png)

**Comment by dhenry-KCI** [comment]
Testing Failed-the health review fee generated on this land use when the property is not on well/septic and the sanitation type is not portable.

![image](https://user-images.githubusercontent.com/4129185/53443242-3f0cca00-39d9-11e9-850e-c169fc8749b2.png)

![image](https://user-images.githubusercontent.com/4129185/53443272-4e8c1300-39d9-11e9-8615-2eebcd7d402e.png)

**Comment by dhenry-KCI** [comment]
Testing failed-The Health Review fee still generated even though this property is not on well/septic and the sanitation type is INBLDG-AW

![image](https://user-images.githubusercontent.com/4129185/53896035-45b2c700-4001-11e9-889a-b30794ca7dda.png)

![image](https://user-images.githubusercontent.com/4129185/53896098-5a8f5a80-4001-11e9-82fa-daff573b5f53.png)

**Comment by calequin** [comment]
Added workflow formula for fee to generate if address is on Well & Septic.

**Comment by dhenry-KCI** [comment]
parcel with public water/sewer generated Health fee but not DUSWM fee.  DUSWM review did not populate

![image](https://user-images.githubusercontent.com/4129185/54611173-d7bcc580-4a2c-11e9-9ada-b07c1a8ca0b8.png)

![image](https://user-images.githubusercontent.com/4129185/54611202-e3a88780-4a2c-11e9-9b25-5925577b7bbd.png)

![image](https://user-images.githubusercontent.com/4129185/54611287-06d33700-4a2d-11e9-8d0d-7e49f07a22dc.png)

**Comment by megisys** [comment]
Added this Issue
