### ISSUE TITLE
Rhythm for Civics - LandUse - Submit New

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#510]
Trying to create a new Land Use Application. Selected Submit a New Record.
Progress through the submittal requirement from “Choose a Record” through “Confirmation;”. 
Couldn’t submit application because New Contact lacked e-mail address
Progressed back to Record Information to update applicant e-mail address 
But couldn’t proceed back to Confirmation (clicked on “Submit,” but no progress)

System should require the user to add an email address for the additional applicants. 

Logged By: M.Rowley
Logged Date: 3.21.2019

**Comment by megisys** [comment]
SAme as Issue #527

**Comment by ABonomo21** [comment]
Christian is going to work on this with Dan West

**Comment by dhenry-KCI** [comment]
CLosing this item as its logged by Issue #527
