### ISSUE TITLE
Building - Capacity - Town Review Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#515]
The "Town Review Details" can be removed from the details page on a new capacity permit.

Logged by Lauren Englar

![image](https://user-images.githubusercontent.com/4129185/54776767-2ada7800-4be7-11e9-82e9-53cb7e455cee.png)

**Comment by megisys** [comment]
Fixed

**Comment by JuanitaMiles** [comment]
Town Details removed. Tested with L Englar
