### ISSUE TITLE
Building - Driveway - Details Page - Permit/Intake Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#516]
The details page for driveway should not let the applicant complete these details

![image](https://user-images.githubusercontent.com/4129185/54776790-35950d00-4be7-11e9-809d-c4c2f6d4c399.png)

logged tiffany martin 3/21/19

**Comment by megisys** [comment]
This is display in IPS Only.. Applicant will never see this page

**Comment by dhenry-KCI** [comment]
would like to retest this when i can see that this is not available for the public to see when applying.

Grading details were fixed where I am unable to see the ones i do not want the public seeing when entering initially. 

tm 4/4/19
