### ISSUE TITLE
Building - Grading Detail Pages

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#517]
What is highlighted in yellow is to be completed by the applicant 

What is in purple is completed by the backoffice

![image](https://user-images.githubusercontent.com/4129185/54777406-9e30b980-4be8-11e9-80a6-cac51a081cae.png)

logged by tiffany martin 3/21/19

**Comment by kellyjj** [comment]
created InforClient.AgencyCDR.BuildingApplet.GradingDetailsIntake to remove back office items for r4c

**Comment by kellyjj** [comment]
unable to create to r4c page
Error System.Exception: Could not find the given applet node in the agency personalization configuration file for moniker=InforClient.AgencyCDR.BuildingApplet.GradingDetailsIntake

**Comment by megisys** [comment]
@kellyjj - Enhancements Synced  Try now

**Comment by kellyjj** [comment]
![image](https://user-images.githubusercontent.com/27238685/55346383-363f6600-5467-11e9-85f3-4c48c8000a54.png)

**Comment by kellyjj** [comment]
success generating page for r4c.   setting to retest, and reassigning.

**Comment by dhenry-KCI** [comment]
still  needs some work tm 4/2/19

**Comment by megisys** [comment]
@kellyjj

**Comment by kellyjj** [comment]
added missing fields.  setting to retest

**Comment by dhenry-KCI** [comment]
additionally we talked about the information from the intake page pulling over to the grading details page as well. this has not been happening.

tm 4/9/19

**Comment by dhenry-KCI** [comment]
nothing has changed since my last comment on 4/9/19 tm

**Comment by megisys** [comment]
@kellyjj

**Comment by megisys** [comment]
They would like the intake page information transfer to the main page. As it is the same business object, it should just be  a detailpagekey update.

**Comment by kellyjj** [comment]
the intake detail page is now coping the info to the other detail page here.

this is ready for retest.

**Comment by dhenry-KCI** [comment]
this has been corrected 5/2/19 tm
