### ISSUE TITLE
Building - Capacity - Meter Model Quantity

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#518]
Within a capacity permit, under the details tab the meter model under the system should default the Qty. field should default to 1.

Logged by Terry May

![image](https://user-images.githubusercontent.com/4129185/54777706-4cd4fa00-4be9-11e9-9b7a-5f4d4b0cb99e.png)

**Comment by megisys** [comment]
Addressed

**Comment by JuanitaMiles** [comment]
Tested with L Englar. Confirmed fixed.
