### ISSUE TITLE
Building - Capacity - Detail Page Format

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#519]
The Water ? Subdivision fields are overlapping on the capacity detail page.

![image](https://user-images.githubusercontent.com/4129185/54777834-91609580-4be9-11e9-8d5e-677e2cb053ef.png)

**Comment by megisys** [comment]
Addressed

**Comment by JuanitaMiles** [comment]
appears correct during testing in training room. Could be a problem with the hardware/monitors. Will monitor.

**Comment by ABonomo21** [comment]
closed will monitor
