### ISSUE TITLE
License - Distributor Report - Unique Business Name

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#52]
The system red lined the user with "Name of Business must have a unique value" - System needs ability to accept multiple lines with the same business / organization 

![distributor businesses](https://user-images.githubusercontent.com/4129185/52880557-42c66400-3130-11e9-8169-e73224bcb706.png)

**Comment by megisys** [comment]
Duplicate

**Comment by JuanitaMiles** [comment]
Closing this DUPLICATE issue
