### ISSUE TITLE
Building - FRO - Project Specifics - Detail Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#520]
Board of County under Project Specifics should be changed to either Frederick County or County - this should be the same as grading.

![image](https://user-images.githubusercontent.com/4129185/54778178-5874f080-4bea-11e9-9ef1-254b11ea6c19.png)

logged by tiffany martin 3/21/19

Also, "In Town" should be changed to "Town"

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
CORRECTED 3/26/19 TM
