### ISSUE TITLE
Building - FRO - Details Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#521]
Fro should be "FRO"

![image](https://user-images.githubusercontent.com/4129185/54778581-7727b700-4beb-11e9-9026-cceb9cb8fb35.png)

logged by tiffany martin 3/21/19

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
corrected 4/4/19 tm
