### ISSUE TITLE
Building - Capacity - Meter Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#522]
Fees are not generating on a capacity permit. Please add the following meter fees (populated under the meter model)

Meter Fees E Series 1 - Value should be updated to $421.50

[IPS - meter fee corrections.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/2993593/IPS.-.meter.fee.corrections.xlsx)

**Comment by JuanitaMiles** [comment]
Correct fee populated per T May.
