### ISSUE TITLE
Building - Capacity - Subdivision Popup

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#523]
system should standardize the presentation of the field description field within IPS. Please update Clover Hill or Cloverhill to all read "CloverHill "

![image](https://user-images.githubusercontent.com/4129185/54779140-d33f0b00-4bec-11e9-9c5b-12cedeff4d34.png)

**Comment by JuanitaMiles** [comment]
Not fixed in TEST or PREPROD. Cloverhill is still two words sometimes and one word other times.
