### ISSUE TITLE
Building - Grading - Details pages - Impervious area

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#526]
Grading details - impervious area should say total impervious area Sf

![image](https://user-images.githubusercontent.com/4129185/54779909-c6231b80-4bee-11e9-8113-85d3dad33d62.png)

logged by tiffany martin 3/21/19

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
CORRECTED 3/26/19
