### ISSUE TITLE
Rhythm for Civics - Upload

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#528]
Can’t upload pdf file for drainage complaint.

Logged by: G.Hessong
Logged date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54792545-ed8cdf00-4c14-11e9-9154-76596aafee07.png)

**Comment by ABonomo21** [comment]
system allowed my to submit a PFD
