### ISSUE TITLE
License - Distributor Report - Resubmit / Complete Milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#53]
System allowed the user to select "resubmit", but the system then moved the application to the Complete Milestone. System should put the user in Awaiting Resubmit milestone

![resubmittal](https://user-images.githubusercontent.com/4129185/52880725-bd8f7f00-3130-11e9-9a11-e8d85ec1e879.jpg)

**Comment by calequin** [comment]
Fixed issue in dev.

**Comment by ABonomo21** [comment]
corrected during retest check - ab
