### ISSUE TITLE
Rhythm for Civics - Submission (Excel Issue #2)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#530]
Error message THAT CONTACT RECORD MUST HAVE EMAIL BUT I CANNOT go back and edit to add and therefore can’t submit.

duplicate of #499 

Logged by: G.Hessong
Logged date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54792642-4c525880-4c15-11e9-91ff-6a4efa07bb0a.png)

**Comment by calequin** [comment]
The additional applicant error message was fixed to populate on the same screen as the input of information. This stops the user from continuing in the application until they fix the additional contact information. Please retest

**Comment by ABonomo21** [comment]
Marked as Enhancement and R4C per Christian because in July R4C will not require send invites to additional applicants that must be accepted in order to be added, which will require an email address to be provided.

**Comment by calequin** [comment]
applicant invite has been configured in r4c

**Comment by dhenry-KCI** [comment]
related to #707 we will not be levergaing the invite applicant functionality.
