### ISSUE TITLE
Rhythm - Electric License - Upload Error

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#531]
Failed to submit an Electrical License application. Error returned uploading the file (my state license). 

Logged by: D.Taylor
Logged date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54792742-cd115480-4c15-11e9-8783-269914f26b56.png)

**Comment by megisys** [comment]
This I am closing as a duplicate.. A list of accepted document types needs to be inputted

**Comment by ABonomo21** [comment]
Not able to duplicate with PDF- closing issue however marking as a DATA issue so that follow up on the types of attachments that are accepted with R4C
