### ISSUE TITLE
Building - Major/Minor Logging - Details Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#533]
We need to add the information below to the major and minor logging permit detail pages.

![image](https://user-images.githubusercontent.com/4129185/54826604-7bed7900-4c86-11e9-808e-f1e6089586af.png)

logged by tiffany martin 3/22/19

**Comment by kellyjj** [comment]
what permit type is this on?  what is the title of detail page?  I am not able to find this

**Comment by megisys** [comment]
Grading with a WorkType of MJL or MNL

**Comment by kellyjj** [comment]
the detail page is named "Logging Conditions Details"

**Comment by kellyjj** [comment]
added 2 columns to InforClient.AgencyCDR.Building.LoggingDetail.   
PZRConservationNo (PZRCONSERVATIONNO)  PZRConservationYes (PZRCONSERVATIONYES) 

have added to the detail page as show in mock up on this issue.  

ready for retest

**Comment by dhenry-KCI** [comment]
I think that the YES, NO needs to be closer together. Also, currently there is a note below that states, "IF yes, a review and approval letter is required from the Frederick County Forestry Board."

![image](https://user-images.githubusercontent.com/4129185/55484202-15594b00-55f6-11e9-8b87-b88a270fb969.png)

![image](https://user-images.githubusercontent.com/4129185/55484409-708b3d80-55f6-11e9-95fe-ffa8edb25646.png)

tiffany martin 4/3/19

**Comment by kellyjj** [comment]
per request,  removed the "No" box.   added note "If YEs..."

changing back to retest

**Comment by dhenry-KCI** [comment]
corrected tm 4/3/19
