### ISSUE TITLE
Building - Major/Minor logging - DOI

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#534]
The declaration of intent (DOI) is a requirement for minor and major logging permit applications.

I believe Mike Wilkins is working on creating this as a separate attachment. But i do not want to forget about this item.

![image](https://user-images.githubusercontent.com/4129185/54826823-0df58180-4c87-11e9-8f87-1fa875f7cb71.png)

logged by tiffany martin 3/22/19

**Comment by ABonomo21** [comment]
on my desk - closing tm 6/20/19
