### ISSUE TITLE
Building - Major/Minor Logging - Applicant information

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#535]
The forester and operator are both required as part of the minor and major logging permit applications. The forester and operator can be the same, if applicable - but both must be provided along with their license #.

![image](https://user-images.githubusercontent.com/4129185/54826961-544ae080-4c87-11e9-87c9-acc323c0922a.png)

logged by tiffany martin 3/22/19

**Comment by megisys** [comment]
Additional Applicants. this should be fine..

**Comment by dhenry-KCI** [comment]
Currently the system doesn't require or have a space for the forester license # and operator license #

still an issue

tm 4/16/19

**Comment by ABonomo21** [comment]
closed will monitor
