### ISSUE TITLE
Building - FRO permit - Details Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#536]
The details page does not include the approved cost estimate amount to be included. Currently we require the applicant to provide this in addition with what planning provides us. 

![image](https://user-images.githubusercontent.com/4129185/54827433-5e211380-4c88-11e9-89f4-4ecb6cf194b8.png)

logged by tiffany martin 3/22/19

**Comment by megisys** [comment]
I am reviewing the database this field doesnt exist in Hansen 7.. If it does please add a screenshot of Hansen7

**Comment by dhenry-KCI** [comment]
this is not in Hansen 7 - this is on the application itself currently. 

tiffany 4/2/19

**Comment by megisys** [comment]
On Job Desctiption

**Comment by dhenry-KCI** [comment]
i guess this is ok as long as actual valuation under job description will pull from the planning AP #.

tm 4/4/19
