### ISSUE TITLE
ResUse Solar Panel Permits issuing without Electrical Permit

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#537]
Solar panel permits are still issuing without an electrical permit. Just like issue #99 this permit needs to go into a Pre Issue Permit stage until an electrical permit is applied for and attached. The stop for the Additional electrical checkbox needs to prevent it from ever getting to Issued/Inspections until the electrical permit is attached.

![image](https://user-images.githubusercontent.com/47611580/54828105-d50adc00-4c89-11e9-9b4d-73934873ce49.png)

![image](https://user-images.githubusercontent.com/47611580/54828132-e81dac00-4c89-11e9-88c8-8bb0f7a9b978.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55023461-3a850280-4fd3-11e9-96e6-992637f94192.png)
