### ISSUE TITLE
IPS first name requirement

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#538]
need to fix first name issue for all AP types

MW

**Comment by megisys** [comment]
This ticket needs more details please.. I thought we fixed this issue ?

**Comment by dhenry-KCI** [comment]
@megisys - this issue was previously addressed but is now no longer working. IPS is not generating  the PDOX user first name on those contacts without a first name.

**Comment by megisys** [comment]
Property Owners MUST have a first Name

**Comment by ABonomo21** [comment]
need to confirm with Dan, I thought this issue was address that IPS will require a first name to be entered to avoid this issue in PDOX??

**Comment by megisys** [comment]
Property Owners Have to have a First Name. This is true.. Companies do not..

**Comment by ABonomo21** [comment]
will monitor when we get back into pdox
