### ISSUE TITLE
License - Distributor Report - Monthly Sal Grid

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#54]
System should require the user to enter information into the Monthly Sales grid (Name of Business, etc.)

![dist repo- monthly sales grid](https://user-images.githubusercontent.com/4129185/52880996-748bfa80-3131-11e9-9052-e7085698943f.png)

Ashlye - please confirm. If so, label as bug and assign to Christian

**Comment by megisys** [comment]
This is not possible. I can only have the completeness check reviewer to check this.

**Comment by JuanitaMiles** [comment]
This is a DUPLICATE of issue #16 . Closing this issue as a result.
