### ISSUE TITLE
PDOX error DOLS review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#540]
error when assigning reviews.

![image](https://user-images.githubusercontent.com/4129185/54845106-e74b4100-4cae-11e9-9d5e-3c0a0e6f8c73.png)

**Comment by megisys** [comment]
This is a security Issue @dhenry-KCI @JuanitaMiles

**Comment by ABonomo21** [comment]
dan showed fix
