### ISSUE TITLE
ProjectDox- error when completing review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#543]
show stopper

![image](https://user-images.githubusercontent.com/4129185/54846038-545fd600-4cb1-11e9-97e3-3e23a42ad853.png)

MW

**Comment by dhenry-KCI** [comment]
Ashlye does not get this error on her building permit application.  I reassigned a Planning review to Ashlye and she received the same error

**Comment by dhenry-KCI** [comment]
Ashlye reassigned a building permit review to me and was able to successfully complete the review.  Problem must be on the Planning side.

MW

**Comment by megisys** [comment]
This is a timing issue.. Do not log these in the future.. If you hit these.. CALL ME !

**Comment by dhenry-KCI** [comment]
starting over with Pdox testing so I am closing this ticket.
