### ISSUE TITLE
Project Dox -Communications 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#544]
Mike nor I have received any emails from project dox notify us that some action is required. 

I did receive an email from IPS telling that a re submission was required however, no applicant actions were required in IPS, there should be a requirement in IPS for the application to be modified or detail page to be updated. Then the applicant needs to be notified from Project Dox to upload revised plans. 

![image](https://user-images.githubusercontent.com/47611580/54847166-0ef0d800-4cb4-11e9-9d96-41a2b3a46b44.png)

![image](https://user-images.githubusercontent.com/47611580/54846790-0b108600-4cb3-11e9-938f-4005f99bd1c1.png)

**Comment by megisys** [comment]
Project Dox Issue. need to understand this from Robert @dhenry-KCI

**Comment by megisys** [comment]
Robert has these turned off.

**Comment by dhenry-KCI** [comment]
closing this issue. We know Pdox notifications are being generated. need to understand when and the associated language.
