### ISSUE TITLE
Project Dox- Batch Stamp- Open reviews in IPS

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#545]
Batch stamp review populated in Project Dox while IPS still said there was an outstanding review to be resulted for DPZ Permit #239012
![image](https://user-images.githubusercontent.com/47611580/54848200-149bed00-4cb7-11e9-91bd-1c2a3fa7ffca.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/54848267-401ed780-4cb7-11e9-800f-33bd2be16645.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/54848344-6d6b8580-4cb7-11e9-8d09-df293a473bae.png)

**Comment by ABonomo21** [comment]
No reviews remain in project dox

**Comment by ABonomo21** [comment]
Cannot move forward with the application because I get the error that the review must be resulted in project dox - which is the correct thing to happen but, I am not able to progress with testing at this point. 

![image](https://user-images.githubusercontent.com/47611580/54848492-c804e180-4cb7-11e9-9821-8ddac1696751.png)

**Comment by megisys** [comment]
Did the DPZ add in Error @ABonomo21  ??

**Comment by dhenry-KCI** [comment]
@megisys the first DPZ review added correctly, the second review generated incorrectly as the first review was approved.

**Comment by megisys** [comment]
Ready for RETest
