### ISSUE TITLE
Temporary Trailer-Health Review Fee did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#548]
The Health Review fee did not generate. According to airtable, it is required.-AW

![image](https://user-images.githubusercontent.com/47611580/54924678-4f826880-4ee3-11e9-802f-c0b386ec12c7.png)

**Comment by megisys** [comment]
Ready for ReTest

**Comment by ABonomo21** [comment]
Not fixed- Health Review fee did not generate-AW
![image](https://user-images.githubusercontent.com/47611580/55484557-b0eabb80-55f6-11e9-9881-ba6d1822c679.png)
![image](https://user-images.githubusercontent.com/47611580/55484576-bba55080-55f6-11e9-98da-4200de8f5493.png)

**Comment by ABonomo21** [comment]
not fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55501008-878e5780-5617-11e9-949c-db07a4e1aeca.png)

**Comment by megisys** [comment]
T will add

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55505323-dab8d800-5620-11e9-867e-82a2a52d8ed1.png)
