### ISSUE TITLE
Building - Resuse - Building Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#55]
The system should generate a building fee for a detached garage.

AP 237173
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/52908329-b99f5200-3241-11e9-9c9b-475801081ebb.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Updated formula RESUSES_Fee_BLDGGarageOrPole_AOC to look at garage sqft field >0.

Please screenshot for proof of test (AP# 236153 in DEV)

<img width="960" alt="issue55_fixed" src="https://user-images.githubusercontent.com/47784290/53190327-4bf37d00-35d7-11e9-96d7-df8ce3c48f8e.png">

**Comment by dhenry-KCI** [comment]
confirmed fixed-aw
![image](https://user-images.githubusercontent.com/4129185/53910610-3db74f00-4022-11e9-9f10-26d83a6256bf.png)
