### ISSUE TITLE
Temporary Trailer-Permit issued after Resubmit review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#550]
The permit issued automatically after two reviews were approved and one was marked as resubmit. The resubmit fee/applicant action never generated.-AW
239014
![image](https://user-images.githubusercontent.com/47611580/54925810-717cea80-4ee5-11e9-942b-e57780c819c0.png)

**Comment by megisys** [comment]
Silly Issue.. Sorry

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55019047-84b5b600-4fca-11e9-8434-2d2c50b36ae9.png)
