### ISSUE TITLE
Res Demo & Sign permits-Resubmit Loop

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#551]
-MCoffman
Residential Demo Permit; Permit #239013
Resulted review as "Resubmit", the $26.00 revision fee generated correctly. Paid the revision fee and then resubmitted the application through Applicant Actions and a new $26.00 revision fee generated and the permit got stuck in a loop of owing a revision fee and awaiting applicant actions. The permit never went back to awaiting reviews. The log says it goes to under review, then it immediately adds another revision fee never giving you a chance to insert and result a new review.

![image](https://user-images.githubusercontent.com/47611580/54926291-61b1d600-4ee6-11e9-8d59-1e667e136d39.png)

![image](https://user-images.githubusercontent.com/47611580/54926423-aa698f00-4ee6-11e9-8ecb-b68e65b74c88.png)

Residential Demo Permit #239015
Recreated the same scenario as Permit# 239013, tried to resubmit through applicant actions before paying the review fee this time, and got stuck in the same loop. 

![image](https://user-images.githubusercontent.com/47611580/54926495-cbca7b00-4ee6-11e9-9e32-e8ea78c1d57f.png)

![image](https://user-images.githubusercontent.com/47611580/54926537-df75e180-4ee6-11e9-8709-37446269ed1d.png)

**Comment by megisys** [comment]
Addressed Issue

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55025702-d7499f00-4fd7-11e9-9288-981161623b50.png)

**Comment by ABonomo21** [comment]
After testing a second demo permit, I got stuck in the same resubmit/pay revision fee loop.-AW

![image](https://user-images.githubusercontent.com/47611580/55026610-bbdf9380-4fd9-11e9-98c8-92654d115d1f.png)
![image](https://user-images.githubusercontent.com/47611580/55026626-c437ce80-4fd9-11e9-92ac-97473f796bfb.png)

**Comment by ABonomo21** [comment]
Tried again on another permit, same result. Stuck in a resubmit/revision payment loop-AW
![image](https://user-images.githubusercontent.com/47611580/55027182-0b728f00-4fdb-11e9-89fd-8ed4e2aaf626.png)

**Comment by ABonomo21** [comment]
Testing from Emily Pearl- she got stuck in the same resubmission loop for a sign permit so the problem is not just for demo permits now-AW

![em3](https://user-images.githubusercontent.com/47611580/55099317-e0994100-5095-11e9-8844-9b5785b2e8b7.png)

**Comment by megisys** [comment]
But I can see the EPEARl - Moved this application around manually.. I tested 240058 and it works as expected.

Please Retest. Fixed Demolition

**Comment by ABonomo21** [comment]
Confirmed Fixed for Demos-AW 

![image](https://user-images.githubusercontent.com/47611580/55349004-8f6ac200-5486-11e9-80ef-b3d0733631ca.png)

![image](https://user-images.githubusercontent.com/47611580/55349034-a7424600-5486-11e9-97b0-563ee56e2883.png)
