### ISSUE TITLE
Permanent Trailer-DUSWMF Review 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#552]
The DUSWMF review generated when according to airtable, it should not have-AW

![image](https://user-images.githubusercontent.com/47611580/54926802-6e82f980-4ee7-11e9-8cbc-4fc05103a1f9.png)

**Comment by megisys** [comment]
SO Never DUSWM.. I am removing it from ALL Trailer Applications. Done

**Comment by ABonomo21** [comment]
confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55018960-533cea80-4fca-11e9-9ee0-4058e9e8943e.png)
