### ISSUE TITLE
Trailer Electrical Permit-Too many inspections

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#553]
For an Electrical permit, too many inspections generated. According to airtable, only the Temp Service, Underground, and Final inspections should generate.-AW

#239018
![image](https://user-images.githubusercontent.com/47611580/54928639-99bb1800-4eea-11e9-948c-d9ac8b15b8cc.png)

**Comment by megisys** [comment]
ReTest

**Comment by ABonomo21** [comment]
This issue is half fixed. The other inspections are gone as they are supposed to be but the Underground inspection, which is required, is also gone. The Underground inspection needs to come back.-AW
![image](https://user-images.githubusercontent.com/47611580/55501523-94f81180-5618-11e9-8df5-c452ce3c6f4a.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55729993-38647000-59e5-11e9-89b4-9961cccef86e.png)
