### ISSUE TITLE
General-Inserting Fees/Review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#554]
Example Permit# 239019: Inserted Additional Review: permit issued
If while doing a completeness check we determine that a permit needs an additional review by a department that would not normally generate, and we need to insert the additional fee/review this permit should not move forward to issued/inspections until the additional fee is paid and the inserted review is approved. Are there steps that the tech can take to prevent this from happening or is this something that needs to be configured in IPS11? -MCoffman

![image](https://user-images.githubusercontent.com/47611580/54930923-827e2980-4eee-11e9-861f-b574e6e583f7.png)

**Comment by megisys** [comment]
This is not valid.. As it would be no longer in Project Dox.. You would put the application on Hold until the review was completed.. But as mentioned if this started life in Project Dox. You will never be able to result the review.. @ABonomo21

**Comment by ABonomo21** [comment]
Dan- We retested and have questions. 

In the event at completeness check for project dox we determine there is an additional agency review and fee that needs to be added, we will approve the completeness check with eplans, add the fee right away and then we can confirm the correct reviews were populated and if we need to add the additional reviews we will do so after the prescreen review through project dox. 

In the event at completeness check for internal review, we determine there is an additional agency fee and review that needs to be added, we will approve the completeness check review with internal plans, add the fee right away. 

Where we are hung up and need your guidance is the following:

How will the techs know when the fees have been paid and reviews need to be assigned if it is internal review? If the system will not auto populate this data, is there something that will need to be placed in our my infor viewer to notify staff when reviews have populated? 
If so they can add any additional reviews at the under review milestone, then the system should not progress to inspection milestone until all reviews are approved. Regardless of manual insert or auto-generation. 

Is IPS going to be configured to auto populate reviewers and due dates? 

We some clarification on the this as it could affect projects and permits. I understand it is that 1%.

**Comment by ABonomo21** [comment]
Need an ad hoc report for under review my dashboard
