### ISSUE TITLE
General-Zoning fee generating for property within Incorporated Town

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#556]
This permits property is within an incorporated town, and the parcel is marked as such but the zoning fee still generated when it shouldn't.-AW
![image](https://user-images.githubusercontent.com/47611580/54932954-21f0eb80-4ef2-11e9-9dc8-5cdb5bf1f6b8.png)

![image](https://user-images.githubusercontent.com/47611580/54932966-261d0900-4ef2-11e9-9dd9-ffa206401926.png)

![image](https://user-images.githubusercontent.com/47611580/54932976-2c12ea00-4ef2-11e9-8119-0fc5a078aab3.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
confirmed fixed, -Aw

![image](https://user-images.githubusercontent.com/47611580/55483807-5dc43900-55f5-11e9-94da-7d0fe023af3b.png)
