### ISSUE TITLE
Planning - Subdivision Code

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#557]
We need to track in IPS the subdivision code/Site Plan number for each project. 
Currently in Hansen we use Code Definitions - Code S - Subdivision to add new subdivisions that have no development activity. Each project has a dedicated number that follows the life of that property. We cannot rely on parcel boundary, project name or tax ID numbers as they can change. AReed

![image](https://user-images.githubusercontent.com/4129185/54934679-4e5a3700-4ef5-11e9-98ad-3b401cb6673f.png)

**Comment by megisys** [comment]
This Functionality has now been added..

**Comment by dhenry-KCI** [comment]
verified in all planning application types. Closed. AReed
