### ISSUE TITLE
Contact Types

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#558]
Would like to be able to add additional contact types for the additional applicants field, i.e. plumber, electrician, MHIC, Home builder etc. 

![image](https://user-images.githubusercontent.com/47611580/54942789-38a13d80-4f06-11e9-9fc0-aceceaca9457.png)

**Comment by mmbanong** [comment]
Plumber, Electrician, MHIC and Home builder have been added as additional contact types
Ashley can you send me the complete list additional contact types you would like to see

**Comment by mmbanong** [comment]
?

**Comment by ABonomo21** [comment]
Can you make all of them consistent with one another i.e. either capitalize all or don't, see employee in this example below compared to all the others added. 

Please make the contact type for home builder read: home bld 

![image](https://user-images.githubusercontent.com/47611580/55506583-ccb88680-5623-11e9-8126-50f437280f5c.png)

Please add Applicant as a contact type. 

I currently do not have a complete list however as I find more that are needed I will add them.

**Comment by ABonomo21** [comment]
can we confirm who is using MFG and Vend ? otherwise please expired them.

**Comment by megisys** [comment]
Resolved

**Comment by ABonomo21** [comment]
confirmed correct
