### ISSUE TITLE
Building - ResUse - Health Dept. Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#56]
The system should generate a Health Review (and Health Fee) for ResUse properties on well and septic.

AP 237173 (same on AP 237177)
Logged by A. White

![image](https://user-images.githubusercontent.com/4129185/52908348-21ee3380-3242-11e9-94be-c871af02a584.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Updated config to add Health review during Under Review milestone. Health fee was already adding correctly, so no changes were needed. See screenshots for proof of testing (AP#236142)

**Health Fee:**
<img width="960" alt="issue56_healthfee" src="https://user-images.githubusercontent.com/47784290/53118848-09b93580-351c-11e9-9e90-6965eb711799.png">

**Health Review:**
<img width="960" alt="issue56_healthreview" src="https://user-images.githubusercontent.com/47784290/53118866-163d8e00-351c-11e9-9ec6-fee6d57d3326.png">

**Comment by dhenry-KCI** [comment]
Confirmed Fixed-AW

![image](https://user-images.githubusercontent.com/4129185/53819053-2a7b8500-3f37-11e9-97c9-2c015dc0bc39.png)

![image](https://user-images.githubusercontent.com/4129185/53819079-35ceb080-3f37-11e9-9cd9-49ca6f90ff22.png)
