### ISSUE TITLE
R4C PLANNING - PWCONSTRUC - DUSWM Lines vs Facilities fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#560]
On the PWCONSTRUC applications:
CMBDEVIMP - CMBSWMIMP - PWIPPLAN 
DUSWM fee could be for Lines $325 or Facilities $500.
IPS is supposed to be configured to pull from the parcel layer. The fees currently populate from selections on the details page
Need to discuss how to address this fee issue.
Areed
![image](https://user-images.githubusercontent.com/4129185/54945278-d2b7b480-4f0b-11e9-8cd9-ded472f29d96.png)

**Comment by dhenry-KCI** [comment]
On PWCONSTRUC Work Type CMBDEVIMP - CMBSWMIMP - PWIPPLAN will need to be a visible field for the applicant to fill out in R4C

**Comment by dhenry-KCI** [comment]
AReed discussed previous comment with DGrendon on 4/2/19

**Comment by dhenry-KCI** [comment]
R4C Testing to verify fields available on CMBDEVIMP - CMBSWMIMP - PWIPPLAN

**Comment by calequin** [comment]
Fields are available in rhythm.
![image](https://user-images.githubusercontent.com/47603568/57414413-9c817c00-71bd-11e9-89bf-eea475334bcf.png)
