### ISSUE TITLE
Plumbing License- State License Expiry

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#561]
Changed state license expiry date in the system and it did not change the milestone from an active status. If the state license date is prior to today, the license should change to an inactive status. 

![image](https://user-images.githubusercontent.com/47611580/54945664-c08a4600-4f0c-11e9-8f8f-d54911886c7f.png)

**Comment by megisys** [comment]
No That is a nightly Job.. Not in this functionality piece

**Comment by ABonomo21** [comment]
I need to see this functionality work once batch manager is up and running.

**Comment by goggansd** [comment]
Batch job has been created, but for now please run the task manually (@megisys says it will be configured as a nightly job prior to Go Live):

![image](https://user-images.githubusercontent.com/28841997/55585755-6308ad00-56f5-11e9-8061-7809e9658bd8.png)
