### ISSUE TITLE
Plumbing License- Expiry Log

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#562]
Inserted a log entry of change expiration date and set date to yesterday. 

The license remained in an active status. 
![image](https://user-images.githubusercontent.com/47611580/54945835-2080ec80-4f0d-11e9-8b3f-0e6f2d8435c9.png)

**Comment by megisys** [comment]
This is correct.. IT wont move from here.. It just moved the application expiry date..

**Comment by ABonomo21** [comment]
I need to test this once batch manager is working! I need to see the change in milestone to expired....
