### ISSUE TITLE
Planning-PWConstruct

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#563]
stuck in review milestone after resulting all reviews.  MW

![image](https://user-images.githubusercontent.com/4129185/54945815-14952a80-4f0d-11e9-9e49-fe0521e9ee86.png)

**Comment by megisys** [comment]
What does check status say ?

**Comment by dhenry-KCI** [comment]
Missing DPZ approval - Issue resolved - Areed PW237924
