### ISSUE TITLE
PLANNING - PWCONSTRUC REVMJIMPRV - fee health

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#564]
REVMJIMPRV
Health Fee $1 populated in error. DUSWM parcel ID. Remove health fee
![image](https://user-images.githubusercontent.com/4129185/55010804-41a01680-4fbb-11e9-9e09-f5265b652be9.png)
![image](https://user-images.githubusercontent.com/4129185/55010823-4f559c00-4fbb-11e9-8cbb-adcff087e92c.png)

**Comment by megisys** [comment]
ready..

**Comment by dhenry-KCI** [comment]
Health fee was removed from water/sewer parcel but still populated in error as extra $1 fee on well/septic parcel under PW239004
![image](https://user-images.githubusercontent.com/4129185/55340107-0053af00-5472-11e9-99ee-b1fc9849845c.png)
AREED

**Comment by dhenry-KCI** [comment]
fixed per PW239123

MW
