### ISSUE TITLE
Building - Major Grading - Intake Review - Grading Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#565]
Did not get a redline for SWM to be linked even though under grading details the stormwater involved box was checked.

![image](https://user-images.githubusercontent.com/4129185/55020895-2c80b300-4fce-11e9-954e-a54390d0ae3b.png)

![image](https://user-images.githubusercontent.com/4129185/55020762-e4fa2700-4fcd-11e9-814a-5d1fdb7d0c7b.png)

However, if I choose a stormwater subcategory it then requires a child SWM to be linked

![image](https://user-images.githubusercontent.com/4129185/55021040-76699900-4fce-11e9-9fc8-e8bc5b931c84.png)

logged  by tiffany martin 3/26/19

**Comment by megisys** [comment]
PLease Restest

**Comment by dhenry-KCI** [comment]
corrected 4/2/19 tm
