### ISSUE TITLE
Building - Major Grading - Bulk Add/Group Add - Error Message

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#566]
I get this error message when trying to group add two permits (MJ/SWM) to this permit. 

![image](https://user-images.githubusercontent.com/4129185/55021541-4ec70080-4fcf-11e9-9a1d-323b429b28ad.png)

**Comment by megisys** [comment]
Do not Select the Details option. As we need these to be re added

**Comment by dhenry-KCI** [comment]
corrected tm 4/9/19
