### ISSUE TITLE
Building - Major Grading - - Grading Details -  Intake Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#569]
We got a redline for PI even though no grading details were marked.

![image](https://user-images.githubusercontent.com/4129185/55024786-f0e9e700-4fd5-11e9-9958-788d1654f5e3.png)

![image](https://user-images.githubusercontent.com/4129185/55024807-ff380300-4fd5-11e9-8cf1-fb08626b20e8.png)

AP # 240049

logged by tiffany martin 3/26/19

**Comment by kellyjj** [comment]
have updated all 38 formulas.

**Comment by kellyjj** [comment]
generated ppage for r4c

![image](https://user-images.githubusercontent.com/27238685/55358800-16b73600-5485-11e9-85dc-d60a27e58af1.png)

**Comment by dhenry-KCI** [comment]
corrected 4/2/19 tm
