### ISSUE TITLE
PLANNING - Verification Letters - Review Comments Requirement

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#571]
Currently, any time I try make an update to a review, this includes trying to Assign a Reviewer and resulting the review with an Approved result, I get the notification that I must provide the customer with review comments. This "add comments" requirement should only be required for a Review Result other than Approved.

![image](https://user-images.githubusercontent.com/31770504/55025819-10820f00-4fd8-11e9-8125-2adf1ad35a09.png)

![image](https://user-images.githubusercontent.com/31770504/55025554-846fe780-4fd7-11e9-82b7-02dab45856ab.png)

(Issue identified by Juanita Miles 3/26/19)

**Comment by dhenry-KCI** [comment]
Bug still exists - Retest Failed - AREED
Lot of record VP238959
Subdivision potential VP238961
Site plan verify VP238963
Zoning Verification VP238964
![image](https://user-images.githubusercontent.com/4129185/55081399-2e05b600-5076-11e9-82c3-a39a4d5b2311.png)
![image](https://user-images.githubusercontent.com/4129185/55081504-5b526400-5076-11e9-801c-64af2cbd9f95.png)
![image](https://user-images.githubusercontent.com/4129185/55081604-88067b80-5076-11e9-947f-bc77fbf6c6d5.png)
![image](https://user-images.githubusercontent.com/4129185/55081692-b7b58380-5076-11e9-8e55-284a3183abe7.png)

**Comment by dhenry-KCI** [comment]
reviewed with mike, ok with comments on approval
