### ISSUE TITLE
Planning-site plan-type III

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#572]
generated a type I and type III fee.  Only fee on a type III is the $210.00 fee

![image](https://user-images.githubusercontent.com/4129185/55026009-75d60000-4fd8-11e9-8158-34eb781bfcb1.png)

MW

**Comment by megisys** [comment]
Please Restest

**Comment by dhenry-KCI** [comment]
fixed per SP239008

MW
