### ISSUE TITLE
Planning-site-type II

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#573]
the type I planning fee is populating in addition to the type II fee.  The $2,304 fee should be populating.  Same issue with Type III site plan previously logged.

![image](https://user-images.githubusercontent.com/4129185/55026515-876bd780-4fd9-11e9-977f-87a1765050a3.png)

MW

**Comment by megisys** [comment]
Ready for ReTest

**Comment by dhenry-KCI** [comment]
fixed per SP239009

MW
