### ISSUE TITLE
PLANNING - Verification Letters - Applicant Not Required on Start Application

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#574]
When starting a Verification Letter application, the system does not require any Applicant Information on the Applicants tab. Although the application will pull the Property Owner from the Parcel entered, the system also does not require a Parcel to be entered, therefore, the application could be submitted without a Site or a Applicant. This seems like a problem....

![image](https://user-images.githubusercontent.com/31770504/55026425-60ada100-4fd9-11e9-9c27-47e72c91942e.png)

![image](https://user-images.githubusercontent.com/31770504/55026476-7622cb00-4fd9-11e9-9dde-01289d681f91.png)

![image](https://user-images.githubusercontent.com/31770504/55026530-8fc41280-4fd9-11e9-8688-dfa72ae061c7.png)

![image](https://user-images.githubusercontent.com/31770504/55026617-bf731a80-4fd9-11e9-839d-b45075579fac.png)

**Comment by JuanitaMiles** [comment]
This is also an issue for APFO, NID, PREPLAT, YARDMOD applications.

**Comment by megisys** [comment]
This is addressed. Was not seen as an issue as they were going to be forced during intake at the Rhtyhm level and county staff start with an address.. Closed this loop

**Comment by dhenry-KCI** [comment]
verified on Lot of record VP238959
Subdivision potential VP238961
Site plan verify VP238963
Zoning Verification VP238964
Areed
Now requires: 
![image](https://user-images.githubusercontent.com/4129185/55080191-13324200-5074-11e9-8c1b-7f253cc9958b.png)
