### ISSUE TITLE
planning-site-type I

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#575]
site plan residential fee shouldnt be the same as the base planning site plan fee.  Residnetial should $10 per lot or dwelling unit, whichever is greater

![image](https://user-images.githubusercontent.com/4129185/55026913-59d35e00-4fda-11e9-8db5-1b24149080e6.png)

MW

**Comment by megisys** [comment]
PLease Retest this.. I am expecting this to potential be wrong.. but need to know..

**Comment by dhenry-KCI** [comment]
Looks like the system is just charging the base site plan fee twice ($2,304)

Below is a Residential mixed use occ type.
![image](https://user-images.githubusercontent.com/4129185/55347499-0f8f2880-5483-11e9-830e-f0cdad724f05.png)

Then I tried this nonres business
![image](https://user-images.githubusercontent.com/4129185/55347765-917f5180-5483-11e9-88d6-f824a0ca26c1.png)

This one is restow
![image](https://user-images.githubusercontent.com/4129185/55347866-c9869480-5483-11e9-8bd1-e238d2653675.png)

For residential work types fee should be the based $2304 plus $10 per lot or dwelling unit.

For non-res fee should be $2304 plus $92 per disturbed acre


MW
