### ISSUE TITLE
Trade License - Electrical

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#576]
Can we please correct the language under license details that says "if applicable" to say "if applicable, please complete state license data"
The clarification is necessary because I don't want anyone to interpret it the company details as "if applicable" all of them require a company. 

![image](https://user-images.githubusercontent.com/47611580/55027107-db2af080-4fda-11e9-8a86-ee5e1e7e3a2d.png)

**Comment by megisys** [comment]
Fixed

**Comment by ABonomo21** [comment]
better
