### ISSUE TITLE
Trade License- Plumbing, Utility, Appliance and Misc. Detail Pages

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#577]
Move all detail pages for plumbing trade licenses (appliance, plumbing, misc, utility) to the from "Start License" tab with the internal only comment like the electrical, see below. 

![image](https://user-images.githubusercontent.com/47611580/55027779-753f6880-4fdc-11e9-96ac-1d5071c30d28.png)

This is more efficient for techs who may have to process licenses in the office instead of waiting to complete those details at completeness check like R4C process.

**Comment by megisys** [comment]
Retest Please

**Comment by ABonomo21** [comment]
confirmed fixed-aw

![image](https://user-images.githubusercontent.com/47611580/55351021-54b75880-548b-11e9-87f4-659588e67517.png)
![image](https://user-images.githubusercontent.com/47611580/55351150-96e09a00-548b-11e9-983c-7dcca38d95fe.png)
![image](https://user-images.githubusercontent.com/47611580/55351174-a4961f80-548b-11e9-87ee-6d904f62ce3a.png)
![image](https://user-images.githubusercontent.com/47611580/55351215-b8da1c80-548b-11e9-8cad-bace6bd9ef13.png)
![image](https://user-images.githubusercontent.com/47611580/55351231-c1325780-548b-11e9-94f8-40c5e2538ff3.png)
