### ISSUE TITLE
Notifications for Additional Applicant not receiving emails

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#580]
#240058- Emily added an additional applicant (Abbie White) but only Emily is receiving email notifications from IPS. Abbie(me) did not receive any emails regarding this permit even though I was listed as an applicant.-AW

**Comment by megisys** [comment]
For all Notifications where additional applicants are effective and not expired. And not in role of PLANSUBMIT as this will be a duplicate.

**Comment by ABonomo21** [comment]
All applicants should receive notifications - email address should be required for all applicants.

**Comment by dhenry-KCI** [comment]
will need to confirm flag fix with post Go-Live

**Comment by dhenry-KCI** [comment]
will reopen ticket as go-live approaches
