### ISSUE TITLE
use-home occ

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#581]
created application in R4C.  This generated a completeness check review which was resulted with approved.  This generated the fee which was paid in R4C. IPS automatically finalized the application without generating an agency review.

![image](https://user-images.githubusercontent.com/4129185/55095970-6e256280-508f-11e9-8cb0-c373d30337a5.png)

MW

**Comment by kellyjj** [comment]
this is a result of the detail page created for r4c.   old formulas were not referencing the new detail page.  
will post all new code to issue, and reassign.   this was for the use permit type HOMEOCCUP

**Comment by kellyjj** [comment]
names and updated sc for formulas changed in http://wh-ipsdevtst/ipstest/ 
++++++++
USE_HomeOccupDetails_SCF


'kjj 4-1-19  added to the if then statement to look for other detail page

Dim res as Result
StateCheck = True

For Each detailPage as Hansen.CDR.Use.IApplicationDetail in oUseApp.ApplicationDetails
If detailpage.ApplicationDetailType.ClassName="InforClient.AgencyCDR.UseApplet.HomeOccupationDetails" or detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupancyIntakeDetails" then
	Dim HomeDetail as InforClient.AgencyCDR.Use.HomeDetail
	HomeDetail = InforClient.AgencyCDR.Use.HomeDetail.GetInstanceFromParent (detailpage, res)
	If HomeDetail.SectionComplete.Code = "Y" then
				StateCheck = False
		End if
	End if
Next

+++++++++++++++++++++++++++++++++++++++++++++

USE_HomeOccupDOLSReview_AOC

'  Formula Name: USE_HomeOccupDOLSReview_AOC
'  Description: Adding reviews based on ap type and if a resubmit was resulted.
'  Created By: Christian Alequin
'  Created On: 12/20/2018
'
'  Revisions
'  ---------
'  IM - Initial Design
'kjj 4-1-19  added to the if then statement to look for other detail page



Dim res as Result
AddOnCondition = False

'Find last review of this type
Dim rev as Hansen.CDR.Use.IReview
Dim mostRecentRev as Hansen.CDR.Use.IReview
mostRecentRev = ServerApplication.NewComponent(of Hansen.CDR.Use.IReview)

'Get latest review    
For each rev in oUseApp.Reviews
If rev.ReviewType.Code.StartsWith("DOLS") and rev.addeddatetime >= mostRecentRev.addeddatetime Then    
           mostRecentRev = rev
  End If
Next

'this adds most recent resubmittal review
If mostRecentRev.ReviewKey > 1 Then
    If mostRecentRev.ReviewResult.Code.Trim.ToUpper = "RESUBMIT" Then
            AddOnCondition = True
		End If
Else
For Each detailpage as Hansen.CDR.Use.IApplicationDetail in oUseApp.ApplicationDetails
If detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupationDetails" or detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupancyIntakeDetails"  then
	
	Dim oHomeDetail as InforClient.AgencyCDR.Use.HomeDetail
	oHomeDetail = InforClient.AgencyCDR.Use.HomeDetail.GetInstanceFromParent (detailpage, res)
	
	if oHomeDetail.ImpactType.Code = "IMPACT" Then

		AddOnCondition = True
	End If
End If
Next
	
End If


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

USE_HomeOccupDPZReview_AO

'  Formula Name: USE_HomeOccupDPZReview_AOC
'  Description: Adding reviews based on ap type and if a resubmit was resulted.
'  Created By: Christian Alequin
'  Created On: 12/20/2018
'
'  Revisions
'  ---------
'  IM - Initial Design
'kjj 4-1-19  added to the if then statement to look for other detail page


Dim Res as Result

AddOnCondition = False

'Find last review of this type
Dim rev as Hansen.CDR.Use.IReview
Dim mostRecentRev as Hansen.CDR.Use.IReview
mostRecentRev = ServerApplication.NewComponent(of Hansen.CDR.Use.IReview)

'Get latest review    
For each rev in oUseApp.Reviews
If rev.ReviewType.Code.StartsWith("DPZ") and rev.addeddatetime >= mostRecentRev.addeddatetime Then    
           mostRecentRev = rev
  End If
Next

'this adds most recent resubmittal review
If mostRecentRev.ReviewKey > 1 Then
    If mostRecentRev.ReviewResult.Code.Trim.ToUpper = "RESUBMIT" Then
            AddOnCondition = True
		End If
Else
For Each detailpage as Hansen.CDR.Use.IApplicationDetail in oUseApp.ApplicationDetails
If detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupationDetails" or detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupancyIntakeDetails"  then
	
	Dim oHomeDetail as InforClient.AgencyCDR.Use.HomeDetail
	oHomeDetail = InforClient.AgencyCDR.Use.HomeDetail.GetInstanceFromParent (detailpage, res)
	
	if oHomeDetail.ImpactType.Code = "IMPACT" or oHomeDetail.ImpactType.Code = "NOIMPACT" Then

		AddOnCondition = True
	End If
End If
Next
	
End If


++++++++++++++++++++++++++++++++++++++++++++++++++++++++

USE_HomeOccupImpactInsp_AOC

'Formula Name: USE_HomeOccupImpactInsp_AOC
'Description: add inspection if Impact worktype is selected
'kjj 4-1-19  added to the if then statement to look for other detail page

Dim res as Result

For Each detailpage as Hansen.CDR.Use.IApplicationDetail in oUseApp.ApplicationDetails
If detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupationDetails" or detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupancyIntakeDetails" then
	
	Dim oHomeDetail as InforClient.AgencyCDR.Use.HomeDetail
	oHomeDetail = InforClient.AgencyCDR.Use.HomeDetail.GetInstanceFromParent (detailpage, res)
	
	if oHomeDetail.ImpactType.Code = "IMPACT" Then

		AddOnCondition = True
	Else
		AddonCondition = False
	End If
End If
Next

++++++++++++++++++++++++++++++++++++++++++++++++++++

USE_ImpactFees_AOC

'kjj 4-1-19  added to the if then statement to look for other detail page
Dim res As result

For Each detailpage As Hansen.CDR.Use.IApplicationDetail In oUseApp.ApplicationDetails

	If detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupationDetails" Or detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.UseApplet.HomeOccupancyIntakeDetails" Then

		Dim oHomeDetail As InforClient.AgencyCDR.Use.HomeDetail

		oHomeDetail = InforClient.AgencyCDR.Use.HomeDetail.GetInstanceFromParent(detailpage, res)

		If oHomeDetail.ImpactType.Code = "IMPACT" Then

			AddOnCondition = True

		Else

			AddOnCondition = False

		End If

	End If

Next

**Comment by ABonomo21** [comment]
confirmed corrected.
