### ISSUE TITLE
Rhythm for Civics-Error Message when trying to pay fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#582]
Emily was trying to pay her permit fees when she received this error message she was supposed to be redirected to Govultion payment site. (I attempted to pay fees and was able to get through to the site to pay)-AW

![em](https://user-images.githubusercontent.com/47611580/55098429-1d643880-5094-11e9-945d-4ca5df99bdae.png)

**Comment by calequin** [comment]
Please retest. I was unable to replicate this issue after updating our rest services with a longer timeout period. We also had the payment and rhythm synced together to fix any of these issues.

**Comment by ABonomo21** [comment]
Unable to duplicate- closed issue will marked as will monitor.
