### ISSUE TITLE
Sign Permit-Received Town Details Review generated when property is not in a town

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#583]
The town details reviews generated when this property is not located within a incorporated town-Permit from EP. Logged by AW
![em 2](https://user-images.githubusercontent.com/47611580/55098761-d6c30e00-5094-11e9-82bf-9bc7316aee0c.png)

**Comment by megisys** [comment]
It is becasue this address has no Tax id (Parcel) so therefore. It doesn't know where it is/./

**Comment by ABonomo21** [comment]
Removing ready for retest and closing as this is only a data issue. Reviews are working correctly for addresses that have their correct parcels. -AW
