### ISSUE TITLE
Rhythm for Civics - FRO Permit - Pay Fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#585]
User made payment on a FRO permit. After processing, system presented the user with the following error.

![SQL Exception](https://user-images.githubusercontent.com/4129185/55102563-0d048b80-509d-11e9-8589-3c31cca6cef7.png)

R4C and IPS both showed that the user had paid (which is correct).

**Comment by calequin** [comment]
This was fixed with a Rest Services server timeout period change. Please retest

**Comment by ABonomo21** [comment]
Emily was not able to pay a Fee on a Fro Permit # 240653 in R4C - got the following error 

![image](https://user-images.githubusercontent.com/47611580/58047678-b3f22a80-7b16-11e9-9d83-e190d87913c8.png)

**Comment by megisys** [comment]
Not the same issue. This is a GoVolution  Error.
