### ISSUE TITLE
Non Res-Tank-Duplicate Inspection when adding Inspections 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#586]
On the Inspection Type Popup there are duplicate fire final inspections. They also have some of the code descriptions in the inspection descriptions. -AW

![image](https://user-images.githubusercontent.com/47611580/55161511-15f86a00-513c-11e9-9b33-7db5f25402d4.png)

**Comment by megisys** [comment]
This will be cleaned up after go live
