### ISSUE TITLE
Trailer-Revision Fee/Review automatically added

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#587]
permit #240075. I had approved all the reviews, when a $26 revision fee automatically generated and forced me in to a Applicant Revision and forced me to add a second Building Plan Review and approved it again. This should have never generated since I did not put any of the reviews as Resubmit.-AW
![image](https://user-images.githubusercontent.com/47611580/55168159-b3f23180-5148-11e9-82f4-7f11fb3f9075.png)
![image](https://user-images.githubusercontent.com/47611580/55168243-da17d180-5148-11e9-85c5-b68ea9425fe7.png)

**Comment by megisys** [comment]
ready for Retest.. System should ask you to add at least one review

**Comment by ABonomo21** [comment]
Not Fixed- After approving all my reviews it is still asking for a $26 revision fee and then the applicant revisions and then a second review to be added. I approved all my reviews so I am not sure as to why it is asking for another revision fee/review-AW
![image](https://user-images.githubusercontent.com/47611580/55487246-beef0b00-55fb-11e9-8e69-70cd89ba70ca.png)
![image](https://user-images.githubusercontent.com/47611580/55487346-ee9e1300-55fb-11e9-911e-5a8e7b2a4947.png)
![image](https://user-images.githubusercontent.com/47611580/55487427-10979580-55fc-11e9-8ce9-014f75d1db2f.png)
![image](https://user-images.githubusercontent.com/47611580/55487509-3ae95300-55fc-11e9-97dd-e527f6535721.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55498400-7f331e00-5611-11e9-96ed-4a7a17a9bf43.png)
