### ISSUE TITLE
ResUse-Addition-Electrical permit required prior to issuance.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#589]
My permit is stuck in the "Pending Issuance" stage until an electrical permit is attached as a child permit. The "Additional Electric" box is checked for the permit but it should not prevent the permit for an addition to issue. -AW

#240079
![image](https://user-images.githubusercontent.com/47611580/55178045-03415d80-515b-11e9-89f8-6ce794fde450.png)
![image](https://user-images.githubusercontent.com/47611580/55178066-12281000-515b-11e9-93e1-9b889878a045.png)

**Comment by megisys** [comment]
Ready for Retest

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55500434-52cdd080-5616-11e9-8b62-4bf8937282bd.png)
