### ISSUE TITLE
Project - Blanket - Add Letter Prefix to Application Number

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#59]
We need to add a two letter prefix to the blanket application number. The prefix should be "MH".

**Comment by megisys** [comment]
@ABonomo21 @dhenry-KCI  - Ashlye said she didn't want letter prefixes. Please Provide the rules here. And assign to Frederick County IT. This is a Business as Usual type Issue

**Comment by ABonomo21** [comment]
They can have a two letter prefix. I do not want all a/p types to have prefixes however there are certain a/p's that do have prefixes for example DL for distributor license and PM for plumbing master license. 

AB

**Comment by JuanitaMiles** [comment]
I made this update in IPS TEST. Ready for testing.

**Comment by ABonomo21** [comment]
corrected
