### ISSUE TITLE
Home Occupation-No Impact-Zoning Fee generated

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#590]
The zoning fee generated when it should not have. This is a no impact home occupation and only the $26 filing fee should have generated.-AW

![image](https://user-images.githubusercontent.com/47611580/55183637-9f249680-5166-11e9-8745-b16bd77cda14.png)

![image](https://user-images.githubusercontent.com/47611580/55183655-ab105880-5166-11e9-9ea2-dc89e46d4f6f.png)

**Comment by kellyjj** [comment]
![image](https://user-images.githubusercontent.com/27238685/55338606-eefca980-5455-11e9-89d0-828098293a98.png)

the fee is always going to add as there is no formula to dictate add on conditions.   rules for adding on fee need to be put into issue for fix.

**Comment by megisys** [comment]
Ready for Retest

**Comment by ABonomo21** [comment]
Confirmed Fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55346379-5a5b7100-5480-11e9-8aca-1a4ad180be51.png)
