### ISSUE TITLE
Sign Permit-BLDG APPLog not being recognized

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#592]
The BLDG APPLog is not being recognized and due to this the permit will not move forward past the completeness check.-aw

![1](https://user-images.githubusercontent.com/47611580/55345848-ec627a00-547e-11e9-939c-e7b736905b00.png)

**Comment by kellyjj** [comment]
I will investigate

**Comment by kellyjj** [comment]
this was tested in http://wh-ipsdevtst/ipstest/  and adding the log BLDGAPP satisfied the status check.

this  issue is not reproducible.

**Comment by kellyjj** [comment]
accidently closed.   reopening and sending to https://github.com/dhenry-KCI

**Comment by ABonomo21** [comment]
Not Fixed-the BldgApp Log hold requirement did not generate and the permit was able to issued without it ever being mentioned.-AW
![image](https://user-images.githubusercontent.com/47611580/55481975-8813f780-55f1-11e9-92f7-400821843743.png)

**Comment by ABonomo21** [comment]
fixed-AW

![image](https://user-images.githubusercontent.com/47611580/55499519-33ce3f00-5614-11e9-805e-ff23a2394ff4.png)
![image](https://user-images.githubusercontent.com/47611580/55499602-62e4b080-5614-11e9-8812-6d648ac25563.png)
