### ISSUE TITLE
Building - Trailer - Town Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#593]
System generating an additional zoning fee for a Temp Trailer. 
For both Temp and Permanent Trailers Types the system should not generate a zoning review fee if the address is in an incorporated town.

#240088
Logged by Dana Taylor

**Comment by ABonomo21** [comment]
Not Corrected; Zoning fee still generated on trailers where the property is within an incorporated town-MCoffman

Permit# 240159-Temporary Construction Trailer-Not Corrected
![image](https://user-images.githubusercontent.com/47611580/55485657-e0022c80-55f8-11e9-8ca6-971c52078b2a.png)

Permit# 240160-Permanent Classroom Trailer-Not Corrected
![image](https://user-images.githubusercontent.com/47611580/55486044-9f56e300-55f9-11e9-8f0b-2aa1f9a2edbe.png)

**Comment by ABonomo21** [comment]
Not Corrected; Zoning fee still generated on trailers where the property is within an incorporated town-MCoffman

Permit# 240159-Temporary Construction Trailer-Not Corrected
![image](https://user-images.githubusercontent.com/47611580/55485657-e0022c80-55f8-11e9-8ca6-971c52078b2a.png)

Permit# 240160-Permanent Classroom Trailer-Not Corrected
![image](https://user-images.githubusercontent.com/47611580/55486044-9f56e300-55f9-11e9-8f0b-2aa1f9a2edbe.png)

**Comment by megisys** [comment]
Sorry Please Restest

**Comment by ABonomo21** [comment]
Not fixed-AW
Temp Trailer in a town-
![image](https://user-images.githubusercontent.com/47611580/55493037-42adf500-5606-11e9-896d-9903ce6b7f3f.png)

Permanent trailer in a town.
![image](https://user-images.githubusercontent.com/47611580/55493223-8f91cb80-5606-11e9-9bee-4b6920b41d2b.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55497366-38442900-560f-11e9-974f-8864d048f59b.png)
