### ISSUE TITLE
Planning - PWCONSTRUC - Fees Work Type CMBDEVIMP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#595]
Missing Engineering Fee $447
PW239034

![image](https://user-images.githubusercontent.com/4129185/55355010-2474b780-5495-11e9-8f35-ef8075523b34.png)
![image](https://user-images.githubusercontent.com/4129185/55355021-2e96b600-5495-11e9-930a-8a6a86d45161.png)
![image](https://user-images.githubusercontent.com/4129185/55355310-e88e2200-5495-11e9-8903-2352ff7e78d5.png)

**Comment by dhenry-KCI** [comment]
areed

**Comment by megisys** [comment]
Ready for retest

**Comment by dhenry-KCI** [comment]
PW239050/PW239051 fee populated - correct. closed areed
