### ISSUE TITLE
Planning - PWCONSTRUC - fees CMBDEVIMP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#597]
PW239034 CMBDEVIMP
Per sheet fee added again in error on 3rd review cycle. This fee was paid when applicant processed re submission for the 2nd review. 
areed

![image](https://user-images.githubusercontent.com/4129185/55355852-6bfc4300-5497-11e9-8128-c95635c0bcbf.png)
![image](https://user-images.githubusercontent.com/4129185/55355886-77e80500-5497-11e9-974d-ace1d2ee6a87.png)

**Comment by dhenry-KCI** [comment]
This is happening on multiple work types. Please update across PWCONSTRUC
PWIPPLAN PW239047 - per sheet fee added on 3rd submission again. Should only add on 2nd.
![image](https://user-images.githubusercontent.com/4129185/55411655-090cb980-5534-11e9-9ea8-19878c7269b9.png)

**Comment by megisys** [comment]
PLease Retest

**Comment by dhenry-KCI** [comment]
PW239065 corrected areed
