### ISSUE TITLE
Planning - PWCONSTRUC - Review time frame CMBDEVIMP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#598]
On all PWCONSTRUC applications - 1st review is 3 weeks, **2nd review is 2 weeks**, each additional review is back to 3 weeks so... 3, 4, 5, 6... all 3 week reviews. Only 2nd review is 2 wks. 
Highlighted reviews should have gone back to the 4/22 due date
areed
![image](https://user-images.githubusercontent.com/4129185/55356190-36a42500-5498-11e9-8aca-1189f9e2eebe.png)

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
PW239065 CMBDEVIMP Review cycle 2 should be 2 week due date
![image](https://user-images.githubusercontent.com/4129185/55425388-5dbe2d80-5550-11e9-8836-b7128b4c6283.png)

**Comment by dhenry-KCI** [comment]
2nd review should be 2 weeks for all PWCONSTRUC
![image](https://user-images.githubusercontent.com/4129185/55427050-2ea9bb00-5554-11e9-88bc-6ad49d8b30b7.png)

**Comment by dhenry-KCI** [comment]
corrected PW239069 areed
