### ISSUE TITLE
PLANNING - PWCONSTRUC - MYLAR REVIEW 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#599]
PW239034 CMBDEVIMP but applies to all PWCONSTRUC where this review populates
MYLAR REVIEW should always be 1 week. Populated to 3 weeks. This should be any time this review populates under any PWCONSTRUC.
areed
![image](https://user-images.githubusercontent.com/4129185/55356351-8b47a000-5498-11e9-904d-fe1a485a60c1.png)

**Comment by megisys** [comment]
Addressed This

**Comment by dhenry-KCI** [comment]
corrected areed PW239066/PW239067
