### ISSUE TITLE
License - Utility Trade - Details Tab

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#6]
The system needs additional information presented to the user on the Utility Trade License Details Page. Currently the system is only presenting the user with standard trade license details. 

Logged by Kelly V. on 2/4

See screenshot below for those fields to be added

![image](https://user-images.githubusercontent.com/4129185/52349791-456cdf00-29f5-11e9-96b8-b2cf3fdeb2ff.png)

**Comment by megisys** [comment]
@dhenry-KCI  Please Verify with SWalter & ABonomo. As we said this was a completeness check operating procesure to review attachments

**Comment by ABonomo21** [comment]
@dhenry-KCI  @ABonomo21 If this is to occur during completeness check, then we just need to make sure the applicant is informed on Rhythm for Civics of the documents that they will need to upload for us to confirm the information.-AW 
![image](https://user-images.githubusercontent.com/47611580/54825300-9d993100-4c83-11e9-94cb-814f875ed5af.png)

**Comment by ABonomo21** [comment]
Details for the insurance data should be available on a details page.

**Comment by ABonomo21** [comment]
This detail page should be called Utility License Detail Page 

![image](https://user-images.githubusercontent.com/47611580/54948234-8754d480-4f12-11e9-80bc-6eea6b4d99fc.png)

**Comment by megisys** [comment]
Done

**Comment by ABonomo21** [comment]
confirmed fixed
