### ISSUE TITLE
Building - ResBldg - DUSWM Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#60]
The DUSWM review did not generate for the residential building permits below. This issue persists through other condo unit permits.

AP - 237223 &  237224
Logged by A.White 2/19

![image](https://user-images.githubusercontent.com/4129185/53099754-6d2f6d00-34f4-11e9-906c-d5af159c7f32.png)

![image](https://user-images.githubusercontent.com/4129185/53102036-edf06800-34f8-11e9-9c39-de918b67475c.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

DUSWM review now gets added correctly. Please screenshot for proof of test (AP# 236149)

<img width="960" alt="issue60_fixed" src="https://user-images.githubusercontent.com/47784290/53136091-a8a95600-354b-11e9-8dd1-23a5a40ca1eb.png">

**Comment by ABonomo21** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/47611580/54136840-e4209d00-43f2-11e9-84c6-7e91d406bb45.png)
![image](https://user-images.githubusercontent.com/47611580/54136867-f0a4f580-43f2-11e9-851b-34f2607b55db.png)
![Uploading image.png…]()
