### ISSUE TITLE
Planning - PWConstruct -CMBSWMDEV- DOLS fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#600]
Life Safety Review Fee should not add to CMBSWMDEV. AREED

![image](https://user-images.githubusercontent.com/4129185/55404991-27b88380-5527-11e9-9dad-8370611599a1.png)
![image](https://user-images.githubusercontent.com/4129185/55405326-ccd35c00-5527-11e9-86d2-7827fcb08f7d.png)

**Comment by megisys** [comment]
Ready

**Comment by dhenry-KCI** [comment]
PW239064 Life safety fee still populating - AReed

![image](https://user-images.githubusercontent.com/4129185/55422589-f8ffd480-5549-11e9-98d4-30646e868b32.png)

**Comment by dhenry-KCI** [comment]
corrected PW239074 Areed Closed
