### ISSUE TITLE
PLANNING - PWCONSTRUC - CMBSWMDEV

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#601]
Date Approved filled in and stuck in admin closure  PW239038 CMBSWMDEV

![image](https://user-images.githubusercontent.com/4129185/55408454-0313da00-552e-11e9-85c9-f3c2fd8e2739.png)

![image](https://user-images.githubusercontent.com/4129185/55408430-f98a7200-552d-11e9-8f41-00d1f865094a.png)
![image](https://user-images.githubusercontent.com/4129185/55408487-145ce680-552e-11e9-9e1a-0be3f734a054.png)

**Comment by dhenry-KCI** [comment]
this happening on multiple work types CMBSWMIMP-PW239040

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
PW239038 corrected PW239040 corrected - closed AReed
