### ISSUE TITLE
Building - RESBLDG - Condo - Under Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#602]
ECS review was resulted as RESUBMIT due to a major grading condo permit being applied for. This created a revision fee which is not correct. This is the case for PWDR, ECS

AP #240142

logged by tm and ep 4/2/19

**Comment by dhenry-KCI** [comment]
R4C - Need to provide clear and detailed information to the applicant that details the cut fill and disturbed area of the plan, allowing the applicant to apply for the correct permits (Building + Major/Minor grading)

Residential Building Permits with a minor grading permit would maintain an ECS review - allowing Tiffany to confirm details. If during her review its determined that a major grading permit is needed, TM would result her review as resubmit and the applicant would be charged a revision fee. 

Residential Building Permits with a major grading permit would not include an ECS review as TM's review would be on the Major Grading permit. This would be identified on Intake review. Issuance of the Building Permit would redline until the issuance of the Grading Permit. 

Will want TM and EP to test the Building redlining for issuance of Major Grading.

**Comment by ABonomo21** [comment]
This issue is resolved because the review will no longer populate on RESBLDG permits. Need to make sure condo/apartment building and townhouses populate a requirement for a major grading permit

**Comment by ABonomo21** [comment]
this is linked to #749 
Swimming pools and Resbldg SFD should auto span a minor grading

**Comment by dhenry-KCI** [comment]
tm 4/30/19 - only closing item 602 NOT 749

**Comment by dhenry-KCI** [comment]
tm 4/30/19 - only closing item 602 NOT 749
