### ISSUE TITLE
Building - Res / Non Res Building- PWDR

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#604]
When the user results a PWDR review as resubmit the system should not generate the Revision fee for that review. 

This was per our discussion on 4/02/2019

**Comment by ABonomo21** [comment]
fixed-AW

![image](https://user-images.githubusercontent.com/47611580/55632690-c7c11780-5788-11e9-9d80-7c4b93dc72aa.png)
