### ISSUE TITLE
Building - Major Grading - town/apt/condo

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#610]
dre cost est still populated after we had selected not part of an overall plan and construct improvements in lieu of guarantee or waive guarantee. DREcost est should not populate. 

Also, the applicant provided the grading permit and building permit on the back tab, however, only a redline for grading permit must be related as a parent was generated. one for the buildin permit did not generate.

AP # 240161

![image](https://user-images.githubusercontent.com/4129185/55486485-62d7b700-55fa-11e9-9943-f38ff0c20b1f.png)

![image](https://user-images.githubusercontent.com/4129185/55486525-74b95a00-55fa-11e9-84fa-a862c0a30671.png)

![image](https://user-images.githubusercontent.com/4129185/55486642-a9c5ac80-55fa-11e9-8c5d-5a91eb96d327.png)

![image](https://user-images.githubusercontent.com/4129185/55486775-e5607680-55fa-11e9-8ccf-4e721e1a725e.png)

tiffany martin 4/3/19

**Comment by dhenry-KCI** [comment]
STILL AN ISSUE 4/16/19 TM/EP

**Comment by megisys** [comment]
I cant fix this. As you aren't telling me it isn't part of an overall plan until we have already generated the review.. Can we add this to the intake page ?

Dan

**Comment by dhenry-KCI** [comment]
Permit #240534 did not generate a redline for the building permit being attached but it did generate a redline for a grading. this is still an issue from the original issue.

However, the costest review is OK - we will consider this a "training issue" and will waive when necessary in these circumstances 

tm/ep 4/30/19

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/56984284-abc85000-6b53-11e9-8f57-2e7cda82134e.png)

The Building permit 240540 is pending issuance, but the grading and driveway are at intake review and completeness check.   Can you add a comment that grading and driveway must be issued

**Comment by ABonomo21** [comment]
This is still not fixed..."Permit #240534 did not generate a redline for the building permit being attached but it did generate a redline for a grading. this is still an issue from the original issue." 

Retested Permit 240587- no redline
![image](https://user-images.githubusercontent.com/47611580/57087138-692a8300-6ccd-11e9-8929-9a5a9d53ccf1.png)

**Comment by ABonomo21** [comment]
no longer an issue because building permits auto generate grading permits when required and they will automatically be linked as a related record
