### ISSUE TITLE
planning-plat-combined preliminary final-passing hearing milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#611]
entered a hearing before resulting all reviews. systems is skipping hearing and going to PZMYLAR--MW

![image](https://user-images.githubusercontent.com/4129185/55487011-4c7e2b00-55fb-11e9-86d6-1749706815b9.png)

![image](https://user-images.githubusercontent.com/4129185/55486936-2eb0c600-55fb-11e9-8e32-4e6b9830b026.png)

**Comment by megisys** [comment]
Addressed this.. If you add a Review it is the same as saying FCPC required on the Detail page

**Comment by dhenry-KCI** [comment]
yes!  per PL239087

MW
