### ISSUE TITLE
Building - Major Grading - Town/Apt/Condo - ap rollback

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#612]
I tried to roll this permit back and the application states it is open however, the current milestone says the application has been finalized. If you roll it back and the application is open the current milestone should be at what at what point it was asked to be rolled back to.

I rolled this back to intake review milestone. 

Also, i got another email that my permit was issued after rolling the permit back. 

AP # 240162

![sdfsdfsdf](https://user-images.githubusercontent.com/4129185/55487585-610ef300-55fc-11e9-8115-e6617b87fc29.png)

logged by tiffany martin 4/3/19

**Comment by ABonomo21** [comment]
Training - we will look at once we go live and determine if there is a need
