### ISSUE TITLE
Non Res-Foundation Only-Capacity permit holding up permit issuance

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#615]
According to airtable a capacity permit is not required for the foundation only permit. I ended up having to add a capacity permit to be able to move the permit forward.-AW

![image](https://user-images.githubusercontent.com/47611580/55491326-48eea200-5603-11e9-8204-ee7cb18ae610.png)

**Comment by megisys** [comment]
Please Retest

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55499057-0af97a00-5613-11e9-91bd-b3213bd033b5.png)
