### ISSUE TITLE
PLANNING - SITE - Type I & Type II- Condition check

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#616]
On Type I Site Plan add highlighted checks on Admin Closure. Date Entries are on Site Plan Details Page
AREED
![image](https://user-images.githubusercontent.com/4129185/55498279-38ddbf00-5611-11e9-8633-37ddf0b12d9b.png)

Replicate from PP239091
![image](https://user-images.githubusercontent.com/4129185/55498209-0af87a80-5611-11e9-9a8a-e21053f985c7.png)

On TYPE II Site Plan add higlighted checks on Admin Closure
![image](https://user-images.githubusercontent.com/4129185/55498197-05029980-5611-11e9-9f06-b9d06fab8e33.png)

**Comment by dhenry-KCI** [comment]
missing FRO child


![image](https://user-images.githubusercontent.com/4129185/55507241-371df680-5625-11e9-8f1f-2a26f4b9055e.png)

**Comment by goggansd** [comment]
Fixed in IPSTest. Please retest.

![image](https://user-images.githubusercontent.com/28841997/55557639-45692280-56b8-11e9-9229-5ed6646d944d.png)

**Comment by dhenry-KCI** [comment]
done-  MW
