### ISSUE TITLE
ResUse-Basement-Electrical permit must be related before Issuance

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#617]
Although the electrical permit is required for basement permits, it should not hold up the issuance of the permit. It should be a regular electrical hold to be able to stop the permit from getting to its final inspection.-AW
![image](https://user-images.githubusercontent.com/47611580/55502469-9cb8b580-561a-11e9-8cdc-e83f1ba1e955.png)

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55728426-0bfb2480-59e2-11e9-8159-f676bda613bd.png)
