### ISSUE TITLE
PLANNING - WSPLANA - PDOX ERROR

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#620]
Project Dox Integrated review populated in error. Unable to progress.
AReed
![image](https://user-images.githubusercontent.com/4129185/55559357-089f2a80-56bc-11e9-9f21-e3a95dbe4d3e.png)
![image](https://user-images.githubusercontent.com/4129185/55559377-1359bf80-56bc-11e9-8172-37a5ce4c354e.png)

**Comment by goggansd** [comment]
Addressed in IPSTest. See test case WS239116:

![image](https://user-images.githubusercontent.com/28841997/55562749-98e06e00-56c2-11e9-996e-5c285f6953ee.png)

Please retest.

**Comment by dhenry-KCI** [comment]
fixed per WS239120  MW
