### ISSUE TITLE
Planning - WSPLANA - Resubmit only to agencies requesting resubmit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#621]
WS239112 Resubmit only to agencies requesting resubmit - AReed
![image](https://user-images.githubusercontent.com/4129185/55559685-bc081f00-56bc-11e9-9277-a6e41b27b23b.png)

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by dhenry-KCI** [comment]
fixed per WS239120   MW
