### ISSUE TITLE
PLANNING - REZONE - REZONE - Detail Page Changes

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#625]
Removed items marked in red. On yellow highlight add the word existing and make fields fillable (Current Zone, Requested Zone, Water Classification, Sewer Classification. Move Water and sewer fields up under requested Zone

![image](https://user-images.githubusercontent.com/4129185/55562667-6f274700-56c2-11e9-94c5-6f148b56c5d5.png)

**Comment by dhenry-KCI** [comment]
Work Type REZONE & MAP - Detail Page Changes - AREED

**Comment by dhenry-KCI** [comment]
overlapping text - MW

![image](https://user-images.githubusercontent.com/4129185/55744283-95225380-5a02-11e9-99fc-4f94d5f605b9.png)

**Comment by megisys** [comment]
Moved

**Comment by dhenry-KCI** [comment]
fixed
