### ISSUE TITLE
Non-Residential Building-Backfill Inspection

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#626]
Permit# 240191; Backfill inspection is not generating. This inspection previously generated on Non-Residential Building permits for New, Core, Addition, and Accessory and now it's not. It is listed as a required inspection for this permit type in Airtable. Is this something that has changed?-MCoffman

![image](https://user-images.githubusercontent.com/47611580/55563518-1e185280-56c4-11e9-928b-a3977c0189e4.png)

**Comment by ABonomo21** [comment]
Nothing has been changed it needs to be corrected- Marked as a bug

**Comment by megisys** [comment]
If ConstrType = "FOUNDATION" OR ConstrType = "FOUN-SLAB" OR ConstrType = "NOCHANG" OR ConstrType = "OWNERCH" OR ConstrType = "RETAINWALL" OR ConstrType = "STEPS" OR ConstrType = "WIND" OR ConstrType = "SOLAR" OR ConstrType = "POOLIN" OR ConstrType = "DECK>500" OR ConstrType = "DECK500" OR ConstrType = "POOLABOV" Then
	
	AddOnCondition = False
	
Else If (NOT oBldgApp.WorkType.Code.Trim() = "ALTER"  AND NOT BuildingUse = "AG-BLDEXEMPT")  AND Ols = False AND ZoneCert = False Then
	
		AddOnCondition = True
		
End If
	
	
	if AddonCondition = True then
		
		If ConstrType = "CORE" OR ConstrType = "ADDITION" OR ConstrType = "ACC399" OR ConstrType = "ACC400" then
			
			AddonCondition = False
			
		End if
		
		
	End if

**Comment by megisys** [comment]
Are these rules still right though ? @ABonomo21

**Comment by ABonomo21** [comment]
I need to sit with you to understand this

**Comment by ABonomo21** [comment]
Backfill inspection generated-AW
![image](https://user-images.githubusercontent.com/47611580/57033655-75ee9e80-6c1b-11e9-939d-5cb26cb391af.png)
