### ISSUE TITLE
Planning - Rezone - Rezone Milestone Awaiting Paperwork missing

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#628]
REZONE - Rezoning went from Hearing to Paperwork review and skipped Awaiting Paperwork milestone. Add Awaiting Paperwork milestone with Condition check. AReed
RZ239117
![image](https://user-images.githubusercontent.com/4129185/55565272-8caadf80-56c7-11e9-98cb-19a00265b9c9.png)

**Comment by dhenry-KCI** [comment]
This is also missing in Work Type MAP under REZONE. AReed

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by dhenry-KCI** [comment]
fixed  MW
