### ISSUE TITLE
Building - ResBldg - Permit Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#63]
For Condo units (237224) the Homebuilder fee generated as $1 when the fee should be $50. 

For single family dwellings (237202) the Homebuilder fee generated as $1 when the fee should be $50 and the Building fee generates as $1 when the fee should be $934. 

For single family dwelling (237215) the Building Fee generated as $1. The building fee should have generated as $1246.

This issue persists throughout other condo unit permits and single family dwellings. 

 AP - 237224, 237202 & 237215
Logged by A.White 2/19 & 2/18

![image](https://user-images.githubusercontent.com/4129185/53101081-14150880-34f7-11e9-95ac-7411097416fa.png)

![image](https://user-images.githubusercontent.com/4129185/53104366-3ca00100-34fd-11e9-915c-5de713104dbb.png)

![image](https://user-images.githubusercontent.com/4129185/53106303-beddf480-3500-11e9-93e1-98db1c101d3d.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Homebuilder fee has been corrected. Please screenshot for proof of test (AP# 236146)
<img width="960" alt="issue63_homebuilderfeefixed" src="https://user-images.githubusercontent.com/47784290/53134272-8233ec80-3544-11e9-85c8-9115df5f8d89.png">

Building Fee has been corrected. Please screenshot for proof of test (AP# 236148)
<img width="960" alt="issue63_buildingfeefixed" src="https://user-images.githubusercontent.com/47784290/53134281-895afa80-3544-11e9-8e7f-cace07813ef6.png">

**Comment by dhenry-KCI** [comment]
Confirmed fixed. 
![1](https://user-images.githubusercontent.com/4129185/53264227-28006c00-36a9-11e9-85f3-5523474d375b.PNG)

**Comment by dhenry-KCI** [comment]
Confirmed Fix

Condo A/P#237351

![image](https://user-images.githubusercontent.com/4129185/53263702-300bdc00-36a8-11e9-81ba-f36a2c5d8162.png)

Single Family Dwelling A/P# 237353

![image](https://user-images.githubusercontent.com/4129185/53264603-018f0080-36aa-11e9-943e-eb6c12509e6b.png)

Single Family Dwelling A/P# 237356

![image](https://user-images.githubusercontent.com/4129185/53265037-2afc5c00-36ab-11e9-9c06-e10ec39774a7.png)

Townhouse A/P# 237357

![image](https://user-images.githubusercontent.com/4129185/53265957-77489b80-36ad-11e9-8745-610deb8e3fc4.png)
