### ISSUE TITLE
PLANNING - REZONE - WORK TYPE CHANGES

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#630]
Removed MXD, Remove PUD 
Change description for MAP to read "MAP AMENDMENT TO PHASE 1 PLAN"
AReed
![image](https://user-images.githubusercontent.com/4129185/55566043-eb248d80-56c8-11e9-8771-6b4f72aacf30.png)

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by dhenry-KCI** [comment]
fixed per RZ239129

MW
