### ISSUE TITLE
PLANNING - REZONE - MAP

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#633]
Narrow Review Results. Only 1 agency selected and full list populated. AReed.
RZ239119
![image](https://user-images.githubusercontent.com/4129185/55566661-283d4f80-56ca-11e9-810e-b703001d2bfc.png)
![image](https://user-images.githubusercontent.com/4129185/55566694-37bc9880-56ca-11e9-9b61-75aa9d146d2f.png)

**Comment by dhenry-KCI** [comment]
Occurred on MAP AND FLOAT - check all reviews under REZONE
RZ239119 MAP
RZ239121 FLOAT

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by dhenry-KCI** [comment]
ok on float and map

MW
