### ISSUE TITLE
Use- Home Occupation - Review Options

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#634]
Should only be approved, resubmit or denied(supervisors only) 

removed conditional approval, failed 

Change waived to not applicable.

![image](https://user-images.githubusercontent.com/47611580/55566888-95e97b80-56ca-11e9-9d0e-3e6eef4c4c48.png)

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55729161-9bed9e00-59e3-11e9-9083-6b6badc59446.png)
