### ISSUE TITLE
Planning-WSPLANNA and REZONE all- hearing results

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#636]
hearing resulted in denied still allowed stage progression.  Apply same coding as used in Preliminary, Site, and other Planning AP types where a hearing result of anything other than approved keeps the project in the hearing milestone.

![image](https://user-images.githubusercontent.com/4129185/55567719-3f7d3c80-56cc-11e9-870f-c9552efa02d8.png)

also, is it possible to add another result option for a hearing, called "Recommendation"?  If so, a result of "Recommendation", "Approved", or "Waived" would allow stage progression.  Selecting "deferred" or "denied" would keep the application at the hearing milestone.

MW

**Comment by goggansd** [comment]
Addressed in IPSTest as requested. Please retest.

**Comment by dhenry-KCI** [comment]
still going to awaiting paperwork when resulting hearing as denied.-MW

![image](https://user-images.githubusercontent.com/4129185/55628318-64ca8300-577e-11e9-96e7-3b0077af6b1c.png)

**Comment by goggansd** [comment]
All of these are using the same workflow formula, so all these listed AP types had the same issue previously. Made correction to workflow formula, so these should now all work as expected. See RZ239136, as an example. Please retest.

**Comment by dhenry-KCI** [comment]
see remaining issue- #645
