### ISSUE TITLE
Planning - REZONE - Notice and Publication Tracking Details - add field for Ordinance Number

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#637]
Notice and Publication Tracking Details - add field for Ordinance Number below Ordinance Signed
![image](https://user-images.githubusercontent.com/4129185/55569097-f37fc700-56ce-11e9-9d82-fdab2584cec8.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by dhenry-KCI** [comment]
done per RZ239129

MW
