### ISSUE TITLE
Building - Driveway - Awaiting Plan Review Payment

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#638]
After group adding the driveway permit from the building permit the fees populated. Is there anyway that the system would recognize that the applicant already paid the fees under the building permit? 

hansen 7 currently does this. it realizes fees have been paid if they have and will not generate them. 

tiffany martin 4/4/19

**Comment by goggansd** [comment]
Need a specific AP #, please. All of the recent DRIVEWAY permits I was able to locate either had no parent application, or had a GRADING as the parent--except for B04000205 (RESBLDG--but with no fees).

**Comment by megisys** [comment]
If Parent of ResBuilding and NEW. Driveway fees will not add for Primary Apron

**Comment by dhenry-KCI** [comment]
corrected tm 4/9/19
