### ISSUE TITLE
Use- Landuse - Work Types

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#639]
Work Type option should only be Individual 

Remove Seasonal

![image](https://user-images.githubusercontent.com/47611580/55579841-2fbf2180-56e7-11e9-903f-a3faf432ded8.png)

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by ABonomo21** [comment]
corrected
