### ISSUE TITLE
Septic Installers License-no fees generated

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#640]
no fees generated for a septic installers license. the fee should be $132. After completing the completeness check, the license when straight to active and issued.-Aw

![image](https://user-images.githubusercontent.com/47611580/55579961-7745ad80-56e7-11e9-95f1-61d3e8783bf3.png)
![image](https://user-images.githubusercontent.com/47611580/55579973-7c0a6180-56e7-11e9-8285-3e2d527a2c6f.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

![image](https://user-images.githubusercontent.com/28841997/55587528-8b92a600-56f9-11e9-8388-e8798d2ebb68.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55631217-88dd9280-5785-11e9-9e13-ea384a06e15b.png)
