### ISSUE TITLE
Use- Land Use - Detail Page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#642]
Please switch Sanitation Type and Add. Entertainment fields, the additional entertainment field should follow the initial entertainment field
![image](https://user-images.githubusercontent.com/47611580/55580356-5d589a80-56e8-11e9-8a88-1701fc89f90b.png)

**Comment by kellyjj** [comment]
I have switched the 2 fields as requested.
setting to retest

**Comment by ABonomo21** [comment]
corrected
