### ISSUE TITLE
Plumbing Master License-Fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#643]
Generating 50% fees when it is not the plumbing renewal period-MCoffman

PM237120-Should be full $158.00 fee; Plumbing is not in the renewal period.
![image](https://user-images.githubusercontent.com/47611580/55580347-57fb5000-56e8-11e9-869d-713bca2b3c66.png)

**Comment by goggansd** [comment]
Fixed in IPSTest environment. Please retest.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55631652-8cbde480-5786-11e9-81e4-77b5788110c7.png)
