### ISSUE TITLE
Use- Log Entry Error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#644]
Receiving an error when trying to add a log to bypass a case in use permit L235889

![image](https://user-images.githubusercontent.com/47611580/55580596-dfe15a00-56e8-11e9-9076-94999e94396d.png)

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55730294-d821fe00-59e5-11e9-9720-276742e66016.png)
