### ISSUE TITLE
ResUse-General Error Message

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#647]
I was in the middle of creating a ResUse Alteration permit and then I kept getting this error message no matter what text box or what tab I tried to click on.-AW
![image](https://user-images.githubusercontent.com/47611580/55637773-ccd79400-5793-11e9-8df6-7ba57ad7e10d.png)

**Comment by goggansd** [comment]
Cannot replicate. I believe that this may have occurred while Kelly J was in the process of making changes to the RESUSES detail pages. Please retest and verify it is no longer an issue.
