### ISSUE TITLE
PLANNING - PWCONSTRUC - Work Type  REAPPMR & REAPPNR - remove # of pages 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#648]
**# of pages does not apply to REAPPMR or REAPPNR, Remove condition from these two work types.
PW239147/PW239148**
areed
![image](https://user-images.githubusercontent.com/4129185/55637997-39529300-5794-11e9-93fc-a38fcb2749f2.png)

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by dhenry-KCI** [comment]
fixed MW

**Comment by dhenry-KCI** [comment]
fixed mw
