### ISSUE TITLE
PLANNING - PWCONSTRUC - Engineering Per sheet Fee REAPPMR & REAPPNR

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#649]
The $145 Engineering Per Sheet Fee is populating in REAPPMR & REAPPNR. Remove this fee. There is not per sheet fee for these work types. AReed
![image](https://user-images.githubusercontent.com/4129185/55639601-c3502b00-5797-11e9-9cb0-b99893407462.png)
![image](https://user-images.githubusercontent.com/4129185/55639624-d2cf7400-5797-11e9-8603-4281a97e5840.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment (see application PW239156). Please retest.

**Comment by dhenry-KCI** [comment]
fized.   MW
