### ISSUE TITLE
PLANNING - PWCONSTRUC - Mylar Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#650]
Mylar review resulted as a resubmit and application moved to closed. Should have gone through applicant revision cycle. AReed
![image](https://user-images.githubusercontent.com/4129185/55640484-b03e5a80-5799-11e9-8893-be9b9fe8bed2.png)

**Comment by dhenry-KCI** [comment]
Fix this under all PWCONSTRUC. Also occurred in work type REVMJIMPRV. Areed

**Comment by goggansd** [comment]
Addressed in the IPSTest environment (see screenshot). Please retest.

![image](https://user-images.githubusercontent.com/28841997/55652713-54d09480-57ba-11e9-9dae-35e44235bb51.png)

**Comment by dhenry-KCI** [comment]
fixed PW239164   MW
