### ISSUE TITLE
Project - Blanket - Completeness Check Review Codes

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#651]
For a Blanket Approval the Completeness Check review results are not filtered properly. Options should include only: Approved, Resubmit, and NA.

![image](https://user-images.githubusercontent.com/31770504/55642473-8a678480-579e-11e9-95cf-1c5efb920488.png)

![image](https://user-images.githubusercontent.com/31770504/55642447-7c196880-579e-11e9-8c66-e11071cf2ef8.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by ABonomo21** [comment]
corrected
