### ISSUE TITLE
Project - Blanket - BLKTMEETING and PLNREV Reviews Codes

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#652]
For a Blanket Approval, the BLKTMEETING and PLNREV review result codes are not filtered properly. Review codes options should include only:

BLKTMEETING:
Complete (Debbie prefers this option over approved)
Resubmit
NA
Denied (should only be made available for supervisors)

PLNREV:
Approved
Resubmit
NA
Denied (should only be made available for supervisors)

![image](https://user-images.githubusercontent.com/31770504/55642924-cfd88180-579f-11e9-9719-403a61c49034.png)

![image](https://user-images.githubusercontent.com/31770504/55642945-dd8e0700-579f-11e9-8a59-58d15f06ecf7.png)

![image](https://user-images.githubusercontent.com/31770504/55642979-f8f91200-579f-11e9-87d8-81b95ab1de6f.png)

**Comment by megisys** [comment]
We only use one positive Verb.. Approved is the consistent approach

**Comment by ABonomo21** [comment]
completed
