### ISSUE TITLE
Distributor Report- Applicant Actions

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#653]
received the following errors when trying to go to applicant actions to do a resubmission on a distributor report

![image](https://user-images.githubusercontent.com/47611580/55644316-93a72000-57a3-11e9-859f-52644c6f0151.png)

**Comment by goggansd** [comment]
@megisys, this looks like an agencypersonalization.config file issue (see ghosted error message in attached screenshot from FC). If so, you'll need to address this, as I have no access to the server...

**Comment by megisys** [comment]
Use only new ones.. Old ones. have the issue

**Comment by ABonomo21** [comment]
corrected
