### ISSUE TITLE
Project - Blanket - Detail Page Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#655]
For a Blanket Approval application, please make the detail page updates outlined in the attached pdf.
We also need to add a "Section Complete" box since no other fields are required on the detail page.

[20190405125354220.pdf](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3049040/20190405125354220.pdf)

**Comment by dhenry-KCI** [comment]
@kellyjj - this needs to be addressed today as well.

**Comment by megisys** [comment]
The Table wont sync as it is hitting some data issues. Can you please work through this issue. as I added the 2 new fire Sprinkler type fields to help you

**Comment by kellyjj** [comment]
the table  AgencyCDR.Project. BlanketDetail had a index against it that was not valid by sql server.  Index was dropped

**Comment by kellyjj** [comment]
table [AGENCYCDR_PROJECT].[BLANKETGRD]   has a constraint linking the apkey column to the [CDR_PROJECT].[PROJAPPLDETAIL] table.

there were 6188 records that didn't have a value in either table.  set the apkey to 1 in blanketgrd to satisfy constraint
update [AGENCYCDR_PROJECT].[BLANKETGRD]
set APKEY = 1
where APKEY not in (select APPROJAPPLDTLKEY from [CDR_PROJECT].[PROJAPPLDETAIL])

**Comment by kellyjj** [comment]
ready for retest

**Comment by ABonomo21** [comment]
received an error when trying to test detail page

![image](https://user-images.githubusercontent.com/47611580/57088968-6893eb80-6cd1-11e9-9310-6ff19289d947.png)

**Comment by kellyjj** [comment]
error resolved

**Comment by ABonomo21** [comment]
Updates for Detail Pages Per Ken & Debbie-AW

![image](https://user-images.githubusercontent.com/47611580/57099068-8f5e1c00-6ce9-11e9-9955-60f0aa0fe09d.png)
![image](https://user-images.githubusercontent.com/47611580/57099094-a00e9200-6ce9-11e9-9e6a-9b46dc4a4dfe.png)
![image](https://user-images.githubusercontent.com/47611580/57099107-a8ff6380-6ce9-11e9-95d1-7a65841976cc.png)
![image](https://user-images.githubusercontent.com/47611580/57099123-b1579e80-6ce9-11e9-8526-8da768983ef4.png)
![image](https://user-images.githubusercontent.com/47611580/57099149-bcaaca00-6ce9-11e9-97a8-6926d785c9eb.png)
![image](https://user-images.githubusercontent.com/47611580/57099168-c92f2280-6ce9-11e9-8bdc-2670b09bcacd.png)
![image](https://user-images.githubusercontent.com/47611580/57099178-d1875d80-6ce9-11e9-9952-1182e343e09b.png)

**Comment by goggansd** [comment]
All of these changes have been completed except for the conversion from code table to checkboxes and the checks for R4C to ensure multiple items can be selected simultaneously.

**Comment by JuanitaMiles** [comment]
Energy Efficiency Compliance Method field name on the details page is spelled incorrectly.

![image](https://user-images.githubusercontent.com/31770504/59040881-970f6400-8845-11e9-8f69-989a822b276d.png)

Means of Egress options/fields have not been converted to checkboxes.

![image](https://user-images.githubusercontent.com/31770504/59041597-e99d5000-8846-11e9-8f4d-276dbe31573f.png)

**Comment by kellyjj** [comment]
Currently working on this issue

**Comment by kellyjj** [comment]
I have corrected the spelling issue.  I have also added the check box columns to the object,  unable to sync due to error show below

![image](https://user-images.githubusercontent.com/27238685/59720312-215fac80-91e4-11e9-93bd-11e47f6fad75.png)

**Comment by kellyjj** [comment]
I have made the changes to the detail page, however unable to test due to inability to sync product family.

**Comment by kellyjj** [comment]
have tested in the test enviroement, and ready for retest.  removing bug tag

![image](https://user-images.githubusercontent.com/27238685/59770985-865fe480-926e-11e9-9133-356a53b5e3fc.png)

**Comment by JuanitaMiles** [comment]
Error when trying to save the Blanket application. In PreProd.

![image](https://user-images.githubusercontent.com/31770504/60127179-8de72800-975d-11e9-9af3-22de1093181b.png)

**Comment by kellyjj** [comment]
the error means that the table under the detail page wasn't moved over to the preprod.
@megisys 
I can add the columns, or this can be done when a ctt is done.  pick how you want this handled.

**Comment by JuanitaMiles** [comment]
Can now submit the Blanket application.
