### ISSUE TITLE
PLANNING - PWCONSTRUC - REVMJIMPRV duplicate health fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#656]
Remove Major Revision-Health Fee on REVMJIMPRV. It is $75 weather it is Major or Minor. Two Health fees populated in error. 
AReed

![image](https://user-images.githubusercontent.com/4129185/55648098-63fd1580-57ad-11e9-9b20-03054ddcaa70.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by dhenry-KCI** [comment]
fixed per PW239165  MW
