### ISSUE TITLE
PLANNING - PWCONSTRUC - REAPPNR Remove Health Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#657]
Remove health fee from REAPPNR - They are never a reviewer on a Reapproval REAPPNR
![image](https://user-images.githubusercontent.com/4129185/55648650-e0442880-57ae-11e9-99de-60e325ceb518.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by dhenry-KCI** [comment]
fixed per PW239162 MW
