### ISSUE TITLE
PLANNING - PWCONSTRUC - REAPPNR Remove Health as a reviewer

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#658]
PWCONSTRUC - REAPPNR Remove Health as a reviewer. They are never a reviewer on this work type
areed
![image](https://user-images.githubusercontent.com/4129185/55648797-3fa23880-57af-11e9-9bcf-13255da2abfa.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by dhenry-KCI** [comment]
fixed per PW239162- MW
