### ISSUE TITLE
PLANNING - PWCONSTRUC - REAPPMR

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#659]
Remove Health fee and Health Review- they are not a reviewer on Reapproval REAPPMR
areed
![image](https://user-images.githubusercontent.com/4129185/55649505-23070000-57b1-11e9-918f-d9330d6a8ac8.png)
![image](https://user-images.githubusercontent.com/4129185/55649551-4631af80-57b1-11e9-9b2d-75104c6f9dd1.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by dhenry-KCI** [comment]
fixed per PW239161
