### ISSUE TITLE
Building - ResBldg - Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#66]
The plot plan review did not generate.

AP - 237202
Logged by A.White 2/19

![image](https://user-images.githubusercontent.com/4129185/53104519-80930600-34fd-11e9-8702-63b0399442dc.png)

**Comment by imazlout** [comment]
Working as designed. Per attached spreadsheet filled out by Ashlye, we were instructed to expire Plot Plan reviews.

[FC_BuildingPermits_AllReviews10232018.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/2886734/FC_BuildingPermits_AllReviews10232018.xlsx)

**Comment by ABonomo21** [comment]
We do not need that plot plan review any longer- as long as the town review is completed and the additional agency review are populated and completed there is no need for a plot plan review. 

closing keeping marked as a training issue to educate staff
