### ISSUE TITLE
PLANNING - PWCONSTRUC - REVMNIMPRV Remove # of pages and $145 per page fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#661]
Minor Improvement REVMNIMPRV does not have a per page fee. Remove # of pages
Remove status check and highlighted fee for $145
areed
![image](https://user-images.githubusercontent.com/4129185/55650344-6cf0e580-57b3-11e9-8c08-63ecb009f746.png)
![image](https://user-images.githubusercontent.com/4129185/55650576-1a63f900-57b4-11e9-8f9f-e22fcbc8f9fe.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by dhenry-KCI** [comment]
PW239167 # of pages and fee corrected. Logged new issue about mylar review timeframe.
