### ISSUE TITLE
R4C- Distributor License

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#663]
We are not going to process distributor licenses online please remove from R4C we only have 5 and will continue our process to mail and accept application renewals the old fashion way 

![image](https://user-images.githubusercontent.com/47611580/55652017-4bdec380-57b8-11e9-9563-0e78d5419206.png)

**Comment by goggansd** [comment]
@megisys, I made the license type setting so it should no longer appear on R4C, but it is still appearing. Do we need an Enhancement folder refresh and/or an IIS reset on the REST Services server?

**Comment by megisys** [comment]
No All Good

**Comment by ABonomo21** [comment]
Not available in R4C to retest

**Comment by goggansd** [comment]
@ABonomo21, I thought the original request was for us to REMOVE this AP type from R4C. If you can't see it on R4C, that means we removed it successfully, right? What is the remaining issue?

**Comment by megisys** [comment]
Removed from Rhythm for Civics

**Comment by ABonomo21** [comment]
Yes. Closed issue!
