### ISSUE TITLE
PLANNING PWCONSTRUC - Town Review  - Permissions

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#677]
Ensure all security and roles to be updated for this reveiw.

![image](https://user-images.githubusercontent.com/4129185/55751460-b6d80680-5a13-11e9-8c63-09cb3f183e7e.png)

![image](https://user-images.githubusercontent.com/4129185/55751645-26e68c80-5a14-11e9-8f05-d433c88d403f.png)

**Comment by dhenry-KCI** [comment]
appears to be hiccup - was able to result review. Concern on routing to appropriate town. Will follow up in GIS. AREED

**Comment by ABonomo21** [comment]
closed will monitor
