### ISSUE TITLE
GIS Planning Region Not Set

### ISSUE THREAD

**Issue by megisys** [kcigeospatial/Fred_Co_Land-Management#678]
![image](https://user-images.githubusercontent.com/47392306/55752067-213d7680-5a15-11e9-85b5-9b6a3023daaf.png)

The Planning Region is not set in the Parcel Details.. This is needed so we can assign Town reviews to the right Town..

Dan

**Comment by megisys** [comment]
@dhenry-KCI Please Make sure this has priority..

**Comment by dhenry-KCI** [comment]
Notify Ashley Bonomo and Ashley Reed/MWilkins when this is resolved so they can go back into IPS and test. AReed

**Comment by megisys** [comment]
Not using this field
