### ISSUE TITLE
PLANNING PWCONSTRUC CMBSWMDEV - no DUSWM review on this work type

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#683]
Remove DUSWM as a reviewer on Work Type CMBSWMDEV under PWCONSTRUC

![image](https://user-images.githubusercontent.com/4129185/55819771-7fc32d00-5ac7-11e9-90e2-48ec03ab3cb3.png)
![image](https://user-images.githubusercontent.com/4129185/55819810-9c5f6500-5ac7-11e9-9fea-ad8b8def85a2.png)

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
PW239225 corrected areed
