### ISSUE TITLE
Building Permit - Misc Detail Pages

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#684]
Building Use, Zoning Use needs to be captured and completed by reviewers on and available as a detail page for Resuse/ Trailer / Zoning Cert
Related to item #275

**Comment by megisys** [comment]
Ready

**Comment by ABonomo21** [comment]
Fixed-AW
ResUse:
![image](https://user-images.githubusercontent.com/47611580/56142452-b20fd700-5f6c-11e9-8d4f-333b82c623a7.png)
Zoning Cert:
![image](https://user-images.githubusercontent.com/47611580/56142791-4843fd00-5f6d-11e9-8cb3-f0f96bbb6620.png)
Trailer:
![image](https://user-images.githubusercontent.com/47611580/56143020-be486400-5f6d-11e9-9ed0-c513adf9e3a4.png)
