### ISSUE TITLE
Building- Misc Detail Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#685]
Occupancy Load Detail page should be available for NonRes 

![image](https://user-images.githubusercontent.com/47611580/55823445-ba30c800-5acf-11e9-90c3-b6e27ab8c1c6.png)

**Comment by megisys** [comment]
Ready

**Comment by ABonomo21** [comment]
fixed, but there is only the option for occupancy load. the section for table & chairs occupancy is missing. need to confirm with @ABonomo21 that this is correct-AW 
![image](https://user-images.githubusercontent.com/47611580/56047675-f2c0e380-5d13-11e9-8421-2fb4d56f525f.png)

**Comment by ABonomo21** [comment]
The Occupant Load should have the two options for entry as shown in the initial screenshot. 

Additionally, this is an entry made by a the reviewer and should not be eligible for completion by the applicant.

**Comment by megisys** [comment]
Added Original detail page back..

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/56156510-6ae50e80-5f8b-11e9-8da6-db20c1954d08.png)
