### ISSUE TITLE
Building- Misc. Detail Page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#686]
Building code edition is captured on building detail pages, we need to discuss if this is the best place for the reviews to complete this entry.

Looks like it has been added but it overlaps with Section completed...see below

![image](https://user-images.githubusercontent.com/47611580/55824117-3972cb80-5ad1-11e9-85bb-0d2f2665f3e8.png)

need to test to make sure it is a condition to be completed on resuse/resbldg/nonres/trailers

**Comment by megisys** [comment]
Ready

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55965345-6a274200-5c44-11e9-98b7-19b8d9eafc63.png)
