### ISSUE TITLE
Priority Code Use 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#687]
![image](https://user-images.githubusercontent.com/47611580/55827140-83f74680-5ad7-11e9-97de-11a55934841f.png)

**Comment by ABonomo21** [comment]
codes created-AW
![image](https://user-images.githubusercontent.com/47611580/56143397-7a099380-5f6e-11e9-835a-b7b7b68b2137.png)

**Comment by ABonomo21** [comment]
EXP-Expedite/Walk Through Review- Due Dates did not generate for the same day review -AW

![image](https://user-images.githubusercontent.com/47611580/56144462-67905980-5f70-11e9-89ef-169e51b0d2af.png)
![image](https://user-images.githubusercontent.com/47611580/56144494-770fa280-5f70-11e9-8653-b4c68256defb.png)

**Comment by ABonomo21** [comment]
EXP-fixed
![image](https://user-images.githubusercontent.com/47611580/56155415-d24d8f00-5f88-11e9-911d-c6bcba3168be.png)
FT-fixed
![image](https://user-images.githubusercontent.com/47611580/56155533-29536400-5f89-11e9-8291-dd5da10f8c3c.png)
P1-fixed
![image](https://user-images.githubusercontent.com/47611580/56155626-63bd0100-5f89-11e9-8b5a-be4668bfd612.png)
P2-fixed
![image](https://user-images.githubusercontent.com/47611580/56155810-c57d6b00-5f89-11e9-8da4-fc5d4e32b87f.png)
P3-fixed
![image](https://user-images.githubusercontent.com/47611580/56155917-08d7d980-5f8a-11e9-86af-8e71186d8530.png)

**Comment by ABonomo21** [comment]
Grading permits still need to be tested.-AW

**Comment by dhenry-KCI** [comment]
CORRECTED TM 4/16
