### ISSUE TITLE
PLANNING - APFO - SHA Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#688]
Add SHA as a reviewer when Traffic Study Received result is "Y" under APFO Details. Traffic Study Received is required to be answered under completeness check. AReed
![image](https://user-images.githubusercontent.com/4129185/55829661-367dd800-5add-11e9-80e3-a5288cadb40e.png)

![image](https://user-images.githubusercontent.com/4129185/55829615-1b12cd00-5add-11e9-9bef-6111a92d8f3d.png)

**Comment by megisys** [comment]
Yep

**Comment by dhenry-KCI** [comment]
Corrected A239238 areed
