### ISSUE TITLE
PLANNING - PREPLAT - AFFADAVIT duplicate condition

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#689]
Resulted signature set as a resubmit - IPS asked for Affidavit to be resulted, then went to awaiting applicant actions to resubmit for signature set review. Then I resubmitted as applicant and 2nd signature set review populated. I approved the second signature set review, but then Affidavit populated again. it should only populate once

![image](https://user-images.githubusercontent.com/4129185/55890236-561a0c80-5b80-11e9-80ee-e03237b84765.png)
![image](https://user-images.githubusercontent.com/4129185/55890259-63cf9200-5b80-11e9-88e1-ef5cd44e2c2a.png)

**Comment by megisys** [comment]
Wont Add a second time

**Comment by dhenry-KCI** [comment]
corrected PP239246 areed
