### ISSUE TITLE
Building - ResBldg - Certificate

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#69]
For the single family dwelling permit, the “Certificate of Occupancy” stage seems to have issued and proved all at the same time as the finalization. The Certificate of Occupancy should be its own milestone and the permit should be stopped until we approved that milestone. This has happened with multiple building permits.

AP - 237202
Logged by A.White 2/18

![image](https://user-images.githubusercontent.com/4129185/53105528-4fb3d080-34ff-11e9-974d-ca8b999f619c.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Added CERTREV review on the Ap Types that require it based on list from Ashlye. This review ensures the application stops at Pending Certificate milestone. Please see screenshot for proof of testing (RESBLDG: AP# 236143 in DEV).

- RESBLDG - Yes
- PLUMBPERM - No
- ELECPERM - No
- CAPACITY - No
- DEMOLITION - No
- TRAILER - Yes
- SIGNS - No
- TANKS - Yes
- GRADING - Yes (Has AOC Formula)
- DRIVEWAY - Yes (Has AOC Formula)
- FROPERM - No
- FIRE - No
- NONRESBLDG - Yes
- RESUSES - Yes
- ZONINGCERT - No

<img width="960" alt="issue69_fixed" src="https://user-images.githubusercontent.com/47784290/53128928-121d6a80-3534-11e9-8b0f-b81dff0f933f.png">

**Comment by imazlout** [comment]
Confirmation from Dustin on Issue #41 that Signs and Demo should also have CERTREV. I'm adding it on the Final Inspection milestone for those since they don't have a pending certificate milestone

Ready for test once changes are move to TEST Environment

**Comment by dhenry-KCI** [comment]
Confirmed Fixed on Res Use, Res BLDg, & Signs. Working on the other types.
![1](https://user-images.githubusercontent.com/4129185/53264502-bd9bfb80-36a9-11e9-980d-1b8791d9786e.PNG)

**Comment by dhenry-KCI** [comment]
The Sign permit generates the "Certificate Pending" review however the permit milestone stays at the "Final Inspection" rather than saying "Pending Certificate" like the others do. Not sure if this is an issue, need to check with Ashlye.

**Comment by dhenry-KCI** [comment]
Trailer permits-confirmed fixed

**Comment by dhenry-KCI** [comment]
Demo permits-Same issue as the sign permits, the "Pending Certificate" generated but the milestone stayed at "Final Inspection" status. Need to check with Ashlye on this one too.
![6](https://user-images.githubusercontent.com/4129185/53267427-4c604680-36b1-11e9-8cef-56b0592fd52d.PNG)

**Comment by ABonomo21** [comment]
The Pending Certificate milestone needs to replace the Final Inspection milestone once the final inspection has passed. once the final inspection passes the milestone should be Pending Certificate and the Certificate Review should generate then too(which it is)

**Comment by megisys** [comment]
ready for ResTest - Demo and Signs

**Comment by imazlout** [comment]
Updated Demolition milestones and status checks as well as status checks for signs to be similar to the other AP Types

**Comment by ABonomo21** [comment]
Confirmed Fixed for Demo Permits-AW
![image](https://user-images.githubusercontent.com/47611580/54694143-1e2e2500-4afe-11e9-855a-dad5c565de03.png)

**Comment by ABonomo21** [comment]
Confirmed Fixed for signs-AW
![image](https://user-images.githubusercontent.com/47611580/54694748-1d49c300-4aff-11e9-97ed-9dd2c1081a6f.png)
