### ISSUE TITLE
ResBldg-ADU-Building fee & Home builder fee did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#691]
For the ResBldg ADU, the Homebuilder fee and the Building fee did not generate. Possibly related to issue #324 for the homebuilder fee.-AW
![image](https://user-images.githubusercontent.com/47611580/55967454-57af0780-5c48-11e9-91c8-1eb270e5defb.png)
![image](https://user-images.githubusercontent.com/47611580/55967504-6eedf500-5c48-11e9-9b1f-4f7cf63e0f68.png)

**Comment by goggansd** [comment]
@megisys, for the Home Builder fee, none of the applicants had a valid HomeBuilder license (HOMEB), which is causing the fee not to add. For the Building Fee for an Accessory Dwelling, there have been no rules provided (i.e. none in V7), so need to know the exact criteria under which this should add.

**Comment by ABonomo21** [comment]
sent Dan an email on how homebuilders are put in the system for H7

**Comment by ABonomo21** [comment]
Building fees are correct for ADUs, that part of this issue is fixed-AW

**Comment by ABonomo21** [comment]
closed due to this being the same as #324  ADU portion of this issue is fixed and working propertly-aw
