### ISSUE TITLE
PLANNING PREPLAT - FRO as a child requirement in admin closure

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#692]
Admin Closure should populate a check for FRO not approved as a Child Application. 
![image](https://user-images.githubusercontent.com/4129185/55967563-862ce280-5c48-11e9-84f6-e02e787b3bdb.png)

**Comment by goggansd** [comment]
@megisys, this is the one we discussed on your drive back home. Rules apparently unclear for FRO permit requirement.

**Comment by dhenry-KCI** [comment]
Corrected PP239273
