### ISSUE TITLE
License data migration-parent child relationship

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#694]
We need to make sure the data migration of all new and existing license holders have the company parent child relationships marked as "also add as a licensed child"-AW
![image](https://user-images.githubusercontent.com/47611580/55972080-c8f2b880-5c50-11e9-8b1b-c4a98437c9a3.png)

**Comment by goggansd** [comment]
@megisys, this needs to be included in data migration...

**Comment by ABonomo21** [comment]
resolved
