### ISSUE TITLE
Zoning Certificate - Bypass Case Log 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#695]
I am attempting to bypass a zoning certificate with a case and the bypass case log is not working. 

![image](https://user-images.githubusercontent.com/47611580/55984722-17618080-5c6c-11e9-83bf-f7cf994f6acb.png)

**Comment by goggansd** [comment]
Fixed in IPSTest environment. Please retest.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/56045015-62cc6b00-5d0e-11e9-9a05-c2226025fd1e.png)
