### ISSUE TITLE
ResBldg-Accessory Dwelling Unit-Building Fee did not generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#696]
The building fee did not generate for an Accessory Dwelling Unit. The fee for this type of ADU should have been $572, The fees for the various ADU fees are below-AW

![image](https://user-images.githubusercontent.com/47611580/56137392-bafbab00-5f62-11e9-8cb2-f72579257c6a.png)

![image](https://user-images.githubusercontent.com/47611580/56137465-ec747680-5f62-11e9-9c40-343b20f5abb8.png)

**Comment by ABonomo21** [comment]
fees are not generating according to the type of ADU and then by the square footage of that type.-AW
#240374
![image](https://user-images.githubusercontent.com/47611580/56214496-ff9f4900-602b-11e9-83c5-bae641ae90af.png)
when going to check yes to this "section complete" this error message appears as well.
![image](https://user-images.githubusercontent.com/47611580/56214469-f4e4b400-602b-11e9-9b74-3478c0a4eb06.png)
![image](https://user-images.githubusercontent.com/47611580/56214682-5a38a500-602c-11e9-87cc-8623233c3dc9.png)


#240378
![image](https://user-images.githubusercontent.com/47611580/56214592-2c536080-602c-11e9-90df-3f313348377d.png)
![image](https://user-images.githubusercontent.com/47611580/56214706-63297680-602c-11e9-9faf-670a907fc7dd.png)
same error message for this permit
![image](https://user-images.githubusercontent.com/47611580/56214607-34130500-602c-11e9-9920-f568348b1422.png)

**Comment by ABonomo21** [comment]
This is mostly fixed- all but one type of ADUs are fixed-AW
**NOT FIXED**
ADU-within a single family dwelling-not fixed (see fee worksheet above for correct fees)
![image](https://user-images.githubusercontent.com/47611580/56219743-447bad80-6035-11e9-8724-50c339381f9a.png)
![image](https://user-images.githubusercontent.com/47611580/56219802-59584100-6035-11e9-8132-265fa3d71c5f.png)


**FIXED**
ADU-addition to SFD 3000 sq ft or less-fixed
![image](https://user-images.githubusercontent.com/47611580/56217310-04b2c700-6031-11e9-878c-ce7673601e47.png)

ADU-addition to SFD 3000 sq ft or more-fixed
![image](https://user-images.githubusercontent.com/47611580/56219014-fdd98380-6033-11e9-97ef-6e8bd32aca22.png)

ADU-stand alone/separate accessory structure 4000 sq ft or less-fixed
![image](https://user-images.githubusercontent.com/47611580/56220221-134fad00-6036-11e9-8760-7cad9ab69e30.png)

ADU-stand alone/separate accessory structure 4000-6500 sq ft-fixed
![image](https://user-images.githubusercontent.com/47611580/56220656-ce784600-6036-11e9-995f-d6870430813d.png)

ADU-stand alone/separate accessory structure 6500 sq ft or more-fixed
![image](https://user-images.githubusercontent.com/47611580/56221106-9c1b1880-6037-11e9-96c8-6d2290076bc4.png)

**Comment by megisys** [comment]
Adjusted

**Comment by ABonomo21** [comment]
ADU within a SFD-fixed-AW
![image](https://user-images.githubusercontent.com/47611580/56233524-3f2c5c00-6051-11e9-886d-d015cb71309c.png)
