### ISSUE TITLE
License - Appliance Installer - License Details Page

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#7]
The system needs additional information presented to the user on the Appliance Installers Trade License Details Page. Currently the system is only presenting the user with standard trade license details.

Logged by Kelly V. on 2/4

See screenshot below for those fields to be added

![image](https://user-images.githubusercontent.com/4129185/52349901-74835080-29f5-11e9-9ebf-4298c2843d4b.png)

**Comment by megisys** [comment]
@dhenry-KCI  Please Verify with SWalter & ABonomo. As we said this was a completeness check operating procesure to review attachments

**Comment by megisys** [comment]
Removing Bug

**Comment by ABonomo21** [comment]
@dhenry-KCI @ABonomo21 same as Issue #6 if this is to be checked during completeness check, then we just need to make sure the information of the required documents to upload is stated on Rhythm for Civics for the applicant to see.-AW

**Comment by ABonomo21** [comment]
This detail page should be called Appliance License Detail Page
![image](https://user-images.githubusercontent.com/47611580/55024003-59d05f80-4fd4-11e9-82f4-2cde552ce563.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
Please correct the detail page as follows: 

![image](https://user-images.githubusercontent.com/47611580/55505813-f375bd80-5621-11e9-8c90-86e4ab07d3e5.png)

**Comment by dhenry-KCI** [comment]
@kellyjj - can you address this issue today so we can close License?

**Comment by kellyjj** [comment]
I have made the changes to detail page.  I added the column  StateNGLicenseReceivedCB to the table Inforclient.AgencyCDR.TradeLicense.ApplianceMasterDetail

setting to retest

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/55642641-06fa6300-579f-11e9-9eff-16066d6235b5.png)

**Comment by ABonomo21** [comment]
fixed
