### ISSUE TITLE
Building - ResBldg - Ap Status 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#70]
Single Family Dwelling Permit #237215 & Plumbing Permit #237217- the building permit is still stating that a plumbing permit of a utility type is required even though the plumbing permit attached has the utilities on the permit. On the plumbing permit application, there is not a type of work that includes utilities that does not include gas work. Just as there is a type of plumbing work “Plumbing, Natural Gas, & Utilities” we need to have a “Plumbing and Utilities” option so customers without gas work can still input their information and meet the requirements of the building permit.

AP - 237215 & 237217
Logged by A.White 2/18

![image](https://user-images.githubusercontent.com/4129185/53106584-5c392880-3501-11e9-8fd9-b9a44da35543.png)
![image](https://user-images.githubusercontent.com/4129185/53106685-8ee32100-3501-11e9-80e4-fc7eb5410a8e.png)
![image](https://user-images.githubusercontent.com/4129185/53106693-9276a800-3501-11e9-8182-6a19e9ccbed0.png)
![image](https://user-images.githubusercontent.com/4129185/53106703-960a2f00-3501-11e9-8519-f137d0b794fa.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Added new Plumbing Type = "PLUMBU - PLUMBING AND UTILITIES" and Updated the following formulas to include this new type (basically wherever UTILITY is also mentioned:
1)BP_PLUMBUtilityPermitRelated_SCF
2)RESBLDG_InspNotResulted_ISC
3)NONRESBLDG_InspNotResulted_ISC
4)RESUSES_InspNotResulted_ISC

Please see screenshots for proof of testing (RESBLDG: AP# 236143 PLUMBPERM: AP#236144 in DEV):

**PLUMBU Added to List:**
<img width="960" alt="issue70_plumbuaddedtolist" src="https://user-images.githubusercontent.com/47784290/53124729-16448a80-352a-11e9-9d37-51717776887f.png">


**Status check on RESBLDG before attaching Plumbing Permit still showing:**
<img width="960" alt="issue70_resbldgstatecheckbefore" src="https://user-images.githubusercontent.com/47784290/53124775-32e0c280-352a-11e9-81f6-f8311e12ef62.png">

**Status check on RESBLDG after attaching Plumbing Permit doesn't show anymore:**
<img width="960" alt="issue70_resbldgstatecheckafter" src="https://user-images.githubusercontent.com/47784290/53124783-3aa06700-352a-11e9-8d7e-ee1d1d2a2a25.png">

**Comment by dhenry-KCI** [comment]
Confirmed Fixed. 
![5](https://user-images.githubusercontent.com/4129185/53257002-2a59ca80-3697-11e9-8d13-af78bd443f91.jpg)
