### ISSUE TITLE
Non-Residential- Incorrect Fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#701]
Permit# 240383; Non-Residential New Complete Structure; Missing the $50 Health Review Fee (Food is checked off), $317.16 Life Safety Review Fee, $555.03 Building Fee for NEW-ADD-REPLACE-ACCESS, and the $210 Site Compliance Fee-MCoffman

![image](https://user-images.githubusercontent.com/47611580/56217544-6b37e500-6031-11e9-9680-970d8535cc61.png)

**Comment by megisys** [comment]
Can you try another address and let me know

**Comment by ABonomo21** [comment]
Fees generated correctly for a different address-AW
![image](https://user-images.githubusercontent.com/47611580/56234188-c201e680-6052-11e9-965f-7129ae30f91c.png)

**Comment by ABonomo21** [comment]
closed-worked on other address, the original issued was due to an GIS issue that needs to be addressed with Dan and GIS-aw
