### ISSUE TITLE
Non-Residential-Reviews

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#705]
Permit# 240383; New Complete Building; Only DUSWM Review Generated-MCoffman
![image](https://user-images.githubusercontent.com/47611580/56219913-8c023980-6035-11e9-8c2d-d999dd2ce22c.png)

**Comment by megisys** [comment]
PLease try a non FR Address and an FR Address

**Comment by ABonomo21** [comment]
Correct reviews generated-AW
![image](https://user-images.githubusercontent.com/47611580/56234394-350b5d00-6053-11e9-943d-b1355c792a9d.png)
