### ISSUE TITLE
R4C - Add Additional Applicant - all application types (Excel Issue #36)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#707]
Make highlighted fields required in R4C that are not currently required

![image](https://user-images.githubusercontent.com/4129185/56291525-705d6880-60f3-11e9-935d-ea4a9142e993.png)

![image](https://user-images.githubusercontent.com/4129185/56291637-9edb4380-60f3-11e9-91b4-92994c6dc945.png)

**Comment by dhenry-KCI** [comment]
Add (*) Areed

**Comment by calequin** [comment]
getting dev to look at this feature

**Comment by dhenry-KCI** [comment]
DH - Must have per County

**Comment by calequin** [comment]
applicant invite has been configured for r4c.

**Comment by dhenry-KCI** [comment]
Closing this issue as we will not be leveraging the invite applicant functionality
