### ISSUE TITLE
Building - Capacity - Capacity Adjustment Factor

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#708]
The system should allow the user to edit the Capacity Adjustment Factor.

Logged by L. Englar

![Capacity permit](https://user-images.githubusercontent.com/4129185/56292181-b23ade80-60f4-11e9-827a-dd042c854231.png)

**Comment by goggansd** [comment]
This is a calculated field, so a workflow formula calculates the value based on other data in the system.

**Comment by dhenry-KCI** [comment]
@goggansd - can you tell us what fields are included to calculate the capacity adjustment factor so we can test it?

**Comment by goggansd** [comment]
It uses the Business Class code value to determine the Capacity Adjustment Factor, as follows:
ACS:  0.12
APT: 0.37
APS: 0.37
AST: 0.19
AUT: 0.32
BTY: 0.21
BOW: 0.64
CAR: 0.00
CHY: 0.05
CHN: 0.05
COL: 0.09
CTR: 0.2
BTH: 0.42
CON: 0.37
GAS: 0.55
COR: 0.27
DAY: 0.11
DIS: 0.14
DRY: 0.11
BNK: 0.07
FIY: 0.11
FIN: 0.14
FUN: 0.15
GRO: 0.27
HLT: 0.22
HOY: 0.34
HON: 0.17
SKT: 1.07
IRR: 0.00
LIB: 0.04
MAN: 0.00
MED: 0.16
OFF: 0.16
OFP: 0.16
RSY: 0.58
RSN: 0.46
RTL: 0.18
RET: 0.14
POL: 0.00
POF: 0.05
SCH: 0.09
SHL: 1.0
SHP: 0.25
STR: 0.37
TRL: 0.35
WHS: 0.82
All Others: 0.00

Not sure if these rules came from V7 or were given to the Infor analyst, but they are very specific, and so should be provided to Frederick County staff so they are aware of the business rules.

**Comment by dhenry-KCI** [comment]
@JuanitaMiles we will need to confirm these items with DUSWM on Thursday morning. Marking as ready for PrePrd Testing.

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - reminder to walk DUSWM through this issue

**Comment by JuanitaMiles** [comment]
Lauren was able to update the Capacity Adjustment Factor.

**Comment by JuanitaMiles** [comment]
The CAP value did not save when manually updating. Reopening
