### ISSUE TITLE
Building - Capacity - Final Fixture Count

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#713]
The system should sum the Fixture Value field for all records populated in the Final Fixture Count Grid in the Total Quantity field above the Final Fixture Count Grid.

![TOTAL FU](https://user-images.githubusercontent.com/4129185/56293319-db5c6e80-60f6-11e9-9fdc-776d00c9c525.PNG)

**Comment by megisys** [comment]
Where is this screen ? If it is on Intake, it will not calculate until you save the application. As Logic is run on the server and until you have saved all the information is on the users computer.

**Comment by goggansd** [comment]
Same question as for Preliminary fixtures: why is this issue being kicked back? Is it not behaving as megisys describes (i.e. saving the detail page data and opening the page again)? Or is it that megisys's reply is not being accepted?

**Comment by ABonomo21** [comment]
at the time the final inspection was completed, the final fixture count on the grid was updated, additional fixtures were found which should have resulted in additional fees being added however, the fees did not add. 

![image](https://user-images.githubusercontent.com/47611580/57231532-ad2cc900-6fe8-11e9-825d-32126d7a3289.png)

**Comment by goggansd** [comment]
@megisys, this will need SA review, as there is no milestone set up for these fees to add after final inspection, and we'd need to double all the fee types, since the rest of them are configured to add on in the Inspections milestone.

**Comment by JuanitaMiles** [comment]
@dhenry-KCI need to have a follow up conversation on the when the final fixture counts are entered and when/how the associated fees would generate. In Hansen 7 there is currently a Final Fixture Count inspection on the Capacity permit that does not exist in IPS.

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - has this been resolved?

**Comment by JuanitaMiles** [comment]
This can be tested as part of issue #1267 . Closing this issue.
