### ISSUE TITLE
Building - Capacity - Quantity Field

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#714]
In the Preliminary Fixture Count Grid the Qty field should default to 1. The user will add additional records for the same fixture. 

![Add FU](https://user-images.githubusercontent.com/4129185/56293432-0ba40d00-60f7-11e9-9bca-3fa8f46bc641.PNG)

**Comment by megisys** [comment]
The grid wont let you have duplicates. Just a total count.. Feel this is a training exercise

**Comment by ABonomo21** [comment]
Got it.
