### ISSUE TITLE
Building -Capacity - Final Fixture Quantity

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#715]
In the Final Fixture Count Grid the Qty field should default to 1. The user will add additional records for the same fixture. 

![TOTAL FU](https://user-images.githubusercontent.com/4129185/56293486-24acbe00-60f7-11e9-84a1-3afceab536be.PNG)

**Comment by megisys** [comment]
Duplicate
