### ISSUE TITLE
R4C - NID Details - format/grouping of information

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#716]
Format should group together the same way as IPS. See IPS image. AReed

![image](https://user-images.githubusercontent.com/4129185/56293438-0fd02a80-60f7-11e9-8773-fc3a0cba0e27.png)
![image](https://user-images.githubusercontent.com/4129185/56293449-16f73880-60f7-11e9-89d1-d3b2ff88bad9.png)

**Comment by dhenry-KCI** [comment]
Make proposed commercial type of use box the same size as the other boxes. areed

**Comment by megisys** [comment]
Detail Page updated

**Comment by dhenry-KCI** [comment]
Fix Proposed Commercial Type of Use Box to make it the same size as the rest. AReed 
![image](https://user-images.githubusercontent.com/4129185/66767252-f7f71a80-ee7d-11e9-88cd-ea5e8694718b.png)

**Comment by dhenry-KCI** [comment]
fixed.

![image](https://user-images.githubusercontent.com/4129185/66842593-89779280-ef39-11e9-8ff8-93d42171ebc7.png)

mw
