### ISSUE TITLE
NonRes Detail Page-Business Use box

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#717]
The Business Use box on the NonRes Detail page does not have the search option (the magnifying glass button on other boxes). It does have the type ahead feature but unless you know the exact code you need to enter, you won't be able to find the correct Business Use type. The type ahead also shows the "showing 5 of 84 matches" but you can not click on this to be able to open the search pop up window. -AW
Currently in Hanson 7:
![image](https://user-images.githubusercontent.com/47611580/56294175-83266c00-60f8-11e9-9e36-a9df891f499c.png)
Currently in IPS 11:
![image](https://user-images.githubusercontent.com/47611580/56294240-a6511b80-60f8-11e9-8361-ce4c57b135ae.png)

**Comment by megisys** [comment]
Fixed

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/56966281-c4713f80-6b2c-11e9-8b53-50551fde3718.png)
