### ISSUE TITLE
R4C - NID - Review tab

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#718]
Review Tab in R4C should show what was entered under NID Details so the applicant can appropriately review. It only shows titles of fields to fill out. Areed

![image](https://user-images.githubusercontent.com/4129185/56294476-1d86af80-60f9-11e9-80ac-185f6c3f6e60.png)
![image](https://user-images.githubusercontent.com/4129185/56294516-29727180-60f9-11e9-8a98-ec5fa47b4195.png)

**Comment by dhenry-KCI** [comment]
This came up when using internet explorer but not chrome

![image](https://user-images.githubusercontent.com/4129185/56298131-9f79d700-60ff-11e9-8aee-05503940719e.png)

**Comment by megisys** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
ok on 4/25/19
