### ISSUE TITLE
NonRes Detail Page-Operating Hours Box

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#719]
The Operating Hours box has the search option however when clicking on the magnifying glass button, there are no options to select in the pop up window. They are all blank.-AW

![image](https://user-images.githubusercontent.com/47611580/56294750-938b1680-60f9-11e9-8058-ce6028b70cbe.png)

The same goes for the two Grease Trap Size Boxes
![image](https://user-images.githubusercontent.com/47611580/56294875-cfbe7700-60f9-11e9-8854-1d4545f2317b.png)
![image](https://user-images.githubusercontent.com/47611580/56294919-e49b0a80-60f9-11e9-8e7a-f9ad6c6029f7.png)

**Comment by megisys** [comment]
This is addressed

**Comment by ABonomo21** [comment]
Fixed-aw
![image](https://user-images.githubusercontent.com/47611580/56966110-8247fe00-6b2c-11e9-8aee-b2d7808adaf8.png)
![image](https://user-images.githubusercontent.com/47611580/56966232-aacff800-6b2c-11e9-932b-9a0a6b85b68a.png)
