### ISSUE TITLE
Planning - Lot of Recordation - Review Dates

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#72]
The system should generated the following review due dates based on Work Type

LORDET, PSRVER, YRDMOD = 2 week reviews

ZONVER - 3 week

**Comment by megisys** [comment]
@dhenry-KCI  This ticket is lacking.. What AP Type is this ?

**Comment by dhenry-KCI** [comment]
@megisyss
Planning - Lot of Recordation 
titles are generally module then AP

**Comment by megisys** [comment]
But what AP type am I fixing ? Lot of Recordation doesn't happen in every AP Type.  Also this Recordation happens after review ? Confused @dhenry-KCI

**Comment by dhenry-KCI** [comment]
@megisys - Verification Letter is the AP type - the following work types should be updated

LORDET, PSRVER, YRDMOD = 2 week reviews

ZONVER - 3 week

**Comment by megisys** [comment]
Ready for Testing After CTT from Dev

**Comment by dhenry-KCI** [comment]
**LORDET - Defaulting to 2 business days for review- should be 2 weeks**
![image](https://user-images.githubusercontent.com/4129185/53665367-47634000-3c39-11e9-8bd6-e5fb5060e480.png)
![image](https://user-images.githubusercontent.com/4129185/53665378-4e8a4e00-3c39-11e9-9624-f9b587f747fa.png)
![image](https://user-images.githubusercontent.com/4129185/53665432-6b268600-3c39-11e9-89b7-4c586049e5be.png)

**PSRVER  - Defaulting to 2 business days for review- should be 2 weeks**
![image](https://user-images.githubusercontent.com/4129185/53665472-85f8fa80-3c39-11e9-8af6-f17669acab5c.png)
![image](https://user-images.githubusercontent.com/4129185/53665537-b6d92f80-3c39-11e9-9ed2-c9f175a6a164.png)
![image](https://user-images.githubusercontent.com/4129185/53665558-c22c5b00-3c39-11e9-87b5-8f8a28aa891d.png)

**ZONVER   - Defaulting to 2 business days for review- should be 3 weeks**
![image](https://user-images.githubusercontent.com/4129185/53665746-4979ce80-3c3a-11e9-8ac0-6cdb87a8ea21.png)
![image](https://user-images.githubusercontent.com/4129185/53665717-3a931c00-3c3a-11e9-9d25-4b8b43cd7a63.png)
![image](https://user-images.githubusercontent.com/4129185/53665793-6f9f6e80-3c3a-11e9-9c05-fe5d086318f9.png)

**Comment by megisys** [comment]
This has been addressed..

**Comment by dhenry-KCI** [comment]
LORDET fixed
PSRVER fixed
YRDMOD fixed
ZONVER fixed

MW 3/7/19
