### ISSUE TITLE
R4C opening attachment sent from county to applicant

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#721]
unable to open the attachment sent to applicant from country

![image](https://user-images.githubusercontent.com/4129185/56295655-20829f80-60fb-11e9-953e-bbca8bff810d.png)

![image](https://user-images.githubusercontent.com/4129185/56295746-385a2380-60fb-11e9-9867-e958c6368655.png)

**Comment by calequin** [comment]
please retest
