### ISSUE TITLE
PLANNING - NID - NOTIFICATION

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#722]
Need email notification once review resulted in IPS for NID to advise applicant that results are available. It would be helpful to include the review results in notification. Areed. 
I thought Christian was working on this, but I just close one and didn't get an email. Didn't want it to get missed.

**Comment by megisys** [comment]
This should be a report and Correspondence. AS we want this on letterhead and formatted

**Comment by dhenry-KCI** [comment]
@TaraF - including you so you are aware. Martin will be discussing with you.

**Comment by mmbanong** [comment]
Do we have an answer to Dan's question "Have a Planning Outcome Notification. Do we still need a matching Correspondance" ?

**Comment by dhenry-KCI** [comment]
Duplicate of #1382 - closing

**Comment by dhenry-KCI** [comment]
works.

![image](https://user-images.githubusercontent.com/4129185/64619970-051d7700-d3b1-11e9-9da6-7319fbe0ceb9.png)


MW
