### ISSUE TITLE
R4C - Due Date (Excel Issue #41)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#724]
Where does R4C provide the due date? If it is not hidden somewhere, it needs to be added so the applicant knows when to expect completion on ALL applications. Permits and Planning. AReed.

![image](https://user-images.githubusercontent.com/4129185/56299415-fb455f80-6101-11e9-803d-f57c19f9dd9b.png)

**Comment by megisys** [comment]
Application Expectations to be added in SOP and Instuctions

**Comment by dhenry-KCI** [comment]
Dan,  R4C needs to show the review due date.  How will an applicant know when to expect review comments?

**Comment by megisys** [comment]
Review dates are under Review details

**Comment by megisys** [comment]
Logged with Dan West in Email

**Comment by dhenry-KCI** [comment]
DH - Must have per County

**Comment by calequin** [comment]
added due date to scheduled date formula in order to make it visible in rhythm

![image](https://user-images.githubusercontent.com/47603568/64637651-e2e42300-d3c9-11e9-8765-6ae958612d75.png)
