### ISSUE TITLE
ResBldg-Driveway permit did not automatically generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#725]
The driveway permit did not generate automatically for this SFD permit #240445 even though the New Driveway Apron box was checked and it was marked as Open Section. This could have something to do with the fact that the Open or Closed Driveway Box does not have any options to select when typing in that box, therefore it does not have any data to correctly read off of for the driveway information. It should only allow the options of  O or C but you can type any letter and it will take it as part of the application.-AW
#240445
![image](https://user-images.githubusercontent.com/47611580/56300099-4f9d0f00-6103-11e9-809c-a0c9ce5bc04b.png)
![image](https://user-images.githubusercontent.com/47611580/56300141-62afdf00-6103-11e9-986f-e64c6cc5f6f7.png)

It let me put in the letter A for open or closed section driveway, it should only accept O or C and they should be drop down options to click just like other option boxes
![image](https://user-images.githubusercontent.com/47611580/56300455-fc778c00-6103-11e9-9030-1bfeda1fa61c.png)

**Comment by goggansd** [comment]
Attempted to address this issue in several ways--all of which were prevented by either bad test data, the existing configuration, or server permissions. Currently, the BuildingDetails table is likely unusable due to an error which @megisys must address.

![image](https://user-images.githubusercontent.com/28841997/56441935-b7e32080-62bc-11e9-836a-74914cd696f5.png)

**Comment by megisys** [comment]
Fixed

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/56965444-55dfb200-6b2b-11e9-8b57-f68fc1cad053.png)
**
![image](https://user-images.githubusercontent.com/47611580/56965467-62fca100-6b2b-11e9-920b-7425b071d316.png)
**

**Comment by ABonomo21** [comment]
#749 when an open section is selected the driveway permit should auto generate.

**Comment by megisys** [comment]
Ready for restest

**Comment by ABonomo21** [comment]
the driveway and grading fees did not generate for this permit (since the driveway and the grading permit auto generated). Good to go on Building side, need to confirm with Tiffany that Driveway/Grading permits work accordingly.-AW
![image](https://user-images.githubusercontent.com/47611580/57018859-ea611780-6bf2-11e9-993a-5add434811b9.png)

**Comment by ABonomo21** [comment]
works correctly. - ab
