### ISSUE TITLE
R4C-Yard Mod- details not showing

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#727]
Yard Mod
under review application, the details did not show.  I hot the back button, then returned to review application, and the details appeared.  

![image](https://user-images.githubusercontent.com/4129185/56301229-62b0de80-6105-11e9-9d72-6921301c007f.png)

MW

**Comment by calequin** [comment]
Please retesst

**Comment by dhenry-KCI** [comment]
ok on 4/24/19

MW
