### ISSUE TITLE
R4C - FRO - R4C changes

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#728]
-Change "Title" to request Project/Phase Name from the Job Descriptions tab in IPS
-Remove Declared Valuation - That is an internal field to IPS only.
-Remove"Square Footage" field
areed

![image](https://user-images.githubusercontent.com/4129185/56300338-c6d2a300-6103-11e9-8e43-f5e37b1768c0.png)

**Comment by megisys** [comment]
Updated the Constraints

**Comment by dhenry-KCI** [comment]
page looks the same as it did a week ago.

![image](https://user-images.githubusercontent.com/4129185/56684818-84c6d580-669e-11e9-8702-cbd961f112b2.png)

MW

**Comment by megisys** [comment]
Addressed This

**Comment by dhenry-KCI** [comment]
ok 4/30/19

MW
