### ISSUE TITLE
Building - ZoningCert - Zoning Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#73]
The zoning review did not generate for the ag building permit

AP - 237190
Logged by A.White 2/15

![image](https://user-images.githubusercontent.com/4129185/53107320-d1592d80-3502-11e9-9764-5a80dc91d8dc.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/55737549-5afd8580-59f3-11e9-9e9a-7368dcd96efa.png)
