### ISSUE TITLE
R4C - Applications

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#730]
Sometimes Planning apps Populate, sometimes they don't under Licenses & Permits on R4C
Why? AReed 
Using Internet Explorer

![image](https://user-images.githubusercontent.com/4129185/56301855-aa843580-6106-11e9-8165-98273689d3df.png)

**Comment by calequin** [comment]
This is a result of performance and whenever we refresh the application. All available AP types come back up after a refresh is done in test.
