### ISSUE TITLE
R4C -PLANNING Applications (Excel Issue #43)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#733]
Reviewing for comments under R4C. Comments are hidden. At minimum, I think they should come up under Needs Action instead of All. Areed
![image](https://user-images.githubusercontent.com/4129185/56310588-42d7e580-611a-11e9-803d-52afe8cf135b.png)
![image](https://user-images.githubusercontent.com/4129185/56310629-5e42f080-611a-11e9-9faf-9649c268392b.png)

**Comment by dhenry-KCI** [comment]
Excessive delays and minutes of spinning when you click View Details under the review to see comments from the reviewers. areed

**Comment by megisys** [comment]
This is not possible. This is an enhancement request

**Comment by calequin** [comment]
currently being researched as an enhacement by dev. This will have the default screen be "ALL" instead of "Needs Action"

**Comment by calequin** [comment]
duplicate of #766
