### ISSUE TITLE
R4C - FRO revision

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#734]
F239296
Applicant actions - ACTION Changes and Attachments Made - Save
No re-submission received in IPS - still in Awaiting Applicant Revisions
Areed

![image](https://user-images.githubusercontent.com/4129185/56311725-b11da780-611c-11e9-9647-66e84f2dd0f2.png)
![image](https://user-images.githubusercontent.com/4129185/56311751-bbd83c80-611c-11e9-913a-5be1fde9c122.png)

**Comment by dhenry-KCI** [comment]
See resubmittal log. resubmittal finally went through but look how many times it says it was sent. Areed
![image](https://user-images.githubusercontent.com/4129185/56312247-c0512500-611d-11e9-894f-eed02684ffee.png)

**Comment by calequin** [comment]
please retest

**Comment by dhenry-KCI** [comment]
all fixed per F239447

MW
