### ISSUE TITLE
R4C - Dashboard for applicant - additional project/site info (Excel Issue #32)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#735]
Under My Dashboard, it would be helpful if the Project/Phase name and Address/Tax ID were visible. The list doesn't provide enough information for our large developers and Engineers who may have 50 or more open projects at any given time. Areed

![image](https://user-images.githubusercontent.com/4129185/56312753-e0cdaf00-611e-11e9-8150-3a387ec41106.png)

**Comment by calequin** [comment]
part of the november release for r4c will address this issue
