### ISSUE TITLE
R4C-FRO-Final FRO-Occupancy Type drop box blank

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#737]
Occupancy type drop box has nothing in it to select

![image](https://user-images.githubusercontent.com/4129185/56314130-36578b00-6122-11e9-8d44-32a495e2a07d.png)

MW

**Comment by calequin** [comment]
work type needs to be selected first in order for Occupancy type filter codes to populate.

**Comment by calequin** [comment]
adding verbiage for this to be clear to the applicant

**Comment by dhenry-KCI** [comment]
ok per F239447
MW
