### ISSUE TITLE
R4C - Resubmittal (Excel Issue #51)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#738]
Applicant is able to continue resubmitting in R4C and it is registered in the log without IPS needing a resubmittal. This needs to communicate with IPS so R4C doesn't allow the applicant to resubmit when it is not appropriate. They also should not be able to resubmit during a review cycle.
AReed

![image](https://user-images.githubusercontent.com/4129185/56315648-3c4f6b00-6126-11e9-8628-242d3fdaf6ba.png)

**Comment by calequin** [comment]
Would this be a likely scenario? Once the resubmittal is sent the applicant action page will be in a closed position.

**Comment by dhenry-KCI** [comment]
still able to submit new attachments while in the under review milestone.  Need to change R4C so that "applicant actions" is disabled until IPS and PDox?  actually requests an action by the applicant

MW

**Comment by calequin** [comment]
Currently being researched by Dan with workflow formula that will disable detail page updates and attachments after submittal.

**Comment by megisys** [comment]
Attachment is already a ticket with Christian.
