### ISSUE TITLE
R4C - Parcels in Municipality

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#739]
VP239305 Sumitted Lot of Record Verification Letter with parcel in Town of Emmitsburg. R4C allowed me to submit and pay for this. R4C can not allow applications without completeness check to accept municipality parcels. There is no way for staff to recognize this and provide feedback before fees are paid. 

![image](https://user-images.githubusercontent.com/4129185/56364712-3f496a80-61bd-11e9-92a4-6569bcf0c4f1.png)
![image](https://user-images.githubusercontent.com/4129185/56364724-483a3c00-61bd-11e9-94e1-d15fa2f4d5f0.png)

**Comment by megisys** [comment]
Mike Can you tell me the rules of when a Verification letter should be rejected.. Eg.. It in Township give message to User . "COunty doesnt issue letters for townships" Please contact your township

**Comment by dhenry-KCI** [comment]
we should only accept Planning applications from towns for the following ap types:
-water/sewer
-PWConstruct
-FRO

I believe all of these alreayd have an intake review before fees are paid so we can catch the odd balls that dont belong to the county

**Comment by dhenry-KCI** [comment]
created Lot of Record application for town of Brunswick.  see VP239530.  Will also let me submit for City of Frederick.

MW

**Comment by dhenry-KCI** [comment]
still allowing verification applications for towns....
![image](https://user-images.githubusercontent.com/4129185/58043316-dbdb9100-7b0a-11e9-8deb-866cefcf66f8.png)

CT/MW

**Comment by dhenry-KCI** [comment]
Addition Plat – town of Myersville accepted
ID PL239592

**Comment by calequin** [comment]
fixed formula and tested with a BOA and address in thurmont. The error message displayed correctly. Succesfully submitted with a FredCo parcel #14322124 application number 239616

**Comment by dhenry-KCI** [comment]
R4C allowed me to submit a Lot of Record Determination within the Incorporated Town of Emmitsburg 
unable to attempt to pay fees at this time because of issue with Govolution - KEV 

![#739](https://user-images.githubusercontent.com/4129185/58809163-6632f300-85e9-11e9-9626-f8d289ecd798.PNG)

**Comment by megisys** [comment]
Dim res As Hansen.Core.Result = Result.Success
Dim ParcelKey as Integer

'Control level message 
If oPlanningApplication.Address.AddressKey < 1001 And oPlanningApplication.Parcel.ParcelKey < 1001 Then

	Dim resLoc As Hansen.Core.Result = New Result(1, ResultSeverity.UserError, "Please search and add a Primary Site")

	resLoc.properties.Add("validationError", "locationDetails")

	res += resLoc

End If

For Each oApplicant As Hansen.CDR.PLanning.IApplicant In oPlanningApplication.Applicants

	If String.IsNullOrEmpty(oApplicant.Contact.EMailAddress) Then

		Dim resLoc As Hansen.Core.Result = New Result(1, ResultSeverity.UserError, "Please ensure all additional contacts have a valid email address")

		resLoc.properties.Add("validationError", "ContactDetails")

		res += resLoc

		Exit For

	End If

Next

Dim Allowable as Boolean = False
Dim TownShipCode as String

If oPlanningApplication.Parcel.ParcelKey > 1000 Then

TownshipCode = oPlanningApplication.Parcel.Township.Code.Trim()

End if

If oPlanningApplication.Address.AddressKey > 1001 Then

	For Each oParcelLink As Hansen.Property.IAddressParcelLink In oPlanningApplication.Address.AddressParcelLinks
	
	TownshipCode = oParcelLink.Parcel.Township.Code.Trim()

	Next

End If

if TownShipCode = "00" then

Allowable = True

Elseif oPlanningApplication.ApplicationType.ApplicationType = "PWCONSTRUC" and TownShipCode <> "04" then
	
Allowable = True

Elseif oPlanningApplication.ApplicationType.ApplicationType = "WSPLANS" then

Allowable = True

Elseif oPlanningApplication.ApplicationType.ApplicationType = "FRO" and (TownShipCode="01" or TownShipCode="09" or TownShipCode="02" or  TownShipCode="11" or TownShipCode="12" or TownShipCode="10")  then

Allowable = True

End if

if TownshipCode = "" Then

Allowable = True

End if

	
	If Allowable = False Then

				Dim resLoc As Hansen.Core.Result = New Result(1, ResultSeverity.UserError, "Frederick County doesn't accept this type of Application for this Parcel")

				resLoc.properties.Add("validationError", "MunicipalityPlanningApp")

				res += resLoc

	Return res

		
	End If

**Comment by dhenry-KCI** [comment]
retest failed.  Was able to submit Lot of Record for City of Frederick.

![image](https://user-images.githubusercontent.com/4129185/59693786-720be100-91b5-11e9-8121-5ec3d0d6b194.png)


MW

**Comment by calequin** [comment]
There seems to be some sort of address data issue. Upon searching for 515 w patrick the system has 2 valid addresses. Once has a township code associated to it (parcel) the other does not. I verified by typing in the parcel that is associated to one of the 515 w patrick addresses and this correctly displays the "error" message. Parcel #02020947. This is an address cleanup function
![image](https://user-images.githubusercontent.com/47603568/59697836-299ff380-91b4-11e9-9a2a-e448aac5b276.png)

**Comment by dhenry-KCI** [comment]
@pooldaddy @mmbanong - addressing issue . Please confirm.

**Comment by pooldaddy** [comment]
There is only 1 address record in H7 PROD for 515 W Patrick Street
