### ISSUE TITLE
PLANNING - Rename JUNK

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#741]
Junk is showing on R4C. Junk needs to be renamed in IPS. 
ID F239310
![image](https://user-images.githubusercontent.com/4129185/56369301-1c23b880-61c7-11e9-8d19-69f8c7e2cfd7.png)

**Comment by dhenry-KCI** [comment]
areed

**Comment by goggansd** [comment]
Addressed in IPSTest. Please retest.

**Comment by ABonomo21** [comment]
Changed to Not Applicable
