### ISSUE TITLE
Mobile - Attachments in IPS from Mobile

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#742]
When there is more than three attachments that have come in from the mobile inspection, the fourth attachment is barely visible in the Attachments tab. There is no way to scroll to see the fourth attachment.

![image](https://user-images.githubusercontent.com/31770504/56386213-3b364080-61ef-11e9-92d6-145ee53e5699.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/56502900-f73e8680-64e1-11e9-8c49-e339a87ff36f.png)

**Comment by megisys** [comment]
Might be a refresh issue.. Lets monitor this one

**Comment by ABonomo21** [comment]
looks corrected closing now
