### ISSUE TITLE
R4C-FRO-withdraw application

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#743]
tried to withdraw an application that was under review and got this error.

![image](https://user-images.githubusercontent.com/4129185/56426467-691a9400-6286-11e9-9a14-febfdb0b5c5d.png)

![image](https://user-images.githubusercontent.com/4129185/56426496-84859f00-6286-11e9-9e1a-acfa499e1d20.png)

MW

**Comment by calequin** [comment]
please retest
