### ISSUE TITLE
R4C-yard Mod-withdraw issue

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#744]
withdrew application through R4C, approved request in IPS, R4C showing closed status BUT still has request withdrawal option

![image](https://user-images.githubusercontent.com/4129185/56427643-9f5a1280-628a-11e9-9735-ca3f9def50d4.png)

MW

**Comment by calequin** [comment]
added the pending withdrawal attribute to the application. This will come up as a pending task for the applicant to see in rhythm for civics whenever they request a withdrawal from the county. Please retest

**Comment by dhenry-KCI** [comment]
fixed per YD239335

MW
