### ISSUE TITLE
R4C-dashboard-cant view project details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#745]
if I click an AP number or hit the view details button on my dashboard the system gets stuck in loading mode

![image](https://user-images.githubusercontent.com/4129185/56428509-9dde1980-628d-11e9-9f81-8cfd5c7ca3ec.png)

![image](https://user-images.githubusercontent.com/4129185/56428519-ab939f00-628d-11e9-8bdb-46c7630a4a37.png)

MW

**Comment by calequin** [comment]
Couldnt replicate the issue. Was the user logged in for more than 30 minutes? There is a timeout period of 30 minutes on the server which may cause it to go into a loop. Please retest

**Comment by dhenry-KCI** [comment]
Stuck in Loading mode. Set up new NID and clicked on link to open and it continues to spin. I have not been logged in more than 30 min.  Areed

**Comment by dhenry-KCI** [comment]
ok on 4/24/19

MW
