### ISSUE TITLE
Building- ResUse- Sq. Ft.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#746]
Unable to fill sq. ft. field in on Resuse permits
![image](https://user-images.githubusercontent.com/47611580/56436775-fd96ed80-62aa-11e9-8523-9fc32dfbb7fd.png)

**Comment by ABonomo21** [comment]
Retest failed, unable to input square footage.-AW

![image](https://user-images.githubusercontent.com/47611580/56963907-12377900-6b28-11e9-88d5-28ad036f19a1.png)

**Comment by ABonomo21** [comment]
Dan please look into this

**Comment by goggansd** [comment]
Fixed this in IPSTest, although the issue is that this AP Type was set for "Use Job Estimation" (@megisys), which conflicts with the Square Footage field bein input manually on the Job Description tab. If Job Estimation is required for this AP Type, this will need to be revisited.

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/57227901-7f438680-6fe0-11e9-9895-c8014664d03c.png)
