### ISSUE TITLE
R4C-dashboard-fees not showing under "my fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#747]
$115 due for a yard mod but "my fees" shows $0.00 due

![image](https://user-images.githubusercontent.com/4129185/56437048-fde3b880-62ab-11e9-992b-47a3402af6be.png)

Mw

**Comment by calequin** [comment]
please retest

**Comment by dhenry-KCI** [comment]
ok on 4/24/19  

MW
