### ISSUE TITLE
Building - Removal of Reviews and Fees for Grading, SWM & Driveway

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#749]
Need to have a discussion regarding which reviews and fees to remove from resbldg, resuse and nonres building permits when a grading/swm or driveway permit is auto generated based on details completed on the building details tab.

**Comment by megisys** [comment]
Changes Made

**Comment by dhenry-KCI** [comment]
1. Permit #240530 Resbldg - SFD - a minor grading permit spawned but the driveway permit did not spawn.

2. Permit #240532 (condo building) spawned a minor grading permit (#240533) BUT this should be a Major Grading permit. 

3.
*On resbldg townhouses, condos and apartments should spawn a major grading permit
*For resuse and resbldg swimming pools and all new res single family dwellings should automatically spawn a minor grading permit
*On anything else building permit wise - including non-res, additions, accessory buildings either a major grading or minor grading permit should be spawned based on cut/fill quantities and/or earth disturbance quantities. 

logged by tiffany martin 4/30/19

**Comment by goggansd** [comment]
Addressed item 1 (the DRIVEWAY issue for permit number 240530) in the IPSTest environment. See test scenario permit # 240601.

**Comment by goggansd** [comment]
Addressed item 2 (the GRADING permit should have been MAJOR for permit 240532) in the IPSTest environment. See test scenario RESBLDG permit # 240607, which spawned GRADING (MJ) permit # 240609.

**Comment by ABonomo21** [comment]
fixed- permit #245641-fees generated correctly.
![image](https://user-images.githubusercontent.com/47611580/59038601-44cc4400-8841-11e9-825d-f705dda02576.png)
