### ISSUE TITLE
Building - ZoningCert - Notification

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#75]
Did not receive any email notifications other than “your permit has been approved and issued” - should receive additional email for the review resubmittal and the fees needing to paid.

AP - 237190
Logged by A.White 2/15

**Comment by megisys** [comment]
Added

**Comment by ABonomo21** [comment]
partially fixed. I only received an email for the fees needing to be paid. I did not receive any emails for the revision/resubmit. #240307  -AW
![image](https://user-images.githubusercontent.com/47611580/55969500-e40ef980-5c4b-11e9-8fb9-37819e211574.png)

**Comment by goggansd** [comment]
Could not replicate. Please tetest:

![image](https://user-images.githubusercontent.com/28841997/55984168-db79eb80-5c6a-11e9-9daf-4ed678193a9c.png)

**Comment by ABonomo21** [comment]
I still am only receiving email notifications regarding payments being due. I have not received an email notification stating that more information is needed for the review resubmit.-AW

![image](https://user-images.githubusercontent.com/47611580/56046479-5d245480-5d11-11e9-8c4c-67bbfffea0e1.png)
![image](https://user-images.githubusercontent.com/47611580/56046499-6a414380-5d11-11e9-9da5-3ec9b208f0fb.png)

**Comment by ABonomo21** [comment]
Fixed-Received emails for revision requirements.-AW

![image](https://user-images.githubusercontent.com/47611580/56985510-8557e400-6b56-11e9-94c4-e6f3883b83ce.png)
