### ISSUE TITLE
Building Permit- Resbldg- Error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#750]
Tried to create a new SFD applicaiton this morning and received the following error when trying to save and create an a/p #. 
![image](https://user-images.githubusercontent.com/47611580/56507459-5951b880-64ef-11e9-8be8-1462437986cf.png)

**Comment by megisys** [comment]
Hey Ashlye, 

I dont get this error see 240482 .. What combinations on the detail page are you using ?

Dan

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/56508559-a2573c00-64f2-11e9-84e3-a0c0d5313914.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/56508649-d7638e80-64f2-11e9-9736-7149db7471eb.png)

**Comment by ABonomo21** [comment]
closed will monitor
