### ISSUE TITLE
Planning-BOA-Hearing 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#751]
when resulting a BOA hearing to deferred IPS stage progresses to Admin closure.  Whenever a hearing is resulted as deferred or denied it needs to remain in the Hearing milestone.  Same issue weas fixed in other Planning Aps.

![image](https://user-images.githubusercontent.com/4129185/56519945-3a641e00-6511-11e9-9f8a-bcbce39da5d4.png)

MW

**Comment by megisys** [comment]
Fixed

**Comment by megisys** [comment]
Mike give it another go

**Comment by dhenry-KCI** [comment]
fixed per testing on 4/29/19

MW
