### ISSUE TITLE
Inspections - Partial Inspection Error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#753]
Did not request partial inspection on R4C populated with partial request 
![image](https://user-images.githubusercontent.com/47611580/56610368-46b5ad00-65dd-11e9-89cc-940bb021ae97.png)

**Comment by goggansd** [comment]
Tried adding myself as an applicant to this same permit, then adding a new BLDG-FOOT inspection in IPS, then attempted a RESCHEDULE in R4c using my R4C login. I specifically did not check the "Partial Inspection" box when rescheduling.

![image](https://user-images.githubusercontent.com/28841997/56814364-0b99c080-680d-11e9-910b-73525ca42659.png)

The workflow formula which add the comment from the initial screenshot does clear out the Partial Inspection checkbox, however.

**Comment by ABonomo21** [comment]
Requested multiple inspections and have not found this error. marking this as closed-AW
