### ISSUE TITLE
Inspections - IPS

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#754]
Should have:

call date(or dated request was submitted)
requested date(date the request is being submitted for)
scheduled date(date the inspection is to be performed)
Completed date (date the inspection was performed)

![image](https://user-images.githubusercontent.com/47611580/56610614-d65b5b80-65dd-11e9-8aeb-d39c9ebe0c69.png)

**Comment by megisys** [comment]
This has been resolved.. Please see Chnage Audit Log. This keeps the history

**Comment by ABonomo21** [comment]
Closed-able to search under the lookup inspections and schedule inspections.-AW
