### ISSUE TITLE
Inspections- Search Filters

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#755]
Unable to filter the  inspections based on status and date range like in H7 
H7 Status- All, no action, passed, failed, canceled, hold, closed, partial
Dates that can be searched- Call, scheduled, started, completed

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/56659950-54feda00-666c-11e9-9a3d-ef6bf36fc425.png)

This will be much more powerful

**Comment by ABonomo21** [comment]
This fix should work, will run by Bob Ensor
