### ISSUE TITLE
R4C- Tank Permit - Detail Page 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#756]
the question for distance to the nearest well head requires a quantity to be entered however, the ft. should be after the text box not on the next line. 
![image](https://user-images.githubusercontent.com/47611580/56680099-8c817c80-6694-11e9-8af2-f288101d20b6.png)

**Comment by megisys** [comment]
Added to Label Text

**Comment by ABonomo21** [comment]
corrected
