### ISSUE TITLE
R4C - Tank Permit- No ID #

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#757]
no id number populated when I clicked save and continue, however I received a confirmation that the application was completed

![image](https://user-images.githubusercontent.com/47611580/56680261-f1d56d80-6694-11e9-80e1-f2997ec7464a.png)

**Comment by ABonomo21** [comment]
application was not added to IPS 

![image](https://user-images.githubusercontent.com/47611580/56680604-935cbf00-6695-11e9-8917-da8f091b31cb.png)

**Comment by megisys** [comment]
This was a Performance linked issue

**Comment by ABonomo21** [comment]
Unable to duplicate again will monitor, closing for now
