### ISSUE TITLE
R4C-yardmod-details layout

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#758]
change "house" to home for constancy.  Keep the Home B field under the Home B address, and Home A details under Home A address

![image](https://user-images.githubusercontent.com/4129185/56680441-424ccb00-6695-11e9-842e-f3580d31bbf8.png)

MW

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57243440-c0955f80-6ffb-11e9-8fcf-5ebd124c72ff.png)
fixed. please retest

**Comment by dhenry-KCI** [comment]
house and home being used.  Please make all "house"

![image](https://user-images.githubusercontent.com/4129185/57244048-85982980-7005-11e9-8bce-d55e46774a0f.png)


MW

**Comment by calequin** [comment]
fixed all to say House

**Comment by dhenry-KCI** [comment]
fixed-mw
