### ISSUE TITLE
R4C - Spinning 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#759]
![image](https://user-images.githubusercontent.com/47611580/56680429-3b25bd00-6695-11e9-95ca-c4b045619303.png)

spinning when trying to click on the ID number for a building permit application (tank)

**Comment by ABonomo21** [comment]
related to #757

**Comment by megisys** [comment]
Fixed Last week

**Comment by ABonomo21** [comment]
still spinning occasionally - will monitor
