### ISSUE TITLE
Planning - Verification Letters - Resubmit Comments

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#76]
User results the review as a resubmit but the system did not for the user to populate required comments back to the applicant.

AP VP237212 
Logged by A. Reed

![image](https://user-images.githubusercontent.com/4129185/53107867-fac68900-3503-11e9-9597-9a0b2b5640f2.png)

**Comment by megisys** [comment]
Duplicate Issue. Same As Resubmit on Letters

**Comment by ABonomo21** [comment]
![resubmit](https://user-images.githubusercontent.com/47611580/53980929-900a7580-40df-11e9-86b5-be2ca1dc2633.PNG)
Fixed - 3/7/19 - KVanaman
