### ISSUE TITLE
R4C- Application population 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#760]
![image](https://user-images.githubusercontent.com/47611580/56680698-bc7d4f80-6695-11e9-8595-754e07aaa933.png)

Applications are not all available for selection have to refresh to generate list

**Comment by calequin** [comment]
The issue comes up whenever a resync is done with the enhancement folders. I will monitor this

**Comment by ABonomo21** [comment]
closed will monitor
