### ISSUE TITLE
Planning-yard mod-wrong due date

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#761]
created AP through R4C.  IPS shows a one month review period.  Needs to be 2 weeks

MW

![image](https://user-images.githubusercontent.com/4129185/56681609-ac666f80-6697-11e9-902e-acf6aebe42b1.png)

**Comment by dhenry-KCI** [comment]
FYI, second review has correct 2 week review period.

![image](https://user-images.githubusercontent.com/4129185/56681933-72499d80-6698-11e9-8d7c-1924de4e97ba.png)
MW

**Comment by dhenry-KCI** [comment]
now its coming up as 20 days.  Needs to be 2 weeks

![image](https://user-images.githubusercontent.com/4129185/56755102-b7cf9e80-675c-11e9-9131-6823ed0f5ed5.png)


MW

**Comment by goggansd** [comment]
Fixed in IPSTest environment.

![image](https://user-images.githubusercontent.com/28841997/56815021-51a35400-680e-11e9-84b9-a168002d0e01.png)

**Comment by dhenry-KCI** [comment]
ok per YD239354 on 4/26/19

MW
