### ISSUE TITLE
R4C-cant download attachments from IPS-YD239338

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#762]
cant download attachments sent from IPS to R4C

![image](https://user-images.githubusercontent.com/4129185/56682306-44b12400-6699-11e9-9798-1d95439011ab.png)

![image](https://user-images.githubusercontent.com/4129185/56682334-5692c700-6699-11e9-917d-7a9bd7648f4d.png)

MW

**Comment by megisys** [comment]
Mike you are using the wrong attachment catalog. This is correct behavior. Please Use Attachment catalog

**Comment by dhenry-KCI** [comment]
ok

MW
