### ISSUE TITLE
Planning-FRO-application created an automatically finalized

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#763]
created F239340 through R4C.  Opened ap in IPS and it was already finalized.  See 12:00am date stamp.  This was created at 2:50pm+/_

![image](https://user-images.githubusercontent.com/4129185/56685660-78437c80-66a0-11e9-97ce-d328ff1fca8f.png)

MW

**Comment by dhenry-KCI** [comment]
also happening in Yard mods.  See YD239342

MW

**Comment by dhenry-KCI** [comment]
label wasnt changed from BUG to ready, but seems to be working fine 4/26/19.  AP239357

**Comment by goggansd** [comment]
Cannot duplicate, but Christian just synchronized the Enhancement folder for R4C, so we are assuming that this was caused by the Enhancement folders being out of synch due to ongoing work in the IPSTest environment. Please retest.
