### ISSUE TITLE
Mobile - Application Description in Mobile App

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#764]
Is it possible to make the application description visible in the inspection on the mobile app?

**Comment by JuanitaMiles** [comment]
Christian is currently researching this functionality.

**Comment by ABonomo21** [comment]
@calequin can you please provide a status update

**Comment by calequin** [comment]
Im meeting with one of our mobile experts tomorrow in order not to cause disruptions during testing. Ill have an update by Monday morning 5/6.

**Comment by calequin** [comment]
Per conversation with mobile developer it is technically possible but not recommended as this can cause issues down the line during upgrades and go live.

**Comment by dhenry-KCI** [comment]
complete
