### ISSUE TITLE
R4C - Error 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#765]
![image](https://user-images.githubusercontent.com/47611580/56748706-4f79c080-674e-11e9-91ae-4eda6a09df16.png)

**Comment by megisys** [comment]
Sync of Enhancment Completed

**Comment by ABonomo21** [comment]
still getting the error will monitor

**Comment by ABonomo21** [comment]
closed will monitor
