### ISSUE TITLE
R4C-all applications-dashboard-review results/comments (Excel Issue #43)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#766]
once an AP is closed, the task should have the "all" option highlighted/ set to default. 

![image](https://user-images.githubusercontent.com/4129185/56760311-ebb0c100-6768-11e9-8c2d-8c58f22ef647.png)

**Comment by calequin** [comment]
Would like to see the "ALL" field displayed. This allows the applicant to see the review results, fees, and all tasks. The applicant will then select the needs action button if they want to filter what they need to do.

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/56966630-1e6e0700-6b25-11e9-912c-c4d754d8e54e.png)

**Comment by calequin** [comment]
part of July release of r4c

**Comment by dhenry-KCI** [comment]
DH - Must have per County

**Comment by calequin** [comment]
needs 1906 backoffice patch

**Comment by calequin** [comment]
ready for test. Once application is closed the ALL button is automatically enabled.
![image](https://user-images.githubusercontent.com/47603568/61755941-6648a700-ad7f-11e9-806d-358ca22a48bb.png)

**Comment by dhenry-KCI** [comment]
Confirmed fixed for closed application. R4C shows, inspections, fees and reviews for closed permit.
