### ISSUE TITLE
R4C-Prelim-application page details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#768]
Page 1:
-remove declared value (this is only in FRO, not sure why its here)
-Title should be a required field
-need acres not square footage
see 1st screen shot below

Page 2: 
-remove a ton of stuff- see 2nd screen shot below

![image](https://user-images.githubusercontent.com/4129185/56829398-9be9fc80-6831-11e9-8d31-5df907b495f7.png)

![image](https://user-images.githubusercontent.com/4129185/56829556-0d29af80-6832-11e9-886d-34983a11bfff.png)

MW

**Comment by megisys** [comment]
Addressed Issues

**Comment by dhenry-KCI** [comment]
square footage is still on here.  please remove.
![image](https://user-images.githubusercontent.com/4129185/56985039-6dcc2b80-6b55-11e9-9ca5-a15b06338e96.png)

**Comment by calequin** [comment]
fixed please retest

**Comment by dhenry-KCI** [comment]
good to go

MW
