### ISSUE TITLE
Planning - Verification Letter - Applicant Resubmit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#77]
The system does not present the user with applicant actions to resubmit under the applicant details tab.

VP237212
Logged by A. Reed

![image](https://user-images.githubusercontent.com/4129185/53107985-39f4da00-3504-11e9-8f90-5e01b1a4c120.png)

**Comment by megisys** [comment]
Duplicate Ticket

**Comment by dhenry-KCI** [comment]
corrected AReed
