### ISSUE TITLE
R4C- Sign Permit (Excel Issue #41)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#770]
Unable to see the fully expanded use and sign type in the grid.
![image](https://user-images.githubusercontent.com/47611580/56831367-e02bcb80-6836-11e9-8fc2-2f228e9f7383.png)

**Comment by calequin** [comment]
Sending this over to Dan West

**Comment by ABonomo21** [comment]
still unable to see the full list of Sign Use and Type-AW
![image](https://user-images.githubusercontent.com/47611580/57231349-5e7f2f00-6fe8-11e9-89ae-d11b0caae37c.png)

**Comment by ABonomo21** [comment]
fixed with the new pop window-AW
![image](https://user-images.githubusercontent.com/47611580/57930890-1d5b0a80-7885-11e9-8cd0-d422ff78d7d8.png)

![image](https://user-images.githubusercontent.com/47611580/57930888-1a601a00-7885-11e9-8fd9-b1f094d917f7.png)
