### ISSUE TITLE
R4C - Sign Permit 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#772]
CIP should not have the word project after it CIP stands for Capital Improvement Project. 

Also they should both be above the section complete.... 

![image](https://user-images.githubusercontent.com/47611580/56831552-5cbeaa00-6837-11e9-90e2-dbb1e1dae0da.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
corrected
