### ISSUE TITLE
R4C-Plat-error on application page-

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#773]
error "pages is required".  No place to enter pages. cant finish application

![image](https://user-images.githubusercontent.com/4129185/56831356-d30edc80-6836-11e9-854b-220cbed57c74.png)

MW

**Comment by calequin** [comment]
fixed. moved the pages constraint to the intake review as a required field

**Comment by dhenry-KCI** [comment]
fixed 4/30/19   MW
