### ISSUE TITLE
R4C - System Timing Out

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#777]
I was actively working in R4C and the system gave me an error and changed the address at the bottom of the screen

![image](https://user-images.githubusercontent.com/47611580/56832052-cc816480-6838-11e9-8056-a44b4a21ac18.png)

**Comment by ABonomo21** [comment]
still an issue spoke with christian he will correct

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57252179-30621500-7011-11e9-81f2-0cf538d7b7d0.png)
fixed

**Comment by ABonomo21** [comment]
it's fixed on some pages, others have different addresses. not sure if this is correct or not?-AW
My Dashboard page:
![image](https://user-images.githubusercontent.com/47611580/58031146-d1f76500-7aed-11e9-88cc-233c5b4445b4.png)
Submit an Application page:
![image](https://user-images.githubusercontent.com/47611580/58031157-da4fa000-7aed-11e9-8d4e-478c108194cd.png)

**Comment by calequin** [comment]
fixed address on both timeout and initial dashboard screen

**Comment by ABonomo21** [comment]
Has not happened while testing currently - closed will mark as will monitor
