### ISSUE TITLE
R4C-FRO-gross tract acres field

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#778]
too large for a number field

![image](https://user-images.githubusercontent.com/4129185/56832137-1bc79500-6839-11e9-9ce9-57889a84c2e2.png)

MW

**Comment by calequin** [comment]
Forwarding to Dan West

**Comment by calequin** [comment]
fixed by Dan G. Please retest

**Comment by dhenry-KCI** [comment]
looks good 4/30

MW
