### ISSUE TITLE
Building - ZoningCert - Related Records

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#78]
After creating a plumbing permit (237193) to attach to the zoning certificate (237190), when going to attach the zoning certificate #237190 to the plumbing permit #237193 as the parent, it shows that the two are connected as parent/child permits.  However, the plumbing permit is still stuck in the completeness check stage stating “building permit must be related as parent application”

AP - 237190
Logged by A.White 2/15

![image](https://user-images.githubusercontent.com/4129185/53107930-1c277500-3504-11e9-841d-450cc499ee95.png)
![image](https://user-images.githubusercontent.com/4129185/53108309-cf906980-3504-11e9-89a2-384435746f86.png)

**Comment by imazlout** [comment]
Status Check is currently looking for a parent of type "RESBLDG", "NONRESBLDG", or "RESUSES" to be attached, which is why it doesn't go away when the tester attached a ZONINGCERT permit. @ABonomo21 Should the formula be updated to allow for "ZONINGCERT" as well?

**Comment by ABonomo21** [comment]
Yes, the formula should be changed to include zoning certificates. 
This will affect others a/p types as well, we will define that relationship and send them as well.

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Updated formula PLUMBPERM_ParentBldAP_SCF So that it checks for ZONINGCERT in addition to resbldg,resuses, and nonresbldg

Please screenshot for proof of test (AP# 236157 in DEV)

<img width="960" alt="issue78_fixed" src="https://user-images.githubusercontent.com/47784290/53192359-4482a280-35dc-11e9-93b5-e5453a5e4d1d.png">

**Comment by imazlout** [comment]
Relating Issue 92 to this Issue was done in error, please ignore

**Comment by dhenry-KCI** [comment]
Confirmed Fix; was able to close out both the Zoning Certificate and the Plumbing permit with the related records attaching correctly.

Zoning Certificate A/P#237346
Plumbing A/P# 237349

![image](https://user-images.githubusercontent.com/4129185/53263252-d656e200-36a6-11e9-8f25-279dd3fd7719.png)

![image](https://user-images.githubusercontent.com/4129185/53263276-e79fee80-36a6-11e9-99d5-2d9a326588f6.png)
