### ISSUE TITLE
R4C-break down AP types by Permits vs Planning (Excel Issue #40)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#780]
we discussed this months ago.  Need to break these down into proper categories.

![image](https://user-images.githubusercontent.com/4129185/56832425-f5562980-6839-11e9-9fa6-5c4738bf50a5.png)

MW and AB

**Comment by megisys** [comment]
This is not possible in current release - this is an enhancement request

**Comment by dhenry-KCI** [comment]
DH - Must have per County

**Comment by calequin** [comment]
Needs 1906 Backoffice patch

**Comment by calequin** [comment]
ready for test
![image](https://user-images.githubusercontent.com/47603568/61755560-d1917980-ad7d-11e9-93fe-5af5600b868c.png)

**Comment by calequin** [comment]
categories can also be broken down inside the modules. for example, Business License can have a category called Liquor and have all related Liquor Licenses applications

**Comment by dhenry-KCI** [comment]
Confirmed correct. Closing issue.
