### ISSUE TITLE
R4C- Land Use Application - No Site address

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#781]
There is no field for site address on the Land Use Application 

![image](https://user-images.githubusercontent.com/47611580/56832690-ae1c6880-683a-11e9-8dcc-399db0f24eac.png)

**Comment by megisys** [comment]
Adjusted and added as Constraint

**Comment by ABonomo21** [comment]
Still not corrected. There is nowhere for the applicant to fill in a site address

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/56969425-2339b780-6b33-11e9-84f3-813500f1ef57.png)

**Comment by calequin** [comment]
verified and worked.

**Comment by ABonomo21** [comment]
resolved
