### ISSUE TITLE
R4C-Preplat-cant pay fees

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#782]
go through the credit card process, submit, and it returns me to the "my fees" page and still shows I owe fee.

MW

**Comment by megisys** [comment]
There seems to be a limit..

**Comment by calequin** [comment]
Conversation with Suzana from Govulation. Currently set to a limited amount

**Comment by ABonomo21** [comment]
closed will monitor
