### ISSUE TITLE
Project - Capacity should not be a required field 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#787]
Capacity should not be a required for project 
![image](https://user-images.githubusercontent.com/47611580/56970349-f4244580-6b34-11e9-80ea-9f394c2200a2.png)

**Comment by megisys** [comment]
Addresssed

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/57245688-71eec200-7009-11e9-8f74-2938ecc0c384.png)
