### ISSUE TITLE
Planning-APFO-hearing milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#790]
deferred or denied is stage progressing instead of staying in hearing

MW

![image](https://user-images.githubusercontent.com/4129185/56980955-b383f680-6b4b-11e9-8a48-d0b19afb4028.png)

**Comment by megisys** [comment]
This is Addressed

**Comment by dhenry-KCI** [comment]
ok per A239401

MW
