### ISSUE TITLE
Planning-Preplat-hearing milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#791]
wont stage progess past hearing when hearing resulted as approved.

![image](https://user-images.githubusercontent.com/4129185/56981295-897f0400-6b4c-11e9-92ae-df1c59c26866.png)

MW

**Comment by megisys** [comment]
Addressed

**Comment by dhenry-KCI** [comment]
ok per PP239402

MW
