### ISSUE TITLE
Building - Grading 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#794]
#240542 the DPZ review was resulted as resubmit and the applicant resubmitted and there is no admin review to show that the applicant has resubmitted. 

tm 4/30/19

**Comment by megisys** [comment]
Added New Adhoc Report for this.. Lets review together

**Comment by ABonomo21** [comment]
Dan showed us how to run the Adhoc Report. Closing.

Thanks Dan!
