### ISSUE TITLE
Building - Grading / Driveway - Issue Comment

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#795]
The Building permit 240540 is pending issuance, but the grading and driveway are at intake review and completeness check. Can you add a comment that grading and driveway must be issued

Prior to issuance of the building permit; grading, driveway and capacity must be at the issuance milestone. System should redline the building permit to alert the user.

![image](https://user-images.githubusercontent.com/4129185/56987541-b8e93d00-6b5b-11e9-8492-ea0a7cfab7c4.png)

**Comment by megisys** [comment]
Added Code to handle this to RESBLDG

**Comment by ABonomo21** [comment]
Corrected.

5/2/19 EP

**Comment by ABonomo21** [comment]
Correct 

5/2/19
