### ISSUE TITLE
R4C - Service Request- Primary Site (Excel Issue #36)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#797]
I was able to submit a service request without a primary site. Primary site should be required.

![image](https://user-images.githubusercontent.com/47611580/56988139-52fdb500-6b5d-11e9-8fd4-721892c2162c.png)

**Comment by calequin** [comment]
fixed

**Comment by calequin** [comment]
fixed primary site required field. enhancement for March 2020 will address the error message needed on the 1st page

**Comment by dhenry-KCI** [comment]
In the update of 20.3 error will be presented to the user at the save and continue page rather than the confirmation page.

**Comment by dhenry-KCI** [comment]
@calequin - the user is able to meet the primary site location requirement by typing in the site description field, but NOT having selected an actual address. IS it possible to enforce the requirement on the selection of the address specifically?

**Comment by calequin** [comment]
@dhenry-KCI , the enhancement will fulfill this request. see comment above.
