### ISSUE TITLE
R4C-credit card issue

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#798]
used 4159299999999997 visa

![image](https://user-images.githubusercontent.com/4129185/56988704-b0463600-6b5e-11e9-9035-4ae029044cf2.png)

MW

**Comment by dhenry-KCI** [comment]
5/2: No longer getting error message but when I pay fees it sends me back to "My Fees" page and the fee isnt paid.

MW

**Comment by calequin** [comment]
fees are processing correctly. please retest

**Comment by dhenry-KCI** [comment]
just tried paying $7,000 in fees with same result as before.

MW

**Comment by dhenry-KCI** [comment]
fee payment still fails.  Couldnt pay a $58 fee for A239497

**Comment by calequin** [comment]
please retest
