### ISSUE TITLE
R4C-My Fees-All showing

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#799]
When I open the details of an application on my dashboard and click pay fee, it takes me to the "my fees" page, which lists every fee for every application on the dashboard that has outstanding fee payments.  This is a bit overwhelming.  It would be better to only show the fees that are due for the application that I selected on my dashboard.

![image](https://user-images.githubusercontent.com/4129185/57016474-538f5d80-6be8-11e9-9678-651795ed37b0.png)

![image](https://user-images.githubusercontent.com/4129185/57016490-6dc93b80-6be8-11e9-9993-2164f522fa07.png)

![image](https://user-images.githubusercontent.com/4129185/57016443-1cb94780-6be8-11e9-839f-65b25d1ee1c2.png)

![image](https://user-images.githubusercontent.com/4129185/57016510-820d3880-6be8-11e9-904e-7c75bdd57df9.png)

MW

**Comment by calequin** [comment]
In a scenario where a customer is applying for applications the fee list wont be as monumental as the testing environment. The fees are listed out as a "checkout cart" option in order for citizens not to miss or get confused on what to pay. Once in the checkout they can select which fees they want to pay including the application number right under. CA
