### ISSUE TITLE
License - Plumbing License - Create Professional ID

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#8]
The system is requiring the user to populate the Professional ID field. This field should NOT be required.

Logged by Shannon W. 

![image](https://user-images.githubusercontent.com/4129185/52350206-025f3b80-29f6-11e9-931b-ca53461bd76d.png)

**Comment by goggansd** [comment]
This is how the core product behaves: if you select the "Is Agency Contractor" checkbox, the Professional ID field becomes required.

**Comment by JuanitaMiles** [comment]
Spoke to Shannon, and she came to same conclusion. This is a training issue to note in the future. Closing the issue.
