### ISSUE TITLE
R4C-Planning-Plat-details (Excel Issue #45)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#803]
remove declared value.  Add Platbook/Page # and recordation date. 

![image](https://user-images.githubusercontent.com/4129185/57018925-209e9700-6bf3-11e9-8f05-bdf7a0c31a39.png)

**Comment by calequin** [comment]
Removed declared valuation.

**Comment by calequin** [comment]
cant add pages. adding this to our list to development
