### ISSUE TITLE
Planning-email notification for "ready for review"

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#804]
i believe this was recently added to inform the applicant of the review due date for each review cycle.  Email needs to include the due date. 

![image](https://user-images.githubusercontent.com/4129185/57020153-77f23680-6bf6-11e9-876c-7d0bf3e97dc2.png)

MW

**Comment by dhenry-KCI** [comment]
DH - Must have per County

**Comment by dhenry-KCI** [comment]
@mmbanong - please add appropriate date time text

**Comment by dhenry-KCI** [comment]
not getting this notification at all now.  Should get it for internal review.

![image](https://user-images.githubusercontent.com/4129185/64183104-5371c980-ce37-11e9-9c7f-36c0df602c48.png)

![image](https://user-images.githubusercontent.com/4129185/64183138-61bfe580-ce37-11e9-93b5-ec2e0edecb3f.png)


MW

**Comment by dhenry-KCI** [comment]
No review due date on the notification. AR
![image](https://user-images.githubusercontent.com/4129185/64202902-44ebd800-ce60-11e9-8476-f0be34f01646.png)

**Comment by megisys** [comment]
We need to talk about this.. We are hitting an issue that as this notification is sending when entering the Under Review milestone and the reviews have yet to be added. We can not dictate this. Need to come up with a solution

**Comment by dhenry-KCI** [comment]
Notification will alert the user that the application is under review. User will need to login in to R4C to view due dates. 

Closing issue and assigned training.
