### ISSUE TITLE
R4C- Land Use - No ID (Excel Issue #58)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#805]
I was able to submit an application for a land use and hit save and continue it generated an application submitted with no ID number.. not in my dashboard. 

![image](https://user-images.githubusercontent.com/47611580/57021324-db319800-6bf9-11e9-871d-9b80ec60ae62.png)

**Comment by ABonomo21** [comment]
closed - will monitor

**Comment by calequin** [comment]
came across again while doing a building application.

**Comment by calequin** [comment]
cant seem to replicate this issue

**Comment by ABonomo21** [comment]
Able to replicated on License and Use and again on building (grading)

**Comment by ABonomo21** [comment]
will monitor
