### ISSUE TITLE
Planning - YardMod - Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#81]
This should be a 2 week review period, not 2 days.

AP - YD237203
Logged by K.Vanaman 2/19

![image](https://user-images.githubusercontent.com/4129185/53110241-8d692700-3508-11e9-868c-4f5a27750480.png)

**Comment by megisys** [comment]
Changed

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/53758161-3dd11680-3e8b-11e9-8ce7-e7e302cdf18d.png)
Issue corrected note 3/18/19 due date 
thx T
