### ISSUE TITLE
Planning-PWConst-"notification to applicant" conditions populating

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#814]
this is the issue Dan fixed in Site and Plat on 5/1.

![image](https://user-images.githubusercontent.com/4129185/57082947-befb2d00-6cc5-11e9-9ff7-9fffec8c9a4f.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58963377-0704e800-877b-11e9-8427-039cec00f170.png)

No conditions populated - Fixed - KEV
