### ISSUE TITLE
Building - Driveway - Entrance Apron Details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#815]
We would like to have a drop down for the following questions under the entrance apron details. We only want the four in the screen shot below, the fifth could be true and associated with any of the four listed in the screen shot.

![image](https://user-images.githubusercontent.com/4129185/57084345-26b27780-6cc8-11e9-8039-33b8fdd0ee57.png)

tm/ep 5/2/19

**Comment by ABonomo21** [comment]
relate to #869

**Comment by ABonomo21** [comment]
missing the highlighted line- should be added as Yes/ No option under Entrance Apron Details

![image](https://user-images.githubusercontent.com/47611580/59038302-d2f3fa80-8840-11e9-90bf-a8d4325d8634.png)
6/6/19 EP

**Comment by megisys** [comment]
Added Back

**Comment by ABonomo21** [comment]
Question- 

It has been removed from historical data, will this affect the migration since there is no longer a checkbox under historical data- will it migrate over? if it will migrate over under the entrance details- this issue on tic #815 can be closed. 

6/20/19 EP

**Comment by megisys** [comment]
It will migrate over.. Just the check box is hidding from the page..

**Comment by dhenry-KCI** [comment]
Closing per EP comment
