### ISSUE TITLE
All- Notifications on Holds 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#817]
There needs to be a notification sent to all applicants for all holds.

**Comment by megisys** [comment]
If you add a UI or PI Hold Log.. Applicants will be notified

**Comment by ABonomo21** [comment]
notifications are not turned on to retest.

**Comment by ABonomo21** [comment]
I added a PI Hold on permit #246884 and did not receive any notification. They still might not be turned on but wanted to add that it was tested-AW

**Comment by ABonomo21** [comment]
closing and will review format with Ashlye and Juanita as a group for all modules
