### ISSUE TITLE
Fire - After Hour Inspections (Excel #54)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#819]
After hours inspections for fire should have a comment on the inspection request page that says:

"To request an after hours inspection for Fire Permits ONLY, please submit your request via email to Permits@FrederickCountyMD.gov. Requests must be submitted and approved a minimum of 3 business days prior to the requested date."

[image](https://user-images.githubusercontent.com/47611580/57089970-b4e02b00-6cd3-11e9-99dd-61da39f0ed59.png)

**Comment by calequin** [comment]
added verbiage to the inspection screen

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/59977040-0600f280-9592-11e9-97b5-49389ab7321b.png)

**Comment by ABonomo21** [comment]
we need to make this language only come up on Fire Permits- it is confusing to have in on the general inspections page !

**Comment by dhenry-KCI** [comment]
Per Ashlye B. is this can not be applied to the Fire AP specifically, then please remove the language.

**Comment by calequin** [comment]
removed the language on inspections

**Comment by ABonomo21** [comment]
thank you
