### ISSUE TITLE
Planning-FRO-easement details (notification)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#820]
need to provide deed of easement details in R4C so applicant has Liber/Folio and recordation date.

MW

**Comment by calequin** [comment]
added deeds of easement to R4C. keep in mind the grid format will change in the July update.

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57543259-8092ed00-7319-11e9-8d14-c641113d6d80.png)

**Comment by dhenry-KCI** [comment]
not working.  Not showing up in R4C

![image](https://user-images.githubusercontent.com/4129185/57724814-9fff8200-7659-11e9-89b5-d394979259b8.png)

**Comment by calequin** [comment]
need to research

**Comment by calequin** [comment]
Discussed with @megisys and this information will be available as a notification. If we expose the detail page the applicant will have the ability to edit these fields after the fact which we do not want.

**Comment by dhenry-KCI** [comment]
ok, then i guess the easement details you added last week need to be removed from R4C

**Comment by calequin** [comment]
removed from r4c. need to create notification @megisys

**Comment by dhenry-KCI** [comment]
@mmbanong - need notification created.

**Comment by dhenry-KCI** [comment]
Martin,

Use the plat recordation notification below as a template.  It should read:

Your Forest Resource Ordinance easement F123456-name of project-has been recorded.

Liber 1234
Folio 4567

Date Recorded _/_/_

Thank You,

Department of Development Review and Planning.



This needs to be sent when the deeds of easement details area entered.  When entered the project will move from admin closure to finalized.

![image](https://user-images.githubusercontent.com/4129185/64183421-e14db480-ce37-11e9-9113-72e82ab74e23.png)


MW

**Comment by mmbanong** [comment]
I created PLN_FRO-EasementDetails notification based on thr recordation details. Dan I am not sure what properties of to assosciate with Liber and Folio any suggestions

![image](https://user-images.githubusercontent.com/47392173/64197293-af4a4b80-ce53-11e9-8e9d-201b9095deb8.png)

**Comment by dhenry-KCI** [comment]
works, but the highlighted area needs to have real info

MW

![image](https://user-images.githubusercontent.com/4129185/64622112-cc7f9c80-d3b4-11e9-8e64-d304ecd07bba.png)

**Comment by mmbanong** [comment]
Dan,

{{oDeed.DeedDetailKey.ApplicationDetailKey.PlanningApplication.ApplicationNumber}} 
     is   not returning expected values from oDeed object

**Comment by dhenry-KCI** [comment]
remove "fro not"

![image](https://user-images.githubusercontent.com/4129185/65700288-6306bb80-e04d-11e9-9abb-bcce3aef4669.png)

MW

**Comment by mmbanong** [comment]
Planning-FRO-easement details notification lanuage already fixed

![image](https://user-images.githubusercontent.com/47392173/65712048-2db99800-e064-11e9-9492-3f6684d741fb.png)
