### ISSUE TITLE
Fire Alarm-"Fire License is Required"

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#821]
For my fire alarm permit, I am being stopped at the completeness check for a Fire License being required. Fire sprinkler licenses are only required for Fire Suppression permits. Fire alarm permits are applied for by an Electrician not a Fire Sprinkler License holder. I ended up adding a fire sprinkler contractor so i would be able to move forward with this permit.-AW
![image](https://user-images.githubusercontent.com/47611580/57094574-dc88c080-6cde-11e9-9e4c-abde7a594dee.png)
![image](https://user-images.githubusercontent.com/47611580/57094598-ee6a6380-6cde-11e9-9744-d588ce8a5b92.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. See test scenario AP # 240598.

**Comment by ABonomo21** [comment]
Permit# 240621 Doesn't hold up the Fire Permit from issuing because a Sprinkler Licensee is required, but under Required Licenses it still lists that it is a required license. The permit should be held up because it needs an Electrical License holder to apply. -MCoffman

![image](https://user-images.githubusercontent.com/47611580/57230478-6c33b500-6fe6-11e9-90fb-6d37567bca00.png)

**Comment by megisys** [comment]
Ready

**Comment by ABonomo21** [comment]
master electrician license required for alarm

**Comment by imazlout** [comment]
Ready for test. Now Fire Alarm requires contact with License Type 'ELEC' to be added

**Comment by ABonomo21** [comment]
corrected

![image](https://user-images.githubusercontent.com/47611580/59615215-25120700-90f0-11e9-806f-93225b545ef2.png)
