### ISSUE TITLE
Planning-NID-finalized before intake review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#823]
very strange.  Just did 2 NIDs just fine and this one acted like this.

![image](https://user-images.githubusercontent.com/4129185/57098454-24601580-6ce8-11e9-8cd1-fe10b37a6f7c.png)

MW

**Comment by dhenry-KCI** [comment]
![image](https://user-images.githubusercontent.com/4129185/57098530-52455a00-6ce8-11e9-8a5f-860cc96806e5.png)

**Comment by goggansd** [comment]
Created an exact duplicate (N239467), but could not replicate the issue.

The logic to mark the date as finalized is set to happen in the Issue Letter milestone and is simply core product functionality (as opposed to configured workflow formula code). But the way it is currently configured, the Issue Letter milestone should not be hit until AFTER Intake Review. From the logs and the timestamp of finalization on the original, however, the finalization happened somehow BEFORE the application even entered Intake Review, which indicates a major hiccup. Strangely, the logs also indicate that the application never actually entered Issue Letter.

@dhenry-KCI, did you encounter any sort of error message while creating or checking status on the original application?

**Comment by dhenry-KCI** [comment]
no error message received.

MW

**Comment by megisys** [comment]
Addressed this
