### ISSUE TITLE
Building - Capacity - Detail Page Missing 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#824]
The Capacity Comments and Rep Detail page needs to be added into IPS as it is in H&
![image](https://user-images.githubusercontent.com/47611580/57231679-fd0b9000-6fe8-11e9-9509-abf57812411d.png)

**Comment by goggansd** [comment]
This was already present,but no business rules had been configured to add it. Since it is not likely a page the R4C public user would fill out, I opted to add it on the Completeness Check milestone. Please retest and see if this works for you (in the IPSTest environment).

**Comment by ABonomo21** [comment]
Checked with Terry May 5.20.19 okay at completeness check
