### ISSUE TITLE
Building- Capacity - Additional Review 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#825]
An additional review to be added after fee payment and prior to issuance - "Administrative Review"

![image](https://user-images.githubusercontent.com/47611580/57231988-b23e4800-6fe9-11e9-9ddb-3ac6388776a5.png)

**Comment by goggansd** [comment]
Created Review Type ADMINREV - ADMINISTRATIVE REVIEW (department: DUSWMF), which automatically adds on all CAPACITY permits in the Pending Issuance milestone. Please retest in the IPSTest environment.

**Comment by JuanitaMiles** [comment]
The ADMINREV is not populating after fees are paid. The application just goes to closed. It does not populate in TEST or PREPROD.

![image](https://user-images.githubusercontent.com/31770504/59854690-5fbeae00-9341-11e9-8582-42cac85fe3a2.png)

**Comment by goggansd** [comment]
Configuration missing from IPSTest somehow. Reapplied configuration in IPSTest. Please retest in IPSTest.
