### ISSUE TITLE
Preplat-expire date copy from Detail Page to Expiry once set

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#828]
![image](https://user-images.githubusercontent.com/4129185/57233303-5f19c480-6fec-11e9-9c65-24510b92020a.png)

![image](https://user-images.githubusercontent.com/4129185/57233266-4e694e80-6fec-11e9-9b1c-9c473d0ed8f6.png)

MW

**Comment by calequin** [comment]
Need more info. Do we always set the expiration for Pre-Plat to be the same as the expiration listed in the detail page? or does it have additional logic?

**Comment by megisys** [comment]
Added Logic

**Comment by dhenry-KCI** [comment]
the logic works. but is there a better way?  I am concerned that staff will not remember to manually change the expiry date from the intial application expiry date to the  "approval" expiry date.

Two ideas:

1. we have two "expiry" fields: one in job description and one in application details.  Cant we rename the expiry field under job description to "Application expires"  and the one under the details to "approval expiry date" and have both on R4C?

2. Create a check alert condition at admin closure that says "Change expiry date to date approval expires"

MW

**Comment by dhenry-KCI** [comment]
@calequin - add a check condition at admin closure to "Change expiry date to date approval expires"

**Comment by calequin** [comment]
added CHEXP condition to PrePlat in the Admin Closure milestone. This needs to be approved before fulfilling the status check.

**Comment by dhenry-KCI** [comment]
looks good.

![image](https://user-images.githubusercontent.com/4129185/65903540-97021980-e38a-11e9-9b0f-896461c258cb.png)
MW
