### ISSUE TITLE
R4C-Preplat (and all Planning APs) expiration date field

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#829]
rename current expire date field to "Application expire date"
![image](https://user-images.githubusercontent.com/4129185/57235273-84103680-6ff0-11e9-82d2-ffacf6a8706a.png)

MW

**Comment by dhenry-KCI** [comment]
correction, not all AP types need the approval expiration date, only the following:
Pre-plat
-site
-pwcons
-APFO
-FRO

MW

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57240711-d18ea280-6ff4-11e9-9cff-f49706fd8fda.png)
 Rhythm allows for verbiage change only per module. All Planning Application types now have Application Expire Date.

**Comment by dhenry-KCI** [comment]
fixed-mw
