### ISSUE TITLE
Planning - YardMod - Review Results

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#83]
We would like to have an Approved, Resubmit and some sort of Denial feature, it is our understanding that Denied is not going to be available. Would we be able to have a Not Approved as a Review Code? 

AP - YD237203
Logged by K.Vanaman 2/19

![image](https://user-images.githubusercontent.com/4129185/53110546-30ba3c00-3509-11e9-93d2-61a27fd5b582.png)

**Comment by dhenry-KCI** [comment]
![yard mod - review results](https://user-images.githubusercontent.com/4129185/53760678-9c00f800-3e91-11e9-944f-73966ee55665.PNG)

Yard Modification - 3/4/19 YD237470  - KVanaman - Review Results should consist of Approved, Resubmit, and Denied (Denied should be restricted to certain users just like the rest of IPS, per M. Wilkins)

**Comment by megisys** [comment]
Resolved

**Comment by dhenry-KCI** [comment]
![yard mod review fox](https://user-images.githubusercontent.com/4129185/53835935-a805bc00-3f5c-11e9-83c2-4995c9059191.PNG)
Fixed - KVanaman - 3/5/19
