### ISSUE TITLE
R4C-Planning-details-approval expire date 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#830]
for all Planning APs, need to provide the project approval expiration date.  Dan suggested this be added to details page as a read only box that will populate once approval expire date is set in IPS back office.

MW

**Comment by calequin** [comment]
@megisys can you elaborate

**Comment by megisys** [comment]
I need more information too.. I have forgotten @dhenry-KCI

**Comment by dhenry-KCI** [comment]
Dan and I already worked this one out.  MW
