### ISSUE TITLE
R4C-BOA-applicant must be property owner

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#833]
entered applicant in R4C as Licensed contact.  County requires the property owner to be the applicant.  Doesnt appear to be a way to change the "role as an applicant" field or to add another contact after an application has been submitted.  Is there a way to add a note next to the "this field indicates your responsibility for this request" for BOA only that says "applicant must be property owner"????

![image](https://user-images.githubusercontent.com/4129185/57244454-62ba4500-7006-11e9-8df1-66112489f315.png)

MW

**Comment by calequin** [comment]
Discussion needed with @megisys for possible workarounds

**Comment by megisys** [comment]
It is under Change Applicants

**Comment by dhenry-KCI** [comment]
@dhenry-KCI - County to confirm ability in R4C

**Comment by dhenry-KCI** [comment]
this issue was resolved last week with Dan by removing the "applicant must be property owner" requirement from IPS.  Staff to verify this upon completeness check and require affidavit from property owner if applicant is not the owner.

MW
