### ISSUE TITLE
R4C-BOA-variance-occ type drop box

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#835]
nothing to select.

![image](https://user-images.githubusercontent.com/4129185/57248026-57b7e280-700f-11e9-9614-a6aa1de530e1.png)

mw

**Comment by dhenry-KCI** [comment]
started working.  will monitor

**Comment by megisys** [comment]
PIck Worktype First

**Comment by dhenry-KCI** [comment]
5/13: as you can see in the screen shot I did choose work type first.  But is is working today. MW
