### ISSUE TITLE
Building- Capacity- Non Residential Auto Generate

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#836]
Non-Res Building permit applications are not auto generating the capacity permits as outlined on the white board.

**Comment by JuanitaMiles** [comment]
Capacity permit spawned on a nonres when the water/sewer type has been populated with PUBLIC/PUBLIC. There is a concern that if the Water/Sewer Type is not filled out, the Capacity will not spawn and how will DUSWM know that a Capacity should have spawned?
