### ISSUE TITLE
R4C-Planning-BOA-BOCC or Planning Commission appeal

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#837]
R4C needs to change BOCC to County Council

![image](https://user-images.githubusercontent.com/4129185/57250164-c5b2d880-7014-11e9-9d2c-dc4aabef9824.png)

MW

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57251929-a44fed80-7010-11e9-9d98-cb2947209bad.png)

Changed the portal description. back office stays the same

**Comment by dhenry-KCI** [comment]
fixed-mw
