### ISSUE TITLE
R4C- Sign Permit - Grid Details

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#838]
In the sign detail grid for Retaining Wall  and Freestanding Ht. Can you please specify the height value should be feet (ft.)

![image](https://user-images.githubusercontent.com/47611580/57305370-f47d8d00-70ae-11e9-80d4-ea09c434d469.png)

**Comment by ABonomo21** [comment]
Should still specify that we are looking for height. 
Example: "Retaining Wall Height (ft)"

![image](https://user-images.githubusercontent.com/47611580/57710130-4dfb3400-763a-11e9-905f-9dc2bf437109.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/57742398-fdfa8c80-768e-11e9-9d3e-6cd29f68c2e1.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/57786354-4e123700-7701-11e9-8d37-748efe8e18d8.png)
