### ISSUE TITLE
R4C - Sign Permit- Sign Details 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#839]
Where it reads Total Freestanding and Total All Except Freestanding 
can you make it read Total # of freestanding signs and Total # of all signs except freestanding

![image](https://user-images.githubusercontent.com/47611580/57305553-46beae00-70af-11e9-97e2-fc6f49390bd6.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/57709173-974a8400-7638-11e9-924e-b4dd5cbf3a9a.png)

**Comment by ABonomo21** [comment]
Should be capitalized to match the rest of the details page-MCoffman

![image](https://user-images.githubusercontent.com/47611580/57709819-b3025a00-7639-11e9-8070-949687a2a546.png)

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57742263-790f7300-768e-11e9-9871-643a80105806.png)
fixed and made it more clear for citizen to understand

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/57786236-2327e300-7701-11e9-8ce6-190786167c8f.png)
