### ISSUE TITLE
R4C- Sign Permit- Add grid details 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#840]
Is there a way to put direction in by the add row that each sign must have a separate row added? 

For example if the applicant is submitting for 4 signs there should be 4 rows added? 

![image](https://user-images.githubusercontent.com/47611580/57305861-b5037080-70af-11e9-8507-775b6b0615cd.png)

**Comment by calequin** [comment]
@ABonomo21 im going to tag this as enhacenment July since grids will be changed in that update.

**Comment by calequin** [comment]
Grids changed in the May update. Can you test a grid and see if this is still needed?

**Comment by ABonomo21** [comment]
I do think we still need some sort of direction to say something like  "Please add details for each different sign on this permit" 
![image](https://user-images.githubusercontent.com/47611580/57858018-46649800-77be-11e9-9f53-ae9c2b23c19b.png)

**Comment by calequin** [comment]
Unfortunately the site does not allow you to change the verbiage on the add row grid. We would have to add a lable on each detail page that contains a grid in order for it to be displayed properly.

**Comment by ABonomo21** [comment]
Add the following details into the grid- and remove from the general detail page 

- Sign type (with drop down including directional, permanent or reface only)
- Wording on sign (with a free form text box)

Then add instructions on the details page that say " For each sign please add the required details into the grid below. "

**Comment by megisys** [comment]
Add to Grid Header fields read only and show in Portal false. for Historic Data Only

**Comment by ABonomo21** [comment]
Partially fixed-MCoffman
Sign type with drop down box-correct

Should say "Wording on Sign"
![image](https://user-images.githubusercontent.com/47611580/59037475-53b1f700-883f-11e9-9bbc-e8f61a34f208.png)

Should say "Please add a row for each Sign" (fix capitalization) and should be above the grid
![image](https://user-images.githubusercontent.com/47611580/59037619-9ecc0a00-883f-11e9-900c-9cbf4d36c506.png)

**Comment by calequin** [comment]
fixed in test

**Comment by ABonomo21** [comment]
@calequin 
 Formatting fixed in test, except red star, which I think is misplaced-MCoffman

![image](https://user-images.githubusercontent.com/47611580/59043324-05eebc00-884a-11e9-97fb-020486885a1a.png)

**Comment by calequin** [comment]
fixed in test

**Comment by ABonomo21** [comment]
Permit# 245699-Fixed in R4C-MCoffman
![image](https://user-images.githubusercontent.com/47611580/59200252-d0a5df00-8b65-11e9-87f4-561e13b89078.png)
