### ISSUE TITLE
Case - Health- Remove Case Group

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#842]
Please remove or expire the case group HLITTER 
![image](https://user-images.githubusercontent.com/47611580/57325307-c1032880-70d7-11e9-8e36-2f5f0c1462be.png)

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Pease retest.

**Comment by ABonomo21** [comment]
corrected
