### ISSUE TITLE
Case- Health- Detail Page

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#843]
The Health Case Detail Page is not populating.

![image](https://user-images.githubusercontent.com/47611580/57325351-d710e900-70d7-11e9-9d55-6dece2d5b6ae.png)

**Comment by megisys** [comment]
What should this look like please ? @ABonomo21

**Comment by megisys** [comment]
Not sure what this means

**Comment by ABonomo21** [comment]
no need for detail page - same as 7 only confidential details
