### ISSUE TITLE
R4C - Autocreate Account for Applicants without Account (Excel Issue #56)

### ISSUE THREAD

**Issue by megisys** [kcigeospatial/Fred_Co_Land-Management#844]
Need to do this and work through the process

**Comment by calequin** [comment]
Invitation model is suggested to be handle instead of auto creation. An invitation email can be sent out to the county past clients with information on how to sign up etc. Discussion needed with county staff.

**Comment by megisys** [comment]
No.... This is for people who submit application in person.. We want to autocreate a login to portal . so they can pay when their permit progresses

**Comment by megisys** [comment]
Dim Res As Result

Dim oPortalAccount As Hansen.Portal.IMembership = ServerApplication.NewComponent(Of Hansen.Portal.IMembership)()

oPortalAccount.Contact.ContactKey = 2490

oPortalAccount.UserName = "Fred@gmail.com"

oPortalAccount.PasswordQuestion.Code = "DAYREG"
oPortalAccount.ActivatedDate = Serverapplication.GetDateToday()
oPortalAccount.ApprovedDate = Serverapplication.GetDateToday()
oPortalAccount.IsPasswordResetRequired = True
oPortalAccount.IsActivated = True
oPortalAccount.IsApproved = True

Res = oPortalAccount.SetPassword("Today")
Res = oPortalAccount.SetPasswordAnswer("Today")
	
Res = oPortalAccount.Add()

if Res.IsSuccess Then
	
	Dim oPortalMembership As Hansen.Portal.IMembershipsinRoles = ServerApplication.NewComponent(Of Hansen.Portal.IMembershipsinRoles)()
	
	oPortalMembership.Membership.MembershipKey = oPortalAccount.MembershipKey
	oPortalMembership.Role.RoleKey = 1002
	
	Res = oPortalMembership.Add()


End if

**Comment by megisys** [comment]
Added to Building.. If you add a Portal Log Type to building will autocreate Accounts for Applicants without accounts. Need to list existing accounts so I can then send Notification.

**Comment by megisys** [comment]
After Adding a Building Application. You will see a PORTAL Log if Users were Created
