### ISSUE TITLE
R4C - Autocreate Account for Applicants without Account

### ISSUE THREAD

**Issue by megisys** [kcigeospatial/Fred_Co_Land-Management#845]
Need to do this and work through the process

**Comment by goggansd** [comment]
@megisys, tried to make this work like Dynamic Portal, but R4C portal accounts are very different, so there's a learning curve as to how to even set this up--stopped moving forward today due to time constraints, and will attempt to address simpler issues.

**Comment by megisys** [comment]
We need to give this another shot
