### ISSUE TITLE
Planning-all-denied result

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#849]
selected denied, which should kill a project, but it stage progressed to hearing.

![image](https://user-images.githubusercontent.com/4129185/57465842-6d1a5000-724d-11e9-8fc2-060dcf50f178.png)

MW

**Comment by goggansd** [comment]
Addressed in IPSTest environment. Please retest.

**Comment by dhenry-KCI** [comment]
tested BOA and addition plat.  denied feature worked as expected.

MW
