### ISSUE TITLE
Planning - Verify - Review Resubmit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#85]
Verification Review requested a resubmit however the application went to directly to Finalized 

AP - 237213
Logged by K.Vanaman 2/19

![image](https://user-images.githubusercontent.com/4129185/53111962-2d747f80-350c-11e9-9b4f-b39b8de3841f.png)

**Comment by megisys** [comment]
We dont Resubmit Verification Letters.. They Pay The Fees and they get a letter.. It is not a true planning application. I was told we dont go back and forth.. Please discuss with Mike.

**Comment by dhenry-KCI** [comment]
@megisys confirmed with Mike and Ashley we do need resubmit. Reviewer and applicant will go abck and forth on submittal requirements.

**Comment by megisys** [comment]
@dhenry-KCI THis has been addressed

**Comment by dhenry-KCI** [comment]
![verify resubmit](https://user-images.githubusercontent.com/4129185/53757840-b2f01c00-3e8a-11e9-8804-919916734857.PNG)
Issue Resolved - KVanaman - 3/4/19 A/P # VP237459
