### ISSUE TITLE
Fire Details Page Needs CIP/Municipality Check Box

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#850]
The fire details page needs the cip/municipality check boxes-AW
![image](https://user-images.githubusercontent.com/47611580/57466351-735cfc00-724e-11e9-95e3-9f4984f69322.png)

**Comment by megisys** [comment]
Added to the Detail Page..

**Comment by ABonomo21** [comment]
corrected
