### ISSUE TITLE
Building Permit- Demolition - Denial Review

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#851]
Denial of a review was resulted by a supervisor.  Should have gone to an admin closer. Instead it remained under remove and generated a revision fee.

![image](https://user-images.githubusercontent.com/47611580/57466393-8b348000-724e-11e9-9ba2-c65d2a0a5b99.png)

![image](https://user-images.githubusercontent.com/47611580/57466123-00ec1c00-724e-11e9-8d9e-a31342e3bbe3.png)

**Comment by goggansd** [comment]
Admin Closure milestone was expired on 3/15/2019 for the DEMOLITION permit type. Please advise.

**Comment by megisys** [comment]
DENIALHOLD is the process. We need to talk through what we are expecting here @ABonomo21 @dhenry-KCI

**Comment by megisys** [comment]
Dan to configure system to go to Complete Milestone with Status of DENIED.

**Comment by ABonomo21** [comment]
Make say Closed-DENIED

**Comment by megisys** [comment]
This was coded

**Comment by ABonomo21** [comment]
denial hold generated then the system asked for a stop date on the denial  entered stop date to see if it would change the milestone and it did not. 

![image](https://user-images.githubusercontent.com/47611580/59441029-ea456180-8dc5-11e9-8dc7-f258de195824.png)

**Comment by megisys** [comment]
Ready in TEST

**Comment by megisys** [comment]
Anyone can add a DENIALHOLD.. But only some one with Access can add a stop date. Which will then complete the denied process. moving the application to Closed - Denied.

**Comment by ABonomo21** [comment]
good job Dan
