### ISSUE TITLE
Building - Budget Number 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#854]
The budget string for permit 240592 for Site Plan Compliance is peoplesoft numbers not infor.

![image](https://user-images.githubusercontent.com/47611580/57468989-9342ee80-7253-11e9-95b3-93bf886fb0ef.png)

**Comment by goggansd** [comment]
What is the correct budget number for this fee? I understand that its format is not like the others, but need to know exactly what it should be in order to fix it.

**Comment by ABonomo21** [comment]
The infor account string is: 10.98.998.999.42427.0000

thank you,
EP 5/14/19

**Comment by megisys** [comment]
Need to Check Jeff Wisner Cross walk and assign to Martin

**Comment by mmbanong** [comment]
Assigned to Jeff Wisner

**Comment by pooldaddy** [comment]
This PS # was in the xwalk provided to INFOR. Must have been a data migration issue.

**Comment by pooldaddy** [comment]
See excel attached.  Row 133
[dbo.H7TOINFORXWALK.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/3306796/dbo.H7TOINFORXWALK.xlsx)

**Comment by pooldaddy** [comment]
Assigning back to KCI

**Comment by dhenry-KCI** [comment]
@megisys - the correct string was provided in the crosswalk. Row #133


10000041416000000 | 10000041416000000 | 10_0000_41416_000000 | 10.98.998.999 42427 0000
-- | -- | -- | --

**Comment by dhenry-KCI** [comment]
@mmbanong is this a field you ca update?

**Comment by megisys** [comment]
Under each Module. There is a Fee Library OPtion. PLease find the above fee and update the budget number. It is pretty easy to navigate.

**Comment by mmbanong** [comment]
![image](https://user-images.githubusercontent.com/47392173/62793215-05b7aa80-ba9f-11e9-80ef-a9396b7cd8cb.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/64374311-8eb7f800-cff1-11e9-8c99-740a314cc847.png)
fixed 9.5.19 ab
