### ISSUE TITLE
R4C- Res Uses- Section Complete

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#855]
The section complete section is at the beginning of the Res Uses details, this should be at the bottom of this section as the last part the applicant completes.-AW
![image](https://user-images.githubusercontent.com/47611580/57472099-a60cf180-725a-11e9-8000-38999488d112.png)

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/57721242-b6094480-7651-11e9-9196-f80d1a5066ad.png)
