### ISSUE TITLE
R4C-ResUse-Drive Way Apron Check box

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#857]
The "How Many?" should say "How many new Drive Way Aprons" I do not think the applicants would know what it is in relation to with it being so far away from the “New Driveway Apron” check box.-AW
![image](https://user-images.githubusercontent.com/47611580/57472608-dc973c00-725b-11e9-8f52-490bed0cb382.png)

**Comment by calequin** [comment]
Added labels on top of the sections
![image](https://user-images.githubusercontent.com/47603568/57542316-e92c9a80-7316-11e9-8f39-a93ba8c5a97a.png)
![image](https://user-images.githubusercontent.com/47603568/57542327-f6e22000-7316-11e9-9c23-38643505efba.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/57705009-0623df00-7631-11e9-8011-350d68a3b8ba.png)
![image](https://user-images.githubusercontent.com/47611580/57705037-163bbe80-7631-11e9-899d-0e4bc1bfb03a.png)
