### ISSUE TITLE
R4C-BOA-changing primary applicant

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#859]
BOA applications must be filed by the property owner.  created an application in R4C as the Licensed Contact instead of property owner.  IPS caught this (well done IPS!) and does not allow me to move past completeness check. I resulted completeness check as "resub" and R4C reflected this.  However, I am unable to change the primary applicant in R4C.  I add property owner as additional applicant in R4C but this obviously didnt remove the check alert condition.

need to find a solution to allow the Primary Applicant to be changed without the applicant having to start a new application.

![image](https://user-images.githubusercontent.com/4129185/57476081-da38e000-7263-11e9-9c59-28ad9c3cc141.png)

![image](https://user-images.githubusercontent.com/4129185/57476128-ec1a8300-7263-11e9-9ef7-89bf45ffdf97.png)

MW

**Comment by ABonomo21** [comment]
after thinking about this I think the best solution is to change IPS.  Instead of requiring the applicant to be property owner and primary applicant, can it be changed to require that either the the primary applicant or additional applicant = property owner?

MW

**Comment by megisys** [comment]
No.. Cause back office auto loads the property owner onto the application and we are going to do this for application from R4C. So it has to be that they are the primary applicant. Also the user can not change themselves as a primary applicant as they are logged into rhtyhm which makes them the primary applicant. 

Application is either rejected on completeness or you do a change applicant action is you think appropraite

**Comment by dhenry-KCI** [comment]
can we add a note next to "role as applicant" on the BOA application only stating "must be owner"?

![image](https://user-images.githubusercontent.com/4129185/58031399-56e27e80-7aee-11e9-9401-c5d86c686409.png)

**Comment by calequin** [comment]
Changing the label on the "What is your role as an applicant" would change it for all planning applications. Therefore it is not possible to change it only on BOA.  My suggestion would be to add this verbiage to the SOP on the top of the page.

**Comment by dhenry-KCI** [comment]
can we change IPS to remove the stipulation that the property owner must be the applicant?  Then we can follow up on the property owner question through the completeness check .

MW

**Comment by megisys** [comment]
Moved this off. Add the check for Owner on the SOP on Intake Review

**Comment by dhenry-KCI** [comment]
fixed.  see ap 244644...used lic. contact as applicant and was able to process

MW
