### ISSUE TITLE
Planning - Verify - Conditions

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#86]
Application Finalized without Letter Condition being approved

AP - 237213
Logged by K.Vanaman 2/19

![image](https://user-images.githubusercontent.com/4129185/53112119-89d79f00-350c-11e9-978f-049bb74bd7a9.png)

**Comment by megisys** [comment]
Changed the Status CHeck

**Comment by dhenry-KCI** [comment]
![verification conditions](https://user-images.githubusercontent.com/4129185/53757257-37419f80-3e89-11e9-9f3d-9c3967a80e8e.PNG)
Planning - Verification Letters - 3/4/19 A/P #VP237456 - Issue still exists - Application was finalized without the  Letter Condition being approved

**Comment by megisys** [comment]
Fixed.. Sorry

**Comment by dhenry-KCI** [comment]
![verification letter fix](https://user-images.githubusercontent.com/4129185/53836041-f74bec80-3f5c-11e9-89ec-92152d96a34a.PNG)
Fixed - KVanaman- 3/5/19
