### ISSUE TITLE
R4C-Res Use-Garage Info Boxes

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#860]
The “Finished Room Above Garage” check box should be down with the Garage Info along with “Unfinished Room Above Garage” 
There are two “# of Cars” for the Garage info, where there should only be one.-AW

![image](https://user-images.githubusercontent.com/47611580/57530577-8da5e100-7305-11e9-9696-f796e37215a8.png)

**Comment by calequin** [comment]
same concept as the rest. the rendering would not work right if rearranged. We should discuss the possibility of changing the verbiage to make more sense to an applicant.
![image](https://user-images.githubusercontent.com/47603568/57555624-6f0e0d00-733a-11e9-8f97-da4bd0b08960.png)

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57556193-f445f180-733b-11e9-888c-156ca5fb3df5.png)

**Comment by ABonomo21** [comment]
I like the idea of changing the title to say "Carport # of Cars" and "Garage # of Cars". I think that will help solve the confusion of the customers.-aw
![image](https://user-images.githubusercontent.com/47611580/57720455-e5b74d00-764f-11e9-8fcf-ef966311c964.png)

**Comment by megisys** [comment]
Add better labels

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/59122358-913e7f00-8928-11e9-8053-fe44ba39dde8.png)
