### ISSUE TITLE
R4C-Res Use-Bedroom/Bath Info & Section Complete

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#861]
The Bedroom & Bathroom info of "# Bedrooms", "#Baths", &  “Full, Half, and R-In” should read "# of Bedrooms, # of Baths, # of Full Baths, # of Half Baths, and “# of Bath Rough-ins” I do not think the applicant would understand this info without a descriptive title. -aw

The “Section Complete” is in the middle of the application. It should be at the bottom so the applicant can check it off, once they have entered all their info.
![image](https://user-images.githubusercontent.com/47611580/57530853-2a687e80-7306-11e9-9100-72bb7caa9484.png)

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57556157-db3d4080-733b-11e9-9b9e-acbc04a9145a.png)

**Comment by ABonomo21** [comment]
I do not see the title changes-aw
![image](https://user-images.githubusercontent.com/47611580/57720296-8eb17800-764f-11e9-8fdd-15f697244adb.png)

**Comment by calequin** [comment]
detail page was reverted back. I fixed it with the correct verbiage
![image](https://user-images.githubusercontent.com/47603568/57741699-0d2c0b00-768c-11e9-90ff-feed62b2abac.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/57802800-c4746080-7724-11e9-9bc3-5a72d40697ea.png)
