### ISSUE TITLE
R4C-Res Use-Basement Info

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#862]
“Egress Type” should be changed to “Basement Egress Type” so the applicant can understand the information we are looking for. 
The basement types, should also have a title of “Basement Type” so the applicant knows to pick the correct one.
 
![image](https://user-images.githubusercontent.com/47611580/57530984-74e9fb00-7306-11e9-86c0-c20cf0038a6d.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/57641932-d36bdf00-757b-11e9-8863-3b22c6ae11a7.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/57704406-d1fbee80-762f-11e9-914c-acd45461317d.png)
