### ISSUE TITLE
R4C-Res Use-Septic Info

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#863]
The Septic Information should have some info for the applicant to know to check New or Existing and then to check what type of septic Conventional or Sand Mound.-aw

![image](https://user-images.githubusercontent.com/47611580/57531122-c1cdd180-7306-11e9-86a2-eb0ca7718959.png)

**Comment by calequin** [comment]
Can you provide the verbiage? I can add this as a label in the back office detail page which can be added to the R4C page.

**Comment by ABonomo21** [comment]
Maybe we could add "If applicable, please select "New Septic" or "Connecting to Existing Septic" Then select the correct Septic Type below." ??? My concern is that a customer will think they need to check what type of septic system they have even if their permit has nothing to do with it. this might be something we will check during the completeness checks. need to check with Ashlye to be sure of how to proceed-AW

**Comment by ABonomo21** [comment]
In Process- Working with Ashlye & Christian to figure out correct verbiage-AW
![image](https://user-images.githubusercontent.com/47611580/57930761-c6553580-7884-11e9-8ff1-509a3ac27df1.png)

**Comment by ABonomo21** [comment]
after speaking with Ashlye & Dan, this is how the septic info details should be for a res use.-aw
![image](https://user-images.githubusercontent.com/47611580/58809711-6aabdb80-85ea-11e9-9564-918b7b202a8d.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/59532821-64054a00-8eaf-11e9-9198-f21b5696b2c4.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/59615104-f8f68600-90ef-11e9-9e3b-becb66342763.png)
