### ISSUE TITLE
R4C-Demolition Square Footage

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#864]
Square footage is not a required field for a demolition permit-MCoffman

![image](https://user-images.githubusercontent.com/47611580/57531303-1cffc400-7307-11e9-8ae8-e4825f8cbdbf.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/57637936-48d2b200-7572-11e9-81c6-f9e7ea107849.png)

**Comment by ABonomo21** [comment]
Issue Corrected-MCoffman

![image](https://user-images.githubusercontent.com/47611580/57704409-d32d1b80-762f-11e9-8de6-47c270a8a20b.png)
