### ISSUE TITLE
r4c - all modules - information button 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#865]
Can the "I" button be modified to be specific to the field we are in? Like Square Footage and we can explain what the square footage is?

logged by tiffany martin 5/10/19

**Comment by calequin** [comment]
yes this is the tool tip function. Send me the information you would like to see and we can input that information. Keep in mind that the tool tip function is per module and not per AP type.

**Comment by dhenry-KCI** [comment]
on grading intake detail pages add what was emailed.   tm 5/14/19

**Comment by calequin** [comment]
part of 19.7 release

**Comment by dhenry-KCI** [comment]
DH - Must have per County

**Comment by calequin** [comment]
Needs 1906 backoffice patch

**Comment by calequin** [comment]
tool tips are now available for detail pages. Would need to know which detail pages need tool tips and what information.
![image](https://user-images.githubusercontent.com/47603568/61757799-b62b6c00-ad87-11e9-9d0a-0dc42e1a45a8.png)

**Comment by dhenry-KCI** [comment]
Will work with Christian to determine "how" to update these tool tips. Will allow County to update during training.

**Comment by ABonomo21** [comment]
why is this a question @dhenry-KCI
