### ISSUE TITLE
R4C-Addresses Duplicates

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#867]
Not sure if this an issue that needs to be fixed or not but I wanted to log it just in case. When I searched this address, a second address with an apartment number showed up as well. This property does not have an apartment.-AW

![image](https://user-images.githubusercontent.com/47611580/57533051-d2804680-730a-11e9-8a88-1c753a671c5c.png)
![image](https://user-images.githubusercontent.com/47611580/57533109-f0e64200-730a-11e9-86ad-ac8052aa1c64.png)

**Comment by calequin** [comment]
tagged this as data issue. this is coming across from legacy data

**Comment by megisys** [comment]
Need to ensure addresses are clean and expired

**Comment by mmbanong** [comment]
Assigned to Jeff Wisner

**Comment by pooldaddy** [comment]
Only 1 address exists in H7, the one w/o an apartment #.  Was this address added in IPS11?

**Comment by dhenry-KCI** [comment]
Closed. No longer an issue with new migration.
