### ISSUE TITLE
r4c - driveway - details pages

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#869]
We configured IPS information that should be input prior to completeness check for a reason. That information needs to be input into R4C. Without that information, every driveway permit in IPS will get the result code of RESUBMIT. The way the system works prior to completeness check in IPS should follow suit in R4C.

tiffany martin 5/10/19

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/57637740-c5b15c00-7571-11e9-8b6f-ebeea6fa6519.png)

**Comment by dhenry-KCI** [comment]
related to #815

**Comment by dhenry-KCI** [comment]
this still has not been corrected 5/14/19 tm

the building permit was input under R4C but did not carry over to IPS - this is also with planning

AP #240698

**Comment by ABonomo21** [comment]
In addition the driveway entrance apron details should be a required field. 

If a common entrance or primary non-res - a planning/ plat no # is required. 

Permit #240698

**Comment by calequin** [comment]
@megisys will add the dropdown fields

**Comment by ABonomo21** [comment]
This also needs to be added into R4C
![image](https://user-images.githubusercontent.com/47611580/59112152-6f390280-8910-11e9-9982-f14bb2569978.png)

The related building permit in R4C didn't carry over to IPs 
![image](https://user-images.githubusercontent.com/47611580/59112327-cccd4f00-8910-11e9-9fc8-5cf56296238f.png)
![image](https://user-images.githubusercontent.com/47611580/59112367-e2427900-8910-11e9-8d10-5dc4c4e165c9.png)

6/7/19 EP

**Comment by megisys** [comment]
You need to relate it during intake. As it needs to be checked it is appropriate. No auto allocation

**Comment by ABonomo21** [comment]
@calequin apron type needs to be a required field if common entrance or primary nonres is selected then plat # should be a required field

missing apron type equal to entrance is onto a dirt of gravel public road from drop down

**Comment by megisys** [comment]
RESBLDG drives creation of Driveway permits. No the other way around.. Please talk with Ashlye. This is a confusion

**Comment by dhenry-KCI** [comment]
@megisys, @calequin Confirmed with Ashlye B. applicant still has ability to due standalone driveway permit. Need the following added:

apron type needs to be a required field if common entrance or primary nonres is selected then plat # should be a required field

missing apron type equal to entrance is onto a dirt of gravel public road from drop down

**Comment by calequin** [comment]
added new dropdown for dirt or gravel road. 
- cant make apron type required since dynamic functionality is not available on detail pages.

**Comment by JuanitaMiles** [comment]
Make the check box for "Is a dirt road?" visible on the detail page in R4C.

![image](https://user-images.githubusercontent.com/31770504/67211367-9b997b00-f3e8-11e9-8809-b0566220ae5c.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/67314553-daa3fb00-f4d2-11e9-8cc0-439e6297125a.png)
