### ISSUE TITLE
Building - ZoneCert - Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#87]
Zoning Review did not populate

AP - 237139
Logged by K.Vanaman 2/11

![image](https://user-images.githubusercontent.com/4129185/53113046-a248b900-350e-11e9-9def-73bc6e8c03fc.png)

**Comment by imazlout** [comment]
This item has already been addressed as part of Issue #58

**Comment by dhenry-KCI** [comment]
Closed as per #58
