### ISSUE TITLE
building - all modules 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#875]
the parcel information populated at the very top of the application, however, under the sites tab no address or parcel information populated. and if an address was entered under r4c then the opposite occurs.

AP #240654
AP #240656

tiffany martin 5/10/19

**Comment by goggansd** [comment]
This has been addressed in the IPSTest environment. Please see AP # 240654.

**Comment by ABonomo21** [comment]
retest failed. 

5/14/19 ep
