### ISSUE TITLE
r4c - reschedule request - inspection (Excel Issue #55)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#876]
when you select reschedule for an inspection, there is not an option to cancel the request.

**Comment by calequin** [comment]
Once you request to schedule the inspection the applicant cant cancel but they can reschedule if needed.

**Comment by ABonomo21** [comment]
Would like to discuss. There should be a way for the applicant to cancel the inspection. 

EP 5/14/19

**Comment by dhenry-KCI** [comment]
1. add a status check verbiage- 
2. work backoffice functionality to trigger a log.
3. action would then occur on a my infor dashboard

**Comment by calequin** [comment]
-added verbiage to portal status check
- added a log that triggers after someone requests cancellation. this clears out the date. If the date = today then a text message notification is sent to the inspector.
- if someone requests a new date then both dates clears out.

**Comment by ABonomo21** [comment]
testing with Christian, Retest failed-AW
![image](https://user-images.githubusercontent.com/47611580/60208127-8be89c00-9825-11e9-8534-bf0de8fdae65.png)
