### ISSUE TITLE
building - major logging permit - test email

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#879]
i got a test email that stated my permit was ready for payment and bond. Logging permits do not get a bond. Language needs to be corrected.

Tiffany martin 5/10/19

Ap #240664

**Comment by megisys** [comment]
Fixed in PreProd

**Comment by ABonomo21** [comment]
Unable to test, notifications are currently turned off.

6/7/19 EP
