### ISSUE TITLE
Building - ZoneCert - Review

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#88]
When trying to add a Zoning Review, Zoning Review was not available as an option.

AP - 237139
Logged by K.Vanaman 2/11

![image](https://user-images.githubusercontent.com/4129185/53113115-ca381c80-350e-11e9-8e4a-b6fb88a86e6f.png)

**Comment by imazlout** [comment]
This issue has already been addressed as part of Issue #58

**Comment by dhenry-KCI** [comment]
Closed as per #58
