### ISSUE TITLE
r4c - major grading - mitigation

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#880]
the mitigation items under the grading details page should auto populate the cost and total based on the quantity given from the applicant. 

AP #240666

mitigation cost, quantity and total did not populate once the application was saved. This should be viewable by the applicant. Once we went back to the grading checklist after saving, then the mitigation information populated but the mitigation items did not. 

![image](https://user-images.githubusercontent.com/4129185/57546328-8ba24900-732a-11e9-9620-d6dd15888343.png)
 
logged by tiffany martin 5/10/19

**Comment by calequin** [comment]
I will monitor this upon the july enhacement which will remove detail page grids with another form.

**Comment by ABonomo21** [comment]
the cost and total is not a column in the mitigation items. you can see from the original screen shot that it was there. I think it should remain. 

![image](https://user-images.githubusercontent.com/47611580/58805219-a8583680-85e1-11e9-9b54-b2e344674400.png)

i added two line items in mitigation, however, nothing populated once I clicked save and continue. once i submitted the information still did not populate. see below pic 2

1    ![image](https://user-images.githubusercontent.com/47611580/58805314-d473b780-85e1-11e9-9fb8-2c49908b5d46.png)

2    ![image](https://user-images.githubusercontent.com/47611580/58805435-113fae80-85e2-11e9-98d6-f72951ba173f.png)

tiffany martin 6/3/19

**Comment by calequin** [comment]
duplicate of #902

**Comment by dhenry-KCI** [comment]
confirmed duplicate
