### ISSUE TITLE
r4c - grading - date plans signed 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#882]
the date plans signed by NRCS and SCD does not need a time to be associated with it. as long as we have the date, this is sufficient.

tiffany martin 5/10/19

**Comment by calequin** [comment]
fixed for only date
![image](https://user-images.githubusercontent.com/47603568/57635164-41a8a580-756c-11e9-8f86-10648e6bf45d.png)

**Comment by ABonomo21** [comment]
this is fixed. thank you. 

ep 5/14/19
