### ISSUE TITLE
R4C-All Permits-Property owners 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#883]
When inputting  an address on to a permit application, the property owners are not generating to show as additional applicants. is this something can be fixed? #240673 -aw
![image](https://user-images.githubusercontent.com/47611580/57550503-9c57bc80-7334-11e9-82ce-b256848ec4ed.png)

![image](https://user-images.githubusercontent.com/47611580/57550538-bbeee500-7334-11e9-8962-619e527f4705.png)

**Comment by ABonomo21** [comment]
We should add the property owners to the application at completeness check - part of the completeness check review is to confirm the parcel details have the most current property owner - if the applicant from R4C stated they were the property owner and it does not match SDAT - we need to reject it for a Deed. If SDAT is accurate., and the parcel is not current we need to update the contact record on the parcel like we do not in 7 and then relate the property owners to the permit  -

If we need to update the SOP's to make this more clear for staff let me know.

**Comment by ABonomo21** [comment]
This process of us checking the property owners during completeness check is fine but until the issued with the Instructions for Applicant Actions Resubmit is fixed we are unable to confirm this process -AW

see issue #1031

**Comment by megisys** [comment]
You are to add the property owner manually to check the person is the property owner

**Comment by dhenry-KCI** [comment]
This issue is closed. Will test #1031 when available.
