### ISSUE TITLE
Planning-APFO-resubmit allowed project to go to complete

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#884]
Resulted review with resub but it went to complete milestone.

![image](https://user-images.githubusercontent.com/4129185/57632519-d1038800-756f-11e9-9d22-07b3bd7b6486.png)

MW

**Comment by megisys** [comment]
Ensure Detail Pages detail are Valid

**Comment by dhenry-KCI** [comment]
fixed per A244575 in test Enviro


![image](https://user-images.githubusercontent.com/4129185/59047152-53baf280-8851-11e9-9d54-180341a9053c.png)

MW
