### ISSUE TITLE
R4C-APFO-details-Exemption fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#885]
Not sure we need this box on R4C.  I am pretty sure clicking this box is what generates the review fee.  Dan, can you verify?  If it does generate a fee is should be removed from R4C and checked by staff in the back office during completeness check. 

MW

![image](https://user-images.githubusercontent.com/4129185/57633022-d2818000-7570-11e9-8e33-07eeddcf46bd.png)

**Comment by calequin** [comment]
Correct this field is the add on condition for the fee. I have removed it from show in r4c.

**Comment by dhenry-KCI** [comment]
fixed-mw
