### ISSUE TITLE
Planning-rezone-details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#887]
why cant i edit the parcel details?

![image](https://user-images.githubusercontent.com/4129185/57633802-1aed6d80-7572-11e9-9c9c-fac73b429161.png)

MW

**Comment by dhenry-KCI** [comment]
meant project details, not parcel details

**Comment by calequin** [comment]
fixed. water and sewer are not editable and come from the parcel information
![image](https://user-images.githubusercontent.com/47603568/57725421-0f29a600-765b-11e9-99cd-6a179025a35c.png)

**Comment by dhenry-KCI** [comment]
filled in w/s class in parcel info but field didnt populate on details.

![image](https://user-images.githubusercontent.com/4129185/57781089-7a28ba80-76f7-11e9-851c-f3a3ab8edd5b.png)

![image](https://user-images.githubusercontent.com/4129185/57781116-8ca2f400-76f7-11e9-88ce-41e72f78bf05.png)


mw

**Comment by megisys** [comment]
Hang on we are way off path here..  We need to use either the details from the parcel or the details entered on the detail page.  The detail page will not duplicate data which exists somewhere else. I added them to the header as per building

**Comment by megisys** [comment]
Added on Planning Header

**Comment by dhenry-KCI** [comment]
looks good-mw

![image](https://user-images.githubusercontent.com/4129185/59856885-bfb75380-9345-11e9-8d28-881428cc4e6e.png)

![image](https://user-images.githubusercontent.com/4129185/59856833-aca48380-9345-11e9-9b45-914fb0ca706b.png)
