### ISSUE TITLE
R4C-Demolition Details: Construction Type

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#888]
For Demolition Permits in the Demolition Details Section; there should not be an option for "Interior Only" under "Construction Type". This is no longer an option.-MCoffman

Permit# 240686
![image](https://user-images.githubusercontent.com/47611580/57704827-ab8a8300-7630-11e9-8f20-594f347ace12.png)

**Comment by calequin** [comment]
fixed and expired interior only
![image](https://user-images.githubusercontent.com/47603568/57717968-4e9bc680-764a-11e9-8214-96fab3a9250e.png)

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/57722826-557c0680-7655-11e9-9695-73512d43f1e2.png)
