### ISSUE TITLE
Building - ZoneCert - Inspection

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#89]
After (2)  failed Site Inspections a re-Inspection fee did not generate 

AP - 237139
Logged by K.Vanaman 2/11

![image](https://user-images.githubusercontent.com/4129185/53113249-1f742e00-350f-11e9-8202-8bc9dbb52ae5.png)

**Comment by imazlout** [comment]
Sent email to @ABonomo21 and awaiting response on how to proceed

**Comment by imazlout** [comment]
@ABonomo21 Kelly V. put in a couple of issues about ZoningCert missing a re-inspection fee. I checked the previous system and saw that this particular AP Type never had a re-inspection fee in its config. Do you want me to add it so that this ap type does have the ability to have re-inspection fees added moving forward? If so, is it $48 like it is for the others? 
(This is related to #90)

**Comment by ABonomo21** [comment]
Yes, this would also follow the same re-inspection fee process and requires the fee after two inspection each subsequent inspection results in a re-inspection fee.

**Comment by imazlout** [comment]
Ready for Test.
Added new re-inspection fee to ZONINGCERT.
<img width="960" alt="issue89" src="https://user-images.githubusercontent.com/47784290/53654193-1f64e400-3c1b-11e9-8e22-f64c7854057d.png">

**Comment by JuanitaMiles** [comment]
@imazlout During testing I noticed that the $48 re-inspection fee did populate after 2 failed SITE-INSP inspections, however the system did not require me to pay the fee. Upon resulting the third SITE-INSP with Passed, the application went to Closed/Complete with an outstanding fee.

![image](https://user-images.githubusercontent.com/31770504/53683334-a5416780-3ccd-11e9-991c-f8f89b805b71.png)

**Comment by megisys** [comment]
Add Status Check Here. Ready for Testing

**Comment by dhenry-KCI** [comment]
Confirmed fixed-AW
![image](https://user-images.githubusercontent.com/4129185/53894322-e606ec80-3ffd-11e9-8bb5-72d28f0dc018.png)
