### ISSUE TITLE
R4C/IPS-Planning-Rezone- acres not transferring to IPS

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#890]
enter acres or square footage in R4C.  Neither field populated in IPS.  because this didnt populate the $20 per acre fee did not populate.  Also, how will the system know if sqft or acres is entered in R4C and does the system generate the per acre fee based on either???????   I dont think sqft should be an option in R4C and IPS.

![image](https://user-images.githubusercontent.com/4129185/57710682-64ee5600-763b-11e9-81bf-28d44bf71cce.png)
![image](https://user-images.githubusercontent.com/4129185/57710700-6ddf2780-763b-11e9-9b0e-6b941dca33b3.png)

MW

**Comment by calequin** [comment]
fixed. removed acreage constraint since fee calc is looking at detail page value

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/57717273-da145800-7648-11e9-8d4f-3a77b62b5e61.png)

**Comment by dhenry-KCI** [comment]
fixed per RZ239541

MW
