### ISSUE TITLE
Trailer Permits-Building fee generated as $0

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#891]
The building fee for a temp trailer generated as $0. It should be $86 for a temp trailer and $173 for a permanent trailer.-AW
#240692
![image](https://user-images.githubusercontent.com/47611580/57711572-f3afa280-763c-11e9-8d22-59e6209f4946.png)

**Comment by ABonomo21** [comment]
not fixed-aw
![image](https://user-images.githubusercontent.com/47611580/58029248-2f89b280-7aea-11e9-8619-6bc34046ecd9.png)

**Comment by ABonomo21** [comment]
this is occurring on permits started in R4C and started in IPS-aw

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
Correct fees generated; Building Fee no longer showing a $0-MCoffman

Temporary Trailer: Permit# 245601
![image](https://user-images.githubusercontent.com/47611580/58806367-0554ec00-85e4-11e9-9a1f-e77b16fcd947.png)

Perminant Trailer: Permit# 245604
![image](https://user-images.githubusercontent.com/47611580/58806677-b065a580-85e4-11e9-8b93-806ff83608ea.png)
