### ISSUE TITLE
Viewing - ALL

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#892]
Is there a way to have the entire screen without having to use the bar at the bottom to see the entire way across? 

Example: Permit #240698
relates records- other applications. There are 26 other applications- 5 show up and in order to scroll down, you have to scroll over first.  You should be able to view as you scroll.  too much back and forth

![image](https://user-images.githubusercontent.com/47611580/57720917-e69cae80-7650-11e9-8f11-a013b39e27db.png)

![image](https://user-images.githubusercontent.com/47611580/57720959-fae0ab80-7650-11e9-9a3a-91bcef9ded49.png)

**Comment by dhenry-KCI** [comment]
@calequin - please review.

**Comment by dhenry-KCI** [comment]
@ABonomo21 - use the "Zoom" feature within the web browser.
