### ISSUE TITLE
building - grading - resubmittals - adhoc report

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#893]
Not getting new resubmittals as of 5/14/19

![image](https://user-images.githubusercontent.com/4129185/57724141-21561500-7658-11e9-97f6-21fa2c5000bf.png)

tm

**Comment by megisys** [comment]
As this is Tiffanys personal report.. Moving to  County to fix with her and adding under reporting

**Comment by dhenry-KCI** [comment]
@mmbanong meet with Tiffany to confirm ad hoc report

**Comment by ABonomo21** [comment]
@mmbanong @dhenry-KCI 
What is the status of this ticket ?

**Comment by JuanitaMiles** [comment]
@mmbanong - martin to update the BP - Grading/Driveway/FRO Intake Review Ad Hoc Report to show the Completeness Check Review type and the cycle that it is in.

**Comment by mmbanong** [comment]
Added completeness check review type and current cycle to Grading/Driveway and FRO
	intake review ADHOC report


![ADHOC Capture](https://user-images.githubusercontent.com/47392173/65536141-d59e5c80-ded0-11e9-9536-4e007a914448.PNG)

**Comment by ABonomo21** [comment]
will check dashboard reports and revisit later
