### ISSUE TITLE
Resubmittal BLDG/ Grading Not in Back Office

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#894]
Permit #240703

I submitted an applicant actions via R4C and it just circled and got hung up. 

![image](https://user-images.githubusercontent.com/47611580/57724052-f2d83a00-7657-11e9-9678-2f61c6bd9da3.png)

![image](https://user-images.githubusercontent.com/47611580/57724092-0d121800-7658-11e9-867e-eecd8451296d.png)

**Comment by calequin** [comment]
upon review of the application it looks like the detail page had missing information. Please retest. We are also working on adding a notification email to the customer when the county receives the resubmittal.

**Comment by dhenry-KCI** [comment]
at resubmit in r4c the applicant cannot see the comments made by the county for resubmit.

Ap #240797

the resubmittal was submitted on r4c and did not carry over to ips. the log verifies that the resubmittal was submitted and the milestone says awaiting applicant resubmit and there was not an additional completeness check review.

**Comment by megisys** [comment]
Closing issue due to working with Tiffany on fix
