### ISSUE TITLE
R4C-All-Resubmittal Log

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#895]
Need to have a resubmittal log as part of the R4C view. -AW
![image](https://user-images.githubusercontent.com/47611580/57724446-cf61bf00-7658-11e9-8ef7-f14cae7e908c.png)

**Comment by calequin** [comment]
spoke to @megisys about this. Exposing logs to the citizen can cause issues with legacy data in the system. For example, an employee could have put "bad" comments on a log type back in 2010 and the citizen would be able to view this going forward if this log type is added. A work around would be a notification sent to the customer that we received their resubmittal and will respond back in x amount of days.

**Comment by ABonomo21** [comment]
Logs for Resubmittals are now showing on the dashboard. I thought per conversations with Ashlye & Christian that we were not doing this and instead doing emails (as mentioned above.) If we are still doing the emails, then I did not get any of the appropriate emails for this resubmital. I only received the email notifcation about the revision payment being due.  And due to issue #924 even if the correct emails notifications were being sent out, I would not be able to read them.-AW

#240774
![image](https://user-images.githubusercontent.com/47611580/58027689-37942300-7ae7-11e9-8e46-f5e5ea677423.png)
![image](https://user-images.githubusercontent.com/47611580/58027706-3ebb3100-7ae7-11e9-815e-b3b3c3172a1a.png)

**Comment by megisys** [comment]
We added only the Resumbittal ones so they could see them

**Comment by ABonomo21** [comment]
fixed-AW
![image](https://user-images.githubusercontent.com/47611580/59105378-c97e9700-8901-11e9-945f-1b39c9945f87.png)
