### ISSUE TITLE
r4c - grading - grading details intake

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#897]
the grading details intake information in r4c disappeared once the application was submitted. After creating permit #240707 and going back to r4c - the information is all blank.

![image](https://user-images.githubusercontent.com/4129185/57724892-cc1b0300-7659-11e9-8371-f7ec1a352316.png)

tiffany martin 5/14/19

**Comment by dhenry-KCI** [comment]
corrected 5/22/19

**Comment by ABonomo21** [comment]
Opening- permit #246854  the details aren't viewable in R4C

6/20/19 EP

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/59872620-2a798680-9368-11e9-9ef7-dec7f526be47.png)

**Comment by calequin** [comment]
this is part of the detail page formula issue being fixed by @megisys

**Comment by calequin** [comment]
fixed added to allowed monikers in r4c config editor

**Comment by dhenry-KCI** [comment]
confirmed fixed grading permit 247881

**Comment by ABonomo21** [comment]
LOGGING CONDITIONS DID NOT POPULATE STILL - HOWEVER, THE GRADING DETAILS DID... PARTIALLY CORRECTED 

![image](https://user-images.githubusercontent.com/47611580/60181276-e0712480-97ef-11e9-9344-eb51c3750174.png)

![image](https://user-images.githubusercontent.com/47611580/60181300-ea932300-97ef-11e9-9c07-3ec90f892ab7.png)


TM #247833 6/26/19

**Comment by megisys** [comment]
This is a newer issue. New to look at this seperately.

**Comment by dhenry-KCI** [comment]
Duplicate of issue #902 - Closing
