### ISSUE TITLE
License - General License - Create New Contact

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#9]
The system is presenting the user with the following error message when trying to create a new contact. 

Logged by Shannon W. 

![image](https://user-images.githubusercontent.com/4129185/52350616-fb84f880-29f6-11e9-841c-baad520ed2c5.png)

**Comment by megisys** [comment]
THIS IS BEING ADDRESSED WITH LATEST PATCH . . Due Soon

**Comment by megisys** [comment]
Patch Applied.. Please Retest

**Comment by dhenry-KCI** [comment]
Was able to add additional contacts. Confirmed fixed
