### ISSUE TITLE
R4C -Detail Page Versioning

### ISSUE THREAD

**Issue by calequin** [kcigeospatial/Fred_Co_Land-Management#903]
County needs the ability to send back a detail page to the citizen during applicant actions in order for them to update any incorrect information. Currently during applicant actions the citizen cant update any submitted information. Instead the applicant adds the information in the applicant actions page and updates the information.

Possible work around is that the county receives the changes in applicant action log and permit tech will input the information in the detail page. Would need a change logs detail page to keep track of all the changes.

**Comment by megisys** [comment]
This is not possible as we lock the detail pages for update. It would be a HUGE HUGE change to allow for this.

Dan

**Comment by megisys** [comment]
This is possible, but a huge effort. I mean like 120 Hours at least

**Comment by ABonomo21** [comment]
Detail page versioning is not available - will be satisfied with applicant actions and log entries as discussed
