### ISSUE TITLE
PUBLIC Records Access from R4C and Other Internal

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#904]
i was able to search under lookup record with an existing application number # 240712 

do we want to limit any information available to the public

tiffany martin 5/15/19

**Comment by megisys** [comment]
Add Mike into this Task

**Comment by dhenry-KCI** [comment]
Meeting in 6/11-
Ashyle and Mike will make updates to the "Is Public" and "Display in portal" checkboxes. Changes will be made in IPS Pre-Prod in the Code Definition Management Tab (RCDI). 
Update the following:
- Inspections 
- Reviews 
- Conditions 
- Logs

**Comment by mmbanong** [comment]
Updated "Is Public" only for Elect per Dan. Will monitor and provide update instructions
