### ISSUE TITLE
R4C - DRIVEWAY - ENTRANCE APRON DETAILS

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#905]
highlighted should be on the same line. ...to install the apron and driveway:

![image](https://user-images.githubusercontent.com/4129185/57786471-89146a80-7701-11e9-98d1-ba81605cce38.png)

tiffany martin 5/15/19

**Comment by calequin** [comment]
fixed in one line
![image](https://user-images.githubusercontent.com/47603568/57789469-f8d92400-7706-11e9-8309-8cf467a09a53.png)

**Comment by ABonomo21** [comment]
Corrected.

EP 5/20/19
