### ISSUE TITLE
R4C-Unable to pay certain fees via portal

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#907]
We are unable to pay certain fees through the R4C portal. Specifically the Automation Enhancement Fee(for all permits) and the Master Plumber Trade License Fee. -aw
![image](https://user-images.githubusercontent.com/47611580/57801956-f389d280-7722-11e9-8922-6c59c39ee29e.png)

**Comment by calequin** [comment]
Also not working on Planning-Preplat-Dev Rev Planning Fee.... Still researching

**Comment by megisys** [comment]
Addressed this Issue

**Comment by ABonomo21** [comment]
I was able to pay Automation Enhancement fee on #240772. and I was able to pay fees on the Master Plumber license PM237153. I'll keep testing the various fees through out the day.-aw

**Comment by ABonomo21** [comment]
was able to pay for a building permit, license and a project.
