### ISSUE TITLE
R4C -All - Fees being paid updates detail pages (Excel Issue #50)

### ISSUE THREAD

**Issue by calequin** [kcigeospatial/Fred_Co_Land-Management#909]
fees being paid are trying to   update the detail page which in turn is causing fees not being able to be   paid.

**Comment by ABonomo21** [comment]
Christian or Dan, I am not sure what this issue is to retest- we have been able to pay fees

**Comment by ABonomo21** [comment]
per dan this is a duplicated issue- #1199 and #912
