### ISSUE TITLE
R4C - DRIVEWAY - RELATED RECORDS

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#910]
We have decided that we would like to have the related record that is required to be input in r4c to be transferred to IPS to keep this consistent with the other AP types. 

AP #240713

tiffany martin/emily pearl 5/16/19

**Comment by megisys** [comment]
This is a Future Enhancement. Nice to have. For now the completeness check tech will associaet. This will make sure we dont get mismatches

**Comment by ABonomo21** [comment]
this should be checked at completeness check and related by the tech.
