### ISSUE TITLE
building - FRO - under inspections milestone

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#911]
after approved notprfees then the below condition populated.

![image](https://user-images.githubusercontent.com/47611580/57854816-22518880-77b7-11e9-8cf9-ce0a0f3be4a5.png)

tm/ ep 5/16/19

**Comment by megisys** [comment]
Ready for Retest in New Environment. Do not test today

**Comment by ABonomo21** [comment]
this still populated, however, I was able to close this permit out. not sure if this condition matters or not. 

![image](https://user-images.githubusercontent.com/47611580/58962050-5dbcf280-8778-11e9-9b56-ac97c0da033c.png)

tm 6/5/19

**Comment by dhenry-KCI** [comment]
All labels removed - need to determine status of ticket.

**Comment by ABonomo21** [comment]
what is this? why is it populating @megisys

**Comment by megisys** [comment]
It is no longer populating.. Test a new one please

**Comment by ABonomo21** [comment]
APPEARS THAT THIS HAS BEEN CORRECTED 6/26/19 TM
