### ISSUE TITLE
r4c - Major logging - payment of fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#912]
took us to the velocity site and got this error message

ap 240730

![image](https://user-images.githubusercontent.com/47611580/57857258-c1c54a00-77bc-11e9-8128-09558596d45a.png)

tm ep 5/16/19

**Comment by calequin** [comment]
please retest

**Comment by ABonomo21** [comment]
Not corrected. Still receiving the same message.

![image](https://user-images.githubusercontent.com/47611580/58044634-3e825c00-7b0e-11e9-9b3c-7c55473f716b.png)

5/20/19 EP

**Comment by calequin** [comment]
fixed in preprod.
web services were out of sync.
![image](https://user-images.githubusercontent.com/47603568/59242828-c8d05400-8bd2-11e9-893c-86376470f2fa.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/59872910-cc996e80-9368-11e9-85ce-796e29e978ec.png)

6/20/19 EP/TM

**Comment by dhenry-KCI** [comment]
Confirmed fixed with recent detail page update 08/06/2019

![image](https://user-images.githubusercontent.com/4129185/62558410-fb02d880-b846-11e9-923d-3e704d817650.png)
