### ISSUE TITLE
R4C & IPS-Tank Commodity is missing

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#913]
The field for the Tank Commodity is missing on both R4C and IPS-AW

![image](https://user-images.githubusercontent.com/47611580/57857470-37c9b100-77bd-11e9-84d7-fdb15535992c.png)
![image](https://user-images.githubusercontent.com/47611580/57857520-4ca64480-77bd-11e9-9f2b-372ce69e992e.png)

Currently in Hanson 7:
![image](https://user-images.githubusercontent.com/47611580/57857677-a1e25600-77bd-11e9-92a5-a1ad538aca28.png)

**Comment by ABonomo21** [comment]
Inserted the commodity in the grid on R4C, Grid does not save. Permit# 240770-MCoffman

![image](https://user-images.githubusercontent.com/47611580/58024186-9ce41600-7adf-11e9-93bf-3faa980b8f1c.png)

![image](https://user-images.githubusercontent.com/47611580/58024245-bedd9880-7adf-11e9-966b-f4b4a98baee8.png)

![image](https://user-images.githubusercontent.com/47611580/58024511-5347fb00-7ae0-11e9-9b70-e09a5b50687f.png)

Is there a way to make it so that it is just asking for the commodity? We need to know what is being held in the tank but it is asking for the gallons two times. 

![image](https://user-images.githubusercontent.com/47611580/58024730-dec18c00-7ae0-11e9-943a-d01cdacebe59.png)

**Comment by calequin** [comment]
fixed the save grid and only to display commodity and not gallons in r4c

**Comment by ABonomo21** [comment]
fixed on the R4C side-AW
![image](https://user-images.githubusercontent.com/47611580/58805239-b443f880-85e1-11e9-828a-b109719ab1bb.png)

**Comment by ABonomo21** [comment]
fixed on the IPS side too. -AW
![image](https://user-images.githubusercontent.com/47611580/58805363-ee14ff00-85e1-11e9-9ba5-214e63868ad3.png)
