### ISSUE TITLE
R4C-Planning-water/sewer info description

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#915]
change "description of the proposed construction" to "description of request".  This is true for all Planning Applications

![image](https://user-images.githubusercontent.com/4129185/57858396-00f49a80-77bf-11e9-93b7-4b72f9250da9.png)

MW

**Comment by calequin** [comment]
in order for it to be module based I had to add it to the actual title instead of the tool tip. Tool tip editable feature will be in the 19.7 release.
![image](https://user-images.githubusercontent.com/47603568/57945862-9156dc00-78a0-11e9-8471-bd03c7cdbed7.png)
