### ISSUE TITLE
IPS-Certificate of Potability hold is not generating automatically

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#918]
The hold/condition for the requirement of a certificate of potability is not generating automatically. There is the option to add it in Conditions but there is not an option in Logs. Need to confirm with @ABonomo21 that they are to generate automatically rather than us adding them to each applicable permit.-AW
#240733 & 240731
![image](https://user-images.githubusercontent.com/47611580/57862086-c93d2100-77c5-11e9-82c4-17c604690ffb.png)
![image](https://user-images.githubusercontent.com/47611580/57862137-dd811e00-77c5-11e9-8a47-325d6ea62de7.png)
![image](https://user-images.githubusercontent.com/47611580/57862321-2e911200-77c6-11e9-9598-ac4821d77ccd.png)

**Comment by ABonomo21** [comment]
Confirmed with @ABonomo21 These holds are to generate automatically.-AW

**Comment by imazlout** [comment]
Ready for test

**Comment by ABonomo21** [comment]
Failed- COP condition did not generate on a new dwelling on well and septic

![image](https://user-images.githubusercontent.com/47611580/60040392-e4356780-9686-11e9-87a7-bb495b8a7f58.png)

tested in preprod permit 246879

**Comment by imazlout** [comment]
Data Issue. Water and Sewer Type are blank for this address
<img width="857" alt="Capture" src="https://user-images.githubusercontent.com/47784290/60073744-40cc6d00-96ef-11e9-97f7-f1e8ab516e9e.PNG">

**Comment by ABonomo21** [comment]
Failed-COP condition did not generate and this parcel had the well/septic info completed.-AW
![image](https://user-images.githubusercontent.com/47611580/60125262-70b05a80-9759-11e9-80cc-7e17a9895dd9.png)

![image](https://user-images.githubusercontent.com/47611580/60125391-b53bf600-9759-11e9-893c-9c5cdd4e9b48.png)

![image](https://user-images.githubusercontent.com/47611580/60125322-8b82cf00-9759-11e9-9a05-9993f84a3f10.png)

**Comment by ABonomo21** [comment]
Retest Failed-Generated as a Log-Confirmed with Ashlye that it needs to generate as a Condition-AW
![image](https://user-images.githubusercontent.com/47611580/60209006-bb000d00-9827-11e9-8fcd-0ed25c3460bc.png)

**Comment by megisys** [comment]
No Conditions are Hansen 7 we switched to LOGS for IPS 11

**Comment by ABonomo21** [comment]
ashlye will check

**Comment by ABonomo21** [comment]
the log is not going to stop stage progression, it needs to be a status check or condition at the pending certificate milestone
![image](https://user-images.githubusercontent.com/47611580/65437100-30f91d80-ddf1-11e9-8ee6-f885da5c740a.png)

**Comment by megisys** [comment]
COP Log will need an End date pending certificate to be cleared as a Status Check

**Comment by ABonomo21** [comment]
once again i want this as a condition not a log that has to be stopped- the permit can be closed with out a log being stopped 
i need this to be a hard hold !

**Comment by ABonomo21** [comment]
i see the condition generated on permit 246801 i also see a log was created - should just be a condition

unable to bypass the status check 
![image](https://user-images.githubusercontent.com/47611580/65629586-98ee6600-dfa1-11e9-9cba-c20ea7b6c43c.png)

**Comment by calequin** [comment]
fixed. removed the need for a log approval and added it as a condition approval in order for status check to be true

**Comment by ABonomo21** [comment]
condition generated- which is great 

![image](https://user-images.githubusercontent.com/47611580/66341747-e9f14900-e915-11e9-969d-ae881e4cdfe9.png)

BUT what is the hold log must have a valid stop date - why is there still a log ? 
![image](https://user-images.githubusercontent.com/47611580/66341811-fd9caf80-e915-11e9-8e33-b1bfc145c0c8.png)

**Comment by ABonomo21** [comment]
@dhenry-KCI and @calequin is this fixed ?

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/68422762-ce749a80-016e-11ea-96ca-afc78db9a5d3.png)
