### ISSUE TITLE
Planning-Rezone-primary applicant must be property owner

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#919]
For Rezone, owner must be the applicant.  Created application in R4C as licensed contact and was allowed to keep moving forward.  Rezone should be configured like BOA where stage progression past Intake should be held up until owner is made primary applicant.

Problem with this is, as noted in issue 859, is we are unable to change the primary applicant in R4C without starting a new application.  Christian thinks this issue may be fizxed with the July R4C upgrades???

MW

**Comment by megisys** [comment]
No The User logged in has to be the Primary Applicant. They can call themselves a Licensed Contact or a Property Owner Only.. Fixed in PreProd

**Comment by dhenry-KCI** [comment]
ok.  change "of" to "or.  


![image](https://user-images.githubusercontent.com/4129185/58808290-c1fc7c80-85e7-11e9-9eb8-161ca33d8d0a.png)


MW

**Comment by dhenry-KCI** [comment]
Dan fixed on fly to not require owner be applicant, same fix as BOA issue

MW
