### ISSUE TITLE
R4C-Res Use- Detail page layout

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#920]
The titles for Accessory Structure and Addition/Alteration Details both need to be moved up.-AW
![image](https://user-images.githubusercontent.com/47611580/57863442-191ce780-77c8-11e9-946d-31d0850d0604.png)

**Comment by megisys** [comment]
Changes made updates

**Comment by ABonomo21** [comment]
not fixed-aw
![image](https://user-images.githubusercontent.com/47611580/58024070-5d1d2e80-7adf-11e9-9fab-a9cd21653d92.png)

**Comment by megisys** [comment]
Addressed

**Comment by ABonomo21** [comment]
not fixed-aw
![image](https://user-images.githubusercontent.com/47611580/58806810-ec990600-85e4-11e9-9535-5cbcbea0372f.png)

**Comment by calequin** [comment]
fixed in test

**Comment by ABonomo21** [comment]
Fixed in test-MCoffman
