### ISSUE TITLE
IPS & R4C-Inspection Requests on Weekends

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#922]
I was able to put in an inspection request for weekend days. Not sure if this is a issue or not but I wanted to log it since we do not allow for weekend inspections. Need to check with Bob Ensor & Ashlye.-AW
![image](https://user-images.githubusercontent.com/47611580/57933948-86924c00-788c-11e9-9586-29f542016f56.png)
![image](https://user-images.githubusercontent.com/47611580/57933978-9873ef00-788c-11e9-8485-54d4fbe8b013.png)

**Comment by megisys** [comment]
You can do that in IPS too. This isn't a Rhythm Issue as it just follows back office rules. We need to set up the scheduling rules still

**Comment by ABonomo21** [comment]
dan has rules needs to configure

**Comment by calequin** [comment]
@megisys I need the inspection scheduling rules

**Comment by megisys** [comment]
Added Holidays too - REady to Promote.. BP_ScheduleInspection_BU
