### ISSUE TITLE
Notification Emails- Does not display

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#924]
Dan- I wanted to make sure this issue was logged. 

![image](https://user-images.githubusercontent.com/47611580/58021515-13c9e080-7ad9-11e9-98c5-f71b9d57e80e.png)

**Comment by ABonomo21** [comment]
Notifications need to be more clear with pdox and new plan review and upload

**Comment by megisys** [comment]
Fixed in PreProd

**Comment by ABonomo21** [comment]
notifications is off to be able to retest

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/59615205-20e5e980-90f0-11e9-8cea-e8098da721dd.png)
