### ISSUE TITLE
PDOX- Testing Error

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#925]
Received an error in batch log when testing PDOX - Selected a Resubmit from PDOX, stuck in a loop with R4C, PDOX and IPS- Fee was paid in back office generate error in batch manager log

PERMIT #240740

![image](https://user-images.githubusercontent.com/47611580/58021752-c9952f00-7ad9-11e9-9e02-090c3b7f2081.png)

R4C Dashboard 
![image](https://user-images.githubusercontent.com/47611580/58021877-2c86c600-7ada-11e9-9da0-b11367d5327a.png)

Pdox
![image](https://user-images.githubusercontent.com/47611580/58021889-33add400-7ada-11e9-99ed-4ea97148e1d8.png)

IPS

![image](https://user-images.githubusercontent.com/47611580/58021904-3a3c4b80-7ada-11e9-942d-8fefd5b00268.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58021965-62c44580-7ada-11e9-88b8-37fe5afebb54.png)

**Comment by megisys** [comment]
I fixed this issue.. Pay Status now travellign across. Loop Broken

**Comment by JuanitaMiles** [comment]
all seems fine now - closing
