### ISSUE TITLE
IPS-Building- Priority Code *

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#927]
Please make Priority code a required field at completeness check. - Not needed for Plumbing and Electrical because there is no review completed on these two A/P's 
![image](https://user-images.githubusercontent.com/47611580/58022250-11688600-7adb-11e9-93d5-883aa7e6a29a.png)

**Comment by megisys** [comment]
This will be in the new environment. Please Do Not Test in TEST

**Comment by ABonomo21** [comment]
failed for Electric. Priority codes are not needed for Plumbing and Electrical permits-AW
![image](https://user-images.githubusercontent.com/47611580/58183309-1feea300-7c7d-11e9-9234-f8b834d45739.png)

**Comment by megisys** [comment]
Test in PREPROD - Fixed

**Comment by ABonomo21** [comment]
corrected - will continue to check review timeframes are working on all a/p types as we re-test

not required on plumbing and electrical
