### ISSUE TITLE
R4C- Resuse -Minor Permits 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#928]
Need to make Minor Permit a back office check box only- applicants will not know when to check this. 

![image](https://user-images.githubusercontent.com/47611580/58022395-5987a880-7adb-11e9-808d-f30ca41a38a2.png)

**Comment by calequin** [comment]
removed minor permit. please retest

**Comment by ABonomo21** [comment]
Issue Fixed; Check box has been removed on the R4C Side-MCoffman

![image](https://user-images.githubusercontent.com/47611580/58805106-629b6e00-85e1-11e9-9873-f6098c65bdf6.png)
