### ISSUE TITLE
PDOX- Observed Sq. Ft. 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#929]
We need to be able to add SOP's in especially for this field because you have total sq. ft. of the space and the altered amount- this is not on all a/p's need to discuss further with Dan 

![image](https://user-images.githubusercontent.com/47611580/58022604-cb5ff200-7adb-11e9-9781-9df3fbeae69d.png)

**Comment by ABonomo21** [comment]
can we add sop's to instruct staff to complete?? @RS-Avolve

**Comment by RS-Avolve** [comment]
Instructions can be added to the Task Instructions - these instructions can be formated with HTML/CSS so there is a lot of flexibility.  If you provide the instructions you need to add, and the format you want to see it in, I will add the information.

**Comment by dhenry-KCI** [comment]
@RS-Avolve - i think this got lost in the email shuffle around training but on 8/21 i sent the following "If New populate field with the Gross Floor Area , if Addition or Alteration populate with the Sq. ft. of the addition or alteration."

You should check that email in case there are other outstanding items you can update.

**Comment by RS-Avolve** [comment]
The text has been added, see screenshot - text can be bolded, or given a color if needed.

![Screenshot Github 929](https://user-images.githubusercontent.com/53225350/66001753-6809a780-e45f-11e9-9f3e-a3d338a2a86e.PNG)
