### ISSUE TITLE
Building - RESBLDG -Septic Installation Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#93]
The system incorrectly generated a septic installation fee.

AP 237221
Logged My M. Coffman

![fred_septicinstall](https://user-images.githubusercontent.com/4129185/53139606-25dac800-3558-11e9-9afb-650b4f420129.png)

**Comment by imazlout** [comment]
Training Needed. This is working as designed (even in H7). When new spetic is selected on detail page, the user must select either Conventional or Sand Mound. 
New Septic + Conventional: $150
New Septic + Sand Mount: $250

Please screenshot for proof of test (AP# 237324 in TEST)
<img width="960" alt="issue93_workingasdesigned" src="https://user-images.githubusercontent.com/47784290/53187062-43e40f00-35d0-11e9-83c0-4569c2905ec9.png">

<img width="960" alt="issue93_detailpage" src="https://user-images.githubusercontent.com/47784290/53187070-48102c80-35d0-11e9-9bfd-3df2eb7bc33a.png">

**Comment by ABonomo21** [comment]
I will have Abbie or Megan retest and close if possible. Please keep marked as a training issue.

**Comment by ABonomo21** [comment]
I believe the original issue was not that the fee type shouldn't have generated but the fact that the fee generated as $0 (in the first screenshot). I'll retest to make sure the correct fee amount generates-AW

**Comment by ABonomo21** [comment]
Fee amount generated correctly-AW
![image](https://user-images.githubusercontent.com/47611580/54368662-ed0bab80-464a-11e9-8bef-a6f0817115ad.png)
