### ISSUE TITLE
Building- Resuse - Grading 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#930]
Dan - This is added as a reminder to make sure you complete the auto- population of the grading permits for resuse based on rules configured on the white board. This resuse permit still generated the fees for grading and scd and no grading permit was created. 
![image](https://user-images.githubusercontent.com/47611580/58022782-35789700-7adc-11e9-8ecc-e1498ae08b94.png)

![image](https://user-images.githubusercontent.com/47611580/58022819-4aedc100-7adc-11e9-8c5f-8b3587b78ded.png)

**Comment by megisys** [comment]
I know.. I need time :)

**Comment by megisys** [comment]
Not sure it is perfect.. Which field on RESUSE is Cut/Fill ?? and Earth Distrub.

**Comment by ABonomo21** [comment]
grading permit did not generate-AW
![image](https://user-images.githubusercontent.com/47611580/59608882-4ec53100-90e4-11e9-9c22-36cc4da0c8b6.png)

**Comment by megisys** [comment]
Please Test REUSES for Grading Permits

**Comment by ABonomo21** [comment]
corrected
