### ISSUE TITLE
R4C- Details not showing up-all permits (Detail page edit option after submit)(Excel Issue # 59)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#932]
The Res Use details are not showing up when you go to look at the permit on your dashboard. even though they show when you submit the permit and they show on the IPS side.-AW

#240774
![image](https://user-images.githubusercontent.com/47611580/58028149-20096a00-7ae8-11e9-87b0-bf6b07517b76.png)
![image](https://user-images.githubusercontent.com/47611580/58028166-28fa3b80-7ae8-11e9-88ff-e203094b7320.png)

**Comment by calequin** [comment]
this was done in order for the customer to not change any detail page data after submission. If they need to change any info they would have to provide it in the applicant actions detail page and the permit tech will have to change this in back office.

**Comment by ABonomo21** [comment]
will need to discuss further with Ashlye-AW

**Comment by megisys** [comment]
Added to Allowed Monikers

**Comment by ABonomo21** [comment]
Permit# 245653; Partially Fixed-MCoffman

Able to view the details; however the applicant should not be able to edit the application once it has been submitted. If they want it to edit the application once it has been submitted they will have to resubmit through applicant actions. 

![image](https://user-images.githubusercontent.com/47611580/59041658-0d609600-8847-11e9-9d37-ced2200d2dfe.png)

**Comment by calequin** [comment]
@megisys has a fix for this

**Comment by megisys** [comment]
This is Fixed

**Comment by ABonomo21** [comment]
Retest failed, I am still able to edit the Res Use Details on R4C-AW
![image](https://user-images.githubusercontent.com/47611580/60103450-9aec2300-972d-11e9-9830-9fc1316ce436.png)
![image](https://user-images.githubusercontent.com/47611580/60103467-a5a6b800-972d-11e9-959a-932882c229a1.png)

**Comment by megisys** [comment]
Applicant can change details until the application is UNDER REview

**Comment by ABonomo21** [comment]
Per Ashlye-applicant should not be able to change the details once the completeness check is approved-AW
![image](https://user-images.githubusercontent.com/47611580/60125929-d5b88000-975a-11e9-8148-9b57bd9ac46e.png)
![image](https://user-images.githubusercontent.com/47611580/60125970-ec5ed700-975a-11e9-98cc-0635c70d8c73.png)

**Comment by calequin** [comment]
20.1 Release will diable edit button. For now it is resolved with formula after the under review milestone

**Comment by ABonomo21** [comment]
closing for now marking as a post go live to see if this is still a problem and if it is resolved in January release
