### ISSUE TITLE
R4C-Payment Screen Stuck on Transaction Number (Excel Issue #54)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#934]
When paying a fee, after the payment has completed, the transaction number appears on the screen and the the "Returning to Home.." message is loading but it stays on this screen until you click "My Dashboard" or one of the other menu options. -AW

![image](https://user-images.githubusercontent.com/47611580/58028403-a2922980-7ae8-11e9-9fc0-6f08b81661f2.png)

**Comment by calequin** [comment]
The screen has been changed to a static page in order to display a payment failure and transaction number. The button label has been changed to say "Click Here for Homepage".

**Comment by ABonomo21** [comment]
Corrected however, 

![image](https://user-images.githubusercontent.com/47611580/59057369-3c3b3400-8868-11e9-934e-9f93787fa498.png)

Can you make the language say "Click here to return to the homepage".

**Comment by megisys** [comment]
This is being moved to nice to have, not a bug

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/59372109-6a0ef580-8d0c-11e9-8513-8ca6c8371a2b.png)

**Comment by ABonomo21** [comment]
Unable to pay fees, therefore unable to test-AW
![image](https://user-images.githubusercontent.com/47611580/59614786-6c4bc800-90ef-11e9-9f9b-606948ccca46.png)

**Comment by megisys** [comment]
Duplicate. We have a ticket for Payment Processing Issues, This actual issue was addressed

**Comment by dhenry-KCI** [comment]
agreed. Ticket with AP's unable to process is #1199
