### ISSUE TITLE
Planning-PWConstr-reapprovals-DUSWM fee didnt populate.

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#935]
this parcel is on water/sewer and should have generated the $162 DUSWM fee

![image](https://user-images.githubusercontent.com/4129185/58029807-5a283b00-7aeb-11e9-9e64-a4f1aacf0a4e.png)

![image](https://user-images.githubusercontent.com/4129185/58029857-74621900-7aeb-11e9-9851-2098c798763c.png)

DUSWM did populate as a reviewer, which is good.

![image](https://user-images.githubusercontent.com/4129185/58029997-c4d97680-7aeb-11e9-8b5d-ffca1ba52e60.png)

MW

**Comment by megisys** [comment]
Added the Fee in

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/59378391-33dc7080-8d22-11e9-85d9-b2ae9e3a98fc.png)

**Comment by megisys** [comment]
Mike this fee hasnt been used since 2010..

**Comment by megisys** [comment]
Worked with Mike.. Happy here
