### ISSUE TITLE
planning-preliminary-misspelling

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#937]
affidavit mispelled under condition type

![image](https://user-images.githubusercontent.com/4129185/58043151-75567300-7b0a-11e9-90c2-3a9fdac0beed.png)

MW

**Comment by megisys** [comment]
Fixed in PreProd

**Comment by dhenry-KCI** [comment]
Fixed per PP244581, AM & GH
