### ISSUE TITLE
R4C - Grading/ Logging - No Confirmation No#

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#938]
Processed three Grading/Logging permits and I received  confirmation for all three that my record was submitted but no # is actually provided... under my dashboard- it doesnt show that they were created. 

![image](https://user-images.githubusercontent.com/47611580/58043806-2ad5f600-7b0c-11e9-95f6-fd8282cfd661.png)

EP 5/20/19

**Comment by megisys** [comment]
We have this issue reported to development.. Closing as this is a wider issue
