### ISSUE TITLE
IPS-Non Res Tank-Incorrect Fees

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#940]
The Life Safety Fee for a Non Res Tank did not generate. This was originally working in IPS and now the fee is not generating when an application is sent from R4C-AW
#240787
![image](https://user-images.githubusercontent.com/47611580/58101063-e6e6fd80-7bac-11e9-9459-ce14432b2e33.png)
![image](https://user-images.githubusercontent.com/47611580/58101082-f1a19280-7bac-11e9-84d5-a326e5e96898.png)
![image](https://user-images.githubusercontent.com/47611580/58101136-0b42da00-7bad-11e9-98d4-a13ffbe1575b.png)

**Comment by calequin** [comment]
fixed

**Comment by ABonomo21** [comment]
Issue fixed in Test Permit# 245731-MC

![image](https://user-images.githubusercontent.com/47611580/59045116-6c290e00-884d-11e9-95ac-73369fecd645.png)

Issue fixed in Pre Prod Permit# 245731

![image](https://user-images.githubusercontent.com/47611580/59046808-a516b200-8850-11e9-8f07-c75eac735fca.png)
