### ISSUE TITLE
R4C-Gaming-Distributor Reports Grid not saving

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#942]
the details of the report in the grid do not save once you go to submit it-aw
![image](https://user-images.githubusercontent.com/47611580/58123738-840c5b00-7bda-11e9-98f4-8102ccae9e74.png)
![image](https://user-images.githubusercontent.com/47611580/58123723-7bb42000-7bda-11e9-901e-272ee83b96a7.png)

![image](https://user-images.githubusercontent.com/47611580/58123835-c0d85200-7bda-11e9-845f-198da9941d20.png)

**Comment by calequin** [comment]
fixed. please retest

**Comment by ABonomo21** [comment]
able to save grid - test complete ab
