### ISSUE TITLE
R4C-Home Occ-Grid not saving

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#944]
The grid details for the Home Occupation applications are not saving when you go to submit-AW

![image](https://user-images.githubusercontent.com/47611580/58177980-56272500-7c73-11e9-88a3-3e15d27d3310.png)

![image](https://user-images.githubusercontent.com/47611580/58177951-4c9dbd00-7c73-11e9-8b88-ce71385f95ea.png)

**Comment by calequin** [comment]
fixed. please retest

**Comment by ABonomo21** [comment]
able to save
