### ISSUE TITLE
r4c - grading - grading details intake

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#945]
saved application in r4c, grading details are editable at any point. we only want to be able to edit this when the applicant initiates it under applicant actions or we push it back. we submitted application and then changed the fill amount and it doesn't show in IPS - which is OK because we do not want the applicants changing information on the fly.

ap 240796

tm 5/22/19

**Comment by ABonomo21** [comment]
Access is now forbidden to edit the details while permit is under intake review.

6/20/19 EP
