### ISSUE TITLE
IPS Pre Prod-Automatically Logged out of the system.

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#946]
I was in the middle of working on the electrical license #E244390 and the system kicked me out while I was inputting an associated contact for the license and the log out screen appeared inside the create contact window-AW
![image](https://user-images.githubusercontent.com/47611580/58179501-507f0e80-7c76-11e9-83c3-28446cf0dc58.png)

**Comment by megisys** [comment]
Fixed

**Comment by ABonomo21** [comment]
will monitor - not happening
