### ISSUE TITLE
IPS Pre Prod-Error Message when trying to add new contact

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#948]
I received this message while trying to add a new contact for a new plumbing license-aw
![image](https://user-images.githubusercontent.com/47611580/58181814-76a6ad80-7c7a-11e9-8719-335efc07fa1a.png)

**Comment by calequin** [comment]
I was able to create a new contact in the system. Please retest. Also add any additional information such as all of the fields that were filed in. This would allow me to replicate exactly each step.

**Comment by ABonomo21** [comment]
was able to create a contact without an error
