### ISSUE TITLE
IPS Pre Prod- Language 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#949]
All the contact records migrated over and defaulted to Language as Spanish.

![image](https://user-images.githubusercontent.com/47611580/58184586-62b17a80-7c7f-11e9-9153-ec8272cdc4fc.png)

**Comment by dhenry-KCI** [comment]
Data migration issue. correct in IPS test

**Comment by ABonomo21** [comment]
fixed-aw
