### ISSUE TITLE
Building - Demolition - Sq. Footage field

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#95]
Sq. footage field shold not be required on a demolition permit.

Logged by M. Coffman

![demo](https://user-images.githubusercontent.com/4129185/53141458-3a21c380-355e-11e9-865d-cf27262dffa0.png)

**Comment by imazlout** [comment]
Ready for test once updates are copied to TEST.

Please screenshot for proof of test

<img width="960" alt="issue95_fixed" src="https://user-images.githubusercontent.com/47784290/53194742-2b7cf000-35e2-11e9-99ca-f0fb2f2a4cdb.png">

**Comment by dhenry-KCI** [comment]
Confirmed Fix 

A/P# 237343

![image](https://user-images.githubusercontent.com/4129185/53256188-43fa1280-3695-11e9-82e3-86ef17d04c11.png)
