### ISSUE TITLE
IPS Pre Prod- Contact Records- Drivers Lic. 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#950]
Drivers License #'s migrated over in the ID number Field instead into the Driver's license # field
PM01131

![image](https://user-images.githubusercontent.com/47611580/58184764-b91eb900-7c7f-11e9-880a-4cabc0a466a7.png)

**Comment by ABonomo21** [comment]
ID # should have been the license # PM01131

**Comment by dhenry-KCI** [comment]
Spot check reveals data migration from Hansen 7 to Test was done incorrectly as well.

**Comment by megisys** [comment]
The standard DL Field length doesnt support the length of the DL for Maryland

**Comment by ABonomo21** [comment]
same in 7 

![image](https://user-images.githubusercontent.com/47611580/58982352-4266dd00-87a2-11e9-8e2c-f03834b86134.png)
