### ISSUE TITLE
R4C - GRADING - ERROR MESSAGE

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#952]
ERROR WHEN APPLICATION SUBMITTED

![image](https://user-images.githubusercontent.com/4129185/58185264-b8d2ed80-7c80-11e9-9fa1-cf3058849909.png)

AP #240797

**Comment by calequin** [comment]
please try again. we reset the environment which may have cause this error. Also close out browser and re log in

**Comment by ABonomo21** [comment]
Resolved. 

6/3/19 EP
