### ISSUE TITLE
IPS Pre Prod- Licenses

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#953]
The plumbing license contact information migrated into the Licenses for this contact section. 

![image](https://user-images.githubusercontent.com/47611580/58185130-6db8da80-7c80-11e9-906b-762a1de65f36.png)

The electrical license contact information migrated into the Available License field 

![image](https://user-images.githubusercontent.com/47611580/58185244-ac4e9500-7c80-11e9-8910-a281eb9b327d.png)

Shouldn't they have all migrated into the License for this Contact field??

**Comment by dhenry-KCI** [comment]
@megisys - Dan question on how the difference between data migrating to Licenses for this contact and Available Licenses.

**Comment by megisys** [comment]
No they should not. As a Company with a employee with an active license has it as an available license rather than that contact having licenses. Slightly different.

**Comment by ABonomo21** [comment]
Working correctly- ab
