### ISSUE TITLE
IPS Pre Prod- Attachments Trade Lic

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#954]
The attachments in the license migrated over without the titles they were assigned in OLE. They converted over with numbers and cannot be opened 

![image](https://user-images.githubusercontent.com/47611580/58185457-1d8e4800-7c81-11e9-938a-400d1631547a.png)

![image](https://user-images.githubusercontent.com/47611580/58185498-35fe6280-7c81-11e9-9b0b-0ef605b0b057.png)

**Comment by dhenry-KCI** [comment]
Issue still exists in recent data migration / conversion. FYI - No attachments for this record in IPS Test.

**Comment by ABonomo21** [comment]
I don't like it but I will accept- okay per mike and ashlye
