### ISSUE TITLE
IPS preprod-planning-APFO-work types

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#955]
crazy list of work types for APFO

![image](https://user-images.githubusercontent.com/4129185/58185718-97263600-7c81-11e9-9a34-a24840c32f1f.png)

MW

**Comment by dhenry-KCI** [comment]
shouldnt even have a worktype.  only occ type.

Prepod...
![image](https://user-images.githubusercontent.com/4129185/58185971-00a64480-7c82-11e9-93f7-162a28f732e4.png)


Test
![image](https://user-images.githubusercontent.com/4129185/58186003-10258d80-7c82-11e9-9465-423855a183df.png)


MW

**Comment by megisys** [comment]
Ready for Retest.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58962098-73cab300-8778-11e9-8d73-5a10465f8819.png)
Fixed per AP # A244572
