### ISSUE TITLE
IPS Pre Prod- Trade License Numbers 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#956]
License numbers converted without the 0 between letters and license number- May not be a huge deal, wanted to log because it is difference from H7 and IPS

![image](https://user-images.githubusercontent.com/47611580/58186045-259ab780-7c82-11e9-80e0-cee934d26ee3.png)

![image](https://user-images.githubusercontent.com/47611580/58186113-419e5900-7c82-11e9-8e87-a8cdafaa114c.png)

**Comment by dhenry-KCI** [comment]
Issue existing IPS Test as well.
