### ISSUE TITLE
IPS Pre Prod-Appliance Installer Confirm License details

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#957]
On the completeness check for the Appliance installer, the hold for Confirming the license details page, is not on the check status before the completeness check. this is part of our review for the completeness check and should hold up the review so it can not be approved until we confirm it.-AW
![image](https://user-images.githubusercontent.com/47611580/58186411-d5702500-7c82-11e9-80fc-71c2e77e2460.png)
![image](https://user-images.githubusercontent.com/47611580/58186458-ed47a900-7c82-11e9-8397-a0c25cecf5d1.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/58587309-ac233c00-8222-11e9-9e37-aa8dd21695a0.png)

**Comment by ABonomo21** [comment]
confirmed corrected - ab
