### ISSUE TITLE
IPS Pre Prod- Duplicated Contact Trade License 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#960]
Related to #959 
Multiple persons of the same name transferred to license PM01331 under relationships tab

![image](https://user-images.githubusercontent.com/47611580/58186616-3b5cac80-7c83-11e9-8895-0cfabaaddc52.png)

only one related in H7

![image](https://user-images.githubusercontent.com/47611580/58186699-647d3d00-7c83-11e9-8993-6d25cdeca016.png)

only one Mark S. exists in H7 
![image](https://user-images.githubusercontent.com/47611580/58186761-88d91980-7c83-11e9-8403-af6f13840d19.png)

**Comment by JuanitaMiles** [comment]
**The duplicate Relationship on the PIPE DOCTOR/MARK S MARTIN Contact record (License # PM01331) is consistent in both TEST and PREPROD.** _(See the two screenshots below, one from each environment)_

![image](https://user-images.githubusercontent.com/31770504/58479258-e955d400-8125-11e9-8523-157884052d15.png)

![image](https://user-images.githubusercontent.com/31770504/58479544-80bb2700-8126-11e9-81e4-d68123991353.png)

**There is, however, only one Mark S Martin Contact Record in both systems, which appears to be consistent with the Hv7 screenshot.** _(Screenshots below from each environment)_

![image](https://user-images.githubusercontent.com/31770504/58479803-f32c0700-8126-11e9-8d66-49d90b54afcb.png)

![image](https://user-images.githubusercontent.com/31770504/58479833-050daa00-8127-11e9-9940-b1c606495bf3.png)

**The issue appears to be that the Mark S Martin contact record was added as a Relationship twice to the Pipe Doctor/Mark S Martin contact record. The License application (PM01331) itself has two applicants: Mark S Martin; and Pipe Doctor/Mark S Martin, which appears correct.** _(Screenshot below from each environment)_

![image](https://user-images.githubusercontent.com/31770504/58480348-30dd5f80-8128-11e9-9b49-aba352492092.png)

![image](https://user-images.githubusercontent.com/31770504/58480273-0a1f2900-8128-11e9-84bd-2ff2b159d463.png)

**Comment by JuanitaMiles** [comment]
@ABonomo21 - Ashlye can you confirm within the Contact Browser in Hv7 that the PIPE DOCTOR/MARK S MARTIN record only has one Mark S Martin relationship?

![image](https://user-images.githubusercontent.com/31770504/58480905-5028bc80-8129-11e9-862a-d7556761e163.png)

**Comment by ABonomo21** [comment]
resolved only in one time
