### ISSUE TITLE
ips-preprod-BOA-councty council or PC appeal-wrong fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#961]
only $1 fee populated

![image](https://user-images.githubusercontent.com/4129185/58187163-47953980-7c84-11e9-84bd-86849bef28ff.png)

MW

**Comment by megisys** [comment]
This is Known Issue. Fee Library updated in Error

**Comment by mmbanong** [comment]
Fees appear to be correct in the fee library

![image](https://user-images.githubusercontent.com/47392173/59516844-3b218c80-8e90-11e9-8479-6ecd491278b5.png)

**Comment by dhenry-KCI** [comment]
fixed- MW

![image](https://user-images.githubusercontent.com/4129185/59610200-e1ff6600-90e6-11e9-800f-1e222a6530af.png)
