### ISSUE TITLE
Building - Major Grading - Sites Tab

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#962]
THE PARCEL AND ADDRESS DOESN'T CARRY DOWN TO LINKED SITES UNDER THE SITES TAB

AP 240798

TM 5/22/19

**Comment by megisys** [comment]
Parcel has no Address - County GIS Data iSsue

**Comment by megisys** [comment]
This is Right

**Comment by megisys** [comment]
None Issue
