### ISSUE TITLE
IPS Pre Prod- Trade License 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#963]
How are we handling the outstanding signature reviews - were they to be converted to the new review names in IPS, for this example Trade license should have gone into renewal reviews?? 
Missing Renewal Review for Electrical Licenses 
May need to have a follow up discussion: 

![image](https://user-images.githubusercontent.com/47611580/58187184-52e86500-7c84-11e9-8c01-a03a3669d243.png)

**Comment by ABonomo21** [comment]
when you check status nothing populates showing a review is pending.

**Comment by megisys** [comment]
Is this valid in our new process. We can ignore these and just focus on our Renewal Reviews

**Comment by ABonomo21** [comment]
number signifies the number in stage progression that the signature review populated in 7
