### ISSUE TITLE
R4C - GRADING 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#964]
UNDER NEEDS ACTION - WE WOULD LIKE TO SEE THE 'PWCONSTRUCT PLAN MUST BE RELATED AS AN OTHER APPLICATION' SHOULD BE IN RED OR SOMETHING 

AP 240798

![image](https://user-images.githubusercontent.com/4129185/58187535-efab0280-7c84-11e9-9683-fc0cce4f08c4.png)

**Comment by ABonomo21** [comment]
Color cannot be changed.
