### ISSUE TITLE
IPS Pre Prod-Electrical License

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#965]
Associated with #963 License gets stuck in a renewal fee payment loop with the renewal review never generating-aw
![image](https://user-images.githubusercontent.com/47611580/58187564-fdf91e80-7c84-11e9-86a4-d2ac7d6fefa9.png)
![image](https://user-images.githubusercontent.com/47611580/58187591-09e4e080-7c85-11e9-9139-b505dd009af7.png)

the electric license renewal should generate the renewal review like the plumbing license did.
![image](https://user-images.githubusercontent.com/47611580/58187874-a313f700-7c85-11e9-997b-bc436a48d31c.png)

**Comment by calequin** [comment]
The electrical license E244390 is waiting for the licensee to pay fees in order for it to proceed to the renewal review milestone. Once in the renewal review milestone the county staff will receive a review to complete.

**Comment by ABonomo21** [comment]
paid the fee renewal review still did not populate-

![image](https://user-images.githubusercontent.com/47611580/60044949-83f7f300-9691-11e9-8f34-cdc91f309f59.png)

**Comment by calequin** [comment]
please retest with an ELEC and not ELECB.

**Comment by ABonomo21** [comment]
See issue #1262 We are unable to test the renewals for trade licenses until the in life mapping is complete for trade licenses-AW

**Comment by megisys** [comment]
Duplicate Ticket
