### ISSUE TITLE
R4C - GRADING

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#967]
PWCONSTRUCT  PLANNING NUMBER SHOULD BE REQUIRED OF THE APPLICANT AND GET CARRIED OVER TO IPS

#240798

![image](https://user-images.githubusercontent.com/4129185/58187881-a7d8ab00-7c85-11e9-9ee5-f73e592bb3fc.png)

**Comment by dhenry-KCI** [comment]
@megisys - what's the question?

**Comment by dhenry-KCI** [comment]
@megisys you added this as a question but didn't ask the question. Updating label for a response.

**Comment by megisys** [comment]
Not every grading will have a PWConstruct. You can turn it on sometimes and not othertimes. Intake person to search by address and link,

**Comment by ABonomo21** [comment]
I am pretty sure we previously went over what was and was not required at intake and when the PWCONSTRUCT will be required. I don't understand why this isn't able to work now...

tm 6/25/19

**Comment by dhenry-KCI** [comment]
During intake review permit tech will need to review if a valid pwconstruct AP exists for that address and associate. at this time, R4C, can't dynamically require fields.

Adding as a future enhancement
