### ISSUE TITLE
IPS Pre Prod- Trade License- Renewal Date 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#968]
Next renewal period did not populate 

![image](https://user-images.githubusercontent.com/47611580/58188524-bf646380-7c86-11e9-9467-8b1e78a81b13.png)

**Comment by ABonomo21** [comment]
I did a test and the last renewal dates are migrated. 
![image](https://user-images.githubusercontent.com/47611580/58190560-c8efca80-7c8a-11e9-9543-d69e799d18c4.png)

but not the next renewal date

**Comment by ABonomo21** [comment]
Also missing on Limited Lic conversion EL12

![image](https://user-images.githubusercontent.com/47611580/58198109-b3cf6780-7c9b-11e9-829f-e28ae8a1c450.png)

**Comment by JuanitaMiles** [comment]
The issue outlined above persists in TEST and PREPROD. Changing the label to 'Data Issue'.

**Comment by megisys** [comment]
Need to meet to discuss if this is an issue or not ?

Dan

**Comment by ABonomo21** [comment]
Dan to create a batch manager job to set next renewal date 45 dates less than the expiry date if the expiry date is int eh future

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/59448999-3b5c5200-8dd4-11e9-90cc-549818248474.png)

no fixed
