### ISSUE TITLE
IPS Pre Prod- Electrical Master converted as Limited 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#969]
A Master General electrical license in H7 converted over as an Electrical Limited License

![image](https://user-images.githubusercontent.com/47611580/58188663-02bed200-7c87-11e9-938f-2624bb6fd7d5.png)

![image](https://user-images.githubusercontent.com/47611580/58188780-3d286f00-7c87-11e9-9363-36a3589bc4e4.png)

**Comment by calequin** [comment]
issue has been fixed.
![image](https://user-images.githubusercontent.com/47603568/58583466-b260ea80-8219-11e9-9b00-2dd8d32d5325.png)

**Comment by ABonomo21** [comment]
fixed-aw
![image](https://user-images.githubusercontent.com/47611580/58968387-fc9b1c00-8783-11e9-93b0-2cff51ee4474.png)
