### ISSUE TITLE
Building - Alteration Permit /Minor Report- MIssing Building Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#97]
The system did not generate teh building fee assocoiated to the alteration permit.

AP237143
logged by M. Coffman 2/12

![alter_permit](https://user-images.githubusercontent.com/4129185/53142028-63dbea00-3560-11e9-8e16-ba67081092b7.png)

**Comment by imazlout** [comment]
@ABonomo21 What is the full name of the fee that is missing?
 I attached the spreadsheet of fees that I received from the county from H7 PROD (current) and I don't see a fee that looks for Work Type= "ALTER" and/or Construction Type of "REPR" as seen in the example permit tested. Is this a new fee, or should an existing fee be modified to add this information?

The one I see that fits is BUILDING FEE - ALTERATION/CONVERSION, but that only gets added if Construction Type = "ALTCONV"

[FC_AllModules_v7PRODFees_09142018.xlsx](https://github.com/kcigeospatial/Fred_Co_Land-Management/files/2891375/FC_AllModules_v7PRODFees_09142018.xlsx)

**Comment by dhenry-KCI** [comment]
@imazlout The type of fee that should have generated assocaited to this AP would be Building Minimum Fee.  In addition to Work Type = "Alter" and Construction TYpe = "REPR", the user also checked the minimum building fee.

**Comment by imazlout** [comment]
Ready for test.

Updated Building minimum fee formula to also add if worktype = ALTER and Construction Type = REPR
Test with AP 238436

<img width="960" alt="issue97" src="https://user-images.githubusercontent.com/47784290/53657032-02ccaa00-3c23-11e9-940a-2bff37a34a0a.png">

**Comment by dhenry-KCI** [comment]
![97 fixed](https://user-images.githubusercontent.com/4129185/53742452-a0fc8200-3e66-11e9-9274-45726b1b46d2.PNG)

Fixed on 3/4/19 - KVanaman
