### ISSUE TITLE
ips-preprod-water/sewer-amendment-duswm fee

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#970]
duswm fee should be 214

![image](https://user-images.githubusercontent.com/4129185/58188988-9b555200-7c87-11e9-93ab-f5d1253f9b05.png)

mw

**Comment by JuanitaMiles** [comment]
The DUSWME Plan Amendment Fee is also $207 on TEST applications. Removing the PreProd label as the issue persists in both environments.

![image](https://user-images.githubusercontent.com/31770504/58494345-e7e6d480-8142-11e9-9888-33e929481aa6.png)

**Comment by calequin** [comment]
fixed to 214

**Comment by mmbanong** [comment]
Checked and the fees look Ok. See screenshot

![image](https://user-images.githubusercontent.com/47392173/59513765-84221280-8e89-11e9-8a35-6739ec8efbe4.png)

**Comment by dhenry-KCI** [comment]
ok mw
