### ISSUE TITLE
IPS Pre Prod-Res Use Details Page-Section Compete

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#971]
There is no option to select any option for the Section Complete license.-AW
![image](https://user-images.githubusercontent.com/47611580/58189787-2256fa00-7c89-11e9-89c8-a795cf67d54b.png)
![image](https://user-images.githubusercontent.com/47611580/58189795-25ea8100-7c89-11e9-93de-7de4e540d09f.png)

**Comment by JuanitaMiles** [comment]
The issue outlined above persists in both TEST and PREPROD. Removing the PreProd label.

Currently the system pre-populates the Section Complete field (under the Garage Details section) on the ResUses Start Application Detail Page with 'Section Completed?'. This is not a valid value for this field, therefore, when you click on the search popup icon the system tries to search for a 'Section Completed?' value but does not return any results. To get the proper values, the user would have to click the Clear button, then the Search button. **This field should not pre-populate with any value to be consistent with the other Section Complete field on this details page.**  _(See below for TEST environment screenshots of this issue)_

![image](https://user-images.githubusercontent.com/31770504/58495525-bb808780-8145-11e9-86e0-d7fba0803f6f.png)

![image](https://user-images.githubusercontent.com/31770504/58495599-ea96f900-8145-11e9-94b9-16f0a3446e68.png)

**Comment by ABonomo21** [comment]
corrected- ab
