### ISSUE TITLE
ips-preprod-plat-wrong milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#972]
ap18827 is waiting for mylars to be submitting in V7.  In IPS it is in process application.  It should be in awaiting paperwork

![image](https://user-images.githubusercontent.com/4129185/58192992-01de6e00-7c90-11e9-9140-d2954a41e434.png)

![image](https://user-images.githubusercontent.com/4129185/58193055-29353b00-7c90-11e9-8b1d-25a1365c6edc.png)

MW

**Comment by megisys** [comment]
This step has not been completed.. This is on the to do list. @dhenry-KCI

**Comment by megisys** [comment]
Duplicate
