### ISSUE TITLE
ips-prepod-plat-wrong milestone

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#973]
this had one round of reviews completed.  should be in awaiting applicant resub milestone, not Process application

![image](https://user-images.githubusercontent.com/4129185/58193691-8f6e8d80-7c91-11e9-9c45-28f3e55e1e6d.png)

MW

**Comment by megisys** [comment]
In Life Processing to be run Tomorrow after Back Up

**Comment by megisys** [comment]
Old
