### ISSUE TITLE
ips-preprod-water/sewer-deferred hearing but stage progressed

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#974]
same problem we have had on and off for a while now.

![image](https://user-images.githubusercontent.com/4129185/58195359-c050c180-7c95-11e9-936c-6773043e8861.png)

MW

**Comment by megisys** [comment]
Can you please test this exactly the same in test. I dont think this is a migration issue

**Comment by JuanitaMiles** [comment]
I've replicated this application and tested in TEST. The issue exists in TEST as well. _(See screenshot below of TEST environment)_ Removing PreProd and Ready for Retest labels. Adding Bug label.

![image](https://user-images.githubusercontent.com/31770504/58496482-fdaac880-8147-11e9-8f4a-dabd499a7534.png)

**Comment by megisys** [comment]
This is a slightly different USE Case.. IF the first Review is Deferred is it likely the last review would be approved. I fixed this as we can have multiple combinations

**Comment by megisys** [comment]
Mike Please test this in test and Mark as Ready to Deploy if happy
Martin Formula is PLN_MultiHearing_ReviewResult

**Comment by dhenry-KCI** [comment]
fixed!

![image](https://user-images.githubusercontent.com/4129185/59704356-ea7c9d00-91c9-11e9-83ba-7d1d85c55a2f.png)


MW
