### ISSUE TITLE
IPS- Pre_Prod Address

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#976]
Addresses marked as delete should have been removed and/or expired  during the migration.

I was able to create a permit on a deleted address in IPS. They should not be usable or available in R4C.

![image](https://user-images.githubusercontent.com/47611580/58196120-94ced680-7c97-11e9-931d-ba5bb694925d.png)

5/22/19 EP

**Comment by megisys** [comment]
Addresses are now expired

**Comment by ABonomo21** [comment]
The deleted address is still available in the type ahead, but it is done from the address popup.-AW
![image](https://user-images.githubusercontent.com/47611580/58967885-0708e600-8783-11e9-91e4-7077cefd81cf.png)
![image](https://user-images.githubusercontent.com/47611580/58967895-0e2ff400-8783-11e9-9652-8058534313e2.png)

**Comment by megisys** [comment]
Updated

**Comment by ABonomo21** [comment]
still view able 

![image](https://user-images.githubusercontent.com/47611580/59105226-83c1ce80-8901-11e9-8a5d-e3052ca4f88e.png)

However, all addresses with deleted in them should not display during the search for a site

**Comment by megisys** [comment]
Duplicate
