### ISSUE TITLE
Building - Resuse Acceossry - Pool

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#98]
System incorrectly generated a DUSWM review for a pool permit.

AP237160
Logged by M. Cofffman

![pool](https://user-images.githubusercontent.com/4129185/53142266-45c2b980-3561-11e9-80be-70ecd36e69b4.png)

**Comment by imazlout** [comment]
Duplicate of #36

**Comment by dhenry-KCI** [comment]
Confirmed closed
