### ISSUE TITLE
ips-preprod-FRO due date

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#980]
due date on second review should be 2 weeks, not 3 weeks

![image](https://user-images.githubusercontent.com/4129185/58197314-f6904000-7c99-11e9-9dbe-2a07055262ba.png)

MW

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/58588296-f4dbf480-8224-11e9-9e12-edaa9c7a35e2.png)

**Comment by dhenry-KCI** [comment]
first review needs to be 3 weeks.  Second review two weeks.  You got the second review correct but now need to make the 1st review 3 weeks again.

![image](https://user-images.githubusercontent.com/4129185/58963626-88f51100-877b-11e9-8e10-74f74b85b304.png)


MW

**Comment by megisys** [comment]
PLEASE TEST IN TEST and mark as Ready to Deploy if happy

**Comment by dhenry-KCI** [comment]
Fixed in TEST F244573
