### ISSUE TITLE
IPS- Pre Prod Plumbing License Inactive Status

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#981]
PI00521 is marked as inactive- however it is showing as ACTIVE. 

![image](https://user-images.githubusercontent.com/47611580/58197429-42db8000-7c9a-11e9-87d9-354e4300c06c.png)

5/22/19 EP

**Comment by dhenry-KCI** [comment]
See issue #982 and #4

**Comment by megisys** [comment]
If inactive or Expired clean up with Batch Manager

**Comment by ABonomo21** [comment]
inactive now
