### ISSUE TITLE
IPS- Pre Prod- Electrical License Inactive 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#982]
Electrical License showing active when it is marked inactive 

![image](https://user-images.githubusercontent.com/47611580/58197603-9c43af00-7c9a-11e9-9e6f-d0f6a08f4ddc.png)

**Comment by dhenry-KCI** [comment]
Similar to github issue #4 - Make sure the two status' match  but we need the process date to remain the same.

**Comment by megisys** [comment]
Not cleaned up in Hansen 7 ?

**Comment by dhenry-KCI** [comment]
Inactive Date field and checkbox marked and has valid expiration date. Additional comments state license is inactive. H7 does not have secondary field to track status - license is inactive.

**Comment by megisys** [comment]
Need batch Manager Task Completed

**Comment by megisys** [comment]
This was completed
