### ISSUE TITLE
IPS Pre Prod-Plumbing-Condition automatically added "Not Fees"

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#984]
I paid the fees on this plumbing permit #245587 and then a condition automatically generated for "Not Fees" and my permit is at "Pending Issuance" I don't know what this means???-AW 
![image](https://user-images.githubusercontent.com/47611580/58198103-afa34a00-7c9b-11e9-8034-b135592ea673.png)

this also happened on #245588-i have no clue why??? (I approved this one just to be able to move forward with my permit)
![image](https://user-images.githubusercontent.com/47611580/58198536-6f909700-7c9c-11e9-8522-46a6cc7025a6.png)

**Comment by megisys** [comment]
It is simply saying a Notification was sent to applicant. Should not appear

**Comment by ABonomo21** [comment]
Then that description needs to be more clear.

**Comment by ABonomo21** [comment]
Additionally- Why would this be "notification"  being sent be a condition, shouldn't it be a log?

**Comment by dhenry-KCI** [comment]
@megisys - this issue working in IPS test and NOT working in PrePROD

**Comment by megisys** [comment]
No that is not how our system works.. Logs dont auto add on entry to a Milestone. Conditions do.. The condition is set to not show. I will fix that piece.

Dan

**Comment by ABonomo21** [comment]
corrected
