### ISSUE TITLE
IPS PreProd - Planning - NID - Resubmittal Comments

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#985]
NID Application is not requiring comments when resulting the NID Review type with RESUBMIT. Resubmittals should require comments.

![image](https://user-images.githubusercontent.com/31770504/58198206-d2356300-7c9b-11e9-996a-3f2d3e71b0e8.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/58264301-9fe33e80-7d4b-11e9-8f20-1684ad1a407a.png)

SEE TEST

**Comment by dhenry-KCI** [comment]
ok per N244563

MW
