### ISSUE TITLE
IPS Pre Prod-Conditions Approval options

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#986]
Conditions should only have the "Yes" option for approvals-AW
![image](https://user-images.githubusercontent.com/47611580/58198704-dca42c80-7c9c-11e9-83c3-f28c48d7aee0.png)

**Comment by megisys** [comment]
What Condition i s this please ?

**Comment by ABonomo21** [comment]
It is for any conditions placed on any module.

**Comment by megisys** [comment]
I addressed this

**Comment by dhenry-KCI** [comment]
Confirmed fixed in preprod
