### ISSUE TITLE
IPS Pre Prod-Res Use- Bldg permits not being held up for trade permits finalization

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#987]
My Bldg permit #245585 passed its final inspection and does not have any notes on the check status that the child permits must be closed out prior to bldg. finalization-AW 
![image](https://user-images.githubusercontent.com/47611580/58199028-9ef3d380-7c9d-11e9-95d0-81e3d560dfae.png)
![image](https://user-images.githubusercontent.com/47611580/58199060-adda8600-7c9d-11e9-966b-f79e3b657f06.png)
![image](https://user-images.githubusercontent.com/47611580/58199084-b7fc8480-7c9d-11e9-9150-ba12581045e7.png)

**Comment by dhenry-KCI** [comment]
User needs to schedule the inspection for the building permit to be help up by trades.
