### ISSUE TITLE
IPS - License Migration (Plumbing & Electrical)

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#988]
The check box for "was copy of drivers license taken" is missing.

![image](https://user-images.githubusercontent.com/47611580/58199567-c13a2100-7c9e-11e9-9b9d-a1550c12a148.png)

Hansen

![image](https://user-images.githubusercontent.com/47611580/58199593-ce571000-7c9e-11e9-9471-603981d148f4.png)

5/22/19 EP

**Comment by megisys** [comment]
We removed this along time ago as we are not doing that anymore

**Comment by dhenry-KCI** [comment]
For Existing Licenses - details from H7 should convert to IPS. (missing copy of driver's license taken)

**Comment by megisys** [comment]
The County said they didn't want to display this as it had no value.. It is this way in TEST. Do you want to add it back in Test ?

**Comment by megisys** [comment]
Added back to view for Historic Entry.. Disabled for future use and Show in Portal = False

**Comment by ABonomo21** [comment]
corrected
