### ISSUE TITLE
IPS Pre Prod-Distributor License Detail Pages

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#989]
The Detail page was not available to input information until after the application was saved. We need to input this information before the application is saved and given a license number-AW
![image](https://user-images.githubusercontent.com/47611580/58199804-4c1b1b80-7c9f-11e9-99ed-996b0333d512.png)

![image](https://user-images.githubusercontent.com/47611580/58199760-39a0e200-7c9f-11e9-8f9f-ee4bdf256d67.png)

**Comment by calequin** [comment]
fixed. added distributor detail to show up in back office at start of application

**Comment by ABonomo21** [comment]
corrected - ab
