### ISSUE TITLE
Building - Resuse - Pool Child Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#99]
System should not issue a pool permit without the required electrical permit being attached. 

Ibto can you confirm that this will either be a checkbox marked by the tech during completeness check or an automatic add by the system.

AP237160
Logged  M. Coffman

![pool2](https://user-images.githubusercontent.com/4129185/53142339-8589a100-3561-11e9-854a-462682711f33.png)

**Comment by imazlout** [comment]
On Resuses applications, If electrical permit is needed, then the user need to make sure the Additional Electrical checkbox is checked on the Residential Detail Page. That will stop the permit on Inspections milestone until user attaches an electrical permit as a related record.

Once attached and Resuses Application moves from Inspections to Final Inspection milestone, the user will schedule the final inspection. If the electrical permit still isn't finalizes, the user will encounter an error upon scheduling the final inspection.

**Comment by ABonomo21** [comment]
The additional electric box was checked and yet the permit still issued. Pool permits can not be issued until the electrical permit has been applied for & attached. They should go into a "Pre-Issue Permit" stage.-AW

![image](https://user-images.githubusercontent.com/47611580/54826371-16998800-4c86-11e9-9485-8658e0c4c9d3.png)

![image](https://user-images.githubusercontent.com/47611580/54826624-8740a480-4c86-11e9-90f5-7a55e7dc6c5c.png)

**Comment by goggansd** [comment]
Please look at RESUSES permit # 240071 in the IPSTest environment. I copied the 239008 using the Group Add feature (but excluded copying parent/child/related applications). When I got to the point in the workflow where it reached Pending Issuance, there was no ELECPERM application attached as a child permit, so I got the status check shown below:

![image](https://user-images.githubusercontent.com/28841997/55163964-23fcb980-5141-11e9-9000-ac4e6eeaccdd.png)

**Comment by ABonomo21** [comment]
per @ABonomo21 okay to close-AW
