### ISSUE TITLE
IPS Pre Prod- Distributor License Details Page Unable to click

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#990]
I can not click on anything other than the "proof of business" on the detail page-AW
![image](https://user-images.githubusercontent.com/47611580/58199961-a0260000-7c9f-11e9-99f3-3f19ca38d590.png)

**Comment by dhenry-KCI** [comment]
@megisys - See issue #436- we need ability to add / edit the hours of operation. This was addressed and closed on April 5th.

**Comment by calequin** [comment]
fixed hour of operation detail. Removed group area and added a new group area.

**Comment by ABonomo21** [comment]
Confirmed correct I was modify the details in the grids
