### ISSUE TITLE
IPS - Reporting Issue

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#991]
Printed a plumbing license card PU00007 for James Voltz

Last name prints in all Caps, but first name prints correctly.

![image](https://user-images.githubusercontent.com/47611580/58200175-23475600-7ca0-11e9-867a-fe1af8f61b69.png)

5/22/19 EP

**Comment by dhenry-KCI** [comment]
@TaraF -reminder for this issue.

**Comment by dhenry-KCI** [comment]
closing - logged with reporting
