### ISSUE TITLE
IPS- Number of Attachments - License

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#992]
The number of PDF attachments didnt migrate over.

There are 7 files attached in hansen and only 6 files transferred to IPS. 

![image](https://user-images.githubusercontent.com/47611580/58200328-9355dc00-7ca0-11e9-95b0-43afcd40bcc1.png)

Hansen
![image](https://user-images.githubusercontent.com/47611580/58200365-a5d01580-7ca0-11e9-8152-370300243551.png)

license PU00007

5/22/19 EP

**Comment by megisys** [comment]
Meeting Agreed to ignoe these files types
