### ISSUE TITLE
IPS Pre Prod-Bldg permit closed with child permits still open

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#993]
My building permit #245589 closed and finalized with the child permit still open.-AW
![image](https://user-images.githubusercontent.com/47611580/58200794-a6b57700-7ca1-11e9-9c7a-c5cffff52b38.png)

**Comment by imazlout** [comment]
Ready for test

**Comment by ABonomo21** [comment]
Inspections must be scheduled to stop progression
