### ISSUE TITLE
IPS PreProd - Planning - BOA - Water/Sewer Details

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#994]
On the BOA - FLDANAREA. Currently being stopped to enter Water and Sewer details at the Under Review milestone. These details should be required to be entered at Completeness Check milestone.

![image](https://user-images.githubusercontent.com/31770504/58200555-07907f80-7ca1-11e9-8968-1e5dd372d2d5.png)

**Comment by calequin** [comment]
fixed. added to completeness check as a status check

**Comment by dhenry-KCI** [comment]
Fixed per AP 244540, AM & GH
