### ISSUE TITLE
IPS Pre Prod-  Log Entry

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#995]
Log Entry Clean up was not completed- not completed in H7 yet however, a list was provided to IIT to clean up 
![image](https://user-images.githubusercontent.com/47611580/58201059-2ba09080-7ca2-11e9-8659-94d19e20db86.png)

**Comment by dhenry-KCI** [comment]
@mmbanong - we will need to re-engage Jeff W.

**Comment by dhenry-KCI** [comment]
Closing ticket and will follow-up during go-live.
