### ISSUE TITLE
ips-preprod-preliminary-details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#996]
Subdivision code didnt migrate.

Acres field in V7 populating as sqft  in Prepod.

![image](https://user-images.githubusercontent.com/4129185/58261512-6e1ba900-7d46-11e9-811a-bfa8b09a7186.png)

![image](https://user-images.githubusercontent.com/4129185/58261539-7d9af200-7d46-11e9-890e-1cccc34b5236.png)

MW

**Comment by dhenry-KCI** [comment]
historic y/n didnt populate in PreProd
![image](https://user-images.githubusercontent.com/4129185/58261740-e71b0080-7d46-11e9-83a3-93ed2b6311c5.png)

![image](https://user-images.githubusercontent.com/4129185/58261782-f9953a00-7d46-11e9-8495-cf43ef3468a3.png)

**Comment by JuanitaMiles** [comment]
These data issues persist in both TEST and PREPROD. Changing the label to 'Data Issue' only. _(See screenshots of the same application in TEST below)_

![image](https://user-images.githubusercontent.com/31770504/58498640-74e25b80-814c-11e9-84a3-41fbfd6fd369.png)

![image](https://user-images.githubusercontent.com/31770504/58498711-9b07fb80-814c-11e9-83a7-8f6deb0538b8.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58967022-5cdc8e80-8781-11e9-8bf5-c17e35985691.png)

FIXED - Data Migration Issue - KEV
