### ISSUE TITLE
IPS - New Trade License - Driver's License

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#997]
For New licenses ONLY - need updated detail pages designed in IPS 11, but should also include checkmark for Was copy of Driver's License Submitted (back office only). 

This is not a configuration migration issue as this bug existed in IPS test as well.

**Comment by megisys** [comment]
This is just a check mark added back and made Read Only

**Comment by calequin** [comment]
added the checkbox on the universal trade license details page.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58963360-00767080-877b-11e9-8841-25d60e5e37fa.png)

![image](https://user-images.githubusercontent.com/47611580/58963408-13894080-877b-11e9-8c64-8396af7a0106.png)

Drivers license submitted check box added
