### ISSUE TITLE
ips-preprod-planning-plat-missing details

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#998]
details from V7 did not transfer to preprod
![image](https://user-images.githubusercontent.com/4129185/58263980-116ebd00-7d4b-11e9-872c-17beeabc2576.png)

![image](https://user-images.githubusercontent.com/4129185/58264046-29464100-7d4b-11e9-84b8-f5bf732b7eb2.png)

MW

**Comment by dhenry-KCI** [comment]
tested another (1204) with same result.  assume this is across all plat work types.

MW

**Comment by JuanitaMiles** [comment]
These Data Issues persist in both TEST and PREPROD for both of Mike's AP examples. _(See screenshot from TEST environment below)_. Changing the labels to 'Data Issue' only.

![image](https://user-images.githubusercontent.com/31770504/58499103-706a7280-814d-11e9-90af-7ef7b49e7c93.png)

![image](https://user-images.githubusercontent.com/31770504/58499152-8415d900-814d-11e9-996b-bdeb3da20248.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/58966741-da53cf00-8780-11e9-864e-9b6ed7a00e86.png)

FIXED - Migration AP # 1112
