### ISSUE TITLE
ips-preprod-planning-plat-addition

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#999]
in preprod the mylar review fee of $58 is required to be paid on before the 2nd review cycle.  It should not generate until all agencies are approved and we hit the awaiting paperwork milestone at the end (ie mylar review phase).
![image](https://user-images.githubusercontent.com/4129185/58266211-3c5b1000-7d4f-11e9-8994-2f715cce8c23.png)

Created duplicate AP in test.  Denied EH just like I did in preprod, but it went straight to finalized!
![image](https://user-images.githubusercontent.com/4129185/58266233-47ae3b80-7d4f-11e9-9306-d93ca89f1e52.png)

MW

**Comment by megisys** [comment]
DENIED is not a review option anymore.. We talked about this.. one Review agency shouldn't DENY. They should contact you , so you can get on the front foot. This is an issue in Test and PreProd.

**Comment by dhenry-KCI** [comment]
all ok per PL244574

MW
